### ISSUE TITLE
Incorrect output of HELP on objects

### ISSUE THREAD

**Issue by endo64** [red/red#1001]
"?" on objects doesn't show the correct datatypes of object fields, it shows "datatype!" instead:

    red>> o: context [a: 1 b: "x"]
    red>> ? o
    `o` is an object! of value:
         a                datatype! 1
         b                datatype! x

**Comment by dockimbel** [comment]
Should have been in the commit log, posting here for the record: now `words-of` returns a block of words bound to the object's context.

**Comment by Kaj-de-Vos** [comment]
You can rewrite Git history.
