### ISSUE TITLE
Can not build curses examples

### ISSUE THREAD

**Issue by bitbegin** [red/red#1019]
λ red-26jan15-3d48d15.exe system\library\curses\examples\curses-example.reds
Pre-compiling Red console...
*** Script error: invalid function definition: compare
*** Where: make-hexa

**Comment by dockimbel** [comment]
By default, the `red` binary will try to run directly the argument script using the interpreter. Red/System code cannot be run by the interpreter that would require a JIT-compiler that will only come in Red 2.0 ;-).

In order to compile the argument script, you just need to use the `-c` option.

**Comment by bitbegin** [comment]
λ ared-26jan15-3d48d15.exe system/library/curses/examples/curses-example.reds -c
Pre-compiling Red console...
*** Script error: invalid function definition: compare
*** Where: make-hexa

**Comment by dockimbel** [comment]
Options come first, see the [README](https://github.com/red/red) or just type `red -h` on command line to see the command-line syntax.

So, it should be:
```
red-26jan15-3d48d15.exe -c system/library/curses/examples/curses-example.reds
```

**Comment by bitbegin** [comment]
λ red-26jan15-3d48d15.exe -c system/library/curses/examples/curses-example.reds

-=== Red Compiler 0.5.0 ===-

Compiling /E/work/github/red/system/library/curses/examples/curses-example.reds ...

Compiling to native code...
*** Syntax Error: Missing matching ]
*** line: 371
*** at: "[^/ #L 30 ^-;-----------------------------"

**Comment by bitbegin** [comment]
λ red--26jan15-3d48d15.exe -c system/library/curses/examples/panel-example.reds

-=== Red Compiler 0.5.0 ===-

Compiling /E/work/github/red/system/library/curses/examples/panel-example.reds ...

Compiling to native code...
*** Syntax Error: Missing matching ]
*** line: 40
*** at: {[
 #L 31 ^-wid: 0
 #L 32 ^-;--------------}

**Comment by dockimbel** [comment]
No luck, it seems we have a regression on that library...looking at it...

**Comment by dockimbel** [comment]
Issue fixed. You can now compile the curses example and run it if you have the [pdcurses](http://gnuwin32.sourceforge.net/packages/pdcurses.htm) library installed.

**Comment by bitbegin** [comment]
![panel-example](https://cloud.githubusercontent.com/assets/4469745/5902860/0f51bdb0-a5b9-11e4-8b8d-b0182a15c50e.PNG)

1. Not Support unicode?

2. λ red-26jan15-48c5719.exe -c system/library/curses/examples/curses-example.reds

-=== Red Compiler 0.5.0 ===-

Compiling /E/work/github/red/system/library/curses/examples/curses-example.reds ...

Compiling to native code...
*** Syntax Error: Missing matching ]
*** line: 371
*** at: "[^/ #L 30 ^-;-----------------------------"

**Comment by dockimbel** [comment]
Issue fixed. 

For the display, I am not sure if pdcurses support Unicode. Anyway, it's possible to make it work by switching to a US codepage using `chcp 437`, then you can switch back to Chinese simplified using `chcp 936`.

**Comment by qtxie** [comment]
@bitbegin I'm using `pdc32dllw.zip` from here: http://sourceforge.net/projects/pdcurses/files/pdcurses/3.4/
It works. :)
```
  ┌─ Window 1 ───────────────────────────────
  │ T┌─ Window 2 ─────────────────────────────
  │  │ T┌─ Window 3 ───────────────────────────
  │ T│  │ T┌─ Window 4 ─────────────────────────
  │ U│ T│  │ T┌─ Window 5 ───────────────────────
  │ U│ U│ T│  │ The Red/System panel Show                           │
  │  │ U│ U│ T│                                                     │
  │ C│  │ U│ U│ Tab to browse through windows                       │
  └──│ C│  │ U│ Use arrow keys to move                              │
     └──│ C│  │ Use Ctrl+arrow keys to resize                       │
        └──│ C│                                                     │
           └──│ Ctrl+Q to exit                                      │
              └───────────────────────────────
```
