### ISSUE TITLE
Feature Request: Blocks as Keys

### ISSUE THREAD

**Issue by JacobGood1** [red/red#1024]
Since strings can be used as keys and they are mutable could we also have blocks as keys?

m: map [[1 2] [3 4]]
m/[1 2] => [3 4]

**Comment by PeterWAWood** [comment]
Work has yet to start of the map! datatype.

Please could you make a proposal on the [wiki] (https://github.com/red/red/wiki) for this feature.

**Comment by dockimbel** [comment]
You already can use block as keys, but the syntactic form you are asking for is not planned to be supported. Also as Peter pointed out, there is no `map` in Red yet.
```
red>> blk: [[1 2][3 4]]
== [[1 2] [3 4]]
red>> select/only blk [1 2]
== [3 4]
```
