### ISSUE TITLE
red-series! definition in %structures.reds may need to be reviewed 

### ISSUE THREAD

**Issue by meijeru** [red/red#1026]
With the support for typesets, the red-series! definition in %structures.reds becomes more than a convenience: it now documents what the representations of all types included in series! have in common. Serveral of these types have a use for the fourth field (cache pointer for strings/files /urls, element type ID for the new vectors). Thus the field name `_pad` for this fourth field is now perhaps misleading. What about `extra` ?

**Comment by dockimbel** [comment]
Preliminary remark: `red-block!` and derivatives have no extra field, it's just a padding. 

As you point out rightly, red-series! represents what is common to all series! types, that common part is just the `head` and `node` fields. Some series! use an additional field, but that extra field is not part of what constitutes a series!.

**Comment by meijeru** [comment]
OK, so `_pad` does not mean 'empty/unused' but 'irrelevant'.

**Comment by dockimbel** [comment]
Could be interpreted like that yes.
