### ISSUE TITLE
red-16feb15-d3a1ccb.exe crashed

### ISSUE THREAD

**Issue by bitbegin** [red/red#1038]
log:
** Script Error: Not enough memory
** Near: script: decapsulate
if none? script

**Comment by qtxie** [comment]
@bitbegin I can not reproduce it. It works well on my Win 7 64bit.

**Comment by bitbegin** [comment]
My PC also is Win7 64bit. But there isn't more information.
How can I do to help you with this issue?

**Comment by qtxie** [comment]
@bitbegin You would delete the old console in here: `"C:\ProgramData\Red\console.exe"`, then try again with administrator permission.

**Comment by dockimbel** [comment]
@bitbegin I cannot reproduce it either. The only reason I could see about such error is a corrupted binary, that could result from a download issue or an anti-virus silently modifying the binary.

Can you reproduce that issue with newer binaries?

**Comment by bitbegin** [comment]
@dockimbel  red-24feb15-3d15e1d.exe can be used normally. It was a download issue.

**Comment by dockimbel** [comment]
Thank your for the reply. Closing this ticket now.
