### ISSUE TITLE
Don't use multiple assignment on multiple lines

### ISSUE THREAD

**Issue by iArnold** [red/red#1045]
gvalue1:
gvalue2:
gvalue3: false

a: func [
/value1
/value2
/value3
][
gvalue1: value1
gvalue2: value2
gvalue3: value3
]
a
Now the program crashes because the gvalue's 1 and 2 were not set to false.

**Comment by iArnold** [comment]
Oh forgot to say that change it to
gvalue1: false
gvalue2: false
gvalue3: false 
and it works ok. (I did not check gvalue1: gvalue2: gvalue3: false on 1 line but I am rather convinced that that should work too).

**Comment by dockimbel** [comment]
Tested with compiler:
```
Red []

gvalue1:
gvalue2:
gvalue3: false

a: func [
	/value1
	/value2
	/value3
][
	gvalue1: value1
	gvalue2: value2
	gvalue3: value3
]
a
```
No errors.

Tested with interpreter:
```
Red []

do [
	gvalue1:
	gvalue2:
	gvalue3: false

	a: func [
		/value1
		/value2
		/value3
	][
		gvalue1: value1
		gvalue2: value2
		gvalue3: value3
	]
	a
]
```
No errors.

**Comment by iArnold** [comment]
Parhaps this issue had to do with the fact I discovered that I can not compile the same program twice in the same Rebol Console. (First time ok generating exe, then second directly after generating some ts___ error. Hope your fix earlier today handles this fenomena.

**Comment by dockimbel** [comment]
The compiler was keeping some data related to type-checking in an internal cache that was not cleaned up a for new compilation.

**Comment by iArnold** [comment]
It could have been that I compiled the program with this code after having compiled some other program, in fact using a dirty Rebol console, leading me to think this was an issue too. But it is working ok now, so all ready for the new release here!
