### ISSUE TITLE
In the spec part of a FUNC, putting a /LOCAL without anything following will cause a Red Compiler Internal Error

### ISSUE THREAD

**Issue by JerryTsai** [red/red#1050]
add: func [ a b /local ] [ a + b ]

*** Red Compiler Internal Error: Script Error : Expected one of: word! - not: none! 
*** Where: check-spec 
*** Near:  [append symbols to word! pos/1]

**Comment by iArnold** [comment]
I "reported" this too on 23 febr in Red group. http://chat.stackoverflow.com/transcript/50258?m=21719837#21719837
