### ISSUE TITLE
WORDS-OF shows a wrong result.

### ISSUE THREAD

**Issue by JerryTsai** [red/red#1051]
book: object [
    title: none
    author: none
    list-fields: does [
        words-of self
    ]
]
print book/list-fields

; The result is:
; none none title author list-fields

**Comment by qtxie** [comment]
It is the same as in R3:
```
>> book: object [title: none author: none list-fields: does [words-of self]]
>> print book/list-fields
none none title author list-fields
```
`words-of book` will return a block `[title author list-fields]`. Since PRINT will evaluate the words in a block, so the result is OK I think.

**Comment by JerryTsai** [comment]
I think qtxie is right. It's not a bug.

**Comment by dockimbel** [comment]
Indeed, closing the ticket.

@PeterWAWood Please delete the corresponding unit test.

**Comment by PeterWAWood** [comment]
@dockimbel I believe that the tests are valid (though perhaps I have made a mistake).The tests do not evaluate the block returned by words-of only compare it with the expected block

**Comment by PeterWAWood** [comment]
@dockimbel I have corrected two mistakes in words-of-test.red. The tests now pass.
