### ISSUE TITLE
ROUTINE cannot be put inside a context.

### ISSUE THREAD

**Issue by JerryTsai** [red/red#1055]
After compile the following code:

``` Red
Red [
]

my-context: context [
    do-something: routine [ 
        num     [integer!] 
        return: [integer!]
        /local
        ret
    ] [
        ret: num + 1
        ret
    ]
]

print my-context/do-something 1
```

I got this:

``` Red
*** Red Compiler Internal Error: Script Error : process-routine-calls expected obj argument of type: object 
*** Where: comp-routine 
*** Near:  [process-routine-calls body ctx/1 spec select] 
```

**Comment by dockimbel** [comment]
Routines are not yet fully supported in objects, but that code example should have worked fine, so it deserved a fix.

Dynamic calls with routines in objects don't work yet, for example the following code pattern is not supported yet:
```
foo: func [o [object!]][
    o/do-something 1
]
```

**Comment by hiiamboris** [comment]
This reports `1` when compiled with `-c`/`-r` but reports an error with `-e` added:
```
*** Script Error: cannot access do-something in path my-context/do-something
*** Where: print
*** Stack:
```

**Comment by greggirwin** [comment]
@hiiamboris this seems a wider issue, which would affect any code that prevents routines from being compiled. May be something we just need to doc as a limitation. If the compiler can catch these and give helpful error messages, that would be great, but doesn't seem like a high priority. Good tooling and code analysis exercise though.

**Comment by hiiamboris** [comment]
@greggirwin I would agree if it was a compiler limitation. This time it is _interpreter limitation_, while compiler does just fine.

**Comment by greggirwin** [comment]
How can it be solved? Routines have to be compiled, so the interpreter can never handle them. All it can do is provide a nicer error message.

**Comment by hiiamboris** [comment]
@greggirwin There may be a little misunderstanding here. Indeed it cannot work in the interpreter itself. However it should work in the encapping mode. Why not? I can't really say if it's the compiler who doesn't properly detect routines inside a context, or if it's the interpreter who can't properly call these routines.

But my line of thinking is this. `-e` option is described in the help message as "... Avoids compiler issues. Required for some dynamic code." If I get things right, `-c` may fail sometimes, but `-e` should never. In this scenario it's the opposite. `-c` works, but `-e` doesn't.

**Comment by greggirwin** [comment]
Thanks for clarifying. What needs to be improved is the description for encapping. In encap mode, *no* user code should be compiled, so you encap is incompatible with R/S in any form.

**Comment by hiiamboris** [comment]
You sure? So far encapping always worked for me. Compiled the R/S stuff I mean. Except this one case.

**Comment by greggirwin** [comment]
I could be wrong. There are checks for `routine` and for straight R/S files, so this is likely a compiler limitation, as you suggest. See `encap-preprocess` in %compiler.r.

**Comment by hiiamboris** [comment]
It's up to @dockimbel to sort this out, but I'm going to leave some more specific info.

In encapping mode the compiled object (even if the word `object` is used instead of `context`) does not contain the routines (I've added the `?? my-context` line to the original snippet before `print`):
```
root size: 2172, root max: 4142, cycles: 0
root size: 2172, root max: 4142, cycles: 1
root size: 2172, root max: 4142, cycles: 2
my-context: make object! []         ;)  <-- note this is empty

*** Runtime Error 1: access violation
*** in file: /D/devel/red/red-src/red/datatypes/object.reds
*** at line: 97
***
***   stack: red/object/rs-select 02ACD364h 038DDBC8h
***   stack: red/error/reduce 02ACD384h 02ACD364h
***   stack: red/error/form 02ACD364h 02ACD374h 02ACD354h -18
***   stack: red/actions/form 02ACD364h 02ACD374h 02ACD354h 0
***   stack: red/actions/form* -1
***   stack: red/natives/prin* false
***   stack: red/natives/print* false
***   stack: red/stack/throw-error 02ACD394h
***   stack: red/fire 0 0018FCC4h
***   stack: red/object/eval-path 02BD2E34h 02C7C634h 00000000h 02C7C5CCh false
***   stack: red/actions/eval-path 02BD2E34h 02C7C634h 00000000h 02C7C5CCh false
***   stack: red/interpreter/eval-path 02C7C634h 02C7C5DCh 02C7C5ECh false false true false
***   stack: red/interpreter/eval-expression 02C7C5DCh 02C7C5ECh false true false
***   stack: red/interpreter/eval-arguments 02BD0494h 02C7C5CCh 02C7C5ECh 00000000h 00000000h
***   stack: red/interpreter/eval-code 02BD0494h 02C7C5CCh 02C7C5ECh false 00000000h 00000000h 02BD0494h
***   stack: red/interpreter/eval-expression 02C7C5CCh 02C7C5ECh false false false
***   stack: red/interpreter/eval 02ACD364h true
***   stack: red/natives/do* true -1 -1 -1
```
The output shows that the error happens when `object/eval-path` is called with a word that the object does not contain, so it `fire`s: https://github.com/red/red/blob/8d712e4ba1b16e1b7a339006d1154aebc9cb7ce4/runtime/datatypes/object.reds#L1158

The routine itself is bound to the system/words, as it works (in `-e` mode only) if the last line is replaced by `print do-something 1` (removing the context name prefix)

**Comment by dockimbel** [comment]
Encapped mode does not compile Red code, therefore the compiler cannot identify Red "contexts". Routines can be compiled in Encapped mode only if they are in the global space and not nested, as contexts cannot be identified in such mode.
