### ISSUE TITLE
HELP without an argument throws an error

### ISSUE THREAD

**Issue by rebolek** [red/red#1063]
I just downloaded latest Red 0.5.1. After compilation I get this message:

    --== Red 0.5.1 ==-- 
    Type HELP for starting information. 

So I did exactly that and it returns an error:

    red>> help
    *** Script error: help is missing its word argument
    *** Where: help

**Comment by dockimbel** [comment]
Thanks for reporting it... Annoying regression caused by too aggressive argument type-checking.
