### ISSUE TITLE
typeset! implementation not complete

### ISSUE THREAD

**Issue by meijeru** [red/red#1065]
The 0.5.1 announcement says:

    The following actions are supported on typeset! values:
    make, form, mold, and, or, xor, complement, clear, find, insert, append, length?

However, this is not (yet) true for the "series" actions `clear, find, insert, append, length?`
They yield errors such as

    *** Script error: clear does not allow typeset for its series argument
    *** Where: clear

**Comment by meijeru** [comment]
I think I found the mistake: the corresponding action definitions in `%environment/actions.red` do not allow for a `typeset!`argument.

**Comment by dockimbel** [comment]
Good catch!

**Comment by meijeru** [comment]
Empty typesets are probably not very useful, and since typesets are not sequences, `insert` and `append` actually have the same effect, which by the way could also be achieved by `or`. I see that `length?` tests the number of types in the set, and that is a useful thing, although it is not exactly what one thinks of for `length?`. Again this is because a set is not a sequence...

**Comment by meijeru** [comment]
I accept that you have now removed some actions, but `find` remains. That means, you still have to change `%environment/actions.red` also, as per my earlier comment!

**Comment by dockimbel** [comment]
Thanks for the reminder, forgot about it.

**Comment by meijeru** [comment]
I see that `find` in `%environment/actions.red` now has the right arguments, but when looking at the description of the function, it occurred to me that it works in fact differently for series on the one hand, and objects, bitsets and typesets on the other, yielding a truth value in the latter cases - with probably none of the refinements making any sense there. One has to document this somewhere, or does it merit a separate function, you think?
