### ISSUE TITLE
Type HELP for more information

### ISSUE THREAD

**Issue by iArnold** [red/red#1066]
Pre-compiling Red console...
--== Red 0.5.1 ==--
Type HELP for starting information.

red>> help
*** Script error: help is missing its word argument
*** Where: help
red>> HELP
*** Script error: HELP is missing its word argument
*** Where: ???

**Comment by rebolek** [comment]
See https://github.com/red/red/issues/1063

**Comment by iArnold** [comment]
Still it is really a pity this was *not* included in the released version today. Now this very basic error will be in the release version the entire period and so *every* newcomer will experience this, there are very few newcomers that will select to download the daily build over the one supported by the big download button.

**Comment by dockimbel** [comment]
We plan to make a new release next week, so that should be fine.

**Comment by iArnold** [comment]
Hearing that makes me happy again :-)
