### ISSUE TITLE
Error when marshalling routine data, seen with "print" but not with "prin"

### ISSUE THREAD

**Issue by teyvk** [red/red#1090]
Using 0.5.2. Looking at the last two lines of the script (when compiled) the output is fine with 'prin count' but gives an error with 'print [count "rows processed"]'. This example is derived from examples/do-sql.red of Kaj de Vos SQLite binding.
```
Red []
#system-global [
  data!: alias struct! [
  	 count 	       [integer!]
  ]
  data:			declare data!]
begin: routine [] [
       data/count: 0]
count: routine [
       return:	[integer!]][
	data/count]
begin
prin count print " rows processed"
print [count "rows processed"]
```
0 rows processed
*** Script error: invalid function definition: thru
*** Where: count
*** Stack: print count

**Comment by Kaj-de-Vos** [comment]
Good find. This breaks a lot of my code.
