### ISSUE TITLE
Parse: copy does not copy input after backtracking

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#1093]
Copy does not seem to copy the matched input if specified after backtracking a non-matching rule:

```
red>> parse "abcde" [copy str to end (print str)]
abcde
== true
red>> parse "abcde" ["xyz" | copy str to end (print str)]

== true

```

**Comment by dockimbel** [comment]
Cannot reproduce the issue. Could you try it again with latest commit from master branch?

**Comment by PeterWAWood** [comment]
The code now works in the master branch.
