### ISSUE TITLE
reform behaviour different than rebol?

### ISSUE THREAD

**Issue by RAbraham** [red/red#1097]
Hi,
I was playing with Red and I got this:
```
red>> reform [ 1 + 2 3 + 4]
*** Script error: reform has no value
*** Where: try
```
In Rebol2,
```
>> reform [ 1 + 2 3 + 4]
== "3 7"
```
Would this be a bug or is the semantics different in Red?

Thanks,
Rajiv

**Comment by x8x** [comment]
`has no value` probably means it has not yet been implemented.
you can use `form reduce` in the meantime
```rebol
red>> form reduce [ 1 + 2 3 + 4]
== "3 7"
```

**Comment by dockimbel** [comment]
Not implemented yet, but you can create it easily:
```
red>> reform: func [spec [block!]][form reduce spec]
== func [spec [block!]][form reduce spec]
red>> reform [1 + 2 3 + 4]
== "3 7"
```

It has not been added yet, as we need to re-examine how we want to handle `reform` vs `form` vs `join` vs `rejoin` and see if we can improve it from Rebol.

**Comment by RAbraham** [comment]
Got it, thank you.
