### ISSUE TITLE
OSX: missing .dylib option

### ISSUE THREAD

**Issue by x8x** [red/red#1102]
red.r line 189:
filename: append temp-dir/:basename pick [%.dll %.so] Windows?

% red
Pre-compiling compression library...
*** Driver Internal Error: Script Error : Library error: dlopen(/tmp/red/crush-2015-4-21-41408**.so**, 1): image not found 
*** Where: build-compress-lib 
*** Near:  [crush-lib: load/library filename 
crush-compress: make
]

  % ls /tmp/red/
-rwxr--r--   1 user  wheel    20K Apr 21 12:01 crush-2015-4-21-41408**.dylib**

**Comment by dockimbel** [comment]
Please confirm if that fix works well for you.

**Comment by x8x** [comment]
Fixed thx 8-)
