### ISSUE TITLE
red/console stuck in a block

### ISSUE THREAD

**Issue by x8x** [red/red#1115]
```rebol
red>> ["^"
[    ]
[    ]
[    ]
[    
```
neither esc nor `]` break out of multiline

**Comment by PeterWAWood** [comment]
This is due to you not closing the string. ^ is used as an "escape" character in Red. The ^ character needs to be escaped in a string.

```
red>> ["^""
[    ]
== [{"}]
red>> ["^^"
[    ]
== ["^^"]
```

That said strings contained within "" are single line strings and there could be a case for the console automatically closing an unclosed string automatically at the end of a line (if it is possible).

**Comment by x8x** [comment]
Still, esc or `]` should work or I have no choice but to restart the console.
This is properly reported as error:
```rebol
red>>  "^"
*** Syntax Error: invalid Red value at: "^"
```

**Comment by qtxie** [comment]
On Windows, it works fine.

**Comment by x8x** [comment]
osx here

**Comment by dockimbel** [comment]
New fix for this problem, now ESC key will let you go back to prompt.

**Comment by x8x** [comment]
## Console
Thought, `ESC` key will let me go back to prompt, in the future this should have a proper fix.

Here the string! value is properly reported as invalid:
```rebol
red>> "^"
*** Syntax error: invalid value at "^"

*** Where: do
```
Here the interpreter should report same above error and NOT enter multi-line mode, as unterminated string! value can not be set in multi-line mode when using quotation marks.
```rebol
red>> ["^"]
[    ]
[    
(escape)
```
Same example in rebol2 returns proper error:
```rebol
rebol>>  ["^"]
** Syntax Error: Missing " at ["^"]
```
Not sure about this case:
```rebol
red>> print [{^
[    /}]

/
red>> 
```

## Compiler
Compiling below code:
```rebol
Red []
print ["^"]
```
will report:
```
Compiling /red/test.red ...
*** Syntax Error: Missing matching ]
*** line: 2
*** at: {["^^"]
}
```
Compiling:
```rebol
Red []
[{^{]
```
will report:
```
Compiling /Users/alpha/.red/test.red ...
*** Syntax Error: Missing matching ]
*** line: 3
*** at: "[{^^{]^/"
```
Both above compiled examples should return error about bad string! value instead of missing matching square brace.


**NB:** These are corner cases, so very low priority should be assigned, noted for correctness.
