### ISSUE TITLE
RC to accept just file!

### ISSUE THREAD

**Issue by Oldes** [red/red#1123]
In the example here: http://www.red-lang.org/2015/04/053-faster-compilation-and-extended.html
is:

    >> do %red.r
    >> rc "-c tests\demo.red"
    ...

which is not what is current result. That looks like:

    >> do %red.r
    No source files specified.

Also `rc` could support source file directly, not just string and unnecessary `-c`
I'm creating a pull request with changes.

**Comment by Oldes** [comment]
Now I can do:

   >> do %red.r
   == none
   >> rc %environment/console/console.red

**Comment by dockimbel** [comment]
The "No source files specified." is not a problem at all and even actually informs you that the toolchain has loaded properly and is able to run fine.
