### ISSUE TITLE
mold/all does not (yet) encode series offset

### ISSUE THREAD

**Issue by meijeru** [red/red#1125]
The blog article announcing 0.5.3 states that one of the pros of `mold/all` is that it can encode series offsets. I take this to mean e.g. (like in R2 and R3) the following:
`mold/all next [1 2 3]` gives `#[block! [1 2 3] 2]`
Unfortunately, so far,
`mold/all next [1 2 3]` gives simply  `[2 3]`

Will the Rebol-like behaviour be provided in some future release?

**Comment by dockimbel** [comment]
Most probably yes.
