### ISSUE TITLE
load does not accept single # as issue!, whereas interpreter has no problem

### ISSUE THREAD

**Issue by meijeru** [red/red#1126]
Compare

    type? # 
    == issue!
    mold # 
    == "#"
    load "#"
    == Syntax Error: invalid Red value at: #

R2 has no problem loading.

Of course, it is another question whether an empty issue is a good idea.

**Comment by dockimbel** [comment]
Issue! nature has changed, it is string-like in R2 and word-like in R3. Red followed R3 on that, so I think that an empty word should not be allowed.

It is interesting to see that the console allows such syntax while relying on LOAD itself. :-)
