### ISSUE TITLE
Red wrongly interpret set-paths

### ISSUE THREAD

**Issue by x8x** [red/red#1128]
Red wrongly interpret set-paths, see example:
```rebol
red>> a: [series/:i:  series/(len - (i - 1)) series/(len - (i - 1)):  tmp]
== [series/i: series/(len - (i - 1)) series/len - i - 1: tmp]
red>> mold a
== {[series/i: series/(len - (i - 1)) series/len - i - 1: tmp]}
red>> 
```

**Comment by dockimbel** [comment]
Please add some text in addition to the code example to explain what is the problem you are reporting. This is not just for saving my time, but also the time of anyone else coming to read this ticket. Thanks. :-)

The set-paths loading seems to be buggy, yes.

**Comment by dockimbel** [comment]
It was a MOLDing issue.
