### ISSUE TITLE
Empty file! value wrongly compiled

### ISSUE THREAD

**Issue by x8x** [red/red#1137]
For an empty file! `%""` compiler wrongly generate `% ""`
(notice the space between `%` and `""`)

See folowing example:

file %test.red :
```rebol
Red []
a: func [f][append copy %"" f]
print mold body-of :a
```
compiled as:
`red -c test.red`

executed with:
`./test`

return:
`[append copy % "" f]`

**Comment by dockimbel** [comment]
File! implementation is not complete yet, it is a work in progress.
