### ISSUE TITLE
Is there any good red (not rebol!) tutorial?

### ISSUE THREAD

**Issue by vasili111** [red/red#1152]

**Comment by meijeru** [comment]
The short answer is no, but you may wish to follow the discussion on Google groups on this subject:

https://groups.google.com/forum/?hl=en#!topic/red-lang/C1O0HUYAA48

**Comment by dockimbel** [comment]
Unfortunately, the Red documentation and tutorials are not yet ready. If you are interested in writing some tutorials yourself, let us know, we can provide some support for that.

You can chat with us on: https://gitter.im/red/red

**Comment by dockimbel** [comment]
Unfortunately, the Red documentation and tutorials are not yet ready. If you are interested in writing some tutorials yourself, let us know, we can provide some support for that.

You can chat with us on: https://gitter.im/red/red
