### ISSUE TITLE
system/words is not filled with all definitions

### ISSUE THREAD

**Issue by meijeru** [red/red#1153]
`system/words/float!` has value `float!` as expected, but e.g. `system/words/symbol!` is unset!, and this has some consequences, e.g. it breaks up `help system/words`

**Comment by hotcore** [comment]
Don't know if this is related:
--== Red 0.5.3 ==--
Type HELP for starting information.

red>> print system/words
Memory error: allocate memory > 2MB (--NOT_IMPLEMENTED--)

*** Runtime Error 1: access violation
*** at: 0041F6ACh

**Comment by meijeru** [comment]
Yes, precisely! Both help and print will evaluate system/words/<unset word> at some point and blow up.
