### ISSUE TITLE
Cannot construct argument to make

### ISSUE THREAD

**Issue by meijeru** [red/red#1157]
I tried to make a vector with a size dependent on the size of another variable, as follows:

    make vector! reduce [integer! 8 length? line []]

This gave the following error:

    *** Script error: datatype type is not allowed here
    *** Where: make

Apparently, `make` does not evaluate its argument(s). Curiously, R3 DOES evaluate the second argument but gives an error anyhow.

Post-script: it is a general thing with `make`, e.g. `sz: 10 make string! sz` does not work either.

**Comment by dockimbel** [comment]
`make vector!` expects a word! value, not a datatype! value (resulting from reducing `integer!` word), hence the legitimate error message. If you use a lit-word! for `integer!`, it will work as you expect:
```
red>> line: [1 2 3]
== [1 2 3]
red>> make vector! reduce ['integer! 8 length? line []]
== make vector! [integer! 8 [0 0 0]]
```

**Comment by dockimbel** [comment]
The `make string!` error is already referenced in another ticket.

**Comment by meijeru** [comment]
I find the design decision to have the first argument in the block as a *word* rather than a *datatype* somewhat strange.

**Comment by dockimbel** [comment]
If it was not a _word_, you would have to `reduce` the block systematically which would not be practical. This is also how types are specified in specification blocks in functions, as words instead of datatypes.

**Comment by meijeru** [comment]
OK got you.
