### ISSUE TITLE
IN native behavior inconsistent with Rebol version

### ISSUE THREAD

**Issue by Oldes** [red/red#1162]
in Rebol:

    >> ctx: context [a: 1]  in ctx [a]
    == [a]

in Red:

    red>> ctx: context [a: 1]  in ctx [a]
    == make object! [
        a: 1
    ]

**Comment by Oldes** [comment]
Looks it's just not implemented for `block` type as this is ok:

    red>> a: 2 ctx: context [a: 1]  do in ctx 'a
    == 1

**Comment by dockimbel** [comment]
I fail to see why `in` was allowed to do that, as it just duplicates the behavior of `bind`.

**Comment by dockimbel** [comment]
I am closing this ticket as this feature seems redundant with `bind`.
