### ISSUE TITLE
Console: tab behaviour when pasting from clipboard

### ISSUE THREAD

**Issue by x8x** [red/red#1164]
Could the tab autocompletion differentiate between typed TAB key and pasted text form clipboard containing tabs? If yes, tab autocompletion should probably always be turned off in such cases.

Currently, pasting this text `sys(TAB)123` will return:
`red>> system123`
I'm not sure what would be the best solution, I think if pasting outside a string definition, tabs should be converted to spaces, so in the case above I should get:
`red>> sys 123`
with tab autocomplete turned off.

When pasting text containing tabs into a string definition (after an open `{` or an open `"`) tab autocompleting should be turned off and tabs converted to `^-`, same treatment as CR and LF currently get.
So it would be great if after:
`red>> {`
pasting a string like `sys(TAB)is(TAB)(LF)great}` would return:
`red>> {sys^-is^-^/great}`

**Comment by x8x** [comment]
It can be dangerous!! check this example:
```rebol
killme: does [q]

f: func [][
ki: 1
ki(TAB);comment
]
```
pasting above code in the console:
```rebol
  killme: does [q]
;   func [][q]
  
  f: func [][
[    ki: 1
[    killme;comment
[    ]
;   func [][ki: 1 killme]
```
Calling the harmless 'f function! will call the could be evil 'killme function!
In this case it will luckily just quit.

**Comment by dockimbel** [comment]
Fixed by commit [7ee272a5](https://github.com/red/red/commit/f07e0bafd3100e265f0af8fa86bbfdf67ee272a5).

**Comment by x8x** [comment]
Not fixed, at least not on MacOS and Linux

**Comment by qtxie** [comment]
Yes. CLI console still has this issue.

**Comment by qtxie** [comment]
Actually in CLI console I cannot distinguish between the text from keyboard, and the text from clipboard.
So maybe we should provide a way to disable autocompletion, something like: `system/console/auto-completion?: off`.

**Comment by x8x** [comment]
nodejs has the same issue, probably because they also can't differentiate between typed vs pasted.
In node REPL, pasting `conso(TAB)//123` will print `console//123`
I will do some research about this.

**Comment by x8x** [comment]
Maybe there is a nice solution working on MacOS and Linux: "Bracketed paste mode".
Quoting: "it enables something very cool: programs can tell the difference between stuff you type manually and stuff you pasted"
have a look https://cirw.in/blog/bracketed-paste

**Comment by x8x** [comment]
Please reopen this one. 8-)

**Comment by dockimbel** [comment]
@qtxie We can try that proposed solution, though it works probably only on Unix terminals, not in Windows DOS console.

**Comment by x8x** [comment]
👍
