### ISSUE TITLE
Console: Feature request for TAB autocomplete

### ISSUE THREAD

**Issue by x8x** [red/red#1165]
Following enhancement to console TAB autocomplete's behaviour would be much appreciated.
Given:
```
red>> compl
```
pressing `TAB` currently returns:
```
red>> complement complement? complete-from-path 
red>> compl
```
it would be very useful if in addition to words proposal, it would also autocomplete the common part of the proposed words, in above case:
```
red>> complement complement? complete-from-path 
red>> comple
```
even better would be if further `TAB` pressed would cycle thru the proposed words until the `ENTER` key is pressed.
```
red>> compl
```
`TAB`:
```
red>> complement complement? complete-from-path 
red>> comple
```
`TAB TAB`:
```
red>> complement complement? complete-from-path 
red>> complement
```
`TAB TAB TAB`:
```
red>> complement complement? complete-from-path 
red>> complement?
```
`TAB TAB TAB TAB`:
```
red>> complement complement? complete-from-path 
red>> complete-from-path
```
`TAB TAB TAB TAB TAB ENTER`:
```
red>> complement complement? complete-from-path 
red>> complement 
```
With a `SPACE` char auto added after the selected word.

**Comment by dockimbel** [comment]
This would be a nice improvement, but this is very low-priority for now, so probably after we reach beta stage.

**Comment by dockimbel** [comment]
Such features would take too much time to implement right now, so we are deferring it to a later stage in the future.

**Comment by geekyi** [comment]
Now fixed with https://github.com/red/red/commit/61efdadd9dc2f2da9d46da6cf0cb72e1fff9f055
