### ISSUE TITLE
Problems with redefined native 

### ISSUE THREAD

**Issue by meijeru** [red/red#1170]
See below
`red>> z: :print`
`== make native! [...]`
`red>> print: 3`
`red>> print`
`red>>` ; should be `3`
`red>> z print`
`3` ; correct

Reported under OSX and Windows

**Comment by dockimbel** [comment]
The console code is written in Red itself, partly compiled, partly interpreted. If you redefine `print`, do not expect the console to still be able to have a correct output anymore. :-)

See the relevant code [here](https://github.com/red/red/blob/master/environment/console/console.red#L114).

**Comment by meijeru** [comment]
Fair enough. Merits a warning, perhaps, in the documentation.

**Comment by dockimbel** [comment]
There will be a big one, warning users from redefining core functions. Moreover, this is a feature that the compiler reports as an error if someone attempts to redefine one of the core functions that are processed as [keywords](https://github.com/red/red/blob/master/compiler.r#L77) by the compiler.
