### ISSUE TITLE
Red website video not showing up.

### ISSUE THREAD

**Issue by hostilefork** [red/red#1183]
![screen shot 2015-05-25 at 2 31 03 am](https://cloud.githubusercontent.com/assets/20440/7792885/2c7d346c-0286-11e5-8cc5-0eb25236b991.png)

**Comment by hostilefork** [comment]
I have a copy of this video in HD if you need it.  The subtitles are at:

https://github.com/red/branding/tree/master/captioning/what-is-red

**Comment by hostilefork** [comment]
With $500K at one's disposal, one would think there'd be *someone* to do a YouTube upload on a channel controlled by the Red project *(vs. being on someone's channel you don't trust?)*.  Deleting the content altogether seems a bit cutting off one's nose to spite one's face.  Just my opinion.

If you change your mind, here is again a copy of the video...or for anyone seeking it in the near term:

https://www.dropbox.com/s/8626lj71nphxlem/nenad-recode-talk.mp4

**Comment by WiseGenius** [comment]
This is the video I send people to whenever I tell them about Red.
