### ISSUE TITLE
equal?  and lesser? behave differently when invoked with no arguments

### ISSUE THREAD

**Issue by meijeru** [red/red#1184]
In the interpreter:

    red>>equal?
    == true

    red>>lesser?
    *** Internal error: reserved for future use (or not yet implemented)
    *** Where: lesser?

Both behaviours seem inappropriate. The first one is shared by strict-equal? and not-equal?, the second one by the other inequality testing functions.

**Comment by dockimbel** [comment]
Good catch. The injection of `unset` values (which is causing this behavior) should be more restricted. It will now happen only if the spec argument is a `lit-word!` and if it accepts `unset!` values.
