### ISSUE TITLE
%lexer.r does not seem to handle line numbers correctly

### ISSUE THREAD

**Issue by meijeru** [red/red#1187]
From inspection of the program text, I fail to see that line break positions are registered correctly.
The parsing rule is

    	ws: [
		pos: #"^/" (
			if count? [
				line: line + 1 
				append/only lines to block! stack/tail?
			]
		)
    | ...

and this does not insert anything sensible in to the `lines` array. Thus `add-line-markers` has nothing useful to do. Are the line break positions ever used??

**Comment by dockimbel** [comment]
Right, the line break positions implementation was started and not completed so far. We plan to add support line breaks position both in static and runtime lexers soon (to be able to pass them to runtime blocks and preserve as much as possible the original source layout).
