### ISSUE TITLE
Source file structure: some puzzlements

### ISSUE THREAD

**Issue by meijeru** [red/red#1189]
I have improved my indexing and analysis of the Red compiler suite, see [this Google groups thread](https://groups.google.com/forum/?hl=en#!topic/red-lang/X-OsmUDAxkI). In this and some following issues I will raise questions arising from that effort.

The sources contain a file `%build/includes.r` which writes information about the source files to be used onto a file called `%build/bin/sources.r`. In the list of files which is the argument of `set-cache`, the file `%runtime/stack.reds` occurs twice. Is that needed? On the other hand, the source files which are in `%runtime/devices/console` do *not* occur in that list. They seem to be duplicates of the files in `%environment/console`. What are the plans here?

**Comment by meijeru** [comment]
Further to my remark about console handling, the two sets of files turn out to be subtly different. See e.g. in `%win32.reds` the list of `#defines`.

**Comment by dockimbel** [comment]
Good catch. It is more probably the result of a bad merge with a development branch.

**Comment by dockimbel** [comment]
Files in `%runtime/devices/console` are leftover from a previous merge operation. They are removed now.
