### ISSUE TITLE
Unused code in %block.reds?

### ISSUE THREAD

**Issue by meijeru** [red/red#1190]
I wonder if the function `append*` in `%block.reds` is needed. It looks as if the `append` action is handled differently, via `insert`.

**Comment by dockimbel** [comment]
It is used in %runtime/natives.reds at line 754.

**Comment by meijeru** [comment]
Why not use actions/append* there?

**Comment by dockimbel** [comment]
Because it is optimized for the general case (no `/into` option), `block/append*` is way more faster than `actions/append*`.
