### ISSUE TITLE
empty? is subtly different from tail?

### ISSUE THREAD

**Issue by meijeru** [red/red#1191]
In `%environment/functions.red`, the function `empty?` used to be defined as identical to `tail?`. The statement doing that is now commented out, and a new definition is provided which accepts not only a series but also `none`. While this has no doubt advantages in programming, one wonders why `tail?` cannot have this same facility.

**Comment by dockimbel** [comment]
`empty?` is meant to be the _relaxed_ version of `tail?`. Sometimes you want the `empty? find` pattern to work even if `find` returns `none`, but in the general case, you expect a series, so `tail?` provides you with the safe variant (that will error out in case of `none` argument).

**Comment by dockimbel** [comment]
The commented code has been removed and the `empty?` has been changed to return `false` instead of `none`.
