### ISSUE TITLE
Different definitions of GENERIC_READ and GENERIC_WRITE

### ISSUE THREAD

**Issue by meijeru** [red/red#1193]
In `%system/library/windows.reds` we find

    #define GENERIC_WRITE	80000000h
    #define GENERIC_READ	40000000h

In `%runtime/simple-io.reds` and `%runtime/platform/win32.reds` we find

    #define GENERIC_WRITE	40000000h
    #define GENERIC_READ	80000000h

Which set of definitions is correct?

**Comment by dockimbel** [comment]
The second one is correct. The first one is coming from the common library code written by Bruno Anselme for his contributed libraries.
