### ISSUE TITLE
RETURN_NONE does EXIT, and RETURN_UNSET does not

### ISSUE THREAD

**Issue by meijeru** [red/red#1194]
In `%runtime/natives.reds` these two `#defines` perform similar functions. As it happens, `RETURN_UNSET` is always used as last statement in the execution flow in a function, thus `exit` is not required,. But this is clearly accidental, and could give a problem if `RETURN_UNSET` were used in another position in the exectution flow.

**Comment by dockimbel** [comment]
RETURN_UNSET definition is removed, as it is used once only.
