### ISSUE TITLE
run time lexer uses subtly different rule for parsing  url! values than compile time lexer does

### ISSUE THREAD

**Issue by meijeru** [red/red#1220]
In particular, the run time lexer relies on  the `integer-end` and `not-file-char` sets of characters and does not use the more obvious `not-url-char` set. Notably, the `integer-end` set contains `x` which has nothing to do with `url!` values. In general, detection of `url!` values should not be dependent on the lexical properties of integers or files.

Whether the end effect of the current definitions is still the same in both lexers is not easy to see from the source and it may be difficult to prove.

**Comment by dockimbel** [comment]
Now, run-time lexer uses `not-url-char` too.
