### ISSUE TITLE
read-input crashes

### ISSUE THREAD

**Issue by endo64** [red/red#1241]
read-input crashes on Windows, v0.5.4

    red>> read-input "test"
    testread-input "test"
    == "test"
    *** Runtime Error 1: access violation
    *** at: 00448DB4h

**Comment by dockimbel** [comment]
`read-input` is not meant for users, it can only work when used internaly, use `ask` for getting user input.

**Comment by dockimbel** [comment]
`ask` stability has been a little improved and `read-input` renamed to `_read-input` to discourage users willing to try it. ;-)
