### ISSUE TITLE
error about documents when interpreting a file

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1245]
On Windows XP:
```
H:\>red-14jun15-406b783.exe test.red
'H:\Documents' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by qtxie** [comment]
I can't reproduce it with the latest version (red-16jun15-12a6ff4.exe).

**Comment by WiseGenius** [comment]
```
H:\>red-16jun15-12a6ff4.exe test.red
'H:\Documents' is not recognized as an internal or external command,
operable program or batch file.
```
I'll be back with more clues later.

**Comment by WiseGenius** [comment]
On another computer, also running Windows XP:
```
C:\>red-16jun15-12a6ff4.exe test.red
Pre-compiling compression library...
Pre-compiling Red console...
'C:\Documents' is not recognized as an internal or external command,
operable program or batch file.
```
The console is successfully compiled in `C:\Documents and Settings\All Users\Application Data\Red`.
My guess is that it's trying to run something like this without accounting for the spaces:
```
C:\Documents and Settings\All Users\Application Data\Red\console-2015-6-16-70074.exe test.red
```
@qtxie I don't have access to a later version of Windows right now, but I suspect the corresponding paths used by the later versions don't contain any spaces? That might explain why you can't reproduce it?
I haven't had a chance to look at the code yet, but maybe this a regression caused by fixing #1232 or #1234?
