### ISSUE TITLE
negate on bitsets does not work

### ISSUE THREAD

**Issue by meijeru** [red/red#1259]
According to the code, it should have the same effect as complement. However, it does nothing:

    red>> negate charset "abc"
    == make bitset! #{00000000000000000000000070}
    red>> charset "abc"
    == make bitset! #{00000000000000000000000070}

**Comment by qtxie** [comment]
It works. ;-)
```
>> negate charset "abc"
== make bitset! [not bits #{00000000000000000000000070}]
```

**Comment by meijeru** [comment]
The commit has been merged; the issue can therefore be closed.
