### ISSUE TITLE
Written interview about red

### ISSUE THREAD

**Issue by unbalancedparentheses** [red/red#1269]
Hello,
First of all @dockimbel, sorry for using github issues for contacting you but I could not find your email. I am interviewing different programming language creators about the reasons why they have created the language, how they did it, what design choices they have faced, how it compares to other languages, etc.

For the moment I have only published only one interview with pretty good success and comments:
https://medium.com/indie-programming-languages

Let me know if you are interested in answering a small interview!

Regards,
Federico.

**Comment by mallochine** [comment]
@unbalancedparentheses this sounds like an awesome idea! I'll be reading the interviews you publish.

**Comment by mallochine** [comment]
@unbalancedparentheses you should also try asking the inventor of terra lang, which I personally view to be a very promising direction -- a low-level language that allows you to easily embed Lua.

**Comment by unbalancedparentheses** [comment]
@mallochine thanks! I will play a little bit with terralang and send the creator an email/github issue. I hope I can interview @dockimbel about red and its development :D

**Comment by PeterWAWood** [comment]
Please stop using Red language issue list as a chat forum. If you wish to contact Nenad, use either the Google Group or Gitter. Links to both are clearly displayed on Red's homepage.

**Comment by dockimbel** [comment]
@unbalancedparentheses Sent you an email about that.
