### ISSUE TITLE
Some almost trivial TO conversions are not allowed -- they could be

### ISSUE THREAD

**Issue by meijeru** [red/red#1270]
This concerns `to percent! <integer value>` and `to float! <percent value>`as well as its converse `to percent! <float value>`

**Comment by dockimbel** [comment]
TO is not fully implemented yet, it is only implemented for a few rare cases so far.

**Comment by dockimbel** [comment]
I will close this ticket and the related one. You can reopen them once we announce full `to` support if they are still relevant.
