### ISSUE TITLE
50 char limit on paths

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1281]
On Windows XP:

```
H:\>red-21jul15-895ec65.exe folder-length-16\dir-length-13\file-length-18.red
This is the test output.

H:\>red-21jul15-895ec65.exe folder-length-16\folder-length-16\file-length-18.red

*** Error: File not found
```

Both files exist.
There seems to be a limit of 50 characters for path lengths here.
Is this a bug, or temporarily intentional?

**Comment by dockimbel** [comment]
I see no special limit in the source code about filename sizes.
