### ISSUE TITLE
MODIFY is specified for map! values, but not (yet) implemented

### ISSUE THREAD

**Issue by meijeru** [red/red#1297]
map! occurs in the spec of the modify action

red>> help modify

USAGE:
    modify target  field  value  /case

DESCRIPTION:
     Change mode for port/file or change the value of a key in a map.
     modify is of type: action!

ARGUMENTS:
     target  [map! file!]
     field  [word!]
     value  [any-type!]

REFINEMENTS:
     /case => Perform a case-sensitive lookup.

red>> modify #(a 1) 'a 2
*** Script error: modify does not allow map for its target argument
*** Where: modify

**Comment by dockimbel** [comment]
`map!` removed from spec block until it gets implemented.
