### ISSUE TITLE
Adding new functions

### ISSUE THREAD

**Issue by BED822** [red/red#1336]
1. Having Red_Script (Python-Django/Ruby-Rails/PHP/Perl)
2. Having Red_Lisp (Clojure/Haskell/Erlang/Scala)
3. Binary to text encoding to base32, base64, base85, base91
4. Binary to mnemonic encoding from S/KEY, PGP, bubble babble and BIP0039
5. Allow decimal, dozenal, hexadecimal, sexagesimal, Chinese and "New Earth" time
6. Include reformed calender, like Asimov, Hanke-Henry, Leap Week, Thirteen Month
7. include date naming system like Positivist, Tranquility or French Revolution.
8. Allow a golfing-specific script Red_Golf as an "easter egg"
9. Make use of military time zone codes and what3words
10. Allow co-ordinate conversion of DEC, DEG, DMS, UTM, MGRS, Swiss Grid (CH1903 or CH1903+), Maidenhead (QTH), Gauss–Krüger (GK, Bassel 1841), Mercator or Geohash
11. Allow color conversion of CMY, CMYK, HEX, HSL, HSV, RGB, YIQ, YUV, YCbCr, YPbPr
12. Allow calculation of distance and bearing between 2 dots, projection from a point to another point, midpoint or intersection of 2 or 3 points, cross or intersection bearing, intersection of circle and line, intersection of 2 lines, intersection 2 points and 2 angles, resection of 3 points and 2 angles, equilateral triangle
13. date converter of WGS84, Bessel 1841: DHDN (Postdam) 2001 or 1995, Krasovsky 1940: S42/83 (Pulkowo) 2001 or 1995, Bessel 1841 MGI or LV95, Airy 1830: OSGB36, Airy Modified: Ireland 1965, Hayford 1924: ED50, Clarke 1866
14.

Points 10 to 14 can be found in the GeoCache Calculator app in the android store

Mathamatics:
Trigonometric functions: sin, cos, tan, asin, acos, atan
Hyperbolic function: sinh, cosh, tanh, asinh, acosh, atanh
Logarithms: log (for 10/decimal), lg (for 2/binary), lon (for 12/dozenal), ln (for e/natural)
Quotient and Modulo in multiple ways: Truncated, Floored, Eucliedian
Modulo 1: FRACtion (fractional part), SAWtooth (y minus floor of y)
Rounding: Ceiling, Floor, Truncate, Round Half up, Round Half down, Round half zero

**Comment by PeterWAWood** [comment]
Please could you submit your wishes as a proposal on the Github Red Wiki, they are too wide ranging to be considered as issues. A brief description and reason for including them in Red would allow them to be properly considered.

Also please remember that Red is still very much in at the alpha stage.
