### ISSUE TITLE
REPL: tab autocomplete partially broken

### ISSUE THREAD

**Issue by x8x** [red/red#1385]
First tab in a line does't autocomplete, tabbing, going back and tabbing again does work

```
(p)(r)(i)(tab) -> {pri } -> (back) -> {pri} -> (tab) ->
{print prin print-error print-to-stderr 
pri}
```

```rebol
  system/platform
;   MacOSX
```
Not sure in which commit it regressed, but since a couple months already.

**Comment by qtxie** [comment]
It's caused by using `#call` inside `routine`.

**Comment by dockimbel** [comment]
@Qtxie Is this working now or does it still require fixing?

**Comment by qtxie** [comment]
@dockimbel It works now.
