### ISSUE TITLE
Possible Float Stack Check Bug

### ISSUE THREAD

**Issue by JacobGood1** [red/red#1424]
I get a float stack check error when I do this...
c code

``` c++
extern "C" __declspec(dllexport) inline float __cdecl sf_sprite_get_x(sfSprite* sprite)
{
    return sfSprite_getPosition(sprite).x;
}
```

reds

``` reds
sf-sprite-get-x: "sf_sprite_get_x" [
    sprite  [sf-sprite!]
    return: [float32!]
]
```

red

``` red
get-x: routine [sprite* [integer!] return: [float!]] [
    as float! sf-sprite-get-x as byte-ptr! sprite*
]
```

get-x sprite*

**\* Runtime Error 11: float stack check
**\* at: 68C6C4CCh

**Comment by dockimbel** [comment]
Can't be reproduced anymore. Moreover, such kind of FPU errors on Intel platforms will be gone once we switch to SSE for floating-point support.
