### ISSUE TITLE
Objects that return objects through "methods" do not work with make

### ISSUE THREAD

**Issue by JacobGood1** [red/red#1427]
```red
Red []

obj1: object [
    make: function [return: [object!]] [
        temp: object []
        temp
    ]
]
obj2: object [
	
]

make obj1/make obj2
```
*** Red Compiler Internal Error: Script Error : any-function? expected value argument of type: word
*** Where: comp-word

**Comment by dockimbel** [comment]
The compiler forbids redefining core words, though it should provide you an nice error in that case instead of crashing.

**Comment by dockimbel** [comment]
Fixing the crash showed that the compiler *can* handle redefinition of core words *inside* object contexts, though, this is untested area.
