### ISSUE TITLE
Accessing bytes in c-Strings with variable index

### ISSUE THREAD

**Issue by menzel** [red/red#1431]
The following code:
    foo: "a string"
    c: 3
    print foo/c

produces the following error:
    *** Script error: word type not allowed here
    *** Where print

It works with a fixed value:
    print foo/3

As far as I can see it should work. At least the language specification tells about the feature:
http://static.red-lang.org/red-system-specs.html#section-4.6

**Comment by Oldes** [comment]
The mentioned documentation is for *Red/System*.
Above is correct behaviour, like in REBOL:
```
>> foo: "a string"
== "a string"
>> c: 3
== 3
>> print foo/c
** Script Error: Invalid path value: c
** Near: print foo/c
>> print foo/(c)
s
>> print foo/:c
s
>>
```
it's in Red:
```
red>> foo: "a string"
== "a string"
red>> c: 3
== 3
red>> foo/:c
== #"s"
red>> foo/(c)
== #"s"
```
