### ISSUE TITLE
Error in draw dialect leads to Access violation

### ISSUE THREAD

**Issue by meijeru** [red/red#1443]
I put "normal" VID code in a draw block. This gave a Script error first, but that was followed by a Runtime error. See below.

    result of test.red
    *** Script error: invalid Draw dialect input at: at 240x10 button 50x20 Exit a quit
    *** Where: show-window
    *** Stack: view show if show-window
    
    *** Runtime Error 1: access violation
    *** at: E0CB93B5h

**Comment by qtxie** [comment]
Related issue #1435

**Comment by dockimbel** [comment]
It seems to be working fine now, can't reproduce it anymore.
