### ISSUE TITLE
drop-down face not wide enough

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1456]
```
view [drop-down "This is fairly long and won't quite fit." data ["This is even longer and its length is ignored altogether."]]
```
On both Windows XP and Windows 7, the above code results in displaying only “This is fairly long and won't quite”. The rest of it, “ fit.”, doesn't fit. My guess is that the width of the box on the end with the triangle wasn't taken into account when calculating the size.
`data` isn't checked at all to see if its longest item will fit.
As a result, if the user tries to type either of the above values into the `drop-down`, it will beep as being too long.

**Comment by dockimbel** [comment]
We cannot yet fix this issue totally as we need to extract the metrics for all decorations used by widgets and take them into account in internal size calculation.

**Comment by dockimbel** [comment]
It works fine now.
