### ISSUE TITLE
transparency changes dragging behaviour of base face

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1461]
When setting a `base`'s `options` to `[drag-on: 'down]`:
* If the `base`'s `color` has an opacity of `255`, it can be dragged outside the window (and out of sight).
* If the `base`'s opacity is set to anything below `255`, or if it's `color` isn't set but its `image` is instead:
  * The `base` cannot be dragged even partially outside the window.
  * The `base` is brought to the front of every other type of face, and in front of every fully opaic `base`.

The issue is the difference in behaviour.
* All other types of draggable faces can be dragged outside of the window (and out of sight).
* No other types of face's movement is restricted by transparency in the way `base` is.
* However, no other types of faces currently display any transparency either, though most display the other channels of `color`.

**Comment by qtxie** [comment]
*The base cannot be dragged even partially outside the window*
This is how it is be implemented for now for simplicity. It would be improved later.

*The base is brought to the front of every other type of face, and in front of every fully opaic base*
It's the restriction in Windows version (prior to Win 8) which doesn't support making Layered windows as Child window. In those Windows version, we need to simulate the feature. When we use transparency in `base`, it's a **pop-up** layered window actually, so it's in front of any other faces.

**Comment by qtxie** [comment]
_The base cannot be dragged even partially outside the window_
It is solved now.

_The base is brought to the front of every other type of face, and in front of every fully opaic base._
It cannot be solved on Windows prior to version 8.
