### ISSUE TITLE
face/selected does not get set in drop-list or drop-down

### ISSUE THREAD

**Issue by meijeru** [red/red#1468]
I tried viewing the following layout:

    [drop-list data ["a" 1 "b" 2 "c" 3] on-change [probe face/selected]]

and the result is always `none`. What should it be?

**Comment by meijeru** [comment]
Sorry to nag, but I don't see the commit that solved this.

**Comment by dockimbel** [comment]
Seems to be working fine with the latest version. Let me know if it doesn't work for you.
