### ISSUE TITLE
There is a lexer inconsistency with Rebol for issue! type

### ISSUE THREAD

**Issue by Oldes** [red/red#1470]
```
red>> load {#4=#5*COS}
== [#4= #5*COS]
```

versus:

```
>> load {#4=#5*COS}
== #4=#5*COS
```

**Comment by Oldes** [comment]
@dockimbel But as I see now.. in Rebol3 it's not possible to have issue like ```#foo#``` (as it was in Rebol2), so it's up to you if you want to close it or accept the lexer change.

**Comment by dockimbel** [comment]
There are two kind of issue! types: *issue-as-string* and *issue-as-word*. The lexical space is not exactly the same for boths, as we want to keep issue-as-word close to word lexical rules (to facilitate conversions). Rebol2 implements the former, Red and Rebol3 implement the latter.

Though, I think both ways to implement issues are useful, for different use-cases,  so the unsolved question so far is, how to define them so there is no ambiguity. Kaj proposed a solution in #380, which is the best option we have so far, though it still requires some studying and prototyping. BTW, I think we could name the types as: *issue!* (for issue-as-string) and *keyword* (for issue-as-word).

So I think your extended rules for issue are premature, they belong rather to the issue-as-string type that we don't have yet.

**Comment by 9214** [comment]
@dockimbel @greggirwin if we agree that `issue!` (word-like) and `ref!` (string-like) fit the bill, then this ticket should be closed.

For the reference, new lexer:
```red
>> load {#4=#5*COS}
== #4=#5*COS
>> transcode/prescan {#4=#5*COS}
== issue!

>> load {#foo#}
== #foo#
>> transcode/prescan {#foo#}
== issue!
```

**Comment by greggirwin** [comment]
I remember the `#<alpha>*` idea, and also my concerns about it. At one time I think it seemed OK, but while I may have been the heaviest user of issues-as-strings in R2 (I used them as IDs in many production systems) there's a catch to being bimodal here. *Everything* has to work seamlessly when it comes to automatic conversions, and handling. If you use a convention which just happens to create half your `issue!` values with a leading digit, nothing in your code should break or dramatically change in behavior. This goes both ways, as now you have the limitations of each type lowering their power. symbol space may be limited, and series are heavier. 

Other options break existing code now. e.g. `##keyword` syntax. There is also the complexity cost in the grammar and implementation. Raw strings don't help as ad-hoc issues either, if they can't be round-tripped.

Numeric support relates to #650 WRT word conversion consistency.

**Comment by 9214** [comment]
↑ ping.
