### ISSUE TITLE
DRAW dialect accepts blocks of DRAW dialect for gathering related instructions

### ISSUE THREAD

**Issue by JerryTsai** [red/red#1478]
```
draw: [  
    [ fill-pen white box 0x0 40x40 ]
    [ fill-pen red box 10x10 20x20 ]
]
```

**Comment by meijeru** [comment]
If this is only a matter of presentation, the newlines will be sufficient. At least, how I understand the DRAW dialect, leaving out the block brackets would not change the semantics.

**Comment by dockimbel** [comment]
@meijeru It is about grouping Draw commands, so it becomes easier to insert/remove them.
