### ISSUE TITLE
In VID, it doesn't seem possible to draw on a base face

### ISSUE THREAD

**Issue by meijeru** [red/red#1486]
In `%view-test.red` the `draw` field of a `base` face is set programmatically. There does not seem to be a corresponding facility in the VID  DSL.

**Comment by meijeru** [comment]
I withdraw the issue. I found a way.

**Comment by Oldes** [comment]
@meijeru You should at least paste _the way_ here, just for a record

**Comment by meijeru** [comment]
Just follow the `base` spec by `draw [...]`. I think my fault was that I made a mistake in the contents of the draw block, and thought that `draw`was not permitted itself.
