### ISSUE TITLE
Reactor processing may lead to parse error

### ISSUE THREAD

**Issue by meijeru** [red/red#1487]
My code, attempting to show slider value as percentage:

    s: slider 100x20 data 50%
    text right "50%" react [
        face/text: append to string! to integer! 100 * s/data #"%"
    ]

This works, BUT replacing `#"%"` by `"%"` gives the following error: 
*** Script error: PARSE - matching by datatype not supported for any-string! input
*** Where: parse
*** Stack: view if set layout unless ctx174~process-reactors foreach parse

**Comment by dockimbel** [comment]
Good catch!
