### ISSUE TITLE
area face needs CRLF (^M^/) to go to newline, ^/ alone is not enough

### ISSUE THREAD

**Issue by meijeru** [red/red#1488]
Apparently there is no "translation" of the Red newline to what Windows needs.

**Comment by dockimbel** [comment]
Another good catch.

**Comment by dockimbel** [comment]
Fix for this class of issues has been pushed to branch `issue-1488`. It needs a few additional changes in the IO code before being mergable in master.

**Comment by dockimbel** [comment]
Fixed by commit [a39c3edb](https://github.com/red/red/commit/dd4009baaab2ed4933dcc23e7813a4f1a39c3edb).
