### ISSUE TITLE
window size too small

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1491]
The VID window size is too small to display its contents.

Windows XP:
![xp](https://cloud.githubusercontent.com/assets/7657453/11611351/c2b31dc0-9c14-11e5-8330-4308331d9a5d.png)

Windows 7:
![7](https://cloud.githubusercontent.com/assets/7657453/11611353/c8cd924e-9c14-11e5-8e68-07dc9852a730.png)

**Comment by dockimbel** [comment]
It is a known problem which got worse in the latest commits. We are working on a fix.
