### ISSUE TITLE
Regression to crash when opening window

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1493]
Regression to crash when opening window.

Compiled:
```
*** Runtime Error 1: access violation
*** in file: /H/Work/Red/Tests Red/2015-12-07-12-01-44-red-gui/red-gui/modules/view/backends/windows/events.reds
*** at line: 791
```

Interpreted:
```
*** Runtime Error 1: access violation
*** at: 00465F16h
```

**Comment by meijeru** [comment]
Same here

**Comment by dockimbel** [comment]
We don't see anything wrong here. How to reproduce the crash?

**Comment by dockimbel** [comment]
For such kinds of regressions which are related to latest commits, just signaling it on  Gitter is enough. Issues related to development branches shouldn't be reported in this issue tracker unless they are long standing issues (means we can't fix them in the same or next day after reporting on Gitter).

**Comment by dockimbel** [comment]
We should move this discussion on Gitter rather...

**Comment by dockimbel** [comment]
Ok, can reproduce it on XP.
