### ISSUE TITLE
a progress bar and a slider with the same size specified, are not equally sized on screen

### ISSUE THREAD

**Issue by meijeru** [red/red#1495]
the slider is slightly smaller

**Comment by 9214** [comment]
@meijeru do you happen to remember which platform was that? W7?

I don't think pixel-perfect match of visual widget's sizes is worth pursuing; at least from my experience, there's a hard cap on padding and margins on all the supported backends.

**Comment by meijeru** [comment]
I have only W10 -- it is on that platform that I noticed it. The difference is very visible to the naked eye.

**Comment by hiiamboris** [comment]
W7:
![](https://i.gyazo.com/42b1e5adc3260a819e7d5b8715aeddb3.png)
It's pixel-perfect actually and the internal padding is added by the OS for whatever aesthetic reason.

**Comment by meijeru** [comment]
As seen in the nice picture above, the slider is INSIDE the space allocated to the widget, so the end points are not extending to the edges of the progress bar. If one does not have a frame around them, it just looks like the slider is narrower. I close this issue.
