### ISSUE TITLE
drop-down face does not allow value to be supplied by user

### ISSUE THREAD

**Issue by meijeru** [red/red#1498]
When you type into the field of the drop-down face, the following error occurs: 

    *** Script error: new has no value
    *** Where: series?
    *** Stack: view either do-events do-event-loop ctx165~awake set do-actor if set do-safe if print =
    type? do act on-change* if unless if any series?
    *** Script error: old has no value
    *** Where: series?
    *** Stack: view either do-events do-event-loop ctx165~awake set do-actor if set do-safe if print =
    type? do act on-change* if if any series?

The first script error occurs on the first letter typed in, and on each further letter the second script error occurs.

**Comment by dockimbel** [comment]
I cannot reproduce that in view-test.red script on Win7 platform.

**Comment by meijeru** [comment]
It occurs with the following demo script:

    view [
        drop-down "Black" data ["Red" "Green" "Blue"] [
            d2/color: attempt [get to word! face/text]
        ]
        d2: base 20x20 black
        button "Exit" [quit]
    ]

and it disappears when I comment out the line `d2/color:  attempt ...`

**Comment by meijeru** [comment]
I discovered a way to avoid the errors: 

    set/any 'c get to word! face/text
    if value? 'c [d2/color: c]

But there remains a problem with `get` see #1499

**Comment by meijeru** [comment]
This problem has nothing to do with drop-down, therefore I close it

**Comment by dockimbel** [comment]
Thank you.
