### ISSUE TITLE
get and get/any seem to do the same on unset values

### ISSUE THREAD

**Issue by meijeru** [red/red#1499]
This behaviour seems to be against the definition of `get`. See the examples below. `get 'b` ought to have given an error.

    red>> b
    *** Script error: b has no value
    *** Where: try
    red>> type? get 'b
    == unset!
    red>> type? get/any 'b
    == unset!
    red>> error? get 'b
    == false
    red>> help get
    USAGE:
        get word  /any  /case
    DESCRIPTION:
        Returns the value a word refers to.
        get is of type: native!
    ARGUMENTS:
        word  [word! path!]
    REFINEMENTS:
        /any => If word has no value, return UNSET rather than causing an error.
        /case => Use case-sensitive comparison (path only).

**Comment by dockimbel** [comment]
`get 'b` should error out, indeed.
