### ISSUE TITLE
show does not seem to update window if only the draw block is modified

### ISSUE THREAD

**Issue by meijeru** [red/red#1500]
See this code:

    view [canvas: base 300x300 draw [line-cap round line-width 10 pen red
        line 10x10 130x190 80x40 150x100]
        return
        button "Change" [p: find canvas/draw 'red remove p insert p 'blue show canvas]
        button "Stop" [quit]
    ]

The idea is that the drawing becomes blue when the button is clicked. Nothing happens however. The draw block IS changed, I checked that. But `show` seems to do nothing. Is this a bug, a feature, or a programming error?

Incidentally, the `remove/insert` is needed because `change` is not (yet) implemented.

**Comment by dockimbel** [comment]
Looks like a bug.

**Comment by qtxie** [comment]
Fixed in latest version.
