### ISSUE TITLE
Latest gui branch objects to 50%

### ISSUE THREAD

**Issue by meijeru** [red/red#1504]
Compiling a very simple GUI program:

    ** Syntax Error: Invalid integer -- 50%
    ** Near: (line 3) view [progress data 50%]

I find it very puzzling, since the lexer hasn't changed, I think!

**Comment by meijeru** [comment]
The gui branch doesn't like any percent! literal, even outside view [ ].

**Comment by dockimbel** [comment]
Works fine here both from compiler and interpreter.

**Comment by meijeru** [comment]
Must be something else, I will continue to investigate but this issue is closed.
