### ISSUE TITLE
R.G.B.A(Transprancy) or R.G.B.O(Opacity)? 

### ISSUE THREAD

**Issue by JerryTsai** [red/red#1510]
1. In my Test on Atom Tablet with Windows 10, the 4th element of the color tuple is Opacity. The bigger the number is, the more opaque the color is. I just need to be sure the system that Red use is RGBA or RGBO.
2. No matter the 4th element of a color is 0 or 255, the color will become opaque. this is absolutely a bug.

**Comment by JerryTsai** [comment]
After you closed the issue. I did a test. When alpha is 255, the color should be fully transparent, but in my test, it's fully opaque. This issue should be re-open.

**Comment by WiseGenius** [comment]
@JerryTsai Are you referring to the color of a base face? If so, see my latest comment on [#1452](https://github.com/red/red/issues/1452).

**Comment by WiseGenius** [comment]
#1512 seems to have fixed #1452.
