### ISSUE TITLE
changing panel content makes changed image disappear and decouples the pane from the window

### ISSUE THREAD

**Issue by iArnold** [red/red#1513]
https://gist.github.com/iArnold/2bd823cb5c2ba8abf6e0
Contains the minimal source code for this program. Only two pictures needed, (could be the same)
Now selecting one image to drag around makes it disappear., It should be placed on top so it drags over the other image.

Second issue: After selecting and removing one image, drag the window around on the screen. The remaining image stays on its place on the screen.

**Comment by Oldes** [comment]
The issue is not related to images, but that removing from ```pane``` starts making problems... here is more simplified test: https://gist.github.com/Oldes/5b549aa56391542a9b5d

**Comment by Oldes** [comment]
More issues... 
1. having in my code ```piece-panel/color: none``` with type ```base```, it display no content
2. switch ```piece-panel/type``` to ```panel``` and using image in ```piece-A``` instead of color prevents the ```piece-B``` to be over even with ```swaping```, which works with just colors.

**Comment by Oldes** [comment]
```piece-panel/type``` with ```base``` prevents displaying images, is it ok?

**Comment by iArnold** [comment]
Testing this on Windows 8 I can see no images, where on WIndows 7 I did see them.

**Comment by iArnold** [comment]
Testing on Win7 again, pics show, but the swap does not result in change in position (z-order), one of the pieces still drags under the other.

**Comment by iArnold** [comment]
Ok, Oldes' swapping method had another difference I didnot notice, causing this last remark. Images do get swapped and using my method to include the pieces-panel it can be done with color: none (nevertheless remains that Oldes' method should also work and not need a filled color.) 

**Also please notice the remark by Oldes on his line 26, the on-over event gets called too often.**

**Comment by iArnold** [comment]
Issue on Windows 8 still holds. Working with visible images/pieces on Windows 7, no pieces/images visible under Windows 8

**Comment by qtxie** [comment]
@iArnold @Oldes Seems it works with the latest version.

**Comment by iArnold** [comment]
I dl'd the latest zip, unpacked, started R3 view and compiled and tested. On win8 I did not see any images.

**Comment by iArnold** [comment]
Downloaded latest Red master (commit count 5702) and tested (R2 view off course not R3 my mistake above) I made the size of the panel larger than the 0x0 which helps to make the images visible on Windows 8 machine too. Dragging the images was not possible though.

**Comment by iArnold** [comment]
Win7 commit count 5748. Panel needs size to make contents (images) visible. Panel pane is not transparent. Using 'base and not 'panel is not a solution too.

**Comment by dockimbel** [comment]
The source code from Oldes (which is the only one testable, as the other ones have external dependencies), works fine now.
