### ISSUE TITLE
when closed "subwin" and "win", the console can't exit

### ISSUE THREAD

**Issue by bitbegin** [red/red#1518]
I wrote a `test.red` to test `VID` menu function, like this:

```red
Red [title: "test" needs: 'view]
win: layout [area 400x400]
win/menu: [
    "subwin" subwin
]
win/actors: make object! [
    on-menu: func [face [object!] event [event!]][
        if event/picked = 'subwin [
            view subwin
        ]
    ]
]

subwin: layout [area 100x100]

view win
```

I use `console.exe test.red` command to open the window, and click the subwin, then close subwin and win, but the console.exe cannot exit unless i press ctrl+c.

**Comment by qtxie** [comment]
It is caused by `view subwin` create another message loop. 
Using `view/no-wait subwin` will solve this issue.

**Comment by bitbegin** [comment]
seems it not be a issue. closed!
