### ISSUE TITLE
Duplicated #import

### ISSUE THREAD

**Issue by Oldes** [red/red#1530]
When one does ```#import ["kernel32.dll" stdcall [ GlobalAlloc: "GlobalAlloc" [..]]]``` in one file and in second the same, it is currently imported twice.

Better would be to filter out duplicate import if the spec is same and throw an error or warning, when the spec for the import is different.

**Comment by dockimbel** [comment]
Fixing note: the check needs to be done in the compiler rather than linker and if the specs are the same, just drop the new imported function with no error.

**Comment by dockimbel** [comment]
The duplicated import are now dropped, though, it is not possible to check if the provided specs are the same as the information is not kept during the compilation, so it would require a new data-structure. I'm not sure if it is worth the trouble.
