### ISSUE TITLE
Newly opened window has offset 0x0 and controls are out of screen

### ISSUE THREAD

**Issue by rebolek** [red/red#1531]
If I create new layout and open it with `show`, window is displayed in top-left corner and controls are not visible, so I’m not able to move the window. Setting offset manually before show solves this but it would be nice if this was done automatically.

Example code:

```
win: layout [
	below
	button "Open window" [
		show layout [
			text "new window"
		]
	]
]
view win
```

**Comment by dockimbel** [comment]
You should be using `view` and not `show` to open a new window, as `show` is low-level and won't do any pre-processing for you.
