### ISSUE TITLE
WISH: SPLINE in Draw Dialect. 

### ISSUE THREAD

**Issue by JerryTsai** [red/red#1543]
I would like to have SPLINE support in the Draw Dialect. Just like REBOL 3 does in this page: http://rebol.com/r3/docs/view/draw-curves.html

**Comment by dockimbel** [comment]
We should be able to draw them using the Bezier curves support we already have, though I am not sure how to handle the `segmentation` argument.

**Comment by JerryTsai** [comment]
I guess it's "Composite Bézier curve" https://en.wikipedia.org/wiki/Composite_B%C3%A9zier_curve
