### ISSUE TITLE
[linux/fish-shell] Red either fails or runs depending on the way it is called

### ISSUE THREAD

**Issue by xaduha** [red/red#1547]
one@voidlinux ~> pwd
    /home/one
    one@voidlinux ~> which red
    /usr/bin/red
    one@voidlinux ~> red
    PROGRAM ERROR: Invalid encapsulated data.
    one@voidlinux ~> /usr/bin/red
    --== Red 0.5.4 ==--
    Type HELP for starting information.

    red>>

I'm using fish-shell, so it probably has something to do with the environment. Still, something is fishy.

    one@voidlinux ~> env | sort > env1.txt
    one@voidlinux ~> bash
    [one@voidlinux ~]$ env | sort > env2.txt
    [one@voidlinux ~]$ diff env*
    16c16
    < SHLVL=2
    ---
    > SHLVL=3
    22a23
    > _=/usr/bin/env

Bottomline, works under bash, doesn't work under fish when called without specifying the absolute path.

~~Doesn't happen with `red-054` or the automated build that I previously used, commit 7526673.~~

EDIT: Having a red binary in a current folder allows it to launch normally, `red` and `./red` both.

**Comment by xaduha** [comment]
I don't know if it's in any way helpful, but other errors I had with this

    bash-4.3# red -d
    *** Driver Internal Error: Access Error : Bad file path: //.red/
    *** Where: throw-on-error
    *** Near:  [make-dir temp-dir]

and 

    # red -d
    ** Script Error: Invalid compressed data - problem: -3
    ** Near: script: decapsulate
    if none? script

**Comment by xaduha** [comment]
Looks like it's an old issue, related to #543.

**Comment by spinningarrow** [comment]
I just got this issue on macOS with the fish shell. Should I reopen it?

**Comment by dockimbel** [comment]
@spinningarrow Have you looked at the linked issue https://github.com/red/red/issues/543 ?

**Comment by spinningarrow** [comment]
Yes, I did. That one is closed too and I couldn't really find a proper resolution for it (other than creating an alias to it, if I understood correctly). What I'm trying to say is - is this something red can fix from its side; or failing that, provide an error message to the user when it's started incorrectly what the workaround is?

I'm also not sure why it works fine with bash but not with fish - what's the difference in the way the binary is invoked?

**Comment by gour** [comment]
> I'm also not sure why it works fine with bash but not with fish - what's the difference in the way the binary is invoked?

I also wonder about it?

For now, I solved the issue, by having Red executable in my `PATH` and creating fish function `~/.config/fish/functions/red.fish` with the following content:

```
function red
    ~/bin/red-063 $argv
end
```

**Comment by programandala-net** [comment]
> I'm also not sure why it works fine with bash but not with fish - what's the difference in the way the binary is invoked?

i have tried all shells i usually have installed.  beside fish (my default shell), the problem happens also with dash, es and rc, while bash, nu and zsh work fine:

- [x] bash
- [ ] dash
- [ ] es
- [ ] fish
- [x] nu
- [ ] rc
- [x] zsh 

as @gour suggested, a workaround is creating a fish wrapper function in <~/.config/fish/functions/> for the red compiler.  in my case:

```fish
function redc
   ~/.local/bin/redc $argv
end
```

**Comment by greggirwin** [comment]
Thanks for the test results!
