### ISSUE TITLE
WISH: `enter` event

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1548]
A new `enter` event:

Name | Input type | Cause
----- | --------- | -----------
**enter**	| keyboard | Enter key is pressed down.

This effect can currently be achieved on a field in Red using:
```
view [field on-key [if event/key = #"^M" [print {Enter key pressed.}]]]
```

However, if there were an `enter` event:
```
view [field on-enter [print {Enter key pressed.}]]
```
It could then be designated the default event for `field` (instead of the current `change`) as in Rebol:
```
view [field [print {Enter key pressed.}]]
```

**Comment by dockimbel** [comment]
Implemented in commit [e3ff482f](https://github.com/red/red/commit/40033fd0bd6b3f79d57463c4a814ec4be3ff482f).
