### ISSUE TITLE
`do` `file!` not relative to the currently interpreted file

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1550]
If a file is being interpreted, it should `do` files relative to itself as Rebol does. Currently, this is not the case:

Consider the following 4 files:

`H:\a.red`
```
Red []

do %folder/b.red
```

`H:\folder\b.red`
```
Red []

do %c.red
```

`H:\folder\c.red`
```
Red []

print "correct result"
```

`H:\c.red`
```
Red []

print "incorrect result"
```

The current result is:
```
H:\>red a.red
incorrect result
```

**Comment by WiseGenius** [comment]
The same is also true of `load`, `save`, `read` and `write`.

Consider the following 2 files:

`H:\a.red`
```
Red []

do %folder/b.red
```

`H:\folder\b.red`
```
Red []

save %saved-file.txt "saved text"
print load %saved-file.txt

write %written-file.txt "written text"
print read %written-file.txt
```

The printed result of `%a.red` is correct:
```
H:\>red a.red
saved text
written text
```

But the resulting files are:
`H:\saved-file.txt`
`H:\written-file.txt`

Not where they should be, which is:
`H:\folder\saved-file.txt`
`H:\folder\written-file.txt`

**Comment by dockimbel** [comment]
Implemented by commit https://github.com/red/red/pull/2071/commits/fdee65883ba7cb0581ce0560f42aec1cfff23738.

**Comment by WiseGenius** [comment]
Passes all tests I can think of when both interpreted and compiled on both Windows XP and Windows 7.
Yay!
