### ISSUE TITLE
Red console cannot be maximised

### ISSUE THREAD

**Issue by meijeru** [red/red#1560]
I have compiled `gui-console.red` with the latest `Red.exe` and `-t Windows` under Windows 10. The resulting `.exe` runs OK but when I maximise the console window, the effectively usable surface does not expand. It *does* expand when I resize the window.

**Comment by meijeru** [comment]
Is there any reason why this is labeled as a *wish*  rather than a *bug*?

**Comment by dockimbel** [comment]
@meijeru The maximizing support is a feature we were planning to add. So strictly speaking, it's not a bug, as it currently behave as it should. ;-)
