### ISSUE TITLE
"Hello World" compilation crashes with Rebol/Core

### ISSUE THREAD

**Issue by Mennohexo** [red/red#1561]
Hi there. I am new in RED.
Wanna start the simple "Hello World" program in the RED-GitHub repository.

Look at the results.  What have a made false ?  My OS: WinXP

`REBOL/Core 2.7.8.3.1 (1-Jan-2011)
Copyright 2011 REBOL Technologies
REBOL is a Trademark of REBOL Technologies
All rights reserved.

Finger protocol loaded
Whois protocol loaded
Daytime protocol loaded
SMTP protocol loaded
ESMTP protocol loaded
POP protocol loaded
IMAP protocol loaded
HTTP protocol loaded
FTP protocol loaded
NNTP protocol loaded
>> do/args %red.r "%tests/hello.red"
Script: "Red command-line front-end" (none)
Script: "Encap virtual filesystem" (21-Sep-2009)
**** Script Error: Feature not available in this REBOL**
** Where: context
** Near: SECURITY_ATTRIBUTES: make struct! [
    nLength [integer!]
    lpSecurityDescriptor [integer!]
    bInheritHandle [int...
>>`

I have strictly followed the instructions on Github  RED package.

Need help in this case.

If the start functions , than i can later try to "compile" it.

**Comment by PeterWAWood** [comment]
I believe you questions have been answered on the Red-Lang mailing list.

I am keeping this issue open as the Red toolchain now requires Rebol/View and the GitHub read links to Rebol/Core.

In future, we would appreciate if you could first raise such issues on the Red-Lang mailing list and get confirmation that there is a problem before opening a GitHub issue.

**Comment by nc-x** [comment]
@Mennohexo There is another way to use Red. Just download the red binaries from http://www.red-lang.org/p/download.html?m=1
There are downloads for both last major release 0.5.4 as well as latest master branch.

**Comment by PeterWAWood** [comment]
@dockimbel @qtxie I was going to simply change the link in the GitHub readme but wanted to check if Rebol/View pops up an option to be installed when you first run it.

**Comment by dockimbel** [comment]
This is a regression, we should be able to run the Red toolchain from Rebol/Core.

**Comment by dockimbel** [comment]
Tested on Rebol/Core 2.7.6 and 2.7.8, works fine now. The shortly flashing DOS console window is required in such configuration (running Red from sources with /Core).
