### ISSUE TITLE
issues with `selected` when window changes focus

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1563]
#### Issue A: `selected` not updated

Example 1:
```
view [field]
```
If the resulting field is clicked in, and the window loses focus and is brought back again, the field loses focus and must be clicked in again.

Example 2:
```
l: layout [
	a: field "a"
	b: field "b"
]
l/selected: a
view l
```
If field `b` is clicked in, and the window loses focus and is brought back again **by using Alt-Tab** or **by selecting it from the taskbar** field `a` has the cursor in it instead of field `b`.
If field `b` is clicked in, and the window is closed, `probe l/selected` indicates that field `a` is still selected.

#### Issue B: selected face loses focus if window clicked into focus

In Example 2, if the window loses focus and is brought back again **by clicking on the window**, no field has the cursor in it, regardless of which one had it before.

Both issues apply to both `field` and `area` in both Windows XP and Windows 7.

**Comment by qtxie** [comment]
Issue B should be fixed in latest commit.

**Comment by dockimbel** [comment]
Issue A and B working fine now.
