### ISSUE TITLE
gui-console history scrolls in wrong order

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1567]
gui-console history scrolls in wrong order

Write some lines as follows:
```
red>> ;1
red>> ;2
red>> ;3
red>> ;4
red>> ;5
red>> ;6
red>> ;7
red>> ;8
red>> ;9
```
Scroll through the history randomly with the up and down keys, and you'll soon discover that the behaviour is not straightforward each time the direction is changed:

Expected behaviour (as in old console):

&uarr;	`;9`
&uarr;	`;8`
&uarr;	`;7`
&uarr;	`;6`
&uarr;	`;5`
&darr;	`;6`
&darr;	`;7`
&darr;	`;8`
&uarr;	`;7`
&uarr;	`;6`

Actual behaviour in gui-console:

&uarr;	`;9`
&uarr;	`;8`
&uarr;	`;7`
&uarr;	`;6`
&uarr;	`;5`
&darr;	`;4`
&darr;	`;5`
&darr;	`;6`
&uarr;	`;7`
&uarr;	`;6`

I suspect this may be related to #1562?

**Comment by qtxie** [comment]
Should be fix now.
