### ISSUE TITLE
Regression: crash when view image!

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1570]
```
red>> img: make image! [100x100 255.0.0]
== make image! [100x100 #{
FF0000FF0000FF0000FF0000FF0000FF0000FF0000...
red>> view [image img]

*** Runtime Error 1: access violation
*** at: 004702FFh
```

Same result when replacing `image` with `base`.

**Comment by dockimbel** [comment]
Cannot reproduce the crash, works fine here on Win7, both from CLI and GUI consoles.

**Comment by WiseGenius** [comment]
Hmm. I just downloaded the latest source, and I'm still getting the crash on both consoles in both Windows XP and Windows 7.

**Comment by nc-x** [comment]
I can reproduce the crash on windows 8.1 with latest master binaries.

**Comment by dockimbel** [comment]
Tried with master binary, cannot reproduce it either, the window with the image shows up with no issue...strange, will try on another box.

**Comment by nc-x** [comment]
@dockimbel console compiled in debug mode gives - 
```
red>> img: make image! [100x100 255.0.0]
== make image! [100x100 #{
FF0000FF0000FF0000FF0000FF0000FF0000FF0000...
red>> view [image img]
opts: context [type offset size text color image f...

*** Runtime Error 1: access violation
*** in file: /C/Users/ABC/Desktop/red-master/environment/console/modules/view/backends/windows/gui.reds
*** at line: 61
***
***   stack: gui/get-face-values 000D04C2h
***   stack: gui/BaseWndProc 000D04C2h 5 0 6553700
```

**Comment by qtxie** [comment]
I can reproduce it on Win 10.
