### ISSUE TITLE
Regression: group-box size ignores content

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1571]
Unlike before, `group-box` has a fixed size of about `200x200` no matter how big the content is:
```
view [
	group-box [
		text "This is a really long text. I don't think the group-box will accomodate it like it used to."
		return
		field "This is a really long field. I don't think the group-box will accomodate it either."
		return
		area "Even this area isn't safe."
	]
]
```
Or how small:
```
view [
	group-box [
		text "Granny, what large size you have!"
	]
]
```
The size can still be specified in VID, though:
```
view [
	group-box [
		text "Hello, World!"
	] 100x100
]
```

**Comment by dockimbel** [comment]
Good catch, I knew there was a good reason why those widgets didn't have a default size in the first place. ;-)

**Comment by WiseGenius** [comment]
In the second example, the `group-box` is still about `200x200` and doesn't shrink to the smaller size like it used to.

**Comment by WiseGenius** [comment]
Also, removing the `area` from the first example makes `group-box` revert back to being too small:
```
view [
    group-box [
        text "This is a really long text. I don't think the group-box will accomodate it like it used to."
        return
        field "This is a really long field. I don't think the group-box will accomodate it either."
    ]
]
```

**Comment by dockimbel** [comment]
Should be the right fix now.
