### ISSUE TITLE
VID: size keyword doesn't work

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#1578]
view [ size 200x200 base 1000x1000 ]

The windws size is 1000x1000, instead of 200x200

**Comment by WiseGenius** [comment]
In the meantime, this way works:
```
view/options [base 1000x1000][size: 200x200]
```

**Comment by JenniferLee520** [comment]
Thanks. Using /options does work.
However, SIZE Keyword in VID used to work until one day ago.

**Comment by dockimbel** [comment]
Indeed, seems like a recent regression.
