### ISSUE TITLE
`title` ignored in `view/options`

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1580]
This works:
```
view [title "Hello, World!" text "Χαῖρε, κόσμε!" font-size 24]
```

This doesn't:
```
view/options [text "Χαῖρε, κόσμε!" font-size 24] [title: "Hello, World!"]
```
Instead of `Hello, World!`, the title is `Red: untitled`.

**Comment by dockimbel** [comment]
`options` gives you direct access to window's facets, so there is no `title` property there, use `text` instead. Maybe `/facets` would be a more appropriate refinement name?.

**Comment by WiseGenius** [comment]
Oops!
I've used it properly in the past, and it's hard to tell whether I forgot the facet was called `text` or if I forgot it was setting facets. So I'm not sure whether or not changing the name would have prevented my mistake.
`/facets` does seem like a better name, though, if that's all it is.
