### ISSUE TITLE
Can’t catch Ctrl+Shift+<key>

### ISSUE THREAD

**Issue by rebolek** [red/red#1586]
Ctrl+[key] and Shift+[key] work, but Ctrl+Shift+[key] does not. You can try it with the following code, it shows `none` instead of [key]:

```
Red [Needs: 'View]

w: layout [text "press Ctrl+Shift+<key>"]

w/actors: object [
	on-key: func [
		face [object!] 
		event [event!]
	] [
		print ["on key:" mold event/key]
		'stop
	]
]

view w
```

**Comment by dockimbel** [comment]
It works since the merge of `key-down` branch.
