### ISSUE TITLE
GROUP-BOX' text is changed when shown for second time

### ISSUE THREAD

**Issue by rebolek** [red/red#1596]
If you have GROUP-BOX in some subwindow, close it and open it again, GROUP-BOX text is changed to text from its content. See this code:

```
Red [
	Needs: 'View
]

view [
	button "show" [
		view [		
			group-box "Original text" [
				field "New text"
			]
			button "close" [unview]
		]
	]
]
```

Press [SHOW], then [CLOSE], then [SHOW] again. GROUP-BOX label now says "New text" instead of "Original text".

**Comment by rebolek** [comment]
Probably related to #1565

**Comment by meijeru** [comment]
Are you even supposed to call `view` from within an action?

**Comment by rebolek** [comment]
How else would you open a sub window?

**Comment by WiseGenius** [comment]
For me, previous builds give this issue, but this behaviour has since changed so that I get the same thing both times: It's a blank group-box with the correct text, but no contents:

![blank group-box](https://cloud.githubusercontent.com/assets/7657453/12868154/6aad9330-cd4c-11e5-82c9-40e538e964bc.png)

Same on both Windows XP and Windows 7. This is basically #1592.

**Comment by meijeru** [comment]
Could one define a sub-window by `layout` and open it by `show`? Or does that omit crucial steps?

**Comment by dockimbel** [comment]
Until recently, `view` was initializing the View engine, but now that is automated. `show` is fine now, though, it is a low-level way to open a window, so you don't get any default features provided by View (like a default title or automatic centering).

**Comment by dockimbel** [comment]
@rebolek The right way to open a sub-window is to use `view/no-wait` to avoid creating a new event loop.

**Comment by dockimbel** [comment]
It seems to be related to Red's UTF-16 internal conversion and the usage of a cache buffer (probably a cache corruption).
