### ISSUE TITLE
Date or Time in header gives syntax error.

### ISSUE THREAD

**Issue by RedJosh** [red/red#1599]
red>> test: read/lines %myfile.red
== ["Red [" {^-Title: "form-date"} {^-Author: "Satish" } "^-Date: 26-A
red>> foreach line test [print line]
Red [
    Title: "form-date"
    Author: "Satish" 
    Date: 26-Apr-2007 
]

print "my first Red program"
red>> do %myfile.red
*** Syntax error: invalid integer at {26-Apr-2007 ^/]^/^/print "my first Red pro
*** Where: do

**Comment by dockimbel** [comment]
Date and time datatypes are not yet implemented in Red. Please use strings for now rather to store such values. Time! datatype is scheduled for 0.6.1, date! is not scheduled yet.
