### ISSUE TITLE
load into text field crashes Red

### ISSUE THREAD

**Issue by RedJosh** [red/red#1600]
Red [title: "test" needs: 'view]
view [
    below
    a: area                               ; an area widget labeled 'a
    f: field                              ; a field widget labeled 'f
    across
    button "Show" [print a/text]
    button "Save" [write %somedatafile.txt a/text]
    button "Load" [f/text: read %somedatafile.txt]
]
Click on Load crashed Red. In windows 10 and on in Wine

**Comment by RedJosh** [comment]
Commented that line and solved
Red [    Title: "form-date"     
    Author: "Satish"     
;    Date: 26-Apr-2007 
]

print "my first Red program"
red>> do %myfile.red
my first Red program

**Comment by dockimbel** [comment]
Yes, it's the same issue as #1599.

When you say "crash", do you mean an application crash or just an error reported (with the program eventually exiting)?

**Comment by RedJosh** [comment]
My bad. I mixed comment on #1599 here.

Application company crashed when I clicked on "load"

**Comment by WiseGenius** [comment]
If I paste the code in the console, and click `Load` (when `somedatafile.txt` doesn't exist) then it works as expected:
```
*** Access error: cannot open: somedatafile.txt
*** Where: read
```

If I click `Save` it saves the data, but then when I click `Load`, the console crashes with:
```
*** Runtime Error 1: access violation
*** at: 00410F3Dh
```

If I replace the `Load` button's block with `[f/text: "Hello, World!"]` it works as expected.

Same results in Windows XP and Windows 7.

**Comment by WiseGenius** [comment]
Also, if I replace the `Show` button's block with `[print read %somedatafile.txt]`, then clicking the `Show` button works as expected too, on both OSes.

**Comment by RedJosh** [comment]
If I replace the Load button's block with  [f/text: read/lines %somedatafile.txt], it does not crash.
 If [f/text: read/lines %somedatafile.txt print f], it works as expected. 
However, it gives long list of messages as below.
 `type:` 'field
offset: 10x170
size: 80x24
text: "Hello World"
image: none
color: none
menu: none
data: none
enable?: true
visible?: true
selected: none
flags: none
options: none
parent: make object! [
    type: 'window
    offset: 573x244
    size: 220x234
    text: "Red: untitled"
    image: none
    color: none
    menu: none
    data: none
    enable?: true
    visible?: true
    selected: none
    flags: none
    options: none
    parent: none
    pane: [make object! [
        type: 'area
        offset: 10x10
        size: 150x150
        text: none
        image: none
        color: none
        menu: none
        data: none
        enable?: true
        visible?: true
        selected: none
        flags: none
        options: none
        parent: make object! [...]
        pane: none
        state: [1179698 0 none false]
        edge: none
        para: none
        font: none
        actors: none
        extra: none
        draw: none
                    ] make object! [...] make object! [
        type: 'button
        offset: 10x194
        size: 60x30
        text: "Show"
        image: none
        color: none
        menu: none
        data: none
        enable?: true
        visible?: true
        selected: none
        flags: none
        options: none
        parent: make object! [...]
        pane: none
        state: [852578 0 none false]
        edge: none
        para: none
        font: none
        actors: make object! [
            on-click: func [face [object!] event [event! none!]][print a/text]
        ]
        extra: none
        draw: none
                    ] make object! [
        type: 'button
        offset: 80x194
        size: 60x30
        text: "Save"
        image: none
        color: none
        menu: none
        data: none
        enable?: true
        visible?: true
        selected: none
        flags: none
        options: none
        parent: make object! [...]
        pane: none
        state: [1245272 0 none false]
        edge: none
        para: none
        font: none
        actors: make object! [
            on-click: func [face [object!] event [event! none!]][write %somedatafile.txt a/text]
        ]
        extra: none
        draw: none
                    ] make object! [
        type: 'button
        offset: 150x194
        size: 60x30
        text: "Load"
        image: none
        color: none
        menu: none
        data: none
        enable?: true
        visible?: true
        selected: none
        flags: none
        options: none
        parent: make object! [...]
        pane: none
        state: [590470 0 none false]
        edge: none
        para: none
        font: none
        actors: make object! [
            on-click: func [face [object!] event [event! none!]][f/text: "Hello World" print f]
        ]
        extra: none
        draw: none
                    ]]
    state: [1245762 0 none true]
    edge: none
    para: none
    font: none
    actors: none
    extra: none
    draw: none
        ]
pane: none
state: [459400 0 none false]
edge: none
para: none
font: none
actors: none
extra: none
draw: non

**Comment by WiseGenius** [comment]
@RedJosh That looks correct. Try replacing `print f` with `print f/text` if you didn't want all those objects printed.

**Comment by RedJosh** [comment]
@WiseGenius Yes.
[f/text: read/lines %somedatafile.txt print f/text] works.
somedatafile.txt  contains only this -> aaaa
It prints correctly into console but does not show it in F field. 

If I replace the load button's block with ][f/text: "Hello World" print f/text]
It shows "Hello World" in f field also.

**Comment by WiseGenius** [comment]
@RedJosh `read/lines` returns a `block!` of `string!`s rather than a `string!` so that would explain why `[f/text: read/lines %somedatafile.txt print f/text]` fails to change the visual content of `f` and yet `print f/text` seems to print the contents of `%somedatafile.txt` regardless of what is being shown in `f`, until `f`'s content is changed again.

So the real question is still, “Why does `[f/text: read %somedatafile.txt]` crash?”.

**Comment by RedJosh** [comment]
and I pulled this code as is from @Nick's [http://redprogramming.com/Getting%20Started.html](url)
So was it working earlie
