### ISSUE TITLE
*** Error: cannot access argument file - When I start in Wine under Ubuntu 15.10

### ISSUE THREAD

**Issue by RedJosh** [red/red#1602]
`*** Error: cannot access argument file
--== Red 0.5.4 ==-- 
Type HELP for starting information. 

red>>
`

Not critical issue maybe, since GUI console opens

**Comment by dockimbel** [comment]
How do you start it in Wine? Could you provide the full command-line?

**Comment by RedJosh** [comment]
satish@satish-Aspire:~/Downloads/red$ ./red-11feb16-9ff1262.exe
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x401, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x402, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x403, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x404, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x405, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x406, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x407, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x408, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x409, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x40a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x40b, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x40c, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x40d, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x40e, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x40f, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x410, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x411, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x412, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x413, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x414, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x415, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x416, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x417, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x418, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x419, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x41a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x41b, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x41c, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x41d, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x41e, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x41f, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x420, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x421, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x422, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x423, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x424, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x425, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x426, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x427, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x429, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x42a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x42b, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x42c, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x42d, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x42f, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x436, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x437, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x438, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x439, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x43e, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x43f, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x440, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x441, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x443, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x444, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x446, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x447, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x449, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x44a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x44b, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x44e, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x44f, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x450, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x452, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x456, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x457, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x45a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x465, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x47e, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x48f, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x490, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x491, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x492, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x494, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x801, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x804, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x807, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x809, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x80a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x80c, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x810, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x813, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x814, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x816, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x81a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x81d, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x82c, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x83c, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x83e, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x843, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0xc01, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0xc04, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0xc07, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0xc09, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0xc0a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0xc0c, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0xc13, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0xc1a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x1001, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x1004, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x1007, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x1009, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x100a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x100c, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x1401, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x1404, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x1407, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x1409, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x140a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x140c, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x1801, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x1809, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x180a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x180c, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x1c01, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x1c09, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x1c0a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x2001, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x2009, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x200a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x2401, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x2409, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x240a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x2801, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x2809, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x280a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x2c01, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x2c09, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x2c0a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x3001, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x3009, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x300a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x3401, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x3409, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x340a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x3801, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x380a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x3c01, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x3c0a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x4001, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x400a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x440a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x480a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x4c0a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x500a, 0000: semi-stub!
fixme:keyboard:X11DRV_ActivateKeyboardLayout setting keyboard of different
locales not supported
fixme:keyboard:X11DRV_ActivateKeyboardLayout 0x4090409, 0000: semi-stub!
fixme:hnetcfg:fw_profile_get_FirewallEnabled 0x13f300, 0x33fd6c
Compiling compression library...
Compiling Red GUI console...
satish@satish-Aspire:~/Downloads/red$ fixme:dwmapi:DwmIsCompositionEnabled
0x33fc78


Red GUI Console opened. Below is what seen in it.-

*** Error: cannot access argument file
--== Red 0.5.4 ==--
Type HELP for starting information.

red>>


regards

On Wed, Feb 10, 2016 at 11:09 AM, Nenad Rakocevic <notifications@github.com>
wrote:

> How do you start it in Wine? Could you provide the full command-line?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/red/red/issues/1602#issuecomment-182207530>.
>



-- 
regards
Satish Joshi

**Comment by RedJosh** [comment]
This issue did not occur in the latest build of 21 Feb. There were no starting messages also, except these two..
Compiling compression library... 
Compiling Red GUI console...

@dockimbel Did you solve this or it corrected due to some other changes?

![a](https://cloud.githubusercontent.com/assets/17100026/13202251/0d877288-d8ba-11e5-9f20-fbb40f9b76e2.png)

**Comment by dockimbel** [comment]
@RedJosh It was probably solved by [this fix](https://github.com/red/red/commit/04deb73e0d2a1915735c73d1c404db7bd9508691) from @qtxie.

**Comment by RedJosh** [comment]
@dockimbel Although I do not understand why the other black terminal remains open. I cannot do any thing with it. If I close it, Red Gui closes. I started Red by double-click on the Red exe. 

If I start Red from X terminal - with this command ..
wine /home/satish/Downloads/red/red-21feb16-667d309.exe
I get lots of messages after which Red Gui console opens properly as above but it is detached from X terminal. Thereafter, I can close the X terminal and Red Console remains open.

Just an observation.
