### ISSUE TITLE
On capturing phase, 'Base stops passing events to its children if the color of the 'Base is none.

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#1604]
I make 'Base C a child of 'Base P, and 'Base C has the 'Drag-on option. If the color of 'Base P is none and there is nothing Drawn on 'Base P under the same area of 'Base C, 'Base C will not be able to drag. ... I guess the capturing phase has a flaw.

**Comment by qtxie** [comment]
Which OS do you use?

**Comment by WiseGenius** [comment]
@JenniferLee520 If you post a minimal code example, I will test it here too.

**Comment by JenniferLee520** [comment]
My OS is Windows 10.

**Comment by qtxie** [comment]
Should be fixed now.
