### ISSUE TITLE
`to number! "1"` crashes Red

### ISSUE THREAD

**Issue by xqlab** [red/red#1613]
`to number! "1"`
and 
`to series!  "1"`
crashes Red without an error message

**Comment by WiseGenius** [comment]
For both lines, I get:
```
*** Runtime Error 1: access violation
*** at: 004197BDh
```
When interpreted on both Windows XP and Windows 7.

**Comment by nc-x** [comment]
@WiseGenius cli-console displays error. But Gui-Console crashes...

**Comment by WiseGenius** [comment]
@nc-x The GUI console never displays such errors when it crashes. That's why if there is a crash I use the CLI console in CMD to find the errors I may have missed otherwise, remembering to compile it with `Needs: 'View` in the header to test GUI stuff.

**Comment by RedJosh** [comment]
Both consoles crash under Wine also. No error displayed

**Comment by dockimbel** [comment]
`to` is only partially implemented.

**Comment by dockimbel** [comment]
`to` has been now fully implemented, and those above cases are now raising proper errors.
