### ISSUE TITLE
Red Gui Console did not start in Windows 2003 Server X64

### ISSUE THREAD

**Issue by RedJosh** [red/red#1617]
![redgui](https://cloud.githubusercontent.com/assets/17100026/12976820/baf47310-d0ec-11e5-9fa4-c8bf8c433993.png)

**Comment by WiseGenius** [comment]
Windows XP once had a [similar problem](https://gitter.im/red/red/gui-branch?at=563accc00800da954de6c306) with `SetGestureConfig` which was fixed.

**Comment by dockimbel** [comment]
@RedJosh If your Windows flavor does not have gesture support, just compile with the `-t WindowsXP` target to avoid linking that API.

In the above case, the console is auto-compiled by Red executable, so it needs to be adjusted for Windows 2003 Server.

**Comment by dockimbel** [comment]
@RedJosh Could you please confirm that this fix works for you (using the latest Red  master build)?

**Comment by RedJosh** [comment]
@dockimbel The latest build (red-15feb16-230e521.exe) compiled Gui console successfully.
There was an issue with the cursor initially. Cursor remained 2 characters to the left. 
The issue was solved by downloading and installing 'Consolas' font in windows.
![red](https://cloud.githubusercontent.com/assets/17100026/13056186/bf18e1c4-d439-11e5-84e2-d89b96ef2238.png)

**Comment by dockimbel** [comment]
@RedJosh Great!
