### ISSUE TITLE
Cursor remains two characters left in Gui console under Wine. Typing becomes difficult

### ISSUE THREAD

**Issue by RedJosh** [red/red#1618]
red-11feb16-9ff1262.exe started from X terminal in Ubuntu 15.10

In the snapshot below, cursor can be seen between b and e of number.

![redgui](https://cloud.githubusercontent.com/assets/17100026/12977175/3ae95700-d0ef-11e5-8d77-042c79fe2ea7.png)

**Comment by RedJosh** [comment]
Cursor became al right after installing Consolas font in Wine.

**Comment by x8x** [comment]
Instructions to install Wine with Consolas font on OSX:
```
brew install wine --without-x11 --devel
brew install winetricks
# set Wine to default to Windows 7
winetricks win7
# install Consolas font
winetricks consolas
```
almost ready to go, download latest Windows Red build and lunch it with wine:
```
curl -o red.exe http://static.red-lang.org/dl/auto/win/red-19feb16-f834e41.exe
wine red.exe
```
[should be similar with apt-get (Debian) and pacman (Arch Linux)]

**Comment by RedJosh** [comment]
I recommend including these instructions in the Red Installation instructions and thereafter close this issue.
