### ISSUE TITLE
wrap inverted for text face

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1619]
When clicking the "Wrap" button from the following code, the text is unwrapped, and wrapped when clicking "No Wrap":

```
longer: {The quick brown fox jumps over the lazy dog.}
view [
    f: text "Hello, World!" wrap
    return
    button "Wrap" [f/text: longer f/para/wrap?: yes]
    button "No Wrap" [f/text: longer f/para/wrap?: no]
]
```

Both in Windows XP and Windows 7.
All other faces seem to ignore `wrap?`.

**Comment by meijeru** [comment]
Same for Windows 10. The effect is even clearer if you adjust the size of the window to show the full text (default window size on W10 is too small).

**Comment by dockimbel** [comment]
It works fine now.
