### ISSUE TITLE
Cannot set SELECTED for TEXT-LIST before it’s shown

### ISSUE THREAD

**Issue by rebolek** [red/red#1620]
I’d like to be able to select item in TEXT-LIST before it’s shown for the first time. Example code:

```
Red [
	Needs: 'View
]

l: layout [
	t: text-list data ["one" "two" "three"]
]
t/selected: 2

view l
```

**Comment by dockimbel** [comment]
That feature is not supported. 

Just FYI, you can write the above code in a more simpler way:
```
view [
    t: text-list data ["one" "two" "three"]
    do [t/selected: 2]
]
```
