### ISSUE TITLE
Passing function! in object! cannot be compiled

### ISSUE THREAD

**Issue by rebolek** [red/red#1621]
Consider this code:

```
o: object [f: func [v] [v + 1]]
f: :o/f
print f 1
```
When run from interpreter, it prints `2` as expected. However, when you try to compile it, you get `*** Red Compiler Internal Error: Script Error : copy expected value argument of type: series port bitset`.

**Comment by meijeru** [comment]
It compiles OK here with Red version of 31-Jan-2016 under W10. So maybe a regression?

**Comment by nc-x** [comment]
Works OK for me as well on latest master binaries...

**Comment by PeterWAWood** [comment]
Compiles and runs as expected for me using the latest master source under both OS/X and Windows 7.

**Comment by WiseGenius** [comment]
Compiles and runs here in both Windows XP and Windows 7 using both Rebol/View and Rebol/Core with the latest Red master sources since February 14.

**Comment by rebolek** [comment]
Hm, thanks for report, I’ll try again with latest version.

**Comment by dockimbel** [comment]
Compiles and runs fine on latest version.
