### ISSUE TITLE
console-call has stopped working

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1625]
Attempting to compile `%tests/console-call.red` gives an error beginning with:

```
*** Compilation Error: include file not found: help.red
```

Once this is remedied with `%environment/console/help.red`, the compilation succeeds. However, when running the executable, any line typed crashes the console with:

```
red>> print "Hello, World!"
*** Syntax error: invalid none at "^@"
*** Where: do
*** Stack: do-console while unless switch do code load either transcode unless ctx168~throw-error cause-error do
```

Even an empty line:

```
red>>
*** Syntax error: invalid none at "^@"
*** Where: do
*** Stack: do-console while unless switch do code load either transcode unless ctx168~throw-error cause-error do
```

But not a commented line:

```
red>> ;Wow! But this works!?
red>>
```

**Comment by dockimbel** [comment]
`%tests/console-call.red` will be deprecated in 0.6.0, as CALL feature will be provided as a module later, once the Unicode support will be properly implemented. So, we won't upgrade that script.

**Comment by dockimbel** [comment]
As `call` feature will be integrated inside Red runtime, the `%console-call.red` script will be removed.
