### ISSUE TITLE
Console history lost after supplying empty line (ENTER)?

### ISSUE THREAD

**Issue by meijeru** [red/red#1626]
Not sure if this is a feature :-) A single empty command line (`red>><ENTER>`) is sufficient to make the up and down arrows show nothing anymore. However, the history is not gone away, and it reappears when a non empty input line is supplied!

**Comment by nc-x** [comment]
@meijeru Which version are you on? Works fine for me on latest master binaries...
This was supposedly fixed earlier https://github.com/red/red/issues/1562

**Comment by meijeru** [comment]
I still use the 31-Jan version. Did not check far enough back to see if this was a solved issue. Sorry!

**Comment by dockimbel** [comment]
Confirming that it works fine with current version.
