### ISSUE TITLE
resize issue C

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1646]
```
red>> view l0: layout [a1: area "Hello, World!" b: button "resize" [l0/size: 100x100]]
red>> ;10 works as expected
red>> view l1: layout [a1: area "Hello, World!" a2: area "Χαῖρε, κόσμε!" b: button "resize" [a2/size: 100x100] react [a1/size: a2/size - 20]]
red>> ;11 works as expected
red>> view l2: layout [a1: area "Hello, World!" b: button "resize" [l2/size: 100x100] react [a1/size: l2/size - 20]]
*** Script error: l2 has no value
*** Where: get
red>> view l2: layout [text "Hello, World!"]
*** Script error: l2 has no value
*** Where: get
red>> view l2: [text "Hello, World!"]
*** Error: path value must start with a word!
```
With that, it crashes.
Same on Windows XP and Windows 7.

**Comment by RedJosh** [comment]
This is working without error under Wine with 21 Feb build.

**Comment by WiseGenius** [comment]
@RedJosh Did you type all of the following in order in the same session?
```
view l2: layout [a1: area "Hello, World!" b: button "resize" [l2/size: 100x100] react [a1/size: l2/size - 20]]
view l2: layout [text "Hello, World!"]
view l2: [text "Hello, World!"]
```

**Comment by RedJosh** [comment]
@WiseGenius  You are right.-:)

red>> view l2: layout [a1: area "Hello, World!" b: button "resize" [l2/size: 100x100] react [a1/size: l2/size - 20]]
*** Script error: l2 has no value
*** Where: get
red>> view l1: layout [a1: area "Hello, World!" a2: area "Χαῖρε, κόσμε!" b: button "resize" [a2/size: 100x100] react [a1/size: a2/size - 20]]
*** Script error: l2 has no value
*** Where: get
red>> view l0: layout [a1: area "Hello, World!" b: button "resize" [l0/size: 100x100]]
*** Script error: l2 has no value
*** Where: get
red>>

**Comment by RedJosh** [comment]
@WiseGenius Type like this and see what happens
view l1: layout [a1: area "Hello, World!" a2: area "Χαῖρε, κόσμε!" b: button "resize" [a2/size: 100x100] react [a1/size: a2/size + 20]]

**Comment by WiseGenius** [comment]
@RedJosh That gives the expected result for me. They overlap a little to begin with, but I expected that since `react` is already working before the button is clicked.
