### ISSUE TITLE
gui console closed unnormally

### ISSUE THREAD

**Issue by bitbegin** [red/red#1648]
when I double click gui-console, it  closed unnormally. I use red-18feb16-58b4a59.exe from red-lang.org, and my pc is 64x win7.

**Comment by bitbegin** [comment]
The gui-console cannot be opened On my PC

```
C:\Users\95\Downloads>C:\Users\95\Downloads\red-18feb16-58b4a59.exe

C:\Users\95\Downloads>
```

**Comment by dockimbel** [comment]
Please try it again with latest commit.

**Comment by WiseGenius** [comment]
It works here now, on both Windows XP and Windows 7.

**Comment by bitbegin** [comment]
today's version works ok
