### ISSUE TITLE
WRITE/APPEND doesn't work

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#1649]
It should append the file, instead of overwriting it.

```Red
write %file.txt "123"
write/append %file.txt "456"
```

**Comment by PeterWAWood** [comment]
Which version are you using Jennifer?

It worked when I tried it using the latest master to compile a console under OS/X

```Red
red>> write %file.txt "123"
red>> read %file.txt
== "123"
red>> write/append %file.txt "456"
red>> read %file.txt
== "123456"
```

**Comment by PeterWAWood** [comment]
It also worked as expected using the gui-console on Windows 7 compiled from the latest source.

**Comment by dockimbel** [comment]
It works fine here too.

**Comment by JenniferLee520** [comment]
OK, then. I will download the latest and try. I am using MacOS.

**Comment by JenniferLee520** [comment]
OK. The latest version of Red doesn't have this problem. So, I close this ticket. Sorry for the false alarm and waste your time. I will be more cautious next time.
