### ISSUE TITLE
WISH: change cursor

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#1654]
I would like to do it automatically:

``` Red
make face! [ 
    type: 'base
    cursor: %my-cursor.png
]
```

and manually:

``` Red
set-cursor %my-cursor.png
```

**Comment by dockimbel** [comment]
System cursor support will be implemented in 0.6.1.

**Comment by JenniferLee520** [comment]
It's supported just now.

**Comment by qtxie** [comment]
We need a way to set the [hotspot](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648379(v=vs.85).aspx#_win32_The_Hot_Spot) of the cursor.
