### ISSUE TITLE
When a face is the reaction source of 2 or more faces, trying to remove a reaction relation will cause some unpredictable result.

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#1661]
When an face is the reaction source of 2 or more faces, trying to remove a reaction relation will cause some unpredictable result, because the reaction table only index the reaction source, and removing a reaction only need to indicate the source. We have no way to indicate which relation should be removed.

**Comment by dockimbel** [comment]
The reactive API has been improved and now supports more accurate removal of a given reaction. See http://doc.red-lang.org/reactivity.html
