### ISSUE TITLE
Trap integer overflow and raise error

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#1669]
Currently integer overflow is not trapped and no error is raised. An overflow error should be raised when an integer overflows.

Examples of current behaviour:
```Red
red>> add 1 2147483647
== -2147483648
red>> subtract -2 2147483647
== 2147483647
red>> negate -2147483648
== -2147483648
```

**Comment by dockimbel** [comment]
This feature has not been implemented yet. We need to decide on the detection method.

**Comment by dockimbel** [comment]
Fixed by commit https://github.com/red/red/commit/b4e73cd35df49dc91e58ba2e5918d3a9508dd857.
