### ISSUE TITLE
Drag&drop problems

### ISSUE THREAD

**Issue by rebolek** [red/red#1671]
See this code:
```
Red [
    Needs: 'View
]

system/view/auto-sync?: no

extend styles [
    cbase: [
        template: [
            type: 'base size: 100x50 color: red
            options: [drag-on: 'down]
            actors: object [
            	on-drag-start: func [f e] [f/color: yellow show f]
            	on-drag: func [f e] [print "drag"]
            	on-drop: func [f e] [f/color: red show f]
            ]
        ]
    ]
]

view [cbase "base"]
```

This code shows two problems (on some systems, confirmed by me (W7 VM) and @Pekr (W10), @dockimbel can’t replicate it (W7)):

1) `on-drag` doesn’t work - "drag" is not printed
2) the face disappears on `on-drop`.

**Comment by dockimbel** [comment]
@rebolek Can you confirm that this issue is fixed now?

**Comment by pekr** [comment]
Windows 10, prints "drag" here, when dragged. The face also does not disappear, so hopefully fixed.

**Comment by dockimbel** [comment]
Ok, thanks.
