### ISSUE TITLE
Size change problem, square value results in rectangular shape

### ISSUE THREAD

**Issue by iArnold** [red/red#1678]
Similar source https://gist.github.com/iArnold/601546d4109f90d16841

Odd behaviour, changing the size of a 'base (to 4x4) result looks more rectangular than square.

**Comment by iArnold** [comment]
I added some display and a different size assignment
change-move-indication: func [
	to-color [integer!]
][ 
	either 1 = to-color [
		print "black to move"
		red-to-move/size: 4x4
		black-to-move/size: move-indicator-size
		player-color-to-move/color: purple
	][
		print "Red to move"
		red-to-move/size: move-indicator-size
		black-to-move/size/1: 4
		black-to-move/size/2: 4
		player-color-to-move/color: green
	]
	
	show player-color-to-move
	
	print black-to-move/size/1
	print black-to-move/size/2
	;show win/pane
]
Now value size/1 is even equal to -1 !

**Comment by qtxie** [comment]
It's should be fixed in the latest commit.
