### ISSUE TITLE
WINDOW/EXTRA field is overwritten when compiled

### ISSUE THREAD

**Issue by rebolek** [red/red#1692]
Have a look at this script:
```
Red [
    Needs: 'View
]

main: layout [text-list 100x200 data ["one" "two" "three"]]
main/extra: object [val: 0x0]
main/actors: object [
    on-resizing: func [
        face [object!]
        event [event!]
    ] [
        print type? face/extra
    ]
]

view/flags main [resize]
```

When you run in from interpreter and resize the window, it prints `object` in console as expected. However when you compile the script, it prints `float` instead (with value of 0.0).

**Comment by dockimbel** [comment]
I cannot reproduce it with the latest commit. The compiled code works fine and I only get `object` printed on screen, never `float` whatever I do with the window's size (even tried maximizing/minimizing).

**Comment by rebolek** [comment]
I can confirm that it works fine now here too.
