### ISSUE TITLE
Latest binaries with a fixed name, e.g. http://static.red-lang.org/dl/auto/linux/red-latest

### ISSUE THREAD

**Issue by xaduha** [red/red#1695]
Or http://static.red-lang.org/dl/auto/linux/red-master

So people can use a simple update script without visiting or grepping the site.

**Comment by nc-x** [comment]
But then `red --version` output should be in the format `x.y.z commit-hash` as the commit hash helps in finding regressions.

**Comment by nc-x** [comment]
Or you could use `modified? http://static.red-lang.org/download.html` and `parse` (if required) to check for any new updates which can then be downloaded. (`modified?` works fine on Rebol2, i dunno if it is implemented in Red yet)

**Comment by xaduha** [comment]
I wasn't thinking that far, isn't for me to decide. People can just download latest version and then say if they are still having a problem. But the main weapon against regressions are automated tests.

**Comment by nc-x** [comment]
@xaduha 
I have a rebol2 script nearly ready to auto-download the latest red binaries. It just needs a bit more tweaking. Will upload it in a day or two.

**Comment by dockimbel** [comment]
@nc-x Good news! Don't worry about it, if you publish it as a gist, others can improve it easily.

**Comment by nc-x** [comment]
@dockimbel @xaduha 
https://gist.github.com/nc-x/041f3db0c660323b8687

Works for me on my Windows pc. Should work on other Linux and OSX also.

**Comment by xaduha** [comment]
To me it seems like a solution at the wrong level. Sure, dockimbel has better things to do, but a proper way is to solve it on the server-side or during deployment. A redirect, a symlink or just a plain old copy.

**Comment by dockimbel** [comment]
The lates auto-builds are now available at these URLs: [Windows](http://static.red-lang.org/dl/auto/win/red-latest.exe), [Linux](http://static.red-lang.org/dl/auto/linux/red-latest), [MacOSX](http://static.red-lang.org/dl/auto/mac/red-latest).
