### ISSUE TITLE
WAIT does not seem to work

### ISSUE THREAD

**Issue by meijeru** [red/red#1703]
In the interpreter, `wait 1000` should return after 1 second. It does not. When complied, the resulting `.exe` hangs up.

Incidentally, the documentation does not say the argument is milliseconds.

**Comment by xqlab** [comment]
`     red>> help wait
          
     USAGE:
         wait value  /all  /only
     
    DESCRIPTION:
       Waits for a duration, port, or both. 
       wait is of type: native!
`
1000 are 1000 seconds. 0.001 would be 1 millisecond

**Comment by dockimbel** [comment]
`wait` takes seconds as argument.

**Comment by dockimbel** [comment]
The description message now mentions `duration in seconds`.
