### ISSUE TITLE
Within some tight loops, view does not seem to check events 

### ISSUE THREAD

**Issue by meijeru** [red/red#1704]
Red []
    view [
        t: text "abcd" button "Change" [forever [t/text: random "efgh"]]
        button "Quit" [quit]
    ]

The button Quit does not react once Change is clicked.

**Comment by dockimbel** [comment]
You are creating an infinite loop, Red execution is single-threaded for now, so such code will freeze the GUI event loop.

In such cases, you can run the event loop manually using `do-events/no-wait`:
```
Red []
view [
    t: text "abcd" button "Change" [forever [t/text: random "efgh" do-events/no-wait]]
    button "Quit" [quit]
]
```
This will allow events to be processed again in such tight loop.

**Comment by meijeru** [comment]
Thanks!  Worthwhile mentioning in View documentation??
