### ISSUE TITLE
'what' not working

### ISSUE THREAD

**Issue by ralfwenske** [red/red#1709]
red>> about
Red 0.5.4 - 15-Mar-2016/15:39:03+10:00
red>> what
*** Script error: symbol! has no value
*** Where: get
red>> 

changing all get's to get/any seems to work:
`what1: func ["Lists all functions" /local w spec desc]
  [foreach w words-of system/words [if any [
    function? get/any w
    native? get/any w
    action? get/any w
    op? get/any w
    routine? get/any w]
    [prin pad form w 15 spec: spec-of get w either any [
      string? desc: spec/1
      string? desc: spec/2
      ] [print [#":" desc]] [prin lf]]]
  exit]`

**Comment by dockimbel** [comment]
Great, thanks for the report + the right fix. We would be glad to accept a PR from you for that fix it you can make it?

**Comment by dockimbel** [comment]
The issue was fixed by one of today's commit. Next time, you should send the PR directly while opening the issue. ;-) Thanks anyway.
