### ISSUE TITLE
Console should give error when Red/System Code is encountered

### ISSUE THREAD

**Issue by nc-x** [red/red#1722]
Currently there are no checks whether the code to be executed is R/S or not. This might confuse a newbie as he wouldn't know that only Red code can be interpreted, and not R/S.

The console should give an error in case -
-   `do %*.reds` where the `*.reds` file contains the R/S header.
-    A `*.red` file to be executed either through `red *.red` (from system console) or `do %*.red` when it -
  -  `#include`'s a `*.reds` file. (Requires https://github.com/red/red/issues/1601 first)
  - contains `#system`.

Because in these cases the ouput (if any) would be wrong and not expected.

Also, currently `red *.reds` (in system console) gives `*** Error: not a Red program!`. This error should also be changed to show that `R/S code cannot be run in the console.`

**Comment by dockimbel** [comment]
All the suggestions mentioned above should now be implemented.

**Comment by DideC** [comment]
And what about `routine` definitions ?
