### ISSUE TITLE
CHANGE-DIR works differently than in Rebol

### ISSUE THREAD

**Issue by rebolek** [red/red#1726]
In both Red and Rebol, you can write `cd dir` to change dir to `%dir/`. In Red, this is also possible with `change-dir`, however in Rebol, `change-dir dir` interprets `dir` as normal word and gets its value. Also, Red does not accept `get-word!` as `change-dir` or `cd` argument, so it's not possible to use `change-dir :dir`. The result is that changing file path to stored value is impossible right now.

**Comment by dockimbel** [comment]
You can simply set `system/options/path` to whatever value you need.

**Comment by rebolek** [comment]
Thanks for tip!

**Comment by dockimbel** [comment]
We still need to enable that feature for `change-dir`, so I keep the ticket opened until it is done.
