### ISSUE TITLE
read http:// does not work under wine

### ISSUE THREAD

**Issue by xqlab** [red/red#1742]
**gui console**

> red>> read http://google.com
*** Access error: cannot connect: http://google.com reason: timeout
*** Where: 

**linux console**

> ~/own/Red $ fixme:dwmapi:DwmIsCompositionEnabled 0x33fc84
fixme:winhttp:winhttp_request_QueryInterface interface {06f29373-5c5a-4b54-b025-6ef1bf8abf0e} not implemented
fixme:ole:CoCreateInstanceEx no instance created for interface {06f29373-5c5a-4b54-b025-6ef1bf8abf0e} of class {2087c2f4-2cef-4953-a8ab-66779b670495}, hres is 0x80004002

**Comment by xqlab** [comment]
It works after installing the winhttp.dll with winetricks. So this can be closed.

Probably you have to download W2KSP4_EN.EXE manually from http://web.archive.org/web/20160129053851/http://download.microsoft.com/download/E/6/A/E6A04295-D2A8-40D0-A0C5-241BFECD095E/W2KSP4_EN.EXE before.

**Comment by nc-x** [comment]
Well, so many issues regarding Wine.
A wiki page linked with readme.md with all the issues and fixes for Wine would be good.

**Comment by gour** [comment]
> Well, so many issues regarding Wine.

Support for GTK will fix them all. ;)

**Comment by dockimbel** [comment]
Indeed, as we aim at native GUI support on Linux, Wine support is very low priority (though the community is welcome to improve the support for it). ;-)
