### ISSUE TITLE
'TO STRING! #"a" == "97"

### ISSUE THREAD

**Issue by DideC** [red/red#1747]
"'to string!" of a character give a string of the integer value of the chararacter. Must give a string with this only chararacter.

ie:
>> to string! #"a"
== "97"        ; not very usefull !
; Must give :
== "a"

**Comment by dockimbel** [comment]
I am not sure this conversion is implemented. @qtxie will answer that.

**Comment by qtxie** [comment]
Convert char! to string! is not implemented yet. And yes, convert it to "a" is more reasonable.

**Comment by dockimbel** [comment]
Closing this ticket, as it is about a non-implemented feature (`to` action).
