### ISSUE TITLE
binary! error messages

### ISSUE THREAD

**Issue by nedzadarek** [red/red#1750]
I'm using red 0.6 on windows.
Messages are unclear.
Using unsupported characters (`F` in base 2):
```
2#{FF}
; *** Script error: get does not allow string! for its word argument
; *** Where: get
```
Not enough characters (2 instead of 8 - can it be auto inserted?):
```
2#{01}
; *** Script error: get does not allow string! for its word argument
; *** Where: get
```
No error. I don't know too much about 64 bit encoding so I'm not sure about it. Should here be some warning.
```
64#{AA}
; == #{}
```
Explicitly using `16#` raises an error:
```
16#{FF}
; *** Syntax error: invalid integer! at {"16#{FF}"}
; *** Where: do
```
Unsupported encodings:
```
4#{0}
; *** Script error: get does not allow string! for its word argument
; *** Where: get
```

**Comment by dockimbel** [comment]
Good catch thanks! Those binary formats are lacking unit tests.
