### ISSUE TITLE
Provide --scan complier option

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#1752]
A --scan compiler option that checked the syntax of a source program, listing all errors, would be very useful for testing.

If it could check for errors other than syntax errors it would be even more useful.

**Comment by dockimbel** [comment]
I don't think this could work as you think. If you have ever used a C compiler, it outputs an exhaustive list of errors found, not stopping at the first one. Most of the time, the majority of the reported errors are pointless, as they are cascading from an initial error, messing up the processing of the source code (could be syntactic or semantic error).

**Comment by PeterWAWood** [comment]
Closing as no longer wished.
