### ISSUE TITLE
Wish: Display the time when compiling a program

### ISSUE THREAD

**Issue by iArnold** [red/red#1757]
Not only the dt how long compilation takes but also begin or end time of compilation.

**Comment by dockimbel** [comment]
What is it needed for? Typical compilation time are done in less than a minute, what do Red users gain from having the starting and ending timestamps displayed on every compilation?

**Comment by iArnold** [comment]
I have submitted a PR to add the date time for finish time of compilation. Because Rebol console does not display the date time I cannot compare the time of last compilation with the creation time of the executable. Because I often do compilations in between other stuff that is to be done, I want to be able to check if I already compiled last version of the program. There are other scenarios where having this feature is nice to have.

**Comment by dockimbel** [comment]
You can easily overload the Rebol prompt to display time (or date/time) if that's what you need:
```
>> system/console/prompt: [reform [now/time ">> "]]
== [reform [now/time ">> "]]
12:06:04 >>
```

**Comment by iArnold** [comment]
I would have to do that every time I start a new console? Besides I like the prompt as ">>" keeps my compilation strings fit on 1 line. I could try and keep it on one existing output line.

**Comment by dockimbel** [comment]
Rebol supports auto-loading a `user.r` script for such definition.

You didn't give any good reply to the main question: "What do Red users gain from having the starting and ending timestamps displayed on every compilation?"

**Comment by iArnold** [comment]
Start and end times both are too much. The ending time is close to the real save time of the executable. In this way everybody instantly can verify that the executable is the one generated from the last compiling. Not one from an earlier compilation where you forgot to copy the program from the red folder to the folder from where to execute the program from. It is just very convenient and adds little to no overhead. 
This is how I made it look now:
>> rc %../xiangqi-master/xiangqi/xiangqi-board.red

-=== Red Compiler 0.6.0 ===-

Compiling /C/.../project/xiangqi-master/xiangqi/xiangqi-board.red ...
...compilation time : 2397 ms

Compiling to native code...
...compilation time : 49199 ms
...linking time     : 496 ms
...output file size : 779776 bytes ...output file saved : 1-Apr-2016 13:34:31
...output file      : C:\...\project\red-master\xiangqi-board.exe

>>
No extra lines used. And every new Red user can have it for free without having to adjust R2 program, just focus on Red.

**Comment by iArnold** [comment]
And I can check if I compiled my source after the latest save!

**Comment by iArnold** [comment]
Do not forget to reject https://github.com/red/red/pull/1767 if my presence still raises those 'Anger Management' feelings for you. Are you really that mad at me?

**Comment by maximvl** [comment]
@iArnold Your change affects every user and your goal seems to be selfish, sounds like you had bad experience with copying not up-to-date binaries, but this is not common case for everybody and accepting such changes can get code and project out of control. I think this is what @dockimbel had in mind.

**Comment by iArnold** [comment]
@maximvl Aren't all wishes a bit selfish? Lets wait and see other developers experience similar inconvenience we could have easily prevented with this change. 
I see plenty of changes passing that have less practical use for the common use. All I am asking for is to display a time (not even asking for a date! here ;-) ) something that is already IN the box, and I get redirected to a solution that is an outside dependency on the user.r file that will become obsolete when Red will be bootstrapped. 
To prevent further pollution of this thread, and not bother others involved, I suppose we better continue the discussion on our gitter channel.
