### ISSUE TITLE
Allow the use of `select:` in a data block for a list in VID.

### ISSUE THREAD

**Issue by dockimbel** [red/red#1760]
Instead of:
```
view [tl: text-list data ["A" "B" "C"] do [tl/selected: 2]]
```
consider allowing this shorter form:
```
view [text-list data ["A" select: "B" "C"]]
```

**Comment by iArnold** [comment]
This also applies to drop-list and drop-down?

**Comment by dockimbel** [comment]
Yes, the title says "for a list", not "for a text-list".

**Comment by dockimbel** [comment]
Actually, putting the selection out of the data block would be preferable:
```
view [text-list data ["A" "B" "C"] select 2]
```

**Comment by iArnold** [comment]
Looks to make sense to me, this way the data block and the select index value can be constructed independent of each other. I figure it can be hard or at least inconvenient to insert "select:" into a constructed datablock or drop it later when the datablock must be changed dynamically.

**Comment by dockimbel** [comment]
`select:` was never meant to be used in a contructed data block, only in VID literal data blocks.

**Comment by dockimbel** [comment]
`select` option implemented. It takes an integer! as argument and sets the `face/selected` facet.
