### ISSUE TITLE
Default window (no size) can't be dragged on Windows 10

### ISSUE THREAD

**Issue by asampal** [red/red#1761]
On Windows 10, if you create a window with something like`view [<some elements but no size>]` it can't be dragged by it's title bar even though there seems to be enough space on the title bar from where to drag.

Red version 10471c731a91e8c7c8ad094388682f4a2173f6d9.

**Comment by qtxie** [comment]
Actually you can still drag it if click the border very carefully. The border is just one pixel in Win 10, so it not easy to choose it. ;-)
