### ISSUE TITLE
WISH: Tab completion for file names in the Red console

### ISSUE THREAD

**Issue by mydoghasworms** [red/red#1765]
It would be nice if in the Red console, as in the Rebol console, you could have tab completion on filenames, so after the % (and the first character), if you hit tab, it will bring up possible completions.

(Unlike the Rebol console, it would be nice if you didn't have to type a character after the % though).

**Comment by nc-x** [comment]
This feature is planned for the 0.6.1 release.
I don't know if anything remains to be implemented but there is this -
https://github.com/red/red/commit/9bf3e48865a627e1d3ef0de32cf922e12bf58241

Please download the latest master binaries from the red-lang website -> downloads, or use the latest sources.

**Comment by dockimbel** [comment]
Feature has been implemented already and is available from the auto builds on [Download](http://www.red-lang.org/p/download.html) page. ;-)

**Comment by nc-x** [comment]
@dockimbel This -
> (Unlike the Rebol console, it would be nice if you didn't have to type a character after the % though).
remains to be implemented. :smile:

**Comment by mydoghasworms** [comment]
Thanks! It is working well. Do you think there is any chance of making the autocomplete work with just having typed `cd ` ('cd' + space)?
