### ISSUE TITLE
Lexer Issue: No error reported for invalid format %{...}

### ISSUE THREAD

**Issue by nc-x** [red/red#1768]
Currently -
```
red>> %{test ing.txt}
== "test ing.txt"
red>> a: %{test ing.txt}
== "test ing.txt"
red>> print read a
*** Access error: cannot open: %""
*** Where: read
red>> a
== %""
red>> print a

red>>
```

Instead an error should be reported for invalid format `%{...}`

**Comment by hiiamboris** [comment]
0.6.4: not fixed yet (no error is reported)
In fact, the result is unexpected:
```
>> try [load {a: %{test ing.txt}}]
== [a: % "test ing.txt"]
>> do try [load {a: %{test ing.txt}}]
*** Script Error: % does not allow set-word! for its value1 argument
*** Where: %
*** Stack:
```
It adds a space where there shouldn't be one

**Comment by 9214** [comment]
@hiiamboris I believe this is an expected behavior. `%` gets parsed as a word bound to modulo operator. Values don't "stick" to brackets (i.e. `[]`, `()` and `{}`)
