### ISSUE TITLE
Compiler compiles `*.red` file with `Red/System` header as a R/S file (and vice versa) instead of erroring out

### ISSUE THREAD

**Issue by nc-x** [red/red#1770]
Compiler compiles `*.red` file with `Red/System` header as a R/S file (and vice versa) instead of erroring out -
`a.red`
```
Red/System []

print 1.0
```
```
C:\Users\ABC\Desktop
λ red -c a.red

-=== Red Compiler 0.6.0 ===-

Compiling /C/Users/ABC/Desktop/a.red ...

Compiling to native code...
...compilation time : 297 ms
...linking time     : 15 ms
...output file size : 24064 bytes
...output file      : C:\Users\ABC\Desktop\a.exe


C:\Users\ABC\Desktop
λ a
1.0
```
Similarly -
`xt.reds`
```
Red []

print 1.0
```
```
C:\Users\ABC\Desktop
λ red -c xt.reds

-=== Red Compiler 0.6.0 ===-

Compiling /C/Users/ABC/Desktop/xt.reds ...
...compilation time : 968 ms

Compiling to native code...
...compilation time : 32834 ms
...linking time     : 250 ms
...output file size : 428032 bytes
...output file      : C:\Users\ABC\Desktop\xt.exe


C:\Users\ABC\Desktop
λ xt
1.0
```

Compiler should instead report an error if a `*.red` file contains an R/S header and vice-versa.

**Comment by dockimbel** [comment]
The file extensions are not significant for Red toolchain, only the header matters and determines the type of the content.

**Comment by nc-x** [comment]
Shouldn't the filename also matter? 
(Well I come from other languages where filename suffix does matter. :wink:)

**Comment by dockimbel** [comment]
As additional explanation, Red (like Rebol) is also a data format (data which eventually gets evaluated), so it has a proper "head marker" to identify it, as do many other data formats (especially binary formats).
