### ISSUE TITLE
Regression in cli console: automatic insertion of whitespace

### ISSUE THREAD

**Issue by nc-x** [red/red#1775]
![a](https://cloud.githubusercontent.com/assets/16458742/14202096/bf9311da-f813-11e5-832d-ad4649bb7812.gif)

Just type something, then ENTER,  then press UP arrow, you get a SPACE inserted for free, then again type something, then press UP arrow, you get more free SPACE's, YAY!!! (not really YAY!!!)...
The GUI Console works fine.

Regression in the latest master binaries of 01-Apr-2016. CLI console works fine in the binaries of 31-March-2016.

It is probably caused by https://github.com/red/red/commit/4aefa269c04364572b3bc92bd2fd2e8d817cc7c0

**Comment by dockimbel** [comment]
Ah, sorry, I went to quickly with the fix for #1769.
