### ISSUE TITLE
Issue with console when using `view [window]`

### ISSUE THREAD

**Issue by nc-x** [red/red#1776]
1) Start the red console.
2) Type `view [window]` 
3) Press ENTER.
=> Two windows open up. One at the Center of the Screen (Lets call it A). Another at the top of the screen (Lets call it B).
  

Now, if you close the window B.
=>  
```
*** Runtime Error 1: access violation
*** at: 928059ADh
```

If __INSTEAD OF__ window B, you close window A 
=>  You get a blinking cursor in the console. But no `red>>` prompt. So you are unable to do anything in the console. You need to close and reopen the console if you want to use Red.

**Comment by dockimbel** [comment]
Good catch, we need to forbid the `window` keyword from usage in VID, as the container is automatically created anyway.
