### ISSUE TITLE
Put parsing rules from transcode into a separate context, to make them accessible.

### ISSUE THREAD

**Issue by SteeveGit** [red/red#1782]
**Transcode** function in red/environment/lexer.red defines all its parsing rules in local.
Instead, they could have their own context in **system/lexer** so that we can reuse them in our own code.

**Comment by 9214** [comment]
@dockimbel is this still relevant?

```red
>> parse to binary! "1 word [:block]" [integer! space word! space #"[" get-word! #"]"]
== true
```

**Comment by 9214** [comment]
↑ ping.

**Comment by dockimbel** [comment]
As the lexer has been redesigned and reimplemented totally, this ticket does not apply anymore.
