### ISSUE TITLE
Console(GUI & CLI both) allows to type in-between some unicode characters

### ISSUE THREAD

**Issue by nc-x** [red/red#1788]
__Both CLI and GUI consoles__ display this behaviour.
Note: Happens only for some characters (not all)
![a](https://cloud.githubusercontent.com/assets/16458742/14251424/949d8c46-faa0-11e5-9cd3-0c5fb3193f18.gif)

**Comment by dockimbel** [comment]
Good catch!

**Comment by qtxie** [comment]
@nc-x Please give a try the latest version.

**Comment by nc-x** [comment]
Okay, I will check and report back.

**Comment by nc-x** [comment]
@qtxie 
On GUI-Console, this issue is fixed
But I don't know why in CLI console, this is happening (I have `Active code page: 65001` ) -
![untitled](https://cloud.githubusercontent.com/assets/16458742/15221786/7d948592-188a-11e6-95e8-41de20340b9c.png)
When I paste `👀` in console, it comes as a question mark but the error message displays it correctly.

**Comment by qtxie** [comment]
Should be fixed now. ;-)
