### ISSUE TITLE
Error with ** exponent operator

### ISSUE THREAD

**Issue by Bitsoma** [red/red#1789]
On the Red 0.6.0 console
10 ** 10 you get 1410065408 as a result.
10 ** 9 is correct
But every exponent above produces wrong values.

**Comment by dockimbel** [comment]
Integer math operations are limited to 32-bit representation. 10^9 fits, 10^10 does not. As we don't have automatic promotion of number types to larger representation (like integer to float), you end up with wrong values. Such upgrading to larger type is scheduled for one of 0.6.x releases.
