### ISSUE TITLE
Break doesn't work with any of loop commands: loop, while, repeat, foreach, forall

### ISSUE THREAD

**Issue by Zamlox** [red/red#1795]
Trying to use break in a loop it will close the console with following message:
`--== Red 0.6.0 ==--
Type HELP for starting information.

*** Throw error: no loop to break
*** Where: break`

Example:
`
a: "hello world"
forall a [break]
`

**Comment by nc-x** [comment]
https://github.com/red/red/issues/1741

**Comment by Zamlox** [comment]
Already reported as nc-x mentioned above
