### ISSUE TITLE
write does not work with block! argument

### ISSUE THREAD

**Issue by fvanzeveren** [red/red#1801]
When trying to write a block of string, the command returns the following error:
`red>> write/lines %test.txt ["a" "b" "c" "d"]`
`*** Script error: write does not allow block! for its data argument`
`*** Where: write`

This does not look right, considering that it is supposed to accept any-type! and the same command works fine with REBOL2.

regards

**Comment by nc-x** [comment]
It is not implemented yet and is a planned feature. See qtxie's reply here - https://groups.google.com/forum/m/?hl=en#!topic/red-lang/h36_IeGmHH4

**Comment by dockimbel** [comment]
Yes, this is a to-be-implemented future, so I'm closing the ticket.
