### ISSUE TITLE
Using refinement on a get argument does not work

### ISSUE THREAD

**Issue by Zamlox** [red/red#1802]
Following code in Red does not work:
```
fz: func [:fp][fp/ref "animal"]
ft: func [/ref p][print p]
fz ft
```

It gives the result:
```
*** Script error: path :fp/ref is not valid for word! type
*** Where: fz
```

The example does work in Rebol2

**Comment by dockimbel** [comment]
Red currently implements get/lit arguments following Rebol3, which errors out the same way as Red on such code pattern:
```
>> fz: func [:fp][fp/ref "animal"]
>> ft: func [/ref p][print p]
>> fz ft
** Script error: path fp/ref is not valid for word! type
** Where: fz
** Near: fz ft
```

We will re-examine this design choice in the future, but for now, it is behaving as expected, so this ticket will be closed. A formal [enhancement proposal](https://github.com/red/red/wiki/Red-Enhancement-Proposal-Process) could be filled, though, we will consider the change back to Rebol2  semantics anyway.
