### ISSUE TITLE
?? confused by compiled words set to values of same name map keys 

### ISSUE THREAD

**Issue by WiseGenius** [red/red#1807]
Code **A**:
```
Red []

m: #(
	a: 1
)
b: m/a
probe b
print type? b
?? b
```

Result (_as expected_) of Code **A** when both interpreted and compiled:

```
1
integer
b: 1
```

Code **B**:
```
Red []

m: #(
	a: 1
)
a: m/a
probe a
print type? a
?? a
```

Result (_as expected_) of interpreted Code **B**:
```
1
integer
a: 1
```

__Surprising__ run-time result of compiled Code **B**:
```
1
integer
*** Script error: ?? does not allow set-word! for its 'value argument
*** Where: ??
*** Stack: ??
```

Code **C**:
```
Red []

m: #(
	a: 1
	b: 2
)
a: m/b
probe a
print type? a
?? a
```

Result (_as expected_) of Code **C** when both interpreted and compiled:
```
2
integer
a: 2
```

**Comment by dockimbel** [comment]
Issue is caused by the hashtable lookup in map corrupting a word slot.
