### ISSUE TITLE
Conflict between `not` behaviour and docstring

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#1813]
Not of an integer returns a logic! value rather than the logical complement of the value as described in the DocString. 

```Red
red>> ? not

USAGE:
    not value

DESCRIPTION:
     Returns the negation (logical complement) of a value. 
     not is of type: native!

ARGUMENTS:
     value  [any-type!]

REFINEMENTS:
red>> not FEh
== false
red>> not 1
== false
```

**Comment by SteeveGit** [comment]
Did you expect the one's complement of a binary number ?
If so, that's the purpose of the func COMPLEMENT.
(logical complement) vs (binary complement)

**Comment by PeterWAWood** [comment]
The DocString says ```not``` returns the one's complement of a binary number. It does not. The DocString needs to be corrected.

**Comment by dockimbel** [comment]
Docstring changed to `Returns the boolean complement of a value`.
