### ISSUE TITLE
`show` not updating face with changes to draw facet

### ISSUE THREAD

**Issue by mydoghasworms** [red/red#1822]
`show` is not updating a face where the draw facet has been changed.

Sample code:

```
Red [needs: 'view]
l: layout [
  tf: panel white 200x200 draw [box 20x20 30x30]
  return
  button "Test" [append tf/draw [box 40x40 50x50] probe tf/draw show tf]
]
view l
```

After pressing the button in the example, the draw facet is update, but following `show`, nothing changes.

(I would have expected that a change to the draw facet automatically results in an update, but even after `show` this does not happen).

**Comment by dockimbel** [comment]
If you replace `panel` with `base`, it works fine. I don't think we support drawing on panels bakground yet. @qtxie Can this be easily supported?

**Comment by qtxie** [comment]
If we support drawing on panels, so what is the difference between `panel` and `base` face?
`panel` is just a container in my opinion. `base` is for drawing, so it can be a base of making custom control, also can be used as a canvas.

**Comment by mydoghasworms** [comment]
Sorry, my bad.
After your comments, I see now in the documentation that it says that `base` is to be used for custom graphic implementation. So unless there is a use case for drawing on anything else like a panel, I guess you may as well close this issue.

**Comment by dockimbel** [comment]
@qtxie Actually, I would be glad if we could define a Panel from a Base face, though, we would have rendering issues I guess, so we can keep them separated for now.
