### ISSUE TITLE
Problem with Console

### ISSUE THREAD

**Issue by Bitsoma** [red/red#1826]
I am not sure whether p is a reserved word in the Red 6.0 console.
When I start the console and type p I get "red>> " as the value of p.
Typing 'what' doesn't show p as defined, but type? gives string.

**Comment by meijeru** [comment]
Are you using the latest version?

**Comment by x8x** [comment]
@Bitsoma that regression was fixed in commit https://github.com/red/red/commit/110433016f0f6b08e5b454db80ef268fcc046992

**Comment by dockimbel** [comment]
Closing this ticket as it is fixed already.

**Comment by Bitsoma** [comment]
I was using 0.6.0 from April 5.
I can confirm the problem is fixed in 0.6.0 from April 19.

Thanks!



Am 18.04.2016 um 22:43 schrieb Rudolf Meijer <notifications@github.com>:
Are you using the latest version?
