### ISSUE TITLE
WISH: Mouse-Away, Mouse-Enter, and Mouse-Over

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#1832]
Most of the time, I don't care about Mouse-Over, so I don't want to set ALL-OVER flag to get all the overwhelming OVER events. I just want to get informed that mouse is entering and mouse is leaving, so I can change the face color or something like that for better user experience.

I suggest that we make Mouse-Away, Mouse-Enter, and Mouse-Over 3 different events.

**Comment by dockimbel** [comment]
The `on-over` event already provides that feature: by default, it is triggered only on face entering and exiting. `event/away?` flag is set for exiting event.

A single event, instead of 3 allows to factorize code better. For example:
```
view [base on-over [face/color: get pick [red blue] event/away?]]
```
