### ISSUE TITLE
red-22apr16-930d811 word INPUT not recognized by compiler

### ISSUE THREAD

**Issue by Arie-vw** [red/red#1839]
*** Compilation Error: undefined word input
*** in file: %/E/Websites/Red-by-Example/auto/test.red
*** near: [input "Enter something ... " print ["You entered: " x] quit]

**Comment by dockimbel** [comment]
`input` is currently only defined for console, so you need to include the %input.red file manually if you compile your code. This is temporary until we gets ports and full I/O in 0.7.0.
```
#include %environment/console/input.red
```
