### ISSUE TITLE
panda free antivirus 16.0.2 says red 0.6.0 is a virus

### ISSUE THREAD

**Issue by melissawells** [red/red#1841]
hi i have a windows 7 toshiba lap top running panda free antivirus 16.0.2 which lets me download red 0.6.0  but every time i try and run it it just deletes it saying its a virus ?

**Comment by nc-x** [comment]
@melissawells There should be an option to Report False Positive in the antivirus.
Or else
@dockimbel -> http://support.pandasecurity.com/forum/viewforum.php?f=13&sid=9afea153360867b1b4a17916849776f3

**Comment by dockimbel** [comment]
This ticket was solved from Gitter chat, so I'm closing it.
