### ISSUE TITLE
WISH: A new type of face, EDIT

### ISSUE THREAD

**Issue by SteeveGit** [red/red#1857]
EDIT would behave like FIELD, emits the same flow of events and can be activated (focus/unfocus events emitted).
All that, without the look and feel of a Field. So en empty face (more like a container) which lets the user choose its look (using draw or sub faces).
Thanks

**Comment by dockimbel** [comment]
We cannot have the `field` features without its look, as it's a native widget. We will provide support for custom widgets creation in a later release. We may or may not implement support for a caret+editing system which could be re-used by any other custom widget. Anyway, decisions and architecture of the custom widget support is still a bit premature, so I'm closing this ticket for now. Feel free to open a new one when custom widgets will be officially supported if your needs are not met.
