### ISSUE TITLE
Return in the description block of a group-box adds additional empty faces

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#1873]
If you use ```return``` inside the description block of a ```group-box```, additional empty faces are added to the grid.

This code:
```Red
Red [
	Needs: 'View
]

view [
	title "My Layout" 
	group-box 2 [
		text "No return" font-name "helevetica" font-size 12
		text ""
		text "Field 1"
		field 200 
		text "Much Longer Field Name"
		field 200
	]
	group-box 2 [
		text "Return" font-name "helevetica" font-size 12
		return
		text "Field 1"
		field 200 
		text "Much Longer Field Name"
		field 200
	]
]
```

demonstrates the issue:

<img width="678" alt="group box return v no return" src="https://cloud.githubusercontent.com/assets/697434/14945608/3c716b2a-1047-11e6-8092-4b3708857350.png">

**Comment by dockimbel** [comment]
@PeterWAWood Not related to the issue, but there's a typo in your font name, it should be `"helvetica"`.

**Comment by PeterWAWood** [comment]
Thanks.

**Comment by dockimbel** [comment]
The `return` keyword is not compatible with grid layout mode, as rows/columns delimitations are determined by VID automatically. I will add a check and make VID report an error if `return` is used in such context.
