### ISSUE TITLE
Slider data facet does not scale up/down with slider's size

### ISSUE THREAD

**Issue by ldci** [red/red#1883]
When resizing a slider, data value is incorrectly updated. For example a slider initialised to 512 pixels in X size will send back data varying from 0.0 to 1.0. When resized to 1024 in X size data value only varies between 0.0 and 0.5

**Comment by dockimbel** [comment]
Example code to reproduce it:
```
view [
    size 400x100
    s: slider [probe s/data] return
    button "resize" [s/size/x: 300]
]
```
