### ISSUE TITLE
possible rejoin problem

### ISSUE THREAD

**Issue by mark-summerfield** [red/red#1896]
Run this and change the value 1.00 to, say 2, and you'll get the error.
[currency-err.red.txt](https://github.com/red/red/files/260954/currency-err.red.txt)

**Comment by xqlab** [comment]
See my comment on gitter.The error results from loading the value/text

**Comment by dockimbel** [comment]
@xqlab Thanks for pin-pointing the cause of the error. Now we need to figure out why it works with an alternative `rejoin` implementation (like the Rebol2's one) and not with @rebolek 's version.

**Comment by greggirwin** [comment]
It's related to the name `value` in the foreach in Bolek's `rejoin`. If you change it to something else, the error goes away.

**Comment by greggirwin** [comment]
Although there may be something else going on. If you comment out the `attempt` from around the assignments in `calculate` you get this error:
    *** Script error: calculate has no value
    *** Where: try

**Comment by dockimbel** [comment]
Indeed, the `value` word is not made local in `rejoin` implementation, so it collides with `value` used in VID block. This is a fixed version (using `function` will capture the `foreach` word argument):
```
rejoin: function [data][
    collect/into [foreach value reduce data [keep value]] copy ""
]
```
@greggirwin I cannot reproduce any error with that fix.

@rebolek You should fix your `rejoin` function with above version.

**Comment by greggirwin** [comment]
Doh! I hate not seeing the obvious.

**Comment by greggirwin** [comment]
But, wait, shouldn't `foreach` be binding that?

**Comment by greggirwin** [comment]
I guess this is a change I need to understand, it must be by design.

**Comment by dockimbel** [comment]
@greggirwin Not in Red, there's no local context for iterators (for now). I might add such feature if we can figure out a cheap and safe way to do it, while avoiding the huge overhead of Rebol's copying and re-binding of the body block on each invocation.

**Comment by greggirwin** [comment]
Thanks Doc. It's a nice feature in REBOL, though `function` will help a lot. It's an important difference to note for those moving from REBOL.

**Comment by rebolek** [comment]
@dockimbel Thanks for the fix and explanation. However, the locality of iterators should be fixed soon, as this is going to be source of bugs, troubles and problems.
