### ISSUE TITLE
WISH: be able to indicate Safety? and Idempotency? notes in function spec block

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#1899]
I would like to indicate or to know a function is safe/Idempotent or not. 

```Red
my-func: function [ a b /safe /Idempotent  ] [ ... ]
```

**Comment by dockimbel** [comment]
Put it in a docstring inside the spec block? You can use a special syntax/convention to make it parsable in case you need that:
```
my-func: function ["#safe #idempotent" a b ] [ ... ]
```

**Comment by JenniferLee520** [comment]
Thanks. That's a good idea. this Ticket can be closed.
