### ISSUE TITLE
file! accepts wrong path separator `\` and does not convert it to `/`

### ISSUE THREAD

**Issue by nc-x** [red/red#1906]
Currently in Red -
```
red>> %\d\
== %\d\
```
whereas in rebol -
```
>> %\d\
== %/d/
```
In Rebol - 
> The standard character for separating directories is the forward slash (/), not the backslash (\). If backslashes are found they are converted to forward slashes.

Either Red should behave like Rebol or it should raise an error, but it just accepts wrong path separator.

**Comment by dockimbel** [comment]
We will implement it asap.

**Comment by dockimbel** [comment]
Fixed by commit [634996c9](https://github.com/red/red/commit/ce76e19676e231a2ec64624ef9400f21634996c9).
