### ISSUE TITLE
Redefining `set` crashes the console

### ISSUE THREAD

**Issue by nc-x** [red/red#1907]
```
red>> set: 1

*** Runtime Error 1: access violation
*** at: 00000000h
```

**Comment by meijeru** [comment]
Isn't there a general danger that redefining built-in words will lead to unpredictable results?

**Comment by nc-x** [comment]
@meijeru Yes. Modules support is gonna help a bit. But besides modules, there should be a way to create immutable variables, else I wouldn't really like if someone breaks a library I create by accidentally redefining an internal private api...

**Comment by dockimbel** [comment]
@meijeru Difficult to say. The console does rely on some interpreted code, so changing core actions/natives will have unpredictable effects. I'm not even sure in that context if it's possible or not to circumvent all potentially crashing outcomes, this needs a deeper study.

**Comment by dockimbel** [comment]
Modules with isolated namespaces should provide a more robust solution to this class of issues.
