### ISSUE TITLE
possible map! bug

### ISSUE THREAD

**Issue by mark-summerfield** [red/red#1911]
I started a Red GUI console and typed as follows and this resulted in a crash. Presumably I did something wrong, but I would have expected an error message rather than a crash.

--== Red 0.6.0 ==-- 
Type HELP for starting information. 

red>> m: make map! []
== #()
red>> k: "a"
== "a"
red>> put m k 1
== 1
red>> m
== #(
    "a" 1
)
red>> k: "b"
== "b"
red>> set m k 2
== 2
red>> m
CRASH!

**Comment by qtxie** [comment]
Yes. It should throw an error. And the right way to set a map is this: `set 'm/k 2`.

**Comment by x8x** [comment]
In his example above, it should be `set 'm/:k 2` instead of `set 'm/k 2`
Just curious, why the shorter way `m/:k 2` does't work ?

**Comment by dockimbel** [comment]
What does `m/:k 2` mean?

**Comment by x8x** [comment]
@dockimbel Sorry, my mistake, I meant `m/:k: 2` which is indeed working no problem..
