### ISSUE TITLE
IMAGE can be drawn outside of window

### ISSUE THREAD

**Issue by rebolek** [red/red#1920]
It’s possible to draw outside of window (at least with `image` widget). This code:

```
view [
    size 200x50 
    text "Image outside of window:" 
    at 210x0 
    image %icons/10.Folder.png
]
```

produces this result:

![image-outside](https://cloud.githubusercontent.com/assets/660267/15420817/08a5960a-1e6f-11e6-96dc-7953119e5fac.png)

**Comment by iArnold** [comment]
This is a feature I use for creating a nice flash screen for my applications! Please do not fix this.

**Comment by dockimbel** [comment]
This is a bug we need to fix. Proper support for transparent windows will come in the future.

**Comment by dockimbel** [comment]
Here is another example of image not clipped by the window:
```
view [
    size 300x500
    i: image 300x500 draw [line 0x0 300x500 line 0x500 300x0]
        on-over [
            face/selected: event/offset/y
        ]
]
```
