### ISSUE TITLE
WISH: Make SET-WORD!s in GUI actors local

### ISSUE THREAD

**Issue by rebolek** [red/red#1922]
Consider this code:

```
red>> warning
*** Script error: warning has no value
*** Where: do
red>> view [image 100x100 draw [line 0x0 100x100] on-over [probe warning: "I will leak"]]
"I will leak"
"I will leak"
red>> warning
== "I will leak"
```

`set-word!`s defined in actors are global. I would prefer they were local, because this can lead to unpredictable problems.

**Comment by dockimbel** [comment]
If we make this change, then it won't be possible to access anymore a set-word from an external context inside the actor's body block...

**Comment by rebolek** [comment]
I have to check how it’s done in R3GUI, where you can have local words in actors.

**Comment by dockimbel** [comment]
Now, set-words inside actors bodies defined in VID will be captured as local by default. In order to modify external words, you need to provide an additional block of external words, just after the body block. Example:
```
a: 100
view [button "+" [probe a: a + 1][a]]
````

**Comment by rebolek** [comment]
Thanks, I guess this is good solution.

**Comment by dockimbel** [comment]
I am not sure it will make things easier for beginners...anyway, we'll see.

**Comment by dockimbel** [comment]
This change has been reverte, as having local-by-default for VID handlers caused more troubles than gains. Alternative ways to make words locals exist.
