### ISSUE TITLE
get-word in a path does not work 

### ISSUE THREAD

**Issue by philipyi** [red/red#1934]
test: context [hello: does [print "Hello"]]
test/:hello
*** Script error: :hello has no value
*** Where: catch

**Comment by nc-x** [comment]
Also, using invalid get-word closes the console.
```
red>> test/:'
*** Script error: tail? does not allow none! for its series argument
*** Where: tail?
```
Will it be possible for the console to not crash itself?

**Comment by nc-x** [comment]
Well, I am not good enough at Red/Rebol to give an appropriate answer but @philipyi your code errors out even in Rebol 2.

**Comment by philipyi** [comment]
I now realize that Red/Rebol don't support full first class functions.  With Red/Rebol you can get global functions and store them in global variables and then call them.  However you cannot 
1) get functions from within objects
2) pass functions to to other functions
My workaround is to create what I call "function objects" which are objects containing a single function as a member. for example:
func-obj: object [call: func does [print "Hello func-obj"]]
I can then use func-obj as I would a first class function, with the provisor that I need to write func-obj/call to call the function.

**Comment by meijeru** [comment]
Have you tried (in your first example) `test/hello` to execute the function, and `:test/hello` to obtain the function as a frist class value?

**Comment by meijeru** [comment]
Your second example that crashes the console merits a real issue.

**Comment by philipyi** [comment]
test/hello works
f1: :test/hello works
f2: func [f [function!]][f]
f2 :test/hello works
f2 f1 crashes the console

**Comment by meijeru** [comment]
Again, it should be `f2 :f1` and that works. More documentation on the `get` native would be useful.

Also again, the fact that `f2 f1` crashes the console merits a separate (true) iss8ue.

**Comment by meijeru** [comment]
Will YOU put up the real issues or shall I?

**Comment by philipyi** [comment]
The correct syntax is :test/hello
issue closed.

**Comment by dockimbel** [comment]
For the record, this is how to read values from contexts without trigerring their evaluation:
```
red>> test: context [hello: does [print "Hello"]]
== make object! [
    hello: func [][print "Hello"]
]
red>> get in test 'hello
== func [][print "Hello"]
red>> :test/hello
== func [][print "Hello"]
```

*I now realize that Red/Rebol don't support full first class functions.* That is not correct. Functions are first class datatypes in Red/Rebol (though the Red's compiler support for that is currently limited, the interpreter should support it fully already).

*1) get functions from within objects*
Works fine when the right syntax is used, as above.

*2) pass functions to to other functions*
Here is a simple example:
```
red>> foo: function [action [any-function!]][action 1 2]
== func [action [any-function!]][action 1 2]
red>> foo :add
== 3
```
