### ISSUE TITLE
Output invisible in GUI-Console

### ISSUE THREAD

**Issue by nc-x** [red/red#1937]
In GUI-Console
```
probe system
probe system
```
Now scroll up, you will find invisible lines of text which becomes visible on click.
If you scroll to the top, there is unformatted text on top which does not occur if `probe` is used only once.

![animation](https://cloud.githubusercontent.com/assets/16458742/15570865/d11d9458-2355-11e6-9e6f-d566ce46bbb6.gif)

**Comment by qtxie** [comment]
Note with this fix, the first few lines still corrupts when `probe system` twice. This is the right behaviour as we use a ring buffer for output. 
We'll let the user to configure the buffer size in the next version, so if someone want to get a big output, he can just enlarge the buffer size.
