### ISSUE TITLE
Fix for #1920 breaks Red

### ISSUE THREAD

**Issue by Zamlox** [red/red#1942]
Following code will crash Red:
```
w: layout/only [base 100x100 blue]
main: layout [base 200x200 30.40.50.255]
main/pane/1/pane: w
view main
```

Because 'main' has alpha? set, ```Os-make-view``` will call ```process-layered-region``` which calls ```get-face-handle```. Last function called will check for ```state``` and it will crash.

**Comment by qtxie** [comment]
@Zamlox Thanks. I knew I forgot something... 囧

**Comment by qtxie** [comment]
Should be fixed with commit: 692ad4746116eb63062bce122d1e88b5fbbb7ea6

**Comment by nc-x** [comment]
@qtxie 
![untitled](https://cloud.githubusercontent.com/assets/16458742/15624841/7de7ab0e-24b1-11e6-9ab1-ea44778cef7b.png)
This is #1942

**Comment by dockimbel** [comment]
@qtxie @nc-x So is #1942 fixed? I can't reproduce the crash anymore.

**Comment by qtxie** [comment]
Should be fixed now.

**Comment by nc-x** [comment]
@dockimbel I never got any crashes. 
I just redownloaded the source after the commit which fixed #1920 and caused this issue but got no crashes. :smile: 
And I am not getting any crashes after the fix for this as well. :smile:
So most probably fixed.

**Comment by dockimbel** [comment]
Shoudn't we see a blue face inside the window? It doesn't seem to work, so maybe we should close this ticket and open a new one for that other issue? @qtxie What do you think?

**Comment by qtxie** [comment]
Nope. We can not see anything because the `main` is totally transparent.

**Comment by dockimbel** [comment]
But the `main` face has a child face which is blue (not transparent), we should see it?

**Comment by qtxie** [comment]
Yes, you're right. It's bug.

**Comment by qtxie** [comment]
But if we set the `visible?` of the parent to `false`, all child windows become invisible too.

**Comment by qtxie** [comment]
We can see the blue face now in the last version.
