### ISSUE TITLE
Mouse action "on-up" unexpected behavior.

### ISSUE THREAD

**Issue by Arie-vw** [red/red#1950]
It appears that on-up behaves like on-click.
When I use on-up and:
   - click a button
   - keep mousebutton pressed
   - move off the button
on-up still fires, which it shouldnt'..

Example.:
```
Red []
view [
    mytext: text 100x25 yello font-size 14 "Default"
    button "Click Me" on-up [mytext/text: "Changed"]
]
```

**Comment by dockimbel** [comment]
`up` is a low-level event, while `click` is a higher-level one. `up` will always be triggered when you release the left mouse button regardless of the mouse position.

For the `click` event, we should improve it in the future, so we might support cancellation too.
