### ISSUE TITLE
Click event not triggered on text face

### ISSUE THREAD

**Issue by endo64** [red/red#1951]
Below code prints clicked only double clicked on the text face:
`
red>> view [text "click" [print "clicked"]]
`

**Comment by nc-x** [comment]
@endo64 Is this a wish???
I think that the default for text is on-dbl-click.
This works for your use case -
```
view [text "click" on-click [print "clicked"]]
```

**Comment by dockimbel** [comment]
Click event is currently produces only for buttons, we need to make a custom implementation for this event in order to use it on other widgets. In the meantime, you can use `down` or `up` events for left mouse button clicks.
