### ISSUE TITLE
WISH: Allow setting words to path in object to keep its binding

### ISSUE THREAD

**Issue by rebolek** [red/red#1952]
Currently, when you set word to a path in object that is not `any-block!` you get the value but lose binding:

```
obj: object [a: [1 2 [3 4]]]
c: obj/a/3/1
c: 5
obj = [a: [1 2 [3 4]]]
```

This would be nice and very useful:

```
obj: object [a: [1 2 [3 4]]]
c: in obj 'a/3/1
c: 5
obj = [a: [1 2 [5 4]]]
```

**Comment by dockimbel** [comment]
You can already achieve similar feature using `set`:
```
obj: object [a: [1 2 [3 4]]]
c: 'obj/a/3/1
set c 5
obj = object [a: [1 2 [5 4]]]
```
What you are asking for is not compatible with how words and contexts work. When you write`
```
c: in obj 'a/3/1
```
You make the word `c` refer to path `a/3/1`. `c` is not concerned by what binding is used inside that path. When you use `c: 5`, you make `c` refer to a different value than the path, that is how set-words work in Red and Rebol, it does not (and cannot) trigger any special action on the old value itself.
