### ISSUE TITLE
Livecode example bad behaviour in GUI-Console

### ISSUE THREAD

**Issue by iArnold** [red/red#1953]
Newest 6177 Red.
Compiled GUI-console then starting Livecode by copying 
```Red
view [
	title "Red Livecoding"
	output: panel 400x600
	source: area 500x600 wrap font-name "Fixedsys" on-key-up [
		attempt [output/pane: layout/only load source/text]
	]
]
```

Now try typing 
`button "Hi"`

Right after release of " the cursor jumps to the start of the input area and I see
`Hbutton "`
Cursor then also sticks to the start of the inputarea.

**Comment by dockimbel** [comment]
Cannot reproduce anymore, so it's considered fixed.

**Comment by iArnold** [comment]
Affirmative. SBL solved by luck ;-P
