### ISSUE TITLE
Wish: POKE to be defined on pair! values

### ISSUE THREAD

**Issue by meijeru** [red/red#1958]
I cannot off-hand find a reason why it should not be defined.

**Comment by dockimbel** [comment]
It is not possible to support POKE on scalar values (values which fit entirely in a memory cell) with Rebol/Red language semantics.

We allowed POKE for tuples, like Rebol2 did (but not Rebol3), but that's a mistake which needs correction.

Here is an example:
```
red>> t: 1.2.3
== 1.2.3
red>> poke t 2 99
== 99
red>> t
== 1.2.3
```
POKE arguments (like for any function arguments), are pushed on a evaluation stack (the Red internal stack), so they are copied there, which means only the copy on the stack gets changed, not the one pointed by the word `t` (or any other kind of reference to a tuple or pair value).
