### ISSUE TITLE
Curious: PUT not defined on string!

### ISSUE THREAD

**Issue by meijeru** [red/red#1959]
The more curious, because it is inherited from `string!` by `file!`and `url!` but the action inherited is `null`.

**Comment by dockimbel** [comment]
`put` is not defined for strings as the key/value concept is not a good match for strings. That said, we might add it in the future if the need for it arises.

**Comment by meijeru** [comment]
If it is not appropriate for strings than *a fortiori* it should not be appropriate for files and urls. Therefore the inheritance can be removed.
