### ISSUE TITLE
Refinement order in function call not respected

### ISSUE THREAD

**Issue by Arie-vw** [red/red#1964]
Red []
add-up: function [/c cval /d dval] [
    temp: 0
    if c [
        temp: temp + cval
    ]
    if d [
        temp: temp - dval
    ]
    return temp
]
print add-up/c/d 3 4
print add-up/d/c 3 4

**Comment by nc-x** [comment]
@Arie-vw https://github.com/red/red/issues/1154

**Comment by nc-x** [comment]
Actually, the code in #1154 gives an error in console. But the code over here does not give any error, but returns wrong result.

**Comment by dockimbel** [comment]
Closing it as duplicate.
