### ISSUE TITLE
Not found image breaks program

### ISSUE THREAD

**Issue by iArnold** [red/red#1966]
```Red
view [image load %image/no-image-here.png]
```
This program when compiled will not start because the picture cannot be opened. 
Situation can easily occur when program is relocated and image was not moved along with it.
Red should open the program and display a "not-found" image for the missing image.

**Comment by dockimbel** [comment]
When compiling it, I get:
```
*** Script error: VID - invalid syntax at: [load %image/no-image-here.png]
*** Where: do
*** Stack: view if set either layout while switch unless throw-error cause-error do
```
which is a valid error as `image` does not evaluate aribitrary expressions. When your VID code is fixed:
```
Red [Needs: 'View]
view [image %image/no-image-here.png]
```` 
it retuns a proper error on start:
```
C:\Dev\Red>bug
*** Access error: cannot open: %image/no-image-here.png
*** Where: decode
*** Stack: view if set either layout while switch set fetch-options until unless
 either set switch select type? set pre-load if set load switch foreach if do de
code
```

**Comment by iArnold** [comment]
Correct my reproduction was in between I typed 'load here too. 
Point is. When starting the program by double clicking the icon or filename there will be no warning message in a cmd window and the user is left without a clue why his program does no longer work.
I know there are workarounds for this problem, like loading the image beforehand and if not available load a binary image like the smileyface in view-test.red or show a popup window warning the image could not be found, or make all images available in binary format in the code itself.
These workarounds are ok but not the most friendly for the user or programmer. So would be nice to have this case backed up by not having the program end like it does now.
Hope this clarifies my point.

**Comment by dockimbel** [comment]
*Correct my reproduction was in between I typed 'load here too.* Grammar rules are now optional in English? Please take care about writing as clearly and as accurately as possible when posting here.

I'm replacing this confusing ticket with a more appropriate one: #1967

**Comment by iArnold** [comment]
Not used typing commas anymore in fact I am thinking about having them surgically removed from my keyboard need some salt to go with the snails? ;)
