### ISSUE TITLE
'over events continue to be fired after a face has been dragged  (loose)

### ISSUE THREAD

**Issue by SteeveGit** [red/red#1970]
In the console, run the following test:
```
system/view/debug?: yes
view/options [b: base red loose][size: 400x400]
system/view/debug?: no
```
Move the mouse over the red box. 
No 'over events are fired at that point (except when entering and leaving the box). 
Drag the red box a little, then release it.
You'll notice in the console that a lot of 'over events continue to be fired when the mouse is inside the red box.
It should not be.

The reason is, the facet face/flags is not cleared:
`red>> b/flags`
`== all-over

...FIX incoming...

**Comment by SteeveGit** [comment]
Don't be abused by the 2 first reference of commits  (above), they were deleted.

**Comment by dockimbel** [comment]
Agreed, the flag should be removed when the dragging stops.
