### ISSUE TITLE
Red compiler does not allow an object to be created by a function

### ISSUE THREAD

**Issue by philipyi** [red/red#1977]
The following compiles with no errors.  When run the last 2 lines cause problems.
```
Red []
proto: object [
	m: 100
	foo: func [][m]
]

create: func [
	x [integer!]
][
	make proto [m: x]
]

obj: create 25
print obj/m      ;-- correctly prints 25
print obj/foo    ;-- ?function? instead of 25
obj/foo  /  2    ;-- Script error: / does not allow function! for its value1 argument
```

**Comment by dockimbel** [comment]
The compiler cannot generate function calls for the last two lines, you need to wrap them in DO [...] for now, until the `dyn-stack` branch is completed:
```
print do [obj/foo]
do [obj/foo  /  2]
```
Note that this is a compiler-specific current limitation, the interpreter can handle it fine.

See more info about that in #1748.
