### ISSUE TITLE
View doesn't get value of word!

### ISSUE THREAD

**Issue by endo64** [red/red#1980]
Below code produces the issue:

```
red>> x: [print "ok"]
red>> view [button "test" x]
*** Script error: copy does not allow word! for its value argument
```

**Comment by nc-x** [comment]
@endo64 I think this is because of https://github.com/red/red/issues/1922 
I don't know what the best way is to get the above code working but this works -
```
red>> x: [print "ok"]
red>> view [button "test" [do x] [x]]
```

**Comment by endo64** [comment]
By the way `draw` already works,

```
red>> b: [circle 50x50 30]
red>> view [base 300x300 draw b]
```

![image](https://cloud.githubusercontent.com/assets/840604/16442076/2c81444c-3dd8-11e6-9352-33f2e12759c6.png)
