### ISSUE TITLE
VID 'origin value is not used on right/bottom side of the window, but 'space one

### ISSUE THREAD

**Issue by DideC** [red/red#1981]
This code show that `space` value is used on right and bottom side of the window. `origin` value must be used there.
```
view layout [origin 0x0 space 25x25 button "Test this and you see the bug"]
```
In Rebol, (if you replace `button` by `btn` because `button` has a fixed width) the button is just centered and occupy the full window client area.
In Red, there is 25 pixel margin on right and bottom side.

workaround is simply to substract last spacing and add origin to last pane size, I guess.
So in [red/module/view/VID.red line 387:](https://github.com/red/red/blob/master/modules/view/VID.red#L387)
`if pane-size <> 0x0 [panel/size: pane-size]`
must be
`if pane-size <> 0x0 [panel/size: pane-size - spacing + origin]`
(not tested)

**Comment by DideC** [comment]
R2 `layout` use `span?` to compute the full size occupied by the faces in the window, and add the `origin` value to it.
I thought it was overkill first, but imagine the following code:
```
a: "text of the button in the window"
view layout [
    b: button 100x100
    do [b/text: a b/size: 8x8 + size-text b b/text]
]
```
In Rebol, the result is correct, but not in Red!

**Comment by dockimbel** [comment]
The difference in your last code example between Red/View and Rebol/View is caused by the text size calculation, in Rebol the text wraps in buttons by default, in Red, it does not (we might change that in the future).

**Comment by dockimbel** [comment]
I used your fix, it was the right one. Thanks! ;-)

**Comment by DideC** [comment]
As I said above, my first fix was a simple one that works in simple case.
It does not solve the problem of delayed face sizing like:```
a: "text of the button in the window"
view layout [
    b: button 100x100
    do [b/text: a b/size: 8x8 + size-text b b/text]
]
```

Rebol use `span?` to compute the window final size before rendering, so it avoid this behaviour.

**Comment by dockimbel** [comment]
@DideC We can improve the VID container size computation, but it still won't make your example code work in Red as you expect. See my first comment above.

**Comment by dockimbel** [comment]
You should open a new ticket for delayed VID sizes calculation, as it's a different topic than this one.

**Comment by DideC** [comment]
You are right, result would be different in Rebol and Red cause Rebol `button` style has a fixed size. Rebol `btn` is more like Red `button`.
If you replace `button` by `area` in the code, it's more fair... and the problem stand.
I will make another ticket for that, as you want.
