### ISSUE TITLE
Text Automatically Getting copied into clipboard for VID Application

### ISSUE THREAD

**Issue by nc-x** [red/red#1992]
Type this into console -
```
view [text "click" [print "clicked"]]
```
Press Enter.
Now double-click on the text `click`.
The text `click` automatically gets copied into clipboard.

**Comment by qtxie** [comment]
The console doesn't do any copy action, Is it a feature of the `text` face?

**Comment by dockimbel** [comment]
No, `text` widget does nothing like that as far I as know.

**Comment by qtxie** [comment]
It's not a bug, it's a feature of the static text control since Vista.

> Starting in Windows Vista, version 6 of the common controls provides an alternative. (A less accessible alternative, mind you.) Static text controls automatically copy their contents to the clipboard when you double-click them if you set the SS_NOTIFY style.

https://blogs.msdn.microsoft.com/oldnewthing/20120301-00/?p=8193

**Comment by dockimbel** [comment]
@qtxie Good finding. I think we should disable it because nobody knows about it and it could interfere with user's clipboard management, and it's probably not provided on other platforms.
