### ISSUE TITLE
WISH: refinement /hide on ASK and INPUT

### ISSUE THREAD

**Issue by meijeru** [red/red#1994]
This is in analogy with R3 (where the implementation is defective, though). The effect is to replace the echo'ed characters by \* or similar. Typical application: input of passwords.

**Comment by dockimbel** [comment]
The current implementations of `ask` and `input` are temporary until we get proper I/O support in 0.7.0, so I doubt we'll implement this feature before 0.7.0.

**Comment by meijeru** [comment]
Fine! It can wait, but I think in the end it will prove useful.

**Comment by dockimbel** [comment]
I didn't say it wasn't useful, just that we usually don't invest in polishing features which are implemented  with temporary code.

**Comment by dockimbel** [comment]
I will close this ticket as it's among planned features, but they won't come until 0.7.0 at least, where `ask` and `input` will be reimplemented in their final form.

**Comment by dockimbel** [comment]
We need this feature now for the `eth://` scheme.

**Comment by 9214** [comment]
@dockimbel coincidentially, @bitbegin wanted to implement this after recent [request](https://gitter.im/red/help?at=5d6777724b1189084e830624).
