### ISSUE TITLE
Wish: image! value indexing could be done by pair! value

### ISSUE THREAD

**Issue by meijeru** [red/red#2006]
Semantics would be like in R2 (row x column), but I would suggest 1-origin instead of the 0-origin that R2 has, which is presumably for faster computation. Even with 1-origin, a native implementation would be more efficient than what the Red programmer has to do now: compute the index into the image explicity from a given pair of coordinates.

**Comment by qtxie** [comment]
Implemented in commit d5ad3629c64a56569f72cd534326961d11ed3c8c.
