### ISSUE TITLE
Wish: ESC should return to >> level even when typed in response to ASK

### ISSUE THREAD

**Issue by meijeru** [red/red#2008]
This is Rebol 2 behaviour and it allows, amongst others, to terminate any computation prematurely (e.g. a FOREVER loop that has gone bad).

Currently, typing ESC into ASK yields the string "^[" i.e. the molded escape.

**Comment by x8x** [comment]
see https://github.com/red/red/issues/1844

**Comment by meijeru** [comment]
Duplicates #1844.
