### ISSUE TITLE
SPLIT with charset produces garbage, memory corruption or no string end  delimiter?

### ISSUE THREAD

**Issue by xqlab** [red/red#2031]
red>> split "1,3,.3,," charset ".,"
== ["1" "3" "" "3" "" {^@^@^@^@^@^@^@^@^A^@^@ Pþ5^@^P^@^@^@¸G^B¿G^Bcharset^@^@^@^@^@^@^@^@^@^A^@^@ Lþ5^@^P^@^@^@ÜG^BÞG^B}]

**Comment by dockimbel** [comment]
This is actually a `parse` bug on matching bitsets.
