### ISSUE TITLE
LS does not work with words representing file paths

### ISSUE THREAD

**Issue by xqlab** [red/red#2032]
red>> d: %/C/
== %/C/
red>> ls d
*** Access error: cannot open: %/C/Users/user1/own/rebol/d/
*** Where: read
red>>

**Comment by dockimbel** [comment]
`ls` is not meant to evaluate its argument, `list-dir` should do that, but it's currently failing to do so.

**Comment by dockimbel** [comment]
Now `list-dir` will work for such use-case.
