### ISSUE TITLE
Functions ?? and SOURCE should also take a path! as argument

### ISSUE THREAD

**Issue by meijeru** [red/red#2035]
It often happens that one wishes to know the source of a function that is defined within a context. Currently, this is not possible since both ?? and SOURCE take only `any-word!` as argument. Extension to `any-path!` is quite feasible and does not even need a change of program logic.

**Comment by xqlab** [comment]
like that?
        
    ??: func [
        "Prints a word and the value it refers to (molded)" 
        'value [word! path!]
    ][
        prin mold :value 
        prin ": " 
        print either value? :value [mold get/any :value] ["unset!"]
    ]

    red>> o: context [ i: does [print 1]]
    == make object! [
           i: func [][print 1]
    ]
    red>> ?? o
    o: make object! [
        i: func [][print 1]
    ]

**Comment by meijeru** [comment]
Rather, `?? o/i` and `source o/i` which are impossible currently.

**Comment by xqlab** [comment]
Sorry, forgot one example with above function

    red>> ?? o/i
    o/i: func [][print 1]
    red>>

**Comment by xqlab** [comment]
```
red>> source: func [
[        "Print the source of a function" 
[        'func-name [any-word! any-path!] "The name of the function" 
[        /local type
[    ][
[        print either function? get/any func-name [[append mold func-name #":" mold get func-name]] [
[            type: mold type? get/any func-name ["Sorry," func-name "is" a-an type type "so no source is available"]
[        ]
[    ]
== func [
    "Print the source of a function" 
    'func-name [any-word! any-path!] "The name of the funct...
red>> source system/platform
system/platform: func ["Return a word identifying the operating system"][
    #system [
        #switch OS [
            Windows [SET_RETURN (words/_windows)] 
            Syllable [SET_RETURN (words/_syllable)] 
            MacOSX [SET_RETURN (words/_macosx)] 
            #default [SET_RETURN (words/_linux)]
        ]
    ]
]
red>> 
```

**Comment by meijeru** [comment]
Since I don't have GitHub commit facilities, I would be happy for you to make the pull request.

**Comment by meijeru** [comment]
Next week this wish will be a year old. Since it is now fulfilled, I close it.
