### ISSUE TITLE
make an-image [] close the console

### ISSUE THREAD

**Issue by DideC** [red/red#2036]
In Rebol you can do:```
>> i: make image! 5x5
== make image! [5x5 #{
000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000...
>> j: make i []
== make image! [5x5 #{
000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000000...
```
But in Red, the second line close the console immediately!

**Comment by dockimbel** [comment]
Feature not yet implemented.

**Comment by DideC** [comment]
OK. Noted.
