### ISSUE TITLE
`0 = 0` in a SWITCH case does not return TRUE

### ISSUE THREAD

**Issue by dockimbel** [red/red#2048]
Following code ouputs FALSE instead of TRUE:
```
Red/System []

foo: func [return: [logic!]][
	switch 1 [1 [0 = 0]]
]
probe foo
== false
```
Though, using any other integers for the comparison works as expected:
```
Red/System []

foo: func [return: [logic!]][
	switch 1 [1 [123 = 123]]
]
probe foo
== true
```

**Comment by iArnold** [comment]
For what it is worth: I use a version from 15-6-2016 commit nr 6329 and that is still ok, returning true.

**Comment by dockimbel** [comment]
@iArnold Tested with last commit on 14th, a commit from 15th and first commit from 16th, all return `false`. Moreover, there is no commit hash in 2016 containing "6329"... Congratulations for wasting my time!

**Comment by PeterWAWood** [comment]
@dockimbel Shouldn't it return ```true```?

This code suggests there is a bug:
```
Red/System []
print ["using 0 = 0" lf]
print [0 = 0 lf]										;--true
f: func [return: [logic!]][0 = 0]
print [f lf]											;--true
print [switch 1 [1 [0 = 0]] lf]							;--false
switch 1 [1 [print [0 = 0 lf]]]							;--true
switch 1 [1 [print f lf]]								;--true
print lf												;--needed because previous lf got "eaten"
f1: func [return: [logic!]][switch 1 [1 [0 = 0]]]
print [f1 lf]											;--false

print ["using 1 = 1" lf]
print [1 = 1 lf]										;--true
f2: func [return: [logic!]][1 = 1]
print [f2 lf]											;--true
print [switch 1 [1 [1 = 1]] lf]							;--true
switch 1 [1 [print [1 = 1 lf]]]							;--true
switch 1 [1 [print f2 lf]]								;--true
print lf												;--needed because previous lf got "eatien"
f3: func [return: [logic!]][switch 1 [1 [1 = 1]]]
print [f3 lf]											;--true
```

**Comment by dockimbel** [comment]
Yes, it should return TRUE, there was a typo in my description message (though the title was accurate).

**Comment by iArnold** [comment]
@dockimbel I truly regret wasting anyones time, let alone yours. I just tested this to see if I could reproduce this issue, so you would have a clue if this was before or after the version I used. Just to HELP you.

It was THIS commit https://github.com/red/red/tree/02cb58c28f3a350c65bf65147648974b8e3beda5 when I downloaded the red-master.zip
commit number 6329.

kind regards,

Arnold

**Comment by iArnold** [comment]
Next older version I had before that was red-master-6253-20160610.zip, but having the gui-console built on the 15th it must have been the one I mentioned earlier. It has time (now* is in natives.reds) and the configuration file.
