### ISSUE TITLE
Resize event on gui-console is also handled by spawned window, leads to console crash

### ISSUE THREAD

**Issue by asampal** [red/red#2051]
Running Windows 10 64 bit, Red 8ec8635b4af8defb8b95b85824324f5eadb1fece

To reproduce:
Open gui-console
Paste source of [clock demo](https://github.com/red/code/blob/master/Scripts/clock.red) into console
Resize gui-console: you will see size event is also handled by clock. While resizing, the gui-console goes blank and remains blank even after resizing is stopped. Closing the clock window causes a crash in the gui-console.

![resize-event](https://cloud.githubusercontent.com/assets/281639/16201153/4c5d3b5a-36de-11e6-872d-0f5f173c9c1d.gif)

**Comment by dockimbel** [comment]
The global handler in %clock.red is affecting boths windows, it needs to filter the events for the clock window only. The script will be fixed before the new release.

**Comment by dockimbel** [comment]
Fixed in `v0.6.1` branch in red/code repo by commit https://github.com/red/code/commit/bfb129b57a6eb3443d8ef91f35aed211d5f8e8f2.
