### ISSUE TITLE
WISH: GUI Console should also accept CTRL-X (CUT) and CTRL-Z (UNDO)

### ISSUE THREAD

**Issue by meijeru** [red/red#2054]
It does accept CTRL-C and CTRL-V for copy/paste already. Especially when using the console for rapid testing, these two will come in handy.

**Comment by meijeru** [comment]
It could also accept CTR-L for clearing the screen.

**Comment by dockimbel** [comment]
Agreed for CTRL-L, though for the other too, I'm afraid it's too much work, so it will wait for the next big iteration on the console (we plan to port more console code from R/S to Red).

**Comment by dockimbel** [comment]
CTRL-L is now implemented by commit https://github.com/red/red/commit/6afc3fb001ff24ffe08f635e3847c95c152e108f.

**Comment by qtxie** [comment]
CTRL-X (CUT) and CTRL-Z (UNDO) are implemented in new gui console.
