### ISSUE TITLE
Functions that need time! support added

### ISSUE THREAD

**Issue by greggirwin** [red/red#2057]
mod modulo
even? odd?
absolute negate
negative? positive? zero?
pick first second third
min max
sign? (TBD)

**Comment by meijeru** [comment]
If negative? and positive? are added, I think sign? should be too, but then also for number! types.

**Comment by dockimbel** [comment]
`pick first second third` now support time!.

**Comment by Oldes** [comment]
`absolute negate mod modulo` also already support time!

**Comment by Oldes** [comment]
I'm not sure if to support `even?` and `odd?` for decimal numbers - so for time too. Rebol converts the decimal value to integer before even/odd test. Should we do the same in Red?

**Comment by Oldes** [comment]
`zero?` is now in Red just an ordinary function.. don't we want to make it native?

**Comment by dockimbel** [comment]
`even?` and `odd?`, yes we can do the implicit conversion to integer. 

For `zero?`, we could yes, though, it's not high-priority for now.

**Comment by Oldes** [comment]
Just wanted to know if you will merge it, if I do it.

**Comment by Oldes** [comment]
@dockimbel  In the pull request is now also implemented `odd?` and `even?` on float! and time! and `zero?` as a native with `time!` and additionally `char!` support. So it is more than requested in this issue.
