### ISSUE TITLE
Cross compile-error (RPi)  in function: ***-on-div-error

### ISSUE THREAD

**Issue by vdsfr** [red/red#2061]
Red [ ] 
;--------------------------------
 add-digs: func [digs [block!]][
 ;
 ]
 
digs: [ 1 2 3 4 5]
add-digs digs
;------------------------------

-=== Red Compiler 0.6.0 ===-

;--Compiling code above for Windows works. 
For **RPi** it fails with error message:

*** Compilation Error: undefined symbol: address 
*** in file: %common.reds 
*** in function: ***-on-div-error
*** at line: 167 
*** near: [address]

**Comment by dockimbel** [comment]
@vdsfr Did you try with latest Red binary? It compiles fine here with latest version.

**Comment by vdsfr** [comment]
Confirming the latest Red binary Red24june16 worked.
