### ISSUE TITLE
Set-word! declared only in view layout won't compile

### ISSUE THREAD

**Issue by greggirwin** [red/red#2067]
```
canvas: none    ;<== Had to add this to get it to compile

win: layout/tight [
	size win-size
	origin 0x0
	canvas: base win-size 10.10.255 draw draw-blk
]
until [
	...
	show canvas
	...
	quit?
]
```
The output is:
-=== Red Compiler 0.6.0 ===- 

Compiling D:\Red\demo\bubbles-2.red ...
*** Compilation Error: undefined word canvas 
*** in file: %/D/Red/demo/bubbles-2.red
*** near: [canvas 
    do-events/no-wait 
    quit?
]

**Comment by dockimbel** [comment]
That is normal, the compiler cannot recognize what is `canvas` in `show canvas` if it's not defined anywhere else (the Red compiler can't process dialects). So, adding `canvas: none` is the right thing to do in order to compile the code.
