### ISSUE TITLE
unique/skip does compare only first item in skip group instead of whole group

### ISSUE THREAD

**Issue by Arie-vw** [red/red#2069]
Example:

red>> unique/skip "abcdefabcghijklmnoghi" 3
== "abcdefbcghijklmnohi"

Expected result:
== "abcdefghijklmno"

**Comment by qtxie** [comment]
So in this case (different between Rebol2 and Rebol3): 
```
unique/skip "abc1abc2abc3" 3
```
Should return:
```
== "abc1abc2abc3"
```

**Comment by dockimbel** [comment]
@qtxie Right, I think the R2 implementation of `unique/skip` is just buggy.

**Comment by dockimbel** [comment]
@qtxie Right, R2's version is buggy.
