### ISSUE TITLE
%View-hanoi.red doesn't work when compiled.

### ISSUE THREAD

**Issue by greggirwin** [red/red#2074]
%View-hanoi.red doesn't work when compiled. First disk goes up, then animation stops. Tried both with and without -t (Windows). 

https://gist.github.com/greggirwin/5da11ee2893f87ccdfc883f670f70368

**Comment by iArnold** [comment]
In my old gui-console this script crashes on 
	Date:   "4-Oct-2001 — 26-Jun-2016"
red>> do %../script/view-hanoi.red
*** Access error: invalid UTF-8 encoding: #{97203236}
*** Where: do
Perhaps it is related or it is a bug on its own.

Sometimes the blocks on the left stick are cut of on the left side
Pressing "Close" also closes console, so should do an unview, not a quit?

**Comment by greggirwin** [comment]
I just checked, and it's UTF-8 here, but I pasted to the gist again, to see if that helps.

Under the official 0.6.0 interpreter, the disks aren't colored, but the alignment is fine. I do want to align the buttons differently.

For demos, do we want to quit or just unview? In some cases, with a manual event loop, we have to make sure we don't leave it spinning.

**Comment by nc-x** [comment]
On latest Red Master Binary, I get this error while try to compile -
```
Compiling C:\Users\ABC\Desktop\a.red ...
*** Compilation Error: expected a block for WHILE-CONDITION instead of word! value
*** in file: %/C/Users/ABC/Desktop/a.red
*** near: [test [move-face face way process-events]]
```

**Comment by dockimbel** [comment]
Closing this ticket as duplicate for #2075.
