### ISSUE TITLE
WHILE with word referring to block condition doesn't compile

### ISSUE THREAD

**Issue by greggirwin** [red/red#2075]
```
i: 0
test: [i < 10]
while test [i: i + 1]
print i
```
-=== Red Compiler 0.6.0 ===- 

Compiling D:\temp\red\while-word-compile.red ...
*** Compilation Error: expected a block for WHILE-CONDITION instead of word! value 
*** in file: %/D/temp/red/while-word-compile.red
*** near: [test [i: i + 1] 
    print i
]

**Comment by SteeveGit** [comment]
Quote From Doc:
> *Note:* the compiler will not accept it as is, because it expects a literal condition block for `while`. Replacing `cond` by `[do cond]` would make it pass compilation. The compiler should be able to handle such cases in the  close future.

**Comment by dockimbel** [comment]
@SteeveGit Thanks! ;-)

**Comment by dockimbel** [comment]
I'm closing this ticket as this is a feature the compiler does not support yet.
