### ISSUE TITLE
GUI console won't quit through File menu

### ISSUE THREAD

**Issue by meijeru** [red/red#2076]
See the attached screenshot. The `console-cfg.red` file is present, but the console says it cannot access it. The `quit` command at the command prompt works normally. The error may be related to the directory that the console is started in...
![quit-problem](https://cloud.githubusercontent.com/assets/743227/16411451/5e21f142-3d27-11e6-84ba-7ae934103959.JPG)

**Comment by qtxie** [comment]
@meijeru Looks like the `console-cfg.red` is locked by other programs. Did you open it with an editor when close the gui-console?

**Comment by meijeru** [comment]
No, this occurs after a fresh restart of Windows 10.

**Comment by dockimbel** [comment]
@meijeru Can you manually write into that file from the console?

**Comment by meijeru** [comment]
No I can't and I get exactly the same error.

**Comment by meijeru** [comment]
NOTE: meanwhile I have deleted `%console-cfg.red` and had it re-created by the console. I cannot anymore reproduce the issue now. Probably was a glitch.
