### ISSUE TITLE
Access violation occurs when modifying a block in a reactor!

### ISSUE THREAD

**Issue by dander** [red/red#2077]
demonstrated by the following code:
```
Red [
    Title: "reactive test"
]

probe system/build

sum: function [list [block!]][
    total: 0
    foreach i list [total: i + total]
]

r: make reactor! [
    l: [3 4 5 6]
    total: is [sum l]
]
probe r

r/l: append copy r/l 5  ; works
probe r

append r/l 5    ; access violation
```

output:
```
λ red-28jun16-0d1be60.exe --cli sum.red
"28-Jun-2016/0:33:06-7:00"
make object! [
    l: [3 4 5 6]
    total: 18
]
make object! [
    l: [3 4 5 6 5]
    total: 23
]

*** Runtime Error 1: access violation
*** at: 0042D467h
```

If I change the `reactor!` object to use `deep-reactor!` instead, then it works, and the `total` value is updated when the block changes.

**Comment by dockimbel** [comment]
Thank you for this report!

**Comment by dockimbel** [comment]
About your `sum` function, the return value of iterators is not entirely consistent depending on the iterator and if the code is interpreted or compiled (there's at least one ticket opened for that). So until this is fixed, it is safer to explicitely return the value (in your case, just `total` as last expression of `sum`).

**Comment by dander** [comment]
Thanks for the info on that! Yesterday I was just experimenting with different ways I could do it. I started with `return total`, then realized just `total` would work, and if that, why not remove it entirely :smile:

**Comment by greggirwin** [comment]
You're correct to remove `return` when it's not needed, unless you need to work around temporary issues. Helps finding bugs too. :^)
