### ISSUE TITLE
Cannot use LENGTH? on IMAGE!

### ISSUE THREAD

**Issue by rebolek** [red/red#2078]
In Rebol, I can use `length?` on `image!` type:

```
>> type? image
== image!
>> length? image
== 1512
```

That’s not possible in Red:

```
red>> type? image
== image!
red>> length? image
*** Script Error: length? does not allow image! for its series argument
*** Where: length?
```

**Comment by meijeru** [comment]
I think this was solved by [this commit](https://github.com/red/red/commit/f9b18cbe1c1005e377b0033f549d79d6a620a342)
