### ISSUE TITLE
broken chain reactor

### ISSUE THREAD

**Issue by WiseGenius** [red/red#2083]
```
red>> a: make reactor! [x: 1 y: is [x + 1] z: is [y + 1]]
== make object! [
    x: 1
    y: 2
    z: 3
]
red>> a/x: 4
== 4
red>> a
== make object! [
    x: 4
    y: 5
    z: 3
]
red>> a/z
== 3
```
Expected `6`.

**Comment by dockimbel** [comment]
I forgot to implement events triggering in the SET native when applied to object. IS function is relying on it, though REACT is not affected by that. Will implement it today.
