### ISSUE TITLE
DECLARE doesn't support alias struct! within contexts

### ISSUE THREAD

**Issue by darithorn** [red/red#2095]
The compiler doesn't seem to support declaring a struct that's been aliased inside a context.

```
foo: context [
    bar!: alias struct! [
        tmp [integer!]
    ]
]
test: declare foo/bar!
```

Gives the compiler error:
`*** Compilation Error: declaring literal for type foo/bar! not supported`

This isn't a huge issue since you can simply define it as `foo-bar!` but it would be nice for consistency.

**Comment by dockimbel** [comment]
Thank you for the ticket.
