### ISSUE TITLE
documentation lack of examples

### ISSUE THREAD

**Issue by xcombelle** [red/red#2101]
When doing `help something`, some examples would be handy to understand how it works. An online documentation would be useful otherwise

**Comment by dockimbel** [comment]
`help <arg>` command is only meant to extract the doc-strings from the values in memory, like from function's header, nothing more. The amount of information in doc-strings is very limited, examples cannot fit there. Such embedded help is meant mostly as a quick reference while coding in the console, without having to search online.

For an online documentation, you can look into our [website](http://www.red-lang.org) at "Getting Started" and "Documentation" pages.
