### ISSUE TITLE
UTF-8 encoding (unit=0) in SeriesBuffer! struct will cause "divide-by-zero" Error

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2112]
I am making a Red/System application which needs to serialize and unserialize Red value from file system. When it comes to Red-String!, I choose to use UTF-8 as the string format in SeriesBuffer!. So I set unit bits (in SeriesBuffer/Flags) to 0, and I get the following information.

```Red
*** Runtime Error 13: integer divide by zero
*** in file: /Users/jenniferlee/datatypes/string.reds
*** at line: 904
```
If I set unit to 1, the code can run without error message, but only strings in ASCII (which take 1 byte) can show correctly, Chinese strings are decoded wrongly.

The line 904 is as follows
```Red
	size:  (as-integer s1/tail - s1/offset) + (unit1 / unit2 * size2)		;-- account for keep?
```

**Comment by qtxie** [comment]
@JenniferLee520 Currrently `UTF-8` encoding is not supported in `series-buffer/flags`. To serialize a red-string!, use following code:
```
Red/System []

;-- convert red-string! to utf8 encoding c string
;-- set `len: -1` to convert the whole string
;-- the length of the converted string will be set in `len`
len: -1
c-str: unicode/to-utf8 red-str :len

;-- write it to file (pesudo code)
write %file1 c-str len

;-- read it back (pesudo code)
buffer: allocate len
len: read %file1 buffer

;-- convert data to red-string!
red-str: string/load as c-string! buffer len UTF-8
```

**Comment by JenniferLee520** [comment]
Thanks. your code works well. You can close this issue, or keep it open as a reminder of UTF-8 support in SeriesBuffer!.
