### ISSUE TITLE
HELP adds trailing dot if func doc string ends with a dot.

### ISSUE THREAD

**Issue by greggirwin** [red/red#2123]
```
red>> dirize: func [
[        "Returns a copy of a filespec with a trailing path marker."
[        path [file! string! url!]
[    ][
[        ; Always return a copy of the path.
[        path: copy path
[        either slash = last path [path][append path slash]
[    ]
== func [
    {Returns a copy of a filespec with a trailing path marker.} 
    path [file! string! url!]
][path: copy path 
    either s...
red>> ? dirize

USAGE:
    dirize path

DESCRIPTION:
     Returns a copy of a filespec with a trailing path marker.. 
     dirize is of type: function!

ARGUMENTS:
     path  [file! string! url!]

REFINEMENTS:
```

**Comment by dockimbel** [comment]
That is the convention we adopted, docstrings do not need an ending dot, as the end is delimited by the closing double quote. Adding a dot when printing it is up to the docstring processor, which is currently only HELP function.

**Comment by greggirwin** [comment]
I know it's the convention (some doc strings may need cleaning), but some people may want to write their doc strings to be more grammatically correct. If they do, this will look like an error on HELP's part.

**Comment by greggirwin** [comment]
Unless you want to be strict in this convention, no matter whose code it is. i.e. is the convention that they MUST NOT have an ending dot, or that they MAY have one?

**Comment by dockimbel** [comment]
Making HELP a little smarter about that wouldn't hurt. You can make a PR to take an eventual ending dot into account. Though, the convention stays for red/red repo.

**Comment by dockimbel** [comment]
Also, maybe rewriting the HELP code would be nice too, as it was contributed by someone, by directly porting the R2 version, not taking into account R3's improvements. I tried to put back some of those improvements, but the whole HELP code is not very well architectured, a cleaner and shorter version would be welcome.

**Comment by greggirwin** [comment]
I'm good with Red deciding its own repo rules. :^)

**Comment by Oldes** [comment]
@dockimbel I can give it a try to rewrite the current help.

**Comment by greggirwin** [comment]
I stopped working on my version when Ingo's was included with Red. I can post it somewhere if you want to collaborate Oldes.

**Comment by greggirwin** [comment]
Or I could tackle this so you can focus on deeper issues from the R/S side. You've been doing a lot there lately.

**Comment by Oldes** [comment]
It's ok.. I already have it.. just some clean up needed.

**Comment by rebolek** [comment]
I have help parse done for `helpr`, VID help, it would would probably make sense to share the code.
