### ISSUE TITLE
switch chokes on datatypes

### ISSUE THREAD

**Issue by WiseGenius** [red/red#2125]
When checking a value equal to `block!`, `switch` errors with a strange message:
```
red>> switch/default block! [
[        #[block!] [print "yes"]
[    ][print "no"]
*** Script Error: author has no value
*** Where: switch
```

When checking a value equal to any other datatype except `datatype!`, `switch` fails to match it:
```
red>> switch/default word! [
[        #[word!] [print "yes"]
[    ][print "no"]
no
```

But hang on. What's this?
```
red>> switch/default integer! [
[        #[integer!] [print "yes"]
[        1 [print "one"]
[        2 [print "two"]
[    ][print "no"]
one
```

I could maybe understand the other way around, but:
```
red>> switch/default 1 [
[        #[integer!] [print "yes"]
[    ][print "no"]
no
```

And then there's this:
```
red>> switch/default string! [
[        #[string!] [print "yes"]
[        1 [print "one"]
[        2 [print "two"]
[        "Surely not!" [print "Oh dear!"]
[    ][print "no"]
Oh dear!
```

And even this:
```
red>> switch/default block! [
[        [a] [print "No way!"]
[    ][print "no"]
No way!
```

**Comment by dockimbel** [comment]
SWITCH is using FIND internally, so the issue is FIND not matching the datatype! properly.

**Comment by WiseGenius** [comment]
Should this result be expected?
```
red>> switch/default integer! [
[        1 [print "one"]
[        2 [print "two"]
[        #[integer!] [print "yes"]
[    ][print "no"]
one
```
Again, I could maybe understand the other way around, but still:
```
red>> switch/default 1 [
[        #[integer!] [print "yes"]
[    ][print "no"]
no
```
And then there's this:
```
red>> switch/default string! [
[        1 [print "one"]
[        2 [print "two"]
[        "Surely not!" [print "Oh dear!"]
[        #[string!] [print "yes"]
[    ][print "no"]
Oh dear!
```
And still this:
```
red>> switch/default block! [
[        [a] [print "No way!"]
[    ][print "no"]
No way!
```
And should this be happening?
```
red>> switch/default [print "a"] [
[        [a] [print "a"]
[        [b] [print "b"]
[    ][print "no"]
*** Script Error: b has no value
*** Where: switch
```
And therefore this strange value again?
```
red>> switch/default [print "b"] [
[        [a] [print "a"]
[        [b] [print "b"]
[    ][print "no"]
*** Script Error: author has no value
*** Where: switch
```
Rebol 2 and 3 return "no" in both of the last 2 cases. Is it too early to test for this sort of thing?

**Comment by dockimbel** [comment]
Should work like Rebol now. Support for block-as-keys has been removed, as it causes too many ambiguities, and prevents multiple keys support.

**Comment by WiseGenius** [comment]
One of the later fixes has caused a regression:
```
red>> switch/default 'a-word ['a-word [print "OK"]][print "broken"]
broken
```

**Comment by dockimbel** [comment]
That case is correct, `switch` argument is strictly matched, so `'a-word` evaluates to `a-word` (type word!) and does not match `'a-word` (type lit-word!) in the body block. Same as in Rebol2 and Rebol3.

If you want to match a lit-word!, you need to pass one as argument:
```
red>> switch/default first ['a-word]['a-word [print "OK"]][print "broken"]
OK
```

**Comment by WiseGenius** [comment]
Oops! Or this way if I wanted to match a word:
```
>> switch/default first [a-word] [a-word [print "OK"]][print "broken"]
OK
>> switch/default 'a-word [a-word [print "OK"]][print "broken"]
OK
```
Thanks.

**Comment by dockimbel** [comment]
Right. ;-) Thanks for all the test cases, we'll convert them to unit tests.
