### ISSUE TITLE
Runtime crash on using op! created with action! that has refinements.

### ISSUE THREAD

**Issue by ifgem** [red/red#2132]
Action! with refinements **doesn't work**.
```red
<<: make op! :append ; doesn't raise any error.
[h] << [ha] ; crashes Red
```
Action! without refinements **works as expected**.
```red
<>: make op! :swap
[1] <> [3] ; => [3]
```
Function! with refinements **works as expected**.
```red
testing: func [a b /test] [either test [print "works"] [a + b]]
<<: make op! :testing
10 << 20 ; => 30.
```

**Comment by dockimbel** [comment]
A proper error will now be displayed if the source function does not strickly have 2 arguments only, and no refinements.
