### ISSUE TITLE
Printing of float values with high exponent is broken

### ISSUE THREAD

**Issue by dockimbel** [red/red#2135]
```
Red/System []

probe 1.836E13
```
gives
```
1.836e+013.0
```

**Comment by dockimbel** [comment]
The culprit is a wrong `printf` format string [here](https://github.com/red/red/blob/master/system/runtime/libc.reds#L171).

**Comment by greggirwin** [comment]
Does `printf ["%g" n]` do what you want? i.e. `1.836e+013`

**Comment by greggirwin** [comment]
Looks like the 2 vs 3 E digits may vary by platform.

**Comment by dockimbel** [comment]
@greggirwin If you remove the `.0` part, then printing a rounded float will look like an integer, it will not have the tail `.0` anymore.

**Comment by greggirwin** [comment]
I wasn't sure exactly what you wanted, since you only said "it's broken". Your digit has the decimal, so I guess I'm not clear why the exponent needs it. No coffee yet this morning. :^)

**Comment by dockimbel** [comment]
We should not have the `.0` for the exponent, but if you remove ".0" from the formatting string, you're then breaking the rounded floats formatting.

**Comment by greggirwin** [comment]
Ah, I see. Without printing to a buffer and post-processing, I'm not finding a quick solution. 
```
printf ["%#g" 1.836E13]		;== 1.83600e+013
printf ["%#g" 1.0]			;== 1.00000     
```
As soon as you spec a width/precision, it rounds (not what I expected). Well, it does anyway, with a default of 6.
