### ISSUE TITLE
to string! crashes for binaries from #{C0} to #{F7}

### ISSUE THREAD

**Issue by x8x** [red/red#2137]
```
  repeat n 56 [to string! debase/base at form to-hex n + 191 7 16]

*** Runtime Error 1: access violation
*** at: 0001838Fh
```
and just wondering, shouldn't this return `#{C0}` (`C0` being hex for 192):
```
  append #{}  make char! 192
;   #{C380}
```

**Comment by qtxie** [comment]
When convert a char! to binary!, it will be encoded to UTF-8. We may provide a way to specify how a char! or string! be encoded when convert it to binary! in the future.
