### ISSUE TITLE
Red console is crashing when started on MacOs 10.7.5

### ISSUE THREAD

**Issue by ifgem** [red/red#2151]
Error:
> dyld: Library not loaded: /System/Library/Frameworks/CFNetwork.framework/CFNetwork
>   Referenced from: /Users/Qwerty/.red/console-2016-8-4-31595
>   Reason: image not found

**Comment by dockimbel** [comment]
Fixed by commit https://github.com/red/red/commit/e19f63a0dd1fd73b3e606b57de13cb7bd91e1d03.
