### ISSUE TITLE
Incorrect work of function with get-word! in function's argument block.

### ISSUE THREAD

**Issue by ifgem** [red/red#2154]
(Compared with Rebol2) (Rebol3 has the same behavior).
**Rebol2:**
```
test: func [a :red] [probe red a + red]
test 10 red =>
  255.0.0
  255.0.1
```
**Red:**
```
test: func [a :red] [probe red a + red]
test 10 red =>
  red
  *** Script Error: word! type is not allowed here
  *** Where: +
```
**Strange difference between op! and functon! behavior:**
```
test: func [:r :b] [r + b]
+_+: make op! :test
red +_+ blue => 255.0.255
```

**Comment by dockimbel** [comment]
Red follows the Rebol3 behavior there, so it is the correct result.

*Strange difference between op! and functon! behavior* I don't see a difference at all...
