### ISSUE TITLE
The latest Auto-build version of Red treats files as directories when I try to DO the file in console.

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2156]
``` Red
red>> do %McEn.red
*** Access Error: cannot open: %/C/Users/JenniferLee/Desktop/McEn.red/
*** Where: do
```

The file %McEn.red does exits though.

**Comment by qtxie** [comment]
I cann't reproduce it on win 7 and win 10.

**Comment by dockimbel** [comment]
I cannot reproduce it either.

**Comment by JenniferLee520** [comment]
This happened from time to time. even in the latest version. Both on Windows and Mac. It is not easy to reproduce this bug. When it happens, I have to load the source file then do the block, instead. After a few hours, it will back to normal, and maybe not. This issue is tricky.

**Comment by qtxie** [comment]
As we cannot reproduce it for now, I close this issue.
