### ISSUE TITLE
Dividing -2147483648 by -1 crashes the runtime

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#2157]
Dividing -2147483648 by -1 crashes the runtime instead of throwing an integer overflow script error.

```
red>> error? try [-2147483648 / -1]

*** Runtime Error 13: integer divide by zero
*** at: 00025371h
```

There is a test of this in integer-test.red, it is currently commented out.

**Comment by PeterWAWood** [comment]
This bug can also be seen with ```remainder```:
```
red>> -2147483648 % -1

*** Runtime Error 13: integer divide by zero
*** at: 00025323h
mbp:red peter$ ./test-console
--== Red 0.6.1 ==-- 
Type HELP for starting information. 

red>> remainder -2147483648 -1

*** Runtime Error 13: integer divide by zero
*** at: 00025323h
```

**Comment by dockimbel** [comment]
Those cases are now producing an error. In Red/System, it will produce an "integer overflow" runtime error.
