### ISSUE TITLE
Write/info crashes when a custom header is used 

### ISSUE THREAD

**Issue by dockimbel** [red/red#2162]
It seems like a regression:
```
red>> write/info https://api.github.com/user [GET [User-Agent: "me"]]
<runtime crash>
```
If no header is passed, it doesn't crash:
```
red>> write/info https://api.github.com/user [GET []]
== [401 #(
    Date: "Mon, 08 Aug 2016 11:03:37 GMT"
    Content-Length: "91"
    Content-Type: "applicati..
```

**Comment by StephaneVeneri** [comment]
A clue: works fine in terminal Window and macOS, but it crash in Gui Console.

**Comment by StephaneVeneri** [comment]
Correction:
Works fine with macOS
Crash are random in cmd.exe et Gui Console:
```
*** Runtime Error 13: integer divide by zero
*** at: 004139EEh
```

**Comment by rebolek** [comment]
Crashes for me under OSX (using latest commit fa7ec196faa41e21680f84c65ada1ba4cbb29483).
