### ISSUE TITLE
WISH: new percent! behavior

### ISSUE THREAD

**Issue by ifgem** [red/red#2164]
New:

```
100 + 10% => 110; = 100 * 110%
100 - 10% => 90; = 100 * 90%
```

Current:

```
100 - 10% => 99.9
100 + 10% => 100.1
```

**Comment by dockimbel** [comment]
A percent is really just a number divided by 100, so `10% == 0.1`.

**Comment by meijeru** [comment]
@dockimbel In changing the semantics, I suppose you will consider these 4 cases:
integer + or - percent
float + or -percent

Question: will integer + or - percent yield an integer result when possible, or always a float result? The formulation of the wish seems to indicate that an integer result (if possible) is preferred.

**Comment by WiseGenius** [comment]
IMHO, the current behaviour makes sense, but the suggested behaviour is ambiguous and belongs in a separate dialect.

**Comment by meijeru** [comment]
Surely it can be defined perfectly unambiguously! All operations must be defined for all combinations of types of left and right operand. The problem is not ambiguity, but desirability.

**Comment by SmackMacDougal** [comment]
The proposed new result would go against mathematics and expectations of almost anyone versed in mathematics. 

@ifgem seems to need simple interest, aka compound growth, where t=1. 

```
growth: func [n [number!] p [percent!]][(n * p) + n]
decline:  func [n [number!] p [percent!]][n - (n * p)]
```

or combined:

```
incr: 	func [
	n [number!] p [percent!]
	/growth /decline
][
	any [if growth [(n * p) + n]if decline [n - (n * p)]]
]
```

The guy is looking for a new operator, something like *+.

In his example, 90% is really -10%, (90% -100%), so the growth from above works in both cases:

red>> growth 100 10%
== 110.0
red>> growth 100 -10%
== 90.0

**Comment by meijeru** [comment]
The evaluation rules of Red (and Rebol) already go against mathematics: `1 + 2 * 3 => 9` instead of `=> 7`. Thus `100 + 10% => 110` would not be öut of character". Only, it has to be well-defined and well explained.

**Comment by SmackMacDougal** [comment]
```
>> ;; not violated
>> 1 + (2 * 3)
== 7
>> ;; good luck
```

Carl made a few mistakes with REBOL. One of which is order precedence in evaluation of math using op! Another is his wrong definition of difference. 

```
>> Soccer: [Alex Case Drew Hunter]
== [Alex Case Drew Hunter]

>> Tennis: [Case Drew Jade]
== [Case Drew Jade]

>> difference Soccer Tennis
== [Alex Hunter Jade]

>> exclude soccer tennis
== [Alex Hunter]
```

But what Carl really defined is an outer join for difference:

>> venn/outer? soccer tennis
== [Alex Hunter Jade]

```
    outer?: func [
        "outside the intersection" 
        s1 [series! bitset!] "set one" 
        s2 [series! bitset!] "set two"
    ][
        sort difference s1 s2
    ]
```

What Carl called `exclude` is what mathematicians call difference in set mathematics:

```
>> venn/difference? soccer tennis
== [Alex Hunter]
```

```
    difference?: func [
        "in first set but not in second set"
        s1 [series! bitset!] "set one"
        s2 [series! bitset!] "set two"
    ][
        sort exclude s1 s2
    ]    
```

**In mathematics, for subtraction, a subtrahend is subtracted from a minuend to find a difference.**

Nenad should fix these things in RED even if it breaks anyone's old REBOL code.

What has been proposed by you only adds to confusion.  What you have described in your original post is the result for the formula for simple interest compounded at one year.

```
Comment {
A = P (1 + r/n) ^ nt
A = the future value of the investment/loan, including interest
P = the principal investment amount (the initial deposit or loan amount)
r = the annual interest rate (decimal)
n = the number of times that interest is compounded per year
t = the number of years the money is invested or borrowed for
}

ci: func [
 p [number!] 
 r [percent!]
 t [integer!]
 n [integer!]
][
	power (p * (1 + r / 1)) (n * t)
] 
```

```
red>> ci 100 10% 1 1 
== 110.0
red>> ci 100 -10% 1 1 
== 90.0
```

Good luck!

**Comment by meijeru** [comment]
You are quite right: 

    >> 1 + (2 * 3)
    == 7

But that is not what I wrote, I left out the parentheses, and that is where the difference lies!

**Comment by SmackMacDougal** [comment]
But REBOL internally does not go against mathematics. What has been proposed by @ifgem goes against mathematics.

1% is a number that means 1 out of 100.  10% is ten times that. 

To convert a percent to a decimal, one divides the percent number by 100 which results in a quotient.

`100 + (10 / 100) = 100 + .1 = 100.1 ≠ 110`

What @ifgem seeks is a function for compound interest. Now, RED might be made better if it had all of the financial formulas one would find in EXCEL or GOOGLE Spreadsheet as included native functions, but of course a user can code those himself.

**Comment by SmackMacDougal** [comment]
The bigger problem is this works in REBOL but not RED:

**REBOL**
```

>> 100 - (90 / 100)
== 99.1
>> 100 + (10 / 100)
== 100.1

```

**RED**

```
red>> 100 - (90 / 100)
== 100
red>> 100 + (10 / 100)
== 100
```

More glitches in **RED**

```
red>> 100 - 90 / 100
== 0
red>> 10 / 100
== 0

```

Works in *REBOL*
```

>> 100 - 90 / 100
== 0.1
>> 10 / 100
== 0.1
```

**Comment by 9214** [comment]
I find the proposed behavior to be more useful, but it needs deeper research and some design mockup.

**Comment by greggirwin** [comment]
It seems like a nice idea, but even spreadsheets don't do this automatically. If we do, how do you work around it? We can also view adding non-like types as an error, but there is a valid way to view percents, which is what Red currently does. This request relates to _incrementing_ a value, which we can do with an `incr` func (don't go into `++ op!` territory though :^) or examples of how do to percentage calculations. It can also be part of a dialect as @WiseGenius suggests.
