### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by SmackMacDougal** [red/red#2174]
REBOL 2.7.8.3.1 vs RED 0.6.1

**REBOL**
```

>> 100 - (90 / 100)
== 99.1
>> 100 + (10 / 100)
== 100.1
```

**RED**

```
red>> 100 - (90 / 100)
== 100
red>> 100 + (10 / 100)
== 100
```

More glitches in **RED**

```
red>> 100 - 90 / 100
== 0
red>> 10 / 100
== 0
red>> divide 10 100
== 0
```

Works in *REBOL*
```

>> 100 - 90 / 100
== 0.1
>> 10 / 100
== 0.1
>> divide 10 100
== 0.1
```

And more inexplicable results in **RED**:

```
;; OK
red>> to float! 10
== 10.0

;; BUT
red>> to float! 10 / 100
== 0.0
red>> to float! (10 / 100)
== 0.0
```

**REBOL** works!

```
>> to decimal! 10
== 10.0
>> to-decimal 10 /  100
== 0.1
>> to decimal! 10 / 100
== 0.1
```

**Comment by meijeru** [comment]
As far as I understand, all of these are not quirks but consequences of a single design decision: `/` as division on two integers yields an integer hence truncation occurs.

Try `(to float 10) / 100` to obtain a `float!` result.

**Comment by SmackMacDougal** [comment]
Well, that decision is stupidity expressed. Few will recall every time something akin to this:

> I need to convert either my dividend or my divisor to a float before applying the divisor to the dividend to get a quotient. 

So Nenad needs to fix that straight away. It is those kinds of design flaws that hindered REBOL. Why does Nenad want to double up on such stupidity?

```
; OK
red>> 6 / 3
== 2
red>> 3 / 3 
== 1
```

```
; BUT is an error in mathematics
red>> 2 / 3
== 0
```

**Doing this reveals an inherent design flaw**

```
red>> (to float! 2) / 3
== 0.6666666666666666
```

In *REBOL*

```
>> 2 / 3
== 0.666666666666667
```

No surprises! REBOL is right. Nenad and his team are wrong with this decision, stupidly so.

**Comment by SmackMacDougal** [comment]
Closed? Why? The issue has not been addressed.

**Comment by PeterWAWood** [comment]
The implementations of neither ```/``` or ```to``` are complete. Their behaviour will be the same as Rebol once they are finalised.
