### ISSUE TITLE
In the interpreter, pick b 1 and b/1 are not equivalent if b/1 is a function 

### ISSUE THREAD

**Issue by meijeru** [red/red#2175]
Note: I have not tested this in the compiler.
```
red>> f: func [x][print x]
== func [x][print x]
red>> b: reduce [:f]
== [func [x][print x]]
red>> type? pick b 1
== function!
red>> type? b/1
*** Script Error: 1 is missing its x argument
*** Where: type?
```

It looks like `pick` does a `get` and `eval-path` does not. Moreover, the error message is not entirely helpful.

**Comment by greggirwin** [comment]
The behavior is by design (otherwise you would have to `do` every path), but maybe the error message could include the path info to make it nicer. R2 works the same way.

**Comment by meijeru** [comment]
(1) This merits some documentation, I think (2) The error message should mention the function rather than the path, if possible

**Comment by dockimbel** [comment]
Paths evaluate their referenced value, otherwise you wouldn't be able to use refinements on functions and expect the function to still be called (e.g. `append/only`).

The error message has been fixed to refer to the path value.
