### ISSUE TITLE
Function `new-line?` always returns `true`

### ISSUE THREAD

**Issue by rgchris** [red/red#2177]
```rebol
probe new-line? [
    foo
]

probe new-line? [foo]
```

Results in:

```
true
true
```

Expected:

```
true
false
```

**Comment by rgchris** [comment]
Was reviewing Red behaviour compared to Rebol per: http://stackoverflow.com/a/28082933/292969

**Comment by greggirwin** [comment]
An empty block always returns false, even if it has new-line markers in it. Or, rather, they are removed if the block is empty.
```
red>> b: [
[    
[    
[    ]
== []
red>> new-line?  b
== false
red>> b
== []
```
