### ISSUE TITLE
CRASH: Directly DOing a native or action you GET

### ISSUE THREAD

**Issue by greggirwin** [red/red#2192]
Tested in GUI console.

```
>> word: "AbcD"
== "AbcD"
>> do get random/only [ lowercase uppercase ] word
<<interpreter console vanishes>>
```

`do get 'sign? 1`
`do get 'add 1 2`

Seems fine if you use an intermediate word to hold the function value.

**Comment by dockimbel** [comment]
If your provide a proper block to `do` including the required argument, it will work fine:
```
do reduce [get random/only [ lowercase uppercase ] word]
== "abcd"
```

**Comment by dockimbel** [comment]
Now the interpreter will not support variable-arity DO anymore (unlike R2/R3).
