### ISSUE TITLE
Phantom map! keys

### ISSUE THREAD

**Issue by WiseGenius** [red/red#2196]
Any `integer!` keys after the 64th to be added to a `map!` hang around after being removed.

```
red>> m: #()
== #()
red>> repeat k 70 [
[        m/:k: {x}
[        m/:k: none
[    ]
== none
red>> m
== #()
red>> keys-of m
== [65 66 67 68 69 70]
red>> m/65
== none
```

**Comment by greggirwin** [comment]
Looks like the fix from 02-sep-2016 regressed. A number of changes in `reflect` exist.  Once fixed, let's make sure we have tests for this. 

Good catch.
