### ISSUE TITLE
Odd make hash!, map! behavior.

### ISSUE THREAD

**Issue by ifgem** [red/red#2204]
#2203 #2202

hash!

```
make hash! [%] => make hash! [%""]
make hash! [% %] => make hash! [% %""]
make hash! [10x] => make hash! [10 x]
make hash! [10h-1] => make hash! [16 -1] ; don't know if it's a bug.
```

map!

```
make map! [@ 10] make map! [% 10] => why @,% aren't word!

make map! [10x] => %(10 x)
make map! [%]
*** Script Error: invalid argument: [%""]
*** Where: make
test: make map! [% %] => #(%: %"")
; But it can't be used:
test/%
*** Syntax Error: invalid path! at "h/%"
*** Where: do
; and so
select #(% %) '%
```

**Comment by qtxie** [comment]
Those are lexer issue, rather than `hash!` and `map` issue.

**Comment by dockimbel** [comment]
Those are indeed lexer issues and not related to map or hash. Given that the aforementioned related tickets have been fixed, it now behaves as it should:
```
>> [%]
== [%]
>> [% %]
== [% %]
>> [10x]
*** Syntax Error: invalid pair! at "10x]"
*** Where: do
*** Stack: load 
>> [10h-1]
*** Syntax Error: invalid integer! at "10h-1]"
*** Where: do
*** Stack: load 
```

> make map! [@ 10] make map! [% 10] => why @,% aren't word!

`%` is allowed to be used as a standalone word, as Red/System relies on it for modulo operator. `@` denotes an email only for now.

> test: make map! [% %] => #(%: %"")
> ; But it can't be used:
> test/%
> *** Syntax Error: invalid path! at "h/%"
> *** Where: do
> ; and so
> select #(% %) '%

Literal paths don't support all literal values that can be used as keys in maps (like `char!` and `string!`). `select` can be used in such cases:
```
>> select #(% %) '%
== %
```
