### ISSUE TITLE
Invalid parsing of email!

### ISSUE THREAD

**Issue by ifgem** [red/red#2206]
```
@ => @
@@@@ => @
@10 => @10
10x10@
-10.0@
%@ => %25@
%1@ => %251@
type? %300@ => email!
%300@ => 00@
%400@ => @0@
...
```

**Comment by dockimbel** [comment]
`%xx` is used in all datatypes inheriting from string (but not `string!`) to represent the encoding of an ASCII character in hexadecimal format. If `%` is not followed by two hex characters, a syntax error should be raised. If the format is correct and if they represent a *displayable* character, then they are decoded in the resulting type. (Same as in Rebol)

A fix has been provided for the cases where the `%xx` format is not correct in the input.

For the isolated `@` and `@@@@` (which loads as `@ @ @ @`), they are left as-is until we implement the rules for the upcoming `ref!` datatype.
