### ISSUE TITLE
? gives more information on a map and its components than on a map component individually.

### ISSUE THREAD

**Issue by meijeru** [red/red#2215]
When exploring `system/codecs` using `?` I found that `? system/codecs` lists all components of the map including the bodies of the routines `system/codecs/png/encode` and `.../decode` (idem for `.../jpeg/...` etc.), whereas `? system/codecs/png` does NOT give the bodies of the routines. This lacks consistency.

**Comment by greggirwin** [comment]
`Help` has a check for objects right now, but `map!` isn't part of that check. Easy to add, though `help` is probably going to get a rewrite at some point. Good to note for that.

**Comment by Oldes** [comment]
I don't think this is an issue... when you do `? system/codecs`, it is like doing: `probe system/codecs` so you see everything, while `? system/codecs/png` displays key/value of the `png` object. The output is limited by design else you could not browse large object easily...

Also `system/codecs` is a `block!`, so help system don't see it as a key/values like with object.

You can test it yourself: `? system` versus `probe system`.

**Comment by Oldes** [comment]
Or what is your proposition?

**Comment by geekyi** [comment]
@Oldes 
> Also system/codecs is a block!, so help system don't see it as a key/values like with object.

I think the wish here is to show more summarized info for `help block!` (specifically, nested blocks) just as for other composite datatypes like `object!`

**Comment by greggirwin** [comment]
Right now there's no special check for blocks. The `value-is-type-str` internal func is called and it uses `mold` directly. It would be easy to change that to use `form-value`, which will make things more consistent. The tradeoff is that the output is intentionally limited, as with help on objects. We may want to change the format for maps in that case, as it only returns the keys right now, which matches objects. Where blocks get `length: n` metadata in the output, we could include "keys:" for both objects and maps, to make it clear that you aren't inspecting the values as well.

I can mock up some different outputs to see what looks most helpful.
