### ISSUE TITLE
Make image! pair! with both float! returns float!

### ISSUE THREAD

**Issue by ifgem** [red/red#2220]
`make image! 100.1x100` works as expected but:

```
make image! 100.0x100.0 => 0.0
make image! 100.0x100.1 => 0.1
make image! 100.1x100.0 => 0.0
```

**Comment by greggirwin** [comment]
There is another ticket, which I can't find right now, that covers the pair parsing with floats, and there was chat on gitter as well. You still get a good image result in this case. Once pair! lexing is completely defined and implemented, this will be fixed. For now, this shows the behavior:
```
red>> [1.1x2.3]
== [1x2 0.3]
```

**Comment by dockimbel** [comment]
Pairs cannot contain float values yet, the lexer has some provision for supporting that in the future, that's why it is not reporting any error for now.
