### ISSUE TITLE
Refinement /case on REPLACE

### ISSUE THREAD

**Issue by Rebol2Red** [red/red#2228]
As implemented on Rebol

**Comment by 9214** [comment]
That one seems to be fulfilled.
```red
>> replace/all/case [a b B c] 'b 'x
== [a x B c]
```

**Comment by meijeru** [comment]
This should be marked `status.built` and closed, then. There might be others of the same kind. @9214, you are apparently reviewing quite a lot of issues, I would hope you have the authority to close those that can be closed, since they contribute to reducing the (apparent) backlog...
