### ISSUE TITLE
Inconsistent trigonometry with 1.#inf

### ISSUE THREAD

**Issue by dsunanda** [red/red#2244]
sin 1.#inf      ==> 1.#NaN
arcsine 1.#inf  ==> "math or number overflow"
tan 1.#inf      ==> 1.#NaN
arctangent 1.#inf ==> 90.0

Would expect 1.#NaN for the ARCSINE.

No sure best behavior for ARCTANGENT. Technically, 90.0 is right -- but only for certain values of infinity.

**Comment by geekyi** [comment]
Maybe related: #2000

You may also be interested in *REP XXXX Add mathematical and time functions* in the wiki

**Comment by qtxie** [comment]
Technically, `sin 1.#inf` should return a range `[-1, 1]`, `arcsine 1.#inf` should return a complex number `(-i)∞`.
As we granted wish #2000, for consistency, I think we should also return `1.#NaN` for `arcsine 1.#inf`.

**Comment by dockimbel** [comment]
@qtxie Agreed.
