### ISSUE TITLE
`read/info <url>` throws Access Error: invalid UTF-8 encoding

### ISSUE THREAD

**Issue by wolframkriesing** [red/red#2259]
``` red
red>> read/info http://news.ycombinator.com
*** Access Error: invalid UTF-8 encoding: #{8C5CA0E0}
*** Where: read
```

Just stabbing in the dark: it looks like the redirect that takes place is confusing the `read` command.

**Comment by geekyi** [comment]
I'm not seeing this error with ycombinator (but the page is not redirecting for me)

With google, it is a known problem:
```
read/info http://www.google.com
*** Access Error: invalid UTF-8 encoding: #{A050726F}
*** Where: read
```
Can you test with http://httpbin.org/ and see if you can narrow it down?

**Comment by geekyi** [comment]
I'm not seeing this error with ycombinator (but the page is not redirecting for me)

With google, it is a known problem:
```
read/info http://www.google.com
*** Access Error: invalid UTF-8 encoding: #{A050726F}
*** Where: read
```
Can you test with http://httpbin.org/ and see if you can narrow it down?

**Comment by wolframkriesing** [comment]
@geekyi this looks good
```
red>> read http://httpbin.org/
== {<!DOCTYPE html>^/<html>^/<head>^/  <meta http-equiv='content-type' va
```

**Comment by geekyi** [comment]
@wolframkriesing strange.. works for me with the most recent build (007b5c3) and one from several days ago (sept 24) on windows 10 anniversary edition. Anything like proxies?
```
red>> read/info http://bitly.com/
== [200 #(
    Cache-Control: "no-cache, no-store, max-age=0, must...
red>> read/info https://bitly.com/
== [200 #(
    Cache-Control: "no-cache, no-store, max-age=0, must...
red>> system/platform
== Windows
```

**Comment by wolframkriesing** [comment]
just did a 
- `git pull` on master and I am on 4fb928aa06 now
- then in rebol I recompiled with `do/args %red.r "%environment/console/console.red"`
- and started red like so `> ./console`
Is that correct so far, to run red from source? (not done that too often yet :))
And result has not changed yet :(

```red
red>> read/info http://bitly.com/
*** Access Error: invalid UTF-8 encoding: #{BC4202F0}
*** Where: read
```

I am on Mac OS X 10.10.5

**Comment by dockimbel** [comment]
Those cases are working fine with latest commit.
