### ISSUE TITLE
Opening ~20 MB file crashes Red under OSX

### ISSUE THREAD

**Issue by rebolek** [red/red#2260]
I have [this file](http://www.qyz.cz/red/messages.red) that is full of messages from Gitter’s Red/Red channel. I am able to load it under W7, but under OSX, I got `*** Runtime Error 1: access violation`.

**Comment by qtxie** [comment]
It works fine on my Mac OSX 10.9 VM.

But it consumes a bit more than 500MB memory on both platforms. :astonished:

**Comment by rebolek** [comment]
I can confirm that it’s possible to load the file now. Must have been fixed with some commit in the last month. Yes, it takes lot of memory, it’s a LOT of `map!`s 😈
