### ISSUE TITLE
WISH: round should be allowed on pairs

### ISSUE THREAD

**Issue by meijeru** [red/red#2264]
I am writing a drawing program and to implement "snap to grid" I need to resort to the cumbersome

```
snapped-point: as-pair round/to point/x grid-size round/to point/y grid-size
```

where I would have liked to write

```
snapped-point: round/to point grid-size
```

**Comment by dockimbel** [comment]
Pair! only holds integer values for now, so applying `round` on a pair value would have no effect.

**Comment by meijeru** [comment]
But `round/to` definetely *would* have, and this is what the example is about. I believe this to be a realistic example.

**Comment by dockimbel** [comment]
Indeed, I overlooked it.
