### ISSUE TITLE
system/view/screens/1/size reports wrong size

### ISSUE THREAD

**Issue by meijeru** [red/red#2267]
My screen size as reported by Windows 10 is 1920*1080, but Red says
```
red>> system/view/screens/1/size
== 1536x864
```

It is perhaps significant that Red's values are 20 % off.

**Comment by iArnold** [comment]
For what it is worth. My Macbook has 1280x800 and Red says it is:
red>> system/view/screens/1/size
== 1280x778

**Comment by DideC** [comment]
@meijeru If you set the font zoom to 100% (usually at 120% or 150% in this kind of resolution), does it change the screen size value in Red ?

**Comment by iArnold** [comment]
Win7 reports 1920x1080, so okay, but where is my second screen?

**Comment by geekyi** [comment]
Okay, after doing what @DideC suggested (Right-click desktop -> display settings, "change size of text , apps ..") to 125% (Recommended) I get after reopening the gui console:
```
red>> system/view/screens/1/size
== 1536x864
```
This seems to exactly match what @meijeru is seeing, so we can probably close this?

**Comment by meijeru** [comment]
Thanks everyone. For me the case is indeed closed.

**Comment by greggirwin** [comment]
As with Arnold, no info on extra monitors here.
