### ISSUE TITLE
VID does not handle "blockable" font! (or para!) field reliably

### ISSUE THREAD

**Issue by DideC** [red/red#2269]
In `font!` object, only `/style` field can be `none!`, a `word!` or a `block!`.
But the `system/view/VID/add-flag` function that handle the `word!` to `block!` transformation, does it for any field of the object it manipulate.
So unexpected results can occurs:

```
view [
    below
    text "Font default"
    text "Font 18" font-size 18
    text "Font 36" font-size 36
    f-t: text "Font 8, 18 and 36" font-size 8 font-size 18 font-size 24
   do [? f-t/font]
]
```

Even if it's not a "correct VID code", it is valid and does not produce errors.
`para!` object could also be affected.

**Comment by dockimbel** [comment]
@DideC Well done!

**Comment by DideC** [comment]
Thanks. Not too hard aniway ;-)
