### ISSUE TITLE
Red/system Compiler Internal Error

### ISSUE THREAD

**Issue by TimeSlip** [red/red#2271]
Compiling to native code...
**\* Red/System Compiler Internal Error: Script Error : decorate-fun expected name argument of type: word
**\* Where: comp-expression
**\* Near:  [decorate-fun expr/1]

I'm getting this when I attempt to compile a .red file which is #including another .red file that itself has an r/s #system #import.

The r/s app compile fine by itself and also compiles fine with a simple view gui.
The larger app, runs fine in the cli, and w/o the r/s code it compiles fine. Only when I add both does it error out.
I've tried using the -u parameter and the same error occurs.
Thank you.

**Comment by dockimbel** [comment]
Thanks for the report, but if you don't provide a code example that triggers the error, this is very little we can do about it.

**Comment by TimeSlip** [comment]
Yes, I'm trying to create something that is not the entire app Doc. The fact that no one else is reporting this to me means that it is user error which doesn't surprise me all that much.
Thanks,
James_Nak

**Comment by TimeSlip** [comment]
OK, as far as I can tell, the error was caused because I used the following in my script (Which I do often in Rebol). This saves me time when I later encap things.

compile: true
either compile [
	

		#include %/o/marcus.png.red
		#include %/l/jamesjeo.red
		#include %/l/jamesmarkjeo.red
		#include %/o/jeopardysound.red  
][


	do %/l/marcus.png.red
	do %/l/jamesjeo.red
	do %/l/jamesmarkjeo.red
]

**Comment by TimeSlip** [comment]
BTW, the file locations, are not the problem because I keep copies of the png data in both places.

**Comment by dockimbel** [comment]
@TimeSlip I need a way to reproduce the issue, the above code pattern compiles fine.

**Comment by dockimbel** [comment]
Without a way to reproduce the issue, we cannot process it.
