### ISSUE TITLE
Add conversion between different types of words

### ISSUE THREAD

**Issue by maximvl** [red/red#2275]
So, right now `to` doesn't support `word!` as an argument:

```
red>> to string! 'a
*** Script Error: to does not allow word! for its type argument
*** Where: to
```

It should be able to convert `word!` at least to `set-word!`, `get-word!`, `lit-word!` and `string!`
Strings conversion also doesn't work for `get-word!`:

```
red>> to get-word! "a"
*** Script Error: TO cannot convert get-word! from: a
*** Where: to
```

**Comment by qtxie** [comment]
It implemented now.
