### ISSUE TITLE
to word! to string! on a file value loses the series pointer

### ISSUE THREAD

**Issue by meijeru** [red/red#2276]
Use case: in order to know what code to use in `save/as <file> <encoding>` I wish to retrieve the file extension as a word! value (e.g. `%filename.png => 'png`). Now `to word!` on a file value is not allowed. Thus one needs to chain `to word!` and `to string!`. But if the file value is the result of `find` and thus the series pointer is not at the head, this fact is lost!

```
red>> save-file: %abc.def
== %abc.def
red>> ext: next find/last save-file %.
== %def
red>> to string! ext
== "def"
red>> to word! to string! ext
== abc.def
red>> to word! "def"
== def
```

**Comment by meijeru** [comment]
The problem is even simpler to locate, without using file values
```
red>> to word! next "abcdef"
== abcdef ; should be bcdef !!
```

**Comment by qtxie** [comment]
Fixed in the latest version.
