### ISSUE TITLE
Non-bold text in draw does not appear when saved to an image file

### ISSUE THREAD

**Issue by meijeru** [red/red#2283]
I have a base face with a draw block that contains text in non-bold style. When I invoke `draw` on the draw block of the face, in order to create a value of type image! and I save this image as a .jpg file using `save/as`, the text is lost. It does appear when the font is bold. I have not been able to determine whether the loss occurs in invoking `draw` or when saving (calling the codec).

**Comment by qtxie** [comment]
Would you please provide the steps to reproduce the issue ? 

I try this one and it works fine.
```
save/as %draw-text.jpg draw 100x50 [text 10x10 "Hello"] 'jpeg
```

**Comment by meijeru** [comment]
The default font used in the above example is bold(er). If you create a non-bold font, it becomes invisible.
```
    text-font: make font! [size: 12]
    save/as %draw-text.jpg draw 100x50 [font text-font text 10x10 "Hello"] 'jpeg
```

**Comment by qtxie** [comment]
@meijeru It works fine on my Win 7 64bit box. Which OS version are you using?

**Comment by meijeru** [comment]
I am using Windows 10. Does the `make font! [size: 12]` make the trouble or did you use my example literally?

**Comment by qtxie** [comment]
Comfirmed it on Windows 10.  When give the font a name, then it works.
