### ISSUE TITLE
Control characters in a text-field are not translated

### ISSUE THREAD

**Issue by meijeru** [red/red#2289]
I put a text containing `^/` (newline) in a text field and checked the contents by printing `to binary!` of these contents. There is no translation to a control character, it is stored as `#{5E2F}` instead of `#{0A}`. Same for `^-` (tab) and `^@` to `^_`. Is this a limitation of View, or of the underlying OS?

**Comment by qtxie** [comment]
The text field and area are general edit widget. It treats its contents as plain text, no language awareness.
