### ISSUE TITLE
Draw dialect - Image key color error

### ISSUE THREAD

**Issue by Rebol2Red** [red/red#2299]
view [base 400x400 transparent draw [image picture 0x0 100x0 0x100 100x100 255.255.255]]

*** Script Error: invalid Draw dialect input at: [picture 0x0 100x0 0x100 100x100 255.255.255]
*** Where: ???

**Comment by meijeru** [comment]
I read in the [documentation](https://doc.red-lang.org/gui/Draw.html#image):
```
Four points mode is not yet implemented.
It will allow to stretch the image using 4 arbitrary-positioned edges.
```

**Comment by Rebol2Red** [comment]
I  read

<image>        : image to display (image! word!).
<top-left>     : (optional) coordinate of top left edge of the image (pair!).
<top-right>    : (optional) coordinate of top right edge of the image (pair!).
<bottom-left>  : (optional) coordinate of bottom left edge of the image (pair!).
<bottom-right> : (optional) coordinate of bottom right edge of the
image (pair!).
<color>        : (optional) key color to be made transparent (tuple! word!).

OPTIONAL,  to set the transparent color should work (image 0x100
240.240.240)
I don't want to stretch the image, but want transparent color
Again a case of not being implemented yet.

2016-11-03 20:25 GMT+01:00 Rudolf Meijer <notifications@github.com>:

**Comment by Rebol2Red** [comment]
@qtxie, It works now, Thank you very much for fixing this!
