### ISSUE TITLE
FUNCTION leaks LOCAL

### ISSUE THREAD

**Issue by rebolek** [red/red#2301]
I had my suspicion, so I tested it and yes:

```
red>> f: function [][local: "leak"]
== func [][local: "leak"]
red>> f
== "leak"
red>> local
== "leak"
```

**Comment by dockimbel** [comment]
Setting `local` word in the body is not allowed when using `function` constructor in the compiler. Now the interpreter implements the same rule, so the above code would trigger an error now.
