### ISSUE TITLE
macro error: parse rule works differently inside of macro

### ISSUE THREAD

**Issue by JacobGood1** [red/red#2305]
The following code works fine outside of a macro:
```
parse mold [there] rule: [
    copy code-captured-b4-newline thru [newline | "]"] (load code-captured-b4-newline) rule
    | end
]

when placed in a macro like so:

expand-directives [
    #macro ~>: func [data code] [
        parse mold code rule: [  
            copy code-captured-b4-newline thru [newline | "]"] (load code-captured-b4-newline) rule
            | end
        ] 
    ]
    ~> hi [there]
]
```
The following error is produced:
*** Script Error: PARSE - matching by datatype not supported for any-string! input
*** Where: parse

This error does not exist when parsing outside of the macro.
The macro uses load, could this be the issue?

**Comment by dockimbel** [comment]
The bug is caused by an unbalance Parse rules stack saving/restoring.
