### ISSUE TITLE
[macOS] OVER events are send to not only the top face but also the face under the top face.

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2307]
Try the following code.
```Red
view [ at 10x10 base 100x100 red all-over on-over [ face/color: random white] at 60x60 base 50x50 all-over on-over [ face/color: random white 'done] ]
```
When the mouse cursor is in the small square, the big square still got the OVER events.

**Comment by qtxie** [comment]
I think it's the right behaviour as the two base faces are siblings and they are overlapped.

Returning `done` will stop sending the event to it's **parent**, rather than it's siblings.
