### ISSUE TITLE
WISH: Complemented charset should work in FIND

### ISSUE THREAD

**Issue by endo64** [red/red#2308]
`FIND` behaves differently on Red than Rebol 2/3

```
>> find #{0000000016180300} complement charset "^@"
== #{0000000016180300}  ;in Red
== #{16180300}          ;in Rebol 2 & 3

red>> find #{0102030405} complement charset "^C"
== #{030405}
```

It looks like `FIND` ignores `complement`.

**Comment by dockimbel** [comment]
Fixed by commit [44d4a54f](https://github.com/red/red/commit/3fa9566cb57623d5838553017e846ea044d4a54f).
