### ISSUE TITLE
drop-list crashes after unview

### ISSUE THREAD

**Issue by Rebol2Red** [red/red#2314]
view [
    drop-list data ["Dutch" "English"][x: face/selected unview]
]
; program stops right here, because of an unview related issue
print x ; <- no value shows up

**Comment by qtxie** [comment]
@Rebol2Red Which version of Windows are you using? It works fine on my Win 7 64bit.

**Comment by Rebol2Red** [comment]
Windows 10 64 bits Red 20-11-2016

Have you tried selecting the first item and THEN  the second item?
When you select the first it gives 1 after the second selecting nothing shows up and
after restarting the script nothing shows up anymore.

**Comment by geekyi** [comment]
Heisenbug detected! Initially was crashing.. I don't know what I did to make it not crash
