### ISSUE TITLE
Add x86_64 to Cross-compilation targets that already support x86

### ISSUE THREAD

**Issue by moscati** [red/red#2319]

**Comment by dockimbel** [comment]
We don't have yet support for 64-bit targets, therefore we cannot "add" something that does not exist.

**Comment by moscati** [comment]
If you had, you would need to add. Anyway I wanted to help in implementing 64-bit targets but I understand I need Rebol SDK for the red build process and I can't get it

**Comment by dockimbel** [comment]
Implementing 64-bit support is not something doable by a newcomer, you need a deep understanding of the Red codebase, the Red language and its implementation, the Red/System language and the Red toolchain (not mentioning deep awareness of 32 vs 64-bit intricacies). If you want to help, you might want first to gain knowledge about all that before diving into deep and complex topics like 64-bit support. You can start with tickets marked with "contribution" tag here that are recommended for first code incursions.

You don't need Rebol SDK nor do you need to build a Red executable. The build process is just a convenient way to deliver the Red toolchain to regular users, it is not needed to run Red from sources. See "Running Red from the sources" section in [README](https://github.com/red/red/blob/master/README.md).
