### ISSUE TITLE
integer: pair/x: <number> results in corrupted pair!

### ISSUE THREAD

**Issue by rebolek** [red/red#2320]
```
red>> p: 0x0
== 0x0
red>> a: p/x: 0
== 0
red>> p
== 454x0
```

**Comment by qtxie** [comment]
It's an issue about multiple assignment: `a: p/x: 0`.

This works:
```
p: 0x0
p/x: 0
p
== 0x0
```

**Comment by rebolek** [comment]
Yes, I should have been more verbose with my description ;)

**Comment by dockimbel** [comment]
It's a duplicate ticket, there are 2 or 3 issues related to that bug already.
