### ISSUE TITLE
make/to string! <block> is not compatible with make/to block! <string>

### ISSUE THREAD

**Issue by meijeru** [red/red#2333]
`to block! "1   2" == [1 2]` but `to string! [1   2] == "12"` whereas `form [1   2] == "1   2"` and `make/to string! is in many cases defined in terms of `form`. I plead for conserving the spaces, in spite of incompatibility with R2/R3. Reason: round trip conservation.

**Comment by qtxie** [comment]
How about this TO conversion?
```
to tuple! [1 2 3]                == 1.2.3
to block! 1.2.3                  == [1.2.3]

to pair! [1 2]                     == 1x2
to block! 1x2                    == [1x2]
```

**Comment by meijeru** [comment]
Actually, the table says: `to string! [1 2]` should be `form [1 2]` and this is `"1 2"` with spaces preserved. Therefore, the current implementation of `to string! [1 2]` as `"12"` is even wrong, or at least incompatible with the specification in the table!

**Comment by dockimbel** [comment]
Red is correct in doing `to string! [1 2] == "12"`. The block (or any-list!) represents a list of constituting elements for the target datatype, concatenating them to each other to create the new datatype. The documentation is wrong by describing it as "FORM list", it should be "Concatenate each FORMed value".
