### ISSUE TITLE
Can't set word to literal integer using the single quote character

### ISSUE THREAD

**Issue by asampal** [red/red#2336]
```red
red>> foo: '3
*** Syntax Error: invalid value at "'3"
*** Where: do
red>> foo: quote 3
== 3
red>>
```

**Comment by asampal** [comment]
If there is not such thing as literal integers in Red, should `foo: quote 4` not also error? Again, why not allow quoting of integers (as seems possible using `quote`) using the single quote character?

**Comment by DideC** [comment]
Per the [Rebol documentation](http://www.rebol.com/r3/docs/datatypes/word.html#section-4), Word! can not begin by a digit.
So `'3` or `2paper` could not be valid word!

The question of `quote` behaviour is less obvious. Need Doc's answer there.

**Comment by asampal** [comment]
As I was suggesting in #2337, it might not be a bad idea to allow integers to be quoted, although they are already literals. The rule for words not beginning with digits could still hold even with this small change.

**Comment by dockimbel** [comment]
@asampal
> why not allow quoting of integers

Why should we allow it?
What does "quoting an integer" mean?
What is the difference between a quoted integer and an unquoted one?
What should `load "'1"` return? If it returns `1`, then why do we need it for? If it's not `1`, then we need a new datatype to represent it (*homoiconicity* requires it). How would you justify such datatype existence? What semantic rules would apply to it?

For `quote`, have a look at its source code:
```
red>> source quote
quote: func [
    :value
][
    :value
]
```
Why do you want `quote` to error out on integers? That would go against the basic semantics of the language.

Quoting integers makes as much sense as quoting lit-words (`''foo`)

**Comment by asampal** [comment]
In the referenced other issue, I mentioned why you might want to allow such character sequences, which is for the case when a sequence of characters is assembled blindly by one piece of code for use somewhere else without attempting to do any kind of validation at the source. In order to be safe under certain auto-evaluation cases, prefixing a sequence of characters with ' should be possible and cause no harm other than making the result not evaluate at certain caller sites. 

Of course a `load "'"1 should return `1` and should not require a new datatype.

**Comment by meijeru** [comment]
If I may add to doc's explanation, the quote sign `'` is syntactic sugar for `quote` *only* in the case of a `word!` or `path!` literal. So your blindly assembling piece of code would be safer to prefix all values with `quote`, since that is syntacttically valid for all values and has the deseired semantics.

**Comment by dockimbel** [comment]
@asampal How do *In the referenced other issue, I mentioned why you might want to allow such character sequences, which is for the case when a sequence of characters is assembled blindly by one piece of code for use somewhere else without attempting to do any kind of validation at the source.* and the example code you refer to relate? The example code you provided:
```
red>> a: to-hash ['4 5 '6 7]
*** Syntax Error: missing #"]" at "sh ['4 5 '6 7]"
*** Where: do
```

**Comment by asampal** [comment]
Sorry, didn't mean to imply that the example provided was representative of the case I tried to describe.

**Comment by dockimbel** [comment]
Closing this ticket now. Please fill a [REP](https://github.com/red/red/wiki/Red-Enhancement-Proposal-Process) if you think such feature brings any value, just back it with sound arguments showing the benefits without breaking the syntactic and semantic rules of the language.
