### ISSUE TITLE
Can't create `hash!` with literal integer key, using single quote character

### ISSUE THREAD

**Issue by asampal** [red/red#2337]
```red
red>> a: to-hash ['4 5 '6 7]
*** Syntax Error: missing #"]" at "sh ['4 5 '6 7]"
*** Where: do
red>> a: to-hash ['foo 5 'foo 2]
== make hash! ['foo 5 'foo 2]
red>> a: make hash! ['4 5 '6 7]
*** Syntax Error: missing #"]" at "h! ['4 5 '6 7]"
*** Where: do
```

**Comment by dockimbel** [comment]
There is no such thing as `literal integer` in Red, nor Rebol2 or Rebol3.
```
red>> '4
*** Syntax Error: invalid value at "'4"
*** Where: do
````

**Comment by asampal** [comment]
Just curious why a literal integer shouldn't exist (despite seeming useless in a case such as above). If the block above was being composed from parts, wouldn't it make sense to allow `'4` just as `'foo` is allowed? It could just resolve to itself.

**Comment by DideC** [comment]
The problem of "literal integer" would be to distinguish them from integer! after loading time. They will lost the ticks so `'1` would be just `1`.
There are to be some limitations in a language. This one is in most computer languages I know of.

The problem of the key is not, as `integer!` could be key after all.

**Comment by dockimbel** [comment]
@asampal Integers are already "literals", like strings, chars, blocks, etc... Word! values are not literal, because they don't evaluate to themselves, but to the value they reference in the context they are bound to. Hence the need for a "lit-word!", to provide a literal word type, to be used as a symbol.

**Comment by asampal** [comment]
I'm aware that they are already literals, but consider that Red is assembling the keys blindly from some kind of source, in some multi-step fashion. This would be some kind of code/data creation context. There should be no harm in the quote character being prefixed to any characters that could form the key. Why not allow it for integers just as you do for non-integers? Does it create problems in some way?

**Comment by dockimbel** [comment]
See #2336 for more in-depth discussion.
