### ISSUE TITLE
make map! from object

### ISSUE THREAD

**Issue by meijeru** [red/red#2338]
Every valid object can be turned into a valid map. I cannot see problem.

**Comment by dockimbel** [comment]
Objects have binding, maps do not have. If you have:
```
obj: context [
	a: 123
	b: [a]
]
```
and make a map out of it, it will keep the binding to the object context, preventing it from being garbage-collected and probably confusing the user about what should `[a]` reduce to.

**Comment by meijeru** [comment]
Does the inverse problem not occur, e.g. with:
```
obj: make object! #(a: 123 b: [a])
```
What should the second `a` be bound to? BTW I tried to have this interpreted, but got an error, although the conversion matrix says it should be allowed.
