### ISSUE TITLE
Runtime crash on doing block!, paren! that include func's /local assigning

### ISSUE THREAD

**Issue by ifgem** [red/red#2346]
```
do compile
```
```
compile: func [/local _list_] [
	to block! [
		_list_: 10
	]
]
```
```
compile: func [/local _list_] [
	to paren! [
		_list_: 10
	]
]
```

**Comment by meijeru** [comment]
Have you tried changing the name of the function?

**Comment by dockimbel** [comment]
Functions in Red by default are not closures, so you need to rather use a `context` for that (until we implement the `closure!` type).

The above code should return an error instead of silently crashing.

**Comment by dockimbel** [comment]
Now you will get a proper `"word is not bound to a context"` error, because you are trying to evaluate a word bound to a function which has returned (no indefinite extent support yet).
