### ISSUE TITLE
Draw text is displayed without 1-2 last symbols

### ISSUE THREAD

**Issue by ifgem** [red/red#2347]
```
view [
	image draw [
		text 0x0 "123456789"
		text 0x30 "12"
		text 0x60 "123"
	]
]
```
[![Снимок1.png](https://s16.postimg.org/ahoydv6md/image.png)](https://postimg.org/image/ylfq25p35/)

**Comment by dockimbel** [comment]
Good finding!

**Comment by dockimbel** [comment]
@qtxie `status.built` should be used when code need fixing, and `status.resolved` for tickets solved without code fixing.
