### ISSUE TITLE
Event/key is none on CapsLock

### ISSUE THREAD

**Issue by ifgem** [red/red#2351]
```
view [
    area on-key [probe event/key]
]
```

**Comment by meijeru** [comment]
Shift, Ctrl and Alt give no event at all. Perhaps CapsLock should do the same?

**Comment by qtxie** [comment]
I'm not sure if it's on purpose or a bug. Looks like in `on-key` event, we only get the `transalated key`.

for example, if we type `ALT + 248` (pressing ALT, type 248, then release ALT), we get a `ø` character in the area and we get an `on-key` event with this character.

To get the raw key code, we can use `on-key-down` event.

**Comment by meijeru** [comment]
If I do that, I get `#"^T"` for my CapsLock which is `U+0014` or `DC4 (DEVICE CONTROL FOUR)`. It would be interesting to try all "special" keys this way. The results may not even be the same for all keyboard/OS combinations.
