### ISSUE TITLE
text in area couldn't be wrapped

### ISSUE THREAD

**Issue by ludx** [red/red#2355]
e.g. I use
```
view layout [
    a: area 200x200 "Here's some text, lots and lots of text. Here's some text, lots and lots of text."
        para[
    wrap?: on
        ]
    return
    button "wrap？" [print a/para/wrap?]
]
```
or
```
view layout [area 200x200 "Here's some text, lots and lots of text. Here's some text, lots and lots of text." wrap]
```
but did not work in Windows 10.

![default](https://cloud.githubusercontent.com/assets/1643434/20864184/d987b9ea-ba20-11e6-8983-33c53d9ff646.png)

**Comment by qtxie** [comment]
Now setting the para/wrap? in area works properly.
```
view layout [
    a: area 200x200 "Here's some text, lots and lots of text. Here's some text, lots and lots of text."
        para[
    wrap?: yes
        ]
    return
    button "wrap？" [a/para/wrap?: not a/para/wrap?]
]
```

**Comment by Oldes** [comment]
@qtxie in current version, your example turns off wrapping, but it is not possible to turn it on again.

**Comment by Oldes** [comment]
Also when there is wrapping turned on, vertical bar is not visible with long wrapped text as used `DrawText` function is not counting with wrapping.

**Comment by qtxie** [comment]
@Oldes Yes, you're right. Did you fix it?

**Comment by Oldes** [comment]
@qtxie just the second one... I don't know how to fix the switching.. the only thing I know is, that `update-para` is called just for the init and the first change.

**Comment by qtxie** [comment]
@Oldes IIRC, the only way is to destroy the old area, then create a new one with the new setting.

**Comment by Oldes** [comment]
@qtxie that does not sound as a good way... any reason for that?

**Comment by qtxie** [comment]
@Oldes It's the limitation of the control. :sweat:

**Comment by Oldes** [comment]
Still don't understand why it works on the first call and not later. It will be source of many confusions.

**Comment by qtxie** [comment]
It's a regression. I checkout this commit e279b28, it works fine.

**Comment by qtxie** [comment]
@Oldes I fixed the first problem. Could you please make a PR for the second one?

**Comment by Oldes** [comment]
It is already available: https://github.com/red/red/pull/2874 with other improvements. So it is up to you to review it and possibly approve it. Main reason for it was, that area with many lines was terribly slow.

**Comment by Oldes** [comment]
Hm... just testing it with your modification and it now does not work as before.:/

**Comment by Oldes** [comment]
@qtxie so it was issue on my side - I had wrong initial state for wrapping. It is fixed now in the pull request. While testing it, I found two things:

1. while writing into the area, the scroll bars does not appear with the first char out of area rectangle... but needs a few more chars.. it looks like we should subtract scroll bar width/height from the rectangle.. what do you thing?

2. when used `right` text alignment, the horizontal bar is not updated and text is always wrapped. Is it normal?

**Comment by qtxie** [comment]
@Oldes 
1. Yes. It's better to substract scroll bar width/height.
2. I think the horizontal bar should be updated. Not sure if it's the text control's issue or ours.

**Comment by Oldes** [comment]
Any idea how to do it? :)

**Comment by qtxie** [comment]
Have no idea about the second issue. For the first one, we can just substract 17 (scrollbar width) as we cannot (easily) change the scrollbar in area, so I think it's safe to hard coded it.

**Comment by Oldes** [comment]
Isn't the scroll bar size dependent on dpi resolution?
