### ISSUE TITLE
Change selected item in text-list will insert it to first column

### ISSUE THREAD

**Issue by qtxie** [red/red#2358]
```
view [
    list: text-list data ["John" "Bob" "Alice"]
    button "Add" [append list/data "Sue"]
    button "Change" [lowercase list/data/(list/selected)]
]
```

**Comment by maximvl** [comment]
Initial state:

![bug1](https://cloud.githubusercontent.com/assets/949890/21031015/a0553470-bda1-11e6-9c98-67d517c2837f.PNG)

After selecting "Alice" and pressing "Change": 

![bug2](https://cloud.githubusercontent.com/assets/949890/21031028/b7931b2a-bda1-11e6-9ce8-595617381636.PNG)
