### ISSUE TITLE
Regression in compiler

### ISSUE THREAD

**Issue by x8x** [red/red#2365]
Code of `%test.red`:
```
Red []

if zero? call/output {date} o: "" []
```
Compiling return an error:
```
red -c -r test.red

-=== Red Compiler 0.6.1 ===- 

Compiling /test.red ...
*** Compilation Error: expected a block for IF-BODY instead of string! value 
*** in file: %/test.red
*** near: ["date" o: "" []]
```

**Comment by dockimbel** [comment]
`call` is not yet part of Red runtime library, so that code cannot be compiled as is.

**Comment by x8x** [comment]
Sorry, bad example..
so the problem seams to be that running this code:
Code of `%test.red`
```
Red []
write %test2.red trim/head next head clear back tail mold compose/only [
	Red []
	#include %libs/call/call.red
	if zero? call/output {date} o: "" []
]
``` 
Now I run `red test.red` and the content of resulting file `%test2.red` is:
```
Red [] do %libs/call/call.red 
    if zero? call/output "date" o: "" []
```
`#include %libs/call/call.red` has been converted to `do %libs/call/call.red ` and that is why I suppose I can not compile it with `red -c -r test2.red`

I suppose I should switch from using `compose` to the new macros functionalities, but still is it correct that `compose` convert the preprocessor line?

Thank you!

**Comment by nc-x** [comment]
@x8x 
`call` uses R/S code so can't be interpreted with `do` and needs compilation.

**Comment by geekyi** [comment]
@x8x you say it's a regression. Do you know of any working version?

Interestingly, when you run the `%test.red` code directly in the interpreter instead of `red test.red`, it works as you expect (i.e. no conversion from `#include` to `do`)

Edit: red-061.exe works as @x8x expected, I'll have to check some more..

**Comment by x8x** [comment]
True, if run in the interpreter it will not do the conversion, `red test.red` will do the conversion.

**Comment by dockimbel** [comment]
@x8x Your second description looks confusing to me, sorry. `compose/only` has no effect on the argument, so why is it there? It seems you try to run Red code which includes R/S code from the interpreter? Can you tell me simply what error you get and how to reproduce it?

About `compose`, I don't get your question, `compose` is a runtime function, so it has nothing to do with the preprocessor (which happens before the evaluation of a given script).

**Comment by x8x** [comment]
Rereading this issue, it is indeed confusing, so let me give a clearer example:
file `include.red` content:
```
Red []

a: true
```
file `code.red` content:
```
Red []

hello: "Hello World"

save %compile.red compose [

	Red []
	#include %include.red
	print a
	print (hello)

]

call/console {red -c -r compile.red}
```
now let's run `code.red`:
```
red code.red
```
the file `compile.red` generated contain:
```
Red [] do %include.red
print a
print "Hello World"
```
Note that `#include %include.red` has been converted to `do %include.red` !
This is the issue!
So is this conversion a feature or a regression?
If it is a feature, what would be the best way to generate code in red that I later want to compile and that needs macros?

**Comment by dockimbel** [comment]
The `#include` => `do` conversion happens when you run code in the interpreter. It is a feature, allowing user code to run unchanged from interpreter and compiler. When such transformation is not wanted, you can switch off/on the preprocessor (see the [documentation](https://doc.red-lang.org/en/preprocessor.html#__process)), so the following code would work fine:
```
	Red []
	#process off
	#include %include.red
	#process on
	print a
	print (hello)
```

**Comment by x8x** [comment]
Very nice! Thank you! Read the docs Luke... :-)
