### ISSUE TITLE
<remove-each> doesn't return anything

### ISSUE THREAD

**Issue by 9214** [red/red#2366]
in **Rebol2** `remove-each` should return changed series:
```
>> remove-each i [1 2 3 4] [even? i]
== [1 3]
```
in **Rebol3** it should return a count of the number of elements removed:
```
>> remove-each i [1 2 3 4] [even? i]
== 2
```
but in **Red** it doesn't return anything:
```
red>> remove-each i [1 2 3 4] [even? i]
red>>
```

**Comment by dockimbel** [comment]
Closing as duplicate of #2126.
