### ISSUE TITLE
simple-clock.red drawing needles off center

### ISSUE THREAD

**Issue by OneArb** [red/red#2370]
red-latest.exe

needles off center
   second makes a circle

![Uploading simple-clock.png…]()

XP machine

Thanks

**Comment by geekyi** [comment]
@OneArb I can't see your image. Also, can you give a link to the demo you are referring to?

P.S. the code might be in https://github.com/red/code/tree/master/Scripts
Or maybe a gist

**Comment by geekyi** [comment]
Looks like the cause of this is 
18ed2b2e006ee021f40b6bdee051567aa6070d1b
@Zamlox ?

**Comment by Zamlox** [comment]
I'll check it out

**Comment by Zamlox** [comment]
Forgot to apply existing world transformation matrix on center point when rotation operation is used.  I will push a fix for it.

**Comment by OneArb** [comment]
The image just in case:

![simple-clock](https://cloud.githubusercontent.com/assets/9049878/21347082/6a51ce88-c6a7-11e6-82c1-3fc436aeaf6b.jpg)
