### ISSUE TITLE
tuple is not handled correctly when compiling

### ISSUE THREAD

**Issue by meijeru** [red/red#2374]
The following program behaves correctly when interpreted, but when compiled with `-t MSDOS` it produces the wrong result:
```
Red []
smpl: 1.2.3.4.5
print mold smpl    ; when interpreted, prints 1.2.3.4.5, when compiled prints 1.2.3.4.2
```

**Comment by meijeru** [comment]
Can be simplified to `print 1.2.3.4.5` -- still gives wrong result

**Comment by qtxie** [comment]
I remember this issue happened before.

**Comment by qtxie** [comment]
Related issue #2068 .
