### ISSUE TITLE
Field can show hint text when it's blank.

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2377]
In old-style GUI design, a field is always next to a label used to tell user what the filed is about. In new-style GUI design, a field can have a prompt string shown such as "Search", "Your name here" when it's blank. I would like Red to support this feature in GUI engine and VID. Thanks.

**Comment by qtxie** [comment]
Implementation Note: 
Windows: https://msdn.microsoft.com/en-us/library/bb761639(VS.85).aspx
macOS: https://developer.apple.com/reference/appkit/nstextfield/1399391-placeholderstring?language=objc

**Comment by qtxie** [comment]
Now you can set hint text in field's options:

```
view [f: field do [f/options: [hint: "search text"]]]
````
