### ISSUE TITLE
to-tuple on floats

### ISSUE THREAD

**Issue by maximvl** [red/red#2384]
`to-tuple` allows floats, but converts them into zeros:
```
red>> to-tuple [1.0 2 3.5]
== 0.2.0
```
In same time other types raise exception:
```
red>> to-tuple [1 a 2]
*** Script Error: cannot MAKE/TO tuple! from: [1 a 2]
*** Where: to
```

I suggest to raise exception on `float!` values too.

**Comment by dockimbel** [comment]
Actually, supporting float values (rounding them to integers) would be helpful when, e.g., calculating RGB/A color values and getting float values as result of the calculation (often the case).

**Comment by dockimbel** [comment]
Now `float!` and `char!` values are supported too in the spec block.
