### ISSUE TITLE
[parse] `collect/keep` inconsistency

### ISSUE THREAD

**Issue by maximvl** [red/red#2391]
`collect/keep` inside `parse` returns different structure depending on number of elements:
```
red>> parse [x -- ] [collect [keep to '-- ]]
== [x]
red>> parse [x y -- ] [collect [keep to '-- ]]
== [[x y]]
```
I suggest to return same structure without depending on number of elements, eg `[[x]]` in first case or `[x y]` in second one.

**Comment by dockimbel** [comment]
This is an intended behavior, `keep` captures a range of value as a block, so that the range information is preserved. This was meant to provide a larger number of options for the user, as it is always possible to rewrite your parsing rules to capture values one by one instead of a range (or the other way around). Though, this can lead sometimes to under-optimized or overly-complex rules. For example:
```
red>> parse [x -- ] [collect [keep copy z to '-- ]]
== [[x]]
```
So far, I have always used `keep` to capture single values, so I have not encounter such issue.

**Comment by dockimbel** [comment]
Another aspect to consider also is the behavior of `keep` when parsing string series. If we remove the range-capturing mode, then this is what you would get for strings:
```
digit: charset "0123456789"
parse "hello123world456" [collect any [keep 3 digit | skip]]
== [#"1" #"2 #"3" #"4" #"5" #"6"]
```
instead of:
```
== ["123" "456"]
```

**Comment by dockimbel** [comment]
Another aspect to consider also is the behavior of `keep` when parsing string series. If we remove the range-capturing mode, then this is what you would get for strings:
```
digit: charset "0123456789"
parse "hello123world456" [collect any [keep 3 digit | skip]]
== [#"1" #"2 #"3" #"4" #"5" #"6"]
```
instead of:
```
== ["123" "456"]
```

**Comment by greggirwin** [comment]
For the non-`parse` version of `collect`, `keep` has an `/only` refinement. It might be confusing to have a `keep-only` keyword in `parse` though. Otherwise, I think the current behavior is good, and is consistent with `load`.

**Comment by geekyi** [comment]
The first case does result in some loss of information. Can always get the second from the first by flattening the series.
In practice, I've not thought much about the difference. It conveniently returns the result I want usually. Unless it's a recursive (or a sub-)rule, in which case I have to think.

**Comment by dockimbel** [comment]
We could maybe add a modifier keyword after `keep` when you want values to be collected individually instead of as a range. Maybe `keep flat` or `keep split`? (`only` is the default mode, so we need an opposite keyword).

**Comment by Oldes** [comment]
`keep split` seems to be better for string result as mentioned above.

**Comment by dockimbel** [comment]
This ticket is related to #2295.

**Comment by dockimbel** [comment]
So, now you have all the possibilities covered:
* by default, nothing is changed, you get a single value or a list of value in range-capturing mode.
* `keep pick` collects all the matched values separately
* `keep copy <word>` collects all the matched values as a series (of same type as input).

For example:
```
red>> parse [x -- ] [collect [keep to '-- ]]
== [x]
red>> parse [x y -- ] [collect [keep to '-- ]]
== [[x y]]

red>> parse [x -- ] [collect [keep pick to '-- ]]
== [x] 
red>> parse [x y -- ] [collect [keep pick to '-- ]]
== [x y]

red>> parse [x -- ] [collect [keep copy _ to '-- ]]
== [[x]]
red>> parse [x y -- ] [collect [keep copy _ to '-- ]]
== [[x y]]
```
Note: `_` is a word, any word would do, here I use underscore to signify that we don't care about that word or his value, as it is immediatly collected by `keep`.
