### ISSUE TITLE
Switch doesn't work on word! and block! values

### ISSUE THREAD

**Issue by maximvl** [red/red#2394]
```
red>> switch 1 [1 [5]]
== 5
red>> switch 'b ['b [5]]
== none
red>> switch [b] [[b] [5]]
== none
```

I suggest to make `switch` work on all comparable types.

**Comment by meijeru** [comment]
Your second example should be `switch 'b [b [5]]` since the labels of the switch alternatives are NOT evaluated. With that change the result is correct: 5. The third example is problematic since the `switch` native allows multiple labels.

**Comment by maximvl** [comment]
@meijeru thanks for reply, what do you mean by multiple labels?

**Comment by meijeru** [comment]
This:
```
switch 1 [1 2 [5] 3 4 [6]]
```
for example. It will be impossible to allow blocks as labels because in that case one cannot know whether a block is a label or an alternative.

**Comment by maximvl** [comment]
Clear enough, last one is subject to another discussion. I'm closing the issue.
