### ISSUE TITLE
checksum crashes of file! type

### ISSUE THREAD

**Issue by jvargas** [red/red#2400]
Red 0.6.1 on windows crashes when running checksum on files, and it fails on OSX.

    red>> data: {Hello World}
    == "Hello World"
    red>> write %testfile.txt data
    red>> checksum data 'md5
    == #{B10A8DB164E0754105B7A99BE72E3FE5}
    red>> checksum %testfile.txt 'md5

**CRASH**

**Comment by geekyi** [comment]
It works on windows with latest automated build, but isn't implemented for [files](https://github.com/red/red/blob/649c433cc160aa01d45ebe86672659599298206f/runtime/natives.reds#L2087)

Maybe you can try to implement yourself? ;)
I think you need to add a condition for `TYPE_PATH` there

**Comment by qtxie** [comment]
Fixed in master branch.
