### ISSUE TITLE
[vid] Image bug on Wine

### ISSUE THREAD

**Issue by maximvl** [red/red#2402]
This code produces result on screenshot:
```
Red []
view layout [ image ]
```
![screenshot_2017-01-05_20-54-18](https://cloud.githubusercontent.com/assets/949890/21691343/3ee32712-d389-11e6-942b-f84a2be658fe.png)

The same image drawn twice, second time in top left corner.

**Comment by meijeru** [comment]
BTW, this can be simplified to `view [ image ]`

**Comment by qtxie** [comment]
I test it on wine1.8, works fine.

**Comment by hiiamboris** [comment]
Is is this relevant still? Anyone reproduced it?

**Comment by qtxie** [comment]
Close it as we don't officially support Wine backend and GTK backend is included in Red now.
