### ISSUE TITLE
The block argument to make typeset! should be allowed to contain typesets

### ISSUE THREAD

**Issue by meijeru** [red/red#2403]
Currently, the block argument to `make typeset!` may only contain datatypes. I had a situation where I wanted to construct a new typeset out of the type spec block of a particular argument of a function; this type spec block was a mixture of datatypes and typesets (allowed in that case). The following error occured:
```
red>> make typeset! [datatype! block! paren! any-path! any-string!]
*** Script Error: invalid argument: any-path!
*** Where: make
```

**Comment by dockimbel** [comment]
Alternatively, you can use *set* functions to construct your typeset:
```` 
union union make typeset! [datatype! block! paren!] any-path! any-string!
```

**Comment by meijeru** [comment]
I agree about the alternative, but the point was that sometimes one has a *block* of types and typesets. If such a block is allowed in a function spec, it would be nice to have it allowed in make typeset!

**Comment by dockimbel** [comment]
Indeed.
