### ISSUE TITLE
Infinite loop on using copy any in #macro rule block

### ISSUE THREAD

**Issue by ifgem** [red/red#2411]
```
expand [
	#macro [copy nums [any integer!]] []
]
```

**Comment by dockimbel** [comment]
I get a syntax error on your macro:
```
*** Preprocessor Error: Syntax error
*** Where: #macro [copy nums [any integer!]] []
```

**Comment by dockimbel** [comment]
Actually, the issue is caused by a misuse of the return value in pattern-matching macros. The [documentation](https://doc.red-lang.org/en/preprocessor.html) is not up to date, and describes the old behavior of pattern-matching macros, and lacks mention of *manual* mode.

**Comment by dockimbel** [comment]
The infinite loop is caused by your usage of `any`, matching 0 or more instances of `integer!`. You should have used `some` instead. Here is a fixed version:
```
expand [
    #macro [copy nums some integer!] func [[manual] s e][?? nums e]
    print [1 2 3]
]
```
which would output:
```
nums: [1 2 3]
[print [1 2 3]]
```
