### ISSUE TITLE
Being able to take address of a struct! member using a get-path

### ISSUE THREAD

**Issue by Zamlox** [red/red#2412]
Curently in Red/System it's not possible to get the address of a ```struct!``` member using ```:```. Doing pointer math calculation might be tedious if the ```struct!``` is large and members of different types.

Following construct would be much easier and elegant:
```
x: declare struct! [
    a   [integer!]
    b   [integer!]
]

y: :x/a
```
where ```y``` is of type ```int-ptr!```

**Comment by meijeru** [comment]
👍 The current system is not only tedious but also error prone in the sense that it depends on detailed knowledge of the way memory is allocated for structs.

**Comment by Skrylar** [comment]
If I had to guess, it's not in because R/S is implemented in throwaway code right now.

**Comment by dockimbel** [comment]
All pointers taken to struct members are `pointer! [integer!]` by default (most common case).

**Comment by Zamlox** [comment]
Thank you for implementing this feature.

I have done a test with latest sources and I have an issue.
Source code:
```
Red/System []

a: declare struct! [
    val [integer!]
]

a/val: 23

p-val: :a/val
print [" p-val: " p-val/value lf]
```

When I compile I get following output:
```
Compiling d:\dev\work\fork_red\tests\test.reds ...

Target: Windows

Compiling to native code...
*** Compilation Error: invalid path value: p-val/value
*** in file: %/d/dev/work/fork_red/tests/test.reds
*** at line: 1
*** near: [10x1 " p-val: " p-val/value lf]
```


Red info: 
```
--== Red 0.6.2 ==-- 
Type HELP for starting information. 

>> about
Red 0.6.2 - 31-Mar-2017/15:11:15+3:00
```

**Comment by Zamlox** [comment]
I haven't tested with latest automated build which contains this fix. This might explain the issue I have.

**Comment by Zamlox** [comment]
Tested with latest automated build and I got rid of compilation error.

I run another test with embedded ```struct!``` and the result is not as expected.
Test program:
```
Red/System []

b!: alias struct! [
    b1  [byte!]
    b2  [integer!]
]
a: declare struct! [
    x   [byte!]
    bb  [b!]
    val [integer!]
]

a/bb: as b! allocate size? b!
a/bb/b1: #"A"

p-bb-b1: :a/bb/b1
print [" a/bb/b1: " a/bb/b1 lf]
print [" p-bb-b1/value: " as byte! p-bb-b1/value lf]
```

Result:
```
 a/bb/b1: A
 p-bb-b1/value: Ï
```

Value of ```p-bb-b1/value``` should be ```A```.

**Comment by dockimbel** [comment]
Thank you for pointing out this issue with deeper get-paths. It should be fixed now.
