### ISSUE TITLE
[macOS] System Crash

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2416]
Running the "Weima" code, that I sent to the FullStack Technologies company earlier, twice in the same console will crush the system (as shown below)

```Red
red>> do %weima.red 
red>> do %weima.red
Jan 16 13:28:53  console[2540] <Warning>: void CGSUpdateManager::log() const: conn 0x1bd0f: spurious update.

*** Runtime Error 1: access violation
*** at: 943052AEh
```

**Comment by JerryTsai** [comment]
This issue is gone in the latest auto-build version.

**Comment by qtxie** [comment]
Good to know. :-)
