### ISSUE TITLE
`attempt` stops propagation of `break`

### ISSUE THREAD

**Issue by maximvl** [red/red#2417]
```
red>> forever [ print "1" break ]
1
red>> forever [ attempt [ print "1" break ] ]
1
*** Throw Error: no loop to break
*** Where: break
```

In second case `break` is expected to break a loop, not to raise an error.

**Comment by dockimbel** [comment]
BREAK and CONTINUE exceptions have been relaxed to allow crossing function borders up to the first wrapping loop.
