### ISSUE TITLE
`switch` expects literal block as second argument -- refuses reduced block

### ISSUE THREAD

**Issue by meijeru** [red/red#2418]
Smallest test program:
```
Red []
a: 1
switch 1 reduce [a []]
```

Result:
```
*** Compilation Error: SWITCH expects a block as second argument 
*** in file: %/C/Projects/Red/programs/test/test-switch.red
*** near: [reduce [a []]]
> Terminated with exit code 1.
```

**Comment by meijeru** [comment]
In contrast to the compiler, the interpreter *does*  accept reduced blocks.

**Comment by dockimbel** [comment]
The fallback to the interpreter for `switch` (and several other control flow function) has not been implemented yet in the compiler. It is supposed to be implemented at a later stage, when we can figure out the most efficient way to support it. Though, for now, I will just add a simple fallback to the interpreter in the compiler code.
