### ISSUE TITLE
In tab-panel, on-change event reports face/selected BEFORE change

### ISSUE THREAD

**Issue by meijeru** [red/red#2420]
This occurs both with on-change and with on-select and it impedes handling multiple tabs correctly.

**Comment by meijeru** [comment]
By analogy with text-list, there could be made a difference between on-change and on-select. That way no information is lost.

**Comment by meijeru** [comment]
I also tried event/picked, but that seems to yield more or less random numbers.

**Comment by dockimbel** [comment]
`on-select` should be working for tab-panels... Trying with this test script:
```
view [
	tab-panel ["one" [] "two" []]
		on-select [print ["on-select:" face/selected event/picked]]
		on-change [print ["on-change:" face/selected event/picked]]
]
```
Clicking alternatively on the tabs gives me:
```
on-select: 1 2
on-change: 1 2
on-select: 2 3
on-change: 2 1
on-select: 1 2
on-change: 1 2
on-select: 2 3
on-change: 2 1
on-select: 1 2
on-change: 1 2
on-select: 2 3
on-change: 2 1
```
which show that `on-select` is not giving the right values.

**Comment by dockimbel** [comment]
After some tests, `on-select` would not be useful there (Windows OS does not provide any information for such event), `on-change` is enough anyway.

So to answer your query, in `on-change`, the `face/selected` property contains the previously selected tab index, while `event/picked` contains the new one (and it's not random, as you can see from the test above). I will add that missing information to the documentation for `tab-panel`.
