### ISSUE TITLE
In area face, tab is set at 8 spaces, tab size apparently cannot be configured

### ISSUE THREAD

**Issue by meijeru** [red/red#2421]
I would prefer it at 4 spaces, or better still, configurable...

**Comment by dockimbel** [comment]
We should add a property for that in `face/options`, like `options/tabs: <integer>`.

**Comment by meijeru** [comment]
Is the default now changed to 4 (commit `966930e`)?

**Comment by dockimbel** [comment]
Yes.

**Comment by qtxie** [comment]
Now we can set tab size in area/options:
```
view [a: area do [a/options: [tabs: 8]]]
```
