### ISSUE TITLE
WISH: an AREA facet that indicates the cursor position ("caret")

### ISSUE THREAD

**Issue by meijeru** [red/red#2422]
Together with the promised implementation of the SELECTED facet this would greatly facilitate the writing of editor facilities in Red.

**Comment by dockimbel** [comment]
We are working on a new feature for Draw dialect, called `text-box` for now, which should be used as the base for writing editors. It does support an interface to access the caret and many features not available in current `area`. The `area` widget might be rewritten in the future using `text-box`.
