### ISSUE TITLE
request-file under Windows ignores value of /file refinement

### ISSUE THREAD

**Issue by meijeru** [red/red#2425]
Instead, request-file starts in the last folder visited, and this across sessions (program start/end). It seems the parameter is ignored.

**Comment by geekyi** [comment]
Works for me with:
`red>> request-file/file %/C/Users/`
Doesn't work if the trailing slash `/` is missing:
`red>> request-file/file %/C/Users`

**Comment by meijeru** [comment]
Using same version (25-Jan-2017) under W10: it works the first time around, but each subsequent call starts in the last folder visited.

**Comment by meijeru** [comment]
Works now -> close issue!
