### ISSUE TITLE
Linux: cannot access argument file

### ISSUE THREAD

**Issue by Skrylar** [red/red#2426]
Red: 0.6.1
OS: Linux, Arch
Reproducible: Always

https://asciinema.org/a/epxsugh4pyjhkoxh75ndrn2rd

Command line arguments can't be used, which in turn means the compiler doesn't appear to be invokable.

**Comment by PeterWAWood** [comment]
```-v``` is not a valid command line argument for the Red executable. ```-V``` or ```--version``` are the arguments to get Red to print its version.

This does not affect Red's ability to compile Red programs:
```text
$ red --v
*** Error: cannot access argument file
--== Red 0.6.1 ==-- 
Type HELP for starting information.

$ red -V
0.6.1

$ red --version
0.6.1

$ red -c test.red

-=== Red Compiler 0.6.1 ===- 

Compiling test.red ...
...compilation time : 574 ms
```

I feel the error message is misleading so I have updated the title of the issue to reflect that.

**Comment by nc-x** [comment]
@PeterWAWood In the screenrecording by @Skrylar, even `red --help` does not work. I think it should be working? Looks like some issues in Skrylar's set-up. IDK, maybe...

**Comment by PeterWAWood** [comment]
I have tested both the 0.6.1 release and the latest automated build under Ubuntu32 and the error message is only displayed with ```red -v```.

**Comment by Skrylar** [comment]
Additional commands (some valid, others not) tested on a second machine (still Arch, and 0.6.1)

https://asciinema.org/a/740utrwaryfn4y07e9nbbzvc0

**Comment by geekyi** [comment]
I have the same behavior as described by @PeterWAWood on windows 10.

@Skrylar what is the output of `red>> ? system/options` after you type something like `--help` ?
I suspect it may be caused by your shell messing with what's passed to red.
For me:
```
red>> ? system/options/args
system/options/args is a string! of value: "-v"
```

**Comment by Skrylar** [comment]
Zshell 5.3.1

```
Raziel% red
--== Red 0.6.1 ==--
Type HELP for starting information.

red>> ? system/options/args
system/options/args is a none! of value: none
```

```
Raziel% red -h
*** Error: cannot access argument file
--== Red 0.6.1 ==--
Type HELP for starting information.

red>> ? system/options/args
system/options/args is a string! of value: {"-h"}
```

GNU Bash 4.4
```
[skrylar@Raziel ostar]$ red
--== Red 0.6.1 ==--
Type HELP for starting information.

red>> ? system/options/args
system/options/args is a none! of value: none
```

```
[skrylar@Raziel ostar]$ red -h
*** Error: cannot access argument file
--== Red 0.6.1 ==--
Type HELP for starting information.

red>> ? system/options/args
system/options/args is a string! of value: {"-h"}
```
