### ISSUE TITLE
event/ctrl? always returns true for on-wheel event

### ISSUE THREAD

**Issue by endo64** [red/red#2434]
event/ctrl? always returns true for on-wheel event.
event/shift? works correctly.

```
b: make face! [
	type:		'base
	color:		red
	size:		100x100
	offset:		0x0
	options:	[drag-on: 'down]
	actors: object [
		on-wheel: function [face event] [
			probe event/ctrl?	;always prints "true"
		]
	]
]
view make face! [
	type: 'window
	size: 200x200
	pane: reduce [b]
]

```

**Comment by endo64** [comment]
I found that this problem occurs only if I use laptop's touch pad, swipe with two fingers (zoom in/out). It doesn't occur with a real mouse's scroll.

**Comment by qtxie** [comment]
@endo64 How about use the `zoom` event: https://doc.red-lang.org/en/view.html#_event_names
