### ISSUE TITLE
help object! needs to be formatted for readable output.

### ISSUE THREAD

**Issue by gltewalt** [red/red#2435]
`help` needs to specifically format the output for object! to show object-name => description, or object-name and attributes => description.
Currently `help object!` appears to emit the source for all objects in the global context.

**Comment by gltewalt** [comment]
Line 87 can be changed to:
`print-out out [tab pad form :w 15 ": " mold words-of get/any w]`

`help system` will then emit:

```
red>> help system
`system` is an object! of value:
     version          string!   0.6.1 
     build            object!   [date config] 
     words            object!   [datatype! unset! none! logic! block! paren!... 
     platform         function! Return a word identifying the operating system 
     catalog          object!   [datatypes actions natives errors] 
     state            object!   [interpreted? last-error trace?] 
     modules          block!    [] 
     codecs           map!      #(png: make object! [title: "" name: 'PNG mi... 
     schemes          object!   [] 
     ports            object!   [] 
     locale           object!   [language language* locale locale* months da... 
     options          object!   [boot home path script args do-arg debug sec... 
     script           object!   [title header parent path args] 
     standard         object!   [header error] 
     lexer            object!   [throw-error make-hm make-msf make-hms make-... 
     console          object!   [prompt history limit catch? count ws gui? r... 
     view             none!     none 
     reactivity       object!   [relations stack queue debug? do-safe eval-r... 
```

Although, the results are then truncated with "..." by Lines 209 through 211

**Comment by dockimbel** [comment]
@gltewalt Feel free to submit a PR.

**Comment by greggirwin** [comment]
The above change won't work, as it applies to all other types, which don't all support `reflect`. We could add a case at line ~85 to handle objects
```
object? get/any w [
    print-out out [tab pad form :w 15 mold words-of get/any w]
]
```
But maps also support words-of, which might be nice. And if we want it to optimize for 80-char width, as later code in help does (`emit` + ...), that should be a clear decision.

**Comment by greggirwin** [comment]
```
any [object? get/any w  map? get/any w] [
    print-out out [tab pad form :w 15 mold words-of get/any w]
]
```

**Comment by greggirwin** [comment]
Hmmm, the `tab*` vars are not /local in `fetch-help`, though others are. `Fucntion` is used, so they're still captured, but that means the `/local` line isn't needed at all. Worth cleaning up?

**Comment by greggirwin** [comment]
Quick PR done for that /local bit. Seems worth it, since it confused me at a glance.

**Comment by gltewalt** [comment]
Thanks, Gregg Irwin

**Comment by dockimbel** [comment]
@gltewalt Congrats for your first PR and issue fixing! ;-)
