### ISSUE TITLE
Parse infinite loop using [TO/THRU :word]

### ISSUE THREAD

**Issue by pekr** [red/red#2437]
Posting a ticket for an issue found by HF: 

`s: copy "abcd" parse s [x: "ab" thru :s "bcd"]`  ... causes an infinite loop, whereas:

`s: copy "abcd" parse s [x: "ab" thru :s "abcd"]` ... returns true

-pekr-

**Comment by geekyi** [comment]
.. Maybe caused by including what is being parsed in the rules?
