### ISSUE TITLE
`load "a<=>"` freezes the session

### ISSUE THREAD

**Issue by dockimbel** [red/red#2438]
```
red>> load "a<=>"
(freeze)
```

**Comment by gltewalt** [comment]
Looks like load transforms return value to block when <> is encountered.
>> load "* <>"
== [* <>]
>> load "a<>"
== [a <>]
>> load "hello<>"
== [hello <>]
>> load "hello"
== hello
>> load "hello>"
== hello>
>> load "hello<>"
== [hello <>]

**Comment by gltewalt** [comment]
Tag rule appears to be involved in the bug.
lexer.red   --  Line 598
Removed #"="

```
	tag-rule: [
			;#"<" not [#"=" | #">" | #"<" | ws] (type: tag!)
			#"<" not [#">" | #"<" | ws] (type: tag!)
			 s: some [#"^"" thru #"^"" | #"'" thru #"'" | e: #">" break | skip]
			(if e/1 <> #">" [throw-error [tag! back s]])
		]
```

```
>> load "a<=>"
== [a <=>]
```

**Comment by gltewalt** [comment]
>> load <">
*** Script Error: transcode does not allow tag! for its <anon> argument
*** Where: transcode

**Comment by gltewalt** [comment]
Also, I watched frozen Red Console today in task manager before making any changes, and the memory used kept growing and growing.

**Comment by dockimbel** [comment]
@gltewalt Thanks for the help, though, that fix causes regressions, as `<=` cannot be loaded as a `word!` value anymore.

**Comment by gltewalt** [comment]
What about this? (I haven't learned Parse yet as I wanted to fully understand Red semantics first before learning Parse.)
Borrowed from lexer.r

```
	
		;-- new data
		ws-ASCII:  charset " ^-^M"
		not-tag-1st:	complement union ws-ASCII charset "=><"
		not-tag-char:	complement charset ">"
		tag-char:	charset "<>"

		tag-rule: [
			#"<" s: not-tag-1st (type: tag!)
		 	any [#"^"" thru #"^"" | #"'" thru #"'" | not-tag-char] e: #">"
		]
		;-- end new data

		;tag-rule: [
		;	 #"<" not ["=><" | ws] (type: tag!)
		;	 s: some [#"^"" thru #"^"" | #"'" thru #"'" | e: #">" break | skip]
		;	(if e/1 <> #">" [throw-error [tag! back s]])
		;]
```

**Comment by gltewalt** [comment]
That freezes also....
I guess I can't help  :-(

**Comment by hiiamboris** [comment]
I should note that however I may have avoided the freeze problem, the lexers (.r and .red) still diverge on this: `<=>` is invalid in lexer.red but a word in lexer.r. Though, lexer.r being a temporary thing, this problem might never surface in practice.
