### ISSUE TITLE
DO/NEXT applied to string does not skip entire expression

### ISSUE THREAD

**Issue by meijeru** [red/red#2439]
Example:
```
red>> do/next "1 + 2" 'p
== 3
red>> p
== " 2"
```
I suppose `do/next` is meant to work only on blocks, but that is neither documented nor checked

**Comment by dockimbel** [comment]
The returned series is wrong, it should be a block.

**Comment by meijeru** [comment]
The solution is not correct:
```
red>> do/next "1 + 2" 'p
== 3
red>> p
== 3
```
IMHO p should be `[ ]` or `""`

**Comment by dockimbel** [comment]
It should be `[]`

**Comment by meijeru** [comment]
It is in R3, but there is something curious in that implementation:
```
>> do/next "1 + 2" 'p
== 3
>> p
== [ ]
>> head p
== [none 1 + 2]
```

**Comment by dockimbel** [comment]
@meijeru Looks like a R3 bug.
