### ISSUE TITLE
Cannot deviate output of help and source

### ISSUE THREAD

**Issue by meijeru** [red/red#2442]
I am trying to  capture the result of evaluating a Red source into a text area by redefining prin and print. This works fine for normal Red values, but curiously, the output of `help`  and `source` are alway going to the console.

**Comment by meijeru** [comment]
Striking example of this:
```
red>> print: none
== none
red>> help print
print is a none! of value: none 
```
If you look at `source help` is uses `print`, so how come?!?

**Comment by dockimbel** [comment]
`help` and `source` are compiled function, changing `print` word binding will not affect them as their compiled code calls `natives/print*` directly.

**Comment by meijeru** [comment]
Thanks for the explanation!
