### ISSUE TITLE
Consecutive ticks in number types cannot be used

### ISSUE THREAD

**Issue by rebolek** [red/red#2443]
I am not sure if it’s bug or feature, however it's possible in Rebol:

```
>> 123''456'789
== 123456789
```

Red throws error instead:

```
c> 123''456'789
*** Syntax Error: invalid integer! at "123''456'789"
*** Where: do
```

**Comment by dockimbel** [comment]
AFAIK, the convention is to use a single tick as separator for groups of 3 digits, so I guess it's a lexer issue in Rebol.

**Comment by rebolek** [comment]
I remember multiple ticks in an old (cca 1930) book, but I am fine with single tick.
