### ISSUE TITLE
It is not possible to use multiple zeros in exponent

### ISSUE THREAD

**Issue by rebolek** [red/red#2444]
Rebol:

```
>> 1e0002
== 100.0
```

Red:

```
c> 1e0002
*** Syntax Error: invalid float! at "1e0002"
*** Where: do
```

**Comment by dockimbel** [comment]
Rebol supports an arbitrary number of zeros in front of the exponent, Red does not. Rebol might just be re-using the lexer rule for parsing numbers, which accepts arbitrary number of leading zeros. For an exponent value, which follows the `e` or `E` character, I do not see any reason why leading zeros should be accepted, beyond the 4 digits allowed for IEEE754 format.
