### ISSUE TITLE
Redefinition of the #define should at least cause warning

### ISSUE THREAD

**Issue by Oldes** [red/red#2448]
Currently when used `#define` of the same type, there is no warning and just the first one is used.

```
Red/System []
#define TEST(x) [print [x lf]] 
#define TEST(x) [print [x x lf]] 
TEST(1)
```

Above code compiles with success and result is `1`, not `11`.

I think that there should be visual warning or error else it could lead to hard to find compilation issues.

**Comment by dockimbel** [comment]
Good suggestion.
