### ISSUE TITLE
Picosheet demo broken by more strict word rules

### ISSUE THREAD

**Issue by greggirwin** [red/red#2458]
There's a placeholder col header with #" " as the text, which `to word!` doesn't like when combined with a numeric digit to create the cell ref name. If you replace [#" "] with [#"_"]for now, it will work again.

**Comment by geekyi** [comment]
This should be in the red/code repo https://github.com/red/code/blob/0.6.2/Showcase/picosheet.red

**Comment by greggirwin** [comment]
Ah, yes! I need to close and re-create it. No way to move between repos I'm sure.
