### ISSUE TITLE
Runtime Error when `make email!` passed a wrong value

### ISSUE THREAD

**Issue by nc-x** [red/red#2461]
(1)
```
red>> make email! 1
== 
red>> 
```
This gives empty value. I think, this should give an error?
  
(2) Huge integer value crashes with 
```
red>> make email! 11111111111111

*** Runtime Error 1: access violation
*** at: FFFFFFFFh
```

**Comment by dockimbel** [comment]
`make <series!> <integer!>` creates an empty series of that type with preallocated size given by the integer.

**Comment by nc-x** [comment]
Oh, I didn't know that. Sorry 😄

**Comment by meijeru** [comment]
In a previous version (20=Feb=2017) the error message for a too big integer is:
```
*** Script Error: value out of range: none
*** Where: make
```
and this for file!, email! and url! as well as string!

**Comment by dockimbel** [comment]
Now it will error out properly:
```
red>> make email! 11111111111111
*** Script Error: value out of range: 11111111111111.0
*** Where: make
```

**Comment by dockimbel** [comment]
More work is required for catching "out of memory" cases where allocating (big) series.
