### ISSUE TITLE
`call` support `hide` function

### ISSUE THREAD

**Issue by bitbegin** [red/red#2472]
On windows platform, `call` will show(flash) a black console. 
My wishes:
Can it be run background, then return immediately. Then i can check the return pid, to know if the call is finished, also i can get output from pid

**Comment by dockimbel** [comment]
Now by default, the DOS window will be hidden. It can be shown if the /SHOW refinement is used.

For the rest of the wishes, we can only support blocking IO operations for now, until 0.7.0 (we need port! support and an IO event loop for that).
