### ISSUE TITLE
Manual compilation using 'rc does not work anymore

### ISSUE THREAD

**Issue by pekr** [red/red#2474]
I am used to using the R2 console session and in the past, following aproach worked (if the 1) is an intended change, ok then):

1) double click the red.r file got me into the R2 console. Does not work anymore

2) Using 'rc to manually compile scripts, does not seem to work either:

>> rc "-t Windows %environment/console/gui-console.red"
*** Driver Internal Error: Script Error : Cannot use path on none! value
*** Where: parse-options
*** Near:  [system/script/parent/path]

**Comment by dockimbel** [comment]
The fix is for 2. Could you test if that fixes 1. too?

**Comment by pekr** [comment]
Compilation 2) works OK now. 1) still does not work. So one has to launch R2 and use 'change-dir. Not a big deal eventually, if it needs to stay that way ...

**Comment by dockimbel** [comment]
You can now force the `red.r` script to halt in the console. Make a shortcut icon from `red.r` icon and edit the properties to use `red.r halt`. Click on that shortcut icon instead of `red.r` to open a console.
