### ISSUE TITLE
call/console "cmd" freezes gui-console 

### ISSUE THREAD

**Issue by xqlab** [red/red#2478]
`--== Red 0.6.1 ==-- 
Type HELP for starting information. 

red>> help system/options/boot
system/options/boot is a string! of value: {C:\ProgramData\Red\gui-console-2017-3-14-39755.exe} 

red>> call/console "cmd"
`

**Comment by qtxie** [comment]
`call/console` is not implemented in gui-console.
I push a fix to fire an error when use `call/console` refinement in gui-console.
