### ISSUE TITLE
compile-time and run-time lexer differ in acceptance of whitespace

### ISSUE THREAD

**Issue by meijeru** [red/red#2492]
`%lexer.r` accepts `U+0085` (newline) whereas `%lexer.red` does not!

BTW all code points > U+00A0 which have Unicode property `WSpace=Y` are for the moment excluded from whitespace (the corresponding code is commented out), and also U+000B, U+000C (no code foreseen)

**Comment by dockimbel** [comment]
The inclusion or non-inclusion of all variants of unicode whitespaces has not been decided yet.
