### ISSUE TITLE
compile-time and run-time lexer differ in acceptance of email values

### ISSUE THREAD

**Issue by meijeru** [red/red#2493]
`lexer.red` accepts email values starting with `@`, whereas `lexer.r` does not.

In order to free `@` as an initial character for values of a new type, the compile-time rule should probably win out

BTW both lexers accept email values ending in `@`, i.e. with an empty "host"

**Comment by dockimbel** [comment]
> BTW both lexers accept email values ending in @, i.e. with an empty "host"

This is done on purpose to support such lexical form for dialecting without having to create a new type.
