### ISSUE TITLE
make vector! has issues

### ISSUE THREAD

**Issue by meijeru** [red/red#2495]
`make vector! [integer!...]` accepts bitsizes 8, 16, 32, 64. However, with 64 the following crashes:
```
v: make vector! [integer! 64 []]
insert v 1
v/1
```
`make vector! [float!...]` also accepts these bitsizes, but with 8 and 16 the following happens:
```
v: make vector! [float! 8 []]
insert v 1.0
v/1 ; == 0.0 instead of 1.0, same for 16
```

**Comment by qtxie** [comment]
64bit integer and 8bit float! are not supported in vector!, we should fire an error when using it.
FYI, supported datatypes in vector:
```
Integer/Char:    8bit, 16bit, 32bit
Float/Percent:   32bit, 64bit
```

**Comment by meijeru** [comment]
`make vector! [percent! 32 []]` still crashes!!!

**Comment by qtxie** [comment]
Thanks. Fix it now.
