### ISSUE TITLE
select <binary> yields char! value instead of integer! value

### ISSUE THREAD

**Issue by meijeru** [red/red#2502]
In all other cases of series selection, the result has the element type of the series. But see this:
```
>> b: #{010203}
== #{010203}
>> select b #{01}
== #"^B"   ; should be 2
>> select b #{0102}
== #"^C"   ; should be 3
```

**Comment by dockimbel** [comment]
Agreed, but actually, it should be an integer, `#{02}` is a binary series, it's not an element of a binary series.

**Comment by meijeru** [comment]
I agree. Will you take it on now that I have changed the title?
