### ISSUE TITLE
Windows COM support

### ISSUE THREAD

**Issue by RedJosh** [red/red#2506]
I wish to have Windows COM support in Red.

**Comment by mydoghasworms** [comment]
This would be great.

**Comment by qtxie** [comment]
I want to implement one before, something similar to [comtypes](http://pythonhosted.org/comtypes/) in python.
I think it would be implemented as a lib or a module.

**Comment by RedJosh** [comment]
Comtypes are easy to understand. It will be very nice to have something similar

**Comment by dockimbel** [comment]
Such feature is not on our roadmap, though, it can be contributed by anyone (including from someone from the Red team). As it will not be part of the red/red repo anyway, I'm closing this ticket.
