### ISSUE TITLE
can I use red gui system on macOS?

### ISSUE THREAD

**Issue by HouLinwei** [red/red#2509]
I have read the `Getting Started` section, but the 
```
view [text "Hello World!"]
```
will raise
```
*** Script Error: view has no value
*** Where: catch
```
so, red gui can work on macOS?

**Comment by nc-x** [comment]
macOS gui is a WIP. You will have to use [this branch](https://github.com/red/red/tree/macGUI?files=1)  and compile from source (read the Readme) or wait a few days for it to get merged to master and then you can use the automated builds.

**Comment by HouLinwei** [comment]
It's cool! thx.
I will try it later.
Thank you for your reply.
