### ISSUE TITLE
Preprocessor-test.red causes access violation in interpreter

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#2516]
When running preprocessor-test.red in the console I get an access violation. (I get the same error running the test in libRed.)

```test
>> do %quick-test/quick-test.red
>> do %tests/source/units/preprocessor-test.red

*** Runtime Error 1: access violation
*** at: 000446C9h
mbp:red peter$ ./test-console
```

**Comment by PeterWAWood** [comment]
The error also occurs un Windows 7:
```
E:\Red\red\tests\libRed>libRedTest.exe ../source/units/preprocessor-test.red

*** Runtime Error 1: access violation
*** at: 6EE29455h
```

**Comment by dockimbel** [comment]
The crash was fixed, though, you should avoid loading the `quick-test.red` lib as it is already loaded from within the test script. ;-)

**Comment by PeterWAWood** [comment]
I thought that #includes were ignored by the interpreter.

**Comment by dockimbel** [comment]
They are ignored by the interpreter, but the preprocessor converts them to `do` when run from the interpreter.

**Comment by PeterWAWood** [comment]
Thanks.
