### ISSUE TITLE
wrong error message when accessing email component by integer

### ISSUE THREAD

**Issue by meijeru** [red/red#2524]
```
>> e: a@b
== a@b
>> e/1
*** Script Error: cannot access 1 in path [script invalid-path]
*** Where: catch
```
The path is not displayed, instead some other value is formed

**Comment by meijeru** [comment]
See lines 62 and 65 of `%email.reds`. Apparently `stack/arguments` is overwritten by `TO_ERROR` so the second argument to the `fire` function should be gotten from somewhere else (or save`stack/arguments` first?).

**Comment by qtxie** [comment]
In Rebol it is allowed:
```
>> e: a@b
== a@b
>> e/1
== #"a"
```

**Comment by dockimbel** [comment]
@meijeru Thank you for the code analysis!

**Comment by meijeru** [comment]
Have you decided what it is going to be: alllowed or forbidden (with better error message)? My vote is for allowing.

**Comment by dockimbel** [comment]
It is allowed since 0.6.3:
```
>> e: a@b
== a@b
>> e/1
== #"a"
```
