### ISSUE TITLE
Math doesn't follow the arithmetic precedence for %, **

### ISSUE THREAD

**Issue by ifgem** [red/red#2532]
```
>> math [10 + 10 ** 2]
== 400
>> math [10 + 10 % 2]
== 0
```
Besides, shall the math dialect be implemented using expensive copy/deep and replace operations? It makes the dialect almost useless.

**Comment by dockimbel** [comment]
That function is really not meant to support more than just basic four operators. Though, contributions to extend it are welcome (if they are not too verbose).

> Besides, shall the math dialect be implemented using expensive copy/deep and replace operations? It makes the dialect almost useless.

That function is used in the picosheet demo, and is far from useless. For the implementation, what alternative do you propose?
