### ISSUE TITLE
Compile using system/console/limit crashes GUI console on startup.

### ISSUE THREAD

**Issue by greggirwin** [red/red#2538]
`VAL_FORM_LIMIT: system/console/limit` compiles fine, but the GUI console crashes on startup. CLI console is fine.

`VAL_FORM_LIMIT: does [system/console/limit]` does not cause the problem, which makes sense.

**Comment by dockimbel** [comment]
Where exactly do you put `VAL_FORM_LIMIT: system/console/limit`? Does it still crash?

BTW, `system/console/limit` is now `system/console/size`.

**Comment by greggirwin** [comment]
The name change came after this ticket. Help code is up to date with that. 

Change https://github.com/red/red/blob/master/environment/console/help.red#L95 by removing the `does` part, so it's just:
```
VAL_FORM_LIMIT: max 0 system/console/size/x - HELP_TYPE_COL_SIZE - HELP_COL_1_SIZE - RT_MARGIN
```

**Comment by greggirwin** [comment]
Just tested, and it still crashes.

**Comment by hiiamboris** [comment]
Looks like https://github.com/red/red/issues/3714 is the same issue
