### ISSUE TITLE
char U+007F is not handled as in Rebol

### ISSUE THREAD

**Issue by meijeru** [red/red#2545]
In Rebol `U+007F (DEL)` has an alternative escape combination besides `^(del)` namely `^~`. This is not accepted by Red when in single character: `#"^~"` gives an error; in a string `^~` is treated as `~` (general escaping function of `~`). Lastly, to char! 127 does not yield `#"^(del)"` as it could be, but `#"⌂"` or some other non-printable character.

**Comment by dockimbel** [comment]
Should be fine now.
