### ISSUE TITLE
Calling "cmd dir" hangs the GUI console

### ISSUE THREAD

**Issue by pekr** [red/red#2546]
Experimenting with the CALL, the following code hangs the Red GUI console:

buffer: "" call/output "cmd dir" buffer

**Comment by dockimbel** [comment]
Works fine on Win7 64 bit.

**Comment by pekr** [comment]
Well, it does not work under Win 10. I admit the code might not make much sense, but I would not expect that particular code to hange the process ...

The reason why I tried to get "whater that works", is because I am getting this (which is unrelated to this ticket):

>> buffer: copy "" call/output "dir" buffer
*** Access Error: invalid UTF-8 encoding: #{FF393631}
*** Where: call
