### ISSUE TITLE
extract -- Runtime Error and Internal Error with negative integer as width

### ISSUE THREAD

**Issue by gltewalt** [red/red#2547]
;-- Red 0.6.2 - 2-Apr-2017/21:42:30-6:00
extract [] -3   ;--  No error with empty block
extract [1] -3  ;-- Internal Error: not enough memory   Where: append
extract [1 2 3 4 5] -2  ;-- Runtime Error 1: access violation   at: 7674980Ah

**Comment by dockimbel** [comment]
Good catch!
