### ISSUE TITLE
Text is not sharp

### ISSUE THREAD

**Issue by Immortalin** [red/red#2553]
The text created by the GUI is not as sharp as native text

**Comment by dockimbel** [comment]
The GUI is using native text... You might want to provide a code example and a screenshot at least...

**Comment by Immortalin** [comment]
![image](https://cloud.githubusercontent.com/assets/7126128/24841314/d8c2c3f0-1d36-11e7-8853-53b420b2d2a3.png)


The 17LOC spreadsheet example
The difference is pretty clear. I noticed that this problem generally occurs with SDL apps and custom widgets, most .NET/native do not have this problem. 

OS is Windows 10

**Comment by Immortalin** [comment]
Another example:

![image](https://cloud.githubusercontent.com/assets/7126128/24841348/5d195556-1d37-11e7-8af6-10c46d00ecfe.png)

**Comment by qtxie** [comment]
@Immortalin I think it causes by the font. 
* In Red PicoSheet demo, You can see thant the text `PicoSheet` in the title is more sharp than the text `A` above the cell.
* In Execl, the text `Format Painter` is not sharp, but `A` above the cell is sharp.

**Comment by dockimbel** [comment]
@Immortalin The cause of the "light blurring" is the automatic upscaling Win10 is applying to apps not declaring that they can handle high DPI. This can be disabled by the users, right click on `gui-console` executable name from the tasks bar -> Properties -> Compatibility -> "Disable display scaling on high DPI settings".

We should set it directly in the console's manifest file anyway, but we need then to adjust the sizes/offsets calculation accordingly.

**Comment by mohd-akram** [comment]
This is still the case with the latest Red. Perhaps the issue should be reopened.

**Comment by greggirwin** [comment]
@mohd-akram is it still the case if you disable high DPI scaling?

**Comment by mohd-akram** [comment]
Disabling high DPI scaling works, but users shouldn't have to do that.

**Comment by meijeru** [comment]
@dockimbel The Windows 10 setting you recommend is not available as such on my version of W10. See the attched screenshot.
![capture](https://user-images.githubusercontent.com/743227/43678256-788ce028-9810-11e8-99d3-4e718f0e6c82.PNG)

**Comment by greggirwin** [comment]
What we should do, then, is open a new ticket that references this one, based on @dockimbel's comment. i.e. FEAT: (Win10) Disable High DPI display scaling in manifest file

Would you like to do that @mohd-akram?

**Comment by greggirwin** [comment]
@meijeru, I believe it's the second/bottom one under `Change high DPI setttings`.

**Comment by meijeru** [comment]
In that case, @dockimbel 's instructions were too brief ;-)
