### ISSUE TITLE
Question: sandboxing red code

### ISSUE THREAD

**Issue by Immortalin** [red/red#2557]
If Red is used as a scripting language for e.g. a game, how do I restrict its features to prevent unauthorized access etc.?

**Comment by dockimbel** [comment]
Please use one of our communication channels for asking questions:
* the Red [mailing-list](http://groups.google.com/group/red-lang?hl=en).
* our Gitter [chat room for newcomers](https://gitter.im/red/welcome).

This issue tracker is only for reporting issues/bug.
