### ISSUE TITLE
to pair! from floats > max integer give unexpected results

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#2560]
to pair! will always result in ```-2147483648x-2147483648``` when the value is a float that is greater than the maximum integer is provided:

```text
>> to pair! 2147483648.0
== -2147483648x-2147483648
>> to pair! 2147483649.0
== -2147483648x-2147483648
```

**Comment by PeterWAWood** [comment]
Note: this will be automatically corrected once pair! values can be float!

**Comment by dockimbel** [comment]
Currently, such operation will result in an undefined result, and as it should be automatically corrected once pair values can be floats, I will close it with a deferred status.
