### ISSUE TITLE
Console freezes on macOS if shift & right-arrow or shift & left-arrow pressed.

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#2575]
The console under macOS freezes if either shift + left-arrow or shift + right-arrow are pressed.

**Comment by PeterWAWood** [comment]
The console no longer freezes when typing shift+right-arrow or shift+left-arrow.

typing shift+left-arrow results in C being typed into the console
typing shift+rigt-arrow results in D being typed into the console

In 0.6.1, the Red console behaved normally (for a macOS terminal app). shift+left-arrow selecting the character to the left of the cursor (retaining previous selections). shift+right-arrow  selecting to the right of the cursor.

**Comment by qtxie** [comment]
@PeterWAWood Strange... We haven't implement `shift+arrow` selecting in the CLI console, it should not work in any version.

**Comment by PeterWAWood** [comment]
Perhaps my memory is failing me.

**Comment by michaeldesu** [comment]
I concur with what Peter observed (C&D appearing in console view, which is better than crash, but ideally shouldn't show those chars). Seen in red-14apr17-3ff52f9.
