### ISSUE TITLE
SIGN? doesn't support percent!

### ISSUE THREAD

**Issue by greggirwin** [red/red#2576]
```
>> sign? 1%
*** Script Error: sign? does not allow percent! for its <anon> argument
*** Where: sign?
```
But the spec uses `number!`, which contains `percent!`

**Comment by greggirwin** [comment]
May just need to add TYPE_PERCENT to sign?* in %natives.reds.

**Comment by meijeru** [comment]
The comment to the code in %natives.red says: add  [...] pair! How would one define the sign of a pair?

**Comment by greggirwin** [comment]
It could return a pair value itself, e.g. 10x50 would return 1x1, -5x10 would return -1x1, etc.

**Comment by meijeru** [comment]
Yes, that makes sense. It goes in the same direction of some of my WISH issues asking for extension of various built-in functions to suitable composite datatypes.

**Comment by greggirwin** [comment]
This applies to negative? and positive? as well.

**Comment by greggirwin** [comment]
Fix merged. Should be able to close this now.
