### ISSUE TITLE
cannot select character from file! or url! value using /<integer>

### ISSUE THREAD

**Issue by meijeru** [red/red#2578]
Compare:
```
>> s: "ab"
== "ab"
>> s/1
== #"a"
>> f: %ab
== %ab
>> f/1
== %ab/1
>> u: a:b
== a:b
>> u/1
== a:b/1
```
The interpretation of the `/...` expression as an _extension_ of the file or url path is sometimes useful (although `[re]join` will also work), but with an integer the system breaks down...

**Comment by qtxie** [comment]
Yes. I think we should remove this feature. 
1. It's easy to misused. (I write some buggy code becuase of that recently. 😓 )
2. It makes the path rule more complex.

**Comment by dockimbel** [comment]
No `rejoin` would not work, as that path extension is handled in a *smart* way to avoid duplicate slashes. 

Slash characters are an intrinsic part of files and urls (unlike for other `any-string!` series), so having a special path handling is natural, as it gives a useful extra feature which is commonly used for those types. It is a feature supported by all Rebol versions, so for all those reasons, we should keep it.

**Comment by greggirwin** [comment]
I agree with Doc here. It's important to note, but also valuable.
