### ISSUE TITLE
[gui][draw] Draw on image doesn't trigger update

### ISSUE THREAD

**Issue by maximvl** [red/red#2581]
If you run this code and click button - image will not change:
```
view [img: image 100x100 button "click" on-click [
    draw img/image [ fill-pen black box 0x0 50x50 ]
    show img
    ]
]
```

However if just one byte is reassigned it will work:
```
view [img: image 100x100 button "click" on-click [
    draw img/image [ fill-pen black box 0x0 50x50 ]
    img/image/1: img/image/1
    show img
    ]
]
```

I guess `draw` changes image in the way that `img` doesn't know it was changed, so update doesn't do anything.

**Comment by DideC** [comment]
I also encounter that issue during the development of my heart animation. But forgot to make an issue about :-(

**Comment by qtxie** [comment]
Fixed in the latest version.
