### ISSUE TITLE
[WISH] reflect on datatype!

### ISSUE THREAD

**Issue by maximvl** [red/red#2583]
It would be nice to have `reflect` working on `datatype!` so it would be possible to get all datatype fields, if there are any. Something like:
```
>> keys-of pair!
[x y] 
```
This would allow things like auto-completion, help and runtime loops over fields, checks, etc.

**Comment by meijeru** [comment]
There are exactly four datatypes to which this applies, and each has a small number of fixed "fields": time! pair! email! and image!. In my view, reflection is for cases where the number of fields and their names are not fixed in advance and user-definable. See also #2527.

**Comment by dockimbel** [comment]
You can find all those accessors listed per datatype in: `system/catalog/accessors` since 0.6.3.
