### ISSUE TITLE
macOS encoding problem with simple-io

### ISSUE THREAD

**Issue by x8x** [red/red#2590]
Here is a wired encoding behaviour:
```
   a: {Ingénierie}
;   "Ingénierie"
  write to-file a ""
  b: read %.
;   [%Ingénierie]
  read b/1
;   ""
  a: {620 Ingénierie}
;   "620 Ingénierie"
  write to-file a ""
  b: read %.
;   [%620%20Inge%00nierie %Ingénierie]
  read b/1
*** Access Error: cannot open: %620%20Inge%00nierie
*** Where: read
```
Also, it would be nicer to have:
`%"file name with space"`
instead of url-escaped:
`%file%20name%20with%20space`
in the result.

**Comment by dockimbel** [comment]
The URL-escaped version is the proper file format, the `%"..."` form is only accepted by the lexer.

**Comment by x8x** [comment]
Thank you! Works correctly now. 👍
