### ISSUE TITLE
DOC: various peculiarities of make bitset!

### ISSUE THREAD

**Issue by meijeru** [red/red#2595]
1. `charset` is shorthand for `make bitset!` except it does not cover `make bitset! <binary>`. This does make sense since `charset` suggests we deal with code point numbers, but it is useful to point out.
2. `charset 5` makes a single-byte empty bitset, `charset #"^E"` makes `#{04}`, BUT both `charset [5]` and `charset [#"^E"]` make `#{04}`. In other words, `make bitset! <integer>` is treated as storage reservation, as with all `series!` values, although `bitset!` does not belong to `series!`. It is questionable which kind of (in)consistency is less confusing for the user. In any case, the chosen solution has to be documented...
3. `charset [32 - #"Z"]` is allowed, in other words, integers and code points may be freely mixed in the spec block.

**Comment by meijeru** [comment]
Point 3 is solved by the fixes to #2587

**Comment by dockimbel** [comment]
Issue moved to [red/docs #194](https://github.com/red/docs/issues/194) via [**ZenHub**](https://www.zenhub.com/)
