### ISSUE TITLE
make vector! <integer>  produces vector of all zeroes instead of an empty one

### ISSUE THREAD

**Issue by meijeru** [red/red#2596]
With other `series!` types, `make <type> <integer>` just produces an empty series with the prescribed number of components allocated. Only with `vector!`  are the components pre-initialized to zero.

**Comment by meijeru** [comment]
One more exception: `make image! <pair>` makes a non-empty white image... However, image! does not allow `insert`,so that makes sense.

**Comment by meijeru** [comment]
`make <type> <integer>` yields an empty value for the following composite types: `any-block!`, `any-string!`,  `binary` and `map!`. If fails for `image!` and `any-object!`, and behaves differently for `vector!`.

**Comment by dockimbel** [comment]
Same as in Rebol3, you want your vector pre-filled with zeros, so you can write values at different places directly, without any additional construction steps. Will be the same for the future `matrix!` datatype (which could or could not be derivated from `vector!`).

**Comment by meijeru** [comment]
How do you make a vector of floats which are all zero?? I accept the utility of this facility, but it seems strange that it is available only for the default element type.

**Comment by qtxie** [comment]
I got a bite by a bug caused by this difference today. Is the need to pre-filled it really stronger than make it consistent with the other series datatypes? IMHO, If someone want it to be pre-filled, they can easily write a simple function to do it. Just one line of code. And I don't the performance would be a problem in this case.

**Comment by 9214** [comment]
I'd say pre-filling should be handled only with `block!` prototype, e.g.:
```red
>> make vector! [integer! 32 [1 2 3]]
== make vector! [1 2 3]
>> make vector! [percent! 64 3]
== make vector! [0% 0% 0%]
```
