### ISSUE TITLE
compiler: wired crash on redefining functions and returning result

### ISSUE THREAD

**Issue by x8x** [red/red#2597]
Both examples belows works fine when compiled:
```
now*: :system/words/now
now: func [/time][do [now*/time]]
a: now/time
print a
```
```
trim*: :system/words/trim
trim: func [string /tail][do [trim*/tail string]]
a: trim/tail {123}
print a
```

But, adding `return` as here:
```
now*: :system/words/now
now: func [/time][return do [now*/time]]
a: now/time
print a
```
```
trim*: :system/words/trim
trim: func [string /tail][return do [trim*/tail string]]
a: trim/tail {123}
print a
```
will crash on execution.
Strangely, these will work:
```
now*: :system/words/now
now: func [/time][return do [now*/time]]
print now/time
```
```
trim*: :system/words/trim
trim: func [string /tail][return do [trim*/tail string]]
print trim/tail {123}
```

**Comment by x8x** [comment]
Not `refinements` related as this will crash as well:
```
trim*: :system/words/trim
trim: func [string][return do [trim* string]]
a: trim {123}
print a
```

**Comment by hiiamboris** [comment]
@x8x can you still reproduce the crash? I think it was solved.. somehow...

**Comment by x8x** [comment]
Closing this, all above crashing examples runs fine on latest Red.

**Comment by hiiamboris** [comment]
We should write a regression test for this though.

**Comment by theSherwood** [comment]
@x8x Any idea what version of the compiler you were using at the time? I'm using one from Apr 17, 2017 (1c2005d066cb67b2b1a78c317af346ed789489e7) and I'm unable to replicate the crash for testing.
