### ISSUE TITLE
`map!` should be excluded from `insert` allowed datatypes

### ISSUE THREAD

**Issue by toomasv** [red/red#2607]
```
>> probe :insert
make action! [[
    {Inserts value(s) at series index; returns series past the insertion} 
    series [series! bitset! map!] 
...
```

But map! is not allowed as series:

```
>> insert #() [a b] 
*** Script Error: insert does not allow map! for its series argument
*** Where: insert
```

**Comment by dockimbel** [comment]
Thanks! The `map!` word just need to be removed from the list of accepted types for `insert` (and `append` too). Would you like to submit a Pull Request with those changes?

**Comment by toomasv** [comment]
I have never pulled a request. What should I do?

**Comment by nc-x** [comment]
@toomasv Fork this repo. Do the changes in your fork. There will be a button "New Pull Request", click on that and tada...

**Comment by dockimbel** [comment]
Two ways to do it:
* If you don't have a git client installed and if it's a minor change in a single file, you can just "fork" the red/red repository using the [Fork] button on github, then navigate in your copy of the red repo to the right file, click on it, then on file's header, there is a pen icon ("Edit this file"), click on it. Then just make the changes and save it. After that you need to make the Pull Request, which is explained [here](https://help.github.com/articles/creating-a-pull-request/).
* Using a git client, clone the red/red repo, make the changes to your fork, push it online, then create a Pull Request as explained [here](https://help.github.com/articles/creating-a-pull-request/).

**Comment by toomasv** [comment]
I submitted the Pull Request. Please comment if it was done correctly.

**Comment by dockimbel** [comment]
Thanks!
