### ISSUE TITLE
request-dir/title "^" and "&" characters not displayed

### ISSUE THREAD

**Issue by 9214** [red/red#2610]
Playing around with file I/O I discovered this:

`request-dir/title {Usual title, nothing criminal}`

![default](https://cloud.githubusercontent.com/assets/15716466/25293921/524964ea-26f6-11e7-86c9-a8c0fadb7462.png) 

Everything's fine, but see what happens then I use **^** and **&**:
`request-dir/title {Nietzsche rocks! ^_^ He wrote "Beyond Good & Evil"}`

![default](https://cloud.githubusercontent.com/assets/15716466/25294140/490cd5fa-26f7-11e7-9667-ebbec1dc8d24.png)

I don't know `View` that much to test it with similar GUI elements, perhaps it's not only `request-dir`-related. 😕 
Also, there might be more such glitchy characters out there.

**Comment by qtxie** [comment]
@9214 
- `^` has special meaning in Rebol/Red string, you need to type this `^^` to insert a caret. [More details here](http://www.rebol.com/r3/docs/datatypes/string.html).
- `&` is used for underline the character on Windows. We'll see how to deal with it as the other platforms no such feature.

**Comment by 9214** [comment]
Thanks for clarifying @qtxie !

`request-dir/title "^^ &Underline"`

![default](https://cloud.githubusercontent.com/assets/15716466/25304276/9beb03ec-277d-11e7-8160-d31f6ebc8daf.png)

Meanwhile I'll stick to `and` instead of `&` :^)

**Comment by DideC** [comment]
You can display an & by doubling it in the string:
`request-dir/title "^^ &&Underline"`

**Comment by 9214** [comment]
Guess it can be marked as resolved, thanks @DideC .

**Comment by endo64** [comment]
I noted this on Wiki [Request-file-and-Request-dir](https://github.com/red/red/wiki/%5BDOC%5D-Request-file-and-Request-dir), this issue can be closed.

**Comment by greggirwin** [comment]
Thanks @endo64 !
