### ISSUE TITLE
Compiled code crashes wine

### ISSUE THREAD

**Issue by maximvl** [red/red#2615]
If you compile & run this snippet:
https://gist.github.com/maximvl/81f31f26b49a7a3a5891b9a63f47171a

and click `run` button it will crash with:
```
> wine haiku.exe 
fixme:dwmapi:DwmIsCompositionEnabled 0x32fdc8
*** Error in GetClassInfoEx

*** Runtime Error err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x414b00
```

It crashes on Windows as well.

**Comment by dockimbel** [comment]
It compiles and works fine with Windows 7 and latest commit.
