### ISSUE TITLE
pick <time> with non-integer index crashes

### ISSUE THREAD

**Issue by meijeru** [red/red#2624]
The out-of-range test is guaranteed to fail, since it uses `all` instead of `any` 😸 . Therefore the next line is taken and this causes a crash. See `%time.reds` at lines 356-357
```
if all [index < 1 index > 3][fire [TO_ERROR(script out-of-range) boxed]]
push-field tm index
```

**Comment by dockimbel** [comment]
Thanks for the analysis!
