### ISSUE TITLE
In making an error based on the integer code, the error number seems off by 2

### ISSUE THREAD

**Issue by meijeru** [red/red#2628]
`make error! <integer>` indexes `system/catalog/errors` as follows: the integer value divided by 100 gives a 0-origin index in the fields of `system/catalog/errors` (`0 = throw`, `1 = note` etc.), and the value modulo 100 gives an index in the fields of the sub-object (`system/catalog/errors/throw` etc). However, every such sub-object has two fixed fields `code` and `type`, and  these are counted for the 0-origin index. Thus `make error! 503` is the _second_ error in group `500`, whereas one would think it should be nr. `501`.

**Comment by meijeru** [comment]
Related: when the system produces an error, the code is not filled in.
```
>> probe try [1 / 0]
make error! [
    code: none            ; should be 400 (or 402???)
    type: 'math
    id: 'zero-divide
    arg1: none
    arg2: none
    arg3: none
    near: none
    where: '/
    stack: 44467008
]```

**Comment by meijeru** [comment]
Also related: `make error! <integer>`  when the integer value is a multiple of `100` crashes.

**Comment by greggirwin** [comment]
Up to 700 it seems. That's a funny one.

**Comment by dockimbel** [comment]
All the above issues should be fixed now.
