### ISSUE TITLE
make error! <integer> does not bind the error id to the message

### ISSUE THREAD

**Issue by meijeru** [red/red#2629]
```
>> e: make error! 402
*** Math Error: attempt to divide by zero
*** Where: ???
>> get e/id
*** Script Error: zero-divide has no value
*** Where: get
>> e: try [ 1 / 0]
*** Math Error: attempt to divide by zero
*** Where: /
>> get e/id
== "attempt to divide by zero"
```

**Comment by meijeru** [comment]
I don't understand why in the first case the error message still comes out!

**Comment by dockimbel** [comment]
> I don't understand why in the first case the error message still comes out!

If an error! value is the last value evaluated in the console, it will get displayed by the console in its FORMed version.
