### ISSUE TITLE
Inconsistency in map!: none is allowed as value upon making

### ISSUE THREAD

**Issue by meijeru** [red/red#2631]
```
>> m: #(a: none)
== #(
    a: none
)
>> m
== #(
    a: none
)
>> m/a
== none
>> put m 'a none
== none
>> m
== #()
```
I would think that `#(a: none)` should yield `#()` straight away!

**Comment by PeterWAWood** [comment]
@meijeru It is understandable as using the literal syntax you have set a to a word! value (none) rather than a none! value.
```text
red>> m: #(a: none)
== #(
    a: none
)
red>> type? m/a
== word!
red>> m: #(a: #[none])
== #(
)
```

**Comment by PeterWAWood** [comment]
This is consistent with the behaviour demonstrated by make:
```text
red>> m: make map! [a: none]
== #(
    a: none
)
red>> m: make map! compose [a: (none)]
== #(
)
```

**Comment by PeterWAWood** [comment]
This behaviour is consistent with that of ```block!```  but differs from the of ```object!``` where the spec block is evaluated.

**Comment by meijeru** [comment]
I stand corrected and will close. It should be taken into account for documentation purposes, though.

**Comment by PeterWAWood** [comment]
@meijeru Yes, it should definitely be clear documented. (I have been caught out by this many times.)
