### ISSUE TITLE
DOC: time! value is allowed as key in map 

### ISSUE THREAD

**Issue by meijeru** [red/red#2632]
The section on map! type in the Gitbook leaves this out. The allowed key values may be summarized as `scalar! all-word!` and `any-string!`.

**Comment by dockimbel** [comment]
You should submit tickets about red/docs repository to its own issue tracker.

**Comment by dockimbel** [comment]
Issue moved to [red/docs #19](https://github.com/red/docs/issues/19) via [**ZenHub**](https://www.zenhub.com/)
