### ISSUE TITLE
make error! [<type> <id>] does not bind the error type and id to the message

### ISSUE THREAD

**Issue by meijeru** [red/red#2633]
See also #2629
```
>> e: make error! [math zero-divide]
*** Math Error: attempt to divide by zero
*** Where: ???
>> e/id
== zero-divide
>> get e/id
*** Script Error: zero-divide has no value
*** Where: get
```

**Comment by meijeru** [comment]
Same issue when using object-spec:
`e: make error! [type: 'math id: 'zero-divide]

**Comment by meijeru** [comment]
Same issue when using `cause-error` which calls `make`.

**Comment by dockimbel** [comment]
Why should those symbols be bound to the message? You can easily retrieve the message already using a path accessor:
```
e: make error! [math zero-divide]
system/catalog/errors/(e/type)/(e/id)

== "attempt to divide by zero"
```
Given how rare such retrieving would be done in user code and how easy it is already to get the message, I don't think it is worth adding extra code in the runtime library for creating such bindings.
