### ISSUE TITLE
make does not allow an error value as first argument

### ISSUE THREAD

**Issue by meijeru** [red/red#2640]
In expressions of the form `make <type> <spec>`, `<type>` may evaluate to a type (`datatype!` value) or to a value ("prototype") of the desired type. In most cases, the protype serves only to indicate the type, but this is not so (and for good reasons) for objects, where the prototype is _extended_ by the spec. But in the case of `make error!` an error value is not even allowed as first argument!

**Comment by dockimbel** [comment]
Works fine here:
```
>> e: try [1 / 0] none
== none
>> type? e
== error!
>> make e [type: 'script id: 'invalid-arg arg1: 0]
*** Script Error: invalid argument: 0
*** Where: ??? 
```
