### ISSUE TITLE
Path notation cannot be used on email! values

### ISSUE THREAD

**Issue by gltewalt** [red/red#2654]
```
>> series? s: @gltewalt
== true
>> s/1
*** Script Error: cannot access 1 in path [script invalid-path]
*** Where: catch
```

**Comment by PeterWAWood** [comment]
It seems the issue is with path notation:
```text
>> pick @gltewalt 1
== #"@"
>> pick @gltewalt 6
== #"w"
>> s: @gltewalt
== @gltewalt
>> pick s 1
== #"@"
>> s/1
*** Script Error: cannot access 1 in path [script invalid-path]
*** Where: catch
```

**Comment by meijeru** [comment]
@b is recognized as email by the interpreter, but NOT by the compiler: %lexer.r requires at least one character before the @. Apparently %lexer.red has a different definition. That is an additional issue.

**Comment by gltewalt** [comment]
```
email-rule: [
    s: some [ahead email-end break | skip] #"@"
    any [ahead email-end break | skip] e: (type: email!)
]
```

**Comment by dockimbel** [comment]
> @b is recognized as email by the interpreter, but NOT by the compiler: %lexer.r requires at least one character before the @. Apparently %lexer.red has a different definition. That is an additional issue.

The lexer is left unfinished for email! rules, until we add ref! type (planned for 0.6.4).
