### ISSUE TITLE
Request split accept none to allow for "exploding" series!

### ISSUE THREAD

**Issue by gltewalt** [red/red#2655]
```
split "Red" none
== [#"R" #"e" #"d"]
```

To behave like:
```
>> explode!: function [str [series!]] [
[        collect [foreach c str [keep c]]
[        ]
== func [str [series!] /local c][collect [foreach c str [keep c]]]
>> explode! "Red"
== [#"R" #"e" #"d"]
>> explode! @gltewalt
== [#"@" #"g" #"l" #"t" #"e" #"w" #"a" #"l" #"t"]
```

**Comment by endo64** [comment]
I'm not sure if this functionality should be added to `split` function, any thoughts @greggirwin ? Anyways this issue should go to REP as a wish.

And here is a shorter explode function:
`explode: func [s] [parse s [collect any [keep skip]]]`

**Comment by hiiamboris** [comment]
Check this out ☺
```
>> extract/into "Red" 1 []
== [#"R" #"e" #"d"]
```

**Comment by endo64** [comment]
@hiiamboris `extract/into` looks shorter but actually it is a mezz and much longer than above `explode` function.

```
width: max 1 width
if pos [series: at series pos]
unless into [output: make series (length? series) / width]
while [not tail? series] [
	append/only output series/1
	series: skip series width
]
output
```

@gltewalt I think we are good to close this ticket, but I'm wondering about below difference, may be we should follow its conversation on gitter or in a another ticket:

```
>> extract/into "Red" 1 []
== [#"R" #"e" #"d"]
>> extract "Red" 1
== "Red"
```
