### ISSUE TITLE
Programming error and inconsistency in comparing integer, float etc.

### ISSUE THREAD

**Issue by meijeru** [red/red#2656]
`float!` numbers can be compared to `time!` values but there is a programming error in `%float.reds`:
```
			TYPE_TIME
			TYPE_PERCENT
			TYPE_FLOAT [right: value2/value]

```
The  `struct!` member in `red-time!` is called `time` not `value`.
In any case, `integer!` values cannot be compared to `time!` values. There is no symmetry.

**Comment by dockimbel** [comment]
There is no programming error there, the different structs for `time!`, `percent!` and `float!` are overlapping for their float value on purpose, to be able to access that field using the same accessor.

**Comment by dockimbel** [comment]
Comparisons between `time!` and single-dimension scalar values should result in an error.

**Comment by meijeru** [comment]
At the moment, such comparisons result in `false`. I seem to be remember that you once said that type incompatibility in comparisons need not yield an error, `false` is enough. Is that right?

**Comment by dockimbel** [comment]
Equality and inequality tests should always return a `logic!` result. Other comparisons can return errors if the  comparison is meaningless or impossible.

**Comment by dockimbel** [comment]
Actually, comparison between `time!` and single-dimension scalar values is possible, because `time!` values can be converted to `integer!` or `float!` values (and back to `time!`) using seconds as the base unit.

So, it works as expected currently.

**Comment by meijeru** [comment]
I beg to differ
```
>> 3600 = 1:00:00
== false
>> 1:00:00 = 3600
== true
```
Thus it is not solved!

**Comment by dockimbel** [comment]
You should have reported that in #2662 rather...
