### ISSUE TITLE
Strange algorithm for comparing objects

### ISSUE THREAD

**Issue by meijeru** [red/red#2658]
On looking at `object/compare` I notice the following. For (strict) equality it is necessary that the field names are pairwise identical. For the field values it is allowed that the types are different in the following sense: both in `any-word!` (but not `refinement!`) or one `integer!` and the other `float!` (but not `percent!`).
This makes no sense for `COMP_STRICT_EQUAL` since that requires in any case that the types are equal, but for `COMP_EQUAL` it seems a rather arbitrary condition. In direct comparison between two values the options for "compatible" types are:
- char! + integer! See issue #2650
- number!
- any-word! + refinement! (note the absence of issue!)
- any-string!
- any-object! See issue #2657  —

**Comment by dockimbel** [comment]
I don't understand where you see a problem (please provide a code example), it works as expected to me:
```
a: object [f: 1]
b: object [f: 1.0]

a = b
;== true
a == b
;== false

a: object [f: 'a]
b: object [f: quote :a]

a = b
;== true
a == b
;== false
```

**Comment by meijeru** [comment]
This leaves the anomaly that `1` and `100%` are not considered equal under `=` whereas `1` and `1.0` are. Likewise `1.0` and `100%` are not considered equal. What is against including `percent!` here?

**Comment by dockimbel** [comment]
```
>> 1 = 100%
== true
>> 1.0 = 100%
== true
>> 1.0 == 100%
== false
>> 1 == 100%
== false
```
Seems it was all corrected a while ago. So, I'll close this ticket.

**Comment by meijeru** [comment]
No! I meant they are not equal when they are in fields of an object. That was the whole point!

**Comment by dockimbel** [comment]
It's fixed now.
