### ISSUE TITLE
Pairs are wrongly compared for greater etc.

### ISSUE THREAD

**Issue by meijeru** [red/red#2660]
The algorithm used is suitable for (in)equality but NOT for greater than etc.
```
>> 1x2 > 2x1
== true
```
 This is because `y` is first tested and if there is a difference, that is taken for the whole.

**Comment by dockimbel** [comment]
Which algorithim do you suggest for that? We could calculate the corresponding vector length for each pair, and compare it, though I'm not certain this would be the best option.

**Comment by meijeru** [comment]
In contrast to tuples, which can be compared "lexicographically" I don't see a sensible algorithm for pairs. Neither do I see a use case. So the best could be to forbid this comparison.

**Comment by geekyi** [comment]
1. Going multidimensional for values of more than one dimension:
```red
== falseXtrue
```
or using ranges, `[false true]` etc. This is the approach taken by some array programming languages (J).
I like this way

2. Giving a `logic!` when all the individual values satisfy, and something akin to `none` when not:
```red
>> 2x2 > 1x1 ; strictly  true
== true
>> 1x1 > 2x2 ; strictly  false
== false
>> 1x2 = 1x2
== true
>> 1x2 > 2x1 ; indeterminate
== none
>> 2x1 > 1x2
== none
```

3. Using the same gradient as `x = y` line to determine what is greater and what is less. Probably too obscure to be useful tho.
Any pairs which have the same

**Comment by greggirwin** [comment]
Geekyi's idea is interesting. Need to think about how useful it would be though. Rebol doesn't allow comparisons, so I think we can leave it out. There's no clear answer, other than what geekyi suggests. 

On a related note, Rebol *does* support `max/min`, which is nice.
```
>> max 1x2  2x1
== 2x2
```

**Comment by greggirwin** [comment]
It occurred to me that a use case for this is a block with pairs as keys, e.g., representing a sparse table, which would lead to sorting like tuples.

**Comment by meijeru** [comment]
Essentally, you are then using pairs as 2-element tuples, which would suggest lexicographic comparison (x first, then y). That is easy to implement.

**Comment by dockimbel** [comment]
Comparison for pairs was modified to adopt lexicographic order.
