### ISSUE TITLE
comparison of time and integer is inconsistent

### ISSUE THREAD

**Issue by meijeru** [red/red#2662]
```
>> to-integer 1:00
== 3600
>> 1:00 = 3600
== false
>> 1:00 > 3600
== true
```
If `time!` and `integer!` values cannot be compared for equality, it should be forbidden to compare them for greater etc.

**Comment by dockimbel** [comment]
Equality testing (`=` and `==`)  on `time!` with another single-dimension scalar value should return `false`, `<>` should return `true`. Other comparisons should return an error.

**Comment by dockimbel** [comment]
Seems it has been fixed:
```
>> 1:00 = 3600
== true
>> 1:00 > 3600
== false
>> 1:00 >= 3600
== true
```
