### ISSUE TITLE
comparison of objects is not lexicographic

### ISSUE THREAD

**Issue by meijeru** [red/red#2663]
The programming of object comparison seems to ensure lexicographic ordering for the field values.
But see this:
```
>> o: object [a: 1]
== make object! [
    a: 1
]
>> o < object [a: 1 b: 0]
== true                 ;; seems OK
>> o < object [a: 0 b: 0]
== true                 ;; should be false?
```
It looks like the "shorter" object (fewer fields) always is seen as smaller.

**Comment by dockimbel** [comment]
Right, number of fields is the first property compared.
