### ISSUE TITLE
HELP doesn't like `parse` spec.

### ISSUE THREAD

**Issue by greggirwin** [red/red#2667]
The `callback` param has a complex type spec, rather than a datatype or typeset.
```
callback [function! [
        event [word!] 
        match? [logic!] 
        rule [block!] 
        input [series!] 
        stack [block!] 
        return: [logic!]
    ]] 
```
`Help` shows the information correctly, but also emits its "Looks like we have a bad type spec:" debug message. 

Right now, the param type check uses `[some [datatype! | typeset!]]` as its rule. Is the correct solution to add a `function! + spec` check there, and (knowing it's limited today) that args could theoretically nest specs deeply? Or should `help` just check for `'function! block!` and leave it at that?

**Comment by dockimbel** [comment]
I think `'function! block!` is enough for now.

**Comment by greggirwin** [comment]
OK, I'll go with that. Thanks.

**Comment by greggirwin** [comment]
This is complete, in a previous PR.
