### ISSUE TITLE
SAVE does not accept binary! as destination

### ISSUE THREAD

**Issue by meijeru** [red/red#2668]
```
USAGE:
    SAVE where value /header header-data /all /length /as format
DESCRIPTION: 
    Saves a value, block, or other data to a file, URL, binary, or string 
    SAVE is a function! value
ARGUMENTS:
    where    [file! url! string! binary! none!] "Where to save"
    value     "Value(s) to save"

>> save "" 1
== "#{31}"
>> save #{} 1
*** Script Error: suffix? does not allow binary! for its path argument
*** Where: suffix?
```
In the case of a string destination, I would have expected a molded result (`"1"`) but NOT a string containing a binary UTF-8 encoded value! In the case of a binary destination, I would have expected a plain binary value (here `#{31}` ) and not an error.

**Comment by greggirwin** [comment]
We need to determine the behavior for non-file values with `suffix?`. Url and email are pretty clear, as the same, but strings...tough call, and binary should return none.

**Comment by greggirwin** [comment]
@meijeru, right you are. `Save` should shortcut in the case of binary, as there is *no* codec needed.

**Comment by meijeru** [comment]
`save` also allows `none` as an argument (why?) and also this errors out on `suffix?`

**Comment by greggirwin** [comment]
"Why?" is a good question, but it's clearly intentional, as the `none` case is handled explicitly in the code. It basically becomes a no-op.

**Comment by endo64** [comment]
`save` accepting `none` is like writing `/dev/null`, but I see no use for it in Red. I'm for removing `none` from spec (and the code related).
