### ISSUE TITLE
Char in numeric form is not supported for values from 0 to 9

### ISSUE THREAD

**Issue by Oldes** [red/red#2671]
```
>> print "^(0)"
(0)
>> print "^(10)"

>> to-char #"^(10)"
== #"^P"
>> to-char #"^(0)"
*** Syntax Error: invalid char! at {#"^^(0)"}
*** Where: do
```

Just for comparison, in Rebol:
```
>> to-char #"^(0)"
== #"^@"
```

**Comment by meijeru** [comment]
The lexer requires an *even* number of hex digits inside the parentheses. That is all.

**Comment by 9214** [comment]
Fixed in `fast-lexer` branch:
```red
>> {^(0) ^(1) ^(2) ^(3) ^(4) ^(5)}
== "^@ ^A ^B ^C ^D ^E"
```

**Comment by meijeru** [comment]
May be closed now!

**Comment by hiiamboris** [comment]
Let's wait some tests before closing.

**Comment by theSherwood** [comment]
Just want to double-check before I write tests for this...

Is this expected behavior?
```
>> {^(0) ^(1) ^(2) ^(3) ^(4) ^(5) ^(6) ^(7) ^(8) ^(9) ^(10)}
== "^@ ^A ^B ^C ^D ^E ^F ^G ^H ^- ^P"
>> print {^(0) ^(1) ^(2) ^(3) ^(4) ^(5) ^(6) ^(7) ^(8) ^(9) ^(10)}
        
>> print "^@ ^A ^B ^C ^D ^E ^F ^G ^H ^- ^P"
        
```
`print` appears to be printing a quantity of spaces in the above cases.

`Red 0.6.4 for macOS built 17-Jul-2020/12:48:27-06:00 commit #ea1d139`

**Comment by hiiamboris** [comment]
I suggest you test the string vs expected only. We can't test `print` anyway. That it prints spaces instead of control chars in GUI console is probably OK.
In CLI console:
```
>> print {^(0) ^(1) ^(2) ^(3) ^(4) ^(5) ^(6) ^(7) ^(8) ^(9) ^(10)}
  ☺ ☻ ♥ ♦ ♣ ♠    ►                                                
```

**Comment by theSherwood** [comment]
So the following test currently fails on master:

```
	--test-- "#2671"
		t2671: form {^(0) ^(1) ^(2) ^(3) ^(4) ^(5) ^(6) ^(7) ^(8) ^(9) ^(10)}
		--assert equal? "^@ ^A ^B ^C ^D ^E ^F ^G ^H ^- ^P" t2671
```

If you `probe` out `t2671` you get:

```
"(0) (1) (2) (3) (4) (5) (6) (7) (8) (9) ^P"
```

This is in contrast to the latest build of the console in which you have this:

```
>> probe form {^(0) ^(1) ^(2) ^(3) ^(4) ^(5) ^(6) ^(7) ^(8) ^(9) ^(10)}
"^@ ^A ^B ^C ^D ^E ^F ^G ^H ^- ^P"
== "^@ ^A ^B ^C ^D ^E ^F ^G ^H ^- ^P"
```

Why would we be having different behavior between the source of master (which I believe is used to run the tests) and the latest build of that source?

**Comment by 9214** [comment]
@theSherwood Red is both compiled and interpreted language, and the behavior of compiler and interpreter usually differ between each other, esp. in processing literal forms.

```red
probe {^(0) ^(1) ^(2) ^(3) ^(4) ^(5) ^(6) ^(7) ^(8) ^(9) ^(10)}
```
Compiled:
```red
"(0) (1) (2) (3) (4) (5) (6) (7) (8) (9) ^P"
```
Interpreted:
```red
"^@ ^A ^B ^C ^D ^E ^F ^G ^H ^- ^P"
```

So compiler needs to be updated too.

**Comment by greggirwin** [comment]
> the behavior of compiler and interpreter usually differ between each other

To clarify, they _may_ differ, being out of sync or because of compiler limitations, but the _goal_ is for them to match.

**Comment by greggirwin** [comment]
Hence, we need to run tests both interpreted and compiled.

**Comment by theSherwood** [comment]
So just to clarify, this issue requires work to be done to make the behavior of the compiler consistent with the behavior of the interpreter before any more testing makes sense.

**Comment by hiiamboris** [comment]
That should be the best course of action, yes.
