### ISSUE TITLE
char! pair!  or tuple!  value + a vector is a NO-OP

### ISSUE THREAD

**Issue by meijeru** [red/red#2675]
These operations are allowed, but they have no effect; the result is the vector value unchanged. The converse (adding a vector to a char! value etc.) is explicitly forbidden.

**Comment by dockimbel** [comment]
Current state:
```lisp
>> #"a" + make vector! [1]
*** Script Error: vector! type is not allowed here
*** Where: +
*** Stack: 
>> 1x2 + make vector! [1]
*** Script Error: vector! type is not allowed here
*** Where: +
*** Stack: 
>> 1.2.3 + make vector! [1]
*** Script Error: vector! type is not allowed here
*** Where: +
*** Stack: 
```

**Comment by dockimbel** [comment]
Those operations are not yet implemented. A suitable error is now displayed if such operations are attempted.
