### ISSUE TITLE
offset? allows comparison of arbitrarily different series

### ISSUE THREAD

**Issue by meijeru** [red/red#2680]
All `offset?` does is `subtract index? series2 index? series1`. It would make more sense to check that
`(head series2) = (head series1)` because now we can do the following:
```

>> s1: next next "abcdefg"
>> s2: at [1 2 3 4 5 6 7 8] 5
>> offset? s1 s2
== 2  ;; what does it mean??? 
```

**Comment by dockimbel** [comment]
Adding extra checking would slow down performances for normal usages, and would prevent usages we don't think about, but which could come handy in some algorithms.

Less is more. ;-)

**Comment by meijeru** [comment]
OK but it could lead to strange results by accident. Anyhow, I will close.
