### ISSUE TITLE
normalize-dir does not invoke clean-path if argument starts with /

### ISSUE THREAD

**Issue by meijeru** [red/red#2690]
```
>> what-dir
== %/C/Projects/Red/programs/
>> normalize-dir %../test
== %/C/Projects/Red/test/
>> normalize-dir %/../test
== %/../test/
```
It would perhaps be useful to re-define normalize-dir as clean-path/dir...

**Comment by dockimbel** [comment]
I don't see the point. `normalize-dir` is just a helper function used by other functions and it does what it is meant for. If the user passes a path which could be not resolved, that needs to be handled by the caller to `normalize-dir`.
