### ISSUE TITLE
'help system' under Linux throws an error

### ISSUE THREAD

**Issue by pekr** [red/red#2691]
>> help system
*** Script Error: image! has no value
*** Where: =

Tested in terms of Ubuntu server, Cloud9 instance and by Dave Dander under his Docker instance, today's automated build ....

**Comment by greggirwin** [comment]
`image?` is the cause. No `image!` type under Linux yet?

**Comment by pekr** [comment]
Yes, `make image! 200x200` results in the same error message. The feature might not be there yet, so if it is not a bug, but just a missing feature, this ticket could be closed, sorry for that ...
