### ISSUE TITLE
to-set-word does not lead to binding

### ISSUE THREAD

**Issue by meijeru** [red/red#2694]
```
>> a: 1
== 1
>> to-set-word 'a 2
== 2
>> a
== 1
```
I would have thought that the second expression is equivalent to `a: 2` but it does not work.

**Comment by dockimbel** [comment]
There is no "double evaluation", `to-set-word 'a 2` evaluates to `a: 2` and returns the last value: `2`.

Same behavior as: `last reduce [to-set-word 'a 2]`.

**Comment by dockimbel** [comment]
Please do not open a ticket for each and every question you have. Use the chat rooms on Gitter preferably, unless it's really an issue which requires code fixing.

**Comment by meijeru** [comment]
It is not always easy to understand that there is no code to be fixed!

**Comment by dockimbel** [comment]
You can ask questions in red/red, or red/bugs chat room, then open a ticket if it's a confirmed issue.
