### ISSUE TITLE
DOC: Not entirely correct HELP text

### ISSUE THREAD

**Issue by meijeru** [red/red#2695]
The text printed in response to `>> help` contains the phrase
```
??     - Display a variable and its value
```
The word `variable` is better replaced by `word` because that is what the spec of `??` says.

**Comment by greggirwin** [comment]
I just put in a PR for this, but also realized that the help uses Display, Print, and Show in the "Other" section. There is no difference between them, so it's a question of whether the different words imply that they work differently, or if they just make the help more interesting to read. 

`What` help there also says "words", which is not correct. `What` only shows function types. I'll fix that.

**Comment by greggirwin** [comment]
This is complete @meijeru. Can we close it?
