### ISSUE TITLE
WISH: source should give result for routines as well

### ISSUE THREAD

**Issue by meijeru** [red/red#2696]
There is no reason why routines should be treated like natives, actions and ops, which do indeed have no body that can be displayed. The spec of a routine is pure Red, and the body is in Red/System but it is composed of Red values, so it can be shown, if need be with a warning "you are now reading RedS".

**Comment by greggirwin** [comment]
Good idea.

**Comment by greggirwin** [comment]
Should we show the interface for any-function! values, and a special body value for natives, actions, and ops?

**Comment by meijeru** [comment]
OK for the interface, but the body for natives and actions is a number, which does not mean a lot. For ops, the body is either that of a native or action (see previous sentence) or a function or a routine, which can be shown.

**Comment by greggirwin** [comment]
Correct. If we see that it's a native/action/op, we can show something like "<body not available>". That's what I meant.

**Comment by greggirwin** [comment]
How does this look?
```
	set 'source function [
		"Print the source of a function"
		'word [any-word!] "The name of the function"
	][
		val: get/any word
		print case [
			function? :val [append mold word #":" mold :val]
			routine? :val [[
				";" uppercase mold :word "is a routine! value; its body is Red/System code.^/"
				append mold word #":" mold :val
			]]
			'else [[uppercase mold word "is" a-an/pre mold type? :val "so source is not available"]]
		]
	]
source repend
source ask
source cr
source append
source +
source call
```

**Comment by meijeru** [comment]
Fine by me!

**Comment by greggirwin** [comment]
Needs a couple tweaks, but I'll fix up and submit.
