### ISSUE TITLE
Does not install on Windows Insider builds

### ISSUE THREAD

**Issue by ZETROzky** [red/red#2698]
It tells me that it isn't supported on my version of Windows, even though I'm on beta builds(, which are technically the newest versions of Windows). Why is that?

**Comment by dockimbel** [comment]
We don't have Windows Insider here, so can't test on it. Could you please describe which version of Red you launch, how you launch it and the exact error message with all the information (or better a screenshot)?

**Comment by ZETROzky** [comment]
![screenshot 33](https://cloud.githubusercontent.com/assets/15012524/26274987/32083e4c-3d74-11e7-9612-9850c54c5568.png)

Here. I'm on build 16199 if that's of any use, and I'm trying to assemble the environment for the first time ("install") on red 0.6.2 stable. I also tried using the latest auto assembled build, and got the same error.

**Comment by ZETROzky** [comment]
I tried deleting the folder and installing again, still got the same error on both stable and nightly.

**Comment by dockimbel** [comment]
Thanks.

**Comment by ZETROzky** [comment]
[Logfile.zip](https://github.com/red/red/files/1016153/Logfile.zip)

Here's the log. Took me an eternity cause of my 2007 grade laptop and internet.

**Comment by dockimbel** [comment]
I could not reproduce the issue on latest Windows 10, and we don't have Windows Insider here. As Windows Insider is actually a beta version of Windows 10, it is possible that it does not ship with all the legacy 32-bit libraries of the release version.
