### ISSUE TITLE
pair! value not allowed as second operand to subtract

### ISSUE THREAD

**Issue by meijeru** [red/red#2702]
This is somewhat inconsistent:
```
>> 1x2 - 1
== 0x1
>> 1 - 1x2
*** Script Error: - does not allow pair! for its value2 argument
*** Where: -
>> negate 1x2
== -1x-2
>> 0 - 1x2
*** Script Error: - does not allow pair! for its value2 argument
*** Where: -
```
The source is in `do-math-op` in `%integer.reds` which is also called for a `char!` first operand

**Comment by greggirwin** [comment]
It's because actions are singularly polymorphic based on the first datatype. Something to be noted in primer docs, but not an inconsistency per se.

**Comment by greggirwin** [comment]
Ah, I see that `+` works, but `-` doesn't, so perhaps an inconsistency indeed.

**Comment by meijeru** [comment]
Also, as I have shown, `negate` which is `0 - ...` does work.

**Comment by dockimbel** [comment]
Subtraction and division will raise an error in
