### ISSUE TITLE
vectors divided by char give divergent results

### ISSUE THREAD

**Issue by meijeru** [red/red#2709]
The error on vector of integer is off the mark. The result with vectors of float and percent is not understandable.
```
>> v: make vector! [1 2 3]
== make vector! [1 2 3]
>> v / #"^B"
*** Math Error: attempt to divide by zero
*** Where: /   ;; there is no zero in sight!!
>> v: make vector! [1.0 2.0 3.0]
== make vector! [1.0 2.0 3.0]
>> v / #"^B"
== make vector! [1.#INF 1.#INF 1.#INF]
>> v: make vector! [100% 200% 300%]
== make vector! [100% 200% 300%]
>> v / #"^B"
== make vector! [1.#INF 1.#INF 1.#INF]
```

**Comment by meijeru** [comment]
on second thought, the `1.#INF` result may also be a division by zero... But the `char!` value is 2, not 0...

**Comment by dockimbel** [comment]
Those operations with vectors and chars are not yet implemented. A proper message is displayed now.
