### ISSUE TITLE
Win 0.6.2: memory issue loading large files

### ISSUE THREAD

**Issue by michaeldesu** [red/red#2711]
Just doing a simple read via 
`s: read request-file`
in the REPL for some text files of size (a) 46Mb, (b) 76Mb, (c) 220Mb and found (b) & (c) fails with:

> *** Internal Error: not enough memory
> *** Where: read

JFYI only

**Comment by michaeldesu** [comment]
I tried red-24may17-3190977 and found that (b) didn't fail now.

**Comment by dockimbel** [comment]
We tried loading 200MB text files, it loads fine here, as long as you have enough **free contiguous** memory for that.
