### ISSUE TITLE
macOS/Interpreter: Crash with help in script

### ISSUE THREAD

**Issue by x8x** [red/red#2713]
File `%test`:
```
Red []

help system/script
```
Run:
```
  # red test

*** Runtime Error 27: non-existent physical address
*** at: A17340E4h
```

**Comment by greggirwin** [comment]
Works on Windows in GUI console, but produces the same error with CLI.

```
*** Runtime Error 1: access violation
*** at: 76B6ABA6h
```

**Comment by greggirwin** [comment]
Happens for any object, not just `system/script`.

**Comment by greggirwin** [comment]
It looks like `system/console/size/x` is `0` when this happens, so the dynamic calc for the help width goes negative and blows up. Looks like `mold/flat/part` doesn't like the negative `/part` arg, but I haven't duped it in a simple case yet.

**Comment by greggirwin** [comment]
Next clue here is that the `/part` arg has to be -4 or less to trigger the problem in the `help` code.

**Comment by greggirwin** [comment]
I'm fixing help, so it won't cause this problem, but still can't narrow it down outside of that.

**Comment by x8x** [comment]
Now it doesn't crash anymore, thought, it returns:
```red
     title   none!         ...
     header  none!         ...
     parent  none!         ...
     path    none!         ...
     args    string!       ...
```
while running `help system/script` directly inside the interpreter returns:
```red
  help system/script
     title   none!         none
     header  none!         none
     parent  none!         none
     path    none!         none
     args    none!         none
```
not sure if it's an issue or this can be closed.

**Comment by x8x** [comment]
@greggirwin Just rechecked this, fell free to close this if behaviour per my last comment is expected.

**Comment by greggirwin** [comment]
`Help` is meant to be used interactively, but there is now `help-string` which is usable in scripts. But you do still need to compile with the console or help environment code included. *However* the help support funcs do currently depend on the console object being there. I'll make a note to address that. 

I'll close this and make that a new ticket.
