### ISSUE TITLE
Compiler error: Find-aliased expected type argument of type: word

### ISSUE THREAD

**Issue by Oldes** [red/red#2714]
If I very simplify the test case:
```Red
#import [LIB stdcall [test: "test" []]]
print-line test
```
throws error:
```
*** Red/System Compiler Internal Error: Script Error : find-aliased expected type argument of type: word 
*** Where: get-type-id 
*** Near:  [either alias: find-aliased/position type/1 [
get-alias-id alias
]]
```

It would be great if the error message could be more descriptive. So the reason of this error could be found easily (providing line number in the source).

**Comment by dockimbel** [comment]
I get here:
```

**Comment by Oldes** [comment]
So maybe already fixed by accident. Above looks good enough.

**Comment by dockimbel** [comment]
Ok, closing the ticket, you can ask for re-opening if you see this issue appearing again.
