### ISSUE TITLE
Slow `print` from pure Red/System compiled app on Windows

### ISSUE THREAD

**Issue by Oldes** [red/red#2723]
Using `print` functions in Red/System compiled code is like 10x slower than output from `.red` code as there is no output buffer involved and used `putchar` is slow in Windows Console.

**Comment by dockimbel** [comment]
How is that a problem? Having to handle the flushing of the buffer manually would create new problems we don't have right now.

**Comment by Oldes** [comment]
Actually I'm not aware about any issues with current buffering... if you mean the problem with `ask` than it is not because of any buffering, but because internal input implementation is forcing screen cleanup and also always sets position of the cursor on 0 (+prompt size).

Anyway.. I made experiments with buffering in R/S only and as the buffer is flushed after each `prin`, and usual user scenario is using multiple prints, the speed up is not so significant - used when parsing (and printing) tags in my SWF parser with large file I had something like 5s with buffering and 6.7s with current version. So I'm quite not sure if I should use it or not.

**Comment by Oldes** [comment]
Btw... the output in GUI console is awesome.. where printing in cli version needs 10s, in gui-console it is in 0.15s. The CLI version could be probably optimized by not using print for each value, but with intermediate c-string which would be printed in one call.

**Comment by qtxie** [comment]
@Oldes IIRC, you added the buffer in CLI console. Are we Ok to close it?

**Comment by endo64** [comment]
Are we good to close this? Printing from Red/System compiled app looks fast enough on my test on Win10.
