### ISSUE TITLE
[macOS VID] backdrop should accept image as its argument

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2730]
```
view [ size 200x200 title "OK" backdrop %ld.jpeg ]
```
backdrop should accept word! that bound to image!, image url!, or image file! as its argument.

**Comment by PeterWAWood** [comment]
You can use ```compose``` to achieve the same effect:
```text
my-image: %ld.jpeg
view compose [ size 200x200 title "OK" backdrop (:my-image) ]
```

**Comment by JenniferLee520** [comment]
Thanks Peter. I've tried your solution on Windows, it worked. But on MacOS, It's not.
