### ISSUE TITLE
[macOS VID] RIGHT, LEFT, CENTER, BOTTOM, TOP, MIDDLE keywords do not work

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2735]
```Red
view [ text 80x80 yellow right bottom "OK" ]
```

The problem only happens in macOS.

**Comment by hiiamboris** [comment]
As of Dec 30, 2018 MacOS and Windows builds are consistent:
`view [ text 80x80 yellow right bottom "OK" ]` honors right/left but always displays text from the top (intended behavior or not?)
`view [ base 80x80 yellow right bottom "OK" ]` honors vertical alignment as well.

**Comment by qtxie** [comment]
@hiiamboris The `text` face does not support all the alignments, it's a limitation of the native control.

**Comment by hiiamboris** [comment]
Hmm. Theoretically we could still emulate that, but I believe it's not worth the trouble, as base already supports all that. Then as everything that was fixable was fixed, this issue can be closed?

**Comment by greggirwin** [comment]
I'll close this, and ask @gltewalt to note the limitation in docs.
