### ISSUE TITLE
[VID] DISABLED and LOOSE

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2737]
Using DISABLED and LOOSE on the same face will cause different behaviors on macOS and Windows. On macOS, the face still can be dragged. On Windows, it cannot. 

```Red
view [ box red 20x20 loose disabled box green 20x20 ]
```

**Comment by dockimbel** [comment]
A `disabled` face receives no event, so it should not be draggable, Windows is correct, macOS version needs fixing.

**Comment by JenniferLee520** [comment]
Also see #2787
