### ISSUE TITLE
[macOS DRAW] The negative sweep value in ARC command should sweep in the counterclockwise direction.

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2741]
Run the following code to see
```Red
view [ box white 100x100 draw [ line-width 10 fill-pen yellow arc 50x50 40x40 0 -90] ]
```
This bug is only in macOS.

**Comment by toomasv** [comment]
This issue has reappeared on Windows now.
![image](https://user-images.githubusercontent.com/11960635/120878336-65603d80-c5c4-11eb-9726-f4e269235d45.png)
