### ISSUE TITLE
`mandelbrot.red` gives error if closed abruptly

### ISSUE THREAD

**Issue by dockimbel** [red/red#2752]
@nc-x commented on [Sun Jun 04 2017](https://github.com/red/code/issues/49)

1.    From the console, run [mandelbrot.red](https://github.com/red/code/blob/master/Scripts/mandelbrot.red)
  
2.    Now click on `Draw`.
  
3.    Now close the GUI window before drawing is complete.

=> The console display error 
```
*** View Error: CreateWindowEx failed!
*** Script Error: path none is not valid for none! type
*** Where: eval-set-path
*** Stack: view do-events do-actor do-safe mandelbrot do-events eval-set-path
```

**Comment by qtxie** [comment]
Seems no error anymore.

**Comment by dockimbel** [comment]
No more crash, though the events in the console are not processed anymore. After the drawing finishes, we should be back in the event loop. Could we improve that?

**Comment by nc-x** [comment]
I still have the error on latest automated build.
![error](https://user-images.githubusercontent.com/16458742/27221071-ea96d44c-52a4-11e7-8c77-87e54b2bb6c3.gif)
