### ISSUE TITLE
Unknown directive compiler error is not thrown in .red file

### ISSUE THREAD

**Issue by Oldes** [red/red#2754]
Using misspelled code like:
```
#sustem [
	test: func[][print-line "test"]
]
```
throws error in Red/System file:
```
Compiling to native code...
*** Compilation Error: unknown directive sustem 
```
but not if used in `.red` file, which may lead to hard to find errors and also crash if used with routines.

**Comment by JenniferLee520** [comment]
#sustem ??

**Comment by dockimbel** [comment]
Could you please elaborate more on the *but not if used in .red file* part?

**Comment by Oldes** [comment]
It is easy... when above code is used in Red source file.. it compiles
without getting compiler error as expected. When used in Red/System, you
get error showing you that you are using unknown directive as expected.

**Comment by dockimbel** [comment]
* it compiles without getting compiler error as expected.* Yes, it compiles because it is valid Red code.

**Comment by Oldes** [comment]
As there are special `issue!` words used by compiler, it does not make sense to have other to be just like data values (at least in code which you compile). But as you wish.

I'm now not able to provide crash, but I had this real situation, when I used `#sustem` instead of `#system`, which silently passed. It was a few days ago.

**Comment by dockimbel** [comment]
Some issue! values are processed by the Red compiler, the same way they are processed by Rebol's SDK preprocessor. In case of Red, you can disable such processing locally, when you want to use them as data in your code, so I really don't see the problem with such approach.

**Comment by Oldes** [comment]
I have nothing against this approach. I'm just missing a compiler's safety warning or error, if I use misspelled preprocessor word and I don't disabled the processing locally. But you can close it if you think we don't need it... but my user experience is, that the single typo forced me to look, what is going on without any visible reason.

**Comment by Oldes** [comment]
btw... I don't know how to disable preprocessing ;-)

**Comment by dockimbel** [comment]
I think you are missing the main point anyway, issue! values are valid values in Red, like their are in Rebol, regardless how the code is run (compiled or interpreted). It's not possible to distinguish between a typo in a issue! that could be used by the preprocessor and a valid issue! value. In R/S, there's no issue! datatype in the language, therefore all issue! values are used by preprocessor, so it can easily detect invalid ones.
