### ISSUE TITLE
[VIEW] Using 'PUT on the 'DRAW facet in a face doesn't trigger the redrawing.

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2769]
For changing the fill-pen color of a draw block, I code like this:
```Red 
put face/draw 'fill-pen 255.0.0.0
```
After running this, the draw block did change, but the view engine didn't redraw the face. But the following code is OK:
```Red 
face/draw/fill-pen: 255.0.0.0
```

**Comment by dockimbel** [comment]
Code to reproduce it:
```
view [
	base draw [fill-pen blue circle 40x40 30] 
		on-down [put face/draw 'fill-pen 255.0.0.0]
]
```
