### ISSUE TITLE
[VID] 'Layout doesn't honor 'size setting in some circumstances

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2774]
If I set the size to 400x400, it won't work.
```Red
view [ size 400x400 backdrop %pix-720x464.jpg ]
```
If I set the size to 800x800, it works.
```Red
view [ size 800x800 backdrop %pix-720x464.jpg ]
```
This bug is both on Windows and macOS.

**Comment by geekyi** [comment]
So this is a wish? What I understand your question is:

## Expectation
Size of window is whatever is `size` set to, always

## Actual
If `backdrop` image is set and is larger, the minimum size of window is that of the backdrop

**Comment by geekyi** [comment]
I can still resize afterwards:
```red
img: make image! [300x200]
view/no-wait atest: layout [ size 10x10 backdrop img]
; afterwards
atest/size: 110x100
```
