### ISSUE TITLE
[VIEW] In 'Draw block in a Face, "Set-word" used as a position mark is updated. It's not like what the document said.

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2777]
According to [the "Draw" documentation](https://doc.red-lang.org/en/draw.html#_source_position)

> 6. Source position
>
> Set-words can be used in the Draw code in-between commands to record the current position in Draw block and be able to easily access it later.
> Note: 
> If the Draw block length preceding a set-word is changed, the recorded position will not be updated.

But somehow, the position can be updated.

```Red
view [ 
    origin 0x0
    base 800x400 draw [
        fill-pen green
        pos: box 400x0 450x100
    ] on-down [
        probe pos
        insert face/draw [pen red]
    ]
]
```
Run the code. "pen red" will be inserted into the draw block every time you click on the face. But as you will see: it's updated. In the following result, I clicked 4 times.
```Red
>> do %pos-test.red
[box 400x0 450x100]
[box 400x0 450x100]
[box 400x0 450x100]
[box 400x0 450x100]
```

**Comment by dockimbel** [comment]
It's a wording issue in the note.

**Comment by dockimbel** [comment]
Issue moved to [red/docs #20](https://github.com/red/docs/issues/20) via [**ZenHub**](https://www.zenhub.com/)
