### ISSUE TITLE
WISH: checksum to operate on url! as well

### ISSUE THREAD

**Issue by meijeru** [red/red#2778]
Unless of course there is a reason why this can't be done...

**Comment by qtxie** [comment]
In R2, `checksum` on `url!` is the same as on `string!`.
```
>> checksum "http://rebol.com"
== 13615491
>> checksum http://rebol.com
== 13615491
```
Is it the behavior you want? @meijeru

**Comment by meijeru** [comment]
No, I suppose the analogy is not with url! as a sort of string, but with url!, like file!, as an address where information is stored, and the checksum is computed over that information...

**Comment by greggirwin** [comment]
It would be a nice convenience wrapper, but may be a bit tricky. With a local file, though it currently just bulk reads it, when we get full I/O it can handle large files. That won't work with url targets.

**Comment by dockimbel** [comment]
We cannot do the checksum on a distant resource, you need to get it first using an I/O operation. What you want is `checksum read <url>`, that's already available (if your URL is using HTTP/S).
