### ISSUE TITLE
[View] Select an index which is out of range

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2791]
When selecting an index which is out of range, the behavior on macOS and on Windows 10 are different. 
In the following example, nothing is selected on Windows, and "CCC" is selected on macOS.
```Red
view [ text-list data ["AAA" "BBB" "CCC" ] select 4 ]
```
In the following example, nothing is selected both on Windows and on macOS.
```Red
view [ text-list data ["AAA" "BBB" "CCC" ] select 0 ]
```

**Comment by dockimbel** [comment]
Out-of-range selection should not select any list entry.
