### ISSUE TITLE
[Windows VID] 'Select on 'Tab-Panel not working

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2792]
In the following code, "select 2" doesn't work. 
```Red
view [ tab-panel [ "P1" [ base red ] "p2" [ base green ] ] select 2 ]
```
This bug is on Windows only.

**Comment by dockimbel** [comment]
Following code even crashes the console:
```
view [ tab-panel [ "P1" [ base red ] "p2" [ base green ] ] on-created [face/selected: 2] ]
```

**Comment by dockimbel** [comment]
The fix is only fixing the crashing, extra work is required for enabling the tab-panel selected from VID.
