### ISSUE TITLE
[mac VID] Same style, difference appearances.

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2794]
In the following code, the two "OK" buttons should look exactly the same. But they don't.
```Red
view [
    style button2: button font-size 25
    button2 "OK"
    button2 "OK"
]
```
This bug is only on macOS.

**Comment by dockimbel** [comment]
Fixed by commit: [d47f3c48](https://github.com/red/red/commit/bab135491c00a45b5004c2544234a571d47f3c48).
