### ISSUE TITLE
Wish: red.exe options inside script header

### ISSUE THREAD

**Issue by luce80** [red/red#2816]
I wish I could specify red.exe options from within red script header.
Such as:
```
Red [
	options: [--cli -t Windows]
]
; code here
```

**Comment by dockimbel** [comment]
There is already an header for that, it's `config: [...]` and you need to pass options as defined [here](https://github.com/red/red/blob/master/system/config.r). The command-line is transformed into those options internally, so you have even more finer-grained control there than on command-line.
