### ISSUE TITLE
BNF grammar of Red

### ISSUE THREAD

**Issue by nickkoro02** [red/red#2817]
(Sorry for my broken English)
I have a school project where we have to write a plugin for an IDE. I've choosen to make a Red plugin for InteliJ IDEA, but I'm having some troubles finding a BNF grammar of it. 

I'm currently using this grammar:
https://github.com/rgchris/Rebol-Notation/blob/master/rebol.ebnf
But it is a Rebol grammar and EBNF. It would be really great if someone could send me a grammar of Red. It doesn't matter if it is ABNF or EBNF, I'll use a tool to translate it.

**Comment by greggirwin** [comment]
There is also https://github.com/rebolsource/rebol-syntax/blob/master/syntax.r. It will be very close to Red, though there will be some differences.

**Comment by greggirwin** [comment]
Is EBNF not allowed, or do you just not want to translate it?

**Comment by nickkoro02** [comment]
I need a BNF grammar in order to make the plugin. Translating a EBNF grammar to BNF won't be the problem, but I can't find a grammar for Rebol or Red except that I linked to. BTW: Thank you for the link, but this is the Rebol grammar in Parse, which is not exactly what i wanted.

**Comment by greggirwin** [comment]
When I started work on Ren, I referred to Chris's work as well, as it was the most complete in BNF form.

**Comment by nickkoro02** [comment]
Hm... alright. Then I'll use it. Thank you.

**Comment by rebolek** [comment]
You should be fine with Rebol grammar, if you add hexadecimal integers `XXh` and literal maps `#(<content>)`.
