### ISSUE TITLE
[macOS View] Changing font color will also change the font size.

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2821]
In the following 2 pieces of code, only font-color is changed, but, after running the code, you will see that the font size is changed too.
```Red
view [ text "This is fun" ]
```
and
```Red
view [ text "This is fun" font-color red]
```
This bug is only on macOS.

**Comment by qtxie** [comment]
The default font size is 13 which cause the issue.
```
layout [ t: text "This is fun" font-color red]
t/font/size
== 13
```

**Comment by qtxie** [comment]
Should be fixed now.
