### ISSUE TITLE
[macOS View] Clicking on the non-button part of a Drop-List component will not make the list shown.

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2827]
In the following code, clicking on the button of the drop-list is fine, but clicking on the field will not make the list popup.
```Red
view [ drop-list data [ "AA" "BB" "CC" ] select 1 ]
```
This bug is only on macOS.

**Comment by dockimbel** [comment]
That is how the macOS widget works. Native widgets can have some platform-specific behavior, that is part of that "native GUI" experience, and expected by end-users.

**Comment by JenniferLee520** [comment]
No, this is not the default behavior on macOS.

**Comment by JenniferLee520** [comment]
This ticket should be re-open.

**Comment by JenniferLee520** [comment]
Nope, this is not the default behavior for drop-list on macOS.

**Comment by dockimbel** [comment]
@qtxie You should have a look at this issue.

**Comment by qtxie** [comment]
I'll use [Pull-Down Lists](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/MenuList/Articles/ManagingPopUpItems.html) instead of Combo Box.
