### ISSUE TITLE
[View] Wish: Renaming the "enable?" facet to "enabled?"

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2829]
The face! object has a facet named "enable?". I would like it to be renamed to "enabled?".

**Comment by dockimbel** [comment]
@greggirwin @PeterWAWood What do you think?

**Comment by PeterWAWood** [comment]
I think the answer lies in the expected use pattern of the facet. 

If its primary use is to set whether the inputs events are enabled or disabled then "enable?" makes most sense to me.

If its primary use is for querying to see if a face responds to input events or not "enabled?" seems the better choice.

**Comment by greggirwin** [comment]
Peter's answer is excellent. I'll add that the trailing `?` makes it look like a query. Another point is that all the facets are nouns/properties, not methods. `Selected` is used as a pseudo-method, e.g., for `text-list`, so `enabled?` seems the better choice to me. It's a state-changing noun.

**Comment by dockimbel** [comment]
Done.
