### ISSUE TITLE
[VID] Buttons in VID won't follow the layout command. 

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2830]
In the following code, everything is fine.
```Red
view [
    size 200x100
    origin 0x0
    space 0x0
    text gray 200x50 
    return
    base "A" red 50x50
    base "B" green 50x50
    base "C" blue 50x50
    base "D" purple 50x50
]
```
After replacing the 4 Bases with Buttons and run the new code, you will see the problem.
```Red
view [
    size 200x100
    origin 0x0
    space 0x0
    text gray 200x50 
    return
    button "A" red 50x50
    button "B" green 50x50
    button "C" blue 50x50
    button "D" purple 50x50
]
```
This bug is on macOS. I am not sure Windows has this bug or not. My Windows Laptop is not with me. I will test it on Windows while I have my Windows Laptop around.

**Comment by greggirwin** [comment]
It seems fine on Windows.

**Comment by nc-x** [comment]
Just to confirm -
On rebol,
```
view layout [button "A" red]
```
gives a red button.
Whereas on Red
```
view [button "A" red]
```
does not give any color.

On Windows 8.1, confirmed. @greggirwin which windows are you on?

**Comment by greggirwin** [comment]
Ah, I thought the layout portion was incorrect, not the color. You currently can't set the color of buttons that way.

**Comment by nc-x** [comment]
@greggirwin
> You currently can't set the color of buttons that way.
Okay. Then, maybe @JenniferLee520 meant some other layout problem on MacOS.

**Comment by JenniferLee520** [comment]
I was talking about layout commands, which are "ORIGIN" and "SPACE".

**Comment by dockimbel** [comment]
Native buttons are not equivalents to barebone faces. On macOS, buttons have a minimal margin preventing them from touching each other. If you need OS-provided buttons with no spaces between them, you should wait for the upcoming `toolbar` widget and use customized base faces in the meantime.
