### ISSUE TITLE
HELP issue with image! values in objects

### ISSUE THREAD

**Issue by dockimbel** [red/red#2839]
```
>> obj: object [i: make image! 10x10]
== make object! [
    i: make image! [10x10 #{
FFFFFFFFFFFFFFFFFFFFFFFFFF
>> help obj
     i  image!        ["size:" 10x10]
```
The last column should print `size: 10x10` instead of a block. This looks like a missing `rejoin` call.

**Comment by dockimbel** [comment]
Additionally, `mold` on images does not seem to honor the indentation.

**Comment by greggirwin** [comment]
Indeed, looks like a missing `form`. Good catch.

**Comment by greggirwin** [comment]
https://github.com/red/red/pull/2840
