### ISSUE TITLE
Wish: the /user part of an email value is of string! datatype.

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2843]
```Red
>> em: jennifer@abc.com
== jennifer@abc.com
>> em/user
== jennifer
>> type? em/user 
== email!
```
I wish
```Red
>> em/user
== "jennifer"
>> type? em/user 
== string!
```

**Comment by dockimbel** [comment]
Agreed, that would be more consistent with the `/user` setting access.

**Comment by meijeru** [comment]
By the same token, I should wish that the `/host` part be of type `url!`, because it looks also like a word and its type cannot be inferred.

**Comment by DideC** [comment]
url! implied a protocol specifier (ie: http:// or pop:// or whatever://). I don't see what it could be in this case. So to me it may be a string! too.

**Comment by meijeru** [comment]
The implied protocol specifier with an internet host addres is always `http://`. Try this in any browser. So either the `/host` component has `http://` prefixed to make it a correct `url!` literal, or we settle for a `string!` value as well.

**Comment by dockimbel** [comment]
There is no path accessor for `url!`. `url!` and `file!` interpret paths as a concatenation action.

**Comment by meijeru** [comment]
So, let us have the `/host` part as a `string!` value also, please?

**Comment by dockimbel** [comment]
@meijeru The change applies to both `/user` and `/host`.
