### ISSUE TITLE
WISH: #include macros defined in separate file

### ISSUE THREAD

**Issue by 9214** [red/red#2847]
File `%macros.red`:
```Red
Red []

#macro [@answer] func [s e] [42]
```

File `%main.red`:
```Red
Red []

#include %macros.red

probe @answer
```

Evaluating `%main.red` gives `@answer`, but I wish it to be `42`. In my understanding `#include` expands all macro directives (and deletes them with all macro calls) before actual inclusion.

**Comment by dockimbel** [comment]
Actually, the issue is not related to macros but to the compiler lexer:
```
Red []
probe @answer
```
gives the following compilation error:
```
*** Syntax Error: Invalid word! value
*** in file: C:\Dev\Red\main.red
*** line: 2
*** at: "@answer"
```

**Comment by dockimbel** [comment]
The `#include` directive being a compiler directive (and not a preprocessor one), the preprocessor is only able to load it (in order to load the macros from it) if the path is relative to the main Red script.
