### ISSUE TITLE
WISH: allow does/has in named macro

### ISSUE THREAD

**Issue by 9214** [red/red#2848]
As title suggests, `func [] [<body>]` is equivalent to `does [<body>]`, and `func [/local <words>] [<body>]` is the same as `has [<words>] [<body>]`. 

Currently only `function` and `func` are allowed in named macro definitions. Though it's just a syntactic sugar, I wish I could also use `has` and `does` in them.

**Comment by meijeru** [comment]
Very similar to #2424

**Comment by 9214** [comment]
Closing as a duplicate of #2424, where an alternative solution is already proposed.
