### ISSUE TITLE
Date: isoweek number calculation is off by two days

### ISSUE THREAD

**Issue by meijeru** [red/red#2853]
Week 2 of 2017 begins on 7 Jan according to Red. It begins on 9 Jan according to ISO.

**Comment by dockimbel** [comment]
Seems to work fine here:
```
>> d: now
== 6-Jul-2017/22:44:51+08:00
>> d/week: 1
== 1
>> d
== 1-Jan-2017/22:44:51+08:00
>> d: now
== 6-Jul-2017/22:45:12+08:00
>> d/isoweek: 1
== 1
>> d
== 2-Jan-2017/22:45:12+08:00
```

**Comment by meijeru** [comment]
I am not denying you can SET isoweek. What I protest is that upon retrieving isoweek, the calculation is not correct. See
```
>> d: 7-Jan-2017
== 7-Jan-2017
>> d/isoweek
== 2
```

**Comment by greggirwin** [comment]
Is http://www.staff.science.uu.nl/~gent0113/calendar/isocalendar.htm / https://en.wikipedia.org/wiki/ISO_week_date our point of reference?

**Comment by dockimbel** [comment]
@greggirwin That's correct, `/isoweek`  implements the ISO week date.

**Comment by greggirwin** [comment]
No problem on current problems it may have. Just want to make sure we can point people to references for expected behavior.

**Comment by dockimbel** [comment]
`/isoweek` should now fully conform to the ISO 8601 week.

Setting `/isoweek` probably needs some adjustments too for full conformity.
