### ISSUE TITLE
Wish: timezone should be denotable by h:m, as normal time values allow.

### ISSUE THREAD

**Issue by meijeru** [red/red#2854]
Currently, the minute part is constrained to be two digits, which makes for special parsing.

**Comment by dockimbel** [comment]
Given that only ":30" could use such shorter notation, I don't think it is worth supporting a shorter form for minutes.

**Comment by meijeru** [comment]
Mind you, also :15 and :45 occur in the real world (admittedly they are rare). Your encoding in 7 bits allows values from -15:45 to +15:45, while only -12:00 to +14:00 are needed, but that is not checked. Also, I have noticed that times of 16:00 and higher are taken modulo 16:00.

**Comment by dockimbel** [comment]
> Mind you, also :15 and :45 occur in the real world (admittedly they are rare). 

How can :15 of :45 use a h:m notation?

**Comment by meijeru** [comment]
I was just, as usual for me, going for consistency, as the zone is a time value, and time values _on their own_ can use h:m. Thus you might invoke the time-rule for the parsing of the time zone. But I agree this is probably not worth bothering.

**Comment by dockimbel** [comment]
There is no full equivalence between time in date! and in time! anyway, time! can be negative while date/time cannot.
