### ISSUE TITLE
setting image/alpha, /rgb and /argb to a value other than binary should give error

### ISSUE THREAD

**Issue by meijeru** [red/red#2857]
There is no check on the type of the value supplied for setting these components of an image.

**Comment by qtxie** [comment]
Will give error now. We also support tuple! and integer! to set image color.

**Comment by gltewalt** [comment]
Error is given on the first attempt, but second attempt crashes GUI console.

Example:
```
>> i: make image! 1x1
== make image! [1x1 #{FFFFFF}]

>> i/rgb
== #{FFFFFF}

>> i/rgb: "hodl"
*** Script Error: invalid argument: "hodl"
*** Where: set-path
*** Stack: 

img/rgb: "hodl"

**CRASH**
```

**Comment by endo64** [comment]
After setting any of `rgb`, `argb`, `alpha` to a string crash happens when first access to the image.

```
i: make image! 1x1
i/allpha: "test"
i ; crash
```
