### ISSUE TITLE
spec block for make date! is treated differently from most other spec blocks

### ISSUE THREAD

**Issue by meijeru** [red/red#2863]
A `word!`  value in the spec block for `make date!`  is replaced by its value. In most spec blocks, e.g. for `make time!` this is not the case.
```
>> harvest: 8
== 8
>> make date! [1 harvest 2017]
== 1-Aug-2017
>> midday: 12
== 12
>> make time! [midday 0 0]
*** Script Error: cannot MAKE/TO time! from: [midday 0 0]
*** Where: make
*** Stack: 
>> make time! reduce [midday 0 0]
== 12:00:00
```
As the example shows, `reduce` will also substitue the `word!` value, and of course do much more. It is not clear why the words in the date spec block are treated specially when reduce is available.

**Comment by greggirwin** [comment]
Maybe in anticipation of allowing month names to be used? e.g. `[1 jan 2017]`

**Comment by meijeru** [comment]
But that would imply defining these month names in the global context. And everything can be done by `reduce`.

**Comment by dockimbel** [comment]
This is part of a move to allow spec block arguments to `make` to accept words instead of values, removing the need to rely on `reduce` for simply resolving words.
