### ISSUE TITLE
Preprocessor error while providing `char!` argument to function in execution context

### ISSUE THREAD

**Issue by 9214** [red/red#2870]
Following simple macro:
```Red
#do [
    goedelize: func [x [char!]][to integer! x]
]

probe #do keep [goedelize #"A"]
```
Interpreted:
```Red
65
```
Compiled:
```Red
*** Preprocessor Error in #do
*** Script Error : goedelize expected x argument of type: char
*** Where: [#do]
*** Near:  [goedelize #'00000041]
```

In my understanding it has something to do with `#` in `char!` argument, because this one works:
```Red
#do [
    goedelize: func [x [char!]][to integer! x]
]

probe #do keep [goedelize to char! "A"]
```
And this one too:
```Red
#do [
    goedelize: func ['x][to integer! to char! form x]
]

probe #do keep [goedelize A]
```

**Comment by dockimbel** [comment]
That's a limitation of the compiler, as it runs on Rebol2, and Rebol2 not having Unicode support, char values need to be encoded in a special way by the lexer before being compiled. As the compiler macros will run just after lexer stage, it clashes with this intermediary encoding.

**Comment by dockimbel** [comment]
This issue will not get fixed until the toolchain is rewritten in Red itself.
