### ISSUE TITLE
Wish: Be able to compile code in console. 

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2881]
I wish I could compile my red code in console.
```Red
>> compile/output %my-clock.red %clock.exe
```

**Comment by geekyi** [comment]
This shouldn't be so hard to do on your own, I think `call %red.exe args` is enough? ;)

**Comment by dockimbel** [comment]
Indeed, it's a one-liner function that can be implement easily.

That said, we plan in the future to support operating the Red toolchain from the Red console. So, I will close this ticket, as it's already a feature in our roadmap.

**Comment by greggirwin** [comment]
+1. I started a dialected func design along these lines some time back.
