### ISSUE TITLE
Linux/macOS: 'enable bracketed pasting' escape sequence gets included in red output

### ISSUE THREAD

**Issue by x8x** [red/red#2885]
Given script `%test.red` containing:
```
Red []
prin ""
```
Running this:
```
rebol --do "print mold system/options/args/1 q" -- `red test.red`
```
returns:
```
"^[[?2004h"
```
expected:
```
""
```
This is problematic when passing the result of a red script to other commands that do not interpret ANSI escapes.

**Comment by x8x** [comment]
If there is no better low level solutions, here is one:
instead of emitting the "start bracketed mode" in the console init routine, emit it at the first call to function `ask`

**Comment by qtxie** [comment]
I run this command, seems works fine now.
```
rebol --do "print mold system/options/args q" -- `red test.red`
```

**Comment by x8x** [comment]
Did you try in macOS or Linux? I get same result as before.

**Comment by qtxie** [comment]
I tried in macOS. Will try in Linux today.
