### ISSUE TITLE
WISH: browse should accept a file! value also

### ISSUE THREAD

**Issue by meijeru** [red/red#2887]
Currently, only `url!` values are allowed. I don't know whether the OS functions called are simply accepting files in addition to urls, or whether a `file://` protocol should be prepended in those calls. Either way, I don't see anything html-specific in the `browse` code (`%environment/routines.reds`).

**Comment by qtxie** [comment]
Now we can browse a folder or a file:
```
browse %/d/
browse %/d/red/usage.txt
```
