### ISSUE TITLE
WISH: support hexadecimal numbers in chars

### ISSUE THREAD

**Issue by rebolek** [red/red#2890]
It is possible to write `char!` with its corresponding numerical ASCII/Unicode value in the form of `#"^(65)" == #"e"`. It would be also nice to use hexadecimal numbers here: `#"^(41h)" == #"e"`. This throws `invalid char!` error currently.

**Comment by meijeru** [comment]
I think there is a misunderstanding: `65` for `#"e" `  is already hexadecimal! And `41` in hex is `#"A"`. Try it for yourself...

**Comment by rebolek** [comment]
Sorry, you're right and I am moron.
