### ISSUE TITLE
Some chars in string cannot be converted to binary

### ISSUE THREAD

**Issue by rebolek** [red/red#2895]
See this example:

```
>> #"^(10FFFF)"
== #"􏿿"
>> mold #"^(10FFFF)"
== {#"􏿿"}
>> to binary! mold #"^(10FFFF)"
*** Script Error: Invalid char! value: #"􏿿"
*** Where: to
*** Stack:
```

It is valid char, so it should work IMO.

**Comment by meijeru** [comment]
According to Unicode (`http://www.unicode.org/charts/PDF/U10FF80.pdf`) both `10FFFE` and `10FFFF` are "Noncharacters", "These codes are intended for process-internal uses"

**Comment by rebolek** [comment]
True, but they can be represented as `char!` in Red. So either forbid it (which I think is a wrong solution, lot (all) of first 32 ASCII codepoints are non-characters too), or fix it.

Anyway, take a look this:
```
>> to binary! mold #"^(10FFFA)"
== #{2322F48FBFBA22}
>> to binary! mold #"^(10FFFD)"
== #{2322F48FBFBD22}
>> to binary! mold #"^(10FFFE)"
== #{2322F48FBFBE22}
>> to binary! mold #"^(10FFFF)"
*** Script Error: Invalid char! value: #"􏿿"
*** Where: to
*** Stack:
```

Especially this: 
```
>> to binary! mold #"^(10FFFE)"
== #{2322F48FBFBE22}
```

So `10FFFE` is fine and `10FFFF` not. Definitely a bug.

**Comment by meijeru** [comment]
Possibly a `<` instead of a `<=`  somewhere...

**Comment by meijeru** [comment]
Indeed! `%runtime/unicode.reds` line 62 is the culprit, and see also line 56...

**Comment by rebolek** [comment]
@meijeru Thanks for looking into it! I checked it locally and it seems that changing line 62 fixes the problem (line 56 is fine, molding #"^(FFFF)" works). I've created pull request for it.
