### ISSUE TITLE
make url! <block> could be a trifle smarter and recognize allowed protocols

### ISSUE THREAD

**Issue by meijeru** [red/red#2901]
There is a list of allowed protocols (`http` etc.). The first component of the block is assumed to be a protocol word, so this could be checked. By-product: the separator inserted after the protocol is now always `://` but this could depend on the protocol, e.g. after `mailto` it should be `:`.

**Comment by dockimbel** [comment]
Why should we restrict the scheme part of `url!` datatype?

**Comment by meijeru** [comment]
But at least it would be worthwhile having `mailto:` instead of `mailto://` as currently!
