### ISSUE TITLE
Avira Blocked and quarantined Red programdata

### ISSUE THREAD

**Issue by singam96** [red/red#2903]
https://files.gitter.im/red/red/1Rz3/image.png

**Comment by dockimbel** [comment]
Thanks, though it's a duplicate of #2399. Avira is the last big AV which is causing us trouble, and their support service is really bad.

**Comment by singam96** [comment]
ooh my bad.

**Comment by dockimbel** [comment]
@singam96 Could you provide us with the version/build/date of your Avira signatures databases and engine?

**Comment by singam96** [comment]
this is the link
https://files.gitter.im/red/red/vQiB/image.png
