### ISSUE TITLE
keys-of not working when compiled / windows10

### ISSUE THREAD

**Issue by kermitaner** [red/red#2905]
`Red[]
m: make map!["a" 1 "b" 2 "c" 3]
foreach k keys-of m[probe k]`
is giving an error :  "entry point exec/f_words-of"  when compiled with -u flag
OS windows10, with latest build from 20.7.2017
note from Gregg:
Looks like an aliasing issue on keys-of. If you change that to words-of, it works fine.

**Comment by dockimbel** [comment]
Good catch, thanks for reporting.

**Comment by dockimbel** [comment]
Please give it a try with a new build. Try first compiling your code directly, if it fails, try with a `red clear` command first, then compile it again.
