### ISSUE TITLE
returned value from function defined in context differs during compiled app execution

### ISSUE THREAD

**Issue by 9214** [red/red#2910]
Another tricky bug which boils down to something like this:
```Red
my-ctx: context [
    my-other-ctx: context [
        f: func [c][
            object [x: 100 * c y: 100 / c]
        ]
    ]

    foo: func [c][my-other-ctx/f c]
]

probe my-ctx/foo 3

view []
```
`my-ctx/foo <arg>` should always return `object!` and that's exactly what happening in interpreter:
```Red
make object! [
    x: 300
    y: 33
]
```
But If I'll compile this script and launch app, `my-ctx/foo 3` for some reason returns `3`.

Another example which is more similar to my original situation:
```Red
with: func [
    contexts [block!]
    body     [block!]
][  
    forall contexts [bind body reduce first contexts]
]

my-ctx*: context [
    my-other-ctx: context [
        f: func [c][
            object [x: 100 * c y: 100 / c]
        ]
    ]

    some-other-ctx: context [field: 'whatever] ;<-- if I'll comment out this line compiled app will silently crash

    foo-body: with [some-other-ctx][my-other-ctx/f c]
    foo: func [c] foo-body
]

probe my-ctx*/foo 3

view []
```
Again, in interpreter it's good ol' `object!`, but once compiled probe returns
```Red
func [c][some-other-ctx]
```
Alternatively, if I wrap up `my-ctx*/foo 3` call inside `view` block like this:
```Red
view [do [probe my-ctx*/foo 3]]
```
I'll get `object!` in interpreter (as usual), and, uhm, `object!` in compiler, but not the one I expected
```Red
make object! [
    field: 'whatever
]
```
Further if I want to access, say, `x` field of returned` object!` I'll get an error, since there's no `x` field! (because it's not *that* object) :worried:

**Comment by 9214** [comment]
Though I'm not sure if `context` has something to do with it, because I've caught similar bug in a script with functions only, (though there were a lot of interleaved function calls).

**Comment by geekyi** [comment]
Is https://github.com/red/red/issues/2542 related?

**Comment by 9214** [comment]
Perhaps, though I didn't used nested functions anythere.

**Comment by dockimbel** [comment]
@9214 At this line: 
```
foo-body: with [some-other-ctx][my-other-ctx/f c]
```
The two blocks are seeing as *data* by the compiler, there is no way it can guess that the second one is code. So in order for that to work with the compiler, you need to replace it with:
```
foo-body: with [some-other-ctx][do [my-other-ctx/f c]]
```

**Comment by 9214** [comment]
Wrapping code inside `do` or `do/expand` fixed everything.
