### ISSUE TITLE
time!: Can not set a date with time including subseconds

### ISSUE THREAD

**Issue by x8x** [red/red#2917]
It's always rounded to the second:
```
>> 23-Jul-2017/10:02:07.4
== 23-Jul-2017/10:02:07
```

**Comment by x8x** [comment]
Probably related: `difference` rounds subseconds to the seconds precision.
```
>> difference 1-Jan-1970/0:0:0.6 1-Jan-1970
== 0:00:01
```

**Comment by dockimbel** [comment]
It's a recent regression, probably from https://github.com/red/red/commit/4acee92cee5e2d60c668ad08cd127cfbea6cd016
