### ISSUE TITLE
Console dies quietly on missing button caption

### ISSUE THREAD

**Issue by kpeters58** [red/red#2938]
When I create a style like this:
     style nbtn:     button      font [ style: [bold] size: 10 ]

And then use it in a script pasted into the console, but without supplying a caption for the button, the console quietly shuts down without any error reporting.

**Comment by dockimbel** [comment]
Could you please provide a complete source code or the full step-by-step way with all the required information to reproduce the issue?

**Comment by kpeters58** [comment]
I can run the code below w/o any issues - if I remove the caption from, say, the b_edit button and re-run, the console dies quietly.


Red [needs: 'view]
    
lookup-form: compose/deep layout [

	title "Lookups maintenance"

	style lbl:      text        100 right font [ size: 10 ] pewter
	style lbl2:     text        right font [ size: 10 ]
	style fld:      field       font [ style: [bold] size: 10 ]
	style drd:      drop-down   font [ style: [bold] size: 10 ]
	style nbtn:     button      font [ style: [bold] size: 10 ] 25x25
	style btn:      button      font [ size: 10 ] 50x25
	
	tp: tab-panel [
	
		" Form view" [  
			backdrop silver
			h5 "Lookups" silver return
			
			panel pewter [
				lbl "ID"        	f_id:       fld 100 return
				lbl "Type"      	f_type:     drd 120 data [ "Genders" "Salutations" "Countries" "Currencies" ] return
				lbl "Description"   f_desc:     fld 488 return 
				lbl "Display order" f_disp:     fld 50
			] 
			return

			db-nav: panel [
				space 2x2
				b_first:  nbtn "|<"
				b_prev:   nbtn "<"
				b_next:   nbtn ">"
				b_last:   nbtn ">|"           pad 10x0
				b_new:    btn  "New"
				b_edit:   btn  "Edit"
				b_del:    btn  "Delete"
				b_canc:   btn  "Cancel"       pad 10x0
						  lbl2 "Records" 50   pad  5x0
				recs:     fld  70 hint "0"    pad 10x0
				b_help:   btn  "Help"
				b_save:   btn  "Save"
			] 
		]
		
		"List view" [ 
			backdrop silver
		]
	] 
] 

view lookup-form

**Comment by kpeters58** [comment]
This is 0.63 on Windows 10 Professional.

**Comment by dockimbel** [comment]
Testing on Win7, your code works fine, with and without "edit" label on the button. Will test on Win10 tomorrow.

**Comment by kpeters58** [comment]
Need to correct Win version - it's Enterprise as shown:
![mypc](https://user-images.githubusercontent.com/17860443/28732797-2dc2585e-738e-11e7-94a8-daf885409e68.png)

**Comment by kpeters58** [comment]
Just to be clear: The caption needs to be removed entirely for bug to show, not just set to "" - like so:

				b_edit:   btn

**Comment by kpeters58** [comment]
Also: I see a split second flash of the expected window before the console disappears. It does not just hide, but terminates as verified via Task Manager.

**Comment by kpeters58** [comment]
Just tried this on another PC @ home under Windows 10 Home - identical failure

**Comment by dockimbel** [comment]
I can reproduce the issue on Win 10.

**Comment by dockimbel** [comment]
@qtxie Please check if my fix is correct (should be) and if the macOS backend requires a similar fix.

**Comment by dockimbel** [comment]
@kpeters58 It should be fixed now. You can download the newest automated build for Windows from our [Download page](http://www.red-lang.org/p/download.html). It should work fine now.
