### ISSUE TITLE
make vector! <float> sets element type/size float! 32

### ISSUE THREAD

**Issue by meijeru** [red/red#2940]
* `make series! <float>` normally makes an empty series with number of elements reserved equal to the truncated float.
* `make vector! <integer>` makes a vector of integers of size 32 with the required number of elements all set to integer 0
* `make vector! <float>` makes a vector of floats (BTW this is as yet undocumented) with the required number of elements all set to float 0.0  BUT they are of size 32, which is not the default size for floats

**Comment by dockimbel** [comment]
@qtxie Did you choose the `float32!` default affinity because of modern 2D/3D APIs?

**Comment by qtxie** [comment]
@dockimbel Nope. Actually it should be integer! in both cases.

**Comment by dockimbel** [comment]
Ah, yes, you're right, the `make vector! <float> makes a vector of floats` part is wrong.

**Comment by dockimbel** [comment]
@qtxie 
```
make vector! 2.5
== make vector! [float! 32 [0.0 0.0]]
```
That is not the right behavior.
