### ISSUE TITLE
Different behaviors between Red and REBOL3 in evaluating a word which is referring to a lit-word.

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#2950]
In Rebol, I get a word:
```Red
>> a: first ['aaa]
== 'aaa
>> a
== aaa
```
In Red, I get a lit-word:
```Red
>> a: first ['aaa] 
== 'aaa
>> a
== 'aaa
```

**Comment by geekyi** [comment]
You could argue Red does it better. What if you wanted to preserve the `lit-word!`?
Also the it makes me uneasy that arguably the same code can give different results:
```red
type? a: first ['aaa]
type? a
```
In Rebol 2:
```rebol
>> type? a: first ['aaa]
== lit-word!
>> type? a
== word!
```

**Comment by dockimbel** [comment]
Rebol has an inconsistent behavior, while Red produces consistent results both for lit-words and lit-paths:
```
>> a: first ['aaa]
== 'aaa
>> a
== 'aaa
>> a: first ['a/b]
== 'a/b
>> a
== 'a/b
```

As there is no cases I can think of where the Rebol behavior is objectively better, Red sticks with a consistent and more intuitive behavior.
