### ISSUE TITLE
Red/System threads, atomics?

### ISSUE THREAD

**Issue by 0joshuaolson1** [red/red#2965]
I haven't found ANYTHING about this. Are these concepts unnecessary? Not yet planned?

**Comment by greggirwin** [comment]
Concurrency will come in a future release. Rather than opening tickets for questions, please visit https://gitter.im/red/red or https://gitter.im/red/red/welcome and ask there.

**Comment by 0joshuaolson1** [comment]
This does not resolve the issue (nor does 'concurrency'). Are they in a public roadmap? A design document?

**Comment by greggirwin** [comment]
I closed the issue because questions are best addressed outside tickets. And this is a potentially big subject. See https://trello.com/b/FlQ6pzdB/red-tasks-overview for the current roadmap. The design is not finalized or public yet.

**Comment by 0joshuaolson1** [comment]
Fair. For anyone who comes across this issue, the topic is 'Define tasking model', even though it's under the (possibly unintentionally) specific label of concurrency.

**Comment by greggirwin** [comment]
Thanks @0joshuaolson1.
