### ISSUE TITLE
How to install Red on ArchLinux based distros?

### ISSUE THREAD

**Issue by faustinoaq** [red/red#2966]
I new in Red language, and looks amazing, but I can't found how to install Red in Manjaro KDE 64 bits.

I tried with raw binaries but have had no success. 

BTW, Is http://red.github.io a kind of second official page?

**Comment by greggirwin** [comment]
Rather than opening tickets for questions, please visit https://gitter.im/red/red or https://gitter.im/red/red/welcome and ask there. 

Red is 32-bit only at this time. 64-bit will come when self-hosted.

**Comment by faustinoaq** [comment]
@greggirwin Ok, My bad, Thanks you for suggestion :sweat_smile:
