### ISSUE TITLE
Error code: 0xc000007b

### ISSUE THREAD

**Issue by EleRam** [red/red#2968]
![image](https://user-images.githubusercontent.com/3352418/29057120-39816d50-7c1d-11e7-80b0-75c5ae4f4da2.png)

this is my first run :(

OS: Windows 10 x64 Build 16193
Anti-Virus: Windows Defender

**Comment by dockimbel** [comment]
When submitting a ticket, you need to provide enough contextual information and steps to reproduce the issue, otherwise, there is little we can do about it.

Which Windows version is it?
Do you have any Anti-Virus running?
Where does the `red-exe.exe` comes from, and how did you run it?

**Comment by EleRam** [comment]
I'm sorry.

Windows version: 10 x64
Anti-Virus: Windows Defender

I downloaded it from [this page](http://www.red-lang.org/p/download.html) and I renamed it.

I tried to run it normally (Double click on the exe file) and using **Run As Administrator**

**Comment by qtxie** [comment]
@EleRam Mostly because the Windows Defender block or delete this file. Do you have this crush.dll file in that location?

**Comment by EleRam** [comment]
@qtxie yes! 
crush.dll exists in "C:\ProgramData\Red" dir

**Comment by geekyi** [comment]
@EleRam Try checking if doing the steps in https://github.com/red/red/issues/2897#issuecomment-315973636 help.
**Run As Administrator** may cause problems and you may have to delete the files in that folder

P.S. @qtxie do we need a tag like `platform.windows`? Would help when searching for issues

**Comment by EleRam** [comment]
@geekyi I removed that folder many times and nothing changed.

**Comment by dockimbel** [comment]
@EleRam Did you find the cause of the issue on your machine? Could you try it again with latest automatic build version of Red?
