### ISSUE TITLE
AS-COLOR not handle negative number properly

### ISSUE THREAD

**Issue by qtxie** [red/red#2970]
Maybe we should give an error on negative number.
```
>> as-color 40 -214 40
== 40.42.255
```

**Comment by geekyi** [comment]
Definitely didn't expect this:
```red
>> as-color -1 10 128
== 255.255.255
```

**Comment by meijeru** [comment]
I wonder about the different programming of `as-color` and `as-ipv4`:
```
>> source as-color
; AS-COLOR is a routine! value; its body is Red/System code.
as-color: routine [
    r [integer!] 
    g [integer!] 
    b [integer!]
][
    arr1: (b % 256 << 16) or (g % 256 << 8) or (r % 256) 
    stack/set-last as red-value! tuple/push 3 arr1 0 0
]
>> source as-ipv4
; AS-IPV4 is a routine! value; its body is Red/System code.
as-ipv4: routine [
    a [integer!] 
    b [integer!] 
    c [integer!] 
    d [integer!]
][
    arr1: (d << 24) or (c << 16) or (b << 8) or a 
    stack/set-last as red-value! tuple/push 4 arr1 0 0
]
```

**Comment by dockimbel** [comment]
> I wonder about the different programming of as-color and as-ipv4

Color components are often the result of math operations with possible out of range results. In such case, taking the modulo ensures that the value is in range.

For IP addresses, the calculations are most of the time just bitwise operations which don't result in out of range values.

**Comment by dockimbel** [comment]
Now both `as-color` and `as-ipv4` will return an error if one of the argument is negative.
