### ISSUE TITLE
wish: 'edit function for launching the default text editor on the OS

### ISSUE THREAD

**Issue by Blocode** [red/red#2971]
I wish I could do this:
```Red
>> edit
```
to launch the default text editor on the OS

**Comment by meijeru** [comment]
Is there such a thing as a default editor on each OS? I know there is a default browser, and a default e-mail client, but on Windows 10 a quick check did not reveal a default editor...

**Comment by Blocode** [comment]
on macOS, there is a default editor, just type this on terminal:
```
$ open -t
```

**Comment by PeterWAWood** [comment]
For the foreseeable future, Red will be implemented to be cross-platform. It is possible that at some future date, there will be platform specific modules. I don't see that happening before Red 1.0 is published.

You can use `call` to achieve what you want:

```
call "open -t"
call "open -t red.r
```
