### ISSUE TITLE
switch/default is missing its case argument

### ISSUE THREAD

**Issue by unchartedworks** [red/red#2973]
**Environment:**
Red: 0.6.3
OS: macOS

**Test Procedure:**
```
schedule: [
    8:30 [ftp://ftp.rebol.org/wakeup.r]
    10:30 [http://www.rebol.com/break.r]
    18:45 [ftp://ftp.rebol.org/sleep.r]
][
    http://www.google.com
]
print switch/default 08:31 schedule

```
**Expected Result:**
http://www.google.com

**Actual Result:**
*** Script Error: switch/default is missing its case argument
*** Where: switch
*** Stack:

**Comment by xqlab** [comment]
schedule is just one, the first block, not two.
You could use
```
 >> schedule:[[
[        8:30 [ftp://ftp.rebol.org/wakeup.r]
[        10:30 [http://www.rebol.com/break.r]
[        18:45 [ftp://ftp.rebol.org/sleep.r]
[    ][
[        http://www.google.com
[    ]]
== [[8:30:00 [ftp://ftp.rebol.org/wakeup.r] 10:30:00 [http://www.
>> print switch/default 08:31 schedule/1 schedule/2
http://www.google.com
>> `

**Comment by greggirwin** [comment]
@xqlab is correct. Chat on gitter at https://gitter.im/red/red/welcome or https://gitter.im/red/red if you have more questions.

**Comment by unchartedworks** [comment]
@xqlab @greggirwin Thanks. It's a surprise. It works!
