### ISSUE TITLE
FOREACH over PARENS! behaves strangely

### ISSUE THREAD

**Issue by WiseGenius** [red/red#2977]
`foreach` over `parens!` behaves strangely:

```
>> foreach [a b] quote [10 20 30 40] [?? a ?? b]
a: 10
b: 20
a: 30
b: 40
```
So far so good.

```
>> foreach [a b] quote (10 20 30 40) [?? a ?? b]
a: (10 20 30 40)
b: (10 20 30 40)
a: (30 40)
b: (30 40)
```
Strange!

```
>> foreach a quote (10 20 30 40) [?? a]
a: 10
a: 20
a: 30
a: 40
```
That looks right.

```
>> foreach [a] quote (10 20 30 40) [?? a]
a: (10 20 30 40)
a: (20 30 40)
a: (30 40)
a: (40)
```
Strange again!

**Comment by unchartedworks** [comment]
There is no regression test for this bug. :)

**Comment by dockimbel** [comment]
@unchartedworks Our resources are limited, so we write regression tests for the most important ones only as we close tickets. From time to time, we revisit some closed tickets and add more tests. Anyway, we are very welcoming contributions in that area. ;-)

**Comment by unchartedworks** [comment]
@dockimbel I see. I am still learning Red. I hope I can add some tests after I become more familiar with Red. :)
