### ISSUE TITLE
When a newline char is included in the prompt string of the ASK function

### ISSUE THREAD

**Issue by Blocode** [red/red#2978]
When a newline char is included in the prompt string of the ASK function, the prompt string will be repeatedly shows up on console every time a char is typed in.

on Windows:
```Red
>> ask "how old are you?^/"
how old are you?
how old are you?
how old are you?
30
== "30"
```

on macOS:
```Red
>> ask "how old are you?^/"
how old are you?
how old are you?
how old are you?
                30
== "30"
```

**Comment by meijeru** [comment]
Notice the difference in where the input is echoed, between win and mac. Any significance?

**Comment by gltewalt** [comment]
This is still an issue with the GUI Console, Win7 Pro, 
Red for Windows version 0.6.3 built 19-Dec-2017/15:46:56-07:00

[https://imgur.com/a/f7BBQ](url)

**Comment by qtxie** [comment]
Fixed in the new gui console.

**Comment by endo64** [comment]
@greggirwin I think we are good to close this ticket.
