### ISSUE TITLE
can't quit Red console after input invalid clause

### ISSUE THREAD

**Issue by Dieken** [red/red#2980]
Input this line into Red console and press Enter, then I can't quit Red console, Ctrl-c/d/z all doesn't work.

```
print ["aa"}
```

Red 0.6.3 on macOS 10.12.5.

**Comment by PeterWAWood** [comment]
Just for information. Pressing Esc works.
```text
>> print ["aa"}
[    
(escape)
>> 
```

**Comment by 9214** [comment]
That's because REPL patiently waits until you close opening `[` with corresponding `]`.

**Comment by Dieken** [comment]
oh, so it's not a bug, just like I didn't know how to quit Vi editor :-D

**Comment by DavidFeng** [comment]
pressing Esc works, so shall we close this?

**Comment by greggirwin** [comment]
Yes, thanks all.
