### ISSUE TITLE
`to word!` is missing check for `char!` type

### ISSUE THREAD

**Issue by toomasv** [red/red#2988]
Currently, `to word!` is making words of non-word-chars like #" ", #"^/", #"{", #";", #"2" etc., eg:
```
>> set to word! #";" 42
== 42
>> get to word! #";"
== 42
```
IMHO, the problem is here: 
https://github.com/red/red/blob/master/runtime/datatypes/word.reds#L398

**Comment by meijeru** [comment]
A suggestion: use `load-value` just like done for `string!`.
