### ISSUE TITLE
save handles function values incorrectly

### ISSUE THREAD

**Issue by meijeru** [red/red#2990]
`save` applies `mold/only` in order to yield a string that can be `load`ed back. For a function value, it applies `mold/only` also to spec and body, and this omits the outer brackets of both, so that `load` cannot handle it. 
```
>> f: func [ ][ ]
== func [ ][ ]
>> save %file.red :f
>> read %file.red
== "func"  ;; was "func " before trimming - the two blocks have disappeared
>> mold :f
== "func [ ][ ]"  ;; mold without /only will work
```

**Comment by dockimbel** [comment]
The issue is in `mold/only` when applied on functions:
```
>> mold/only func [][]
== "func "
```
Only the outer brackets should be removed by `/only`, not the nested ones.
