### ISSUE TITLE
A GUI code without [ needs: 'view] on header should cause an error on compile-time instead of on run-time.

### ISSUE THREAD

**Issue by Blocode** [red/red#2995]
```Red
Red []
view [button "OK"]
```
There is no problem while compiling. But running the generated executable code will show an error like this.
```Red 
*** Script Error: view has no value
*** Where: ???
```

**Comment by meijeru** [comment]
How should the compiler detect that this is GUI code?

**Comment by dockimbel** [comment]
The compiler cannot guess if you meant `view` from the View module, or just made a typo, or just forgot to define a function called `view` in your code...
