### ISSUE TITLE
Consider using HTTPS on red-lang.org

### ISSUE THREAD

**Issue by wiktor-k** [red/red#2996]
Hello,

Currently the main site, including [downloads](http://www.red-lang.org/p/download.html) is served using plain HTTP. Please consider switching to HTTPS ([Let's Encrypt](https://letsencrypt.org/) have free SSL certificates). Downloading executable over HTTP is insecure.

Maybe it would be also good to use [code signing](https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml) to further decrease the chance of antivirus complaining about the red executable.

Thank you for this excellent tool!

**Comment by dockimbel** [comment]
We already tried using Certum services, and they are very bad, the web site is so buggy, that you need to hack the HTML/JS code to be able to actually purchase such certificate. Then just generating the keys is a very painful process, again because of bugs. I would recommend anyone just avoiding Certum at all, and using a more professional company to acquire a certificate.

**Comment by wiktor-k** [comment]
Thanks for the context, now I understand your position better.

I think offering HTTPS along with HTTP on red.org could be a good middle ground, people that want encrypted traffic could still manually use https: while people in China can keep using http:.

Another option would be to provide binaries in GitHub Releases page (not just the source code). Since GitHub is using https that could be the easiest way.

**Comment by dockimbel** [comment]
> Another option would be to provide binaries in GitHub Releases page (not just the source code). Since GitHub is using https that could be the easiest way.

Not an option for us as we need easy access to rich download stats (unless GitHub Releases page now provides such information?).

**Comment by wiktor-k** [comment]
I don't think they do.

So maybe just integrity hashes (SHA256) for binaries on GitHub releases? That'd be secure as hashes would be served on HTTPS and you wouldn't have to setup HTTPS on your server.

**Comment by dockimbel** [comment]
@wiktor-k Thanks, that's an interesting and cheap option we need to look into.

**Comment by dockimbel** [comment]
We have switched the download section to HTTPS since a month.
We have just switched the main red-lang.org site to HTTPS, as Google just enabled today that feature on Blogger for custom domains. \o/
