### ISSUE TITLE
WISH: provide compile time option to choose View backend

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#2999]
In order to build a Red console to test the GTK backend on macOS, it is necessary to modify `platform.red` to include the GTK3 backend instead of the macOS backend and other items.

Please could a compile-time option be provided to override the "platform default" backend?

**Comment by dockimbel** [comment]
It's already there (added after 0.6.3 release): https://github.com/red/red/blob/master/system/config.r#L35
