### ISSUE TITLE
View: window is resizeable without 'resize flag

### ISSUE THREAD

**Issue by 9214** [red/red#3000]
Per [documentation](https://doc.red-lang.org/en/view.html#_window):
> * resize: enable window resizing (default is fixed size, not resizeable).

But

![view](https://user-images.githubusercontent.com/15716466/29744786-6bb0f3f2-8ac5-11e7-83a8-6b94b73285fb.gif)

**Comment by meijeru** [comment]
looks like a regression; on my older Windows build it does not do this
