### ISSUE TITLE
WISH: /SKIP refinement for REVERSE

### ISSUE THREAD

**Issue by 9214** [red/red#3004]
I wish `reverse` could treat series as a bunch of fixed-size records:
```Red
>> reverse/skip [a 1 b 2] 2
== [b 2 a 1]
```
perhaps `/by` is a better name?

**Comment by meijeru** [comment]
`/skip`  is appropriate: it tells what it does, in the same way as `sort` and all the others that have such a refinement

**Comment by greggirwin** [comment]
@toomasv posted a mezz version in gitter chat I think. Though having it as standard would be better. I don't have one in my old toolbox, but think I needed this a couple times through the years.

**Comment by dockimbel** [comment]
Agreed. We should also add the missing `/part` option, which is present in Rebol.

**Comment by toomasv** [comment]
Here is my version:
```
reverse: func [
    series /skip size /part length /local i tuple
][
	switch type?/word series [
		pair! [return to-pair reduce [series/2 series/1]]
		tuple! [tuple: clear [] repeat i length? series [append tuple pick series i] series: copy tuple tuple: yes]
	]
    size: any [size 1]
    either 0 = ((length? series) % size) [
        length: any [length length? series]
        i: 1
        loop (length / size - 1) [
            i: i + size
            series: at head series i
            insert head series take/part series size
        ] 
        series: head series
    ][cause-error 'user 'message ["Wrong length of series or skip!"]]
	either tuple [to-tuple series][series]
]
```

**Comment by 9214** [comment]
I took the role of self-serving wish fairy and granted myself what I asked for 3 years ago 🧚‍♂️ Hope that's OK.
