### ISSUE TITLE
first of a get-path! value gives a word! instead of a get-word!

### ISSUE THREAD

**Issue by meijeru** [red/red#3007]
This came up in the red/welcome chat:
```
>> type? quote :read/lines
== get-path!
>> type? first quote :read/lines
== word!
```
Why isn't the type `get-word!`? As it is, one has to resort to elaborate programming to extract the `get-word!` value from the `get-path!` value...

**Comment by dockimbel** [comment]
The "get" part of `get-path!` is a property of the whole path, not of one of its elements. `:read/lines` is a `get-path!` series made out of two `word!` values.

**Comment by Oldes** [comment]
```
>> first quote :read/lines
== read
>> second quote :read/lines
== lines
```
