### ISSUE TITLE
Backdrop of Container is not properly filled under macOS

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#3022]
When setting the backdrop of a container in macOS, the bottom two corners are not filled with the backdrop colour.

It can be seen by running this script:

```text
Red[
	needs: View
]
view [
	title ""
	size 232x300
	backdrop 230.230.230.192
	across
	text "0" right 230 font-size 24
	return
]
```
macOS and Windows screenshots of the output are attached.
<img width="316" alt="macos backdrop" src="https://user-images.githubusercontent.com/697434/30237168-eb5a25bc-955e-11e7-9c99-f7f44324aeaf.png">

<img width="264" alt="windows backdrop" src="https://user-images.githubusercontent.com/697434/30237169-f694c9a0-955e-11e7-9751-fa13b563bf54.png">

**Comment by qtxie** [comment]
Fixed in commit 73d8342fc71bc0c115cc693020e00a66ce743d3d .
