### ISSUE TITLE
macOS View programs have no Quit menu option and do not respond to CMD-q

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#3024]
On macOS, the menu for a View program doesn't include a Quit option. View programs don't respond to CMD-q.

Under Windows, View programs have a quit option and respond to Alt-F4
<img width="484" alt="macos menu" src="https://user-images.githubusercontent.com/697434/30245092-b8c69ace-9601-11e7-8a95-3f8d32c37295.png">

**Comment by dockimbel** [comment]
The "Quit" option is now present. For CMD-q, the menu needs to be opened, then it works fine.
