### ISSUE TITLE
menu on macOS 

### ISSUE THREAD

**Issue by ralfwenske** [red/red#3025]
menus on macOS only respond after switching to another app (window) and back.

**Comment by qtxie** [comment]
Do you use the latest version or 0.6.3 ?

**Comment by ralfwenske** [comment]
qtixie,
I just found out: 
the above issue happens when I start the app on macOS from Visual Studio (F6 command).
When I start from console the menu is immediately accessible (is working ok).
(Starting on Win 10 via Visual Studio also is working as expected (ok).

**Comment by PeterWAWood** [comment]
@qtxie I see this behaviour on macOS using the latest master.

**Comment by ralfwenske** [comment]
On macOS when I compile the app and start the app from console I also need to first activate another window before I can use the menus. 
Yet when I start the code via REPL the menus are immediately functioning.
REPL and compiled app on Win10 both work ok.

**Comment by qtxie** [comment]
Thanks. I'll try to fix it.

**Comment by ralfwenske** [comment]
Menus now working am macOS
