### ISSUE TITLE
Bitdefender - red-063 false positive

### ISSUE THREAD

**Issue by OneArb** [red/red#3026]
I removed Bitdefender without taking note of the Trojan name.

Bitdefender kept quarantine exe regardless of my white listing it.

Thanks

**Comment by dockimbel** [comment]
Using VirusTotal, it seems to be reporting as clean by Bitdefender: 
https://www.virustotal.com/#/file/105d0f7b009a802a35a636c5dbedc69e89477fd62b6ba77690845fd78d436171/detection

If that happens again, try submitting a false posivite report to Bitdefender. If that's not enough, you can re-open this ticket.

**Comment by OneArb** [comment]
Can you virustotal gui-console-2017-8-3-49893.exe which was also getting blocked?

Also crush-2017-8-3-49893.dll
