### ISSUE TITLE
Setting multiple face values does not update display

### ISSUE THREAD

**Issue by rgchris** [red/red#3048]
I have the following code:

```
view also ui: layout [
    below
    field 200 "Field"

    button "Button 1" [
        set list-of-fields/1 "Button 1"
    ]

    button "Button 2" [
        set list-of-fields ["Button 2"]
        probe face/parent/pane/1/text
    ]
]

list-of-fields: reduce [in ui/pane/1 'text]
```

On clicking the first button, the display is updated correctly. However, on clicking the second button the display does not change despite the appropriate text value having been set.

**Comment by dockimbel** [comment]
`set` does the object events checking for single word setting, multiple words setting should too.
