### ISSUE TITLE
Access a layout/face while in construction

### ISSUE THREAD

**Issue by rgchris** [red/red#3049]
Would like to be able to access the current layout/panel in situ to be able to assess it's current state.

For example:

```
fields: []

view [
    field 200 "Content"
    field 200 "More Content"
    do [
        foreach kid face/pane [
            append fields in kid 'text
        ]
    ]
    button [
        probe reduce fields
    ]
]
```

As to faces, a WITH feature that allows access to the face's internals would be useful as well.

```
fields: []

view  [
    field with [append fields quote 'name append fields 'text]
    field with [append fields quote 'city append fields 'text]
    button [probe reduce fields]
]
```

The aim would amongst other things be to assist in a few data-driven operations.

**Comment by greggirwin** [comment]
For the first part, it looks like you want an implicit `face` reference as the access method, correct? One issue, from a quick look at the code, is that the VID spec is processed, but the panel's pane is only set after that's all done. The working area is a local var in the `layout` func. So the `do` may be bound to the panel, or access it as in your example, but the faces aren't there yet.

**Comment by greggirwin** [comment]
What does this wish look like if you reformulate it without the mechanism as the wish, but the feature need? e.g., *I want to "X Y Z" so I can build data driven apps that ...*

**Comment by dockimbel** [comment]
You can use `self` in `do [...]` blocks to refer to the parent panel object. For the parent's `pane` access, it is indeed set at a later stage, though it should be possible to set it earlier without any side-effect on the processing.

**Comment by dockimbel** [comment]
Please separate different wishes in different tickets.

**Comment by dockimbel** [comment]
So the right code is:
```
fields: []

view [
    field 200 "Content"
    field 200 "More Content"
    do [
        foreach kid pane [
            append fields in kid 'text
        ]
    ]
    button [
        probe reduce fields
    ]
]
```

An alternative version:
```
view [
    field 200 "Content"
    field 200 "More Content"
    do [
    	fields: collect [foreach-face self [keep in face 'text]]
    ]
    button [
        probe reduce fields
    ]
]
```

**Comment by dockimbel** [comment]
`with` was a pending feature on my todo-list for VID, so I will add it also now.
