### ISSUE TITLE
Red/System: rules for context names seem overly restrictive

### ISSUE THREAD

**Issue by meijeru** [red/red#305]
It turns out that context names must not have been defined anywhere except as outer context!

Thus

```
c: 1 f: func [][c: context [a: 1]]
```

gives an eror even though

```
c: context [a: 1] f: func [/local c][c: 1]
```

is perfectly acceptable. In both cases, the scope of any use of `c` is easily identifiable. 

What's more, the following is allowed:

```
c: context [c: context [c: 1]]
```

**Comment by Crystal-RainSlide** [comment]
Re-running those 3 lines of code in Red 0.6.4 under Windows:
``` Red
>> c: 1 f: func [][c: context [a: 1]]
== func [][c: context [a: 1]]
```
``` Red
>> c: context [a: 1] f: func [/local c][c: 1]
== func [/local c][c: 1]
```
``` Red
>> c: context [c: context [c: 1]]
== make object! [
    c: make object! [
        c: 1
  ...
>> 
```
Molded result of the last one:
``` Red
make object! [
    c: make object! [
        c: 1
    ]
]
```
Is this issue resolved already?

**Comment by 9214** [comment]
@Crystal-RainSlide you're confusing Red and Red/System.

**Comment by dockimbel** [comment]
I see nothing to fix or change in the code examples. Contexts cannot be defined in functions, someone can add that to R/S docs if one thinks it is worth it.
