### ISSUE TITLE
Add a 'product modifier to faces and VID spec

### ISSUE THREAD

**Issue by rgchris** [red/red#3051]
This could work in lieu of a formal validation language. This could sit between the transformation between `face/text` and `face/data` and moderate the product of that element.

```
view layout [
    field 'name 500  ; see #3050 for proposed lit-word! use
    field 'phone 500 product [
        if parse text ["+" some digit][
            to issue! text
        ]
    ]
]
```

PRODUCT is a literal description of the function—there may be a more appropriate name.

**Comment by rgchris** [comment]
Quite possibly an error!—intentional or not—returned from this function could trigger the face's error visual state.

**Comment by greggirwin** [comment]
It seems like you would have to write the func to go both directions, yes? And only applies to free-form input faces, correct? For other styles, the standard actors provide all we need. Maybe I don't see the value, compared to creating a style that uses change detection via standard actors.

**Comment by rgchris** [comment]
It's not necessarily just free-form input, but even if it were the idea is that a face has enough information to format/validate its own unit of data.
As to the actors—the closest would be **on-change**, though a more appropriate name would be **on-get** where the code is only ran when trying to obtain the face's value.

**Comment by planetsizecpu** [comment]
@rgchris @greggirwin   I remember some old text-mode lang validations like this:

!temp value_int4,"INT-VALUE",i4,########          <-- digit mask
!temp value_real8,"REAL-VALUE",r8,######00.00 <-- also forced 0 filling places
!temp value_alpha10,"TEXT-VALUE",a10,u             <--  "u" for uppercase "s" for passwords displaying "*"

So simply! even you could define this in data dictionary for indexed files fields  
old times where easy.

**Comment by greggirwin** [comment]
We can currently use `extra` to hold information about validation and formatting, to experiment with. Masked input can be very helpful, but is hard to get right. e.g., do invalid keys just fail to do anything or, along the lines Chris is thinking, do we just change the state of the face(s) if the input doesn't match a format mask? And use them to trigger the ability to save data and such.

**Comment by PeterWAWood** [comment]
Following the introduction of the [Red REP repository for enhancements and wishes](https://gitter.im/red/red?at=5adfeed527c509a7744a3dc8), this issue is being closed.

If you believe that your wish is still valid, please open a new issue for it in the new [red/REP repo](https://github.com/red/REP). It would help if you could include a link to this issue when opening an issue in the REP repository.
