### ISSUE TITLE
Windows opened with view/no-wait do not respond to unview on macOS

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#3057]
On macOS, Windows opened with view/no-wait do not respond to unview or to mouse-clicks on the window minimise and close buttons.
<img width="756" alt="unview issue" src="https://user-images.githubusercontent.com/697434/30842401-bc370530-a2b4-11e7-9a53-52c2a02748f3.png">

**Comment by qtxie** [comment]
It caused by no event loop is running. The same behaviour on Windows when using CLI console.

**Comment by qtxie** [comment]
Works on GUI console.

**Comment by qtxie** [comment]
`unview` works fine on macOS 10.14 on both CLI console and GUI console.
