### ISSUE TITLE
`request-dir` and `request-file` ignore string! values

### ISSUE THREAD

**Issue by endo64** [red/red#3074]
`request-dir` and `request-file` functions accept `string!` values for `/dir` and `/file` refinements respectively but silently ignores them. `file!` values work as expected.

Steps to reproduce:
`request-dir/dir "C:\windows\"`
`request-file/file "red.exe"`

I've fixed this PR #3138

**Comment by greggirwin** [comment]
@endo64 I just merged PR #3138. Please confirm it all looks good once built and either close this ticket or follow up with me and we'll revisit. Thanks!

**Comment by endo64** [comment]
Hi @greggirwin I built and tested on Win10, it works as expected, I'm closing this issue.
