### ISSUE TITLE
Windows compilation of script failed with "undefined word input"

### ISSUE THREAD

**Issue by nd9600** [red/red#3078]
### Expected behavior
Compilation succeeded

### Actual behavior
Compilation failed with the error `undefined word input`

### Steps to reproduce the problem

Compile [this file](https://gist.github.com/nd9600/3d8c1e92e39fe76c29dbba7c0018104e) on Windows:
`red.bat -c x.red`, `red.bat -c -r x.red`, `red.bat -c -r -t Linux x.red` all fail with the same error.

Is it not possible to compile files that need user input to run yet?

I tried to compile it on Red 0.6.2 and got the same error

### Red version and build date, operating system with version.
`Red for Windows version 0.6.3 built 8-Oct-2017/21:50:01+01:00`, Windows 10

**Comment by 9214** [comment]
`ask` and `input` are not part of Red runtime library (yet), they're only available from console and interpreter. 

If you want to use them you, need to include proper files with functions definitions. See [`how to compile ask?`](https://github.com/red/red/wiki/Guru-Meditations#how-to-compile-ask) entry in wiki.

**Comment by hamzamu** [comment]
> `ask` and `input` are not part of Red runtime library (yet), they're only available from console and interpreter.
> 
> If you want to use them, you need to include proper files with functions definitions. See [`how to compile ask?`](https://github.com/red/red/wiki/Guru-Meditations#how-to-compile-ask) entry in wiki.

Hello, I know this is a long issue, but is it resolved yet, Also the wiki entry is empty. Is there any related documents?

**Comment by hiiamboris** [comment]
https://github.com/red/red/wiki/[DOC]-Guru-Meditations#how-to-compile-ask

**Comment by hamzamu** [comment]
> [https://github.com/red/red/wiki/[DOC]-Guru-Meditations#how-to-compile-ask](https://github.com/red/red/wiki/%5BDOC%5D-Guru-Meditations#how-to-compile-ask)

Thank you

**Comment by hamzamu** [comment]
> [https://github.com/red/red/wiki/[DOC]-Guru-Meditations#how-to-compile-ask](https://github.com/red/red/wiki/%5BDOC%5D-Guru-Meditations#how-to-compile-ask)

I tried and it didn't work. I am using Solus Linux, I am still getting 


`*** Compilation Error: undefined word ask 
`

**Comment by 9214** [comment]
@hamzamu please use [community chat](https://gitter.im/red/help) if you need any assistance with that. The issue tracker is mainly for bug reporting and collaboration with contributors.
