### ISSUE TITLE
macOS High Sierra APFS

### ISSUE THREAD

**Issue by JenniferLee520** [red/red#3079]
I've just upgraded my macOS to the latest version "macOS High Sierra 10.13". After running my old Red code, I got an issue which has never happened before. I guess it's caused by the new File System "APFS".

```Red
>> do %bcode.red
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Common/ChunkCompression.cpp:50: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/Frameworks/AppKit.framework/Resources/Base.lproj/NSTextTouchBarItems.nib'
```

**Comment by x8x** [comment]
@JenniferLee520 Could you please provide some code to reproduce the issue?

**Comment by JenniferLee520** [comment]
It's not easy to reproduce and locate the bug. close it for now until I have more info.
