### ISSUE TITLE
as-pair converts floats to integers

### ISSUE THREAD

**Issue by BrianOtto** [red/red#3083]
I am working on a project where I parse SVG files and use the Draw dialect to render them to the screen. SVGs typically have floating point values for their coordinates and they are getting converted to integers when I use as-pair.

`probe as-pair 1.123 1.789`

### Expected Behavior
`1.123x1.789`

### Actual Behavior
`1x1`

### Red version and build date, operating system with version.
red 0.6.3 on Windows 7 Pro SP1 (build date = week or two ago)

**Comment by DideC** [comment]
floating pair is not implemented in Red. Actually it's still in a "wish" status.

For your convertion, you must multiply all coordinates by 1000 and use a 'scale command to reduce the scale by 1000 at the beginning of your drawing.
`as-scaled-pair: func [x y][as-pair 1000 * x 1000 * y]`

**Comment by BrianOtto** [comment]
OK, I see, thank you for the workaround !

**Comment by dockimbel** [comment]
```
Expected Behavior
1.123x1.789
```

Pairs do not support decimal number for now, so it can't be an expectation.
