### ISSUE TITLE
Integers containing group seps lex as floats

### ISSUE THREAD

**Issue by greggirwin** [red/red#3088]
Looks like a recent change altered lexing of numbers with group seps. Including a group sep now loads as a float, rather than an int. Build from 15-Oct didn't do this.

Just happened to run a script here that failed, because I used a group sep and repeat choked on the resulting float.

### Expected behavior
```
>> n: 100000
== 100000
>> n: 100'000
== 100000
```

### Actual behavior
```
>> n: 100000
== 100000
>> n: 100'000
== 100000.0
```

### Steps to reproduce the problem
See above. Enter an integer value containing at least one group separator.

### Red version and build date, operating system with version.
>> print [system/version system/build/date]
0.6.3 24-Oct-2017/9:52:34-06:00

Windows 7

**Comment by dockimbel** [comment]
Unfortunate regression.
