### ISSUE TITLE
CALL/INPUT crashed cli

### ISSUE THREAD

**Issue by AT-Aoi** [red/red#3090]
### Expected behavior

Report an exception in console

### Actual behavior

Crashed

### Steps to reproduce the problem

```
>> call/input %a "cd"

*** Runtime Error 1: access violation
*** at: 77E7EBD0h
```

The file `%a` doesn't exist.

### Red version and build date, operating system with version.

Red for Windows version 0.6.3 built 29-Oct-2017/2:07:07+08:00

Windows 10

**Comment by qtxie** [comment]
The CLI console works fine. Only the gui console crashes.
