### ISSUE TITLE
VIEW: modifying DRAW block inside WITH body does not cause any visual changes

### ISSUE THREAD

**Issue by 9214** [red/red#3091]
Fire up the snippet bellow and move the slider - as you can see, `draw` block is updated, but radius of a circle remains static:

```Red
view [
    b: base 
        with [draw: [fill-pen red circle 40x40 20]]
        react later [
            b/draw/5: to integer! 50 * s/data
            probe b/draw
        ]
    return
    s: slider 
]
```

However, I expect it to behave exactly as:
```Red
view [
    b: base 
        draw [fill-pen red circle 40x40 20]
        react later [
            b/draw/5: to integer! 50 * s/data
            probe b/draw
        ]
    return
    s: slider 
]
```

Perhaps it's related not only to `draw` block, but to any `series!` inside `with` body. Red version:
```Red
>> about
Red for Windows version 0.6.3 built 21-Oct-2017/23:57:00+05:00
```

**Comment by dockimbel** [comment]
Your second example as a typo, it should be `draw` instead of `draw:` in the VID block.

**Comment by 9214** [comment]
@dockimbel your comment has a typo, it should be `has` instead of `as` in the 4th word :nerd_face:

**Comment by dockimbel** [comment]
Making a typo while pointing out a typo... :roll_eyes:
