### ISSUE TITLE
Access violation when creating errors improperly

### ISSUE THREAD

**Issue by wasamasa** [red/red#3094]
### Expected behavior

Even if I don't get the block argument of `make error!` right, the console stays open.

### Actual behavior

The console crashes with "Runtime Error 1: access violation"

### Steps to reproduce the problem

```
red
--== Red 0.6.3 ==-- 
Type HELP for starting information. 

>> make error! [user "Test"]

*** Runtime Error 1: access violation
*** at: 08073FBAh
```

### Red version and build date, operating system with version.

Snapshot downloaded today from http://static.red-lang.org/dl/auto/linux/red-latest running on Arch Linux.

**Comment by qtxie** [comment]
No crashes on Windows.

**Comment by qtxie** [comment]
No crashes on Windows.
