### ISSUE TITLE
request-font selects incorrect font size

### ISSUE THREAD

**Issue by endo64** [red/red#3097]
### Expected behavior
Font requester should open with selected font size.

### Actual behavior

Font requester window opens with a font bigger than the provided font size.

### Steps to reproduce the problem

Open font requester by providing a font object with size 10. Just click on Ok, it returns a font object with size 12:

>> request-font/font make font! [name: "Consolas" size: 10]
== make object! [
    name: "Consolas"
    size: 12  ; <<<<

### Red version and build date, operating system with version.

Latest Red compiled from source on 2017-11-05
Win10 x64

**Comment by greggirwin** [comment]
Works correctly on Win7, x64, just FYI.

**Comment by meijeru** [comment]
Works correctly on Win19, x64, build 9-Aug

**Comment by endo64** [comment]
Interesting, I just tested on Win8 x64 it worked. I realized that issue while trying to change font settings of GUI console, every time I open the font settings window and click Ok, font size is getting bigger.

**Comment by endo64** [comment]
I confirm that this issue appears on Win10 x64, Red build 2-Dec-2017/10:04:41+03:00 (tested with both CLI & GUI console)
![3097](https://user-images.githubusercontent.com/840604/33799730-9180d1c2-dd42-11e7-8dce-e794b73848b8.gif)

**Comment by endo64** [comment]
On Win10 x64 this issue is still there and affects font settings on GUI console

**Comment by qtxie** [comment]
Are you using a high DPI screen?

**Comment by endo64** [comment]
I just checked, correct this happens only if I use high DPI, mine was 125%.

**Comment by hiiamboris** [comment]
Works fine for me W7x64 with 125% scaling.

**Comment by endo64** [comment]
I just checked, it works for all DPI settings on Win10, we are good to close this ticket as it looks fixed already.
