### ISSUE TITLE
`find` implicitly casts char to integer

### ISSUE THREAD

**Issue by toomasv** [red/red#3100]
### Expected behavior
```
>> find [103 23 #"g" 56 11 #"8"] #"g"
== [#"g" 56 11 #"8"]
```
### Actual behavior
```
>> find [103 23 #"g" 56 11 #"8"] #"g"
== [103 23 #"g" 56 11 #"8"]
```
### Steps to reproduce the problem
Try to find `char` value in a block containing its integer value before it.
### Red version and build date, operating system with version.
```
>> system/version
== 0.6.3
>> system/build
== make object! [
    date: 7-Nov-2017/23:05:16+02:00
```
Win10Pro

**Comment by dockimbel** [comment]
@qtxie I think we need a `COMP_FIND` mode.

**Comment by qtxie** [comment]
@dockimbel Yes. I'll implement it.

**Comment by qtxie** [comment]
@Yes. I'll implement it.
