### ISSUE TITLE
Error Message change for func contexts

### ISSUE THREAD

**Issue by greggirwin** [red/red#3103]
### Expected (desired) behavior

`context for x is not available`

See: https://github.com/red/red/wiki/Guru-Meditations#function-contexts

### Actual behavior

`x is not in the specified context`

### Steps to reproduce the problem

```
>> do bind [x] has [x][x: 1]
*** Script Error: x is not in the specified context
*** Where: do
*** Stack:
```

### Red version and build date, operating system with version.

0.6.3, as of 10-Nov-2017

**Comment by dockimbel** [comment]
Implemented by commit [212a6c43](https://github.com/red/red/commit/6413a38bbcea6920978f7db4953de751212a6c43).
