### ISSUE TITLE
Including text facet in style causes it to be `load`ed

### ISSUE THREAD

**Issue by greggirwin** [red/red#3109]
### Expected behavior

@qtxie says this is by design, so it currently is the expected behavior, but it was surprising to me. I expected the text to be used verbatim, which is not the case.

### Actual behavior

Setting a text value in a style, which is loadable, is loaded and formed, rather than being used as the literal string.

### Steps to reproduce the problem
```
view [
    style num: text ".01"
    num  text ".01" return

    style txt: text "2017-12-24"
    txt  text "2017-12-24" return

    style fld: field "2017-12-24"
    fld field "2017-12-24" return

    style blk: text {"a b c"}
    blk  text {"a b c"} return
]
```
### Red version and build date, operating system with version.

0.6.3 (latest source). Windows 7 x64.

**Comment by qtxie** [comment]
Adds a screenshot of the view window:
![20171116110546](https://user-images.githubusercontent.com/1673525/32871808-3addf5a2-cabe-11e7-89f2-ccf2995d2e2f.png)

**Comment by dockimbel** [comment]
It seems unaltered here when using the 0.6.4 branch.

**Comment by greggirwin** [comment]
![image](https://user-images.githubusercontent.com/460079/32877686-f75bd5be-ca5f-11e7-8d61-d05bb14d9aa2.png)
