### ISSUE TITLE
get/any causes an error when accessing non-existant path

### ISSUE THREAD

**Issue by nickkoro02** [red/red#3112]
### Expected behavior
```
>> foo: context [bar: 5]
== make object! [
    bar: 5
]
>> type? get/any 'foo/something
== unset!
```
### Actual behavior
```
>> foo: context [bar: 5]
== make object! [
    bar: 5
]
>> type? get/any 'foo/something
*** Script Error: cannot access something in path foo/something
*** Where: get
*** Stack:

>>
```
### Steps to reproduce the problem
See expected and actual behavior
### Red version and build date, operating system with version.
Windows 10 x64
```
>> system/build
== make object! [
    date: 12-Aug-2017/21:38:44+02:00
    ...
```

**Comment by meijeru** [comment]
With due respect, I think the error message is both clear and to the point. Why should non-existant path expressions be unset ?

**Comment by greggirwin** [comment]
The results are interesting, and something to be doc'd, if the current behavior is by design.

```
>> foo: context [bar: 5]
== make object! [
    bar: 5
]
>> type? get/any 'foo/something
*** Script Error: cannot access something in path foo/something
*** Where: get
*** Stack:  

>> type? get/any 'baz/something
*** Script Error: baz has no value
*** Where: get
*** Stack:  

>> type? get/any 'bap
== unset!
```

**Comment by meijeru** [comment]
This follows strictly the logic that I stated above: a single word may be unset, a head word that is unset gives an error (because the remaining part of the expression cannot be analyzed) and a non-existant field name gives another error.

**Comment by greggirwin** [comment]
My thought was that if a word returns unset, then a path with that word at the head should also return unset. We can't really use this standard error (`not-in-context: ["context for" :arg1 "is not available"]`) for the first case, because it could just be a block, which works like this:
```
>> foo: [bar: 5]
== [bar: 5]
>> type? get/any 'foo/something
== none!
```
Which will never return unset, AFAICT. 

Another alternative might be to adjust the doc string for `/any` to point out that paths ignore that refinement.

**Comment by meijeru** [comment]
A path with an unset word at the head could possibly return unset, but what the submitter of this issue wants, is that a non-existing field name yields unset - that is different.

**Comment by 9214** [comment]
A food for thought:
```Red
>> foo: context [bar: 5]
== make object! [
    bar: 5
]
>> in foo 'bar
== bar
>> in foo 'something
== none
```

**Comment by meijeru** [comment]
In your last example, though, the type of `'something` is `unset!`, independent of the fact that it is the second element in a path; the interpretation of `'something` is not determined, in this case, by whatever `foo` is.

**Comment by dockimbel** [comment]
Current behavior is intended and correct. Rebol3 follows the same rules.
