### ISSUE TITLE
face takes 2 times to update

### ISSUE THREAD

**Issue by githubnyn** [red/red#3114]
### Expected behavior
 face should be updated on the first click
### Actual behavior
you need to click on the face twice in order to update it and bring it to the front
### Red version and build date, operating system with version
red version 0.6.3 - MacOS 10.13.1

```
move-to-top: func [face][move find face/parent/pane face tail face/parent/pane]

win: layout [
    a1: base 200x200 gold loose
    on-down [move-to-top face]
    pad -100x0
    a2: base 200x200 brick loose
    on-down [move-to-top face]
    pad -50x0
    a2: base 200x200 loose
    on-down [move-to-top face]
]
view win

```

**Comment by meijeru** [comment]
Two faces are given the name `a2` ???
