### ISSUE TITLE
Add support for x86_64 machines.

### ISSUE THREAD

**Issue by luis-lavaire** [red/red#3115]
I was guessing if it could be possible to add native support for 64-bit processors.

**Comment by greggirwin** [comment]
64-bit support will come after Red is self-hosted. After v1.0.

**Comment by luis-lavaire** [comment]
Oh, thanks @greggirwin!

**Comment by Dialga** [comment]
This should be given higher priority because most major Linux distributions are dropping or phasing out 32bit support.

**Comment by greggirwin** [comment]
@Dialga are Linux users willing to pay to have it done? It's not that we don't want to, just that we have limited resources and have to make the project sustainable. There are plans in place for this though.
