### ISSUE TITLE
React errors keep being re-thrown

### ISSUE THREAD

**Issue by mikeyaunish** [red/red#3129]
### Expected behavior
```
>> view [ a: field b: field react [ bb/text: a/text ] ]
*** Script Error: bb has no value
*** Where: set-path
*** Stack: view layout react  
>> view [ a: field b: field react [ b/text: a/text ] ]
```
Program should now run sucsessfully 
### Actual behavior
```
>> view [ a: field b: field react [ bb/text: a/text ] ]
*** Script Error: bb has no value
*** Where: set-path
*** Stack: view layout react  

>> view [ a: field b: field react [ b/text: a/text ] ]
*** Script Error: bb has no value
*** Where: set-path
*** Stack: view layout react  
```
The original syntax error is thrown again, even when the error has been corrected.
### Steps to reproduce the problem
As shown above
### Red version and build date, operating system with version.
Red version: 0.6.3 
date: 22-Nov-2017/23:06:38-07:00
Windows 10 Pro

**Comment by greggirwin** [comment]
`Clear-reactions` doesn't help. After running the above `view` example after clearing, the relation shows back up in `dump-reactions` output.

**Comment by dockimbel** [comment]
Good finding!
