### ISSUE TITLE
VID: camera - GUI Console freeze when select is omitted in view [camera select 1]

### ISSUE THREAD

**Issue by gltewalt** [red/red#3130]
### Expected behavior
If a mistake is made and `camera 1` is written instead of `camera select 1`
I expect view to treat it as a size and produce a camera object with size: 1x250
```
view [camera 1]
```

### Actual behavior
Will freeze GUI Console and GUI Console can not be killed until the computer is put back into sleep again or is rebooted.
Will freeze cli console but it can be escaped back to CMD.exe
### Steps to reproduce the problem
1) With GUI Console left open, put computer in to sleep mode. 2) Awaken computer, then type `view [camera 1]` in the GUI Console.
### Red version and build date, operating system with version.
Red for Windows version 0.6.3 built 1-Dec-2017/16:58:47-07:00
Win7 Pro 64bit

**Comment by qtxie** [comment]
I cannot reproduce it. @gltewalt Does this issue still existing?

**Comment by gltewalt** [comment]
It no longer freezes with new GUI Console.
