### ISSUE TITLE
replace/all infinite loop

### ISSUE THREAD

**Issue by pijoter** [red/red#3132]
### Expected behavior
>> replace/all "test" charset [#"t" #"e"] ""
== "s"
### Actual behavior
infinite loop 
### Steps to reproduce the problem
as above
### Red version and build date, operating system with version.
red 0.63
25-Nov-2017/16:24:59+01:00
Windows 10.0.16299.64

**Comment by meijeru** [comment]
Not a recent problem, confirmed also on W10 of 9-Aug-2017.
