### ISSUE TITLE
usage of MOVE/PART with /PART argument greater than or equal to series length crashes the console

### ISSUE THREAD

**Issue by 9214** [red/red#3136]
### Expected behavior
Hard to tell, I think `[1 2 3]` should be returned without a change.
### Actual behavior
GUI console crashed, CLI REPL in VSCode produced:
```Red
*** Runtime Error 16: invalid virtual address
*** at: F76F7A6Fh
```
### Steps to reproduce the problem
```Red
>> x: [1 2 3]
== [1 2 3]
>> move/part x next x length? x
```
### Red version and build date, operating system with version.
Applies to Linux version too.
```Red
>> about
Red for Windows version 0.6.3 built 9-Dec-2017/18:21:06+05:00
```

**Comment by greggirwin** [comment]
Crash confirmed here.
