### ISSUE TITLE
false positive virus - red-063.exe - gui-console-2017-8-3-49893.exe - 7/67 Virustotal

### ISSUE THREAD

**Issue by emaines** [red/red#3137]
I  get a virus alert for gui-console-2017-8-3-49893.exe with Avast and 7/67 AV softwares on virustotal. https://www.virustotal.com/#/file/6469f90889846177c57b70be2f42a2734e9dab350cbe868aa16ec19e8a2ab613/detection

Cheers

**Comment by dockimbel** [comment]
Those are the usual suspects, which are doing a bad job, despite our attemtps to make them improve their heuristics. Avira and AVAST should be avoided, try to switch to a better AV.
