### ISSUE TITLE
defining a word `print:` causes access violation

### ISSUE THREAD

**Issue by roobie** [red/red#3140]
Forgive me if this issue already has been reported, but I was not able to find any that looked exactly like this, so here goes.

### Expected behavior
Either a more descriptive error message or that the code works as "intended"

### Actual behavior

Shell input/output

```
PS D:\> c:\applications\red-063.exe --cli d:\scratch.red

*** Runtime Error 1: access violation
*** at: 00000000h
```

### Steps to reproduce the problem

Evaluate this code:

```
Red [
    Title: "fault"
]

f: func [a [series!]][
    print: length? a
]

print f "a"
```

### Red version and build date, operating system with version.

Red 0.6.3
Windows 10 64-bit 1511 10586.839

**Comment by greggirwin** [comment]
I just built a fresh CLI console here and it seems OK.
```
>> f: func [a [series!]][
[        print: length? a
[    ]
== func [a [series!]][print: length? a]
>> f
*** Script Error: f is missing its a argument
*** Where: f
*** Stack: f

>> f "a"
== 1
>> print f "a"
== 1
```

Also in a GUI console:
```
>> f: func [a [series!]][
[        print: length? a
[    ]
== func [a [series!]][print: length? a]
>> f "a"
== 1
>> print f "a"
== 1
```

However, if I don't call `f "a"` first, then it does segfault.

If you use `function`, to capture the reassignment of `print`, it eliminates the problem. So it seems to be reassigning `print` while it's on the stack that's the problem.

**Comment by greggirwin** [comment]
That's a good catch @roobie. Thanks.

**Comment by roobie** [comment]
Happy to be of help.

I too can work around the segfault if I call `f "a"` before `print f "a"`.

**Comment by dockimbel** [comment]
System words protection is scheduled to be supported in 0.8.
