### ISSUE TITLE
trim/lines resulting in vertical block

### ISSUE THREAD

**Issue by Phryxe** [red/red#3143]
### Expected behavior
```
x: {
    a? 
    b ,
    c .
    d; 
    e
}
replace/all x charset ",.;?" ""
trim/lines x
x: split x " "
== ["a" "b" "c" "d" "e"]
```
### Actual behavior
Not sure if this is a feature or something that might cause trouble later on.
```
x: {
    a? 
    b ,
    c .
    d; 
    e
}
replace/all x charset ",.;?" ""
trim/lines x
x: split x " "
== [
    "a" 
    "b" 
    "c" 
    "d" 
    "e"
]
```
### Steps to reproduce the problem
Paste code in console. A string without linebreaks doesn't result in vertical block.
### Red version and build date, operating system with version.
- Red for Windows version 0.6.3 built 14-Dec-2017/21:27:14+01:00
- Win 7 x64
- Win 10

**Comment by greggirwin** [comment]
Also, FORMing the string before splitting clears the markers:
```
>> x: {
{        a? 
{        b ,
{        c .
{        d; 
{        e
{    }
== {^/    a? ^/    b ,^/    c .^/    d; ^/    e^/}
>> replace/all x charset ",.;?" ""
== {^/    a ^/    b ^/    c ^/    d ^/    e^/}
>> trim/lines x
== "a b c d e"
>> x: split form x " "
== ["a" "b" "c" "d" "e"]
```

**Comment by dockimbel** [comment]
It's a lexer issue, not related to `trim/lines`.
