### ISSUE TITLE
vector! type unsupported by forall 

### ISSUE THREAD

**Issue by ldci** [red/red#3146]
vectRandom: function [v [vector!] value [number!]
][
	forall v [v/1: random value]
]
*** Script Error: forall does not allow vector! for its 'word argument
*** Where: forall
*** Stack: vectRandom

**Comment by meijeru** [comment]
This is because the macro `ANY_SERIES?` does not include `vector!` by oversight.

**Comment by ldci** [comment]
Thanks Rudolf

François Jouen
Université de Recherche Paris Sciences et Lettres (PSL)
Ecole Pratique des Hautes Etudes
GRET Modélisation Epigénétique et Développement (MEDé)
Laboratoire Cognitions Humaine et Artificielle (CHArt) EA 4004 FED 4246
Les Patios Saint Jacques
4-14 rue Ferrus, 75014 Paris
01 53 63 61 69
06 87 13 76 81
francois.jouen@ephe.sorbonne.fr<mailto:francois.jouen@ephe.sorbonne.fr>
http://www.cognition-usages.org/chart/
http://marcbui.wixsite.com/mede



Le 18 déc. 2017 à 18:19, Rudolf Meijer <notifications@github.com<mailto:notifications@github.com>> a écrit :


This is because the macro ANY_SERIES? does not include vector! by oversight.

**Comment by ldci** [comment]
Thanks a lot

Envoyé de mon iPhone

Le 19 déc. 2017 à 12:30, Qingtian <notifications@github.com<mailto:notifications@github.com>> a écrit :


Closed #3146<https://github.com/red/red/issues/3146>.
