### ISSUE TITLE
[Wish] support explicitly setting the radio button data to false 

### ISSUE THREAD

**Issue by BeardPower** [red/red#3152]
### Expected behavior

The radio button should also support explicitly setting its data to false.
From the documentation: data | true: checked; false: unchecked (default).

`view [radio false]`

It should create a radio button just like `view [radio true]`, but with the radio button unchecked.

### Actual behavior

`view [radio false]`

*** Script Error: VID - invalid syntax at: [false]
*** Where: do
*** Stack: view layout cause-error 

### Steps to reproduce the problem

Just create a radio button with its data explicitly set to false:

`view [radio false]`

### Red version and build date, operating system with version.

Red for Windows version 0.6.3 built 11-Dec-2017/15:42:34+01:00

**Comment by rebolek** [comment]
According to https://doc.red-lang.org/en/view.html#_radio `radio` should support `false`, so IMO it's bug, not a wish, but that's just a detail.

**Comment by BeardPower** [comment]
@dockimbel asked me to tag it as wish.

**Comment by dockimbel** [comment]
I think the doc went a bit further than the implementation, as `false` is the default value, the code is not accepting it. Though, when dynamically constructing a VID block, reducing an expression could lead to a `false`, so it would be convenient to support it.
