### ISSUE TITLE
WISH: Math ops on pairs with floats should be same as with percent values

### ISSUE THREAD

**Issue by endo64** [red/red#3154]
Multiply and divide `float!` with `pair!` should be allowed just as with `percent!`:

### Expected behavior

```
>> 12x12 * 0.5
== 6x6
```
### Actual behavior

Float value casts to integer:

```
>> 12x12 * 0.6
== 0x0
```

Should be same as with `percent!`

```
>> 12x12 * 50%
== 6x6
```

### Red version and build date, operating system with version.

21-Dec-2017/1:59:20+03:00
Win10 x64

**Comment by dockimbel** [comment]
Agreed.
