### ISSUE TITLE
Crash when assigning result of function in object to a word

### ISSUE THREAD

**Issue by rebolek** [red/red#3156]
### Expected behavior

```
>> c: context [f: func[a][""]]
== make object! [
    f: func [a][""]
]
>> t: c/f []
== ""
```

### Actual behavior

```
>> c: context [f: func[a][""]]
== make object! [
    f: func [a][""]
]
>> t: c/f []

*** Runtime Error 1: access violation
```

### Steps to reproduce the problem

See above. Also, here's stack trace:

```
*** Runtime Error 1: access violation
*** in file: /home/sony/Code/red/runtime/datatypes/context.reds
*** at line: 283
***
***   stack: red/_context/set F6A0D7ECh F6A0D7FCh
***   stack: red/word/set
***   stack: red/interpreter/eval-expression F6805564h F6805564h false false false
***   stack: red/interpreter/eval F6A0D7CCh true
***   stack: red/natives/catch* true 1
***   stack: ctx357~try-do F7F50D6Ch
***   stack: ctx357~do-command F7F50D6Ch
***   stack: ctx357~eval-command F7F50D6Ch
***   stack: ctx357~run F7F50D6Ch
***   stack: ctx357~launch F7F50D6Ch
***   stack: ***_start
```

### Red version and build date, operating system with version.

Custom build from latest sources (21-Dec-2017/10:47:01+01:00), Ubuntu 17/10.

**Comment by meijeru** [comment]
Looks like regression after this commit: [9178838](https://github.com/red/red/commit/9178838f7569b6e3d28fedcf070f04ab7e6e4e33)

**Comment by rebolek** [comment]
@meijeru Actually, it's this commit: https://github.com/red/red/commit/bca86785936b0750b994702daa15734361237f1f

**Comment by meijeru** [comment]
So @dockimbel and @qtxie have enough food for thought :smile:

**Comment by dockimbel** [comment]
Thanks for identifying those culprit commits, that's a significant time-saver for us! :+1:

**Comment by dockimbel** [comment]
Relates to #3128

**Comment by rebolek** [comment]
You're welcome!
Actually, I needed working console, so I had to find which commit works ;)

**Comment by toomasv** [comment]
works with explicitly set type:
```
t: to-string c/f []
```

**Comment by 9214** [comment]
Maybe related (crashes the console)
```Red
graph: make deep-reactor! [
    data: [
        red  10x10 10
        blue 40x40 20
    ]
]

view/no-wait [
    base 500x500 with [
        draw: collect [
            foreach [color size center] graph/data [
                keep compose [fill-pen (color) circle (size) (center)]
            ]
        ]
    ]
]
```

**Comment by greggirwin** [comment]
Also reported as https://github.com/red/red/issues/3202

**Comment by gltewalt** [comment]
Also works with `reduce`

```
>> c: context [f: func[a][""]]
== make object! [
    f: func [a][""]
]
>> t: reduce c/f []
== ""
```

**Comment by gltewalt** [comment]
`t: c/f []`

Shows all zeros for my `ctx` before crash. Is that normal or does that mean it was set to null somehow?
[https://imgur.com/a/eSrL9](url)

**Comment by gltewalt** [comment]
`set` calls `set-in` with `set-in word value TO_CTX(node) yes` but doesn't look like it's entering the `if event?` in `set-in`

**Comment by meijeru** [comment]
Another example, in which the binding just does not take place:
```
>> p: 1
== 1
>> p
== 1
>> p: system/platform ;; function call
== Windows
>> p
== 1
```

**Comment by toomasv** [comment]
I checked with all the other system-words and `platform` was the only one not binding.

**Comment by meijeru** [comment]
Right. That is because `platform` is a function.

**Comment by 9214** [comment]
Adieu! :beers: :bear:
