### ISSUE TITLE
Error running on linux (Solus 3)

### ISSUE THREAD

**Issue by unreadable** [red/red#3160]
### Expected behavior
Open a simple window
### Actual behavior
Compiles fine, but on the runtime throws the following error:
### Steps to reproduce the problem
	Red [Needs: 'View]
    view [text "Hello World!"]
	
Save it in a gui.red file then `red -c gui.red`

    ./gui
	*** Script Error: view has no value
	*** Where: ???

### Red version and build date, operating system with version.
red-063, December 22, 2017, Solus 3

**Comment by PeterWAWood** [comment]
There is no GUI backend for Linux yet. Work has started in the GTK git branch but it is a long way from complete.
