### ISSUE TITLE
How to use write/info to set HTTP POST parameters?

### ISSUE THREAD

**Issue by JunyanHe** [red/red#3166]
I want to use write/info to set HTTP POST parameters. 
write/info http://httpbin.org/post  [post [] "name=Tom"]
The server can not get the args.

**Comment by dockimbel** [comment]
You should ask such question in the [chat room](https://gitter.im/red/help). Github issues are for reporting issues.

**Comment by dockimbel** [comment]
@qtxie Where did we put the doc for that? :-)

**Comment by 9214** [comment]
[This one](https://github.com/red/red/wiki/Guru-Meditations#how-to-make-http-requests) will do?

**Comment by qtxie** [comment]
@JunyanHe Please check the document in @9214's reply.

**Comment by JunyanHe** [comment]
When I put head "Content-Type", it works.
write/info http://httpbin.org/post  [post [Content-Type: "application/x-www-form-urlencoded"] "name=Tom"]

Thanks @9214 , @qtxie
