### ISSUE TITLE
Replace misbehaving when pattern is the series at same or different index

### ISSUE THREAD

**Issue by x8x** [red/red#3172]
### Expected behavior
same as Rebol:
```
  replace t: %a.b t %.c
;   %.c
   replace t: %a.b find/last t %. %.c
;   %a.c
  replace t: %a.b at t 2 %.c
;   %a.c
```
### Actual behavior
```
  replace t: %a.b t %.c
;   %.ca.b
  replace t: %a.b find/last t %. %.c 
;   %a.c.b
  replace t: %a.b at t 2 %.c
;   %a.c.b
```
### Red version and build date, operating system with version.
macos/latest

**Comment by qtxie** [comment]
Seems it's a regression.

**Comment by x8x** [comment]
Sorry @qtxie it works fine indeed. I have a local custom replace that I missed when wrote the issue. Have a good day!
