### ISSUE TITLE
WISH: "dynamic" refinements

### ISSUE THREAD

**Issue by 9214** [red/red#3175]
Currently we write something like
```Red
either bar [foo][foo/baz]
```

I wish `refinement!` could also support (akin to `path!`s)
```Red
foo/(if bar ['baz])
```
which could also be chained to form full pack of refinements (i.e. `foo/(...)/(...)/(...)`). I have doubts that current compiler can support that, but when it comes to JIT, if there aren't any technical trade-offs for such syntax, why not?

**Comment by x8x** [comment]
@9214 Something like that would be useful.
How would you menage if `/baz` need more arguments ?
```
foo/(if bar ['baz arg1 arg2])
```
Better idea?

**Comment by 9214** [comment]
@x8x good point

**Comment by x8x** [comment]
@9214 That way would break chainability:
```red
  a: pick sort/(if true ['part]) [4 3 2 1] 4 1 a
;   1
  a: pick sort/(if false ['part]) [4 3 2 1] 4 1 a
;   4
```
Expected result would be `1` for both cases.

**Comment by 9214** [comment]
@x8x indeed, totally missed that out. It seems that proposed feature is not that useful though :confused:

**Comment by greggirwin** [comment]
I think we'll get this covered in other ways. e.g. the `specialize` func that floated around, I have various `refine` mezz ideas out there, `apply` of some kind. We can chat on gitter, and if those cover this need, we can close this ticket.

**Comment by dockimbel** [comment]
You can already achieve something similar with regular code:
```
bar: true
foo: func [/baz][either baz [2][1]]

do append to-path 'foo (if bar ['baz])
== 2
```

Given how overloaded are `path!` semantics already, it is unlikely that we will introduce some other syntactic sugar for paths. Actually, desugaring is rather on the table, like limitating the parens support in path (which is syntactly inconsistent already).

**Comment by DideC** [comment]
@dockimbel this code error out if `bar: false`. How do you handle this case simply?

**Comment by 9214** [comment]
:neckbeard: 
```red
>> do to path! trim compose [foo a (if no ['b])]
== 2
>> do to path! trim compose [foo a (if yes ['b])]
== 1
>> :foo
== func [/a /b][either all [a b] [1] [2]]
```

**Comment by greggirwin** [comment]
What is the concrete use case for this original wish? I imagine it will get as ugly as the alternative, and maybe moreso. If we decide to remove paren! support from paths, it also goes away as a possibility.
```
foo/(if bar ['baz])/(if bax ['bip])/(if bim ['bok])
```
Let's find a concrete use case and compare this wish against `specialize/refine/apply` approaches, and see which looks better. Overloading the syntax this way also seems like we're working against the language.

**Comment by nedzadarek** [comment]
As for syntax of it: 
Why not just `foo/(bar baz)/(bax bip)/(bim bok)` instead of `foo/(if bar ['baz])/(if bax ['bip])/(if bim ['bok])`?
