### ISSUE TITLE
`base` doesn't detect some events

### ISSUE THREAD

**Issue by nedzadarek** [red/red#3178]
`Base` doesn't detect some events:
`view [base red on-wheel [print event/type]]`
Here is a list of event's that is not working:

1. wheel
2. zoom 
3. pan
4. rotate
5. two‑tap
6. press‑tap
7. key‑down
8. key
9. key‑up
10. enter

I am using Red 0.6.3 22 November 2017/17:20:39+01:00 on Win 8.1.

**Comment by qtxie** [comment]
@nedzadarek `set-focus` to the `base` will make it work.
```
 view [b: base red on-wheel [print event/type] do [set-focus b]]
```
