### ISSUE TITLE
Background interferes with `text` in `view`

### ISSUE THREAD

**Issue by toomasv** [red/red#3180]
### Expected behavior
```
view [box white "split-^/text"]
```
would show multi-line text exactly as 
```
view [box "split-^/text"]
```
### Actual behavior
Line-break is ignored with background color
### Steps to reproduce the problem
^
### Red version and build date, operating system with version.
W10 Pro
```
system/build
== make object! [
    date: 29-Dec-2017/16:33:38+02:00
    config: make object! [
        config-name: 'Windows
```
### Additional notes
It will wrap with `wrap`, but then it will be vertically aligned to top:
```
view [box white wrap "split-^/text"]
```
It will also wrap when alpha channel of any value is included:
```
view [box 255.255.255.0 "split-^/text"]
view [box 255.255.255.255 "split-^/text"]
```

**Comment by hiiamboris** [comment]
I fixed this in https://github.com/red/red/pull/3683 and it's okay to close this one.
