### ISSUE TITLE
Changing FALSE value changes also literal #[FALSE]

### ISSUE THREAD

**Issue by rebolek** [red/red#3192]
### Expected behavior

```
>> false: "bad stuff"
== "bad stuff"
>> #[false]
== false
```

### Actual behavior

```
>> false: "bad stuff"
== "bad stuff"
>> #[false]
== "bad stuff"
```

### Steps to reproduce the problem

See above code. In Rebol it works as expected. 

The same error happens also with `true` and `none`.

### Red version and build date, operating system with version.

Linux Ubuntu 17.10

```
>> system/build
== make object! [
    date: 4-Jan-2018/9:25:48+01:00
```

**Comment by dockimbel** [comment]
This looks like console-related, if you change core words, the console may not function properly anymore. In Rebol, the console is written in C, so it won't get affected by such redefinitions.

**Comment by dockimbel** [comment]
There is no fix we can provide for that for now, it needs to wait for modules support, where core words will be by default protected from redefinition.
