### ISSUE TITLE
WISH: expose more APIs to control area face.

### ISSUE THREAD

**Issue by qtxie** [red/red#3194]
Provide a way to let user to have a fine control of the area. like:

- scroll-lineup
- scroll-linedown
- scroll-to-bottom
- scroll-to-top
- move-caret
- select-text
more......

**Comment by toomasv** [comment]
👍

**Comment by dockimbel** [comment]
The `/selected` facet should be used to handle selection in a reflective way (read/write). It should be set to a `pair!` value holding the index of first and last selected characters, defining a selection range. When there is no selected text, the facet should be set to `none`.
