### ISSUE TITLE
set operations do not work as expected with block elements

### ISSUE THREAD

**Issue by 9214** [red/red#3195]
### Expected behavior
```Red
>> difference [[1][2]] [[1]]
== [[2]]
>> exclude [[1]] [[1]]
== []
>> intersect [[1][2]] [[1]]
== [[1]]
>> unique [[1][1]]
== [[1]]
```

### Actual behavior
```Red
>> difference [[1][2]] [[1]]
== [[1] [2] [1]]
>> exclude [[1]] [[1]]
== [[1]]
>> intersect [[1][2]] [[1]]
== []
>> unique [[1][1]]
== [[1] [1]]
```
### Steps to reproduce the problem
Play around with set operations (see all of them with `? "data set"`). `union` seems to work as expected. Moreover, I think this bug applies not only to `block!` elements, but also to `map!` and `object!` (I understand that it might not be intended to use them as elements of sets, but anyway), and perhaps some other `series!`.

### Red version and build date, operating system with version.
Same on Linux version.
```Red
>> about
Red for Windows version 0.6.3 built 10-Jan-2018/23:14:39+05:00
```

**Comment by 9214** [comment]
I actually think that this is an expected behavior, since set operations check whenever all series-element are *actually* same series (i.e. reference the same underlying buffer):
```Red
>> x: [1 2 3]
== [1 2 3]
>> unique reduce [x x]
== [[1 2 3]]
```

**Comment by Phryxe** [comment]
Don't you mean expected behavior of `intersect` to be?
```
>> intersect [[1][2]] [[1]]
== [[1]]
```

**Comment by Phryxe** [comment]
Also compare this actual behavior
```
>> intersect [[1][2][3]][[3][4][5]]
== []
>> intersect [[1][2][3]] [[3][4][5]]
== []
>> intersect [[1] [2] [3]] [[3] [4] [5]]
== [[3]]
```

**Comment by greggirwin** [comment]
I get the result above the first time I run it. Empty result if I just do the last line again. Then I did it in another fresh console, and got all empty results.

**Comment by gltewalt** [comment]
Probably only expected behavior if the choice was to diverge from Rebol2
```
REBOL/View 2.7.8.3.1 1-Jan-2011
Copyright 2000-2011 REBOL Technologies.  All rights reserved.
REBOL is a trademark of REBOL Technologies. WWW.REBOL.COM
>> difference [[1][2]] [[1]]
== [[2]]
>> exclude [[1]] [[1]]
== []
>> intersect [[1][2]] [[1]]
== [[1]]
>> unique [[1][1]]
== [[1]]
```

**Comment by greggirwin** [comment]
If this is a show-stopper for you, I have some mezzanine set funcs at https://gist.github.com/greggirwin/e579c08410497b9f9ba3b9978fa45347

**Comment by hiiamboris** [comment]
Results are still random:
```
>> intersect [[1][2][3]][[3][4][5]]
== []
>> intersect [[1][2][3]][[3][4][5]]
== []
>> intersect [[1][2][3]][[3][4][5]]
== [[3]]
>> intersect [[1][2][3]][[3][4][5]]
== [[3]]
>> intersect [[1][2][3]][[3][4][5]]
== [[3]]
>> intersect [[1][2][3]][[3][4][5]]
== [[3]]
>> intersect [[1][2][3]][[3][4][5]]
== []
```

```
>> recycle/off
>> len: [0 0 0 0 0] ()
>> loop 100000 [i: length? r: intersect copy/deep [[1][2][3][4][5]] copy/deep [[3][4][5][6][7]] len/(i + 1): len/(i + 1) + 1]
== 42390
>> len
== [42312 42390 13876 1422 0]
```
Expected: `len == [100000 0 0 0 0]` in current implementation, `[0 0 0 100000 0]` in the one proposed.

I think it's either a set-ops bug or hashtable bug.

**Comment by qtxie** [comment]
Achieve the same behaviors as Rebol2 in commit b28e0d687d610d00c26acf0424a93831baf5e8c2.
