### ISSUE TITLE
Unable to RED in Windows 7: Access Error

### ISSUE THREAD

**Issue by kuopassa** [red/red#3198]
Red version 0.63 refuses to do anything with Windows 7 due to:

Driver Internal Error: Access Error: Cannot open /C/ProgramData/Red/red-console.red

Is there an easy and cheap fix for this?

Screenshots: [one](http://kuopassa.net/images/652.png) and [two](http://kuopassa.net/images/653.png)

**Comment by greggirwin** [comment]
This comes up for some people, based on permissions. Please join the Gitter red/red room and chat there. 
Here is how someone solved their problem recently: https://gitter.im/red/red?at=5a570913ce68c3bc74a412ff

It's not a common issue, but one we need to get in a wiki, if not already there.
