### ISSUE TITLE
WISH: split function change

### ISSUE THREAD

**Issue by endo64** [red/red#3200]
Split function's return value is missing the last one if there are delimiters at the end of the input value consecutively.

### Expected behavior

```
>> split "a-b--" "-"
== ["a" "b" "" ""]
```
### Actual behavior

```
>> split "a-b--" "-"
== ["a" "b" ""]
```

### Red version and build date, operating system with version.

Red v0.6.3
Build 21-Dec-2017/23:39:43+03:00
Win10 x64

**Comment by endo64** [comment]
I made a PR for this change: #3201

**Comment by xqlab** [comment]
Omitting the last empty value is similar to the behavior how Rebol2 handles it. It has an advantage when dealing with files with lines of text.

**Comment by DideC** [comment]
Maybe a `/trim` refinment to have the R2 behaviour for times it's needed ?
