### ISSUE TITLE
Crash when assign function result of an object

### ISSUE THREAD

**Issue by Zamlox** [red/red#3202]
### Expected behavior
Following sequence of code should execute in gui console without crashing
```
a: none
obj: object [
	f1: does [
		11
	]
]
a: obj/f1
```
### Actual behavior
It crash when executed in gui console
Culprit commit: bca86785936b0750b994702daa15734361237f1f
### Steps to reproduce the problem
Fire up gui console and execute the above code
### Red version and build date, operating system with version.
Red for Windows version 0.6.3 built 16-Jan-2018/9:28:40+02:00
OS: Windows 7

**Comment by rebolek** [comment]
This is duplicate of https://github.com/red/red/issues/3156

**Comment by Zamlox** [comment]
Yep, looks like.

**Comment by greggirwin** [comment]
Added a comment for this ticket to #3156, and will close this so we focus there.

Thanks @zamlox!

**Comment by toomasv** [comment]
As with sibling issues, explicit typing is work-around:
```
>> a: to-integer obj/f1
== 11
```

**Comment by gltewalt** [comment]
>> a: reduce obj/f1
== 11
