### ISSUE TITLE
WISH: scientific notation for INTEGER!s

### ISSUE THREAD

**Issue by 9214** [red/red#3215]
I wish I could use E-notation to write large integers more shortly, say, `10e8` vs `1'000'000'000`. However, currently Red supports this notation only for `float!`s.
```Red
>> 10e8
== 1000000000.0
```

What I propose is to use uppercase `E` for integers and lowercase for floats, i.e.:
```Red
>> 10e8
== 1000000000.0
>> 10E8
== 1000000000
```
Or, since Red is case-insensitive, make `integer!` case the default one and write `float!`s explicitly as `10.0e8`?

**Comment by nc-x** [comment]
👎 from me. 
> What I propose is to use uppercase E for integers and lowercase for floats
  
and
  
> Or, since Red is case-insensitive, make integer! case the default one and write float!s explicitly as 10.0e8
  
In both cases it is pretty easy to get confused or make mistake.

Also, i don't think there are going to be many use cases where you would need to use something like `10e8` for int, so supporting this use case does not seem a good idea considering the fact that it would be pretty easy to make mistake especially for a newcomer for whom this change would be IMHO an unwelcome surprise.

**Comment by 9214** [comment]
And typing 9 zeros by hand is less error-prone? Either this or explicit `to` conversion.

Use-cases? Any non-trivial computation or math problem, profiling loop with large number of iterations.

How is it confusing when in `10e8` left-hand side is an integer, hence the result is an integer, and in `10.0e8` left-hand side is float, so as the result? I can't see any reason (aside from R2 compatability) why existent syntax should produce float in both cases.

**Comment by 9214** [comment]
And how newcomer can be surprised with a change if he is, by definition, a newcomer who doesn't even know syntactic rules and can't compare two things about which he's not yet aware?

**Comment by endo64** [comment]
But please do not make scientific notation  default for results:

```
>> form 1 / 70.0
== "0.01428571428571429" ; red
== "1.42857142857143E-2" ; rebol
```
I always had to use `format-number` function to "fix" this unwanted scientific format for all numbers, it is very time consuming task when we have thousands of numbers

**Comment by greggirwin** [comment]
> Use-cases? Any non-trivial computation or math problem, profiling loop with large number of iterations.

For non-trivial math problems, what is the win with making the result an integer? There may be non-trivial integral math problems, but I'd hazard a guess that they're the exception, and this notation would lead to more internal type conversions, or requiring the use of 1.0e8 notation for floats. Being explicit there may not be all bad though.

I don't see the benefit in loop counting, but then we've never had it to use and get accustomed to. My first thought when seeing E notation is that calculations are involved, not just a value that is never used in a computation.

**Comment by 9214** [comment]
Well, since it introduces overhead and confuses everyone, I'll retract my wish. On a side note, whenever I use E-notation in Red, I somehow expect `integer!` instead of `float!`, but don't mind to use explicit conversion.
