### ISSUE TITLE
Crash on some invalid parse rules

### ISSUE THREAD

**Issue by endo64** [red/red#3217]
### Expected behavior

No crash, meaningful error message.

### Actual behavior

Console crashes:

*** Runtime Error 1: access violation
*** at: 00427815h

### Steps to reproduce the problem

Try one of these:

```
parse "abc" [to fail]
parse "abc" [some fail]
parse "abc" [thru fail]
parse "abc" [any fail]
```

### Red version and build date, operating system with version.

0.6.3 date: 29-Jan-2018/11:00:51+03:00
Win10 x64

**Comment by dockimbel** [comment]
Good catch!
