### ISSUE TITLE
PRIN / PRINT doesn't output anything after compilation on Windows targets

### ISSUE THREAD

**Issue by 9214** [red/red#3221]
### Expected behavior
Script prints `something` in shell console.
### Actual behavior
No output (checked on Wine, Win7 and Win10). 
Wine chokes with following exception:
```
*** Runtime Error err:seh:raise_exception Unhandled exception code c0000005 flags 0 addr 0x416191
```
### Steps to reproduce the problem
```Red
Red [Needs: View]
print "something"
```
Compile the script above for `Windows` or `WindowsXP` targets and execute it from shell. Same script  works as expected for `Linux` (with `Needs: View` omitted for obvious reasons) and `MSDOS` targets.

### Red version and build date, operating system with version.
I think it applies to latest ones too.
```Red
>> about
Red for Windows version 0.6.3 built 25-Jan-2018/23:52:32+05:00
```

**Comment by qtxie** [comment]
It should be fixed in 0.6.4 branch.

**Comment by qtxie** [comment]
It is normal that PRIN / PRINT doesn't output anything after compilation on Windows targets. It should not crash anymore in the latest version.

**Comment by 9214** [comment]
@qtxie 
> It is normal that PRIN / PRINT doesn't output anything after compilation on Windows targets.

Will it stay that way? I'd like to implement a console interface fallback (i.e. if executable is called with an argument, then print output into console, otherwise launch GUI) for my app, which is problematic because of the issue with `prin` and `print`. 

This forces me to use MSDOS as a compilation target, which works, but then there appears a blank console window in the background each time users launches GUI mode.

**Comment by qtxie** [comment]
@9214 In this case you need to integrated a GUI console into your app.
