### ISSUE TITLE
TEXT in DRAW does not honour TRANSLATE command

### ISSUE THREAD

**Issue by rebolek** [red/red#3225]
See this code:

```
view [
    base 300x100 draw [
        push [translate 50x20 
            fill-pen 230.145.190 circle 10x10 10 
            text 20x0 "Text" 
        ]
    ]
]
```

### Expected behavior

Expected is to have both circle and text moved by 50x20.

### Actual behavior

![](https://files.gitter.im/red/red/gui-branch/0977/image.png)

### Steps to reproduce the problem

Run the above code.

### Red version and build date, operating system with version.

Win 10 with system/build/date: 18-Jan-2018/11:35:36+01:00
Wine, Red for Windows version 0.6.3 built 25-Jan-2018/23:52:32+05:00

**Comment by StephaneVeneri** [comment]
Seems to be working properly on macOs 10.12.6.
With Red for macOS version 0.6.3 built 20-Jan-2018/23:49:34+01:00

![test](https://user-images.githubusercontent.com/10183753/36278489-430e21a2-1294-11e8-9c1e-106a94adb043.jpeg)

**Comment by toomasv** [comment]
On W10 `text` is put always on its provided coordinates unregarding transformations:
```
view [base 300x100 draw [matrix [1 0 0 1 50 20] text 0x0 "Text" box 0x0 30x20]]
view [base 300x100 draw [translate 50x20 text 0x0 "Text" box 0x0 30x20]]
view [base 300x100 draw [transform 0x0 0 1 1 50x20 text 0x0 "Text" box 0x0 30x20]]
```
All these result in
![try2](https://user-images.githubusercontent.com/11960635/36293637-dc8122d6-12e3-11e8-8e1a-cd2bca88bf53.png)

**Comment by Zamlox** [comment]
@qtxie perhaps replacing ```ExtTextOut``` with ```GdipDrawString``` ?

**Comment by qtxie** [comment]
@Zamlox Yes. We can try that.

**Comment by Zamlox** [comment]
@qtxie I have analyzed deeper and it looks like replacing ```ExtTextOut``` with ```GdipDrawString``` will require also modification of ```size-text```. 
An alternative solution would be to replace 
```either ctx/on-image?``` with ```either any [ctx/on-image? ctx/other/GDI+?]``` 
in ```OS-draw-text```, because when text is drawn, flag ```ctx/other/GDI+?``` is set to ```true```. Currently the false branch of that either is selected which is not ok. 
To work properly this change will require following additions in ```draw-begin```
   - a call to ```update-gdiplus-font-color ctx ctx/pen-color```
   - selecting ```default-font``` in the device context (```GdipCreateFontFromDC``` will work only if a font is selected in the device context). Also currently the font are not same if text is drawn in image or window (run command in gui console: ```view compose/deep [base 100x100 draw [image (draw 40x30 [text 10x10 "Hello"]) text 10x40 "Hello" ]]```). 

If you agree with this fix I can push a PR

**Comment by Zamlox** [comment]
@qtxie Do you remember what was the reason do combine GDI/GDI+ ? Can we remove code based on GDI ?

**Comment by Zamlox** [comment]
@rebolek Windows XP has support for GDI+. Maybe for older version of Windows.
But there are features implemented taking into consideration only GDI+. For example ```anti-alias``` draw command is using GDI+ functions regardless of the value set ```on/off```. 
An alternative would be to have different layers for these technologies: GDI/GDI+/Direct2D and not to mix them. A detection can be done at startup to choose the right layer. The disadvantage would be more lines of code to be written.

**Comment by rebolek** [comment]
@Zamlox 
> Windows XP has support for GDI+. 

Thanks, I'm no expert on this, so it was just a wild guess.

> Maybe for older version of Windows.

Windows XP is the oldest version supported.

> An alternative would be to have different layers for these technologies

This seems reasonable to me.

**Comment by hiiamboris** [comment]
For a more complete overview, text is unaffected by all matrix transformations and by clipping:
![](https://i.gyazo.com/06380406291be017fec016f9dbbab123.png)
source:
```
Red [Needs: 'View]

view [
	below
	base 200x100 draw [
		fill-pen blue
		box 0x0 100x20
		text 0x0 "quick browne bear"
	]
	base 200x100 draw [
		translate 50x10
		fill-pen blue
		box 0x0 100x20
		text 0x0 "quick browne bear"
	]
	base 200x100 draw [
		clip 10x0 30x30 replace [
			fill-pen blue
			box 0x0 100x20
			text 0x0 "quick browne bear"
		]
	]
	base 200x100 draw [
		scale 3 3 [
			fill-pen blue
			box 0x0 100x20
			text 0x0 "quick browne bear"
		]
	]
	base 200x100 draw [
		skew 10 30 [
			fill-pen blue
			box 0x0 100x20
			text 0x0 "quick browne bear"
		]
	]
	base 200x100 draw [
		rotate 30 0x0 [
			fill-pen blue
			box 0x0 100x20
			text 0x0 "quick browne bear"
		]
	]
]
```

**Comment by moliad** [comment]
Implementing a node graph editor, the text is still not following the matrix transformations (quite a few releases have gone by).

this brings back Rebol2 memories which had similar problems (painful memories).

**Comment by rebolek** [comment]
At least Red is not closed source, like Rebol2 was.

**Comment by toomasv** [comment]
Workaround: Text will move (on W10) if face has transparent/no color, e.g. `box`:
```
view [
    box 300x100 draw [ ; or `base glass`
        push [translate 50x20 
            fill-pen 230.145.190 circle 10x10 10 
            text 20x0 "Text" 
        ]
    ]
]
```
matrix-transformations work also in this way. Background can be set e.g. with `backdrop` or panel.
