### ISSUE TITLE
segfault on TO FLOAT! applied to empty string

### ISSUE THREAD

**Issue by 9214** [red/red#3227]
### Expected behavior
Something meaningful.
### Actual behavior
Segmentation fault.
### Steps to reproduce the problem
```Red
>> to float! ""
Segmentation fault
```
### Red version and build date, operating system with version.
same on Windows.
```Red
>> about
Red for Linux version 0.6.3 built 18-Feb-2018/17:02:40+05:00
```

**Comment by PeterWAWood** [comment]
`to float! ""` hangs under macOS both in the terminal and a compiled executable.

**Comment by Ivo-Balbaert** [comment]
On Windows 10 and Ubuntu 16.04
from inside the Red console, or compiled  ( Red 0.6.3)
to float! ""
results in 
*** Script Error: cannot MAKE/TO float! from: ""
I get no segmentation fault
This seems perfectly appropriate result to me.
