### ISSUE TITLE
Typo in description of `arc` shape

### ISSUE THREAD

**Issue by toomasv** [red/red#3230]
### Expected behavior
In https://doc.red-lang.org/en/draw.html#_arc, `arc` shape syntax should be:

> `arc <end> <radius-x> <radius-y> <angle> sweep large       (absolute)`
`'arc <end> <radius-x> <radius-y> <angle> sweep large       (relative)`

I.e. `large` in the end.
### Actual behavior
Currently it is:

> `arc <end> <radius-x> <radius-y> <angle> sweep closed       (absolute)`
`'arc <end> <radius-x> <radius-y> <angle> sweep closed       (relative)`

**Comment by 9214** [comment]
https://github.com/red/docs/pull/39

**Comment by greggirwin** [comment]
Thanks!
