### ISSUE TITLE
exception with uncommented probe

### ISSUE THREAD

**Issue by snotbubble** [red/red#3231]
exception after compiling with uncommented probe
```
*** Runtime Error : access violation
*** at: h
```

1. download and compile this file with just -c :
 https://github.com/snotbubble/fulltardie/blob/master/badprobe.red

2. run it via cmd

Red 063 windows10 x64

**Comment by 9214** [comment]
https://github.com/snotbubble/fulltardie/blob/master/badprobe.red#L516
If you could come up with much shorter example to reproduce the problem, that would be highly appreciated.

**Comment by snotbubble** [comment]
yep try this, same exception :
https://github.com/snotbubble/fulltardie/blob/master/busteddata.red

**Comment by greggirwin** [comment]
Second example compiles and runs fine here on Win 7. Will try the first one.

**Comment by greggirwin** [comment]
First example works fine too.

**Comment by greggirwin** [comment]
`probe btab/1` is the only uncommented probe in the big example.

**Comment by greggirwin** [comment]
I'm using a local build, so it's possible this is in the 063 download, if you're using that. There are a couple known regressions in there right now.

**Comment by qtxie** [comment]
No crashes in the [latest version](http://static.red-lang.org/dl/auto/win/red-latest.exe).

**Comment by dockimbel** [comment]
@snotbubble Can you confirm that there is no crash anymore, so we can close this ticket?

**Comment by snotbubble** [comment]
yep no crash.
