### ISSUE TITLE
MAKE IMAGE! READ-CLIPBOARD with image copied in a buffer causes access violation

### ISSUE THREAD

**Issue by 9214** [red/red#3239]
### Expected behavior
Image is created or meaningful error message is raised.
### Actual behavior
Access violation.
### Steps to reproduce the problem
Copy any image in a buffer (say, right click on my userpic - Copy Image) and run the snippet below
```Red
make image! read-clipboard
 ```
This effectively results in
```Red
*** Runtime Error 1: access violation
*** at: F7C73599h
```
While `read-clipboard` itself returns `bitset!`
```Red
>> read-clipboard
== make bitset! #{0000000020C000300000009400000090}
```

### Red version and build date, operating system with version.
I don't think that checking with latest build makes much sense ;)
```Red
>> about
Red for Windows version 0.6.3 built 25-Jan-2018/23:52:32+05:00
```

**Comment by qtxie** [comment]
Interesting, `read-clipbord` should return `string!`. @9214 Are you using Windows 10? Works fine on Win 7 64bit.

**Comment by 9214** [comment]
@qtxie no, I checked this with Wine on Linux Mint.

**Comment by lepinekong** [comment]
On Windows read-clipboard doesn't even return: console just shut down :)

**Comment by nedzadarek** [comment]
I have Red from 21 Januarry, on Win 8.1

It seems that when there is nothing in the clipboard or non-text is copied, `read-clipboard` holds the same bitset:
`read-clipboard; make bitset! #{0000000020C000300000009400000090}`
but when you try to set it to the variable, it will be `none`:
`v: read-clipboard`
however, when you try run `read-clipboard` directly with some function:
`print read-clipboard`
It causes access violation.
ps. with a variable:
```
v: read-clipboard
; == none
v
' == none
make image! v
; *** Script Error: cannot MAKE/TO image! from: none
; *** Where: make
; *** Stack:
```

@lepinekong you have to run it in the "text mode": `red324234.exe --cli`

**Comment by gltewalt** [comment]
@qtxie It blows up on my Win7 64 bit.  Ensure that you are copying an image into the clipboard via the OS first.

**Comment by qtxie** [comment]
I see. Thanks.

**Comment by qtxie** [comment]
I see. Thanks.

**Comment by qtxie** [comment]
I pushed a fix. Should not crash anymore.
FYI. `read-clipboard` only support string for now. If you selected any other datatypes into clipboard, `read-clipboard` will return `none`.

**Comment by qtxie** [comment]
I'll close it. If it still crashes, please reopen it.
