### ISSUE TITLE
Red (automated builds) is blocked by Windows Defender

### ISSUE THREAD

**Issue by anta40** [red/red#3255]
1. Grab the latest automated build, e.g red-13mar18-3b520bea.exe.
2. Run it.
3. After the usual "Compiling compression library..." and "Compiling Red GUI Console...", Windows Defender (I'm on Windows 10) will block it:
![dorv](https://user-images.githubusercontent.com/16976/37357798-e80ed8c2-271b-11e8-8f6e-3362ad94296b.jpg)

**Comment by greggirwin** [comment]
Thanks for the report. We have an AV initiative in the works to deal with these false positives.

**Comment by greggirwin** [comment]
I've linked this ticket for that work, and so will close this ticket as we can't address the AV issues here.

**Comment by dockimbel** [comment]
@anta40 Could you provide your Windows Defender definitions version?
