### ISSUE TITLE
CRASH on extensive map copying (not garbage collected?)

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3261]
```
Red []
m: #(a: 1 b: 2 c: 3 d: 4 e: 5 f: "6" g: "7" h: "8")
loop 10000000 [copy m]
probe m
```
### Expected behavior
no crash
### Actual behavior
```
*** Runtime Error 19: stack error or overflow
*** at: 0041929Eh
```
note: address varies
### Steps to reproduce the problem
use big number in the loop above, 1e6 isn't enough, 1e7 is fine
### Red version and build date, operating system with version.
Red 0.6.3 system/build/config/build-basename = **%console-2017-8-3-49893** (stable) and **%console-2018-3-11-43723** (nightly)
OS: win7 x64 v6.1.7601

**Comment by dockimbel** [comment]
It should not crash, you should rather get an out of memory error, as the GC is not plugged into the master branch yet.

**Comment by hiiamboris** [comment]
how do I manually free maps and objects until GC is there?

**Comment by dockimbel** [comment]
For maps and objects, you can't. For series, you can re-use them, so you don't have to allocate new ones.

**Comment by greggirwin** [comment]
@hiiamboris, can we close this ticket, since we know GC isn't there yet?

**Comment by hiiamboris** [comment]
as you wish :)

**Comment by dockimbel** [comment]
We can leave it open for now, as we need to bring a specific handler for out-of-memory error in extreme cases. I started working on such support in this branch: https://github.com/red/red/tree/issue-3261, though this require much more time to get it done, so I label this ticket as "deferred" for now.
