### ISSUE TITLE
Selecting `About` menu crashes the GUI console

### ISSUE THREAD

**Issue by planetsizecpu** [red/red#3267]
### Expected behavior
Press on console File/About option, then message window should appear

### Actual behavior
Console exit to OS.

### Steps to reproduce the problem
Press on File/About option.

### Red version and build date, operating system with version.
Red for Windows version 0.6.3 built 19-Mar-2018/10:16:49+01:00

**Comment by dockimbel** [comment]
Regression caused by commit https://github.com/red/red/commit/ee507c76269fbde4040618944f2ae8a13d1844cf
