### ISSUE TITLE
Console doesn't catch some `cause-error` from `try` (and quits)

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3268]
### Steps to reproduce the problem
`>> try [break]`
(or anything from system/catalog/errors/throw category)

### Expected behavior
same as if there was no "try"
```
--== Red 0.6.3 ==--
Type HELP for starting information.

>> break
*** Throw Error: no loop to break
*** Where: break
*** Stack:
```

### Actual behavior
silent exit from the console (although an extra layer of try/all catches this)

### Red version and build date, operating system with version.
Red 0.6.3 system/build/config/build-basename = %console-**2017-8-3-49893** (stable) and %console-**2018-3-11-43723** (nightly)
OS: win7 x64 v6.1.7601

**Comment by bitbegin** [comment]
That's how it is designed. You should use try/all.

```
>> ? try
USAGE:
     TRY block

DESCRIPTION: 
     Tries to DO a block and returns its value or an error. 
     TRY is a native! value.

ARGUMENTS:
     block        [block!] 

REFINEMENTS:
     /all         => Catch also BREAK, CONTINUE, RETURN, EXIT and THROW exceptions.

>> try/all [break]
*** Throw Error: no loop to break
*** Where: break
*** Stack:  

>> 
```

**Comment by hiiamboris** [comment]
I disagree @bitbegin . It should report an error instead of crashing.

**Comment by bitbegin** [comment]
Maybe we should set /all for default, and remove /all

**Comment by greggirwin** [comment]
R2:
```
>> try [break]
** Throw Error: Nothing to break
** Near: break
>> break
** Throw Error: Nothing to break
** Near: break
```
Red:
```
>> try [break]
<poof!>

>> try/all [break]
*** Throw Error: no loop to break
*** Where: break
*** Stack:  

>> break
*** Throw Error: no loop to break
*** Where: break
*** Stack:  
```

This needs more research. It may be something the console needs to handle differently, or may be due to compiler and interpreter differences. Not something we want to change lightly, without full understanding.

**Comment by greggirwin** [comment]
I agree that it shouldn't crash though.
