### ISSUE TITLE
Direct download of image does not work

### ISSUE THREAD

**Issue by Oleg-N-Cher** [red/red#3278]
Tried in stable Red 0.6.3 for Windows and the latest red-23mar18-5f9c4283.exe

It doesn't work:

`  view [image load http://rebol.com/view/bay.jpg]`

*** Script Error: VID - invalid syntax at: [load http://rebol.com/view/bay.jpg]
*** Where: do
*** Stack: view layout cause-error  

The same happens when to download an image from a file:

`  view [image load %/n/gLf0HJEKI1M.jpg]`

Although it works:

```
  img: load http://rebol.com/view/bay.jpg
  view [image img]
```

Can I assume that this is a bug, and not some feature of Rebol that is not present in Red?

The example given from lesson Computer Programming Tutorial, by Nick Antonaccio (#03) and looks (in Rebol):

`  view layout [image load http://rebol.com/view/bay.jpg]`

Thanks.

**Comment by greggirwin** [comment]
Red is not going to be 100% compatible with Rebol. This particular bit may come later but your workaround is fine. You can also see, and add to, notes @gltewalt put together at: https://github.com/red/red/wiki/Differences-between-Red-and-Rebol

**Comment by greggirwin** [comment]
Also, even in the best case, you may eventually need to use a `paren!` for the loading part.

**Comment by greggirwin** [comment]
Another, shorter workaround is just to directly reference the URL, which is the best solution.
```
 view [image http://rebol.com/view/bay.jpg]
```
