### ISSUE TITLE
Strange output about what happens on the source in Win1251 encoding

### ISSUE THREAD

**Issue by Oleg-N-Cher** [red/red#3280]
I accidentally tried to open a source file in the Win1251 encoding instead of UTF-8. And that's what happened:

> *** Error: cannot access argument file:
> Face.red
> --== Red 0.6.3 ==-- 
> Type HELP for starting information. 
> 
> >>

Red certainly was not meant to work in Win1251 encoding, but exception handling/error reporting can be more informative to help understand what is really happening, not confuse.
I attach the file that reproduces this behavior.

[Face.zip](https://github.com/red/red/files/1844939/Face.zip)

**Comment by dockimbel** [comment]
Thank you for providing a test file.
