### ISSUE TITLE
[WISH] [R/S] add syntax to get pointer to a pointer

### ISSUE THREAD

**Issue by qtxie** [red/red#3287]
Wish to get a pointer which point to a pointer.
### Code
```
Red/System []

test: func [
    p   [int-ptr!]
    pp  [int-ptr!]
][
    p: allocate 10
    pp: :p
]
```

**Comment by dockimbel** [comment]
Implemented by commit https://github.com/red/red/commit/2107361c14270b4a3e47eb575416334572bebe8f.
