### ISSUE TITLE
build.r script hangs on Rebol 2.7.8.3.1

### ISSUE THREAD

**Issue by endo64** [red/red#3295]
### Expected behavior

No hangs and builds Red.exe

### Actual behavior

Rebol.exe hangs in background when build.r script executed.

### Steps to reproduce the problem

Execute build.r script with encap.exe from Rebol SDK 2.7.8.

### Version

Red for Windows version 0.6.3 built 29-Mar-2018/23:06:16+03:00

Latest source. Win10 x64 (possibly on all Windows' OSes)

**Comment by qtxie** [comment]
Thanks! :-)
