### ISSUE TITLE
[R/S] cannot compile float -0.0

### ISSUE THREAD

**Issue by qtxie** [red/red#3297]
The code below cannot be compiled anymore.
### Code
```
Red/System []
probe -0.0
```
Compiling error:
```
Compiling to native code...
*** Compilation Error: unknown directive .0- 
*** in file: %/D/Work/tests.reds 
*** at line: 2 
*** near: [#.0-]
```
### Version (run `about` in the Red Console and paste the result here) also add OS version.
Win7 64bit
master branch commit [e65fcfec8a3a5c63cda5f4a862f9929ec803ac4a]

**Comment by dockimbel** [comment]
Support for special float values is not implemented yet in R/S.

**Comment by meijeru** [comment]
What is so special about `-0.0`?

**Comment by rebolek** [comment]
@dockimbel see https://github.com/red/red/issues/3763#issuecomment-459890255 , it crashes for                            very non-special value of `-0.01` also.

**Comment by dockimbel** [comment]
@meijeru Signed zeros are special values in IEEE754 floating point standard: https://en.wikipedia.org/wiki/Signed_zero

**Comment by dockimbel** [comment]
Support for special float values added in `negative-zero` branch, merged in master now.
