### ISSUE TITLE
list-dir prints only dots and is very slow on GUI console

### ISSUE THREAD

**Issue by endo64** [red/red#3298]
### Expected behavior

Directory list should be printed.

### Actual behavior

Only dots `...` printed for every file.

### Steps to reproduce the problem

Open GUI console and type `ls` or `list-dir`

### Version

Red 0.6.3 for Windows built 30-Mar-2018/11:40:57 commit #317934fa
Win10 x64.

**Comment by qtxie** [comment]
Should be fixed now.
