### ISSUE TITLE
New console help/about gives invalid path error on clicking links

### ISSUE THREAD

**Issue by meijeru** [red/red#3306]
### Expected behavior

Help about contains two links: `red-lang.org` and `github.com/red/red`. These should both be clickable.
### Actual behavior

The first one is indeed displaying the Red site, the second one is inoperative.
### Steps to reproduce the problem

Run the console, select help/about and click on the second link: nothing happens
### Version (run `about` in the Red Console and paste the result here) also add OS version.

Red 0.6.3 for Windows built 31-Mar-2018/17:00:58 commit #d8e9eaad (on Win10)

The culprit is the [following line in the `link` style](
https://github.com/red/red/blob/master/environment/console/GUI/settings.red#L72) where `face/font` is `none`.

**Comment by dockimbel** [comment]
This issue has the same cause as #3300. Closing this ticket now.
