### ISSUE TITLE
GUI Console nightly build - color chooser not working

### ISSUE THREAD

**Issue by gltewalt** [red/red#3307]
### Expected behavior
Clicking on a background color, or font color changes the background color or font color.
### Actual behavior
Clicking a color in the color pallet does not change the RGB value.
### Steps to reproduce the problem
Download latest build, compile GUI Console. Select `Options` then `Settings`, click on a color.
### Version (run `about` in the Red Console and paste the result here) also add OS version.
Red 0.6.3 for Windows built 1-Apr-2018/18:57:10 commit #ddacd32c

Win7 Pro

**Comment by greggirwin** [comment]
Confirmed.

**Comment by qtxie** [comment]
It's a regression. https://github.com/red/red/issues/3300

**Comment by dockimbel** [comment]
#3300 is fixed, so I'm closing this ticket.
