### ISSUE TITLE
CRASH when making an object with a recursive block

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3318]
### Steps to reproduce the problem
```
>> append/only l: [1] l
== [1 [...]]
>> c: context [x: l]
== make object! [
    x: [1 [...]]
]
>> make c []
(crash)
>> bind l c
(crash)
>> copy/deep l
(crash)
```
### Actual behavior
```
*** Runtime Error 19: stack error or overflow
*** at: 0041A38Dh
```
### Expected behavior
A normal catchable error at least.
Better if there was a way to tell `make` not to use `copy/deep` and `bind` on inner blocks? or also inner objects? Sometimes recursive data is something valid, like a doubly-linked-list.

### Version (run `about` in the Red Console and paste the result here) also add OS version.
`Red 0.6.3 for Windows built 31-Mar-2018/3:49:39 commit #d8e9eaad`
and the stable 0.6.3
win7 x64 6.1.7601

**Comment by dockimbel** [comment]
> Better if there was a way to tell make not to use copy/deep and bind on inner blocks?

Binding is part of object's creation process.

**Comment by hiiamboris** [comment]
I just found an even worse limitation:
```
>> make reactor! [x: l]
(crash)
>> r: make reactor! [x: 0]
r/x: l
(crash)
```
It's totally impossible right now to use recursive series in the reactors :(

**Comment by hiiamboris** [comment]
I guess cunning can get one anywhere though...
```
append/only l: [1] l
c: context [x: l]

link: func ['w [any-word!] /with c [object!]] [
	c: any [c context? :w]
	func [/update v] compose/deep [
		either update [set bind (to-lit-word :w) (c) v][get bind (to-lit-word :w) (c)]
	]
]
r: make reactor! [
	x: link/with x c
	y: link l
]
>> r/x/update l
>> r/x
== [1 [...]]
>> r2: make r []
>> r2/x
== [1 [...]]
>> r2/y
== [1 [...]]
```
works like a charm, if just a bit slower..

**Comment by greggirwin** [comment]
> Is it impossible to make a shallow bind, sort of, as an option?

@hiiamboris, what would be the context of deep words then?

**Comment by hiiamboris** [comment]
> what would be the context of deep words then?

@greggirwin same as in the prototype maybe?

**Comment by hiiamboris** [comment]
@greggirwin They were bound already, so how does that harm?

**Comment by 9214** [comment]
@hiiamboris they were bound because `make object!` did a deep traversal in the first place.

**Comment by dockimbel** [comment]
For the record, both Rebol 2 and 3 are crashing on such code.

**Comment by greggirwin** [comment]
@hiiamboris should we start (or see if we already have) a wiki page for advanced topics and cunning workarounds?

**Comment by dockimbel** [comment]
Now Red no longer will crash on those cases, returning just a catchable error in case the circular reference can't be handled:
```
>> make c []
*** Internal Error: block or paren series is too deep to display
*** Where: make
*** Stack:  

>> bind l c
== [1 [...]]

>> copy/deep l
*** Internal Error: circular reference not allowed
*** Where: copy
*** Stack:  
```
