### ISSUE TITLE
Form and to string! on image - not enough memory

### ISSUE THREAD

**Issue by nedzadarek** [red/red#3320]
### Expected behavior 
It should return string
### Actual behavior
```
*** Internal Error: not enough memory
*** Where: form
*** Stack:  
```
And Red.exe took 1GB ram.
### Steps to reproduce the problem
```
form make image! [10x10]
to-string make image! [10x10]
```
### Red and platform version
```
Red for Windows version 0.6.3 built 26-Mar-2018/1:14:22+02:00
```
Win 8.1 64b with 4GB ram

**Comment by greggirwin** [comment]
Confirmed on Windows 7.

**Comment by greggirwin** [comment]
`Mold` is fine.

**Comment by meijeru** [comment]
1x1 and 2x2, even 2x3 are OK. Trouble starts (on W10) from 3x3 already.

**Comment by meijeru** [comment]
Hopefully all of this is enough to put @qtxie on the right track...

**Comment by qtxie** [comment]
@meijeru @nedzadarek Very useful information. Thanks a lot. :+1:
