### ISSUE TITLE
Windows GUI console has problem with some unicode string input from clipboard.

### ISSUE THREAD

**Issue by Oldes** [red/red#3324]
When you select&copy this text: ```to-binary "🦄"``` and paste it to console, there will be redundant null char:
```
>> to-binary "🦄"
*** Syntax Error: invalid value at "^@"
*** Where: do
*** Stack: load 
```
The edit of the line in the console is also broken because of it.

Linux version was reported to be working correctly.

EDIT:
better test case:
```
>> to-string #{F09FA684}
== "🦄"
>> write-clipboard to-string #{F09FA684} read-clipboard
== "🦄^@"
>> write-clipboard to-string #{F09FA684F09FA684} read-clipboard
== "🦄🦄^@^@"
```

**Comment by meijeru** [comment]
Could you specify the Unicode number? Is it the unicorn face at U+1F984?

**Comment by Oldes** [comment]
@meijeru I don't know... I just copy pasted "unicorn" from a web page to see if it works or not with Red console... and found the issue.

**Comment by 9214** [comment]
@rebolek first :bear:, now :unicorn: .

**Comment by qtxie** [comment]
This issue has been fix. I'll close it.
The caret still not working properly, though it's another issue (maybe hard to fix :upside_down_face: ).
