### ISSUE TITLE
Latest console has trouble with dead keys

### ISSUE THREAD

**Issue by meijeru** [red/red#3325]
### Expected behavior

Dead keys like `"` (there are about six on my keyboard) should be handled correctly, i.e. a `"` keypress should not give an echo, and the `"` character should appear after a subsequent `space` keypress. Likewise, a `"` followed by an `a`  should result in an `ä` appearing.
### Actual behavior

The first `"` keypress echoes a `"`, and the following `space` gives another `"`. Likewise, `"` followed by `a` gives `"ä`.

### Steps to reproduce the problem

Do the keypresses as shown above, on a keyboard with dead keys (mine is a Logitech K270).

### Red and platform version
```
-----------RED & PLATFORM VERSION----------- 
RED: [ branch: "master" tag: #v0.6.3 ahead: 595 date: 6-Apr-2018/13:49:30 commit: #f53f9073931e1acc7ee00e9ddad4615e14326a68 ]
PLATFORM: [ name: "Windows 10" OS: 'Windows arch: 'x86-64 version: 10.0.0 build: 16299 ]
--------------------------------------------
```

**Comment by meijeru** [comment]
I should say that this error makes it almost impossible to type anything with quotes into the console.

**Comment by qtxie** [comment]
@meijeru Does the old gui console has this issue?

**Comment by meijeru** [comment]
Not that I remember.

**Comment by greggirwin** [comment]
@meijeru is there a "dead key" reference somewhere? I'm not familiar with the term and can't dupe this (win7 ATM).

**Comment by meijeru** [comment]
On my keyboard the single and double quotes (as well as a few other keys) do not immediately yield a character. Instead, the system waits for the next key, and types the quote over the next character if that is a space, or turn it into an accent (') or diairesis (") when that next character is a vowel. That is a way to produce accented letters. Works also with back-tick `, tilde ~ and caret/circumflex (^) . It even does '+c = ç, ~+n=ñ and a few more.

**Comment by meijeru** [comment]
See also [wikipedia](https://en.wikipedia.org/wiki/Dead_key)

**Comment by greggirwin** [comment]
Interesting. I'm transitioning to Win10, but maybe someone else will chime in to confirm before I do.
