### ISSUE TITLE
Number conversion

### ISSUE THREAD

**Issue by GerardSontag** [red/red#3326]
### Expected behavior
>> to-integer 2#{00000001}
== 1
>> to-integer 16#{00000001}
== 1
so 
to-integer 16#{0001} would return  1
### Actual behavior
unfortunatly
>> to-integer 64#{0001}
== 13847861
and
>> to-integer 64#{00000001}
== -749914925
return wrong values
### Steps to reproduce the problem
N/A
### Red and platform version
0.6.3 W10/64b

**Comment by meijeru** [comment]
There is a misunderstanding here: What is enclosed by `64#{` and `}` is encoded by [Base64](https://en.wikipedia.org/wiki/Base64) encoding, and not by normal hexadecimal encoding. Try `64#{0001}` in the console, and you will see that it is not equal to `16#{0001}`.

**Comment by DideC** [comment]
@GerardSontag `64#{0001}` is not equal to `16#{0001}` !!
I invite you to read what is base 64 encoding, for exemple on [wikipedia](https://en.wikipedia.org/wiki/Base64).

**Comment by meijeru** [comment]
Thanks DideC for reinforcing my comments. I woudl recommend this issue for closing.

**Comment by 9214** [comment]
@GerardSontag before reporting an "issue", it might be a good idea to check out in [/bugs](https://gitter.im/red/bugs) room and clarify if the observed behavior is indeed buggy and unexpected.

**Comment by greggirwin** [comment]
@GerardSontag, you can also use to play with alternate representations, to compare.
```
>> to char! 1
== #"^A"
>> enbase/base "^A" 64
== "AQ=="
>> enbase/base "^A" 16
== "01"
>> debase/base "00000001" 64
== #{D34D34D34D35}
```

**Comment by GerardSontag** [comment]
Thank you all,  my apologies
"There is a misunderstanding here"

**Comment by greggirwin** [comment]
Not to worry Gerard. We've all been there.
