### ISSUE TITLE
unset crash console

### ISSUE THREAD

**Issue by planetsizecpu** [red/red#3338]
### Expected behavior
If a word can't be unset issue an error

### Actual behavior
hang for a moment and crash console

### Steps to reproduce the problem
unset word [block]

### Red and platform version
Red 0.6.3 for Windows built 16-Apr-2018/11:21:12+02:00 commit #7c6d67f

```
>> about
Red 0.6.3 for Windows built 16-Apr-2018/11:21:12+02:00 commit #7c6d67f
a: [1]
unset a
```

**Comment by meijeru** [comment]
It will also happen with `unset [1]`.

**Comment by planetsizecpu** [comment]
Instead  `unset 'a ` works properly, as usual.

**Comment by meijeru** [comment]
Yes, that is because in `unset a`, there is an evaluation of `a`! The moral is: probably anything other than a `word!`  value leads to a crash.

**Comment by 9214** [comment]
I can reproduce this with `unset` and `block!` argument containing at least one non-`any-word!` value.

**Comment by meijeru** [comment]
Conclusion: anything other than a word or block of words leads to a crash.
