### ISSUE TITLE
It is not possible to set a newline at tail of a block using new-line function

### ISSUE THREAD

**Issue by Oldes** [red/red#3348]
This works:
```
>> b: [1 2] new-line next b true append b 3 b 
== [1 
2 3 
] 
```
But this does not works:
```
>> b: [1 2] new-line tail b true append b 3 b 
== [1 2 3]
```
Expected result is:
```
== [1 2
3]
```

PS: Rebol3 has same problem. https://github.com/rebol/rebol-issues/issues/2303

**Comment by greggirwin** [comment]
What you expect is not possible. The new-line marker is stored with the word/slot, not the series itself, so when you use `tail`, there is nothing for `new-line` to work against. It's like saying `new-line [] on`.
