### ISSUE TITLE
Wallet code uses diverging macro definitions for HIWORD and LOWORD

### ISSUE THREAD

**Issue by meijeru** [red/red#3354]
### Expected behavior

Once a useful macro has been defined, other code should use it as is, or define another one with a different name.

### Actual behavior

In the wallet folder:

    #define LOWORD(param) (param and FFFFh << 16 >> 16)
    #define HIWORD(param) (param >> 16)

In Red toolchain:

    #define LOWORD(int) (int and FFFFh)
    #define HIWORD(int) (int >>> 16)

These are not identical.
### Steps to reproduce the problem

There may not yet be a problem, but confusion and difficult to detect errors seem possible.

**Comment by dockimbel** [comment]
That's a wallet issue, not a Red issue.

**Comment by meijeru** [comment]
Depending on which formulation of the HIWORD/LOWORD definitions is considered better/more appropriate.

**Comment by greggirwin** [comment]
@meijeru they were renamed in the wallet:
```
	;--extract the short type data from integer!
	#define HID_LOWORD(param) (param and FFFFh << 16 >> 16)
	#define HID_HIWORD(param) (param >> 16)
```
