### ISSUE TITLE
Error messages for make on unallowed types are inconsistent

### ISSUE THREAD

**Issue by meijeru** [red/red#3359]
### Expected behavior

Using `make` with a type for which it is not defined should always give the message

    *** Script Error: make does not allow <type> for its type argument
    *** Where: make
    *** Stack:  

### Actual behavior

With `datatype! routine!` and `event!` this message is indeed displayed.
With `native!` and `action!`, the other two types for which `make` is not defined, the message is

    *** Script Error: cannot MAKE <type> from: <...>
    *** Where: make
    *** Stack:  

This will leave the users wondering from which expression they CAN indeed make a native or action, but in reality this will never succeed.

### Steps to reproduce the problem

Use `make` with any of the above-mentioned types.

### Red and platform version
```
-----------RED & PLATFORM VERSION----------- 
RED: [ branch: "master" tag: #v0.6.3 ahead: 669 date: 27-Apr-2018/10:07:23 commit: #4c36108655f3410124f8539543cbd4bc4525fed1 ]
PLATFORM: [ name: "Windows 10" OS: 'Windows arch: 'x86-64 version: 10.0.0 build: 16299 ]
--------------------------------------------
```

**Comment by dockimbel** [comment]
You are making false assumptions there. `make` is defined for `native!` and `action!`:
```
>> puts: make native! [[v [any-type!]] 23]
== make native! [[v [any-type!]]]
>> puts "Hello"
Hello
```

**Comment by meijeru** [comment]
These "makes" are used in the initalizing phase of the compiler, I suppose. But should they be available to the user??

**Comment by dockimbel** [comment]
They are available to the users as a way to recreate a `native!` or `action!` value if needed. For examply, after doing a `print: none`, you can recreate the `print` native if necessary. Rebol supports that too.

The second argument is just `[[<spec>] <id>]` here `<spec>` is the right action/native spec block (a wrong one will currently lead to a crash), and `<id>` is the index of the action/native in their respective internal tables: [actions ID](https://github.com/red/red/blob/master/runtime/macros.reds#L69), [natives ID](https://github.com/red/red/blob/master/runtime/macros.reds#L147)

**Comment by meijeru** [comment]
I myself know how it works, but look at the way you explain it - it sounds awfully esoteric for the general user. R2 forbade it altogether.

**Comment by meijeru** [comment]
I have added some wording to the spec document saying it is not recommended...

**Comment by 9214** [comment]
It would be nice if `body-of` on `native!`s and `action!`s returned their IDs, the way R2 does.
```rebol
>> second :find
== 53
```
Curiously, this works only with `second` but not with `body-of`, which yields `none` instead (same as in R3).

**Comment by meijeru** [comment]
Let's make that a wish!!
