### ISSUE TITLE
Latest GUI Console fails to start

### ISSUE THREAD

**Issue by nickkoro02** [red/red#3364]
### Expected behavior
GUI Console compiles and starts normaly.
### Actual behavior
Displays the following:
![2018-05-05 13_05_47-c__users_user_desktop_red-gui exe](https://user-images.githubusercontent.com/19800702/39662649-7cc10ba8-5065-11e8-8a64-5815ae779132.png)

Tried starting with the VS 2017 debugger (I have literary no experience with it through) and it gave me the following message (freely translated from german):
```
Exception at 0x657AFF75 (CoreUIComponents.dll) in red-gui.exe: 0xC0000602:  A fail fast exception occurred. Exception handlers will not be invoked and the process will be terminated immediately 
```
Original:
![2018-05-05 13_12_05-red-gui debugging - microsoft visual studio](https://user-images.githubusercontent.com/19800702/39662683-f4b54f2a-5065-11e8-9cfb-f78929c723b4.png)

### Steps to reproduce the problem
Download latest Windows build from https://www.red-lang.org/p/download.html. `red-04may18-1c0952c0.exe` at time of writing.

### Red and platform version
```
Lenovo E31-70
Windows 10 x64
```

**Comment by nickkoro02** [comment]
After renaming it from `red-gui.exe` to `red-latest.exe` it actually works. If I rename it back it doesn't.

**Comment by Tallefer** [comment]
Some older version did leave some files (after crashing) in the temp/profile dir, and they somehow messed with running Red again, please check there. Just a wild guess.

**Comment by nickkoro02** [comment]
I tried deleting the `C:\ProgramData\Red` and `%AppData%\Red` folders but it didn't solve the problem. When I try to start the Red executable it now reports a `Rebol/Pro SDK` Error or just crashes without a message. It actually fails to compile the GUI Console, the `C:\ProgramData\Red` directory contains the source of it (several `.red` files, `crush-xxxxx.dll` and a `GUI` directory). Does Red store files anywhere else?

**Comment by Tallefer** [comment]
Yep, those are the ones, I don't think there are others. Oh well.

**Comment by 9214** [comment]
Do you have AV turned on by any chance?

**Comment by nickkoro02** [comment]
Nope, I always turn off Avira when working with Red.

**Comment by greggirwin** [comment]
@nickkoro02 does this still happen for the latest automated build? What about the stable build?

**Comment by Tallefer** [comment]
Another wild guess. @nickkoro02 did you try to clean "Downloaded from Internet" flag from executable/zip? Also maybe that particular folder's policy is different somehow? Did you try to run it from another folder/disk?

**Comment by gltewalt** [comment]
I've seen this crash before, months ago.  I don't think that we figured out why, but I think downloading rebview.exe was the solution.

**Comment by endo64** [comment]
Any update @nickkoro02 ? If not are we good to close this @greggirwin ?

**Comment by nickkoro02** [comment]
Oh, I've completly forgoten this issue. I reinstalled my Windows last week and cannot reproduce the issue now. 

Feel free to close it and thank you for the reminder.
