### ISSUE TITLE
Compiled object keep using memory

### ISSUE THREAD

**Issue by qtxie** [red/red#3366]
### Expected behavior
Memory usage is stable.
### Actual behavior
Memory usage is increasing.
### Steps to reproduce the problem
Compiles the following code and run.
```
Red [Needs: View]
w: layout [size 200x200]
caret: make face! [
    type: 'base offset: 1x1 size: 1x17 rate: 30
]
caret/actors: object [
    on-time: func [face [object!] event [event!]][
        face/color: 0.0.0
    ]
]
append w/pane caret
view w
```
### Red and platform version
```
Red 0.6.3 for Windows 7 64bit built 5-May-2018/19:45:17+08:00
```

**Comment by greggirwin** [comment]
Confirmed that the leak occurs when compiled on Win10 as well. Running from the REPL is fine. Only compiled is the issue.

**Comment by qtxie** [comment]
Should be fixed in simple-gc branch.
