### ISSUE TITLE
trim/with corrupts trim function

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#3374]
### Expected behavior
>> trim/all {   a ^-1^/    ab2^-  ^/  ac3  ^/  ^/^/}
== "a1ab2ac3"
### Actual behavior
>> mstr: {   a ^-1^/    ab2^-  ^/  ac3  ^/  ^/^/}
== {   a ^-1^/    ab2^-  ^/  ac3  ^/  ^/^/}
>> trim/all {   a ^-1^/    ab2^-  ^/  ac3  ^/  ^/^/}
== "a1ab2ac3"
>> "    ^-1^/    2^-  ^/  c3  ^/  ^/^/" = trim/with copy mstr "ab"
== true
>> trim/all {   a ^-1^/    ab2^-  ^/  ac3  ^/  ^/^/}
== {^-1^/2^-^/c3^/^/^/}
>> 
### Steps to reproduce the problem
run the above code
### Red and platform version
commit 9ce2aacce1509943ac11efa3b13457e8a66f03b4 (HEAD -> master, upstream/master)
macOS 10.12.16

**Comment by meijeru** [comment]
Looks like unintentional global?
