### ISSUE TITLE
Wrong error message when giving wrong accessor to time value

### ISSUE THREAD

**Issue by meijeru** [red/red#3384]
### Expected behavior
```
>> t: 0:00
== 0:00:00
>> t/day
*** Script Error: cannot access day in path t/day
*** Where: catch
*** Stack:  
```
### Actual behavior
```
>> t: 0:00
== 0:00:00
>> t/day
*** Script Error: cannot access day in path [script invalid-path]
*** Where: catch
*** Stack:  
```
### Steps to reproduce the problem
run the above code
### Red and platform version
```
any
```

**Comment by meijeru** [comment]
I seem to remember having made a similar issue for another datatype (since then solved). For this one, I am not sure it has already been reported.

**Comment by hiiamboris** [comment]
https://github.com/red/red/blob/e0a31a954b223ca9767c73d99ce26891d83440c1/runtime/datatypes/time.reds#L281
should be `fire [TO_ERROR(script invalid-path) path element` ?
same bug with pair!

**Comment by meijeru** [comment]
Merged  and therefore solved.
