### ISSUE TITLE
NOW silently ignores some refinements

### ISSUE THREAD

**Issue by meijeru** [red/red#3385]
### Expected behavior

`now` should raise an error if it has more than one refinement and they are incompatible
### Actual behavior

`now/time/day` and `now/day/time` both act as if `/time` was not there, giving the result of `now/day`
### Steps to reproduce the problem

execute `now/time/day` in GUI console
### Red and platform version
```
Red 0.6.3 for Windows built 27-Apr-2018/12:07:23+02:00 commit #4c36108
```

**Comment by endo64** [comment]
R2, R3 and Red have different behaviors on multiple refinements:
```
>> now/time/day
; Red== 11
; R2 ==  ** Script Error: Too many refinements
; R3 == 10:10:09
```

**Comment by meijeru** [comment]
R2 seems the most sensible one

**Comment by bitbegin** [comment]
I wanted fix this by disallow more than one refinements for now, but found another issue: "now/time/precise is allowed"

**Comment by bitbegin** [comment]
i set these refinements (year month day time zone weekday yearday) to be uniqued, and `date precise utc` can be existed with above refinements at the same time.

**Comment by dockimbel** [comment]
Too many combinations to check:
```

>> now/time
== 21:19:47
>> now/time/utc
== 19:19:49
>> now/utc
== 20-Aug-2019/19:19:52
>> now/utc/precise
== 20-Aug-2019/19:19:56.783413
>> now/time/utc
== 19:20:14
>> now/time/utc/precise
== 19:20:40.798931
```
