### ISSUE TITLE
How to hide the console for a GUI program in Red Language on Windows?

### ISSUE THREAD

**Issue by ZJUGuoShuai** [red/red#3386]
I wrote a simple "hello world" GUI program on Windows. And compiled it. When I double-clicked the `hello.exe`, it displayed a black console window behind my GUI program like this:
![img](https://wx2.sinaimg.cn/mw1024/8163951egy1fr7hnr2xljj20o90efjrr.jpg)
### Expected behavior
There is only my GUI program displayed.
### Actual behavior
An additional console window displayed behind.
### Steps to reproduce the problem
Double-click the `hello.exe` program.
### Red and platform version
Windows 10 / Red 0.6.3
```
Red [Needs: 'View]

view [text "Hello World!"]
```

**Comment by PeterWAWood** [comment]
You need to supply the `-t Windows` compiler option to exclude the console.

**Comment by 9214** [comment]
@ZJUGuoShuai use [community chat](https://gitter.im/red/help) instead of issue tracker to ask your questions.
