### ISSUE TITLE
max and min are not compatible with > and <

### ISSUE THREAD

**Issue by meijeru** [red/red#3395]
### Expected behavior

for all `p` and `q` for which `>, >=, <, <=` are defined, it should hold that 
if `p >= q` then `(max p q) = p` and analogous for `min`
### Actual behavior

with tuples at least, this is not the case:
`1.2.3.4 >= 1.2.3` but `max 1.2.3 1.2.3.4` yields an error

### Steps to reproduce the problem

execute above example codes
### Red and platform version
```
all
```

**Comment by meijeru** [comment]
See also this red/bugs discussion:  [May 21, 2018 9:58 PM](https://gitter.im/red/bugs?at=5b0324eb2df44c2d0646d0f4)

**Comment by greggirwin** [comment]
For pairs, it's not hard to see how the behavior could make some things easier, but I agree that consistency should win here, and helper funcs could take the place of it. The strongest argument against that is performance, which could be important in GUI and drawing scenarios.

**Comment by greggirwin** [comment]
@dockimbel needs to weigh in on this, as it's not behavior from R2 on tuples, and it's not a default. It was explicitly written to do this, so we need the design intent there.

**Comment by dockimbel** [comment]
@greggirwin Looks like R2 implements `min/max` in a way consistent with comparisons for tuples.
