### ISSUE TITLE
libcurl.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by DanielSokil** [red/red#3399]
Downloaded red-063
```
sudo apt-get install ia32-libs libc6-i386 libcurl3
chmod u+x red-063
./red-063
```

Output:
```
/home/user/.red/console-2017-8-3-49893: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
```

OS Info:
```
RELEASE=18.3
CODENAME=sylvia
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 18.3 Sylvia"
DESKTOP=Gnome
TOOLKIT=GTK
GRUB_TITLE=Linux Mint 18.3 Cinnamon 64-bit
```

Solution:
```
sudo apt-get install libcurl3:i386
```

**Comment by bitmage** [comment]
Maybe I'm missing something?  I'm running 64 bit linux, and downloaded what I thought would be the 64 bit version of Red.

```bash
$ readelf -a red-064  | grep 32
  Class:                             ELF32
  Size of program headers:           32 (bytes)
  [15] .rodata           PROGBITS        080aa020 062020 007554 00   A  0   0 32
  [23] .data             PROGBITS        080b2880 069880 0069e4 00  WA  0   0 32
  [24] .bss              NOBITS          080b9280 070264 004c2c 00  WA  0   0 32
```
After `apt-get install libc6-i386` the binary runs, but then I get the error above by DanielSokil.  I'm not too keen on installing a whole bunch of 32 bit dependencies on my system.  What's going on here?  Why the 32 bit binary?

**Comment by greggirwin** [comment]
There is no 64-bit version of Red at this time. You need to install the 32-bit libs for your OS.

**Comment by NewSunSEO** [comment]
Hello, I am having a similar issue.  I tried - sudo apt-get install libcurl3:i386

But it did not work for me.  

cryptovibe@ubuntu:~/Desktop/miner$ sudo apt-get install libcurl3:i386
[sudo] password for cryptovibe: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libcurl3:i386

Thank you anyone who see's this & tries to help.

**Comment by hiiamboris** [comment]
@NewSunSEO have you tried looking at the [download page](https://www.red-lang.org/p/download.html)?
![](https://i.gyazo.com/948597260412b8a80a695209d4b3abda.png)
(note `libcurl4:i386`)

**Comment by NewSunSEO** [comment]
I just installed ubuntu-20.04.3-desktop-amd64.  I'm completely new to Linux, but I wanted to compare Linux with Windows 10 for some CPU mining.  I barely know anything about Linux yet.  I'm looking at this now.  

Thank you!
