### ISSUE TITLE
field not work, cannot input anything

### ISSUE THREAD

**Issue by zhaoxiongfei** [red/red#3401]
OS: mac pro 10.13.4 (17E199)

**Comment by qtxie** [comment]
I'm using macOS 10.13.4 (17E202) I tried `view [field]` in the [latest version](https://static.red-lang.org/dl/auto/mac/red-latest). Works fine.
Would you please give us more details about how to reproduce this issue?

**Comment by dockimbel** [comment]
Can't be reproduced, so we'll close this ticket. Feel free to re-open with new information if it is reproducible.
