### ISSUE TITLE
rejoin inserts newline in wrong position

### ISSUE THREAD

**Issue by meijeru** [red/red#3410]
### Expected behavior
```
>> line: <test>
== <test>
>> rejoin [line "^/"]
== <test>
{{newline here}}
```

### Actual behavior
```
>> line: <test>
== <test>
>> rejoin [line "^/"]
== <test 
{{newline here}}
>
```

### Steps to reproduce the problem

Execute above code. Only applicable to `tag!` values?
### Red and platform version
```
-----------RED & PLATFORM VERSION----------- 
RED: [ branch: "master" tag: #v0.6.3 ahead: 669 date: 27-Apr-2018/10:07:23 commit: #4c36108655f3410124f8539543cbd4bc4525fed1 ]
PLATFORM: [ name: "Windows 10" OS: 'Windows arch: 'x86-64 version: 10.0.0 build: 17134 ]
--------------------------------------------
```

**Comment by meijeru** [comment]
On second thoughts, this makes sense since `< >` are brackets like `{  }` or `"   "`. Rebol does the same.
I close this issue.

**Comment by greggirwin** [comment]
`Rejoin`ing tags has always been a little confusing. It's consistent, but non-obvious.
