### ISSUE TITLE
Bug: set-focus crashes console and compiled script, when closing popup window 

### ISSUE THREAD

**Issue by pixel40** [red/red#3420]
Using set-focus on field in main window causes crash when popup window is unviewed. <br /><br />
**Expected behaviour**<br /><br />
Program to stay open after unview.<br /><br />
**Actual behaviour**<br /><br />
gui console crashes, compiled version crashes.<br/><br/>
**Steps to reproduce the problem**<br/><br/>
```
lay1: layout [
    panel [
        f1: field 200x20 "Hello, I am assisting with crash test"
        return
        button "Press Me First" [
            view [
                button "First step to Crash" [
                    set-focus f1
                    unview
                ]
            ]
        ]
        button "Press Me Second" [
            view [
                text "Do you think this will cause crash?"
                return
                button "Yes" [
                    unview
                ]
            ]
        ]
    ]
]
view lay1
``` 

**Red and platform version**<br/><br/>
Red 0.6.3 for Windows 10 red-07jun18-3f3c037f

**Comment by endo64** [comment]
Confirmed. Non-GUI console also crashes.
