### ISSUE TITLE
compiler error: function value cannot occur alone

### ISSUE THREAD

**Issue by meijeru** [red/red#343]
func[][]
    -= Red Compiler =-
    Compiling red/tests/mytest.red ...
    *** Red Compiler Internal Error: Script Error :
        emit-block expected blk argument of type: block

**Comment by meijeru** [comment]
Can this now be closed?

**Comment by dockimbel** [comment]
It compiles with no errors no, so it can be closed.

Note that the anonymous function support is still very limited in the compiler.
