### ISSUE TITLE
to-char with integer > 10FFFFh crashes

### ISSUE THREAD

**Issue by meijeru** [red/red#3437]
### Expected behavior

>> to-char 110000h
== Error of some kind, e.g. Invalid Unicode Code Point
### Actual behavior

>> to-char 110000h
Crash! 
### Steps to reproduce the problem
execute above code
### Red and platform version
```
-----------RED & PLATFORM VERSION----------- 
RED: [ branch: "master" tag: #v0.6.3 ahead: 669 date: 27-Apr-2018/10:07:23 commit: #4c36108655f3410124f8539543cbd4bc4525fed1 ]
PLATFORM: [ name: "Windows 10" OS: 'Windows arch: 'x86-64 version: 10.0.0 build: 17134 ]
--------------------------------------------
```

**Comment by gltewalt** [comment]
It gives this on Win7 with red --cli
```
>> to-char 110000h
== #"��"
```

Crashes GUI Console

**Comment by meijeru** [comment]
Curiously, `to-integer to-char 110000h` does not crash the GUI console, but yields simply `110000h`.

**Comment by endo64** [comment]
Crashes only on GUI console and only if you try to print:
Here is more detail:

```
>> to-integer c: to-char 110000h
>> write-clipboard form c
Error: to-utf16 codepoint overflow== true
```

**Comment by endo64** [comment]
Crash can be prevented by changing line 96 on `runtime/datatypes/char.reds` from `proto/value: spec/data2` to `proto/value: spec/data2 and FFFFh`  

```
>> to-integer c: to-char 110000h
== 0
>> c
== #"^@"
```

But not sure if it should return an error.

**Comment by meijeru** [comment]
In view of @greggirwin 's laters comment, I close this and open a new issue, just to keep the subject fresh....
