### ISSUE TITLE
Very long bitset and corresponding binary are differently molded and/or printed

### ISSUE THREAD

**Issue by meijeru** [red/red#3438]
### Expected behavior

bitset and underlying binary, when too long to print (mold) conveniently, should be similarly abridged, with ellipsis
### Actual behavior
bitset is differently molded from binary, and binary is printed with ellipsis, whereas bitset is not
>> b: charset ""
== make bitset! #{00}
>> b/(11FFFFh): true
== true
>> to-hex length? b 
== #00120000
>> b
== make bitset! #{0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
>> to-binary b
== #{
0000000000000000000000000000000000000000000000000000000000000000
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000000000000000000000000...
>> length? mold b
== 294928
>> length? mold to-binary b
== 299524

The difference in length is not explained by the presence of `make bitset!` which is absent from the molded binary, on the contrary, the molded binary is longer.
### Steps to reproduce the problem
execute above code
### Red and platform version
```
presumably all (tested only on W10)
```

**Comment by greggirwin** [comment]
Good catch. Bitsets do have their own special formatter internally, but mold and form the same, so fixing `form` will handle both. Not clear on the ellipsis problem source at a glance. It's the same in CLI or GUI console.

**Comment by bitbegin** [comment]
I have fixed `mold/part bitset! limit` issue.
the mold bitset! include "make bitset!" header, and the mold binary! include lf, so their `length? mold` should not equel.

**Comment by meijeru** [comment]
Is there a compelling reason why a molded bitset should not follow the format of a molded binary? In other words, why not have a lf every 64 characters in a molded bitset also? This should also save some code.

**Comment by greggirwin** [comment]
@meijeru, at a glance, it won't save code. Bitset forming uses different logic (nibble based, and accounting for inversion (`not`)) than binary. But I agree that breaking into lines would be nicer and more consistent. No more helpful though. :^) Worth a low priority wish ticket.

**Comment by bitbegin** [comment]
`The primary importance of mold is to produce strings that can be reloaded with load.` -- from rebol doc.
So bitset! need have a diffent header with other datatypes, to allow `load` to load it's literal value. 

string! and bitset! type are molded and matched to console's width, the console can control their display.

**Comment by meijeru** [comment]
I see from your log above that binary! type is indeed molded to console's width! But could bitset! please also?

**Comment by endo64** [comment]
> I see from your log above that binary! type is indeed molded to console's width! But could bitset! please also?

@meijeru In latest version bitset!s also molded to console's width.

**Comment by meijeru** [comment]
I notice that the molded bitset fills the width of the console, and that the molded binary is printed in groups of 64 which get wrapped on smaller widths. But don't that let you stop closing this...

**Comment by Oldes** [comment]
It is not fixed correctly!
```
>> b: charset "^(11FFFF)"
== make bitset! #{0000000000000000000000000000000000000000000000000000...
>> mold b: charset "^(11FFFF)"
== {make bitset! #^{0000000000000000000000000000000000000000000000000000
```

**Comment by greggirwin** [comment]
Is this the fault of bitset molding, or `mold` itself?
```
>> b: charset "^(11FFFF)"
== make bitset! #{00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000...
>> mold b: charset "^(11FFFF)"
== {make bitset! #^{00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
>> append/dup copy "" "abc" 100
== {abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabca...
>> mold append/dup copy "" "abc" 100
== {^{abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabca
```

**Comment by meijeru** [comment]
Must be the latter one, by all accounts.

**Comment by bitbegin** [comment]
probe b and print mold b are good

**Comment by Oldes** [comment]
`mold` is ok... the console is over truncating... simply truncates the string created by `mold`. Don't know if it is good or not.. for sure the output looks buggy on the first look. Especially when it escapes chars like `{` and `LF`.

**Comment by Oldes** [comment]
If nothing else, there should be `...` in the end of the truncated string. Now it is missing:
```
>> {#{0000000000000000000000000000000000000000000000000000000000000000000000000000}}
== {#^{000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by greggirwin** [comment]
Agreed.

**Comment by qtxie** [comment]
Added `...` at the end of the truncated string.
