### ISSUE TITLE
TANGENT 90 should return infinity instead of overflow error

### ISSUE THREAD

**Issue by Oldes** [red/red#3441]
### Expected behavior
```
>> tangent 90
== 1.#INF
>> tangent -90
== -1.#INF
>> tangent/radians (pi / 2)
== 1.#INF
```
### Actual behavior
```
>> tangent/radians (pi / 2)
*** Math Error: math or number overflow
*** Where: tangent
*** Stack:  
```

**Comment by greggirwin** [comment]
Since the result is really "undefined", why should it return 1.#INF instead of throwing an error? Not disagreeing with the change, just trying to make sure we know why we're making it.

**Comment by Oldes** [comment]
Maybe for the same reason why `1.0 / 0.0` is not throwing the error too.

**Comment by hiiamboris** [comment]
@greggirwin good point, should be 1.#NAN not 1.#INF since the limit of tan depends on where you approach the 90 from.

**Comment by Oldes** [comment]
`1.#NaN` is no useful at all as it would break computations. If you don't like infinities, you may have what `tan` function gives you or some large enough numbers...btw.. this is from LUA:
```
> math.tan(math.pi/2)
1.6331239353195e+016
> math.tan(-math.pi/2)
-1.6331239353195e+016
```

**Comment by Oldes** [comment]
According: https://math.stackexchange.com/a/189626
_where we are motivated by the continuity of the tangent function on (−π/2,π/2), we may let tan(±π/2)=±∞ so that it is extended to a 1-1 well-behaving mapping between [−π/2,π/2] and the extended real line [−∞,∞]_

**Comment by Oldes** [comment]
Which result you prefer in this case:
```
>> arctangent/radians 1.#INF
== 1.5707963267948966
>> (pi / 2) = arctangent/radians 1.#INF
== true
```
versus
```
>> arctangent/radians 1.#NaN
== 1.#NaN
>> (pi / 2) = arctangent/radians 1.#NaN
== false
```
And using the Lua's number:
```
>> (pi / 2) = arctangent/radians 1.6331239353195e+016
== true
```

**Comment by hiiamboris** [comment]
Yes I too find infinity more useful, albeit mathematically incorrect. The main point to have it is to have `x = tangent atan x` where you have series of trigonometric computations. Considering the whole imprecise nature of the floating point it may be useful to extend it to +-infinity like you propose.

But then I don't write trigonometry on a daily basis so I can't be a good judge if it's worth it.

**Comment by greggirwin** [comment]
1.#INF does seem more useful here. Thanks for the thoughts guys. I'll comment on the PR direction for requested changes, then merge if those are made.
