### ISSUE TITLE
User errors receive code 600 instead of 800

### ISSUE THREAD

**Issue by meijeru** [red/red#3444]
### Expected behavior

`e: make error! "abc"` should have `e/code = 800` since `system/catalog/errors/user/code = 800`

### Actual behavior
```
>> probe make error! "abc"
make error! [
    code: 600
    type: 'user
    ....
```
### Steps to reproduce the problem
execute above code
### Red and platform version
```
presumably all, tested on W10
```

**Comment by nedzadarek** [comment]
I can confirm on Win 8.1 64b `Red for Windows version 0.6.3 built 26-Mar-2018/1:14:22+02:00` and `cli` `Red 0.6.3 for Windows built 18-Jun-2018/15:11:17+02:00 commit #6753157`.

**Comment by bitbegin** [comment]
good catch!

**Comment by greggirwin** [comment]
With that merged, it looks fixed to me. Thanks @bitbegin !
