### ISSUE TITLE
to-char with integer > 10FFFFh should give error

### ISSUE THREAD

**Issue by meijeru** [red/red#3450]
### Expected behavior
`to-char <integer>` where the argument is greater than the highest Unicode Code Point should give an error
### Actual behavior
in the same expression the argument is reduced by ANDing with `10FFFFh`
### Steps to reproduce the problem
execute `to-char 110000h`
### Red and platform version
```
all
```

**Comment by greggirwin** [comment]
@endo64, do you want to handle this one, since you were just in that code?

**Comment by endo64** [comment]
@greggirwin Yep, I'll do it next week.

**Comment by greggirwin** [comment]
@meijeru, OK to close this issue with @endo64's fix?

**Comment by meijeru** [comment]
Yes thanks
