### ISSUE TITLE
Case folding should use latest Unicode data

### ISSUE THREAD

**Issue by meijeru** [red/red#3453]
### Expected behavior
the table in `%runtime/case-folding.txt` should correspond to the latest Unicode version (currently 11)
### Actual behavior
the table uses version 7
### Steps to reproduce the problem
N/A
### Red and platform version
all

**Comment by endo64** [comment]
The file name should be `%runtime/case-folding.reds`

**Comment by meijeru** [comment]
Right you are!

**Comment by bitbegin** [comment]
1. use https://github.com/bitbegin/generate-unicode-table to generate two tables in one file, one for to-uppercase, another for to-lowercase.

2. #include this file to case-folding.reds, directly use these two tables without sort.

**Comment by meijeru** [comment]
I continue to think that pulling directly from `unicode.org`  is the most desirable solution, notwithstanding the anomalies that @bitbegin found. These should be reported to Unicode instead of being circumvented. As to reading directly, I dod not need `ftp://` for that, as my Gist shows. But if the current solution passes all tests, let it stand...

**Comment by bitbegin** [comment]
@meijeru  this file CaseFolding.txt cannot give whole information for case folding direction.
For example, `00B5; C; 03BC; # MICRO SIGN` cannot tell us which is uppercase, which is lowercase. But we can get it from UnicodeData.txt.  Maybe we can also parse this file to get two tables if we have time. (I found the UnicodeData.txt from here https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt)
