### ISSUE TITLE
It is possible to define function using malformed specification

### ISSUE THREAD

**Issue by Oldes** [red/red#3454]
### Expected behavior
```
>> f: func[a return: [integer!] c /local b][]
*** Some Error: malformed function specification
```
### Actual behavior
```
>> f: func[a return: [integer!] c /local b][]
== func [a return: [integer!] c /local b][]
>> ? f
Func spec couldn't be parsed, may be malformed.
func [a return: [integer!] c /local b][]
```

**Comment by greggirwin** [comment]
Your Expected example should not fail. It's valid syntax, just not used yet. `Function!` checks for set-words in the spec, but not specifically for `return:`.

**Comment by greggirwin** [comment]
Ah, I skimmed way too fast before. My fault. I see what you mean now.

**Comment by greggirwin** [comment]
I thought this was a `help` issue, but it's not.

**Comment by greggirwin** [comment]
`Validate` in %function.reds does say ";-- temporary mimalist spec checking".

**Comment by greggirwin** [comment]
I think I have this fixed. Just working on tests now.

**Comment by greggirwin** [comment]
The compiler seems to have different checks than the interpreter, and catches things differently. Note that we should sync those up.
