### ISSUE TITLE
Access violation on IMAGE! creation with RTD usage

### ISSUE THREAD

**Issue by 9214** [red/red#3459]
### Expected behavior
Rich-text string is rendered on an image.
### Actual behavior
```
*** Runtime Error 1: access violation
*** at: 0041F95Ah
```
### Steps to reproduce the problem
```red
? (draw 100x100 compose [text 50x50 (rtd-layout [b "test" /b])])
```
### Red and platform version
W10, though, I also experienced this crash on Wine (which is expected I guess).
```
Red 0.6.3 for Windows built 5-Jul-2018/20:38:08+05:00 commit #963ec55
```

**Comment by qtxie** [comment]
It should not crash, though it's not supported yet.

**Comment by qtxie** [comment]
It will throw an error now.
