### ISSUE TITLE
How do I trans Redlang's formers from English characters to [Chinese characters/Mandarin]?我该如何转换红语言的形态为中文字符或汉语?

### ISSUE THREAD

**Issue by qwas982** [red/red#3484]
### Red and platform version
```
Run below code in Red Console and replace these 3 lines enclosed in ``` with the result:
  any [attempt[about/debug] about]
(add OS version if not in above command result)
```
How do I trans Redlang's formers from English characters to [Chinese characters/Mandarin]?
我该如何转换红语言的形态为中文字符或汉语?

Hello everyone, I found that the Redlang is much more advanced than other existing languages and supports Unicode characters. That is, the Redlang  can support source code using Chinese characters or Mandarin characters , so I want to use all the sources of the Redlang . The code is translated into Chinese characters or Mandarin. Which point should I start with? What kind of tools do I need to use to do this? I found that the source code of the Redlang  is not a lot, so I came up with such an idea and hope that everyone will support me. .
大家好,我发现红语言相对于其他现存的语言来说要先进很多,并且支持Unicode字符,也就是说,红语言可以支持使用中文字符或汉字编写源代码,于是我想将红语言的所有源代码翻译为中文字符或汉语,我该从哪一点开始呢?我需要使用什么样的工具做到这样?我发现红语言的源代码并不是很多,于是就萌生了这样的想法,希望大家支持我.

**Comment by greggirwin** [comment]
@qwas982, welcome to Red! Do you mean you want to translate the *existing* source code, for all of Red, to Chinese? We don't have the resources to support that, but we do have https://gitter.im/red/red/Chinese?source=orgpage, where you could talk with other users about what would be best to translate, and get input from some of our Chinese team perhaps. It's a busy time for us, but we're happy for people to find ways to support and use Red.

**Comment by qwas982** [comment]
@greggirwin  thank you for your help,yes,I wanna translate all of Redlang's source code,Thank you for your guidance,I well try.

**Comment by qtxie** [comment]
@qwas982 I'll close this ticket. If you have more questions, welcome to join our Chiniese gitter room.
