### ISSUE TITLE
FEAT: Make `help-string` available without console

### ISSUE THREAD

**Issue by greggirwin** [red/red#3487]
### Expected behavior

You should be able to use `help-string`, if not `help`, in non-console apps. If there is no console object, output should not wrap.

### Actual behavior

`help-string` crashes, because it depends on the console object existing to determine when to wrap output. 

### Steps to reproduce the problem

e.g. `print [help-string "-thru"]`

### Red and platform version
```
-----------RED & PLATFORM VERSION-----------
Should be the same on all.

RED: [ branch: "master" tag: #v0.6.0 ahead: 3561 date: 24-Jul-2018/23:29:28 commit: #f77e751ad310318172fd5b714c6f41c4b7004e9b ]
PLATFORM: [ name: "Windows 10" OS: 'Windows arch: 'x86-64 version: 10.0.0 build: 17134 ]
--------------------------------------------
```

**Comment by greggirwin** [comment]
Or maybe it should format just as the console would, truncating if needed, at a configurable width in characters.

**Comment by greggirwin** [comment]
I have this change made, but won't push a PR until I have tests, if we have a solution for that.

**Comment by PeterWAWood** [comment]
@greggirwin It should work if you include %help.reds in a #system block and then define a routine! to access it. 

I hope that it won't require the `-r` option to compile.

**Comment by greggirwin** [comment]
Sorry, should have been %help.red, not %.reds. Just wasn't sure if #include-ing  was how you wanted things done. Thanks.
