### ISSUE TITLE
reduce and compose evaluate lit-words twice

### ISSUE THREAD

**Issue by meijeru** [red/red#3499]
### Expected behavior
>> a: 1
>> reduce a     ;== 1
>> reduce 'a    ;== a
### Actual behavior
>> a: 1
>> reduce a     ;== 1
>> reduce 'a    ;== 1

compose behaves the same
### Steps to reproduce the problem
execute above code
### Red and platform version
all

**Comment by greggirwin** [comment]
@meijeru, it's the console evaluating it in that example.
```
>> a: 1
== 1
>> first reduce ['a]	
== a
>> quote reduce 'a
== a
```
This is a change from how Rebol works, but I believe is by design.

**Comment by meijeru** [comment]
Fair enough. Not worth pursuing further, I close.
