### ISSUE TITLE
run-time lexer does not check Unicode numbers and crashes if > 10FFFFh

### ISSUE THREAD

**Issue by meijeru** [red/red#3521]
### Expected behavior
escaped characters using Unicode hex numbers should be checked by the run-time lexer for validity (<= 10FFFFh) like the  compile-time lexer does
### Actual behavior
`#"^(110000)"` and higher crash the console
### Steps to reproduce the problem
type `#"^(110000)"` or higher in console
### Red and platform version
```
all
```

**Comment by endo64** [comment]
It crashes only on GUI console, not on CLI console (tested on Win10 x64)

**Comment by meijeru** [comment]
Strange, because it uses `%lexer.red` -- which omits the test -- and I suppose this is also used by CLI.
