### ISSUE TITLE
return spec of modify action is incorrrect

### ISSUE THREAD

**Issue by meijeru** [red/red#3522]
### Expected behavior
result of `modify` should have type `map!` or `file!` as per the action spec
### Actual behavior
when `modify` is used to set the `owned` property of a series within an object the result is the series
### Steps to reproduce the problem
```
>> modify o/b 'owned reduce [o 'b]
== [1 2 3]
>> reflect o/b 'owned
== make object! [
    b: [1 2 3]
]
```
### Red and platform version
```
all
```

**Comment by meijeru** [comment]
I cannot imagine which application of `modify` would result in either a `map!` or a `file!` value.

**Comment by dockimbel** [comment]
The returned type constraint has been removed, as `modify` could in fact return any type.
