### ISSUE TITLE
Object's owner and owned properties can be set, but not reflected

### ISSUE THREAD

**Issue by meijeru** [red/red#3523]
with series values, the `owned` property can be set by `modify` and interrogated by `reflect`;
with object values, `owner` and `owned` properties can be set by modify, but `reflect` with these properties is not implemented
### Red and platform version
all

**Comment by dockimbel** [comment]
Objects can be owners but cannot be owned currently.

**Comment by dockimbel** [comment]
`owned` flag on an object can now be checked with `reflect`.
