### ISSUE TITLE
Red Header Inconsistency

### ISSUE THREAD

**Issue by audinue** [red/red#3529]
I believe Red header should be case insensitive.

```
Red [] ; Ok
Print "Love Red"
```

```
RED [] ; *** Error: not a Red program!
PRINT "Hello world!"
```

**Comment by 9214** [comment]
This is a design decision.

> The reason why the Red[/System] header was made case-sensitive was to lower the risk of collision when running a Red script which is appended to a non-Red textual content (HTML, email body, etc...). Rebol has less chances of accidental collision, as it's a unique word (unlike "red").

Do you have any solid arguments for a proposed change?
