### ISSUE TITLE
runtime error 101 on TRIM/WITH called with BINARY! as a second argument

### ISSUE THREAD

**Issue by 9214** [red/red#3534]
### Expected behavior
`trim/with <binary!> <binary!>` removes specified bytes, `trim/with <binary!> <string!>` either treats characters in `string!` as bytes (and vice versa for `trim/with <string!> <binary!>`), or raises an error.

### Actual behavior
```
*** Runtime Error 101: no value matched in SWITCH
*** at: 00431869h
```

[Culprit](https://github.com/red/red/blob/master/runtime/datatypes/string.reds#L2342).

### Steps to reproduce the problem
```red
trim/with {} #{}
```

### Red and platform version
Latest.

**Comment by endo64** [comment]
It looks like adding `TYPE_BINARY` just before `TYPE_STRING` as you pointed solves all the issues:

```
>> trim/with "aA" #{6141}
== ""
>> trim/with #{6141} "aA"
== #{}
>> trim/with #{6141} #"a"
== #{41}
>> trim/with #{6141} #{41}
== #{61}
```

**Comment by 9214** [comment]
Silence! :^/
