### ISSUE TITLE
New GUI Console not redrawing/scrolling properly

### ISSUE THREAD

**Issue by gltewalt** [red/red#3538]
### Expected behavior
To scroll properly so that the next input line is visible and available.
### Actual behavior
https://imgur.com/a/6UGEbhz
### Steps to reproduce the problem
Type `help datatype!` in GUI Console.
### Red and platform version
```
RED: [ branch: "master" tag: #v0.6.3 ahead: 857 date: 16-Sep-2018/5:12:03 commit: #09de884db66698de77464e42ffdb91445991fe2d ]
PLATFORM: [ name: "Windows 7 Service Pack 1" OS: 'Windows arch: 'x86-64 version: 6.1.1 build: 7601 ]
```

**Comment by 9214** [comment]
W10, output expressions get doubled and partially malformed if I directly copy-paste from GUI console session:
```red
>> [
[    a
[    b
[    c
[    ]
== [
    a 
    b 
    c ; <-- WTF? Note the missing closing bracket.
== [
    a 
    b 
    c
]
>> object []
== make object! []
>> object [x: 1 y: 2]
== make object! [
    x: 1
    y: 2
== m ;<-- WTF? Note the missing closing bracket above.
```

**Comment by qtxie** [comment]
@gltewalt @9214 Does the issue still exist in the latest red version?

**Comment by 9214** [comment]
@qtxie can't reproduce with latest automated build, I guess it's fixed. 👍

**Comment by gltewalt** [comment]
Issue is resolved in the latest automated build.
