### ISSUE TITLE
Simple hello world program on docs fails to run

### ISSUE THREAD

**Issue by liminalitythree** [red/red#3557]
### Expected behavior
The hello world program runs

### Actual behavior
it outputs the error
```
*** Script Error: view has no value
*** Where: ???
```

### Steps to reproduce the problem
Write the following into a text file
```
Red [Needs: 'View]

view [text "Hello World!"]
```

run
```
red -c hello.red
./hello
```

### Red and platform version
```
Run below code in Red Console and replace these 3 lines enclosed in ``` with the result:
  any [attempt[about/debug] about]
(add OS version if not in above command result)
```
```
>> any [attempt[about/debug] about]
Red for Linux version 0.6.3 built 10-Oct-2018/14:00:16-06:00
*** Script Error: block did not return a value
*** Where: any
*** Stack:  
```
I'm using solus linux

**Comment by dockimbel** [comment]
The stable and dev (master branch) versions of Red don't include a GUI backend for Linux. There is a WIP backend for GTK on [this branch](https://github.com/red/red/tree/GTK) which implements roughly 50% of the features.

**Comment by liminalitythree** [comment]
oh. It would be nice if the getting started page mentioned this somewhere.

**Comment by qtxie** [comment]
@liminalitythree It works on macOS too.

**Comment by greggirwin** [comment]
@liminalitythree working on Windows and Mac means it is cross platform. :^)

**Comment by greggirwin** [comment]
And while Android is an experimental branch, it also works there.

**Comment by liminalitythree** [comment]
No, that means it works on windows and mac. Even though technically working on two platforms may mean cross platform when people say cross platform they mean windows, linux, and osx. If I said I made a cross platform library but it only actually runs on iOS and windows for ARM you would say I'm using semantics to make my library seem better than it is.

**Comment by greggirwin** [comment]
So if we run on Windows, MacOS, Android, iOS, and any number of other GUI capable systems, we still can't say we're cross platform if we don't support Linux GUIs? What specific Linux GUIs meet that requirement? Not everyone will agree that GTK is enough.

**Comment by liminalitythree** [comment]
being able to use the gui library on linux like you would any of those other platforms. the implemention details don't matter.

**Comment by greggirwin** [comment]
The implementation details *do* matter, as not all Linux's are created equal. It would just lead to another semantic argument from someone.

**Comment by greggirwin** [comment]
Let us consult the oracle: https://en.wikipedia.org/wiki/Cross-platform_software

**Comment by liminalitythree** [comment]
being able to run on an average linux installation like all cross platform programs do. you're the one arguing tiny details.

**Comment by greggirwin** [comment]
>  like all cross platform programs do

No, you're defining something to meet your needs.

Per Wikipedia: Cross-platform programs may run on as many as all existing platforms, or on as few as two platforms.

**Comment by greggirwin** [comment]
And, as noted above, it **is** supported on Linux, in a branch, in progress, and incomplete. :^)

**Comment by PeterWAWood** [comment]
This issue should be closed. The GTK+ backend is not scheduled to be worked on by the Red Team until after the Alpha 0.9.0 release (at the earliest). That the current GTK+ branch is roughly 50% complete is a great credit to those members of the Red community have taken it that far (with much appreciated guidance from @qtxie).

**Comment by liminalitythree** [comment]
Yeah, technically they can. But when you're advertising a cross platform desktop GUI library everyone expects it to work on linux, windows, and osx. Those are the three major desktop platforms. Many gui libraries also support lesser-known platforms but supporting all three of those is basically a requirement for being called a cross platform gui library. Can you name any "cross-platform" gui library that's moderately popular, in any language that doesn't support one of those three? (other than red of course)

**Comment by PeterWAWood** [comment]
Worthwhile contributions from the community to the GTK+ backend are always welcome.

**Comment by liminalitythree** [comment]
and its fine to be in development, I'm just meaning that its a bit misleading to say it's cross platform right now when it isn't yet

**Comment by greggirwin** [comment]
I agree with Peter, and will close this. 

> supporting all three of those is basically a requirement for being called a cross platform gui library

My point is, where is that written? "Everybody knows..." is not justification. Aaaaannnd, we *do* run on Linux, don't we? In a branch....in alpha software.

**Comment by liminalitythree** [comment]
Words don't have to be written down in a dictionary to have meaning. Their meaning is how they're used. If you can't find any library that's called cross platform but doesn't support one of those, that means it's not used that way.

**Comment by liminalitythree** [comment]
Oh, wouldn't it also be better to give an error when I try to import the `View` library that doesn't exist, rather than when I try to use the imported library? That might make it a bit more clear

**Comment by 9214** [comment]
@liminalitythree what would be better is for you to stop imposing ad-hoc concepts and breed polemic on a bug tracker. This doesn't solve any problems, raises tension and puts you in a bad light.

Accusing developers of being dishonest for calling cross-platform alpha software, well, _cross-platform_, and calling README file an "advertisement" is quite impolite, don't you think?

@greggirwin I suggest to put info about Red being alpha (50% finished GTK backend and respective branch of development, missing functionality, link to roadmap &c) somewhere, explicitly and with due emphasis, to nip potential cases like that in the bud.

**Comment by greggirwin** [comment]
Sounds good @9214. Where is the best "somewhere"?

**Comment by 9214** [comment]
@greggirwin I believe at the bottom of [this](https://github.com/red/red#red-programming-language) section.

**Comment by liminalitythree** [comment]
I was talking about your website. I think that would be fair to call an advertisement for the language.
