### ISSUE TITLE
DO ANY-PATH! misbehaves

### ISSUE THREAD

**Issue by 9214** [red/red#3561]
### Description
`do` applied to some of `any-path!` values yields unexpected results.

### Steps to reproduce the problem
* Here I expected `c`:
```red
>> a: [b c]
== [b c]
>> a/b
== c
>> do 'a/b
== false
```
* And here too:
```red
>> do quote a/b
== a/b
```
* Here `lit-path!` should have decayed to `path!`:
```red
>> do quote 'a/b
== 'a/b
```
* And this one seems to be correct:
```red
>> do quote :a/b
== c
```
### Red version and OS
```
Red 0.6.3 for Windows built 6-Oct-2018/7:28:28+05:00 commit #dafc828
```

**Comment by hiiamboris** [comment]
It's even messier in compiler:
```
Red []
a: reduce ['b does [1 + 2] 'x 'y]
print do 'a/b
print do quote a/b
print do 'a/x
print do quote a/x
```
Compiled:
```
3  
3  
3    ;) what??
a/x
```

Or:
```
Red []
a: reduce ['b does [1 + 2] 'x 'y]
print do 'a/x
print do quote a/x
```
Compiler:
```
*** Script Error: b has no value
*** Where: print
*** Stack:
```
Red 0.6.4 for Windows built 20-Nov-2019/21:01:43+03:00 commit #aa7c46e

**Comment by dockimbel** [comment]
There were some back and forth on supporting path evaluation with `do`. One of the main issue in allowing `do <path>` if `<path>` evaluates to a function, is that it makes it possible to create variadic expressions
