### ISSUE TITLE
Can't run Red from other programs

### ISSUE THREAD

**Issue by maximvl** [red/red#3562]
**Describe the bug**
When I try to execute Red from another program it fails with ```PROGRAM ERROR: Invalid encapsulated data.```

**To Reproduce**
1. Install Elixir
2. Clone https://gitlab.com/maxvel/reddish.git
3. In the repo run `iex -S mix`
4. In the REPL type
```
p = Reddish.start
Reddish.send_input(p, "5 + 5\n")
flush()
```

5. See message `{#PID<0.170.0>, :data, :out, "PROGRAM ERROR: Invalid encapsulated data.\n"}`
6. After this I can't even run Red as regular:
```
> red
PROGRAM ERROR: Invalid encapsulated data.
```
7. And in a new shell instance:
```
> red
** Script Error: Invalid compressed data - problem: -3
** Near: script: decapsulate 
if none? script
```

**Expected behavior**
`flush()` prints message with "10" returned by Red, Red is runnable.

**Screenshots**
![screenshot](https://i.imgur.com/LpGHVrT.png)

**Platform version(please complete the following information):**
```
Red 0.6.3 for Linux built 11-Oct-2018/3:00:23+02:00 commit #b1f01cc
```

**Comment by 9214** [comment]
#543, #1547

**Comment by maximvl** [comment]
I also tried to create a wrapper like this:
```
#!/bin/bash
red $@
```
With it I don't get the error, but got no output either. From what I tried this works with `cat` and `ipython`, but doesn't work with `python`.

**Comment by dockimbel** [comment]
If you need only the Red interpreter, compile the CLI console and use that binary instead of `red.exe`.

**Comment by x8x** [comment]
I work around this issue by wrapping the Red call into `sh` like this:
```sh
sh -c "red -r code.red"
```
I suspect a path issue in certain environment ~where the console called from red binary can't find the crush decompressor~ maybe not as in the example the toolchain is called not the console.., but haven't investigated further.

**Comment by beenotung** [comment]
I found similar bug on windows.
I saved red as red.exe, and add the containing folder into PATH.
I found it will raise below error when launch form cmd:
```
PROGRAM ERROR: Invalid encapsulated data.
```

## below case will trigger error
1. if the current directory is not containing red, and using `red` or `red.exe`
2. if the current directory is not containing red, and using `..\local\bin\red`

## below case will not trigger error
1. if the current directory is containing red, and using `red` or `red.exe`
2. if the current directory is not containing red, and using `..\local\bin\red.exe`

**Comment by beenotung** [comment]
I tried the case test with rebol-core and rebol-view, all the two cases trigger error for red do not trigger error for rebol.

**Comment by greggirwin** [comment]
Thanks for the note @beenotung.

**Comment by pierstitus** [comment]
I get the same error when running from ipython3:

```
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import subprocess                                                                                                      

In [2]: subprocess.run('./red-064')                                                                                            
** Script Error: Invalid compressed data - problem: -3
** Near: script: decapsulate 
if none? script
Out[2]: CompletedProcess(args='./red-064', returncode=0)
````

Running from python3 gives a slightly different error:
```
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.run('./red-064')
** Script Error: Not enough memory
** Near: script: decapsulate 
if none? script
CompletedProcess(args='./red-064', returncode=0)
```

It doesn't matter what arguments are given, `subprocess.run(['./red-064','hello.red'])` or `subprocess.run(['./red-064','-V'])` give the same error. Compiled red programs do run normally.

**Comment by endo64** [comment]
I just realized that, on Windows, if your `red.exe` is located in your `PATH`, you get `PROGRAM ERROR: Invalid encapsulated data.` if you execute `red.exe` in command prompt (`cmd.exe`), but it works if you use Powershell.

And also the output speed is much faster on Powershell.

**Comment by dockimbel** [comment]
The Red binary is now separated in several binaries. The CLI console binary can be called from other languages if needed.
