### ISSUE TITLE
MODIFY is defined on files and urls, but does not seem to do anything

### ISSUE THREAD

**Issue by meijeru** [red/red#3570]
`file!` and `url!`  values inherit `modify` from `series!`. However, for `series!` values `modify` is only defined with the `owned` property -- this is presumably in connection with `on-change` for objects. There is no indication what `modify` would do for files, urls or ports for that matter.

**Comment by dockimbel** [comment]
The behavior of `modify` on those types will be defined once we implement the full I/O sub-system.
