### ISSUE TITLE
clean-path takes a url! and produces a file!

### ISSUE THREAD

**Issue by meijeru** [red/red#3571]
The argument to `clean-path` may be a `url!` value, but the result is always a `file!` value. It would seem that the result in this case should more usefully be a `url!` value, since by RFC3986 the `.` and `..` elements are equally applicable in such a value. What the result should be when the argument is a `string!` value is open for discussion.

**Comment by dockimbel** [comment]
`clean-path` in its current implementation is not handling URLs properly anyway:
```
>> clean-path http://toto/../titi
== %/titi
```

Even Rebol3 does not process them entirely well:
```
>> clean-path http://toto/../titi
== http:///titi
```

**Comment by endo64** [comment]
It can at least return (copy of) the URL if the input is `url!` just like in R2 & R3:
```
>> clean-path https://google.com
== https://google.com
```

**Comment by hiiamboris** [comment]
Why `status.contribution`, I wonder?
