### ISSUE TITLE
Wrong error message for as object!

### ISSUE THREAD

**Issue by meijeru** [red/red#3572]
**Describe the bug**
I naively tried `as object! <error>` which is not allowed, and found the error message misleading. 

**To Reproduce**
Enter `as object! try [1 / 0]` in the console.

**Expected behavior**
`*** Script Error: as does not allow object! for its type argument`

**Screenshots**
`*** Script Error: as does not allow refinement! for its spec argument`

I don't know where the `refinement!` comes from; also `spec` should really be `type`

**Comment by dockimbel** [comment]
Your expectation is wrong, `object!` argument is of type `datatype!`, so allowed as first argument to `as`.

The latest commit returns a correct error message:
```
>> as object! try [1 / 0]
*** Script Error: as does not allow error! for its spec argument
*** Where: as
*** Stack:
```
