### ISSUE TITLE
sort/skip does not work on binary! values

### ISSUE THREAD

**Issue by meijeru** [red/red#3583]
**Describe the bug**
`sort` is defined for all `series!` values except `image!`. Without `/skip` it works on `binary!` values. However, with `/skip` it does not, and this is inconvenient.
**To Reproduce**
```
>> sort #{04030201}
== #{01020304}
>> sort/skip #{00000004000000030000000200000001} 4
== #{00000004000000030000000200000001}
```
**Expected behavior**
```
>> sort/skip #{00000004000000030000000200000001} 4
== #{00000001000000020000000300000004}
```
**Platform version(please complete the following information):**
```
all
```

**Comment by meijeru** [comment]
It *does*  work with explicit `compare` function and `/all`
```
>> sort/skip/all/compare #{00000004000000030000000200000001} 4 func [a b][a < b]
== #{00000001000000020000000300000004}
```
but why it does not work straight away I don't know.

**Comment by meijeru** [comment]
If that is a feature rather than a bug, this issue can be closed, especially since a workaround exists, as indicated.

**Comment by endo64** [comment]
This explains the feature:

```
>> sort/skip/compare [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16] 4 func [a b] [probe reduce [a b] 0]
[5 1]
[9 5]
[13 9]
== [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16]

>> sort/skip/compare/all [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16] 4 func [a b] [probe reduce [a b] 0]
[[5 6 7 8] [1 2 3 4]]
[[9 10 11 12] [5 6 7 8]]
[[13 14 15 16] [9 10 11 12]]
== [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16]
```

**Comment by meijeru** [comment]
Very instructive! But, since `f [a b][a < b]` is - as it were - the default comparison function, my workaround should work with `/all` and *without*  `/compare` -- only it doesn't!

**Comment by hiiamboris** [comment]
Yep, I've also discovered the default sorting function is kinda lazy - it only takes the 1st byte into account:
```
```

**Comment by qtxie** [comment]
Another way to choose which element to be compared:
```
>> sort/skip/compare [0 0 0 4 0 0 0 3 0 0 0 2 0 0 0 1] 4 4
== [0 0 0 1 0 0 0 2 0 0 0 3 0 0 0 4]
>> sort/skip/compare [0 0 4 0 0 0 3 0 0 0 2 0 0 0 1 0] 4 3
== [0 0 1 0 0 0 2 0 0 0 3 0 0 0 4 0]
```

**Comment by 9214** [comment]
@qtxie except that it doesn't work with `binary!`:
```red
>> sort/skip/compare #{00000004000000030000000200000001} 4 4
== #{00000004000000030000000200000001}
```

**Comment by meijeru** [comment]
Sort on binary! is inherited from string! and on string! it does not work either! So /skip in combination with /all needs serious revision.

**Comment by qtxie** [comment]
@9214 Oops... :sweat: 
@meijeru Yes. When using `/all`, the default comparison function should compare all the fields rather than the first one. The implementation is missing in the codebase.
