### ISSUE TITLE
compile with -r then defenered by Windows Defender

### ISSUE THREAD

**Issue by yibaifei** [red/red#3584]
**Describe the bug**
the binary defenered by windows defener

**To Reproduce**
i used win 10 home edition
```
C:\Users\xxx\Downloads>cat hello.red
Red [Needs: 'View]

view [text "Hello World!"]

C:\Users\xxx\Downloads>red-063.exe -r hello.red

C:\Users\xxx\Downloads>hello.exe     
系统无法执行指定的程序。 (the system can not execute the program ...)
```
then notice remove by system

**Expected behavior**
it can be running correctly.

**Comment by 9214** [comment]
@yibaifei please submit both Red toolchain and `hello.exe` binaries as false positives [here](https://www.microsoft.com/en-us/wdsi/filesubmission).
