### ISSUE TITLE
Alert source code is flawed: OK button does not do anything.

### ISSUE THREAD

**Issue by meijeru** [red/red#3586]
**Describe the bug**
A call to `alert` brings up a modal window, but the OK button has no action associated with it. The action should preferably be `unview`.

**To Reproduce**
Execute `alert "msg"`.

**Expected behavior**
Clicking the OK button should close the modal window.

**Platform version(please complete the following information):**
```
All
```

**Comment by meijeru** [comment]
Also, a `block!` value is permitted as message. This value is then inserted after `text` in the VID code. THe documentation does not say what the result of this would be.

**Comment by greggirwin** [comment]
PR submitted. Also added key support for easy dialog dismissal.
