### ISSUE TITLE
Unexpected window minimization

### ISSUE THREAD

**Issue by dsunanda** [red/red#3589]
**Describe the bug**
Console window (and/or) VID window expectedly minimized if moved rapidly

**To Reproduce**
 1. View [box 200x200 red]   ;; any GUI structure seems to work

 2. Move the VID window rapidly back and forth - the console window will soon minimize

 3. Move the console window rapidly back and forth - the VID window will soon minimize
  
**Expected behavior**
Windows don't minimize

**Platform version:**
Red 0.6.3 for Windows built 13-Nov-2018/15:49:48 commit #7404492

**Comment by meijeru** [comment]
Cannot reproduce; with my set-up (W10) it is the other open windows that minimize under this treatment. Perhaps a Windows question rather than a Red one?

**Comment by greggirwin** [comment]
I also can't dupe on Win10.

**Comment by greggirwin** [comment]
Determined by Sunanda and ToomasV not to be a Red issue.

**Comment by DideC** [comment]
That seems to be "Aero shake" behaviour.

https://winaero.com/blog/disable-aero-shake-in-windows-10-windows-8-and-windows-7/
