### ISSUE TITLE
Compiler chokes on redefined `equal?` function

### ISSUE THREAD

**Issue by meijeru** [red/red#360]
I was testing if operators and natives/actions could be redefined. This is true for almost all names, whether by using a set-word or by using the `set` construction. The only operator name that the compiler has difficulty with, is `equal?`

```
equal?: 1
-= Red Compiler =-
Compiling red/tests/mytest.red ...
*** Red Compiler Internal Error: Script Error : Invalid path value: equal?
*** Where: rejoin
*** Near:  [forall ops [
comp-expression/no-infix
emit make-func-prefix ops/1
insert-lf -1
emit-close-frame
unless tail? next ops [pc: next pc]
]
return true
]
```

**Comment by dockimbel** [comment]
I will close this ticket as the compiler is not meant to support the redefinition of such words for now. Such feature may or may not be added on the road to 1.0, but as it is speculative, there is no need to keep this ticket open.
