### ISSUE TITLE
Access violation on BLOCK! probing

### ISSUE THREAD

**Issue by 9214** [red/red#3603]
**Describe the bug**

Seemingly harmless one-liner leads to an unexpected crash.

**To reproduce**

```red
probe back change block: [] do/next block 'rest
```
```
*** Runtime Error 1: access violation
*** at: 0042FCDBh
```

On further inspection, `mold` revealed that block contains a null byte:
```red
>> mold back change block: [] do/next block 'rest
== "[^@]"
```

**Expected behavior**

`[unset]`

**Platform version (please complete the following information):**
```
Red 0.6.4 for Windows built 22-Nov-2018/0:36:02+05:00 commit #5f63e4a
```

**Comment by qtxie** [comment]
Seems only crashes when the block is empty.
```
>> probe back change block: [1] do/next block 'rest
[1]
```

**Comment by endo64** [comment]
@9214 `mold` shows only one null byte but there is more actually;

```
>> change block: [] do/next block 'rest
== []
>> block
== [´I¸ý]
>> mold block
== "[Ä^LE^LÉÂ^H]"
```
