### ISSUE TITLE
integer overflow in pair values is not handled correctly

### ISSUE THREAD

**Issue by meijeru** [red/red#3613]
**Describe the bug**
A `pair!` literal with a component larger than (2 ** 31 - 1) is not giving an error. Instead, the component is changed to - (2 ** 31), regardless of its value.

**To Reproduce**
```
>> p: 0x2147483648  ;; 1 larger than allowed - an overflow error should be reported
== 0x-2147483648
>> p: 0x2147483649  ;; 2 larger
== 0x-2147483648
>> p: 0x2147483650  ;; 3 larger
== 0x-2147483648
```
**Platform version(please complete the following information):**
```
presumably all
```

**Comment by meijeru** [comment]
I hit on this when playing around with `0x...` lexemes that may be used for `hex!` literals. There is a potential ambiguity between those literals and the ones for `pair!` values.

**Comment by endo64** [comment]
Behavior of converting to float of overflowing integers is same as R2.

**Comment by 9214** [comment]
This was already reported https://github.com/red/red/issues/3228

**Comment by meijeru** [comment]
Sorry! It is increasingly difficult to check if an issue has already been reported, since there are so many... I came to this from an angle which in itself has some interest (literals for hex!) but will close it anyhow.

**Comment by greggirwin** [comment]
It will only get worse, until there's a better system than github tickets, because some things get closed, and reported anew.
