### ISSUE TITLE
access violation on probing of EVENT/PICKED from incorrectly specified MENU facet

### ISSUE THREAD

**Issue by 9214** [red/red#3619]
**Describe the bug**

Title.

**To reproduce**
Examine one of the following snippets:
```red
view [
    panel
        with [menu: ["a"]]
        on-menu [probe event/picked]
]
```
```red
view/options [
    on-menu [probe event/picked]
][
    menu: ["a"]
]
```

In both cases, `menu` block is incorrectly specified - `string!` should be followed by menu element ID in the form of `word!` value. In both cases, after clicking on `a` menu entry, I experience a crash:
```
*** Runtime Error 1: access violation
*** at: 0042F984h
```

**Expected behavior**

I would expect `event/picked` to be set either to `none` or to `unset` value. Perhaps View engine should do a preliminary check of menu block format.

**Platform version (please complete the following information):**
```
Red 0.6.4 for Windows built 28-Nov-2018/6:34:42+05:00 commit #d463f89
```

**Comment by dockimbel** [comment]
@qtxie Please implement for macOS the same fix as I did for Windows backend.
