### ISSUE TITLE
[R/S] Add the result of integer div and the result of EITHER, will get incorrect value

### ISSUE THREAD

**Issue by bitbegin** [red/red#3620]
**Describe the bug**

```
Red/System []

size: 1 / 1 + either 0 <> 0 [1][0]
print-line size

```

the `size` should be `1`, but i get `1703785`

**To Reproduce**

compile and run the above sample code

**Expected behavior**

the `size` should be `1`

**Platform version(please complete the following information):**
```
Red 0.6.4 for Windows built 28-Nov-2018/9:34:42+08:00 commit #d463f89
```

**Comment by bitbegin** [comment]
```
Red/System []

size: 1 * 1 + either 0 <> 0 [1][0]
print-line size
```

this sample also failed.

**Comment by bitbegin** [comment]
other one:

```
Red/System []

size: 1 * 1 <> either 1 <> 0 [1][0]
print-line size

```

**Comment by qtxie** [comment]
Inline `either` in math expression is not supported in R/S.

**Comment by bitbegin** [comment]
but,

```
Red/System []

size: 1 + either 0 <> 0 [1][0]
print-line size

size: 1 <> either 0 <> 0 [1][0]
print-line size

```
work right.

**Comment by meijeru** [comment]
In the Red/System specification, section 5.1, there is an example:
`b: 1 + (2 * a - either zero? a [0][a + 100])`
Is this not supported?!?

**Comment by qtxie** [comment]
Ok. I have been known this issue since 3 years ago. That's why I thought it's unsupported. 😅

**Comment by meijeru** [comment]
It may be that it _should_ be supported, but that there is sometimes a problem in code generation. Then it is a genuine issue. _Or_, the example is not appropriate, and it is not supported, then the issue can be dismissed. Only @dockimbel can tell, I think. But he seems to be very busy...

**Comment by qtxie** [comment]
FYI: #1096

**Comment by dockimbel** [comment]
The compiler will now throw an error when `either` is used nested in such expressions. Using `either` after an assignment is still supported though. The main reason for not supporting it is that it would require deep changes in the compiler and its backend, which is not worth doing now. The new toolchain though should support it, or an alternative ternary operator.
