### ISSUE TITLE
[DOC] Update View/VID documentation with regard to units used

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3626]
**Describe the bug**

[Since some time](https://github.com/red/red/commit/b3da143e621e8b254c8e9e8a7a9b4652dfc30d04) the View engine became DPI-aware. Every pair! is expressed in some logical screen units, not pixels. Documentation should clearly state that in a separate paragraph and use word "screen unit" instead of "pixel" everywhere.

**Comment by 9214** [comment]
Perhaps you should re-post it on [respective](https://github.com/red/docs/issues) issue tracker?

**Comment by hiiamboris** [comment]
@9214 didn't know about that, sorry! ☺

**Comment by hiiamboris** [comment]
https://github.com/red/docs/issues/95
