### ISSUE TITLE
stats function returns negative memory usage

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#3629]
**Describe the bug**
When large amounts of memory has been "reserved" with the make function, the stats function returns negative values.
```text
>> s: make string! 1'000'000'000
== ""
>> stats
== 1001475992
>> s: make string! 1'000'000'000
== ""
>> stats
== 2001476868
>> s: make string! 1'000'000'000
== ""
>> stats
== -1293489468
```
**To Reproduce**
See above
**Expected behavior**
stats returns only positive values for memory usage

**Platform version(please complete the following information):**
```
Red 0.6.4 for macOS built 3-Dec-2018/21:24:35+08:00
```

**Comment by hiiamboris** [comment]
How can it possibly return a positive result while we don't have an unsigned integer type in R/S to hold this result?

**Comment by greggirwin** [comment]
On Win10 I get insufficient memory errors before it will return an invalid result. this may just be a bug in `memory-info` in %debug-tools.reds.

**Comment by qtxie** [comment]
I think @hiiamboris is right.

**Comment by dockimbel** [comment]
@hiiamboris `pointer! [byte!]` type in R/S effectively acts as a unsigned 32-bit integer, though not all math operations are permitted on it.

**Comment by bitbegin** [comment]
if we print a hex format will be ok?

**Comment by bitbegin** [comment]
this situation has to wait uint! type be implemented

**Comment by greggirwin** [comment]
I just hit this using my `profile` function when testing the JSON codec over many runs.

**Comment by dockimbel** [comment]
Output is now switching to float if overflowing.
