### ISSUE TITLE
attempt to SAVE a block with LOADed image inside of it results in access violation

### ISSUE THREAD

**Issue by 9214** [red/red#3636]
**Describe the bug**
Title.

**To Reproduce**
Create a Red script with content as specified below, and put any image file in the same directory:
```red
Red []

save %image.red reduce [load %<your-image-file>]
``` 

Then try to execute that script.

```
*** Runtime Error 1: access violation
*** at: 742BA8C9h
```

**Expected behavior**

An `image.red` file is created with `image!` value as its content.

**Platform version (please complete the following information):**
```
Red 0.6.4 for Windows built 28-Nov-2018/6:34:42+05:00 commit #d463f89
```

**Comment by bitbegin** [comment]
how you execute the image.red?

**Comment by endo64** [comment]
@bitbegin I think @9214 means executing the file above not the `image.red`

@9214 It worked for me on W10 x64: `Red 0.6.4 for Windows built 5-Dec-2018/12:31:35+03:00 commit #90c8e83`

**Comment by 9214** [comment]
It's strange that others can't reproduce it. Still the case for me with the latest build.

**Comment by bitbegin** [comment]
you can put call-stack here, using `-r -d` argument

**Comment by 9214** [comment]
Interesting, I just tried to reproduce it with my own Github profile pic taken from this chat, no crash.

**Comment by endo64** [comment]
@9214 Can you share the image file you try?

**Comment by 9214** [comment]
Sure, I got 3 of them.
[buggy.zip](https://github.com/red/red/files/2658859/buggy.zip)

**Comment by hiiamboris** [comment]
Crashes on W7 x64 with all these 3 pics.

**Comment by bitbegin** [comment]
seams GC bug:

```
>> recycle/off
>> to binary! trim mold/only reduce [load %3.jpg]
```

**Comment by bitbegin** [comment]
```
to binary! trim mold/only reduce [append/dup a: "" "a" 1100000]
```

**Comment by 9214** [comment]
> The only known leak is the bitmaps object allocated from the OS by `image!` values.

**Comment by endo64** [comment]
@9214 Crashes pictures in buggy.zip. Works if `recycle/off`.

**Comment by bitbegin** [comment]
@9214 @endo64 can you check if https://github.com/red/red/pull/3644 work for you? it works for me both:
`save %image.red reduce [load %1.png]` and `to binary! append/dup a: "" "a" 1100000` are all run ok

**Comment by qtxie** [comment]
If turn off the GC can make it work, then there is a bug in the GC. Maybe the GC corrupt the memory used by the C's allocator. As a consequence `copy-memory` crashes.

**Comment by greggirwin** [comment]
@9214, does the new fix solve this for you?

**Comment by 9214** [comment]
@greggirwin can't check it right now, will report in the next week.

**Comment by 9214** [comment]
@qtxie I can't reproduce the crash anymore.

**Comment by qtxie** [comment]
@9214 Thanks. I need to add some tests before closing it.

**Comment by 9214** [comment]
@qtxie don't forget to add the tests 😉

**Comment by qtxie** [comment]
@9214 Yes. I should have add it before. Now I don't even know how does the commit fix the issue. 😓 I'll try to figure out today and write the test. Otherwise I'll just add the code in the issue into the test suite.
