### ISSUE TITLE
[CRASH] Interoperability bug between libRedRT.so and the GC?

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3640]
**Describe the bug**
The following code crashes (on Linux only) when compiled with `-c` or `-c -u` options.

**To Reproduce**
Compile, execute:
```
Red []
repeat i 10 [
	append/dup b: copy [1 2 3] 1 i * 10000
	print mold/flat stats/info
	length? copy b
	print mold/flat stats/info
	recycle
	print mold/flat stats/info
	o: make object! []
	probe type? try [o/()]
	print "^/"
]
```
**Platform version(please complete the following information):**
```
Red 0.6.4 for Linux built 7-Dec-2018/9:41:53+04:00 commit #1bdbdc2
```
:point_up: [December 8, 2018 11:12 PM](https://gitter.im/red/bugs?at=5c0c25aaf4880a60a249e4b5)

**Comment by 9214** [comment]
Confirmed on 64-bit Mint installation.

**Comment by dockimbel** [comment]
Can reproduce on Ubuntu 16.04 64-bit.
