### ISSUE TITLE
Red evaluates 2.022794416824728e-308 == 2.2250738585072014e-308 / 1.1 inconsistently across platforms

### ISSUE THREAD

**Issue by PeterWAWood** [red/red#3643]
**Describe the bug**
Red evaluates 2.022794416824728e-308 == 2.2250738585072014e-308 / 1.1 inconsistently across platforms. It returns true on Linux and macOS but false on Windows.

**To Reproduce**
Evaluate `2.022794416824728e-308 == 2.2250738585072014e-308 / 1.1`
**Expected behavior**
The behaviour of Red is as consistent as possible across all platforms.
(I have checked with Java and JavaScript and both return true for the expression on Windows.)
A decision is required as to which behaviour is desired:

1. Such expressions should evaluate to true on all platforms
2. Such expressions should evaluate to false on all platforms
3. Red will evaluate such expressions differently on different platforms.

The decision then needs to be implemented. Choice 3 will require the test suite to distinguish which platform it is being run on.

**Platform version(please complete the following information):**
```
Red 0.6.4 for macOS, Ubuntu32, Windows7, Windows10 built 8-Dec-2018/15:08:13+08:00
```

**Comment by hiiamboris** [comment]
on Windows:
```
>> to-binary 2.022794416824728e-308
== #{000E8BA2E8BA2E8A}
```
on Linux:
```
>> to-binary 2.022794416824728e-308
== #{000E8BA2E8BA2E8B}
```
Note the last bit.

**Comment by qtxie** [comment]
It's an old issue and it's caused by the C's `strtod` is different in each platform. It can be fixed it by use our own `strtod`.

**Comment by qtxie** [comment]
The latest Red returns `false` on 3 platforms (Linux, macOS, Windows).
