### ISSUE TITLE
reset-matrix on MacOS flips the image

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3649]
**Describe the bug**
`reset-matrix` flips the image upside down.

Should be:
`? (draw 40x40 [fill-pen red box 0x0 40x10 translate 10x10 fill-pen brown box 0x0 40x10])`
![](https://i.gyazo.com/dfc08ae44f9de98db8d50f6a7d8a1c10.png)

Now with the matrix resetted everything is drawn from the lower left corner:
`? (draw 40x40 [reset-matrix fill-pen red box 0x0 40x10 translate 10x10 fill-pen brown box 0x0 40x10])`
![](https://i.gyazo.com/ea7e9c5b723563bff2c8befd156e2242.png)

**Platform version(please complete the following information):**
```
Red 0.6.4 for macOS built 11-Dec-2018/18:29:30+03:00 commit #21ef0b8
```

**Comment by dockimbel** [comment]
@hiiamboris Please confirm if this fix is working for you.

**Comment by hiiamboris** [comment]
@dockimbel Yes it works!
Before closing this ticket please remove lines 42-44, 46-47, 49-51, 54-55 of https://github.com/red/red/blob/master/tests/source/units/draw-test.red

**Comment by qtxie** [comment]
Was it fixed? I don't see any issue on my macOS VM.

**Comment by hiiamboris** [comment]
@qtxie https://github.com/red/red/pull/4054

**Comment by dockimbel** [comment]
@qtxie @hiiamboris It is unclear from this ticket history if it is fixed or not... could you please confirm what is the status of this ticket?

**Comment by hiiamboris** [comment]
@dockimbel fixed for Windows, MacOS VM, but not Travis' flavor of MacOS.
