### ISSUE TITLE
wait allows none as argument, but this always errors out

### ISSUE THREAD

**Issue by meijeru** [red/red#3652]
**Describe the bug**
The argument of `wait` may be `none`. It is not clear why. In any case, it always gives an error when used.

**To Reproduce**
>> wait none
*** Script Error: invalid argument: none
*** Where: wait

**Expected behavior**
Not documented (at least I have not found it).

**Platform version(please complete the following information):**
```
Presumably all
```

**Comment by meijeru** [comment]
I have seen the commit, but what is the rationale? Could that be explained somewhere?!?

**Comment by bitbegin** [comment]
In Rebol, `wait none` can also run

**Comment by meijeru** [comment]
Fine, but what does it DO?

**Comment by 9214** [comment]
Both in R2 and R3 `wait none` results in a breakable infinite loop.

**Comment by greggirwin** [comment]
We need a design note for the intended purpose. For ports, you could have a port that failed to open, and is `none`. In a block of wait targets, having a single none should be a no-op. But `block!` is also not yet supported. `None` behavior isn't doc'd for Rebol, and even the `dispatch` func doesn't provide clues as I hoped it might.
```
dispatch: func [
    {Wait for a block of ports. As events happen, dispatch port handler blocks.}
    port-block [block!] {Block of port handler pairs (port can be timeout too).}
    /local ports awake timeblk result
][
    ports: copy []
    foreach [port job] port-block: reduce port-block [
        if any [number? port time? port] [if none? timeblk [timeblk: :job]]
        append ports port
    ]
    forever [
        either awake: wait/all ports [
            if foreach item awake [
                set/any 'result do select port-block item item
                if all [value? 'result 'break = :result] [break/return true]
            ] [break]
        ] [do :timeblk]
    ]
]
```

**Comment by greggirwin** [comment]
I commented on @bitbegin's PR, so @qtxie or @dockimbel can weigh in.

**Comment by dockimbel** [comment]
`wait` in Red is just a partial implementation until we get to full I/O.

**Comment by dockimbel** [comment]
The `wait` spec block has just been copied from R2 in order to provide a partial implementation. This is a WIP, so I will close this ticket and the related PR as they are irrevelant right now.
