### ISSUE TITLE
expand-directives allows a paren argument, but this always errors out

### ISSUE THREAD

**Issue by meijeru** [red/red#3653]
**Describe the bug**
The argument to `expand-directives` may be a `paren!` value (why?), but this always gives an error because in the body it is used as argument to `expand` which does not allow a `paren!` value.

**To Reproduce**
>> expand-directives quote (a b c)
*** Script Error: expand does not allow paren! for its blk argument
*** Where: expand

**Expected behavior**
Not documented (at least I have not found it).

**Platform version(please complete the following information):**
```
Presumably all
```

**Comment by greggirwin** [comment]
Need to clarify the `expand` func vs preprocessor as well.

**Comment by 9214** [comment]
`do/expand` goes here too.

**Comment by dockimbel** [comment]
The `expand` call inside `expand-directives` has 2 arguments and a `/clean` refinement that the console's `expand` does not have. That should be a strong hint that it's a different function from another context. In %preprocessor.r, it's called in several places. Using functions with the same name in different contexts should not be an issue in Redbol.

In case of doubt, you can always query the context of word from the console:
```
b: body-of :expand-directives
context? b/6/1      ;-- second `expand` call

== make object! [
    exec: make object! [
        config: none
    ]
    protos: ...
```
