### ISSUE TITLE
to-pair with a single percent value is accepted, but with a block of two values they may not be percent

### ISSUE THREAD

**Issue by meijeru** [red/red#3655]
**Describe the bug**
See the title - this is an inconsistecy

**To Reproduce**
>> to-pair 200%
== 2x2
>> to-pair [100% 200%]
*** Syntax Error: invalid construction spec: [100% 200%]
*** Where: to
>> to-pair [1 2]
== 1x2

**Expected behavior**
>> to-pair [100% 200%]
== 1x2

Or, disallow `to-pair 200%`

**Platform version(please complete the following information):**
```
Presumably all
```

**Comment by greggirwin** [comment]
I seem to recall old chat about percent values and their relative vs absolute nature. Deserving of deeper thought.

**Comment by meijeru** [comment]
More consistent all around to disallow percent here. May be just a question of specifying number! when it was still only integer! + float! ...

**Comment by endo64** [comment]
I'm for disallowing percent for `make pair!` (`to` is same with `make` for pair), unless we will have pairs with float values.

**Comment by meijeru** [comment]
This can now also be closed?

**Comment by greggirwin** [comment]
Thanks for weighing in guys.
