### ISSUE TITLE
access violation on setting PANE facet to non-SERIES! value

### ISSUE THREAD

**Issue by 9214** [red/red#3656]
**Describe the bug**
Title.

**To Reproduce**
```red
view [button [face/pane: 'boom]]
```
Clicking on the button results in:
```
*** Runtime Error 1: access violation
*** at: 004CE8B5h
```

**Expected behavior**
Meaningful error message or poka-yoke disregard of a change.

**Platform version (please complete the following information):**
```
Red 0.6.4 for Windows built 11-Dec-2018/7:46:27+05:00 commit #02c277d
```

**Comment by greggirwin** [comment]
Confirmed.

**Comment by dockimbel** [comment]
As a side-note, they are many ways to crash face objects currently, as the backends implement very little type-checking on facets for now.

**Comment by endo64** [comment]
@dockimbel Should we add a milestone (ex. 0.9.x) to this and these kind of issues to not examine them again. Later we can fine tune the milestones, like we did with 0.6.4 and 0.6.5.

**Comment by dockimbel** [comment]
@endo64 I have at least one 0.9.x milestone planned for searching for all the ways to crash the runtime code and fixing them. I also have one for cleaning up and polishing all the language features, so that we can get a solid 1.0 design-wise too.

**Comment by hiiamboris** [comment]
FYI the provided snippet doesn't crash for me on W7. Tried multiple builds down to 0.6.1.
![](https://i.gyazo.com/da3dff41494ed2389808ced22423d8e1.png)

**Comment by 9214** [comment]
@hiiamboris that's cool, but you should really click that button.

**Comment by hiiamboris** [comment]
I did ☻ Nevermind, I see that the console crashes *after I click it and then close the window*

**Comment by hiiamboris** [comment]
It doesn't crash now, yet there's still an issue with this:
```
>> view [button [face/pane: 'boom]]
*** Script Error: foreach does not allow word for its series argument
*** Where: foreach
*** Stack: view do-events do-actor do-safe show 
```
Should such internal errors pop out?
