### ISSUE TITLE
argument type for source function is too wide

### ISSUE THREAD

**Issue by meijeru** [red/red#3658]
**Describe the bug**
The argument type for the `source` function is `[any-word! any-path]` but in the body of source the argument is supplied to `get/any` which only allows `[word! path!]`. Thus `source` can restrict its argument also to these two types.

**To Reproduce**
>> source 'add
*** Script Error: get does not allow lit-word! for its word argument
*** Where: get

**Expected behavior**
```
source: func ["Print the source of a function" 
    'word [word! path!] "The name of the function" 
    /local val
...
```
**Platform version(please complete the following information):**
```
Presumably all
```

**Comment by greggirwin** [comment]
I thought at first that this was related to lit-arg evaluation changes from R2 to Red, but it seems not. @9214, thoughts?

**Comment by meijeru** [comment]
I cannot even see a use case for other than word/path.

**Comment by 9214** [comment]
@greggirwin `set` accepts `any-word!` and `path!`, while `get` accepts only `word!` and `path!`. There might be a historial argument for that, but I think relaxing rules and allowing `any-word!` and `any-path!` for both natives might be a good idea (which I had in my head a while back).

Another thing is that `'quoted` arguments can be escaped with  `paren!`, `get-path!` or `get-word!` value. `:hard-quoted` arguments have no escape mechanism. That is, supplying  `get-path!` and `get-word!` argument with `'word [any-word! any-path!]` spec makes little sense, as they'll be escaped.

So, two paths:
* Follow @meijeru's proposal and restrict typeset to `[word! path!]`;
* Relax `get` and `set`, change `source` spec to `:word [any-word! any-path!]`.

I'd go with the former, but considered changes in the latter outside the scope of this issue.

**Comment by meijeru** [comment]
I suppose this can be closed now.

**Comment by greggirwin** [comment]
Closing this. @9214, notes on path handling, from your analysis above, would make a great to-do list item for you.
