### ISSUE TITLE
[Lexer] Hex literals inconsistencies and bugs

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3662]
**Describe the bug**
R/S and Red lexers treat these differently, and Red compiler is buggy.

**To reproduce**

**In the interpreter:**
```
>> print [10h 100h 1000h 10000h 100000h 1000000h]
16 256 4096 65536 1048576 16777216
```
That was totally OK!

**Compiled:**
```
Red []
print [10h 100h 1000h 10000h 100000h 1000000h]
```
Prints:
```
16 0 4096 0 1048576 0
```
what???

**R/S:**
```
Red/System []
print-line 100h
```
Prints:
```
Compiling to native code...
*** Loading Error: invalid hex literal: 100h
*** in file: %/D/devel/red/red-src/tests/1.reds
*** at line: 3
```

**Red routine:**
```
Red []
r: routine [][print-line 100h]
r
```
Prints:
```
0
```

**Expected behavior**
All scenarios should follow the interpreted behavior.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 7-Dec-2018/8:41:53+03:00 commit #1bdbdc2
```

**Comment by endo64** [comment]
Confirmed on Win10, `Red 0.6.4 for Windows built 6-Dec-2018/4:52:41+03:00 commit #08e9d17`

**Comment by hiiamboris** [comment]
One more bit: R/S accepts 2-, 4- and 8-digit hex literals. Nothing in between, not even FFFFFFh (6-digit) and such.

**Comment by 9214** [comment]
```red
>> 1h
== 1
>> 10000000h
== 268435456
>> 100000000h
== 0
```
