### ISSUE TITLE
Infix operator with lit-word first argument treats second argument wrongly

### ISSUE THREAD

**Issue by meijeru** [red/red#3664]
**Describe the bug**
I was inspired by Ren-C to make an infix equivalent of `reflect`: call it `of`. While at it, I decided to try `type of` to replace `type?`. The `of` infix operator needs a lit-word first argument. The second formal argument is a normal word. It turns out that the actual second argument, when it is a word, is not evaluated.

**To reproduce**
```
>> of: make op! func [field value][print type? value] ; minimal example, normal word! argument
== make op! [[field value]]
>> 'type of integer! ;; type needs to be quoted here
datatype ;; correct
>> of: make op! func ['field value][print type? value] ; same example with lit-word first argument
== make op! [['field value]]
>> type of integer! ;; type does not need to be quoted
word ;; integer! is not evaluated
```

**Expected behavior**
The treatment of the second argument should remain unaffected

**Platform version (please complete the following information)**
```
Not platform dependent, I think
```

**Comment by 9214** [comment]
This is a duplicate https://github.com/red/red/issues/3344

**Comment by meijeru** [comment]
Thanks. I will close now. It can be hard to check previous issues. Even the beta feature which looks up related issues did not work here.
