### ISSUE TITLE
Red GUI Console cannot be ran on Windows 8

### ISSUE THREAD

**Issue by qtxie** [red/red#3671]
**Describe the bug**
Red GUI Console cannot be ran on Windows 8

**Platform version (please complete the following information)**
Red 0.6.4 Windows 8

**Comment by qtxie** [comment]
Works fine on Win8.1

**Comment by greggirwin** [comment]
Should we note somewhere that Win 8.0 is not supported by the GUI console?

**Comment by greggirwin** [comment]
I don't know how widespread WIn8 is, versus how much work it will take to support it.

**Comment by greggirwin** [comment]
Works for me. Let's make sure we note that MS doesn't support it either, where we say we don't.
