### ISSUE TITLE
Auto complete doesn't work with uppercase file names

### ISSUE THREAD

**Issue by endo64** [red/red#3674]
**Describe the bug**
If there is a file named in uppercase in a folder, auto complete doesn't work correctly.

**To reproduce**

1.Create files named: `test1`,  `test2`, `TEST3`
2.Open console (GUI or CLI)
3.Go to that folder, type `%te` and press `tab`

**Expected behavior**
`%te` should be completed to `%test`

Case sensitive OSes should be considered as well.

**Platform version**
```
RED: [ branch: "master" tag: #v0.6.4 ahead: 47 date: 11-Dec-2018/3:54:21 commit: #ba127045ba10d19e0f586013432afc0b8e65b0b9 ]
PLATFORM: [ name: "Windows 10" OS: 'Windows arch: 'x86-64 version: 10.0.0 build: 17134 ]
```

**Comment by qtxie** [comment]
Code changed in commit 89f29492c2dae5a019f4158f7c75bf8cc4dad207

**Comment by greggirwin** [comment]
Works on Windows now, with the code changed to use `find`. However, `/case` is not used with find, so it will not match case on case-sensitive file systems at this time. The question is, should it? It would have to be an environment option. By default, I prefer case-insensitive matching.
