### ISSUE TITLE
AT <series> <position> does not check for integer type of <position>

### ISSUE THREAD

**Issue by meijeru** [red/red#3676]
**Describe the bug**
`at <series> <position>`  should allow only integer values for `<position>` except for `image!` values, which also allow pairs. The spec allows integers and pairs generally, but in `%series.reds` there is no check, only an `assert`. In `%image.reds` there is a separate implementation which allows integer and pair values.

**To reproduce**
`at [1 2 3] 3x5`  ;; 3, no error

**Expected behavior**
Error message on usage of pair, except for images

**Platform version (please complete the following information)**
```
all
```

**Comment by dockimbel** [comment]
That is unfinished work. Sematics for `pair!` positions when applied to series is not defined yet.
