### ISSUE TITLE
Color disabled in rich-text data

### ISSUE THREAD

**Issue by toomasv** [red/red#3691]
**Describe the bug**

Whenever `strike` or `underline` appear immediately before color-tuple in low-level data, color is not rendered.

**To reproduce**

```
>> view [rt: rich-text data [s [red "bbb"]] do [probe rt/data]]
[
    1x3 strike 255.0.0
]
```
![image](https://user-images.githubusercontent.com/11960635/50554894-c84e9b80-0ccb-11e9-8a3e-f2ee1ac1ebfc.png)

Color is rendered if tuple appears before `strike` / `underline` style-word. Also, this does not affect `italic` and `bold` styles.

**Expected behavior**

Color should be rendered with `strike` and `underline` as it is rendered now with `italic` and `bold`.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 30-Dec-2018/4:42:09+02:00 commit #6968dad
```

**Comment by qtxie** [comment]
It's strange that the code below works:
```
 view [rt: rich-text data [s [red "bbb"]] do [rt/data/2: 255.0.0 rt/data/3: 'strike probe rt/data]]
```

**Comment by qtxie** [comment]
The text color should always follow the range. The color following the `strike` is used to specify the color of the strike line, but this is feature is not implemented yet.

**Comment by toomasv** [comment]
OK, then my partial fix was OK. But this does not concern `italic` and `bold`, which show correctly if color follows to these?

Then the full fix needs to insert color just after address when uniting styles in optimization phase?

**Comment by toomasv** [comment]
Thanks for the detailed spec!
