### ISSUE TITLE
[View] actors format inconsistency between VID and make-face

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3693]
**Describe the bug**
VID expects actors to be a `block!`
while make-face (and make face!) expect an `object!`
This requires a manual workaround to turn that block into an object.

**To reproduce**
```
Red []

system/view/VID/styles/square: [
	template: [
		type: 'base
		color: green
		size: 100x100
		actors: [
			on-created: func [f e] [print "Created!"]
		]
	]
]

view/options [
	square
	with [
		actors: make actors [
			on-down: func [f e /local f2] [
				print "Clicked!"
				append f/parent/pane f2: make-face/offset 'square f/offset + 110x0
				? f/actors
				? f2/actors
			]
		]
	]
] [size: 400x150]
```

After clicking on the face:
![](https://i.gyazo.com/751380cded808ca418ea97bfb61da41f.png)

As you can see, `make-face` made a face with a useless `block!` actors facet that does not trigger anything - no second "Created!" message, and unclickable.

**Expected behavior**
`make-face` should be able to understand the template format used by VID

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 30-Dec-2018/5:42:09+03:00 commit #6968dad
```

**Comment by dockimbel** [comment]
I agree that the base behavior of `make-face` (without `/spec` refinement) is not satisfying as the face is not entirely constructed as a full instance of the argument style.

**Comment by dockimbel** [comment]
Your example can now be simplified a bit, as actors are properly merged between template styles and instanciated ones:
```
system/view/VID/styles/square: [
	template: [
		type: 'base
		color: green
		size: 100x100
		actors: [
			on-created: func [f e] [print "Created!"]
		]
	]
]

down-handler: func [f e /local f2] [
	print "Clicked!"
	append f/parent/pane f2: make-face/offset 'square f/offset + 110x0
	? f/actors
	? f2/actors
]

view/options [square on-down :down-handler] [size: 400x150]
```
