### ISSUE TITLE
FEAT: Add code of conduct to project

### ISSUE THREAD

**Issue by greggirwin** [red/red#3700]
Add via https://github.com/red/red/community.

Research others and see if @PeterWAWood has something drafted somewhere.

**Comment by dockimbel** [comment]
We already have one in the repo: https://github.com/red/red/blob/master/CODE_OF_CONDUCT.md

**Comment by greggirwin** [comment]
Hmmm, why didn't github know about that then? I created a new one, which references the old one that was just a copy of the wiki page.

**Comment by endo64** [comment]
@greggirwin We might need to Propose it here: https://github.com/red/red/community/code-of-conduct/new?template=citizen-code-of-conduct

See [here](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/)

**Comment by greggirwin** [comment]
I don't recall seeing a Propose button, but the Community page still seems to think we don't have one. I went through that process, so probably not worth more time now.
