### ISSUE TITLE
Inconsistency of Replace function with tag! value

### ISSUE THREAD

**Issue by endo64** [red/red#3703]
**Describe the bug**
`replace` with `tag!` value behaves different than `string!` values

**To reproduce**

```
>> replace "aaa <tag> ccc" <tag> "bbb"
== "aaa bbb ccc" ; on R2 and R3
== "aaa <bbb> ccc" ; on Red
```

**Expected behavior**
Same result as R2 & R3

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 1-Jan-2019/17:22:21+03:00 commit #8bf2cbe
```

**Comment by endo64** [comment]
@dockimbel it is already:

```
>> form <tag>
== "<tag>"
```

Or did I misunderstood your comment?

**Comment by hiiamboris** [comment]
Looks like `replace` went ahead of `find` here:
```
>> find "ab<b>b" <b>
== "b<b>b"
>> replace "ab<b>b" <b> 1
== "ab1b"
```
Should we open another ticket for `find`?
