### ISSUE TITLE
.deb wanted for debian/ubuntu

### ISSUE THREAD

**Issue by hypnosis-i2p** [red/red#3706]
**Describe the bug**

chmod a+x ~/Desktop/red/red-064 
Ok
./red
Compiling compression library...
Compiling Red console...
/home/user/.red/console-2018-11-22-8164: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
Ok
lsb_release -a && uname -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
Linux i7sn1 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Ok
echo $PS1
Ok\n
Ok

**To reproduce**
1. Download stable red version above;
2. chmod+x, run.

**Expected behavior**
1. Download .deb file for red
2. dpkg -i red.deb
3. red

**Platform version (please complete the following information)**
```
Red 0.6.4 for Linux built 22-Nov-2018/8:40:38+08:00 commit #755eb94
```

**Comment by endo64** [comment]
Did you try with libcurl4?

`sudo apt-get install libcurl4`

**Comment by Haxerking** [comment]
Currently i don't have laptop or any smart phone to access git hub dxc so
I'm sorry .

**Comment by x8x** [comment]
@9214 The download page is update thought I have to verify the exact version where the change occurred and add Alpine Linux instructions.

**Comment by hypnosis-i2p** [comment]
now after 2nd thought i came to a conclusion that .deb is a rubbish and bloat for rebol/red. trashcan

**Comment by pierrechtux** [comment]
?
Oh well, `apt install rebol red` would be just so convenient for a daily use of these marvellous languages, that are just so useful and magical for daily GNU/Linux administration tasks, both on servers or on clients.

Note that I'm not referring to `dpkg -i`, but to `apt` or similar (yum, etc.).

The gain of popularity from the availability of such a package would be great, by spreading the word among the world of GNU/Linux sysops.

At the moment, when you mention "Rebol" or "Red" to them (us), and they have to get an executable which ... sometimes doesn't run, it is most often a no-go.  Too bad.
