### ISSUE TITLE
[View] `event/window` returns a wrong face under very specific circumstances

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3722]
**Describe the bug**

`event/window` is supposed to return a window face, but sometimes it returns the very face provided to the event actor.

**To reproduce**

Try this:
```
system/view/VID/styles/bomb: [
	template: [
		type: 'base		size: 50x50
		actors: [on-created: func [f] [f/color: random white]]
	]
]

view [ bomb on-down [? event/window/type] ]
```

Click on the base, and it outputs:
```
EVENT/WINDOW/TYPE is a word! value: base
```

**Expected behavior**
`EVENT/WINDOW/TYPE is a word! value: window`

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 9-Jan-2019/5:46:16+03:00 commit #acf3492
W7 x64
```

**Comment by endo64** [comment]
Confirmed on Win10.

**Comment by hiiamboris** [comment]
Smaller snippet: `view [base #FF007001 on-down [? event/window/type]]`
The key here is to have non-zero alpha in base's initial color.

**Comment by qtxie** [comment]
Seems fixed in the version red-20may20-053dece4c.

**Comment by hiiamboris** [comment]
@qtxie 
![](https://i.gyazo.com/01df43a996965eab2076e1f8a9ce4cc2.png)
W7

**Comment by qtxie** [comment]
OK. Another layered window issue.
