### ISSUE TITLE
Can't change attributes of text in VID box

### ISSUE THREAD

**Issue by dsunanda** [red/red#3730]
**Describe the bug**
 You can change attributes of text in VID TEXT boxes (eg font color and size). But it seems not possible to do so for any other VID style. 

**To reproduce**
```
view/no-wait [
    b: box "BOX" font-color blue font-size 10
    t: text "TEXT" font-color blue font-size 10
]
b/font/size:  t/font/size: 20
b/font/color: t/font/color: green
```

b/text remains as original. No amount of coaxing (with SHOW etc) helps.

**Expected behavior**
Change of attributes on screen

HiIamBoris comments: 
It works for base but doesn't work for box or any base with non zero alpha. Mention that it's the same for W7, W8 and W10.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 11-Jan-2019/2:18:27 commit #5e37a10
Also with 0.6.4 stable under Win10
```

**Comment by hiiamboris** [comment]
Snapshot:
![](https://i.gyazo.com/052b488a137c409efeb47eb6c0ba0855.png)

**Comment by nedzadarek** [comment]
It doesn't work with the old version as well: `Red for Windows version 0.6.3 built 26-Mar-2018/1:14:22+02:00` on Win 8.1 64x

**Comment by dockimbel** [comment]
It works fine on latest commit.

**Comment by hiiamboris** [comment]
Is it though @dockimbel ?
![](https://i.gyazo.com/5242166ff0d48fab34b124fe55c4e930.png)
`Red 0.6.4 for Windows built 25-Sep-2022/4:45:17+03:00  commit #499b279`
