### ISSUE TITLE
cause-error incompatible with R2/R3 as it does not accept string! as an argument

### ISSUE THREAD

**Issue by Dobeash** [red/red#3738]
**Describe the bug**

In R2/R3 the following works:
```
cause-error 'user 'message "blah"
```

but Red requires:
```
cause-error 'user 'message ["blah"]
```

**To reproduce**

```
cause-error 'user 'message "blah"
```

**Suggested Fix**

Gregg Irwin proposed changing the spec and switching from `reduce` to `compose`:

```
cause-error: func [
    {Causes an immediate error throw, with the provided information} 
    err-type [word!] 
    err-id [word!] 
    args [block! string!] 
][
    args: compose [(:args )]
    do make error! [
        type: err-type 
        id: err-id 
        arg1: first args 
        arg2: second args 
        arg3: third args
    ]
]
```

**Comment by endo64** [comment]
Related [conversation](https://gitter.im/red/bugs?at=5c3cfbca8318994524ed09f5)

**Comment by greggirwin** [comment]
Yay! I get a coding assignment! :^)

**Comment by 9214** [comment]
@greggirwin I believe this one can be closed.

**Comment by greggirwin** [comment]
Was there a PR other than mine (which needed fixes)?

**Comment by 9214** [comment]
@greggirwin nope, I thought yours fixed the issue.

**Comment by greggirwin** [comment]
@hiiamboris found a problem, related to how the test system works with errors, so I need to revisit.
