### ISSUE TITLE
[View] CRASH in `set-focus` with field & area on W8+

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3753]
**Describe the bug**

`Red [Needs: View] view [a: area on-created [set-focus a]]`
or
`Red [Needs: View] view [a: field on-created [set-focus a]]`

When:
- run from CLI console with View support, as `do %1.red`, or
- compiled as `red -r -e -d 1.red` & ran
- perhaps some other circumstances

On W8 and W10 results in:
```
*** Runtime Error 1: access violation
*** in file: /D/devel/red/red-src/red/modules/view/backends/windows/gui.reds
*** at line: 143
***
*** stack: gui/get-node-facet 00000000h 0
*** stack: gui/get-facet 0050AD3Ch 0
*** stack: gui/process-command-event 003B003Ah 273 16777216 14484762
*** stack: gui/WndProc 003B003Ah 273 16777216 14484762
```

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 19-Jan-2019/17:04:42+03:00
```

**Comment by greggirwin** [comment]
Can't reproduce on Win10. What Win OS are you on?

**Comment by hiiamboris** [comment]
Win7. But this was discovered by @toomasv on W10. Looks like everyone's W10 is different...

**Comment by toomasv** [comment]
I confirm the above issue appears on my W10:
Compiled:
```
*** Runtime Error 1: access violation
*** in file: /C/Users/Toomas/Documents/Red/modules/view/backends/windows/gui.reds
*** at line: 143
***
***   stack: gui/get-node-facet 00000000h 0
***   stack: gui/get-facet 004F2314h 0
***   stack: gui/process-command-event 000E149Ch 273 16777216 7736260
***   stack: gui/WndProc 000E149Ch 273 16777216 7736260
```
On cli:
```
*** Runtime Error 1: access violation
*** at: 004CB4FBh
```
```
Red 0.6.4 for Windows built 5-Jan-2019/3:37:59+02:00 commit #1c0642e
```

**Comment by endo64** [comment]
Confirmed on Win10. 
This could be the reason `on-create actor which will be called when the face is shown for the first time, just before system resources are allocated for it.`
