### ISSUE TITLE
sort with comparator function returning number sorts incorrectly

### ISSUE THREAD

**Issue by endo64** [red/red#3768]
**Describe the bug**
When comparator function returns a positive number (`integer!` or `float!`) `sort` treats it as `false`, and when the returned number is negative `sort` treated it as `true`. It should be the opposite.

**To reproduce**
```
>> sort/compare [1 2 3 4 5 6] func [a b] [5]
== [1 2 3 4 5 6]
>> sort/compare [1 2 3 4 5 6] func [a b] [5.3]
== [1 2 3 4 5 6]
>> sort/compare [1 2 3 4 5 6] func [a b] [-5]
== [6 5 4 3 2 1]
```

**Expected behavior**
Return value should be `[6 5 4 3 2 1]` as in R3 (note that R2's result is complete mess)

**Platform version**
```
Red 0.6.4 for Windows built 30-Jan-2019/9:03:13+03:00 commit #25ef631
```

**Comment by hiiamboris** [comment]
:point_up: [February 2, 2019 6:27 PM](https://gitter.im/red/bugs?at=5c55b6e054f21a71a1e84e42) discussion

**Comment by dockimbel** [comment]
There is something wrong with the `compare` function behavior now:
```
>> sort/compare [1 2] func [a b] [a < b]
== [2 1]
>> sort/compare [1 2 3 4 5 6] func [a b] [a < b]
== [6 5 4 3 2 1]
```

We require `a` to be less than `b`, so the input series should be left unchanged as they are already rightly sorted (same as in Rebol).

**Comment by hiiamboris** [comment]
Looks like we all read the intent of the compare func differently ☺
We with @endo are apparently reading it as "swap if result is true or greater than zero". While you are reading it as "don't touch it if it's true or greater than zero". Perhaps this should be documented in the `sort` docstrings.

**Comment by dockimbel** [comment]
The past fix was too broad, it should have changed only the behavior when numbers are returned by `compare` function.

@hiiamboris After reverting partially the previous fix, it now works identically as in R3, and uses the same rule as in all Rebol versions: swap on `false` or greater than zero, which is the intuitive way (maybe more visible if I rename the local words):
```
>> sort/compare [1 4 3 5 2] func [left right][left < right]
== [1 2 3 4 5]
>> sort/compare [1 4 3 5 2] func [left right][left > right]
== [5 4 3 2 1]
```
The comparison function expresses a constraint on a couple of values, if that constraint is satisfied, no change occur.

**Comment by endo64** [comment]
@dockimbel Did you fix it on another branch? I just pulled the latest version, my test results are different:

```
>> sort/compare [1 2] func [a b] [a < b]
== [2 1]
>> sort/compare [1 4 3 5 2] func [left right][left < right]
== [5 4 3 2 1]
>> sort/compare [1 4 3 5 2] func [left right][left > right]
== [1 2 3 4 5]
```

**Comment by dockimbel** [comment]
It's on the `fast-lexer` branch.

**Comment by Oldes** [comment]
I think that current output is not correct:
```red
sort/compare [1 2 6 5 4 3] func [a b] [b - a]
;== [1 2 3 4 5 6]
```
In Rebol it is reversed:
```rebol
sort/compare [1 2 6 5 4 3] func [a b][a < b]
;== [1 2 3 4 5 6]
sort/compare [1 2 6 5 4 3] func [a b][a - b]
;== [1 2 3 4 5 6]
```
see [discussion](https://matrix.to/#/!EorVRCzrVpjojJtctJ:gitter.im/$uMlyUj21cq5r_LmQvQnD_nvpHlRlYe_KfhLJgwnfMMw?via=gitter.im&via=matrix.org&via=tchncs.de)

**Comment by dockimbel** [comment]
I agree with the rationale for integer results for the comparison function.

@qtxie We should also take the opportunity to support integer argument to `/compare` (and block too if not too much work).
