### ISSUE TITLE
reading uploaded file is broken

### ISSUE THREAD

**Issue by rebred** [red/red#3777]
**Describe the bug**
when uploading a file using an HTML form RED can only read the first 4 lines

**To reproduce**
this is the RED script that print the file received from an HTML form:

#!/Library/WebServer/Documents/red2.dms
Red[]
print "Content-type: text/html^/"
print ["input1:" input]
print ["input2:" input]
print ["input3:" input]
print ["input4:" input]
print ["input5:" input]

this is the HTML output:

input1: ------WebKitFormBoundaryxBNH9pwUye3VNRvU 
input2: Content-Disposition: form-data; name="pic"; filename="img0.png" 
input3: Content-Type: image/png 
input4: 
input5: *** Runtime Error 100: no value matched in CASE *** at: 000D5922h

**Expected behavior**

RED should read every line of the file uploaded

**Screenshots**

###   *** Runtime Error 100: no value matched in CASE *** at: 000D5922h

**Platform version (please complete the following information)**
```
Red 0.6.4 for macOS built 4-Feb-2019/19:45:38+01:00 commit #a4d8240
```

**Comment by 9214** [comment]
Can you be _a bit more_ specific? What file? What HTML form? Error message indicates that the problem is in the type of data being passed (`image!` or `binary!` I surmise) rather than in the number of lines. How can we deduce any of this from your report?

**Comment by rebred** [comment]
I am using Apache, this is the HTML form

<form action="/image.cgi" method="post" enctype="multipart/form-data">
  <input type="file" name="pic" >
  <input type="submit">
</form>

this is: image.cgi

#!/Library/WebServer/Documents/red2.dms
Red[]
;print ["Content-type" Content-type]
print "Content-type: text/html^/"
print "<body>"
print "<BR><BR>input1:"
print input
print "<BR><BR>input2:"
print input
print "<BR><BR>input3:"
print input
print "<BR><BR>input4:"
print input
print "<BR><BR>input5:"
print input

I am uploading a PNG image

**Comment by qtxie** [comment]
The `input` function is for reading text only. You can use `read-stdin` to read binary data for now until we finish the full IO.
