### ISSUE TITLE
Reaction created with IS containing `collect [keep/only]` produces an error

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3790]
**Describe the bug**
```
>> make reactor! [n: 3  b: is [collect [repeat x n [keep x]]]]
== make object! [
    n: 3
    b: [1 2 3]
]
>> make reactor! [n: 3  b: collect [repeat x n [keep/only x]]]
== make object! [
    n: 3
    b: [1 2 3]
]
>> make reactor! [n: 3  b: is [collect [repeat x n [keep/only x]]]]
*** Script Error: keep has no value
*** Where: get
*** Stack: react  
```

**Expected behavior**

Third case should give the same result as the other ones.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 30-Jan-2019/9:03:13+03:00 commit #25ef631
```

**Comment by 9214** [comment]
I rather think that `is` [messes up](https://github.com/red/red/blob/master/environment/reactivity.red#L204) any `path!` value, not just `keep/only`.

**Comment by hiiamboris** [comment]
Right. And it will probably be enough of a fix to use get-words in place of `item/1` at [L201](https://github.com/red/red/blob/master/environment/reactivity.red#L201) and maybe other places

**Comment by hiiamboris** [comment]
Actually, this whole ticket can serve as an argument in favor of restricting paths from being *always active accessors* to *accessors active only when the function was referred to by a word*.

Like this:
`c: compose [f: (func [/r][print "invoked"])]`

This is OK:
```
>> c/f
invoked
>> c/f/r
invoked
```
But this is harmful:
```
>> c/2
invoked
>> c/2/r
invoked
```
After all, if @dockimbel makes these mistakes on occasion - everyone will.

**Comment by 9214** [comment]
```red
>> pick c 2
== func [/r][print "invoked"]
>> select c 'f
== func [/r][print "invoked"]
```

**Comment by hiiamboris** [comment]
I believe L300 is the error source.

**Comment by greggirwin** [comment]
Great research guys. Thanks!

**Comment by dockimbel** [comment]
> I rather think that is messes up any path! value, not just keep/only.

Paths processes in reaction blocks are not modified...

> Actually, this whole ticket can serve as an argument in favor of restricting paths from being always active accessors to accessors active only when the function was referred to by a word.

The issue in this ticket is unrelated to that. It's caused by not taking into account the case where the first word found in a path of length 2 is unset.

> c/f vs c/2

Those two paths are semantically equivalent, so introducing an arbitrary exception there breaks consistency. If you think that you can make a really good case for it, you can try that in a REP.

**Comment by hiiamboris** [comment]
> If you think that you can make a really good case for it, you can try that in a REP.

No, I reconsidered some time ago, it's fine as it is ;)

There's a bigger issue with reactivity and any other preprocessing:
```
>> r: reactor [a: 1 b: 2 react [b: collect [keep/only self/a]]]
== make object! [
    a: 1
    b: [1]
]
>> dump-reactions
1:---
  Source: object [only]
   Field: only
  Action: [b: collect [keep/only self/a]]
2:---
  Source: object [a b]
   Field: a
  Action: [b: collect [keep/only self/a]]
```
(reacts to global keep :)

But I don't see a solution yet.

**Comment by dockimbel** [comment]
Does not seem to happen anymore:
```
>> r: reactor [a: 1 b: 2 react [b: collect [keep/only self/a]]]
== make object! [
    a: 1
    b: [1]
]
>> dump-reactions
1:---
  Source: object [a b]
   Field: a
  Action: [b: collect [keep/only self/a]]
```

**Comment by hiiamboris** [comment]
Ah sorry, copy/paste problem, `keep: object [only: x]` missing :D
