### ISSUE TITLE
[Compiler] `self` isn't recognized by `react`

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3797]
**Describe the bug**

%1.red:
```
Red []
r: make reactor! [a: 1 react [self/a print 123]]
```
Compiled (-c/-r doesn't matter)
```
> red -c 1.red & 1.exe
*** Script Error: self has no value
*** Where: get
*** Stack: react
```

**Expected behavior**

Works when interpreted, should also work compiled.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 30-Jan-2019/9:03:13+03:00 commit #25ef631
```

**Comment by hiiamboris** [comment]
No error report anymore now. But the reaction is not being registered when compiled.

**Comment by dockimbel** [comment]
This behavior is by design. `self` is a keyword and not a slot in the object's context (see [explanation](https://github.com/red/red/issues/4501#issuecomment-1231656729)).

So, in order to accomplish what you want, you need to explicitly assign a slot in the object to such self-reference. The following example works as you expected when compiled:
```
Red []
r: make reactor! [a: 1 parent: self react [parent/a print 123]]
```

**Comment by greggirwin** [comment]
`Self` will be an important thing to spec and doc, because it's special and cases like this are likely to come up a lot.

**Comment by dockimbel** [comment]
The issue is that the reaction is evaluated later, outside of the object, so `self` is "out of context". Setting a reaction on a reactor! object from within is not the "normal" way to do it. Here is the usual way:
```
r: make reactor! [a: 1]
react [r/a print 123]

>> r/a: 2
123
== 2
```

**Comment by hiiamboris** [comment]
> The issue is that the reaction is evaluated later, outside of the object, so `self` is "out of context".

You must be confusing something. It works in interpreter. During `react` evaluation, `self` has value and `react` gets an object value out of it.

**Comment by dockimbel** [comment]
You're right, the `react`'s block argument is not compiled, but processed at run-time by the interpreter. The issue happens during `react`'s processing of the block argument, `self` has no context, so generate and error.

That said, `self` has a "special" context resolution, but the extra info needed for that seems to not have been generated by the compiler for the interpreter to process it...
