### ISSUE TITLE
McAffee Security Endpoint deletes Red console as trojan

### ISSUE THREAD

**Issue by mydoghasworms** [red/red#3802]
**Describe the bug**
Red GUI Console is identified by McAffee Endpoint Security provider as a Trojan and deletes it.

From the log:

```
[redacted] ran R:\USERS\[redacted]\DOWNLOADS\red-04mar19-53b5b37b.exe, which attempted to access C:\ProgramData\Red\gui-console-2019-3-4-76181.exe. The Trojan named GenericRXGX-HD!B469AA210B2C was detected and deleted.
```

**To reproduce**
1. Download and execute latest Red Windows release or daily build.
2. Execute downloaded file
3. Check errors in Windows Event Viewer / Application Log

**Expected behavior**
Console should launch

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/514461/53784936-76bacb00-3f1f-11e9-86ee-6658ca555454.png)

**Platform version (please complete the following information)**
```
Windows 10 Enterprise running McAffee Endpoint Security 10.5.4
```

**Comment by 9214** [comment]
@mydoghasworms thanks for the heads-up; don't forget to report it as a false-positive to McAfee.

@greggirwin :point_up: could you label this as `type.AV`?

**Comment by rebolek** [comment]
@mydoghasworms can you please check `gui-console.exe` (19-03-05 or newer) from https://www.rebolek.com/builds/ ? Latest version should be compressed with `upx` that should theoretically work as workaround for AV problems.

**Comment by greggirwin** [comment]
@9214 done.

**Comment by dockimbel** [comment]
Closing this ticket. Feel free to ask for reopening if the same AV makes trouble again.
