### ISSUE TITLE
Red Console crashes after using it for a while

### ISSUE THREAD

**Issue by alex65536** [red/red#3811]
**Describe the bug**
After using the console for some time and entering some commands, the interpreter crashes with:
```
Runtime Error 1: access violation
                                          *** at: 0806A5CBh
```
and the shell then becomes unusable (e. g. doesn't echo the characters typed).

The crash always happens during auto-completion (after pressing &lt;Tab&gt;). Didn't notice the correlation between the crash and the word being autocompleted.

**Platform version (please complete the following information)**
Red 0.6.4 for Linux built 22-Nov-2018/3:40:38+03:00 commit #755eb94

I am using Debian GNU/Linux 10 and Konsole as a terminal emulator.

**Comment by 9214** [comment]
@alex65536 can you reproduce this crash with the [nightly build](https://static.red-lang.org/dl/auto/linux/red-latest)?

**Comment by alex65536** [comment]
@9214, I'll try

**Comment by endo64** [comment]
@alex65336 did you test with nightly build? How long do you keep the console open? Could it be related to Konsole?

**Comment by alex65536** [comment]
> How long do you keep the console open?

I was playing with Red for maybe half an hour, entering some commands.

For now, I cannot reproduce it by some reason (on Red 0.6.4, the same where the bug happens), but I'll try more.

**Comment by endo64** [comment]
@alex65536 Lets keep this issue open for a while, if no one else faces this issue or you can find some causes then it probably something with your system, hence we close the issue. Thanks for digging!

**Comment by dockimbel** [comment]
I guess it's time to close it now. Feel free to ask for re-opening if you notice such crash again.
