### ISSUE TITLE
[View] menu instantly disappears when shown

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3818]
**Describe the bug**

This code should show a menu when right-clicked on a base:
```
Red [needs: view]
view [panel [base with [menu: ["a" a]] on-menu [probe event/picked]]]
```
It works in GUI console.

When ran as `red --cli ...` or from any (CLI/GUI) custom-built console (with rebol from sources) the menu is shown and then instantly disappears. I can barely notice that it was shown at all. Same behavior for any face.

Removing `panel` fixes it.

**Screenshots**
![](https://i.gyazo.com/b75a163c2a8b439d150dde388e5d04d7.gif)

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 13-Mar-2019/6:42:17+03:00 commit #0af69a5
```

**Comment by qtxie** [comment]
It works well on Win10.

**Comment by endo64** [comment]
Works for me too (Win10), @hiiamboris Are you on Win7 or Win8.1?

**Comment by hiiamboris** [comment]
W7

**Comment by hiiamboris** [comment]
I'm closing this as the *only way* I can reproduce it when I start `red` from ConEmu. It does some hijacking of system calls so I suspect it's the cause.
