### ISSUE TITLE
[View] `event` gets corrupted inside an actor by another `view []`

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3823]
**Describe the bug**

Try this:
```
view [
  base cyan on-down [
    probe event/offset
    view [base purple rate 3 on-time [unview]]
    probe event/offset
  ]
]
```
Click on the base and see another window appearing then disappearing.
Output is like this:
```
35x42    ;) event at the actor entry was correct
0x0      ;) after view invocation it is corrupted
```

**Expected behavior**

`event` should be preserved until the actor finishes.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 13-Mar-2019/6:42:17+03:00 commit #0af69a5
```

**Comment by greggirwin** [comment]
Confirmed on Win10.

**Comment by qtxie** [comment]
No corruption in the latest version anymore.

**Comment by greggirwin** [comment]
Looks good on Win10 here now.
