### ISSUE TITLE
Scrollable flag doesn't work for drop-list and drop-down faces

### ISSUE THREAD

**Issue by DVL333** [red/red#3830]
**Describe the bug**
Scrollable flag doesn't work for drop-list and drop-down faces - a vertical scroll-bar can't be enabled manually for these faces. 

**To reproduce**
```
dlist: make face! [type: 'drop-list size: 100x50 offset: 10x10 
    data: ["Line1" "Line2" "Line3" "Line4" "Line5" "Line6" "Line7" "Line8" "Line9" "Line10"]
    selected: 2 flags: 'scrollable]
append p: [] dlist
view make face! [type: 'window size: 120x90 pane: p]
```

**Expected behavior**
According to the documentation a vertical scroll-bar must be enabled.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 25-Mar-2019/13:11:08+03:00 commit #e6c96aa
```

**Comment by greggirwin** [comment]
It was mentioned in chat that `scrollable` was the way to do it, and I could have sworn there was an example somewhere, but it doesn't work and I can't find an example, so we should add a `TBD` to the docs for it @gltewalt.

**Comment by dockimbel** [comment]
`scrollable` flag is not the way to do it. A drop-list calculates automatically if a scrollbar should be displayed or not depending on the number of visible rows compared to the total number of rows. There is no option for now to set the number of visible rows in lists. You can open a wish for that.
