### ISSUE TITLE
PROBE FACE/PARENT interrupts FIELD / AREA event handling

### ISSUE THREAD

**Issue by 9214** [red/red#3848]
**Describe the bug**
Probing `parent` facet of `field` or `area` in event handler effectively prevents them from displaying the input.

**To reproduce**
```red
view [field on-key [probe face/parent]]
```

Note that this affects only scripts running from GUI console. Also, note that the above example works with `print` instead of `probe`  as expected, but not with `print mold`.

**Expected behavior**
Input field is updated as usual, `parent` face is probed and printed in the background.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 13-Apr-2019/11:27:16+05:00 commit #fb18d4e
```

**Comment by dockimbel** [comment]
I can reproduce it on W10.
