### ISSUE TITLE
Syntax Error: invalid binary!

### ISSUE THREAD

**Issue by jefurry** [red/red#3855]
**Describe the bug**
Syntax Error: invalid binary! at "2#{0000 1111}".

**Expected behavior**
for Rebol:
```
>> 16#{12 34}
== #{1234}

>> 64#{abcd efgh}
== #{69B71D79F821}

>> 2#{0000 1111}
== #{0F}
```

for Red:
```
>> 16#{12 34}
== #{1234}

>> 64#{abcd efgh}
== #{69B71D79F821}

>> 2#{0000 1111}
*** Syntax Error: invalid binary! at "2#{0000 1111}"
*** Where: do
*** Stack: load
>>
```

**Platform version (please complete the following information)**
```
Red 0.6.4 for macOS built 22-Nov-2018/8:40:38+08:00 commit #755eb94
```

**Comment by qtxie** [comment]
The lexer only allows separate each byte by spaces. That why `2#{0000 1111}` throw an error.

**Comment by jefurry** [comment]
@qtxie For binary, it is intuitive to separate by half-byte.

**Comment by 9214** [comment]
Both R2 and R3 support this, so it makes sense to relax lexing rules a bit.

**Comment by meijeru** [comment]
Not trivial, but doable.
