### ISSUE TITLE
libRed crash on macOS

### ISSUE THREAD

**Issue by 9214** [red/red#3860]
**Describe the bug**
On 64-bit macOS, running C application linked with libRed results in access violation. (see [this](https://gitter.im/red/help?at=5cc036cf4b4cb471d94b7890) chat for reference).

**To reproduce**
1. Build libRed
```
red build libRed
```
2. Prepare C code
```C
#include "libRed/red.h"
int main(){
    redOpen();
    redDo("print {Hello, World!}");
    redClose();
    return 0;
}
```
3. Link
```shell
gcc bug.c -lRed -L. -m32 -o bug
```
4. Execute

**Expected behavior**
I expect compiled binary to be fully functional. e.g. on 64-bit Linux Mint everything works silky smooth.

**Platform version (please complete the following information)**
Latest, crash was observed on macOS High Sierra.

**Comment by rcqls** [comment]
This is the output of the example provided above by @9214 running on macOS Sierra.
```
$ gcc test.c -lRed -L. -m32 -o test
$ ./test

*** Runtime Error 1: access violation
*** at: 00221492h
```
