### ISSUE TITLE
[Compiler] weird complaint about `single?` func

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3862]
**Describe the bug**

This code cannot be compiled w/o encapping (`red -c 1.red` or `red -r 1.red`):
```
Red []
x: [1]
if single? x [print "TRUE"]
```
Compiler shows an error:
```
Compiling D:\devel\red\red-av\1.red ...                                    
...using libRedRT built on 22-Apr-2019/18:51:22                            
*** Compilation Error: expected a block for IF-BODY instead of word! value 
*** in file: D:\devel\red\red-av\1.red                                     
*** near: [x [print "TRUE"]]                                               
```
Same error appears if `unless` is used in place of `if`.

`single?` is one of the latter additions defined [here](https://github.com/red/red/blob/6dcea4a482a8528d0dab8bf18f2b63785375e689/environment/functions.red#L1051) as `single?: last?: func [...]`

However the same code compiles if `last?` is used instead of `single?`. It also compiles with many other functions from `help "?"` output that I have tried.

It also compiles if the block `x` is inlined as `if single? [1] ...`.

Changing the order `single?: last?: ..` to `last?: single?: ..` doesn't help - it still works with `last?` but not with `single?`

**Expected behavior**

Should compile.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 22-Apr-2019/19:40:30+03:00 commit #9ac4430
```

**Comment by dockimbel** [comment]
The way the `single?` function is defined is not compatible with the compiler:
```
single?: last?: func [
```
The compiler processes those runtime source files specifically to extract function definitions, and you are not allowed to carelessly change those core files. Currently, the compiler only recognizes `name: func` and `name: :other-name` patterns for defining functions.

**Comment by greggirwin** [comment]
@dockimbel, I wouldn't call it a careless change. It's a compiler limitation we didn't know about, and has been in place without issue for 2 months. Why does Red build successfully with it, but not user apps?

**Comment by greggirwin** [comment]
Ah, likely because nobody used `single?` yet.

**Comment by greggirwin** [comment]
Added a note to the Compiler Limitations wiki page about it.

**Comment by hiiamboris** [comment]
Works for me.
