### ISSUE TITLE
access violation on a specific pattern of function application

### ISSUE THREAD

**Issue by 9214** [red/red#3864]
**Describe the bug**
`function!` that accepts quoted `op!`s and returns `scalar!` (with exception of `date!`), if applied with `do reduce [<function> <quoted words>]` construct, results in access violation.

**To reproduce**
```red
f: func [:a :b][1] do reduce [:f '+ '-]
```
Yields:
```red
*** Runtime Error 1: access violation
*** at: 004304F1h
```

Stack trace from debugging console:
```red
*** Runtime Error 1: access violation
*** in file: .../runtime/datatypes/string.reds
*** at line: 1045
***
***   stack: red/string/concatenate-literal-part 028603F4h 00779000h 1350576
***   stack: red/datatype/mold 02C5A898h 028603F4h false false true 00000000h 0 0
***   stack: red/actions/mold 02C5A898h 028603F4h false false true 00000000h 0 0
***   stack: red/error/reduce 028603D4h 029808CCh
***   stack: red/error/form 029808CCh 028603C4h 028603A4h -18
***   stack: red/actions/form 029808CCh 028603C4h 028603A4h 0
***   stack: red/block/form 028603B4h 028603C4h 028603A4h 0
***   stack: red/actions/form 028603B4h 028603C4h 028603A4h 0
***   stack: red/actions/form* -1
***   stack: red/natives/prin* true
***   stack: red/natives/print* true
***   stack: ctx475~do-command 027D1BC4h
***   stack: ctx475~eval-command 027D1BC4h
***   stack: ctx475~run 027D1BC4h
***   stack: ctx475~launch 027D1BC4h
```

Also (note the weird error messages):
```red
>> do reduce [func [:a :b :c][1] '+ '- '*]
*** Script Error: object!: needs a value
*** Where: object!
*** Stack:  

>> do reduce [func [:a :b][1] '+ '-]
*** Script Error: + does not allow none! for its value2 argument
*** Where: +
*** Stack:  

>> do reduce [func [:a][1] '+]
*** Script Error: + operator is missing an argument
*** Where: do
*** Stack:
```

**Expected behavior**
I expect such function application to behave like in common-case scenario:
```red
>> f: func [:a :b][1] f + -
== 1      
```

**Platform version (please complete the following information)**
Latest.

**Comment by dockimbel** [comment]
> I expect such function application to behave like in common-case scenario

It cannot behave like that, as infix operators have precedence, so you'll necessarily get a "operator is missing an argument" error.

**Comment by dockimbel** [comment]
The crash is fixed and now those patterns will consistently produce an "operator is missing an argument" error.

**Comment by 9214** [comment]
> It does not behave like that

Code snippet in my example tells me the opposite. `+` and `-` are quoted and safely passed to `f`, as expected.

**Comment by dockimbel** [comment]
@9214 The `+` and `-` words are passed to `f` but they are already on the call stack before `f` is evaluated (because infix ops really do take precedence), so that when `f` returns, a left operand is provided, but the right operand is still missing.

**Comment by 9214** [comment]
@dockimbel I see. This ticket ties with https://github.com/red/red/issues/3840.

**Comment by 9214** [comment]
I've checked the fresh build:
```red
>> f: func [:a :b][1] do reduce [:f '+ '-]
*** Script Error: + operator is missing an argument
*** Where: +
*** Stack:  

>> f + -
== 1
```

I can live with this difference of course, but it should be properly documented. Why `+` errors out in the former case but gets quoted in the latter?

**Comment by greggirwin** [comment]
@9214 add it to your Guru Docs / articles to-do list. :^)

**Comment by dockimbel** [comment]
@9214 Good catch. It can be improved.
