### ISSUE TITLE
Ask "" crashes when not getting characters piped to stdin

### ISSUE THREAD

**Issue by loziniak** [red/red#3874]
**Describe the bug**
Following script:
```
Red [File: %adapter.red]
#include %red-github/environment/console/CLI/input.red
arg-str: ask ""
print arg-str
```
crashes with "access violation" message on Linux and Windows:
```
Z:\adapter_test>adapter.exe

*** Runtime Error 1: access violation
*** at: 0041F70Dh
```

**To reproduce**
Compile the script with `-r` option and execute.

**Expected behavior**
Version of the script using `read-stdin` function compiles and executes as expected under both Windows and Linux:
```
Red [File: %adapter.red]
#include %red-github/environment/console/CLI/input.red
input: copy #{}
until [
	buff: copy #{}
	read-stdin buff 10
	append input buff
	0 >= length? buff
]
print to string! input
```

**Platform version (please complete the following information)**
```
(Arch Linux)
Red 0.6.4 for Linux built 25-Mar-2019/12:11:08+02:00 commit #e6c96aa
(Win7)
Red 0.6.4 for Windows built 1-May-2019/20:32:06+02:00 commit #8d712e4
```

**Comment by loziniak** [comment]
Bug is connected with #3872

**Comment by loziniak** [comment]
It crashes also with latest version - `red-13may19-973dcd65`

**Comment by loziniak** [comment]
It still crashes under Linux.

**Comment by qtxie** [comment]
@loziniak Hmm, I missed it. Will fix it on Linux soon.

**Comment by qtxie** [comment]
It works fine on Ubuntu Linux. I'll try to run it on Arch Linux in the next days.

**Comment by qtxie** [comment]
I still cannot reproduce the crashes under Linux. Does anyone has the same issue?

**Comment by loziniak** [comment]
Under Arch it works ok with `red-08jun19-1b68168a`
