### ISSUE TITLE
[Compiler] Script file names with spaces result in a wrong exe name

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3875]
**Describe the bug**

```
>red -c "prog ram.red"
...
...output file      : ...\prog.exe

>rebol -s --do "do/args %red.r {\"prog ram.red\"}"
...
...output file      : ...\prog.exe
```

**Expected behavior**

`prog ram.exe` is expected to be written

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 1-May-2019/21:32:06+03:00 commit #8d712e4
```

**Comment by greggirwin** [comment]
Is this related to https://github.com/red/red/pull/3870 ?

**Comment by hiiamboris** [comment]
@greggirwin Not in the sense "caused" or "fixed" by it, no.
