### ISSUE TITLE
Problem with date calculations for 29-Feb

### ISSUE THREAD

**Issue by meijeru** [red/red#3881]
**Describe the bug**
Changing the `/year` component of a valid `29-Feb` date yields an invalid date.
**To reproduce**
```
>> d: 29-Feb-2020
== 29-Feb-2020
>> d/year: d/year - 1
== 2019
>> d
== 29-Feb-2019
```
**Expected behavior**
```
== 1-Mar-2019
```
**Platform version (please complete the following information)**
```
All
```

**Comment by greggirwin** [comment]
R2 converts it to 1-Mar-2019 if you do that.

**Comment by greggirwin** [comment]
Looks like it normalizes if you set the month or the day.

**Comment by meijeru** [comment]
Apparently, normalization is not invoked when the year is set, then?

**Comment by dockimbel** [comment]
@meijeru Correct.
