### ISSUE TITLE
Failed to access GUI api on linux from GTK branch

### ISSUE THREAD

**Issue by beenotung** [red/red#3888]
**Describe the bug**
I am on the current GTK branch (last commit: c494addcb21b583c0b108ce33a8531df5131ca8f) . I am trying to use GUI feature in red on linux but failed.

When I build the CLI console, it said:
```
$ ./console
--== Red 0.6.4 ==-- 
Type HELP for starting information. 

>> view []
*** Script Error: view has no value
*** Where: catch
*** Stack:  

```
when I build GUI console, it said:
```
$ ./gui-console
*** Runtime Error 1: access violation
*** at: 08126A88h
```

**To reproduce**
1. Clone the red repo
2. Checkout the GTK branch
3. Launch the rebol console
4. Run `do/args %red.r "-r %environment/console/CLI/console.red"`
5. Quit the rebol console
6. Run the red cli console `./console`
7. Run `view []`
> Result: Failed, as above description
8. Launch the rebol console
9. Run `do/args %red.r "-r %environment/console/GUI/gui-console.red"`
10. Quit the rebol console
11. Run the red gui console `./gui-console`
> Result: Failed, as above description

**Expected behavior**
1. The view module should be loaded for red.
2. The GUI console should be able to launch without error.

**Platform version (please complete the following information)**
Red about:
```
Red 0.6.4 for Linux built 22-May-2019/12:37:26+08:00
```
OS: Archlinux 64-bit (lib32-gtk3 installed)
WM: awesome v4.3 (Compiled against Lua 5.3.5)

**Comment by rebolek** [comment]
You need to build `%environment/console/CLI/console-vie.red` or manually add `Needs: View` to header.

**Comment by meijeru** [comment]
If @rebolek 's suggestion is the solution, this is not an issue proper, in fact.

**Comment by rebolek** [comment]
Right, this is not an issue, CLI console is not meant to be able to run View scripts. `console-view.red` is workaround for GTK version, as GUI console doesn't work there yet.
Also I believe that GTK problems should be reported to https://github.com/rcqls/red as it's community effort, not official Red branch.

**Comment by meijeru** [comment]
@greggirwin For your attention.

**Comment by dockimbel** [comment]
@rebolek Correct, GTK-related issues should be opened in https://github.com/rcqls/red repo for now.
