### ISSUE TITLE
Restrict `compose` to block arg

### ISSUE THREAD

**Issue by greggirwin** [red/red#3905]
**Describe the bug**

`Compose` allows any type in the spec, but the body only supports blocks. This was initially done to match R3, which acts as a pass-thru for non-block args, but Red behaves differently.

**To reproduce**
>> compose ""
*** Script Error: expected block! not string!
*** Where: compose
*** Stack:  

>> compose 1
*** Script Error: expected block! not integer!
*** Where: compose
*** Stack:  

**Expected behavior**

Should enforce block arg in spec.

**Platform version (please complete the following information)**

All

**Comment by endo64** [comment]
@greggirwin I think `FIX: ` in the title should go to a commit message :)

**Comment by greggirwin** [comment]
Fixed.

**Comment by dockimbel** [comment]
@greggirwin Is there anything else to do for this ticket or can it be closed now?

**Comment by greggirwin** [comment]
Should be good to go.
