### ISSUE TITLE
Wrong error message when using foreach wrongly on map

### ISSUE THREAD

**Issue by meijeru** [red/red#3910]
**Describe the bug**
`foreach` on a map value should provide a block of 2 words as counters. If only one word is given, the error message is not clear and even misleading

**To reproduce**
```
>> m: #(a: 1)
== #(
    a: 1
)
>> foreach p m []
*** Script Error: foreach does not allow map! for its 'word argument
*** Where: foreach
```

**Expected behavior**
```
*** Script Error: foreach requires a block of 2 words for its 'word argument
```

**Platform version (please complete the following information)**
```
all
```

**Comment by greggirwin** [comment]
Good catch. It's better, but can't be entirely specific without adding a new error, if you use a block:
```
>> m: #(a: 1)
== #(
    a: 1
)
>> foreach p m []
*** Script Error: foreach does not allow map! for its 'word argument
*** Where: foreach
*** Stack:  

>> foreach [p] m []
*** Script Error: invalid argument: [p]
*** Where: foreach
*** Stack:  
```

**Comment by meijeru** [comment]
I look forward to that better error message (combined with better testing in the toolchain, if needed).

**Comment by meijeru** [comment]
On closer inspection, the tests for erroneous first argument to `foreach` are not done in the main code (`foreach*` in `natives.reds`) but in the auxiliary functions `foreach-next-block` and `foreach-next`. This may have been an effective approach *before* extension to maps, but is currently more inconvenient. A redesign would be neceessary which I am not ready to undertake.

**Comment by 9214** [comment]
Related: https://github.com/red/red/issues/617
