### ISSUE TITLE
cannot install Red into Ubuntu 18.04 WSL under Windows 10 Home

### ISSUE THREAD

**Issue by mxdpeep** [red/red#3919]
1. I have added the libraries
> apt-get install libc6:i386 libcurl4:i386

2. when trying to run the downloaded binary
> cannot execute binary file: Exec format error

**Comment by mxdpeep** [comment]
We don’t currently have plans to support running ELF-32 binaries on WSL x64.

**Comment by rebolek** [comment]
It seems that WSL doesn't support 32bit apps: https://github.com/Microsoft/WSL/issues/2468

**Comment by mxdpeep** [comment]
> It seems that WSL doesn't support 32bit apps: [microsoft/WSL#2468](https://github.com/microsoft/WSL/issues/2468)

makes sense 👍
