### ISSUE TITLE
MOLD produces invalid bitset

### ISSUE THREAD

**Issue by giesse** [red/red#3950]
The output of `mold` for "complemented" bitsets cannot be used to re-create the bitset.

```
>> mold charset "A"
== "make bitset! #{000000000000000040}"
>> do mold charset "A"
== make bitset! #{000000000000000040}

>> mold complement charset "A"
== "make bitset! [not #{000000000000000040}]"
>> do mold complement charset "A"
*** Internal Error: reserved for future use (or not yet implemented)
*** Where: make
*** Stack:  

>> about
Red 0.6.4 for Linux built 27-Jul-2019/12:09:49-10:00
```
(current master branch)

**Comment by meijeru** [comment]
This has nothing to do with `mold`. Try `make bitset! [not {000000000000000040}]`.

**Comment by giesse** [comment]
@meijeru if `[not #{...}]` is not allowed, then clearly `mold` should not generate such output. If it is supposed to be allowed, then this is a bug in `make bitset!` (more likely).

Still, the statement is true that the output of `mold` is not usable right now (which is my problem, since I'm saving code to a file and then trying to load it back).
