### ISSUE TITLE
Regression: parse-macros don't get substituted anymore

### ISSUE THREAD

**Issue by hiiamboris** [red/red#3951]
:point_up: [July 27, 2019 2:11 PM](https://gitter.im/red/bugs?at=5d3c316c8aab922429ccc272)

**Describe the bug**
Somewhere after July 1st and before July 23rd parse-pattern macros got broken.

**To reproduce**
run this code with `red --cli 1.red` or as `do %1.red`:
```
Red []
#macro [path!] function [s e] [print ["ATE" s/1] []]
invalid/path
```
It displays: 
```
*** Script Error: invalid has no value
*** Where: catch
*** Stack:
```

**Expected behavior**
It should display `ATE invalid/path`

**Platform version (please complete the following information)**
latest

**Comment by greggirwin** [comment]
https://github.com/red/red/commit/6e3a460d29153bed585efbd16041e5ab1754e9db is parse related. If not there, then in the batch of regression fixes perhaps.

**Comment by 9214** [comment]
OTOH, `expand [#macro path! func [s e][[]] a/b]` works as expected, so this issue seems to be related to file preprocessing only.

**Comment by 9214** [comment]
I also vaguely recall having a similar issue back in Februrary when testing https://github.com/red/red/issues/3771, but at that time I ruled it out as a PEBKAC on my side.

**Comment by dockimbel** [comment]
@hiiamboris As the macros are mostly useful for compilation, the interpreter does not run the preprocessor by default. So when you interpreter the script from command-line or using `do`, macros won't get expanded. `do` has an `/expand` refinement for that, or you can use the `expand` function shortcut:
```
>> #macro [path!] function [s e] [print ["ATE" s/1] []]
== func [s e][print ["ATE" s/1] []]
>> invalid/path
*** Script Error: invalid has no value
*** Where: catch
*** Stack:  

>> expand [#macro [path!] function [s e] [print ["ATE" s/1] []]
[    invalid/path]
ATE invalid/path
[]
== []
```
I don't remember the macros ever get expanded by default from the interpreter, but my memory could be wrong there.

**Comment by 9214** [comment]
@dockimbel nethertheless, this doesn't explain the following heisenbug. Here's an old build from May:
```red
>> about
Red 0.6.4 for Windows built 14-May-2019/21:12:30+05:00 commit #587a64a

>> expand [#macro word! func [s e]['OK] WTF]()
[OK]
>> expand [[] #macro word! func [s e]['OK] WTF]()
[[] OK]
>> expand [#macro word! func [s e]['OK] WTF []]()
[OK []]
```

Everything works as expected. Now, compare it with the fresh build:
```red
>> about
Red 0.6.4 for Windows built 8-Aug-2019/12:28:05+05:00 commit #2331e25

>> expand [#macro word! func [s e]['OK] WTF]()
[OK]
>> expand [[] #macro word! func [s e]['OK] WTF]()
[[] WTF]
>> expand [#macro word! func [s e]['OK] WTF []]()
[OK []]
```

**Comment by dockimbel** [comment]
@9214 Indeed. Do you have any clue about which commit created the regression?
