### ISSUE TITLE
`event/ctrl?` and `event/shift?` not set on `down` event

### ISSUE THREAD

**Issue by toomasv** [red/red#3955]
**Describe the bug**
`event/ctrl?` and `event/shift?` are not set on `down` event. Neither are set corresponding flags

**To reproduce**
```
>> view [base on-down [print [event/ctrl? event/shift? event/flags]]]
false false 
false false 
false false 
```

**Expected behavior**
As previously:
```
>> view [base on-down [print [event/ctrl? event/shift? event/flags]]]
true false control
false true shift
true true control shift
>> about
Red 0.6.4 for Windows built 21-May-2019/3:23:06+03:00 commit #c80ba51
```

**Platform version (please complete the following information)**
```
>> about
Red 0.6.4 for Windows built 30-Jul-2019/9:19:01+03:00 commit #3f14bf4
```

**Comment by toomasv** [comment]
Same for `on-mid-down` and `on-alt-down`. Neither do any `on-key` events work.

**Comment by bitbegin** [comment]
macOS ok, windows failed.

**Comment by hiiamboris** [comment]
I can confirm this issue on W8.1
