### ISSUE TITLE
Compiling -r fails while -c succeeds

### ISSUE THREAD

**Issue by ralfwenske** [red/red#3959]

**Comment by ralfwenske** [comment]
A view app with a reactor leads may be
- interpreted: it works (shows a view, on button click does some processing )
- compiled -c: it works (shows a view, on button click does some processing )
- compile -t macOS -r: compiler error
```
*** Compilation Error: word with not defined in react/with 
*** in file: /Users/ralfwenske/Dropbox/red-test/test-objects.red
*** near: [react/with blk ctx]
```
after removing all react stmts:
compiled -t maOS -r: it works partly (shows view but does not respond to button click)
putting back in two lines:
```
win-size: 1200x800
react: make reactor! [w-size: win-size]
```
compile -t macOS -r: results in:
same compiler error as above.

**To reproduce**
copy following code and run those three variations (interpreter, -c, -t)
then search for and comment out all `react` -statements
and repeat
finally uncomment the first `react` statement
and repeat

**Expected behaviour**
Compiler should behave identical between `-c` and `-r` mode

**Platform**
Red 0.6.4 for macOS built 24-Jul-2019/5:51:39+10:00 commit #613d71c

**Code**
Red [ needs: 'view ]

win-size: 1200x800
react: make reactor! [w-size: win-size]     ;comment this and -t compiles
so: ""
win: layout compose [
    title "Compiler Tests with red-lang"
    size win-size backdrop yellow
    below
    h2 "Red Compiler Tests"
    w-panel: panel red   [        
        below
        b: button "Run Tests" [      
            area1/text:  "test area1 after button click"
            area2/text: rejoin ["test area2 after button click" newline]
        ]
    ]  react [face/size: as-pair react/w-size/x - 20 50]
    w-tab-panel: tab-panel [
        "First" [
            area1: area 580x250 font-name "courier" font-size 12 
            react [face/size: face/parent/parent/size - 40x80]
        ]
        "Second" [
            area2: area 580x250 font-name "courier" font-size 12  
            react [face/size: face/parent/parent/size - 40x80]
        ]
    ] react [face/size: as-pair react/w-size/x - 10 react/w-size/y - w-tab-panel/offset/y - 20 ]
]

view/flags/no-wait win 'resize
insert-event-func [
    case [
        event/type = 'close [
            quit
        ]
        event/type = 'resizing [
           react/w-size: win/size
        ]
    ]
]
win/size: win/size + 0 ;trigger a first resize
do-events

**Comment by endo64** [comment]
I confirm that compiling with `-r` fails on Win10 too.
```
D:\Projects\Red\red\build\bin>red -r test.red

-=== Red Compiler 0.6.4 ===-

Compiling D:\Projects\Red\red\build\bin\test.red ...
*** Compilation Error: word with not defined in react/with
*** in file: D:\Projects\Red\red\build\bin\test.red
*** near: [react/with blk ctx]
```

**Comment by dander** [comment]
Is overriding the `react` function intentional? It seems like that could cause problems, and have differing compilation/interpretation behavior.

**Comment by greggirwin** [comment]
I think @dander may have nailed it. See https://github.com/red/red/wiki/%5BDOC%5D-Guru-Meditations#compiled-versus-interpreted-behaviors for some basic notes on differences when compiling and overriding functions. e.g., something in Red is calling `react/with`, but you've made it an object, not a function, so that code is broken by your override.

**Comment by ralfwenske** [comment]
I just followed the first sample in the blog `0.6.1: Reactive Programming` . How do I make it a function? Is there sample code somewhere? Or does it mean we can't use reactor in release mode?

**Comment by ralfwenske** [comment]
I had followed @greggirwin 's help ☝️ July 29, 2019 2:48 PM
but now I realise that for my purpose (view resizing) I don't need the `reactor!` at all.
In the above source I removed the reactor, replaced all `react/w-size` with `face/parent` and it works in `-r` mode. Great.
Should I close this issue? 
The questions if `-c` and `-r` compilations may differ seems still open.

**Comment by greggirwin** [comment]
I think this ticket can be closed.

**Comment by ralfwenske** [comment]
Closed

⁣Sent from BlueMail ​
