### ISSUE TITLE
[macOS] `layout/parent` causes access violation

### ISSUE THREAD

**Issue by nulldatamap** [red/red#3980]
**Describe the bug**
The usage of `layout/parent` in this specific context results in an access violation.

**To reproduce**
Running the following code:
```red
Red [needs 'view]

view [
	panel on-down [
		layout/parent compose [
			text "A: " text "B"
		] crash-box none
	]
    crash-box: group-box []
]
```
Then clicking on the panel, results:
```
*** Runtime Error 1: access violation
*** at: A6C1CF13h
```

**Expected behavior**
The face tree to be built and added to `crash-box` without crashing.

**Platform version**
```
Red 0.6.4 for macOS built 9-Aug-2019/10:17:57+02:00 commit #8a9920e
```

**Comment by 9214** [comment]
Cannot reproduce on W10.

**Comment by dockimbel** [comment]
Cannot reproduce on W7 either, seems to be macOS-specific.

**Comment by hiiamboris** [comment]
reminds me of https://github.com/red/red/issues/3762 , although that one crashes on Windows.

**Comment by 9214** [comment]
@hiiamboris would be great if anyone with macOS compared stack dumps.
