### ISSUE TITLE
[RPi] LOAD on a very long float literal will crash

### ISSUE THREAD

**Issue by dockimbel** [red/red#4000]
@dockimbel I have isolated the test in load-test.red the is giving a segmentation fault:

```text
--test-- "load-41"	--assert "1.0e23"		= mold load "0.99999999999999999999999999999999999999999e+23"
```

Here is confirmation in a Red console running on ARM:
```text
>> mold load "0.99999999999999999999999999999999999999999e+23"
Segmentation fault

```

_Originally posted by @PeterWAWood in https://github.com/red/red/issues/3352#issuecomment-401671356_

**Comment by dockimbel** [comment]
```
load "0.99999999999999999999999999999999999999999e+23"
```
is enough to reproduce the crash.

**Comment by qtxie** [comment]
Looks like a regression. It works fine in an old version of the console (built on Jul 1).

**Comment by dockimbel** [comment]
Seems to be gone using latest commit from `atomic` branch. To be confirmed on master.

**Comment by dockimbel** [comment]
This issue is gone, so I'm closing this ticket.
