### ISSUE TITLE
Can't find how to clear Red Cli 

### ISSUE THREAD

**Issue by lepinekong** [red/red#4032]
Ctrl+L works in Red GUI Console not in Cli console and I can't find info anywhere

**Comment by 9214** [comment]
Please use dedicated [chat room](https://gitter.im/red/help) to ask your questions, and keep issue tracker for bug reports only.

[ANSI escape sequence](https://en.wikipedia.org/wiki/ANSI_escape_code) for clearing terminal screen is:
```red
print "^[[2J"
```

**Comment by endo64** [comment]
@lepinekong You can also use below function for CLI:

```
cls: func [][
    unless system/console/gui? [
        call/console pick ["cls" "clear"] 'Windows = system/platform
    ]
    prin ""
]
```

But as @9214 said better to ask questions on gitter or stackoverflow.

**Comment by greggirwin** [comment]
@lepinekong please find or create a good wiki page for the answers here, and add them. Thanks!
