### ISSUE TITLE
Read-clipboard doubles newline chars

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4055]
I have already fixed this issue. Just reporting it for historical reference.

**Describe the bug**

Text in the clipboard:
```
1
2
3
```
Let's try to read it:
```
>> print probe read-clipboard
{1^M^/2^M^/3^M^/}
1

2

3

```
As you can see every new-line appears twice.

This also has a very harmful effect:
```
>> length? read-clipboard
== 7
>> write-clipboard read-clipboard
== true
>> length? read-clipboard
== 9
```
It grows! ☻ 

Then `loop 10000 [write-clipboard read-clipboard]` will just crash it since memory footprint grows exponentially.

**Expected behavior**
```
>> print probe read-clipboard
{1^/2^/3^/}
1
2
3
```

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 25-Sep-2019/22:36:30+03:00 commit #f753e25
```

**Comment by greggirwin** [comment]
:+1: So I can close this?

**Comment by hiiamboris** [comment]
No, @greggirwin, not until I make a PR and it's accepted :)

**Comment by greggirwin** [comment]
Ah, I thought you meant you had fixed it in the past, and just created the ticket to doc the fact. Thanks.
