### ISSUE TITLE
MacOS terminal delay

### ISSUE THREAD

**Issue by ralfwenske** [red/red#4058]
MacOS: hitting return several times in terminal ( or worse: holding it down a few seconds ) causes long delay until >> shows again.

Alvydas Vitkauskas confirmed:
It also happens if you just keep Red console open for a few minutes without doing anything.

**Platform version**
```
Red 0.6.4 for macOS built 28-Sep-2019/2:46:20+10:00 commit #d0e6692
```

**Comment by hiiamboris** [comment]
It really became impossible to use.
Not so much as <Enter> triggers the bug but entering/pasting something a few times.
Then after each line display happens a 10 second delay (always the same).
And this delay stops in an instant when I activate or deactivate the terminal.

**Comment by rebred** [comment]
very very slow. 5 seconds or more when typing to get any feedback. unusable
