### ISSUE TITLE
Confusing error message on encountering $ inside block

### ISSUE THREAD

**Issue by meijeru** [red/red#4119]
I was formulating a parse rule for strings not incorporating a `$` sign. I would have liked to call the rule `non$` but `$` is not allowed in words. That is fair, but when such a non-word is inside a block, the interpreter gives a confusing error message. It should of course have been the same as for the first case.

```
>> non$
*** Syntax Error: invalid value at "$"
*** Where: do
*** Stack: load 
>> rule: [ any non$ "something else"]
*** Syntax Error: missing #"]" at "$]"
*** Where: do
*** Stack: load 

```

**Comment by greggirwin** [comment]
`\` as well. 
```
>> rule: [ any non\ "something else"]
*** Syntax Error: missing #"]" at {\ "something else"]}
*** Where: do
*** Stack: load 
```

**Comment by meijeru** [comment]
Most likely all non-allowed characters in `word!` values gives this confusing message, so it must be a single imperfection in the lexer. Given that the lexer is being redesigned, one should remember to test this with the new lexer as soon as it is in operation, so as to hopefully discard this issue then.

**Comment by 9214** [comment]
I propose we close it.

```red
>> $non
*** Syntax Error: (line 1) invalid money at $non
*** Where: transcode
*** Stack: load 
>> non\
*** Syntax Error: (line 1) invalid character at \
*** Where: transcode
*** Stack: load 
````

**Comment by meijeru** [comment]
I am OK with closing it if there are the tests I mentioned.

**Comment by theSherwood** [comment]
Tests were added. So I suspect that this can be closed.
