### ISSUE TITLE
Disable Red Console with interpreter

### ISSUE THREAD

**Issue by cup** [red/red#4150]
Using this script:

~~~
Red [
   Title: "Simple hello world script"
]
print "Hello World!"
~~~

I try to run like this:

~~~
red-064 hello.red
~~~

but a new window "Red Console" opens with the output, instead of outputting to
my current console. How do I resolve this?

**Comment by qtxie** [comment]
@cup `red-064 --cli hello.red`

**Comment by greggirwin** [comment]
@cup please ask questions on Gitter, rather than opening tickets for them. If a bug is confirmed, that'st the time to open a ticket. Thanks.
