### ISSUE TITLE
`find/same` doesn't properly find words

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4165]
**Describe the bug**

`find/same` is supposed to be using `same?` comparator, but when looking for a word it doesn't.
```
>> a: object [x: 1]
>> b: object [x: 2]
>> (in a 'x) == (in b 'x)
== true
>> (in a 'x) =? (in b 'x)
== false                    ;) words aren't "same" if bound to different contexts
>> xs: reduce ['x in a 'x in b 'x]
== [x x x]
>> find/same xs in a 'x
== [x x x]                  ;) should be [x x]
>> find/same xs in b 'x
== [x x x]                  ;) should be [x]
>> find/same xs next xs
== [x x x]                  ;) should be [x x]
>> select/same xs in b 'x
== x                        ;) should be none
```

**To reproduce**
```
a: object [x: 1]
b: object [x: 2]
(in a 'x) == (in b 'x)
(in a 'x) =? (in b 'x)
xs: reduce ['x in a 'x in b 'x]
find/same xs in a 'x
find/same xs in b 'x
find/same xs next xs
select/same xs in b 'x
```

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 27-Nov-2019/10:17:45+03:00 commit #b2aafe6
```

**Comment by 9214** [comment]
Examples are wrong.
```red
>> xs: reduce ['x in a 'x in b 'x]
== [x x x]
>> find/same xs in a 'x
== [x x x]                       ; expected: [x x]
>> find/same xs in b 'x
== [x x x]                       ; expected: [x]
>> find/same xs next xs
== [x x x]                       ; expected: [x x]
>> select/same xs in b 'x
== x                              ; expected: none
```

**Comment by hiiamboris** [comment]
Thanks @9214. Updated them now. I agree `find` should probably check refinements and report errors.

I compiled a refinement matrix for it some time ago:
![](https://i.gyazo.com/3f0b28c6fb006238c29f116aa59101d6.png)

**Comment by 9214** [comment]
@hiiamboris `/case` and `/same` are not mutually exclusive. The former is a case-sensitive comparison of symbols (spelling), the latter is a case-sensitive comparison of spelling, comparison of types and comparison of binding. So, `find/same` is already case-sensitive, and there is no need for extra `/case`, that's what I meant.

**Comment by hiiamboris** [comment]
That's "mutually exclusive" in my dictionary ;)

**Comment by greggirwin** [comment]
/same "Use `same?` as comparator; implies /case"

**Comment by hiiamboris** [comment]
I understand it may make sense to say so for characters, but it will be misleading for other data. `/case` is `==` and `/same` is `=?`, and when your data contains blocks or objects for example, or floats, these work totally differently.

**Comment by greggirwin** [comment]
I guess I need to revisit the differences. In order of increasing strictness, it should be: `equal? strict-equal? same?`, each implying that the previous is satisfied.

**Comment by hiiamboris** [comment]
Not at all. There's a lot of fun:
```
>> a: b: 0.0 / 0.0
== 1.#NaN
>> a = b
== false
>> a == b
== false
>> a =? b
== true
```

**Comment by greggirwin** [comment]
That seems an aberrant case, where `=?` should also be false. The IEEE spec says NaNs are never equal.

**Comment by hiiamboris** [comment]
And they are not *equal*. But `same?` compares bitwise, and I think rightfully so, since there are no other means to do it directly.

**Comment by 9214** [comment]
WRT original issue with `find/same`: `same?` (and by extension `=?`) is implemented as `native!` that does a raw comparison of slots' contents.

https://github.com/red/red/blob/02776dcf50c085b3fe9c207df88bdaceb8c5b3c0/runtime/natives.reds#L825-L830

But datatype-specific `compare` action does not necessarily follow this logic. `word!`, for example, conflates `COMP_SAME` and `COMP_STRICT_EQUAL` together, and ignores binding information completely.

https://github.com/red/red/blob/02776dcf50c085b3fe9c207df88bdaceb8c5b3c0/runtime/datatypes/word.reds#L482-L488

**Comment by hiiamboris** [comment]
2. is also `find/case`, right?

**Comment by 9214** [comment]
@hiiamboris hm... so we have 8 levels strictness: the above mentioned 4, each with a case-sensitive and case-insensitive comparisons.

**Comment by hiiamboris** [comment]
Indeed. Though we're limited to choose only 3 I guess, preferring consistency and usefulness. More fine grained comparison can be done by comparing spelling and binding separately.

**Comment by 9214** [comment]
`/case`, `/same` and hypothetical `/strict` should cover all of them I think. That's 2<sup>3</sup> = 8 combinations, applicable even outside of `word!` searching/comparison.

I'm reluctant to reserve `/case` for cases (no pun intended) where there is no casing yet a stricter form of comparison is required, like e.g. in https://github.com/red/red/issues/4327.

**Comment by hiiamboris** [comment]
`find/case/same/strict/only/skip/part block 'Word 2 end`... nowai :D

**Comment by 9214** [comment]
@hiiamboris [Eek!](https://user-images.githubusercontent.com/15716466/89556481-bc18b180-d811-11ea-8d8b-2f79318fb303.png)
