### ISSUE TITLE
MAKE hash! is painfully slow on repeating items

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4178]
**Describe the bug**

```
>> append/dup b: [] 0 100'000
>> make hash! b
```
Takes a few minutes...

**Expected behavior**

I realize hash! loses any advantage on this particular sample ;) Yet, it should offer some degree of universality. In R2 the same operation is instantaneous. As it should be in Red.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 27-Nov-2019/10:17:45+03:00 commit #b2aafe6
```

**Comment by qtxie** [comment]
It's a known issue. https://github.com/red/red/pull/4026

**Comment by hiiamboris** [comment]
I see. Closing ;)
