### ISSUE TITLE
Escape key on CLI console doesn't clear input buffer

### ISSUE THREAD

**Issue by endo64** [red/red#4189]
**Describe the bug**
Pressing Escape key on CLI console during writing a refinement doesn't clear the buffer correctly.

**To reproduce**
1. Open CLI console
2. Type a function name and part of a refinement of it
3. Press TAB key to complete
4. Press Escape key

Input buffer is cleared just after the position where the tab key pressed.

**Expected behavior**
Console input buffer should be cleared completely.

**Screenshots**
![red-console](https://user-images.githubusercontent.com/840604/70948453-8c435080-206c-11ea-9075-ddd101d008e6.gif)

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 17-Dec-2019/0:33:50+03:00 commit #847ede2
```

**Comment by hiiamboris** [comment]
Works for me on `Red 0.6.4 for Windows built 12-Dec-2019/11:14:17+03:00 commit #61d4d36`

**Comment by loziniak** [comment]
Confirmed in Arch Linux, branch GTK commit #d89f33b100c051ed

**Comment by endo64** [comment]
I'm on Win10, @hiiamboris you tested on W7 right? @greggirwin also confirmed the issue, he is also on Win10 I assume.
@loziniak Yes, error happens because I pressed enter key not related to the issue (just to be sure that it is not just a visual artifact)

**Comment by hiiamboris** [comment]
Right

**Comment by hiiamboris** [comment]
Duh! I only now noticed it's **CLI** console where this bug appears. Confirmed on W7 then ;)
