### ISSUE TITLE
[Parse] KEEP PICK PAREN! semantics is undefined

### ISSUE THREAD

**Issue by 9214** [red/red#4198]
**Describe the bug**

Title. `keep pick <expression>` in Parse is allowed but has no effect.

**To reproduce**

```red
>> parse [][collect keep pick ('a)]
== []
>> parse [][collect keep pick ([a b])]
== []
```

**Expected behavior**

Per discussion with @dockimbel, it should be the same as `keep <expression>`:

```red
>> parse [][collect keep pick ('a)]
== [a]
>> parse [][collect keep pick ([a b])]
== [[a b]]
```

**Platform version (please complete the following information)**

The latest build, all platforms.

**Comment by gurzgri** [comment]
Current `keep pick ([ ... ])` behaviour has the following asymmetry:

```Red
>> collect [parse [] [(keep [value]) (keep/only [block])]] ;== [value [block]]
```
```Red
>> parse [] [collect [keep pick ([value]) keep ([block])]] ;== [[value] [block]]
```

The latter offers no way to collect the values of a block instead of keeping the block as a value.

**Comment by dockimbel** [comment]
Implemented!
