### ISSUE TITLE
unable to execute ./red: Bad CPU type in executable

### ISSUE THREAD

**Issue by tealin** [red/red#4216]
System environment 

mac OS Catalina

型号名称：	MacBook Pro
  型号标识符：	MacBookPro14,1
  处理器名称：	Dual-Core Intel Core i5
  处理器速度：	2.3 GHz
  处理器数目：	1
  核总数：	2
  L2缓存（每个核）：	256 KB
  L3缓存：	4 MB
  超线程技术：	已启用
  内存：	8 GB
  Boot ROM版本：	203.0.0.0.0
  SMC版本（系统）：	2.43f7
  序列号（系统）：	FVFWD4APHV29
  硬件UUID：	70A10CC6-9C14-539A-855D-84C6F4AD6701

error:unable to execute ./red: Bad CPU type in executable

**Comment by greggirwin** [comment]
Catalina is not currently supported. Please join us on gitter.im/red/red to determine if something is ticket worthy.
