### ISSUE TITLE
[R/S] Float by integer division is bugged

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4224]
**Describe the bug**

```
Red/System []
s: 1
e: 2
f: as float32! 3.0
g: 3.0
probe f / (e - s)
probe g / (e - s)
```
Output:
```
-1.#IND.0
-1.#IND.0
```
Happens only when dividing by integer expression. `/ (s)` or `/ 1` work fine.

**Expected behavior**
```
3.0
3.0
```

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 27-Dec-2019/1:01:27+03:00
```

**Comment by hiiamboris** [comment]
Any kind of promotion doesn't work properly either:
```
probe f / as float32! (e - s)
probe g / as float! (e - s)
```
Output:
```
0.3333333         
0.3333333333333333
```
Or rather - it works backwards - dividing the second operand by the 1st

**Comment by dockimbel** [comment]
Doing such math operation without explicit type casting is not a supported feature in R/S currently.

**Comment by hiiamboris** [comment]
According to R/S spec:
> The resulting value type for math operators is the type of the left argument (an implicit type casting is operated when required).

Perhaps the spec should be clarified then.

**Comment by hiiamboris** [comment]
There's more to this bug. Not only there's a wrong result, but it causes certain undefined behavior - local variables become filled with trash and it leads to a crash in the end.

Can't point to an exact line as the amount of trash grows gradually, but here's a snippet that crashes: https://gitlab.com/snippets/1933695

If you inspect the output of it, it starts with extreme floating point values (e-300, e+160..) which are not produced by the algorithm, and then integer values become extreme too, then assertions fail, or (if you don't use the `-d` flag, it just crashes).
