### ISSUE TITLE
decode-url doesn't handle `a:b` which is valid.

### ISSUE THREAD

**Issue by greggirwin** [red/red#4242]
**Describe the bug**
`a:b` is a valid URL, but the %networking.red url parser doesn't recognize it.

see: https://gitter.im/red/bugs?at=5e179e84e52f635378b239f6

**To reproduce**
`decode-url a:b`

**Expected behavior**
Return decoded URL object.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 8-Jan-2020/13:51:56-07:00 commit #e26452d
```

**Comment by 9214** [comment]
I can see that the fix was implemented, so maybe it's time to make a PR?
