### ISSUE TITLE
[View] CHECK treats NONE as truthy

### ISSUE THREAD

**Issue by 9214** [red/red#4245]
**Describe the bug**

Setting `data` facet of `check` face to `none` switches it to a toggled state.

**To reproduce**

```red
view [c: check data none button [c/data: none]]
```

Note that pre-setting it with `none` has no effect, facet needs to be set after low-level instantiation of the face. This issue affects all View backends.

**Expected behavior**

In fact, `none` is supposed to indicate the 3rd state for a tri-state checkbox. This functionality is available on all platforms (see [here](https://github.com/red/red/issues/4244#issuecomment-575745396)), but currently is not properly implemented.

**Platform version**

The latest release, all platforms.

**Comment by hiiamboris** [comment]
hmm... is there a principal difference between this and #4244 I'm missing?

**Comment by 9214** [comment]
@hiiamboris #4244 addresses `radio`/`check` face initialization before OS resources are allocated for it (i.e. just pre-filling object's fields with some data), this one is about setting `check`'s `data` facet _after_ these resources were allocated (i.e. face is fully instantiated and reacts to user interactions at runtime).
