### ISSUE TITLE
crash when parsing corrupted float

### ISSUE THREAD

**Issue by loziniak** [red/red#4250]
In Red console I get this error when trying to parse truncated `float!` string, and console crashes:
```
>> to float! "12e4"
== 120000.0
>> to float! "12e"

*** Runtime Error 1: access violation
*** in file: /home/devel/prj/red/gtk/red-github/runtime/dtoa.reds
*** at line: 1334
***
***   stack: red/dtoa/parse-exponent 08457000h 081E00BEh
***   stack: red/dtoa/to-float 081E00BBh 081E00BEh FFACD93Ch
***   stack: red/string/to-float 081E00BBh 3 FFACD93Ch
***   stack: red/tokenizer/scan-float F5398EE3h 3 1 FFACD93Ch
***   stack: red/float/to 09A2D854h 09A2D864h 12
***   stack: red/actions/to 09A2D854h 09A2D864h
***   stack: red/actions/to*
***   stack: red/interpreter/eval-arguments F553A7E0h F5398E58h F5398E58h 00000000h 00000000h
***   stack: red/interpreter/eval-code F553A7E0h F5398E38h F5398E58h false 00000000h 00000000h F553A7E0h
***   stack: red/interpreter/eval-expression F5398E38h F5398E58h false false false
***   stack: red/interpreter/eval 09A2D824h true
***   stack: red/natives/catch* true 1
***   stack: ctx||512~try-do F7F229ECh
***   stack: ctx||512~do-command F7F229ECh
***   stack: ctx||512~eval-command F7F229ECh
***   stack: ctx||512~run F7F229ECh
***   stack: ctx||512~launch F7F229ECh
***   stack: ctx||529~launch F7F22530h
***   stack: ***_start
```
Instead crash I'd expect an informative error message.

Platform: `Red 0.6.4 for Linux built 10-Jan-2020/15:13:57+01:00`

**Comment by 9214** [comment]
Parsing and scanning (tokenizing) are two different things. @qtxie ☝️ I think you did some work on `dtoa` refactoring in `fast-lexer` branch? Worth addressing it there.

**Comment by loziniak** [comment]
So, the error happens when this `float!` is tokenized, not parsed, as `red/dtoa/parse-exponent` method would suggest? I'd say that float is already a token, so it's processing can be called parsing. Although one could argue, that float token is itself composed of tokens – coefficient end exponent, right. It's so complicated... Thanks for explanation.

**Comment by 9214** [comment]
From the outset, the issue's title suggested that there's something wrong with Parse or lexer itself, while in fact it's specific to low-level tokenizers that are only partially implemented.

**Comment by qtxie** [comment]
FYI. Fixed in fast-lexer branch.

**Comment by hiiamboris** [comment]
Needs a regression test written and we can close it afterwards.
