### ISSUE TITLE
GTK: set-focus does not work

### ISSUE THREAD

**Issue by loziniak** [red/red#4251]
After running this script, messages should be printed to the console, when clicking on a button and then pressing keys on a keyboard:
```
view [
    button "give focus to blue rectangle" [set-focus bb]
    bb: base blue on-key-down [print "Message: I'm blue!"]
]
```
It works fine in Windows (Wine), but fails in Linux.

Platform: `Red 0.6.4 for Linux built 10-Jan-2020/15:13:57+01:00`

**Comment by bitbegin** [comment]
@loziniak can't set-focus on `base` widget, because macOS/gtk3 not support set-focus on some widgets

**Comment by bitbegin** [comment]
https://github.com/red/red/issues/2820

**Comment by loziniak** [comment]
Perhaps Windows implementation should be updated then to keep constant behavior?

**Comment by 9214** [comment]
@bitbegin both W10 and macOS 10.14 react to keystrokes as expected.

> updated

@loziniak "degraded" rather, in the light of the above.

**Comment by loziniak** [comment]
It could be a better word, indeed. Thanks for testing on macOS, I was just depending on what bitbegin wrote.

**Comment by qtxie** [comment]
@bitbegin We should be able to `set-focus` on base face. We have fully control on `base` face. 

A widget has `focus` just means it's capturing the keyboard input. Some OS standard widgets don't accept keyboard input, that's why we cannot set focus on them. That's fine as set focus on those widgets is useless.

**Comment by loziniak** [comment]
Giving focus to `base` or `panel` would allow them to receive keyboard events. It'd be nice to have this, for example when writing own custom widgets.

**Comment by hiiamboris** [comment]
Seems the above statement 
> because macOS/gtk3 not support set-focus on some widgets

is incorrect. When I run `red` in WSL2 and start fresh xserver, `view [base focus on-key [probe event/key]]` works for me and when I type `a s d f left right up down` it prints: 
```
>> view [base focus on-key [probe event/key]]
asdf^[[D^[[C^[[A^[[B
```
So it is supported by GTK.
However keys printed are invalid for Red (all extended keys seem to produce escape sequences).
And all further attempts to focus `base` fail, until I restart xserver when it works once again.

**Comment by hiiamboris** [comment]
I raise the priority for this issue is fundamental to Linux keyboard support in https://gitlab.com/hiiamboris/red-spaces project

**Comment by gltewalt** [comment]
I believe that  #4917 fixes this issue.
