### ISSUE TITLE
CLEAN-PATH/ONLY returns empty file! for files without path

### ISSUE THREAD

**Issue by rebolek** [red/red#4258]
`clean-path/only` cleans `%./` part of path. However, if no such part of path is present, `clean-path` returns empty file. It should leave the file as is in such case.

**To reproduce**

```
>> clean-path/only %asdf
== %""
;; %asdf ; -- expected
>> clean-path/only/dir %asdf
== %""
;; %asdf/ ; -- expected
```

**Platform version**

Latest Red on all platforms

**Comment by greggirwin** [comment]
:+1: Please add a test for this as well, to catch future regressions.

I hadn't looked at `clean-path` in a while. Is `/dir` needed? Just wondering what the use cases are, where it isn't just as easy to spec a dir as the value.

**Comment by greggirwin** [comment]
And maybe while you're head is in this function, look at https://github.com/red/red/issues/3571

**Comment by greggirwin** [comment]
Ah, tests running now. You beat me to it. Thanks.

**Comment by rebolek** [comment]
> Is /dir needed? Just wondering what the use cases are, where it isn't just as easy to spec a dir as the value.

That's out of the scope of this PR. It probably has its value, I guess, even if I haven't used it in a while (ever?). `clean-path` would need more attention anyway, as there's still an open issue with `url!`.

**Comment by meijeru** [comment]
"there's still an open issue with url!" indeed see #3571

**Comment by x8x** [comment]
Doesn't work for this case:
```
clean-path/only %../path/../file
;   %../path/../file
```
I had a quick go at an alternative that should solve all current issues (and maybe add some new ones.. )
It's here https://gist.github.com/x8x/612e9fa77378b93d98f0cf19ed27c215

Also, we have `dirize`, we should probably have `undirize` as well.
