### ISSUE TITLE
`halt` & generally `catch` lead to invalid error messages

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4260]
**Describe the bug**

First error message after `halt` is misleading. It makes debugging more annoying.
Note `body`:
```
(halted)
>> c/f 1
*** Script Error: body does not allow integer! for its x argument
*** Where: f
*** Stack:

>>
>> c/f 1
*** Script Error: f does not allow integer! for its x argument
*** Where: f
*** Stack:
```

All subsequent error messages will be okay

**To reproduce**

1. Run this script with GUI console
```
Red []
c: object [f: function [x [object!]][]]
halt
```
2. Type `c/f 1`
3. Observe `none` instead of `f`

**Expected behavior**

Valid error messages

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 27-Dec-2019/1:01:27+03:00
```

**Comment by meijeru** [comment]
In my trial the first function reported is `=` instead of `body`. So I suppose that it is somewhat random. Note: I types directly into console, not using a file with `Red []` in front.

**Comment by hiiamboris** [comment]
Yes, that's even simpler:
```
c: object [f: function [x [object!]][]]
halt
c/f 1
```
Thanks

**Comment by hiiamboris** [comment]
```
>> catch [throw 1]
== 1
>> add none none
*** Script Error: all does not allow none! for its value1 argument
*** Where: add
*** Stack:  
```
