### ISSUE TITLE
[GTK] showing modal window blocks GUI console input

### ISSUE THREAD

**Issue by 9214** [red/red#4276]
**Describe the bug**

Displaying and closing modal window renders the GUI console input area unresponsive.

**To reproduce**

From the GUI console, type `view/flags [] 'modal` and close the popped up window. Note that you cannot type anything in the console after that.

**Expected behavior**

I expect the GUI console to be fully responsive after the modal window is closed.

**Platform version**

The latest build from GTK branch.

**Comment by hiiamboris** [comment]
that's not GTK-specific
https://github.com/red/red/issues/3942#issuecomment-579964271

**Comment by 9214** [comment]
@hiiamboris neither W10 nor macOS have this behavior, so you should clarify that it's W7-specific.

**Comment by bitbegin** [comment]
need find a way to get the focus widget of a window, for example: put the focus widget handle to pane/status

**Comment by qtxie** [comment]
Fixed by commit e3692ffed5ad6c0e77bb7ce0549b7be80975b755 .
