### ISSUE TITLE
[Console] `?` is overworking a bit with long strings

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4290]
**Describe the bug**

`?` does not check the output length of `help-string`, neither `help-string` checks it's own output length. So, given a very long string it hangs console for minutes or crashes.

**To reproduce**

Do this in GUI console:
```
s: form draw 1920x1080 []
? s
```
It's unresponsive for ~2 min, after which becomes unusable or crashes.

**Expected behavior**

Output should be truncated to a sane length.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 31-Jan-2020/17:12:41+03:00 commit #414cdb3
```

**Comment by greggirwin** [comment]
Good catch.

**Comment by 9214** [comment]
@hiiamboris I propose to close this ticket in favor of #4464, which has a bit more contextual info to address the underlying problem.

**Comment by hiiamboris** [comment]
I don't know. Technically fix for either of these issues does not guarantee that another is solved. Let @greggirwin decide. He's probably fixed it locally anyway ;)
