### ISSUE TITLE
SAVE doesn't save an empty image

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4293]
**Describe the bug**

```
save/as %testimg.bmp make image! 0x0 'bmp
save/as %testimg.gif make image! 0x0 'gif
save/as %testimg.jpg make image! 0x0 'jpeg
save/as %testimg.png make image! 0x0 'png
```
All these commands produce a file of 0 bytes.

**Expected behavior**

I expect the result of such `save` to be loadable as `make image! 0x0`.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 31-Jan-2020/17:12:41+03:00 commit #414cdb3
```

**Comment by meijeru** [comment]
Of course `load/as` on an empty file could itself produce a `0x0` image as well.

**Comment by hiiamboris** [comment]
I'd prefer normal `load` to work too, but currently even `load/as` is failing:
```
>> read/binary %1
== #{}
>> load/as %1 'png
*** Access Error: cannot open: %1
*** Where: decode
*** Stack: load 
```

**Comment by meijeru** [comment]
The two issues may be connected, but even if they are not, they deserve to be resolved together, I would say.

**Comment by qtxie** [comment]
> I'd prefer normal `load` to work too, but currently even `load/as` is failing:
> 
> ```
> >> read/binary %1
> == #{}
> >> load/as %1 'png
> *** Access Error: cannot open: %1
> *** Where: decode
> *** Stack: load 
> ```

This is expected as the file is empty. It should at least include a PNG header otherwise the decode cannot recognize it.
