### ISSUE TITLE
Bad code in a console prompt kills the REPL

### ISSUE THREAD

**Issue by ralfwenske** [red/red#4301]
as detected by @greggirwin 

**To reproduce**
```
>> system/console/prompt: does [append now " >> "]
```
results in
== func [][append now " >> "]
*** Script Error: append does not allow date! for its series argument
*** Where: append
*** Stack: ask string? prompt 
macmini:~ ralfwenske$
```

**Expected behavior**
Console not crashing

**Platform version (please complete the following information)**
```
Red 0.6.4 for macOS built 13-Feb-2020/19:18:35+10:00 commit #d513c8f
```

Also see #3506 # 1953 #867 #1122

**Comment by greggirwin** [comment]
My test is on Win10, with the console crashing.

**Comment by loziniak** [comment]
Same in Linux. Kills both CLI and GUI consoles.

**Comment by loziniak** [comment]
↑↑↑
> Also see #3506 #1953 #867 #1122

(I repeat to generate ticket associations in GitHub)

**Comment by dockimbel** [comment]
It does not crash anymore, so I'm closing this ticket.

**Comment by dockimbel** [comment]
Actually, there's still an issue, the erroneous prompt should be discarded automatically by the console and fall back to the default prompt.
