### ISSUE TITLE
Error message on invalid argument in chained infix expression is off by one

### ISSUE THREAD

**Issue by 9214** [red/red#4311]
**Describe the bug**

When the unallowed operand is used in infix expression, `where` points to the operator leftmost to the actual culprit.

**To reproduce**

```red
>> 0 = 1 - 1
*** Script Error: = does not allow logic! for its value1 argument
*** Where: =
*** Stack:  
```

**Expected behavior**

```red
>> (0 = 1) - 1
*** Script Error: - does not allow logic! for its value1 argument
*** Where: -
*** Stack: 
```

**Platform version**

```
Red 0.6.4 for Windows built 27-Feb-2020/4:07:00+01:00 commit #bf15211
```

**Comment by hiiamboris** [comment]
Could be a part of a bigger picture, this: https://github.com/red/red/issues/4260 https://github.com/red/red/issues/3910
