### ISSUE TITLE
Windows platform back-end run question

### ISSUE THREAD

**Issue by VKingi** [red/red#4317]
Click exe and the program flashes by. How do I hide exe from running in the background?
I don't want to show a black window,Similar to Windows background service.
make a passing remark, Red got me a little excited,Thanks organization. ^^

**Comment by hiiamboris** [comment]
Compile it for Windows target (`-t Windows`). And please ask questions [in a proper place on Gitter](https://gitter.im/red/help) rather than on the tracker.

**Comment by 9214** [comment]
Hi @VKingi, thanks for taking interest in Red.

That's one of the frequent questions which is already [answered](https://github.com/red/red/wiki/%5BDOC%5D-Guru-Meditations#hide-the-cmd-window-popping-up-in-the-background-after-execution-of-compiled-red-script) in our Github wiki. Consider running a little search on it each time you stumble upon something or ask around in our community [chat](https://gitter.im/red/red/welcome). Cheers, and have fun!

**Comment by VKingi** [comment]
@hiiamboris @9214 thanks
