### ISSUE TITLE
[VID] Incorrect height inferrence from DROP-DOWN

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4334]
**Describe the bug**

Layout size does not stretch to account for `drop-down` size:
`view [drop-down font-size 50]`
![](https://i.gyazo.com/d3d44cbe4b77eb6a58035476f15d2d68.png)

**Expected behavior**

![](https://i.gyazo.com/9cefa6f7035934e732e674507ea03182.png)

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 10-Mar-2020/16:22:26+03:00
```

**Comment by qtxie** [comment]
Remember that on some platforms the height of some controls (drop-down, field, etc.) cannot be changed. For example on macOS the controls have very limited customization.

**Comment by greggirwin** [comment]
Then the question is whether we standardize to the lowest common denominator, for portability, or make each platform work the best it can, and user's have to know that not all behavior is portable. Not being a MacOS guy, how does XCode other others tell you that you can do that?

**Comment by henrikmk** [comment]
I don't think one should go for the lowest common denominator, as that will cause more problems than offering a workaround to affected platforms.

The lowest common denominator has to be coded and tested for, for every platform that Red supports, whereas workarounds only are for affected platforms.

The workaround can then be removed, once the platform support is rectified through OS changes or a custom widget is created that solves the problem.

**Comment by 9214** [comment]
Related: https://github.com/red/red/issues/1437

As @greggirwin said, we need to cut that knot and decide if we support the truly cross-platform feature subset or push each platform as far as it can go, noting the differences between them.

**Comment by qtxie** [comment]
The point of using a native GUI framework is making the APP follows the guidelines of the OS UI, not customize the widgets. We'd better to put our effort in a new customizable GUI framework, rather than hacking the native GUI.

**Comment by greggirwin** [comment]
I mostly agree with @qtxie, but I come back to my question: how does XCode other others tell you that you can do that? Do Mac developers expect this, and is it something we can fix with language. That is, in the docs, we just note this behavior and limitation.

**Comment by qtxie** [comment]
IIRC, You cannot change the height of drop-down in the Interface Builder editor in XCode, and there are no APIs to do it.

**Comment by greggirwin** [comment]
In that case, we can _easily_ note this limitation in the docs, IMO.
