### ISSUE TITLE
[View, CRASH] When copying fonts (GC is unable to release)

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4373]
**Describe the bug**

This says it all:
![](https://i.gyazo.com/1900ec61e75c1efe15a104660c17f90b.jpg)

Run the provided script
First, some of the bases lose their text (matter of 3-5 seconds)
Second, window stops updating (try to move it around!)
Third, if you wait long enough, OS will hardly be able to draw Task Manager window (turn GC on so it doesn't run out of memory for that)

**To reproduce**

Be ready to kill the console in the process list
```
Red [needs: view]

recycle/off

view/options collect [
	keep [backdrop magenta space 2x2]
	repeat i 450 [
		keep compose [base 40x40 (random white)]
		if i % 30 = 0 [keep 'return]
	]
][
	rate: 20
	actors: object [
		on-time: function [fa ev] [
			foreach base fa/pane [
				base/draw: compose [font (make font! [size: 20]) text 0x0 "ABC"]
			]
		]
	]
]
```

**Expected behavior**

Should reallocate fonts without issues. It works fine with static fonts.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 30-Mar-2020/20:23:44+03:00
```

**Comment by greggirwin** [comment]
This is good to know about, especially if it happens with less faces and slower updates. If that's not the case, allocating 9'000 fonts per second isn't likely to happen in the real world. Offering a Best Practice may be enough.

**Comment by greggirwin** [comment]
Works fine here on Win10, so maybe a Win7 issue. I let it run until it used ~2GB, then stopped it. A manual `recycle` is taking quite a while. Maybe due to so many small allocations being handled separately.

**Comment by hiiamboris** [comment]
It crashes my test system UI in ~15 seconds simply because I was lazy to define a static font for it. Talk about real world applications ;)

**Comment by greggirwin** [comment]
Hmmm, what does the app do?

**Comment by greggirwin** [comment]
I will say that this _kind_ of thing is important if we brute force small spreadsheets.

**Comment by greggirwin** [comment]
Ah, your elastic GUI is probably where it came from.

**Comment by greggirwin** [comment]
Funny, I just mentioned to Maarten that a constraint based layout system like Cassowary has come up in the past.

**Comment by hiiamboris** [comment]
> Hmmm, what does the app do?

Just updates it's state 3 times a sec (and it has ~100 base faces). Nothing more.
Consider this. Test is simple. There aren't many points of failure there. But the real world app's complexity is orders of magnitude more, and all that complexity is potential points of failure, and as a result it is affected greatly. I wouldn't advise to dismiss the issue lightly without [first running it, running all the tests, and seeing how low Red's stability is - as it will most likely crash during the run](https://github.com/hiiamboris/red/tree/view-test-system)

**Comment by hiiamboris** [comment]
> Ah, your elastic GUI is probably where it came from.

Not exactly. Elastic UI just handles a few widgets, while I'm arranging all issues into tiles and using custom arrangement algorithm for that (I think it's too uncommon to provide in a general purpose UI lib)

**Comment by greggirwin** [comment]
Sure. I hope @qtxie can make time to look into your test system soon. You've turned up a lot of important issues.

**Comment by qtxie** [comment]
The GC cannot release OS resources currently. Image! has the same issue.

**Comment by hiiamboris** [comment]
Crash scenario:
```
Red [needs: view]

font: make font! [name: "Antiqua"]
loop 5000 [       ;) if it doesn't crash for you - increase the count
	lt: rtd-layout ["text"]
	lt/font: copy font
	size-text lt
]
view [text "visible"]
```

I was profiling some code where temporary rich-text faces were generated to draw text on a layout. 50 faces * 100 times makes for 5000 fonts, unfortunately. After that I either see a blank console (without letters) or a crash:
```
*** Runtime Error 1: access violation
*** Cannot determine source file/line info.
***
```

**Comment by dockimbel** [comment]
I'm closing the ticket as the main issue reported is now fixed.

For the "Crash scenario:", I don't get any crash, though, the window does not display. Most probably Windows is running out of graphic handles, so it's an OS limitation. If you think something is wrong with Red there, feel free to open a new ticket to examine it again.
