### ISSUE TITLE
make bitset! <float> gives strange result

### ISSUE THREAD

**Issue by meijeru** [red/red#4378]
**Describe the bug**
`make bitset! <float>` is not forbidden, but `charset <float>` _is_, which suggests that `make bitset! <float>` should be forbidden as well; in any case `make bitset! 1.0` is _not_ interpreted as `make bitset! 1` which should be reasonable, but gives an arbitrary result

**To reproduce**
```
>> charset 1
== make bitset! #{00}
>> charset 1.0
*** Script Error: charset does not allow float! for its spec argument
>> make bitset! 1.0
== make bitset! #{40}
```

**Expected behavior**
```
>> make bitset! 1.0
*** Script Error: cannot make/to bitset! from 1.0
```

**Platform version (please complete the following information)**
```
all
```

**Comment by 9214** [comment]
Strange..?
```red
>> make bitset! [1.0]
== make bitset! #{40}
>> make bitset! [1]
== make bitset! #{40}
```

**Comment by qtxie** [comment]
Or we convert the float! to integer!.
```
>> make block! 1.0
== []
>> make vector! 1.0
== make vector! [0]
>> make string! 1.0
== ""
```

**Comment by meijeru** [comment]
@qxtie That is in line with the rest, yes.
