### ISSUE TITLE
WISH: TO should be allowed for vector! type

### ISSUE THREAD

**Issue by meijeru** [red/red#4382]
It looks like an oversight, rather than a design decision, to not allow `to vector! <spec>`.

**Comment by 9214** [comment]
We have [REP](https://github.com/red/REP/issues) for wishes and design proposals.

**Comment by meijeru** [comment]
Will go there, alright. Just notice that there are quite a few issues around, which are labeled WISH. Do you want to send them all to REP?

**Comment by greggirwin** [comment]
If only there were hard and fast rules. :^) To me, REPs are for bigger design questions. This may be one, but may also be a missing feature, per the chat.
