### ISSUE TITLE
make bitset! 0 does not work

### ISSUE THREAD

**Issue by meijeru** [red/red#4389]
**Describe the bug**
There exist "empty "bitsets, i.e. bitsets of length 0. In analogy with `series!` values, one should be able to make a bitset of length 0 by `make bitset! 0`. However this gives an error. It is true that one can make such a bitset by `make bitset!  #{ }`. Still, it is an unnecessary lack of consistency.

**To reproduce**
```
>> make bitset! 0
*** Script Error: value out of range: 0
>> make bitset! make binary! 0
== make bitset! #{}
```
**Expected behavior**
```
>> make bitset! 0
== make bitset! #{}
```

**Platform version (please complete the following information)**
```
all
```

**Comment by meijeru** [comment]
See also #2609

**Comment by 9214** [comment]
> In analogy with series! values

`bitset!` is not a `series!`, so this analogy does not hold.

**Comment by meijeru** [comment]
If it were a `series!` value, it would not be an analogy! The whole point about an analogy is that they are unequal but comparable in properties. I also want to invoke the principle of least surprise.

**Comment by greggirwin** [comment]
Analogies aside, @9214 is there a reason _not_ to do this?

**Comment by 9214** [comment]
@greggirwin last time I checked it seemed that empty bitset is a bug, since at least 1 byte must be allocated internally (you might think of it as a limitation). If it's literally empty then that means there's some memory overlap.

**Comment by greggirwin** [comment]
If we need to allocate space, we just do. Like `make block! 0`. My question stands. Is there a reason not to support this? It should auto-expand if needed in any case.
```
>> bs: make bitset! make binary! 0
== make bitset! #{}
>> bs/0: 1
== 1
>> bs
== make bitset! #{80}
```

**Comment by endo64** [comment]
Empty bitsets and `empty?` on bitsets are supported on R2, just to note:

```
R2> empty? make bitset! 0
== true
```
