### ISSUE TITLE
[CRASH] [View] when converting a face with altered `template` to an image

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4396]
**Describe the bug**

`to image!` can usually be safely used on a `window` and `base` faces.
But if you add some stuff to those faces' templates, Red crashes saying:
```
*** Internal Error: block or paren series is too deep to display
*** Where: print
*** Stack: 
```

**To reproduce**

1. modified `window`:
```
append system/view/VID/styles/window/template [custom-option: 'custom-value]
i: to image! view/no-wait []
```

2. modified `base`:
```
Red [needs: view]
append system/view/VID/styles/base/template [custom-option: 'custom-value]
view/no-wait [b: base "text"]
i: to image! b
```

**Expected behavior**

Acquire snapshot of the face.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 18-Mar-2020/14:57:39+03:00 commit #101a64f
```

**Comment by qtxie** [comment]
[This line](https://github.com/red/red/blob/master/runtime/datatypes/image.reds#L466) causes the error. 
One solution is checking if the object has all the fields the face! object has. Though it's not guarantee it's a face!, better than no checking.

**Comment by hiiamboris** [comment]
You'll have to exclude `on-change*` and `on-deep-change*` from `words-of` lists (I'm using the same logic to check if I *loaded* a molded `face!` and these two have caused problems).

`state` checking is a great idea too, as otherwise it crashes (there must be another issue about it)

**Comment by qtxie** [comment]
> You'll have to exclude `on-change*` and `on-deep-change*` from `words-of` lists (I'm using the same logic to check if I _loaded_ a molded `face!` and these two have caused problems).

@hiiamboris What's the reason you don't use `mold/all` to preserve those two functions?

**Comment by hiiamboris** [comment]
At first I didn't because `mold/all` serialized me handle as `#[handle! hex]` and then I couldn't load it. But then realized I *need* the handle, so I patched my build and started using `mold/all`. So you're right, I can probably remove that `on-*` part now.

**Comment by hiiamboris** [comment]
REP proposes a proper solution.

**Comment by qtxie** [comment]
Fixed by commit https://github.com/red/red/commit/7e39cd7b25970fa6405d7a26eb54dd6c17efc252.
