### ISSUE TITLE
Make TIME! with negative hours

### ISSUE THREAD

**Issue by Oldes** [red/red#4397]
**To reproduce**
```red
>> t: make time! [1 2 3]
== 1:02:03
>> t/hour
== 1
>> t/minute
== 2
>> t: make time! [-1 2 3]
== -0:57:57 ;<--- should be: -1:02:03
>> t/hour
== 0 ;<---- should be -1
>> t/minute
== 57 ;<---- should be 2
```

**Comment by greggirwin** [comment]
See https://gitter.im/red/bugs?at=5e9203331aaf8e4b8e774740

This isn't a right/wrong issue, but a choice.

**Comment by endo64** [comment]
Similar to R2's behavior with one difference:

```
>> t: make time! [-1 2 3]
== -0:57:57
>> t/hour: -1
== -1
>> t
== -1:57:57 (R2)
== -0:57:57 (Red)
>> t/hour: -5
== -5
>> t
== -5:57:57 (R2)
== -4:57:57 (Red)
```

**Comment by dockimbel** [comment]
I think the R3 way is more human-friendly. Though, semantics for negative time! values are not well-defined in any Redbol incarnation.

**Comment by greggirwin** [comment]
R3 also doesn't let you assign negative values to time segments, even hours. Time is another one of those cases where Rebol got the most common bits right enough that we rarely hit edge cases where people do things that don't make much sense. I'll draft some design notes.

**Comment by dockimbel** [comment]
I've implemented the R3 way:
```
>> t: make time! [-1 2 3]
== -1:02:03
>> t/hour
== -1
```

**Comment by greggirwin** [comment]
I drafted some notes, for future spec use: [time.txt](https://github.com/red/red/files/7190410/time.txt)

**Comment by hiiamboris** [comment]
Current implementation has some serious flaws, mainly the /hour mentioned above:
```
>> t/hour: 0 t/hour
== 0
>> t/hour: -1 t/hour
== 0
>> t/hour: -2 t/hour
== -1
```
And inability to make sub-hour negative times using `make` from block spec:
```
>> make time! [0 0 -3]
*** Script Error: cannot MAKE/TO time! from: [0 0 -3]
*** Where: make
*** Near : make time! [0 0 -3]
*** Stack:  

>> make time! [-0.0 0 3]
*** Script Error: cannot MAKE/TO time! from: [-0.0 0 3]
*** Where: make
*** Near : make time! [-0.0 0 3]
*** Stack: 
```

**Comment by dockimbel** [comment]
You should have opened a new ticket and linked it to this old one...

**Comment by hiiamboris** [comment]
Isn't it all part of the same make time with negative hours issue?

**Comment by dockimbel** [comment]
The original issue reported in this ticket has been fixed. If there was a regression on that same issue (does not seem to be the case), then it's legit to expand this ticket and reopen it. Any other case requires a new ticket (with an eventual link to this one, as the issues _seem_ to be close/related, but are not the exact same).
