### ISSUE TITLE
MAKE-DIR fails silently if it has not a permission to make a directory

### ISSUE THREAD

**Issue by rebolek** [red/red#4400]
`make-dir` help text states that there is no error when creating already existing directory, which is a nice feature, however, there's also no error when creating a directory is not successful due to lack of access rights.

# Example
```
>> make-dir %/asdf
== %/asdf/
>> find read %/ %asdf
== none
```

# Expected behavior

I would expect an error, something like `cannot create directory: access denied`.

# Platform

```
>> about
Red 0.6.4 for Linux built 8-Apr-2020/13:22:20+02:00
```

**Comment by hiiamboris** [comment]
Confirmed on W7.

**Comment by greggirwin** [comment]
I agree on the expected behavior.
