### ISSUE TITLE
Incorrect output of to-csv

### ISSUE THREAD

**Issue by endo64** [red/red#4424]
**Describe the bug**
See below

**To reproduce**
```
>> o: context [a: "x x"]
== make object! [
    a: "x x"
]
>> to-csv values-of o
== {"x x"^/}
>> to-csv values-of o
== {"""x x"""^/}
>> to-csv values-of o
== {"""""""x x"""""""^/}
>> b: ["x x"]
== ["x x"]
>> to-csv b
== {"x x"^/}
>> to-csv b
== {"""x x"""^/}
>> to-csv b
== {"""""""x x"""""""^/}
```

**Expected behavior**

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 29-Apr-2020/15:24:35+03:00 commit #db7f36a
```

**Comment by dockimbel** [comment]
@rebolek This one is for you. I'm putting Gregg as the proxy in "Assignees".

**Comment by greggirwin** [comment]
Objects and maps share the same encoder, so affects those too. What we need to do is vet the input, to make sure it's what `to-csv` expects, and also put that in the wiki (and eventually docs and articles).
```
>> mm: load-csv/as-columns s
== #(
    "A" ["a" "1" "11"]
    "B" ["b" "2" "22"]
    "C" ["c" "3" "33"]
)
>> to-csv mm
== {A,B,C^/a,b,c^/1,2,3^/11,22,33^/}
>> to-csv mm
== {A,B,C^/a,b,c^/1,2,3^/11,22,33^/}
>> to-csv mm
== {A,B,C^/a,b,c^/1,2,3^/11,22,33^/}
```
I thought at first it was `/skip` related, that you needed to include it in the call, but it seems like it may be a special case where there's only one string in the block.

**Comment by rebolek** [comment]
Merge request with fix created https://github.com/red/red/pull/4425
