### ISSUE TITLE
`break` after `try` can't see the loop

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4440]
**Describe the bug**
```
forever [try/all [1] break]
*** Throw Error: no loop to break
*** Where: break
*** Stack:
```

**Expected behavior**

Should break out of it

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 13-May-2020/14:18:13+03:00
```

**Comment by dockimbel** [comment]
Cannot reproduce the issue anymore.
