### ISSUE TITLE
[Compiler] Internal error `defer needs a value`

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4526]
**Describe the bug**

Compile this:
```
Red []                                 
c: context [++: make op! func [x y] []]
```
Compiler says:
```
-=== Red Compiler 0.6.4 ===-

Compiling D:\devel\red\red-src\red-master\environment\reactivity-bug2.red ...
*** Red Compiler Internal Error: Script Error : defer needs a value
*** Where: comp-word
*** Near:  [defer: fetch-functions skip pc -2]
```

**Expected behavior**

Compiles.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 28-May-2020/17:51:04+03:00 commit #36857eb
```

**Comment by 9214** [comment]
The same error blocks me from compiling a 750LOC test suite.

**Comment by 9214** [comment]
I can no longer reproduce the original error message. @hiiamboris?

**Comment by hiiamboris** [comment]
Bad if issues go away by themselves. Means they hide deeper.
Anyway:
```
Red []                                 
c: context [**: make op! func [x y] []]
```
*** Red Compiler Internal Error: Script Error : defer needs a value
*** Where: comp-word
*** Near:  [defer: fetch-functions skip pc -2]
```
