### ISSUE TITLE
cannot type BINARY! in console multi-line mode

### ISSUE THREAD

**Issue by 9214** [red/red#4561]
**Describe the bug**
Red console enters multi-line editing mode when user types opening series delimiter on a single line. This mode does not work for `binary!` values.

**To reproduce**
```
>> #{
*** Syntax Error: (line 2) invalid binary at #{
*** Where: transcode
*** Stack: load 
```

Same holds for construction syntax, but that might be expected since it's only partially implemented.

**Expected behavior**
```
>> #{
{    }
== #{}
```

**Platform version**
 W10, b452716, both GUI and CLI consoles.

**Comment by bitbegin** [comment]
https://github.com/red/red/pull/4536
