### ISSUE TITLE
compiler ignores setting a word to an object

### ISSUE THREAD

**Issue by 9214** [red/red#4569]
**Describe the bug**
If one instance of a word is bound to function's context, and then another instance with the same spelling is set to an object — magic happens.

**To reproduce**
The script below, once compiled:
```red
Red []

bind 'foo has [foo]['WTF]
foo: object []

probe foo
probe :foo

```
Results in:
```red
WTF
make object! []
```

**Expected behavior**
```red
make object! []
make object! []
```

**Platform version**
a1d1495, W10.

**Comment by greggirwin** [comment]
Good example. :+1:

**Comment by 9214** [comment]
Another one:
```red
Red []

block: reduce ['foo func [/bar]["Definitely not bar."]]
foo:  context [bar: does ['bar]]
probe foo/bar
```
When compiled:
```red
"Definitely not bar."
```

**Comment by dockimbel** [comment]
@9214 In your second example, the following line:
```
block: reduce ['foo func [/bar]["Definitely not bar."]]
```
has no effect on the rest of the code.

**Comment by 9214** [comment]
@dockimbel if what you say is true, then the "Definitely not bar." message appears out of nowhere 😉 I expect the compiled code to call `bar` within object `foo`, instead the anonymous function within `block` is called, as if referenced by key `foo`.
