### ISSUE TITLE
compiler does not process OP! aliases properly

### ISSUE THREAD

**Issue by 9214** [red/red#4572]
**Describe the bug**
Even with a workaround for https://github.com/red/red/issues/2867 in place compiler still cannot handle `op!` aliases properly.

**To reproduce**
Compile the script below:
```red
Red []

set 'o get '//

probe 8 o 3 == 2
probe try [1 o 0]
```

Result:
```red
8
0
```

**Expected behavior**
```red
true 
make error! [...]
```

**Platform version**
 a1d1495, W10.

**Comment by hiiamboris** [comment]
Compiler is it's own DSL ;)

**Comment by 9214** [comment]
[In my world, everyone's a pony...](https://www.youtube.com/watch?v=CJr4kPMVvpU)

**Comment by dockimbel** [comment]
It is possible to improve the compiler to support an explicit form like `set 'o get '//`. However, it is easy to defeat it by indirectly referencing the `op!` value, like in:
```
new: first reduce [get '//]
set 'o :new
```
There is no way the compiler could guess that `o` will be set to an `op!` during static analysis in the general case.

As a reminder, only a subset of Red semantics are statically analyzable, therefore compilable. This set is quite large and covers most of the code written by users. Scripts using a more dynamic constructs should not be fed to the compiler, they should be evaluated only or compiled in encapped mode to fully preserve their semantics. That's the best we can achieve for now.
