### ISSUE TITLE
Remainder silently allows (char % negative int) and (tuple % negative int)

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4577]
**Describe the bug**

```
>> #"^A" % 10
== #"^A"
>> #"^A" % -10
== #"^A"
```
Latter should be `-#"^A"` which is impossible, so should raise an error.

```
>> 1.2.3.4 % -10
== 1.2.3.4
```
Same here.

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 30-Jun-2020/21:32:08+03:00
```

**Comment by 9214** [comment]
https://github.com/red/red/issues/3650

**Comment by 9214** [comment]
This actually reminds me... @theSherwood since you have expressed an interest in writing tests, would you like to work on `tuple!` datatype test suite?

**Comment by 9214** [comment]
> Latter should be -#"^A" which is impossible, so should raise an error.

Consider:
```red
>> to integer! #"A"
== 65
>> 65 % -10
== 5
>> #"A" % -10
== #"^E"
>> to integer! #"A" % -10
== 5
```

> Same here.

Consider:
```red
>> 7.8.0 % -4
== 3.0.0
>> 7x8 % -4
== 3x0
```

AFAIK remainder can be negative only if the dividend is negative. And since neither `char!` nor `tuple!` can be negative, the existing behavior is IMO expected.

**Comment by hiiamboris** [comment]
I must have been very tired when I wrote this :D
Thanks.

**Comment by 9214** [comment]
@hiiamboris happens with all of us #4558 😳
