### ISSUE TITLE
Using function as `system/console/prompt` crashes

### ISSUE THREAD

**Issue by Oldes** [red/red#4587]
**To reproduce**
```red
>> system/console/prompt: does[ join now/time ">> "]
;** crashes **
```
**Expected behavior**
no crash

**Platform version (please complete the following information)**
```
Red 0.6.4 for Windows built 24-Jul-2020/15:16:00
```

**Comment by 9214** [comment]
Duplicate of https://github.com/red/red/issues/4301.
