### ISSUE TITLE
RANDOM -2147483648 hangs

### ISSUE THREAD

**Issue by 9214** [red/red#4590]
**Describe the bug**
`random -2147483648` gets stuck in an infinite loop.

**To reproduce**
1. Get some tea or a cup of damn good Joe;
1. Type `random 1 << 31` in console;
1. Sip the brew, meditate, observe Red trying to spell out [無](https://en.wikipedia.org/wiki/Mu_(negative)).

**Expected behavior**
A random integer in `[-1, -2147483648]` range.

**Platform version**
30652909, W10.

**Comment by hiiamboris** [comment]
I suggest a special case for `random 80000000h` which would just `return not rand`, and smth alike in random/secure
