### ISSUE TITLE
TRANSCODE/INTO ignores destination block

### ISSUE THREAD

**Issue by 9214** [red/red#4630]
**Describe the bug**
`/into` refinement usually specifies that the result should either be appended or insterted into the provided destination block. `transcode` ignores this and always returns the result as-is.

**To reproduce**
```red
>> transcode/into "a" block: [b]
== [a]
>> block
== [b]
>> head block
== [b]
```

**Expected behavior**
```red
>> transcode/into "a" block: [b]
== [b] ; or [b a] if /INTO implies APPEND
>> block
== [a b] ; or [b a]
```

**Platform version**
b0e52d4, W10.

**Comment by dockimbel** [comment]
Not implemented yet.
