### ISSUE TITLE
Lot of READ-THRUs can lead to TIMEOUT error and/or total breakdown of IO

### ISSUE THREAD

**Issue by rebolek** [red/red#4675]
Consider this code:
```
repeat i 1000 [link: probe rejoin [http://duckduckgo.com?q= i] read-thru link query path-thru link]
```

On macOS, this ends with timeout error when `i = 249`. On subsequent run, it reads four files from cache and then ends again with `cannot read` error. All IO functions are dead then and it's not even possible to quit Red, as it wants to save console history.

On Linux, this runs fine first time, second time it ends with timeout error when `i = 21` (so it read 1021 files total).  After that, each `read-thru` ends with timeout error, even when cached. Unlike macOS, IO is not totally dead, local file access works and it's possible to quit Red.

Tested on macOS and Linux with latest build, it seems to work fine on Windows.

**Comment by 9214** [comment]
[Gitter log](https://gitter.im/red/bugs?at=5f842fb8cdb04d1ea079a9e1).

**Comment by rebolek** [comment]
@qtxie I can still reproduce it under different conditions. Unfortunately, I wasn't able to isolate it yet. There's no `query` in the code and it happens *much* later, on macOS it took aproximatelly 100x more tries, it happened after 25149 `read-thru`s. No `query` used this time, only `read-thru`.
