### ISSUE TITLE
GUI-Console crash when using help for system/words

### ISSUE THREAD

**Issue by litew** [red/red#4685]
**Describe the bug**
Red console crashes when trying to use help with system/words keywords.

**To reproduce**
1. Run red console with `red`.
2. Type `? system/words`
3. Program crashes with following output:

```
*** Runtime Error 1: access violation
*** at: 0000000Fh
```

**Expected behavior**
List of words used in Red.

**Platform version**
OS: Fedora 32 x86_64
Red:
```
Red 0.6.4 for Linux built 16-Oct-2020/21:35:47+03:00 commit #df54dcdf65cdf9dd37590225ac51aaedcd065f9a
```

**Comment by bitbegin** [comment]
after `recycle/off`, it runs ok

**Comment by bitbegin** [comment]
windows platform just not easy to reproduce, but still exists this issue. you can use `loop 100 [? system/words]` to reproduce

**Comment by litew** [comment]
> after `recycle/off`, it runs ok

Indeed, works for me too.
