### ISSUE TITLE
Red can't load URL with percent encoded space

### ISSUE THREAD

**Issue by rebolek** [red/red#4687]
```
>> http://www.example.com?q=test%20(A)%20.html
*** Script Error: A has no value
*** Where: catch
*** Stack:
```

It seems that Red first decodes `%20` to space and then wrongly assumes it's a real space and thinks that theURL ended already.

 
**Platform version**
```
>> about
Red 0.6.4 for macOS built 13-Oct-2020/7:21:49
```

**Comment by hiiamboris** [comment]
Shouldn't your url be *fully* percent encoded?
```
>> to "" http://www.example.com?q=test%20%28A%29%20.html
== "http://www.example.com?q=test (A) .html"
```

**Comment by rebolek** [comment]
Good point, however, this is something scraped from web. Also, there's another problem:

```
>> load "http://www.example.com?q=test%20(A)%20.html"                                                             
== [http://www.example.com?q=test%20
```

**Comment by qtxie** [comment]
Here is a workaround:
```
to url! dehex "http://www.example.com?q=test%20(A)%20.html"
```

**Comment by dockimbel** [comment]
AFAIR, parens are not legal characters in URL, so they must be hex-encoded.

**Comment by qtxie** [comment]
Just to note, some molded URLs are not loadable:
```
>> url: to url! "http://www.example.com?q=test(A).html"
== http://www.example.com?q=test(A).html
>> s: mold url
== "http://www.example.com?q=test(A).html"
>> url = load s
== false
```
According to RFC 3986, the characters in a URL have to be taken from a defined set of unreserved and reserved ASCII characters. Any other characters are not allowed in a URL.

The unreserved characters can be encoded, but should not be encoded. The unreserved characters are:

```
A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z 0 1 2 3 4 5 6 7 8 9 - _ . ~
```

The reserved characters have to be encoded only under certain circumstances. The reserved characters are:

```
! * ' ( ) ; : @ & = + $ , / ? % # [ ]
```
I'm not sure we if should encode `( ) [ ]` or not. Rebol2 encode those characters:
```
R2:
>> mold to url! "http://www.test.com?q=a(b)c[d]e.html"
== "http://www.test.com?q=a%28b%29c%5Bd%5De.html"
```
