### ISSUE TITLE
R/S floating point output inconsistencies

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4713]
**Describe the bug**

The following script:
`Red/System [] print-wide [1.0 / 0.0  -1.0 / 0.0  0.0 / 0.0  "^/"]`

On Windows produces the following:
`1.#INF -1.#INF -1.#IND.0`
In 2019 builds it was producing:
`1.#INF.0 -1.#INF.0 -1.#IND.0`

On Linux it produces:
`inf.0 -inf.0 -nan.0`
On RPi:
`inf -inf 1.#NaN`

**Expected behavior**

Same output on all platforms.
`1.#INF -1.#INF 1.#NAN` ?

**Platform version**
```
Red 0.6.4 for Windows built 16-Oct-2020/12:58:41+03:00 commit #e5876af
```

**Comment by dockimbel** [comment]
@qtxie Please confirm that the fix is correct.
