### ISSUE TITLE
Missing header field

### ISSUE THREAD

**Issue by toomasv** [red/red#4728]
Currently the following header fields propagate to the .rsrc header in the PE file:
`Title: Version: Company: Comments: Notes: Rights: Trademarks: Author: ProductName:`
Please add `ProductVersion` to these.

**Comment by greggirwin** [comment]
Note that Author maps to PrivateBuild in the PE version info. @dockimbel, not sure that makes sense. https://docs.microsoft.com/en-us/windows/win32/menurc/versioninfo-resource says 

> VS_FF_PRIVATEBUILD | File was not built using standard release procedures.

Maybe we don't map Author, as that's really more dev oriented. We could use PrivateBuild as a tag, e.g. for test releases, but I don't see a lot of value in that right now.

**Comment by dockimbel** [comment]
I'll let @qtxie handle this as he wrote the code for .rsrc section support.

**Comment by qtxie** [comment]
@greggirwin Looks like a wrong mapping, I'll remove it.
