### ISSUE TITLE
Shouldn't conversion from string to word do check of input validity?

### ISSUE THREAD

**Issue by Oldes** [red/red#4735]
Current situations in `Red` is like:
```red
>> to word! "a{b}c"
== a
>> to word! "a b c"
== a
```
In Rebol2:
```
>> to word! "a b c"
== a b c
>> to word! "a{b}c"
== a{b}c
```
and in Rebol3:
```
>> to word! "a b c"
** Script error: contains invalid characters
** Where: to
** Near: to word! "a b c"

>> to word! "a{b}c"
== a{b}c
```

I think that it should throw error in all cases like does R3 with spaces.

Tested with:
```
Red 0.6.4 for Windows built 18-Nov-2020/3:13:59+01:00 commit #8ee5a9f
```

**Comment by Oldes** [comment]
On the other side, current situation may be useful in situation like:
```red
>> to word! as string! <a href="foo">
== a
```

**Comment by greggirwin** [comment]
I don't think the tag example is that useful.

**Comment by Oldes** [comment]
@greggirwin so you think that there should be error message like in R3 instead of this silent truncation?

**Comment by greggirwin** [comment]
Yes. It's one thing to make a non-loadable but usable value, which could potentially be mapped back to the original. It's another to create a value that is so lossy that predicting behavior will be difficult. That doesn't mean we won't have *any* lossy conversions, but this one seems particularly bad.

**Comment by dockimbel** [comment]
@Oldes 
> ```red
> as string! <a href="foo">
> ```

You can do it using:
```
>> transcode/one as string! <a href="foo">
== a
```

**Comment by dockimbel** [comment]
It's now reporting an error in all those invalid cases. 
Adding a unit test is left to the poster @Oldes or anyone willing to submit a PR. ;-)

**Comment by greggirwin** [comment]
> transcode/one as string! <a href="foo">

@dockimbel I only get `a` using `transcode`. 
```
>> transcode/one as string! <a href="foo">
== a
>> mold transcode/one as string! <a href="foo">
== "a"
```

**Comment by greggirwin** [comment]
Unless that's part of the new fix.

**Comment by dockimbel** [comment]
@greggirwin Not sure what you mean. Using `transcode`, you will get all values tokenized:
```
>> transcode as string! <a href="foo">
== [a href= "foo"]
```

**Comment by greggirwin** [comment]
Ah, I see what you mean now. I thought you meant that should convert the complete tag value to the word.
