### ISSUE TITLE
[GTK & Mac] Transparent surfaces are eating events

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4743]
**Describe the bug**

`view [backdrop red box 100x100 on-down [probe "down"]]`
click anywhere on the box
`box` should not react to clicks (at least it's transparent parts when something is drawn on it), but it does

**Platform version**
```
Red 0.6.4 for Linux built 1-Nov-2020/23:51:29+03:00 commit #2d05900
```

**Comment by 9214** [comment]
https://github.com/red/red/issues/1931

**Comment by qtxie** [comment]
That's another issue cannot be solved without changing the low-level GUI engine.

**Comment by hiiamboris** [comment]
Can't we just check the pixel color and kick the event further from one face into another, in our own code?

**Comment by qtxie** [comment]
It will be very costly if no low-level API to do the checking.

**Comment by hiiamboris** [comment]
Don't we have cached images of each face?

**Comment by greggirwin** [comment]
> Can't we just check the pixel color 

What it the pixel color matches the one underneath?

**Comment by qtxie** [comment]
> Don't we have cached images of each face?

No, we don't. There should be an OS API to get the bitmap of a face. Then we'll need to get the face under the current face, pass the event to it. If no API to get the face, we'll have to enumerate the face tree to check the bounding box and the z-order. Not an easy fix but it's possible.

**Comment by qtxie** [comment]
We already have some related code to handle it on macOS. The fix is much easier than I thought. 
For GTK backend, @bitbegin had been spent quite some time on this issue, seems no easy fix.

**Comment by qtxie** [comment]
> Can't we just check the pixel color and kick the event further from one face into another, in our own code?
