### ISSUE TITLE
Escaped char is never terminated in binary syntax when used in console

### ISSUE THREAD

**Issue by Oldes** [red/red#4744]
**Before submitting**
[dedicated chat](https://gitter.im/red/bugs?at=5fce24fe75f7397e29fb1b73)

**Describe the bug**
```red
>> {^/} ;<--- it's ok with string!
== "^/"
>> #{^/} ;<--- but not with binary (enters multi-line input)
{    
(escape) ;<-- one must hit ESC to exit
```
It is possible to load it as:
```red
>> load "#{^/}"
== #{}
```

**Platform version**
commit: dcadff1e895a4d26e831d53667192b4a50c96d2b

**Comment by hiiamboris** [comment]
I still think `^/` syntax has nothing to do with `binary!`.
In `load "#{^/}"` example, `^/` is interpreted when lexing `string!`, not when lexing `binary!` (which receives a single LF char, not two `^` and `/` chars as input).

**Comment by Oldes** [comment]
Maybe I should use better char, not a LF. 
```red
>> load "#{^(00)}"
*** Syntax Error: (line 1) invalid binary at #{}
*** Where: transcode
*** Stack: load  

>> #{^(00)}
{    
{    
(escape)
```

**Comment by Oldes** [comment]
I don't say I expect these escaped chars to be supported... I expect that console will throw an error in both cases.

**Comment by Oldes** [comment]
On the other side... one should be able to copy code like: `#{00} = 2#{0000^-0000}` and paste it into console to see the result.

**Comment by hiiamboris** [comment]
You will copy a binary tab, not `^-`

**Comment by Oldes** [comment]
No... if I copy it from source code (which is valid use now) I will have `^-` and not a binary tab.

**Comment by zwortex** [comment]
The following sequence has the same effect : 
```
a: #{ name: "john" family: "doe" }
```

**Comment by Oldes** [comment]
Another case: type in console `<@` and than hit enter.
