### ISSUE TITLE
to integer! #issue silently eats digits

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4750]
**Describe the bug**

1. Issues of odd length throw away the last digit:
```
>> to 0 #f
== 0
>> to 0 #fff
== 255
>> to 0 #fffff
== 65535
```
2. Issues longer than 8 digits throw away the rest:
```
>> to 0 #12345678
== 305419896
>> to 0 #123456789
== 305419896
>> to 0 #1234567890
== 305419896
```

**Expected behavior**

1. [Tastes divided](https://gitter.im/red/bugs?at=5fceb4948d1477540fab098b) on whether issues of odd length should throw an error or produce valid output (and it barely matters anyway), but clearly we don't want conversion to just silently ignore those digits.
2. Error if digits do not fit the `integer!` type (whether it's 32- or 64-bit one).

**Platform version**
```
Red 0.6.4 for Windows built 4-Dec-2020/7:41:48+03:00 commit #382dd4e
```

**Comment by hiiamboris** [comment]
Same issue with tuples:
```
>> to tuple! #F
== 0.0.0
>> to tuple! #FF
== 255.0.0
>> to tuple! #FFF
== 255.0.0
>> to tuple! #FFFF
== 255.255.0
```
and so on

**Comment by greggirwin** [comment]
Tuples as a byte-view debugging tool. Nice. :^)

**Comment by dockimbel** [comment]
The corresponding conversion routines have been rewritten to be much more faster and more accurate. For `issue!` to `tuple!` conversions, only following formats are supported: `#rgb`, `#rrggbb` and `#rrggbbaa`.

**Comment by hiiamboris** [comment]
In this case I suggest `hex-to-rgb` func to be rewritten as simply `to tuple! issue`, or made obsolete.
