### ISSUE TITLE
Trying to LOAD Redbin file created in previous session crashes Red

### ISSUE THREAD

**Issue by rebolek** [red/red#4756]
When I create a Redbin file, save it and load it back, everything works fine. However when I save the file, close Red, run it again and try to load it, Red crashes with `Runtime Error: Access violation`.

**To reproduce**

1. run Red
2. make some testing Redbin. I used this:
```
save/as %test #(%ab/cd #(url: http://example.org date: 1-2-1934/5:6:7)) 'redbin
```
3. quit Red session and run Red again
4. `load/as %test 'redbin` -> crash

**Expected behavior**

Redbin file would be loaded

**Platform version**

```
Red 0.6.4 for macOS built 10-Dec-2020/16:04:06
```

**Comment by dockimbel** [comment]
I can reproduce the crash.
