### ISSUE TITLE
Halt from within a view

### ISSUE THREAD

**Issue by zwortex** [red/red#4757]
Halt from within a view opened from the gui console triggers an error and does not return to the input prompt.

```
view [
    b: button "The Button" [ halt ]
]
```

gives the error :

```
*** Throw Error: no catch for throw: halt-request
*** Where: =
*** Stack: view do-events do-actor do-safe halt
```

The same in Rebol2 returns to the input prompt.

```
In Rebol 2 :
view layout [
    b: button "The Button" [ halt ]
]
```

**Comment by dockimbel** [comment]
A fix has been pushed on a development branch, as it needs to be implemented for other platforms (only Windows for now). Also, exiting the event loop that way should activate the (GUI) console window and show the blinking cursor.

**Comment by dockimbel** [comment]
This new fix supersedes the previous one.
