### ISSUE TITLE
Decimals in time! values not accepting comma

### ISSUE THREAD

**Issue by raimundasa** [red/red#4781]
**Describe the bug**
```
>> 3:3:3.3
== 3:03:03.3
>> 3:3:3,3
*** Syntax Error: (line 1) invalid time at 3:3:3,3
*** Where: case
*** Stack: load
```

**Expected behavior**

`==3:03:03.3`

**Platform version**

`Red 0.6.4 for Linux built 25-Dec-2020/1:08:25+02:00 commit #98f31b5`

**Comment by meijeru** [comment]
It seems a feature rather than a bug, unless one is keen on consistency ;-)

**Comment by greggirwin** [comment]
It used to work, and works in R2, so is a fast lexer regression.
