### ISSUE TITLE
`size-text` cannot fill rich-text face fully

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4783]
**Describe the bug**

When rich-text face's size equals it's text size, I expect size-text to return the same value always. However here's a snippet proving the opposite:
```
txt: "Lorem ipsum dolor sit amet, conse"
lt: rtd-layout [""]
lt/font: make font! [name: "Segoe UI" size: 10]
lt/size/x: 300
loop 20 [
	lt/text: txt
	lt/size: probe size-text lt
]
```
Output:
```
197x17
160x34
125x34
108x34
82x51
74x51
68x69
47x86
36x103
34x121
33x138
31x155
30x172
29x172
26x172
25x190
24x190
23x190
20x190
19x190
```

**Expected behavior**
```
197x17
197x17
197x17
197x17
<...>
```

**Platform version**
```
Red 0.6.4 for Windows built 20-Dec-2020/21:04:56+03:00 commit #7a6d9a9
both master and D2D branches
```

**Comment by hiiamboris** [comment]
Another problem with it, it also **draws** the text wrongly:
```
txt: "Lorem ipsum dolor sit amet, conse"
lt: rtd-layout [""]
lt/font: make font! [name: "Segoe UI" size: 10]
lt/size/x: 300
lt/text: txt
lt/size: probe size-text lt   ;) 197x17
;) this should draw the text on a single line, right?
view compose/deep [rich-text 300x100 draw [text 0x0 (lt)]]
```
![](https://i.gyazo.com/68446b1f22e9bbaf6139e51ce020c8dc.png)

**Comment by hiiamboris** [comment]
Could be some DPI rounding glitch. I'm using 150% scaling.

**Comment by greggirwin** [comment]
Same results here, at 100% scaling.

**Comment by qtxie** [comment]
The API gives us `float` size, while Red use `integer` size.
The accurate size returns by the API: `197.6724, 17.29102`.

**Comment by hiiamboris** [comment]
So, rounding up should be the easiest solution I guess.

**Comment by hiiamboris** [comment]
I don't think adding 0.5 is gonna work. To integer drops the float part, so `100.2 + 0.5 = 100.7 -> 100`.

**Comment by qtxie** [comment]
> 
> 
> I don't think adding 0.5 is gonna work. To integer drops the float part, so `100.2 + 0.5 = 100.7 -> 100`.

I also add 0.5 to the size of the rich-text to make it work. Rounding up is not satisfying if the fractional part is very small. e.g. we don't want round 17.01 to 18.
