### ISSUE TITLE
Misformed literal string cannot be ended in console

### ISSUE THREAD

**Issue by toomasv** [red/red#4796]
Entering unbalanced literal string in console enters a loop that cannot be ended:
```
>> %{}%%
{    }%
{    }%
{
```

**Expected behavior**
String should be closed with correct ending as in following case
```
>> %%{}%
{    }%%
== "}%^/"
```

**Platform version**
```
Red 0.6.4 for Windows built 9-Jan-2021/1:47:49+02:00 commit #db2c060
```

**Comment by hiiamboris** [comment]
related https://github.com/red/red/issues/4744
