### ISSUE TITLE
Argument-handling not consistent over platforms

### ISSUE THREAD

**Issue by memophen** [red/red#480]
Red/System handles arguments on Windows differently from MacOS (and presumably Linux). On MacOS, everything delimited by _single_ or _double_ quotes is taken as one single argument, and the quotes themselves are not copied to the ITEM field of the SYSTEM/ARG-LIST. On Windows however, only substrings delimited by _double_ quotes are interpreted as one argument, and the quotes are preserved; single quotes have no special meaning. I doubt if the preservation of quotes is a good idea for Red/System, albeit in line with the behavior of batch files (and maybe also exactly what Windows programmers expect). There are (at least) two acceptable options for getting more consistency over the platforms:
- Respect the local tradition, and don't regard single quotes as delimiters. But drop the double quotes after the intake. This is how Perl behaves on Windows.
- Try to impose more civilization on Windows and treat single quotes similar to double quotes. And drop the quotes afterwards. This is the Ruby way.

Perl or Ruby? It's is a real dilemma. Personally I slightly prefer the Perl approach here. DOS and bash are very different shells, after all. Quotes are not the only thing to worry about. How to handle backslashes as escape character? (Perl and Ruby only allow double quotes to be escaped this way. REBOL and Windows use the caret as escape character, but Windows doesn't apply it consistently.)

This brings me to introducing an amendment to the Red/System constitution: Every programmer has the right to parse the command line as he chooses. Therefore the command line must be easily accessible.

**Comment by dockimbel** [comment]
Now Red/System behaves in a more standard way (relying on `CommandLineToArgvW` and
`GetCommandLineW`), supporting Unicode characters (encoded in UTF-8 on all platforms) and providing a parsed arguments list similar to C/Perl:
```
C:\Dev\Red>test-args """abc""" """ def """
count: 5
1: test-logic2
2: "abc"
3: "
4: def
5: "
```
