### ISSUE TITLE
`do-file` breaks `halt`

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4830]
**Describe the bug**

`1.red`: `Red [] do %2.red`
`2.red`: `Red [] halt`

```
D:\devel\red>red "2.red"
(halted)

D:\devel\red>red "1.red"
*** Throw Error: no catch for throw: halt-request
*** Where: do
*** Stack: do-file
```

**Expected behavior**

`halt` should display `halted` even if it's included.

**Platform version**
```
Red 0.6.4 for Windows built 9-Feb-2021/20:31:32+03:00 commit #18bc5f7
```

**Comment by hiiamboris** [comment]
Other include-related stuff:
#4817 #4422 #4390 #4422 #4249 #4139 #4128 #3921 #3550 #3464 #2484 red/REP#56

**Comment by dockimbel** [comment]
This one was not related to include system per se, but to `halt` proper catching when thrown from a script file.
