### ISSUE TITLE
Loading malformed file-name crashes console

### ISSUE THREAD

**Issue by toomasv** [red/red#4834]
**Describe the bug**
`load {%"}` crashes console

**Platform version**
```
Red 0.6.4 for Windows built 9-Feb-2021/19:31:32+02:00 commit #18bc5f7
```

**Comment by hiiamboris** [comment]
Stack trace looks like a bug on it's own:
```
>> load {%"}

*** Runtime Error 1: access violation
*** in file: ¸,
*** at line: 1818845542
***
```

**Comment by hiiamboris** [comment]
Related: https://github.com/red/red/issues/4547
Another scenario: run this in the GUI console:
```
gui-console-ctx/terminal/color?: yes
%"^/"
```
Output:
```
*** Runtime Error 1: access violation
*** in file: ç1
*** at line: 1818845542
***
```

**Comment by dockimbel** [comment]
> Stack trace looks like a bug on it's own:

No bug there. What happens sometimes is that the debug records inside the executable image in memory get corrupted by a crash. We should move such data to a read-only segment once the linker will have support for that.
