### ISSUE TITLE
[Compiler] `alert` fails unwittingly under console subsystem

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4867]
**Describe the bug**

The call to `alert` says:
```
*** Script Error: path none is not valid for unset! type
*** Where: eval-path
*** Stack: alert
```

**To reproduce**

1. Create a script `1.red`: `Red [] alert "is a game"`
2. Compile it: `red -r -t MSDOS 1.red`
3. Run, see the error output

**Expected behavior**

Compiler must warn that GUI subsystem is not being included.

**Platform version**
```
Red 0.6.4 for Windows built 18-Mar-2021/22:28:01+03:00  commit #73d9bd2
```

**Comment by dockimbel** [comment]
> Compiler must warn that GUI subsystem is not being included.

The compiler cannot know that. `view` and `alert`  are just unknown words from the compiler's perspective.

**Comment by hiiamboris** [comment]
Perhaps `alert` should simply be undefined then.
