### ISSUE TITLE
changing an object function breaks it

### ISSUE THREAD

**Issue by snotbubble** [red/red#4871]
**Before submitting**
Prior to opening this ticket, please share your finding in our [dedicated chat](https://gitter.im/red/bugs), so we can confirm it and help in reproducing it, including on other platforms.

**Describe the bug**
altering an object function will break its ability to read other object fields

**To reproduce**
run this
```
p: "" o: context [ n: "name" f: func [] [print [ "name=" n ] ] ] o/f parse (form o) [ thru "f:" copy p thru "]]" ] replace p "name" "nom" o/f: do (load p) probe o o/f
```

**Expected behavior**
the modified function `f` should see the parameter `n` and print its value

**Platform version**
```
Red 0.6.4 for Linux built 2-Mar-2021/22:01:01+10:00 commit #6de9b93
```

**Comment by greggirwin** [comment]
Formatting the code will help readers a lot. :^)

**Comment by greggirwin** [comment]
What you're missing here is that when you extract the function as a string, then load that string, what you get back is not bound to the object in any way, so that function you (re)create is looking for `n` in the global context.
```
p: ""
n: "Not this one!"
o: context [
	n: "name"
	f: func [] [
		print [ "name=" n ]
	] 
]

o/f
parse (form o) [ thru "f:" copy p thru "]^/]" ]
replace p "name" "nom"
o/f: do (load p)
probe o
o/f
```
You need to bind it to get the result you want.
```
o: context [
	n: "name"
	f: func [] [
		print [ "name=" n ]
	] 
]

o/f
parse (form o) [ thru "f:" copy p thru "]^/]" ]
replace p "name" "nom"
o/f: do (bind load p o)
probe o
o/f
```
In this case, you should also be able to do it like this:
```
o: context [
	n: "name"
	f: func [] [
		print [ "name=" n ]
	] 
]

o/f
body: replace/deep body-of :o/f "name=" "nom="
probe o
o/f
```

**Comment by snotbubble** [comment]
`bind` just rebuilds the whole object, correct?

**Comment by hiiamboris** [comment]
no, it just binds the words deeply
