### ISSUE TITLE
Word lexing edge cases do not follow any logic

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4872]
**Describe the bug**

```
>> [<<<>>>]
== [<<<>>>]  ;) word
>> ['<<<>>>]
== ['< <<>>>]  ;) 2 words
>> ['<'<<>>>]
== ['<' <<>>>]  ;) 2 words
>> ['<'<'<>>>]  ;) word and a tag (not closed)
<    
(escape)
>> ['<'<'<'>>>]  ;) word tag word
== ['<' <'<'> >>]

>> [:<<<>>>]
== [:< <<>>>]
>> [:<<<>>>:]
== [:< <<>>>:]
>> [<<<>>>:]
== [<<<>>>:]
```
total mess

```
>> '-1
== -1   ;) word
>> '-1x1
== -1x1    ;) word
```
this is simpler, just disallow words in `[sign][digit][..]` form

**Expected behavior**

We need a clear description of where one type ends and another type begins. Human-readable set of rules and a list of exceptions. Something we can use later as a reference and a learning material. Absence of such description is the core issue, one that leads to all such ambiguities, more of which will no doubt be found in the future.

**Platform version**
```
Red 0.6.4 for Windows built 18-Mar-2021/22:28:01+03:00  commit #73d9bd2
```

**Comment by 9214** [comment]
Duplicate of https://github.com/red/red/issues/4562, duplicate of https://github.com/red/red/issues/3569.

**Comment by hiiamboris** [comment]
wow it's old
