### ISSUE TITLE
Publish to scoop

### ISSUE THREAD

**Issue by Milo123459** [red/red#4873]
Publish to [scoop](https://scoop.sh) - it's a better package manager for windows

**Comment by Milo123459** [comment]
Alright then?

**Comment by hiiamboris** [comment]
This is not the place for ad spamming. If you wish red on scoop, cooperate your efforts with the team on [Gitter](https://github.com/red/red/)

**Comment by Milo123459** [comment]
I'm not spamming ads I'm simply suggesting that it is published to scoop.

**Comment by hiiamboris** [comment]
We welcome champions if you wish to be one ;)

**Comment by Milo123459** [comment]
> We welcome champions if you wish to be one ;)

Whatever that means?

**Comment by hiiamboris** [comment]
Actually, this sounded familiar so this is what I've found: https://github.com/red/scoop-bucket
You sure Red isn't on scoop yet?
