### ISSUE TITLE
Dynamically update face/pane crashes view

### ISSUE THREAD

**Issue by qtxie** [red/red#4876]
**Describe the bug**
Run the following script, click on the window repeatedly.
```
Red []
getpanel: function [ i ] [ 
    compose/deep [ panel 200x55 0.30.30 [ ] draw []]
]
view [
    aa: panel 400x600 [ text "click to add panel" ] on-down [ 
        clear face/pane
        repeat n 10 [
            append face/pane layout/only getpanel n 
        ]
    ]
]
```
Crashes:
```
*** Runtime Error 1: access violation
*** at: 004341B7h
```

**Expected behavior**
No crash.

**Platform version**
Red 0.6.4 for Windows built 13-Apr-2021/6:52:09

**Comment by qtxie** [comment]
Related to GC.  No crash with `recycle/off`. No crash in debug mode.

**Comment by qtxie** [comment]
Not related to view backend. This also crashes:
```
loop 1000 [layout/only compose/deep [panel [ ] draw []]]
```

**Comment by qtxie** [comment]
It crashes inside `parse` when parsing empty draw block. It looks like the GC corrupted some states in parse. The parse is happened inside another `parse`, which makes it's even harder to find out which value was corrupted.

**Comment by dockimbel** [comment]
Note: the crash can only be reproduced when run from the GUI console. When compiled, even if the example code is wrapped into a `do [...]` section to force interpretation, no crash occurs.
