### ISSUE TITLE
MOLD & FORM go nuts over an url in the object

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4879]
**Describe the bug**

This demoes how `mold/part` works with and without an url:
![](https://i.gyazo.com/3cb5befdc501b94027d94402a0798aa9.gif)

**To reproduce**

Create an object with an url in it and mold/part or form/part it:
```
Red []
o1: object [
    field1: "value of field1"
    field2: "value of field2"
    field3: "value of field3"
    field4: "value of field4"
    field5: "value of field5"
]
o2: make o1 [
    field6: url://here
]
i: 0
view [
	style area': area 300x200 font-name system/view/fonts/fixed
	a1: area' rate 5 on-time [
		a1/text: mold/part o1 i: i + 1
		a2/text: mold/part o2 i
		a2/selected: a1/selected: as-pair 1 i + 1
	]
	a2: area'
]
```
1. Result makes no sense
2. Ending `]` is never printed

**Expected behavior**

The one to the left

**Platform version**
```
Red 0.6.4 for Windows built 18-Mar-2021/22:28:01+03:00  commit #73d9bd2
```

**Comment by greggirwin** [comment]
That's a fun one. Great demo. Looking at the calls from object to url's `mold`, to string/encode-url, there are things that look suspicious if you don't know the code (like me). e.g. url/mold returning zero, `:size` mapping to `string/encode-url`'s `type` arg. That's where comments would really help.

**Comment by dockimbel** [comment]
Could we have some minimal code to reproduce the issue that does not involve View and GUI animations?

**Comment by hiiamboris** [comment]
```
>> form/part object [x: 1 u: u://rl] 1
== "x: 1^/u: u"
```
?

**Comment by hiiamboris** [comment]
Another issue appears with urls in blocks:
```
>> [http:// 1 2 3]
== [http://
>> mold/part [http:// 1 2 3] 999
== "[http://"
```
