### ISSUE TITLE
[CRASH] `size-text` punches WORMHOLES in code space-time

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4897]
**Describe the bug**

Took hours to track this pirate ☻
When `size-text` is called on a rich-text face that has negative width, flow of code becomes totally unpredictable, leading to most annoying debug sessions.

**To reproduce**
```
Red [needs: view]

recycle/off					

depth: 0
wrap: func [code [block!]] [		;) should display "OUT" for every "IN"
	print ["IN" depth: depth + 1]
	print try/all code
	print ["OUT" also depth depth: depth - 1]
]

rigged?: none
rig: has [r] [						;) wormhole generator
	print "rigging"
	rigged?: yes
	r: make-face 'rich-text
	r/size/x: -1					;) has to be negative
	size-text r						;) ends here
	quit							;) never reached
]

view [								;) somehow simple forever [try/all []] is not enough
	field rate 3 on-time [
		wrap [print "heartbeat"]
		wrap [rig]
		; unless rigged? [wrap [rig]]
	]
]
```
`wrap` function is supposed to finish normally regardless of what happens. However it never does, so every call of it leaves `stack` in an invalid state.

It then crashes on closing the view:
```
IN 1
heartbeat

OUT 1
IN 1
rigging
IN 2
heartbeat

OUT 2
IN 2
rigging
IN 3
heartbeat

OUT 3
IN 3
rigging
IN 4
heartbeat

OUT 4
IN 4
rigging

*** Runtime Error 95: no CATCH for THROW
*** at: 0041E0B5h
```

**Expected behavior**

`quit` should be reached:
```
IN 1
heartbeat

OUT 1
IN 1
rigging
```

If we comment `quit` out then:
```
IN 1
heartbeat

OUT 1
IN 1
rigging
0x0       ;) or some other pair
OUT 1

(repeats 3 times per sec)
```

**Platform version**
```
Red 0.6.4 for Windows built 18-Mar-2021/22:28:01+03:00  commit #73d9bd2
```

**Comment by hiiamboris** [comment]
Other issues where `95: no CAT for THROW` appears (may be somewhat related): 
https://github.com/red/red/issues/4547 https://github.com/red/red/issues/4497#issuecomment-639074552 https://github.com/red/red/issues/4375 https://github.com/red/red/issues/4323#issuecomment-819673337 https://github.com/red/red/issues/4319#issuecomment-631968841

**Comment by greggirwin** [comment]
Nice research. :+1:

**Comment by qtxie** [comment]
I'll close it as the size-text issue has been fixed.
