### ISSUE TITLE
Case returns none when last condition is matched but action is missing

### ISSUE THREAD

**Issue by zwortex** [red/red#4899]
**Before submitting**
 https://gitter.im/red/help?at=609d4d8d9f2c352db109513b

**Describe the bug**
In the following code the last condition is true, but there is no associated action. In such case, case returns none.

```
a: case [
    false [ "NOK" ]
    true
]
probe a ;= none
```
Initially the problem arose with the following snippet where the condition was missing.
```
a: case [
    false [ "NOK" ]
    []
]
probe a ;= none
```

Normally case returns none when they are no matched conditions at all :
```
a: case [
    false [ "NOK1" ]
    false [ "NOK2" ]
]
probe a ;= none
```

The same with no condition at all 
```
a: case []
probe a ;= none
```

**Expected behavior**
To be discussed. I would suggest a syntax error, or unset (i.e. no action to eval, therefore nothing to return). This is not a well formatted call, as if an argument was missing.

Note that R2/R3 returns true in that case.

**Platform version**
Red 0.6.4 for Windows built 13-May-2021/13:13:31

**Comment by zwortex** [comment]
Related notes and other cases in the [wiki](https://github.com/red/red/wiki/%5BNOTES%5D-Conditionnals)

**Comment by meijeru** [comment]
I observe that case does NOT require an action even in the before-last alternatives.
E.g. `case [false true [1]]` does not give a syntax error

**Comment by zwortex** [comment]
Case distinguishes conditions from actions by referring to their positions in the block. Not the type of the element : true could be the action returned in case of false. If the element is in an uneven position, it is a condition. If it is in an even position, it is an action. But if there is an uneven number of elements in the case block, that should enough to trigger a syntax error. And that would cover your case as well.

**Comment by greggirwin** [comment]
We need to distinguish between elements and expressions. `Case`  evaluates expressions, so the number of elements (values) doesn't matter. e.g. 
```
>> case [even? 1 ['nope]]
== none
>> case [even? 1 ['nope] 12 // 5 ['yup]]
```
And since the expressions can be dynamic, there's no way to know without evaluating them.

**Comment by zwortex** [comment]
When compiling, a syntax error is raised. For instance, this script :

```
Red []
a: 2
b: case [
    a == 1 [ "1" ]
    []
]
probe b ;= none
```

triggers that error :

```
*** Compilation Error: CASE is missing a value    
*** in file: D:\Developpements\RedTest\test.red   
*** near: []                                      
```

**Comment by dockimbel** [comment]
Now an error occurs if the action part is missing.
