### ISSUE TITLE
GUI console caret can be placed outside the input line

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4918]
**Describe the bug**
![](https://i.gyazo.com/d6b1b5eba14b5e9dad73547cb1f9bfc8.gif)

**To reproduce**

Key sequence: (any input) Home Shift-End Home (any input)

**Expected behavior**

Stays within the input line (;

**Platform version**
```
Red 0.6.4 for Windows built 13-Jun-2021/10:10:47+03:00  commit #79ded2f
```

**Comment by greggirwin** [comment]
That's a fun one.
