### ISSUE TITLE
Alignment of text in a field and a text-list are different

### ISSUE THREAD

**Issue by Rebol2Red** [red/red#4922]
Red 0.6.4 for Windows built 3-Jul-2021/13:08:38+02:00  commit #ef6ca5e

d: ["text1" "text2"]
view [
	f: field font-size 20 return
	t: text-list 100x38 font-size 20 data d return
]

![Knipsel](https://user-images.githubusercontent.com/18308797/124364089-88235780-dc3f-11eb-9755-ce996408a912.JPG)

**Comment by greggirwin** [comment]
This is the native control's behavior (unless you can find native apps and the APIs they use to that prove me wrong :^), so out of our control in the native UI. One of the reasons we're working on a non-native GUI system is so we have more control.
