### ISSUE TITLE
Routine typechecks aren't working

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4928]
**Describe the bug**

A few tests.

## 1
```
Red []
rou: routine [x [float!]][probe "entered"]
probe rou 123
```
Compiling with `-r -d` I get:
```
*** Runtime Error 98: assertion failed
*** in file: /d/devel/red/red-src/red/runtime/datatypes/float.reds
*** at line: 67
***
***   stack: red/float/get 00000062h
***   stack: red/float/get 02754A34h
```
Expected: error during compilation

## 2

Same, but interpreted call
```
Red []
rou: routine [x [float!]][probe "entered"]
do [probe rou 123]
```
Compiled output is fine:
```
*** Script Error: rou does not allow integer! for its x argument
*** Where: rou
*** Stack: probe
```

## 3

```
Red []
rou: routine [x [string!]][probe "entered"]
probe rou 123
```
Compiled as `-d -r` output:
```
entered
123
```

Wrapped in `do []` it throws a runtime error as expected.

----

So when compiled it is clueless about the type, unless one of these lines crashes it:
https://github.com/red/red/blob/1e4fb1b4aa4238c1c56b2c26890fdf3879be5384/runtime/interpreter.reds#L290-L295

When interpreted it tries to check the type, but also may crash as in #4927 

**Expected behavior**

- no crashes
- compiler errors when routine typecheck fails

Right now, routine code has to do all the checks manually, and types/typesets cannot be used for documenting the accepted types, having to accept `any-type!` for each argument.

**Platform version**
```
Red 0.6.4 for Windows built 4-Jul-2021/2:04:09+03:00  commit #1e4fb1b
```

**Comment by dockimbel** [comment]
They are "not working" because they are not implemented yet.

**Comment by hiiamboris** [comment]
We should at least be able to use typesets for documentation. And do the checks manually then.

**Comment by dockimbel** [comment]
Support for a few standard typesets has been added: https://github.com/red/red/commit/6c7556e17e4d928df5ef694543ebf81c46aa5c94

I just need to write some unit tests for those cases, then I can merge that branch.

**Comment by dockimbel** [comment]
Tests and fixes have
