### ISSUE TITLE
repeated prin messes up output

### ISSUE THREAD

**Issue by meijeru** [red/red#4929]
Run the following small program:
```
Red [ ] print "do print"
repeat n 3 [prin " " prin n] print ""
```
It outputs:
```
do print
 1 2 3
```
as it should
Now comment `print "do print"` and run again
The output is:
```
 1 12 1 123
```
The same error when the looping construct is `loop`. Note that calling `prin` several times without looping gives correct results.

**Comment by hiiamboris** [comment]
Related: https://github.com/red/red/issues/2986 https://github.com/red/red/issues/2679
Now closed: https://github.com/red/red/issues/4313 https://github.com/red/red/issues/4521 https://github.com/red/red/issues/4742

These print issues seem to never end, highlighting a problem with GUI console design.

**Comment by meijeru** [comment]
In this case, it looks like a buffer is not correctly addressed ?!?

**Comment by meijeru** [comment]
That was quick! What does this do to the other issues mentions by @hiiamboris?

**Comment by qtxie** [comment]
For #2986, we need to support [ANSI escape code](https://en.wikipedia.org/wiki/ANSI_escape_code) in the gui-console.
Fixed #2679 in the gui-console.

**Comment by hiiamboris** [comment]
> For #2986, we need to support ANSI escape code in the gui-console.

Why can't GUI console handle CR char directly?

**Comment by qtxie** [comment]
> > For #2986, we need to support ANSI escape code in the gui-console.
> 
> Why can't GUI console handle CR char directly?

`prin` and `print` treat the string as it is for now, not process it character by character. So we need to rewrite the `prin*` functions to be able to handle any control code in the string.
