### ISSUE TITLE
TRANSCODE/NEXT and LOAD/NEXT problems with non-ASCII chars

### ISSUE THREAD

**Issue by giesse** [red/red#4933]
(Tested on latest commit on master as of today.)
```
>> load/next {"Gab’s Books"^/Work In P} 'pos
== "Gab’s Books"
>> pos
== "ork In P"
>> load/next {"Gab's Books"^/Work In P} 'pos
== "Gab's Books"
>> pos
== "^/Work In P"
```
Also:
```
>> transcode/next "фывапр abcdef"
== [фывапр "f"]
```
But:
```
>> to "" second transcode/next to #{} "фывапр abcdef"
== " abcdef"
```

**Comment by dockimbel** [comment]
The issue occurs only on string! input, it works fine on binary! input.

**Comment by giesse** [comment]
> The issue occurs only on `string!` input, it works fine on `binary!` input.

That's what I meant with the "But:" example, sorry for not being clear. (@hiiamboris found that out.)
