### ISSUE TITLE
`system/console/prompt` and `system/console/result` may be used to prematurely exit a console

### ISSUE THREAD

**Issue by Oldes** [red/red#4936]
It's possible to crash a console when making an error in `prompt` or `result` system/console functions...
Like:
```red
system/console/prompt: does [some-error-here]
```

**Comment by hiiamboris** [comment]
Not a crash though, just terminates the REPL:
```
>> system/console/prompt: does [some-error-here]
== func [][some-error-here]
*** Script Error: some-error-here has no value
*** Where: prompt
*** Stack: ask string? prompt
```

**Comment by dockimbel** [comment]
I've removed the "CRASH" mentions in the issue title, as there is no crash strictly speaking (native level error), just an regular error that makes the console engine exit.

I will add an error catching and proper restoration procedure for those sensitive values.

**Comment by dockimbel** [comment]
Relates to #4936.
