### ISSUE TITLE
CLIP with SHAPE commands doesn't work

### ISSUE THREAD

**Issue by toomasv** [red/red#4939]
According to [docs](https://github.com/red/docs/blob/master/en/draw.adoc#228-clip) `clip` supports two forms: 1) by rectangular area and 2) by shape dialect commands.

Following snippet should clip rectangular area formed by shape dialect commands, but it doesn't:
```
view [box 200x200 beige draw [
   clip [move 10x10 line 100x10 100x50 10x50 close] 
        [fill-pen gold box 10x10 198x198]]]
```
Nor could I make it clip by any other shape dialect region.

```
>> about
Red 0.6.4 for Windows built 29-Jul-2021/13:31:32+03:00  commit #2dc7612
```

**Comment by qtxie** [comment]
BTW, the clip shape will always be closed. The following code also works.
```
view [box 200x200 beige draw [
   clip [move 10x10 line 100x10 100x50 10x50] 
        [fill-pen gold box 10x10 198x198]]]
```
