### ISSUE TITLE
unicode/load-utf8-buffer corrupts memory

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#494]
I'm having memory corrupted when I call load-utf8-buffer with a pre-existing string (similar to what load-utf8-stream does). When load-utf8-buffer allocates a new series, it sort of ensures it's long enough to hold the output. Also, most processing branches expand the series when necessary, but not all. The simplest case says this:

```
assert buf1 <= end          ;-- should not happen if we're good
```

This is not the case when using a pre-existing series.

Further, it claims that it can be used in streaming mode, but it does not examine or reset the flags of an existing series, rather it assumes it's Latin1 type.

Here's a case apparently corrupting code memory:

```
Red []

r: routine [
    from    [string!]
    to      [string!]
][
    to/header: TYPE_STRING
    to/head: 0
    unicode/load-utf8-buffer
        as-c-string string/rs-head from  string/rs-length? from
        GET_BUFFER (to)  null
    to/cache: null
]
r from: "0123456789abcdefghijklmnopqrstuvwxyz"  to: ""
print [from to]
```

**\* Runtime Error 1: access violation
**\* at: 08066E79h

**Comment by rebolek** [comment]
Under 0.6.1 I can’t compile the example with this strange error:

```
Compiling E:\Code\red-bugs\test.red ...
*** Compilation Error: expected a block for IF-BODY instead of word! value
*** in file: %/E/Code/red-bugs/test.red
*** near: [binary! hex [as-color bin/1 bin/2 bin/3]]
```
