### ISSUE TITLE
Wrong console prompt position after a LIST-DIR call

### ISSUE THREAD

**Issue by dockimbel** [red/red#4942]
From the GUI console (not tested from CLI), calling `ls` or `list-dir` results in wrong prompt position:

![image](https://user-images.githubusercontent.com/411393/128020383-20b5faf2-6a0b-49f1-8307-c4e72c3af58e.png)

**Comment by dockimbel** [comment]
I've tried several simple fixes, but they destroy the columns alignment...

**Comment by qtxie** [comment]
It is due to a `prin` issue (#2679) was fixed. LIST-DIR has a workaround for this issue.
