### ISSUE TITLE
Doc of map wrong

### ISSUE THREAD

**Issue by toomasv** [red/red#4949]
There is following proposition in map [documentation](https://github.com/red/docs/blob/master/en/datatypes/map.adoc):

>Trying to access a key not defined in a map will:
>* produce an error if the path syntax is used.
>* return a none value if select is used.

No error is produced in either case, only `none` is returned.

Correct would be something like:

"Trying to access a key not defined in a map will return a `none` value."

**Comment by hiiamboris** [comment]
Should this be in https://github.com/red/docs/issues ?

**Comment by toomasv** [comment]
Ah, yes, sorry!
