### ISSUE TITLE
FIND accepts binary target, but PARSE not

### ISSUE THREAD

**Issue by Oldes** [red/red#4952]
Although `find` _somehow_ accepts binary as its search value (without any conversion):
```red
>> find "a" #{61}
== "a"
>> find to-string #"^(7f)" to-binary #"^(7f)"
== "^~"
>> find to-string #"^(80)" debase/base "80" 16
== "^(80)"
```
`parse` don't handle it:
```red
>> parse "a" [#{61}]
== false
>> parse "#{61}" [#{61}]
== false
>> parse "61" [#{61}]
== false
```

**Comment by greggirwin** [comment]
The "somehow" is just using `as red-string!` on the search value, which could possibly also be done in `parse`.

Are there use cases for this you have in mind? I haven't done mixed binary/string content parsing myself that I recall. Formats certainly exist that mix them, so having a couple of those as examples, would be great to show the power of this feature.

**Comment by Oldes** [comment]
To be honest, I'm so far just looking for some consensus and have no idea, what would be the most useful. If nothing else, I think that `find` and `parse` should be consistent.

**Comment by dockimbel** [comment]
That's a bug, that combination should not be allowed. It works only for ASCII strings.
