### ISSUE TITLE
Cursor blink doesn't respect Windows setting

### ISSUE THREAD

**Issue by mark-summerfield** [red/red#4953]
When I tried red-64.exe on Win7-64 it compiled and then the GUI console came up but with a blinking cursor. In my windows settings I have set the cursor blink rate to 0 (zero) since I can't work with blinking cursors. Red ought to respect this setting or at least provide an option to stop blink or set the rate down to 0.

I know that the great majority of people like blinking cursors but for the minority of us they are awful. See [jurta/noblink](https://jurta.org/en/prog/noblink).

**Comment by hiiamboris** [comment]
As a temporary workaround I suggest creating an init script:
```
Red []
gui-console-ctx/caret/actors/on-time: func [face event] [face/color: gui-console-ctx/caret-clr 'done]
```
And passing it to the GUI console on startup: `red --catch <full-pathname-of-the-script>`

**Comment by greggirwin** [comment]
Certainly an edge case setting I didn't know about. Thanks for the report @mark-summerfield.

**Comment by greggirwin** [comment]
And thanks for the workaround @hiiamboris.

**Comment by mark-summerfield** [comment]
Thank you that works fine.

I now have:
`noblink.red` with the code you gave me above and `red.bat` containing:
`c:\bin\red-064.exe --catch c:\bin\noblink.red %*`
So now I can have another go experimenting with Red.

I've left this open though because I think that red should read the Windows CursorBlinkRate at GUI startup and respect it automatically.

BTW I'm finding [Red from Python](https://github.com/red/red/wiki/Coming-to-Red-from-Python) very helpful.

**Comment by greggirwin** [comment]
If you have any comments, or want to improve the Python primers, I'm sure @galenivanov will be glad for any support and feedback.

**Comment by mark-summerfield** [comment]
I just ran `red-064.exe --help` which lists lots of options but _not_ `--catch`. Should I report this as a bug?

**Comment by hiiamboris** [comment]
`red-064` is nearly 3 years old. Use the nightly builds before reporting anything.

**Comment by mark-summerfield** [comment]
> `red-064` is nearly 3 years old. Use the nightly builds before reporting anything.

I went to the download page and there is a big link to red-064 at the top, so naturally I used it.
Anyway, I'll try the nightly now.
