### ISSUE TITLE
DO doesn't evaluate path!

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#497]
red>> b: [1]
== [1]
red>> p: 'b/1
== b/1
red>> do p
== b/1

**Comment by rebolek** [comment]
This still seems buggy to me:

Rebol2
---

```
>> b: [1]
== [1]
>> p: 'b/1
== b/1
>> do p
== 1
```

Red 0.6.1 compiler
---

Source:
```
Red []

b: [1]
p: 'b/1
probe do p
```

Output:
```
E:\Code\red (master)
λ test
b/1
```

Red 0.6.1 interpreter
---

```
red>> b: [1]
== [1]
red>> p: 'b/1
== b/1
red>> do p
== false
```

**Comment by 9214** [comment]
https://github.com/red/red/issues/3561
