### ISSUE TITLE
[Regression] get path evaluates its argument

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4988]
**Describe the bug**
```
>> about
Red 0.6.4 for Windows built 13-Jun-2021/10:10:47+03:00  commit #79ded2f
>> c: context [f: does [print 123]] get 'c/f
== func [][print 123]

>> about
Red 0.6.4 for Windows built 4-Jul-2021/2:04:09+03:00  commit #1e4fb1b
>> c: context [f: does [print 123]] get 'c/f
123
```

**Expected behavior**

No evaluation.

**Comment by qtxie** [comment]
`get/any` works as expected.
```
>> c: context [f: does [print 123]] get/any 'c/f
== func [][print 123]
```

**Comment by hiiamboris** [comment]
`get/any` shouldn't even exist IMO ;)

**Comment by greggirwin** [comment]
Good note @qtxie but `/any` is there _only_ for `unset!` handling, isn't it?

**Comment by qtxie** [comment]
@greggirwin According to the documents, yes. I pointed it out as I don't see a code branch to handle this case. The `get?` parameter in `interpreter/eval-path` should be used for it, but it's set by the `/any` refinement now. @dockimbel Do we need to add another `any?` parameter for the function?

**Comment by hiiamboris** [comment]
Result of `? system/console/do-command` is fun

**Comment by hiiamboris** [comment]
```
>> o: object [x: 1 unset 'x]
== make object! [
    x: unset
]
>> ? o/x
*** Script Error: value needs a value
*** Where: set
*** Near : ? o/x
*** Stack: ? help-string  
```

**Comment by dockimbel** [comment]
> Do we need to add another any? parameter for the function?

Yes, it seems to be the simplest solution.
