### ISSUE TITLE
Memory CORRUPTION during MOLD

### ISSUE THREAD

**Issue by hiiamboris** [red/red#4991]
**Describe the bug**

Need 2 scripts.
1. Generator script `1.red`:
```
Red [] 
make-dir %tmp/
b: [[[]]]
random/seed 1337
repeat i 3000 [
	do random/only [
		[append/only b/1 copy []]
		[append random/only b/1 copy/part random n: {^A^B^C^D^E^F"""""^{^}фывапроолджэ} random length? n]
		[new-line skip b/1 random length? b/1 yes]
	]
	write probe rejoin [%tmp/ i] b mold/only b
]
```
2. Loader script `2.red`:
```
Red [] 
repeat i 3000 [
	if error? e: try [load rejoin [%tmp/ i]] [print [i e]]
]
```

Run `red --cli 1.red` then `red --cli 2.red`
Output of `2.red` is:
```
1154 *** Syntax Error: (line 185) invalid string at {ж"э^Eл^D^A"^{"о^F^Cаы%]
*** Where: transcode
*** Stack: load
1165 *** Syntax Error: (line 186) invalid string at {^F"^}ол"жэо"ф^A^{д"^Dы
*** Where: transcode
*** Stack: load
1214 *** Syntax Error: (line 78) invalid string at "]
*** Where: transcode
*** Stack: load
2304 *** Syntax Error: (line 356) invalid character at }] [{^}ыпфлэ^Dжрд^C"^A
*** Where: transcode
*** Stack: load
2618 *** Syntax Error: (line 128) invalid string at "ап}]
*** Where: transcode
*** Stack: load
```

The 1st two errors are obvious: `}` gets replaced by `%` and by `^E`.
For the rest, there is an unclosed string in some of the *preceding* lines, not near value that is reported. Again `}` gets replaced by `õ`, `Å` and `¥`.

**Platform version**
```
Red 0.6.4 for Windows built 7-Oct-2021/14:56:13+03:00  commit #7218fb4
```

**Comment by hiiamboris** [comment]
A continuation of https://github.com/red/red/issues/4291, though that one doesn't produce any garbage for me anymore.

We're also experiencing an issue that in ~1% cases a perfectly valid HTTP request (with `write/info`) fails with the server reporting 400 Bad Request. I suspect the same cause for it.

**Comment by dockimbel** [comment]
No need to run script `2.red`, the following code from console is enough to reproduce the issue:
```
>> load %tmp/1254
*** Syntax Error: (line 78) invalid string at "] 

*** Where: transcode
*** Stack: load 
```

**Comment by dockimbel** [comment]
> The 1st two errors are obvious: } gets replaced by % and by ^E.

How can I see that?

**Comment by dockimbel** [comment]
If the GC is disabled, no issue happens.
