### ISSUE TITLE
Symantec intercepts hello.red when explicitly targeted to Windows

### ISSUE THREAD

**Issue by memophen** [red/red#500]
When the example script hello.red or a home-brewed script is compiled with option `-t Windows`, the executable is intercepted by Symantec Endpoint Protection (12.1.1101.401), due to the risk "Suspicious.Cloud". This concerns Red v0.3.2, compiled on a Windows Vista platform.

It does not happen when I compile with `-t MSDOS` or with no target option at all. (May I conclude that MSDOS is the default target on a Windows platform?)

For hello.reds and other Red/System programs, I see no difference whether it's compiled with Windows or MSDOS as target: the executables look pretty much the same and Symantec keeps quiet.

**Comment by dockimbel** [comment]
Symantec is not reporting any false positive in a [new](https://www.virustotal.com/en/file/3b14d0120116bcb9a5941ed5a9406c1053b39f7c6bbab247038cc0c9e43ff748/analysis/1454785416/) scan, so I'm closing this ticket.
