### ISSUE TITLE
AT doesn't implement 0 hole

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#501]
red>> at tail "abc" -1
== "bc"
red>> at tail "abc" 0
== "c"

R3 & R2:

> > at tail "abc" -1
> > == "c"
> > at tail "abc" 0 
> > == ""

**Comment by rebolek** [comment]
@dockimbel You wrote "Index 0 should raise an error in Red". Is this true still? Currently it works as Rebol:

```
red>> at tail "abc" 0
== ""
```
