### ISSUE TITLE
Red Does Not Work On 64-bit macOS & Android

### ISSUE THREAD

**Issue by Wajinn** [red/red#5012]
Tried to get cross-compiled Red app to run on macOS and Android.  This appears not possible, so looks like failure of promised features.  What can be done to get a Red app working on 64-bit OSes?  When will this be possible or should Red website and documentation be updated to reflect this is not possible?

**Comment by hiiamboris** [comment]
Hi @Wajinn 
See https://github.com/red/red/issues/4652
We'll get there when we'll get there. The site has some out of date info, true, but don't worry: plan to support those hasn't changed :)

**Comment by Wajinn** [comment]
Thank you sir for your reply.  So this problem has existed for more than 2 or 3 years.  I like the features that I have read about that Red supposedly has and was hoping to use it on macOS, iOS, and Android.  

Is this issue not considered important?  Can you please give an estimation of how long or how many more years before the 64-bit problem will be resolved?

**Comment by hiiamboris** [comment]
If I were you I would not rely on any estimates and used what tools are already available.
