### ISSUE TITLE
[View, Regression] `text` and `field` cannot be set to whitespace

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5014]
**Describe the bug**

Regression happened between 29 Jul 2020 and 17 Aug 2020:
```
view [t: text on-created [t/text: " "]]
```
This code produces a weird error for `text` and `field` faces:
```
*** Script Error: invalid argument: none
*** Where: find
*** Stack: view show show do-safe on-created
```

**Expected behavior**

No errors.

**Platform version**
```
Red 0.6.4 for Windows built 17-Dec-2021/23:20:59+03:00  commit #2b5d37a
```

**Comment by qtxie** [comment]
No this issue in commit fe574eacde9f08db2f83ceea579bfbea689f4e25.
