### ISSUE TITLE
[Lexer] BC (and far AD) dates don't round trip

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5023]
**Describe the bug**
```
>> 02/03/-4
*** Syntax Error: (line 1) invalid date at 02/03/-4
*** Where: set
*** Stack: load 
>> 02/03/-04
*** Syntax Error: (line 1) invalid date at 02/03/-04
*** Where: set
*** Stack: load 
>> 02/03/-004
== 2/Mar/-4
>> 02/03/-0004
== 2/Mar/-4
>> load mold 02/03/-0004
*** Syntax Error: (line 1) invalid date at 2/Mar/-4
*** Where: transcode
*** Stack: load  
```

**Expected behavior**

`load mold` should work

**Platform version**
```
Red 0.6.4 for Windows built 22-Dec-2021/17:36:36+03:00  commit #328c904
```

**Comment by hiiamboris** [comment]
Addendum:
```
>> d: 1/1/1
== 1-Jan-2001
>> d/year: 15000
== 15000
>> d
== 1-Jan-15000
>> load mold d
*** Syntax Error: (line 1) invalid date at 1-Jan-15000
*** Where: transcode
*** Stack: load 
```

**Comment by hiiamboris** [comment]
Compiler's treatment of these date is even worse:
```
Red ["run me"]

save/all %2.red [
	Red ["compile me"]
	probe b: [1/2/-0003/4:5:6.7]
	probe length? b
]
```
`red -c 2.red & 2.exe`:
```
[1 /Feb /-3 /4:05:06.7]
4
```

**Comment by dockimbel** [comment]
About your addendum, the [documentation](https://github.com/red/docs/blob/master/en/datatypes/date.adoc) states it clearly:

> Supported dates range from 1/Jan/-16384 to 31/Dec/16383, wrapping around on overflowing math operations. On input, that range is reduced from 1/Jan/-9999 to 31/Dec/9999 for practical reasons.

**Comment by dockimbel** [comment]
> >> 02/03/-04
> *** Syntax Error: (line 1) invalid date at 02/03/-04
> *** Where: set
> *** Stack: load 

I cannot reproduce that. 

```
>> 2/03/-04
== 2-Mar-1996
```

**Comment by dockimbel** [comment]
> Compiler's treatment of these date is even worse:

That's a separate issue...

**Comment by hiiamboris** [comment]
> > > > 02/03/-04
> > > > *** Syntax Error: (line 1) invalid date at 02/03/-04
> > > > *** Where: set
> > > > *** Stack: load
> 
> I cannot reproduce that.
> 
> ```
> >> 2/03/-04
> == 2-Mar-1996
> ```

You missed zero.

**Comment by hiiamboris** [comment]
File generated before the last commit looks like this:
```
    Red ["compile me"]
    probe b: [1/Feb/-3/4:05:06.7]
    probe length? b
```
After the last commit like this:
```
    Red ["compile me"]
    probe b: [1/Feb/-0003/4:05:06.7]
    probe length? b
```
