### ISSUE TITLE
LENGTH? on port returns random integer

### ISSUE THREAD

**Issue by gurzgri** [red/red#5032]
**Describe the bug**
LENGTH? on a port returns some random integer value instead of the length as determined in the ports LENGTH? actor.

**To reproduce**
```
Red []
register-scheme make system/standard/scheme [name: 'len actor: context [
    open: func [port] [port]
    length?: func [port] [20]
]]
probe length? port: open len://test ;== 75611332, expected 20
```

**Expected behavior**
Return the length as determined in the ports LENGTH? actor.

**Platform version**
Red 0.6.4 for Windows built 30-Dec-2021/14:02:56+01:00  commit #895d4cb

**Comment by hiiamboris** [comment]
have you tested on the IO branch?

**Comment by hiiamboris** [comment]
nvm, same junk:
```
>> probe length? port: open len://test
42713084
== 42713084
```
