### ISSUE TITLE
transcode/into overwrites its into block argument

### ISSUE THREAD

**Issue by endo64** [red/red#5042]
**Describe the bug**
transcode/into overwrites its into block argument

**To reproduce**
```red
>> b: [1 2 3] transcode/into "4 5"  next b head b
== [1 4 5]
```

**Expected behavior**
```red
>> b: [1 2 3] transcode/into "4 5"  next b head b
== [1 4 5 2 3]
```

**Platform version**

```
Red 0.6.4 for Windows built 19-Jan-2022/0:46:09+03:00  commit #6557e9b
```

**Comment by endo64** [comment]
Duplicate of https://github.com/red/red/issues/4109

Also look at:
https://github.com/red/red/issues/2927
https://github.com/red/red/issues/4515

**Comment by dockimbel** [comment]
According to the conclusion of #3340 about `/into`, the behavior will be appending.
