### ISSUE TITLE
`trim/tail` on `binary!` is incorrect, when there are just nulls

### ISSUE THREAD

**Issue by Oldes** [red/red#5046]
There seems to 1-off error when using `/tail` on binary:
```red
trim/tail #{000000}
== #{00} ;<-- WRONG, should be #{}
```
also:
```red
>> head trim/tail probe at #{11000000} 1
#{11000000}
== #{11} ;<- OK
>> head trim/tail probe at #{11000000} 2
#{000000}
== #{1100} ;<- WRONG, should be #{11}
>> head trim/tail probe at #{11000000} 3
#{0000}
== #{110000}  ;<- WRONG, should be #{1100}
>> head trim/tail probe at #{11000000} 4
#{00}
== #{11000000}  ;<- WRONG, should be #{110000}
>> head trim/tail probe at #{11000000} 5
#{}
== #{11000000} ;<- OK
``` 

`trim/head` is ok:
```red
>> trim/head #{000000}
== #{}
```

**Comment by Oldes** [comment]
Related to: https://github.com/red/red/issues/3663

**Comment by dockimbel** [comment]
> trim/tail #{000000}
> == #{00} ;<-- WRONG, should be #{}

Fixed by commit: https://github.com/red/red/commit/e707df880de6c9c3652886262eeb200e01f3a7b2

> >> head trim/tail probe at #{11000000} 2
> #{000000}
> == #{1100} ;<- WRONG, should be #{11}

This looks fine to me. `trim/tail` should not go back past the index you provide.

**Comment by Oldes** [comment]
It's not fine.. it should remove all 3 bytes visible from the `probe`, not just 2.

**Comment by greggirwin** [comment]
```
>> head trim at #{11000000} 2
== #{11}
>> head trim/tail at #{11000000} 2
== #{1100}
```

**Comment by dockimbel** [comment]
You're right, I've overlooked it.
