### ISSUE TITLE
Console -> Help -> About: VID error

### ISSUE THREAD

**Issue by kpeters58** [red/red#5048]
>> about/cc
Red 0.6.4 for Windows built 21-Jan-2022/9:33:03-08:00  commit #89896f9
>> 
*** Script Error: VID - invalid syntax at: [fstk-logo at 0x160]
*** Where: do
*** Near : args
*** Stack: ask ask do-events do-actor do-safe layout cause-error

**Comment by greggirwin** [comment]
Looks like a regression. Works in my 11-Jan build here.

**Comment by greggirwin** [comment]
Just synced and did a fresh build here, and still works.

**Comment by hiiamboris** [comment]
Can't reproduce either.

**Comment by dockimbel** [comment]
Cannot reproduce using the lastest commit on master.

**Comment by dockimbel** [comment]
I'll close this ticket. Feel free to reopen or ask for reopening if it can be reproduced.
