### ISSUE TITLE
Children of `base` face do not show up

### ISSUE THREAD

**Issue by toomasv** [red/red#5051]
**Describe the bug**
Faces in pane of `base` face are not shown, although they are present.

**To reproduce**
E.g. Enter following in console:
```
view lay: layout [base 200x100 with [pane: layout/only [button "OK" [print "hi"] base brick loose]]]
```
Nothing shows up, although clicking on base where button should be, buttons' on-click actor fires, and dragging invisibvle brick base out of its parents' area and back again makes it visible.

**Expected behavior**
As it was before February 2021. See below

**Screenshots**
[![base-regression](https://toomasv.red/images/Errors/base-colors.gif)](https://toomasv.red/images/Errors/base-colors.gif)

**Platform version**
```
>> about
Red 0.6.4 for Windows built 18-Jan-2022/23:46:09+02:00  commit #6557e9b
```

**Comment by qtxie** [comment]
FYI. The base face can only show base faces in its `pane` in current Direct2D backend.

**Comment by qtxie** [comment]
@toomasv Use `panel` as parent face if possible or use the GDI+ backend.
```
Red [
	Title:	 "Red GUI App"
	Needs:	 View
	Config:	 [draw-engine: 'GDI+]
]
```

**Comment by toomasv** [comment]
@qtxie Good, thank you!

**Comment by qtxie** [comment]
There are some issues when using base face as parent face since the beginning. Even the GDI+ backend has some issues. For example, it doesn't work properly when using semi-transparent base face as a child face of a base face. The only reliable way is put only base faces inside base face.

**Comment by greggirwin** [comment]
Something good to note in the wiki: https://github.com/red/red/wiki/%5BHOWTO%5D-VID-and-View-(GUI)-hints-and-tips

We should encourage people strongly to use panels, rather than base faces as containers.

**Comment by qtxie** [comment]
Close it now as it won't be fixed in the native GUI backend.
