### ISSUE TITLE
[Regression] R/S Compiler won't accept float arguments to % and // anymore

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5054]
**Describe the bug**

The following script:
```
Red/System []
probe 123.0 // 10.0
probe 123.0 % 10.0
```
With:
- `red-01jun19-66d20bd7.exe` compiles, outputs `3.0` for both
- `red-23jul19-613d71cf.exe` and later errors out:
```
*** Compilation Error: argument type mismatch on calling: //
*** expected: [number!], found: [float!]
*** in file: %/D/devel/red/unicode/1.red
*** at line: 2
*** near: [123.0 10.0]
```

**Expected behavior**

`3.0`

**Platform version**
```
Red 0.6.4 for Windows built 14-Jan-2022/17:48:17+03:00  commit #4923e32
```

**Comment by qtxie** [comment]
Those operators are only for integer! now.
https://static.red-lang.org/red-system-specs.html#section-4.4

> 4.4.3 Math operations
> 
> All Red/System math operators (+, -, *, /, //, %) are supported. The default rounding method on results is "rounding to nearest". Both operands need to be of float32! types (no implicit casting).
> 
> The modulo (//) and remainder (%) operators give the same results when used on float32! values.

**Comment by hiiamboris** [comment]
OK in that case I expect the compiler to tell me that instead of saying that `float!` doesn't fit the `number!` somehow

**Comment by qtxie** [comment]
Don't expect a _temporary_ compiler works perfectly. We'll do better in the self-hosted toolchain.

**Comment by hiiamboris** [comment]
OK feel free to close it then.

**Comment by dockimbel** [comment]
We have dropped native support for modulos on floats as the behavior differs between platforms. `fmod()` is the only consistent way.
