### ISSUE TITLE
GUI console doesn't start

### ISSUE THREAD

**Issue by ushakov-s** [red/red#5073]
It doesn't show any error messages. Just doesn't run.
I used precompiled binary for Windows. Any "latest" version for years. https://static.red-lang.org/dl/auto/win/red-latest.exe
Stable release works fine.
Windows 7 32bit Home.

**Comment by hiiamboris** [comment]
Try `flip-exe-flag %gui-console-2022-2-17-41962.exe` from a working Red console, then run this buggy console. Does it print anything?

**Comment by hiiamboris** [comment]
Or better, can you build the console from sources?
Instructions are [here](https://github.com/red/red/#running-red-from-the-sources-for-contributors), but command will be `do/args %red.r "-r -t -d Windows %environment/console/GUI/gui-console.red"` (notice -d)

**Comment by hiiamboris** [comment]
Correction: `do/args %red.r "-r -d -t Windows %environment/console/GUI/gui-console.red"`

**Comment by ushakov-s** [comment]
Rebol output:
 do/args %red.r "-r -d -t Windows %environment/console/GUI/gui-console.red"

-=== Red Compiler 0.6.4 ===-

Compiling C:\Users\1\Sets\Äèñòðèáóòèâû\dev\Red\red-master\environment\console\GUI\gui-console.red ...
Compiling compression library...
...compilation time : 6357 ms

Target: Windows

Compiling to native code...
...compilation time : 229777 ms
...global words     : 25832 (78.53%)
...linking time     : 32748 ms
...output file size : 5126144 bytes
...output file      : C:\Users\1\Sets\Äèñòðèáóòèâû\dev\Red\red-master\gui-console.exe

== none

And created gui-console.exe can't launch.

**Comment by hiiamboris** [comment]
What's GUI console output when it is run from the terminal?

**Comment by hiiamboris** [comment]
@ushakov-s also what is the *last working* version for you?

**Comment by ushakov-s** [comment]
GUI console output is empty. It just try to run and then exit immediately. No any messages appears.

I didn't update Red every night, so I can't to say which working version is really last, but red-04nov20-277584b4c.exe is working fine and all versions since 2021 doesn't.

**Comment by ne1uno** [comment]
Platform Update for Windows 7, SP1 may help?
 the gui windows back-end changed to Direct2D sometime around then.
https://www.microsoft.com/en-us/download/details.aspx?id=36805

**Comment by qtxie** [comment]
@ushakov-s Please try the Platform Update for Windows 7. If it's still not working, you can use the GDI+ backend by adding `draw-engine: 'GDI+` in the header of the `%environment/console/GUI/gui-console.red`.
```
Red [
    ...
    Needs:	 [View JSON CSV]
    Config:	 [gui-console?: yes red-help?: yes draw-engine: 'GDI+]
    ...
```

**Comment by ushakov-s** [comment]
Updating to Win7 SP1 has no effect.
So, changing GUI backend to GDI+ is the same. Behavior remains unchanged.

**Comment by hiiamboris** [comment]
But recent `--cli` console works for you, and you can use `view`?

**Comment by dockimbel** [comment]
At this point, it's most likely not an issue with Red, but your local environment. If you have any third-party anti-virus, disable it. Also disable the Windows Defender AV entirely to see if that's the one blocking this.

**Comment by ushakov-s** [comment]
cli console works, but view inaccessible:
*** Script Error: view has no value
*** Where: catch
*** Near : Red [title: "Hello" needs: 'view] view []
*** Stack:

**Comment by hiiamboris** [comment]
Try automatically built CLI console, or add `Needs: View` into the header of `console/CLI/console.red` before building it.

**Comment by ushakov-s** [comment]
Well, now CLI reports:
*** Runtime Error 1: access violation
*** at: 004F17B5h
I will try to catch it by sysinternals tools.

**Comment by hiiamboris** [comment]
no, better build it with `-d` flag and paste the printed trace here

**Comment by hiiamboris** [comment]
I would expect GUI console built with `-d` also to crash with a message though... strange if it's silent

**Comment by hiiamboris** [comment]
No, it always worked for me with `-t` Windows. `-d` handles that.

**Comment by hiiamboris** [comment]
@ushakov-s the following commands both should output the stack trace then:
`do/args %red.r "-r -d -t MSDOS %environment/console/GUI/gui-console.red"
`do/args %red.r "-r -d -t MSDOS %environment/console/CLI/console.red"`

**Comment by ne1uno** [comment]
@ushakov-s, can you open the event viewer and see any error message?
if you run dxdiag and  save info, at the end of the report it might list recent crashes.
might be possible graphic drivers need update? openGL less than version 2?

Press Windows+R to open the Run dialog, enter eventvwr (or eventvwr.msc) or DxDiag

**Comment by ushakov-s** [comment]
Yes, it reports DirectX error:
*** Runtime Error 98: assertion failed
*** in file: /C/Users/1/Sets/Äèñòðèáóòèâû/dev/Red/red-master/modules/view/backends/windows/direct2d.reds
*** at line: 1579
***
***   stack: gui/DX-init
***   stack: gui/init
***   stack: ctx||454~init 001EA7BCh

Why is dx? I select to use GDI+ : @ Config: [gui-console?: yes red-help?: yes draw-engine: 'GDI+]

DxDiag reports no any errors, Event Viewer is the same.
OpenGL version 2.1
DirectX version 10

**Comment by ushakov-s** [comment]
Hmmm. Red was being support DX10 very recently. At least release 0.64 or red-04nov20-277584b4c.exe works fine with it.
Is it difficult to merge that support back to the master branch?

**Comment by gltewalt** [comment]
Check quarantined Anti-virus files
