### ISSUE TITLE
load-csv/as-records gives error on MacOS

### ISSUE THREAD

**Issue by BuilderGuy1** [red/red#5075]
load-csv/as-records gives error "append does not allow map! for its series argument" when using the Feb 9th 2022 version of RED on MacOS.

**Describe the bug**
Read CSV file with:
   mydata: read %data_test2.csv
Loaded CSV with:
   mycsv: load-csv/as-records mydata

I used the attached "data_Test2.csv" file to create this error.

**Data File**
[Data_Test2.csv](https://github.com/red/red/files/8076653/Data_Test2.csv)

**Platform version**
```
MacOS 10.14.6 Mojave
Red 0.6.4 for macOS built 9-Feb-2022/8:46:44-08:00  commit #e343951
```

**Comment by greggirwin** [comment]
Reproduced on Win10. All it takes is this:
```
Time
"30 December, 2019 7:37 PM"
```
Where this works fine:
```
X,Time
A,"30 December, 2019 7:37 PM"
```

**Comment by greggirwin** [comment]
Guessing it's the `add-line` rule, which does `value: make map! length`. The catch of rules not capturing vars. `Value` is used for two purposes in the func. Nice find @BuilderGuy1. :+1:

**Comment by rebolek** [comment]
@BuilderGuy1 thanks!
Also reported by @toomasv in Gitter with this example:
```
load-csv/as-records {"A","B"^/"1","2"}
```

**Comment by rebolek** [comment]
https://github.com/red/red/pull/5077
