### ISSUE TITLE
String buffer corruption & Console CRASH after trimming a split unicode string

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5076]
**Describe the bug**

`print trim first split {х^/+й} "+"` this code:
- crashes Linux CLI console with a lot of garbage output and an error:
```
*** Runtime Error 16: invalid virtual address
*** at: 0807070Eh
```
- hangs Windows GUI console (seemingly it's too slow to output the whole garbage)

**Expected behavior**
```
>> print trim first split {х^/+й} "+"
х
```

**Platform version**
```
Red 0.6.4 for Windows built 25-Jan-2022/14:48:41+03:00  commit #dbbe6e0
```

**Comment by dockimbel** [comment]
Cannot reproduce the issue outside of the GUI console (works fine from CLI console on W10). 
In GUI console, the issue is caused by `dyn-print/red-print` function which enters an infinite loop. The string passed by `trim` seems correct, no traces of corruption.

**Comment by hiiamboris** [comment]
works after latest 2 commits by @qtxie
but worth adding tests?

**Comment by dockimbel** [comment]
@hiiamboris Which simple regression test do you propose to write? This issue can't be easily detected, as it's a buffer internal corruption.

**Comment by hiiamboris** [comment]
how about this in regression-test-redc-5.r:
```
		--compile-and-run-this {
			Red []
			do [print trim first split {х^/+й} "+"]
		}
		--assert compiled?
		--assert qt/output == "х^/"
```

**Comment by dockimbel** [comment]
@hiiamboris That does not trigger the issue here, as I posted in my first comment above. I can only reproduce it in GUI console, not outside of it.

**Comment by hiiamboris** [comment]
Have you tried on Linux?
> crashes Linux CLI console with a lot of garbage output and an error

**Comment by dockimbel** [comment]
@hiiamboris There is something wrong with the code you've posted in the description. It is using [overlong encoding](https://en.wikipedia.org/wiki/UTF-8#Overlong_encodings) for some characters. If you copy/paste the `x` in the Red console and wrap it in a char!, you get:

```
>> to-hex to-integer #"х"
== #00000445
```

Overlong encodings are considered invalid UTF-8, though Github/browsers seem to accept it anyway. You might want to check the code editor you were using to write that code, as it needs fixing. :wink:

I've spent the last two hours trying to understand why Red was producing strings with unit=2 (UCS-2) format out of `{x}` extracted from your code snippet... :sweat_smile:

**Comment by hiiamboris** [comment]
Nah, that's just cyrillic `х`, which looks similar to latin `x` :D 
https://util.unicode.org/UnicodeJsps/confusables.jsp?a=x&r=None
