### ISSUE TITLE
Console truncates tags

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5078]
**Describe the bug**
GUI:
![](https://i.gyazo.com/610d5660f8da7b1528c21272d24a66a4.png)
CLI:
![](https://i.gyazo.com/778319f607fd7e0d858e4535984a3e9a.png)

**To reproduce**

type `loop 100 [append [] <abcdefghi>]`

**Expected behavior**

Ellipsis at the end.

**Platform version**
```
Red 0.6.4 for Windows built 25-Jan-2022/14:48:41+03:00  commit #dbbe6e0
```

**Comment by dockimbel** [comment]
```
>> loop 100 [append [] <abcdefghi>]
== [<abcdefghi> <abcdefghi> <abcdefghi> <abcdefghi> <abcdefghi> ...
```

It works as it should. Can you explain what is the issue?

**Comment by hiiamboris** [comment]
Strange. Maybe my version?

**Comment by hiiamboris** [comment]
nope, tried the latest..

on GUI console:
```
>> system/console/size
== 77x36
```
on CLI:
```
>> system/console/size
== 192x46
```
some sizes may not trigger it

**Comment by dockimbel** [comment]
Go it:
```
>> system/console/size
== 77x43
>> loop 12 [append [] <abcdefghi>]
== [<abcdefghi> <abcdefghi> <abcdefghi> <abcdefghi> <abcdefghi> ]
```

**Comment by dockimbel** [comment]
There are two issues actually: the lack of ellipsis and the endind `]`.

**Comment by hiiamboris** [comment]
```
>> mold/part loop 100 [append [] <abcdefghi>] 55
== {[<abcdefghi> <abcdefghi> <abcdefghi> <abcdefghi> <abcde}
>> mold/part loop 100 [append [] <abcdefghi>] 54
== {[<abcdefghi> <abcdefghi> <abcdefghi> <abcdefghi> <abcd}
>> mold/part loop 100 [append [] <abcdefghi>] 53
== {[<abcdefghi> <abcdefghi> <abcdefghi> <abcdefghi> ]}
```

**Comment by dockimbel** [comment]
Yes, `mold/part` and `form/part` are inserting the closing bracket even if the part limit has been reached.
