### ISSUE TITLE
tag lexing glitch

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5079]
**Describe the bug**
```
>> '<img src=(url)>
== <<img src=(url)>
```
Where the extra `<` comes from?

**Expected behavior**

Hmm.. `'<img` could be a lit-word

**Platform version**
```
Red 0.6.4 for Windows built 25-Jan-2022/14:48:41+03:00  commit #dbbe6e0
```

**Comment by dockimbel** [comment]
This will now be reported as a tag error, as it's anyway ambiguous.
