### ISSUE TITLE
GUI console does not let you select with the mouse

### ISSUE THREAD

**Issue by greggirwin** [red/red#5089]
GUI console does not let you select with the mouse, after at least one evaluation, unless you go down a line.

Was fine up to at least 15-Feb-2022.

**To reproduce**

1) Enter anything in the console and press Enter to evaluate it.
2) Try to drag the mouse across any single line to select it.

**Expected behavior**

Select text without having to drag down a line.

**Platform version**
```
-----------RED & PLATFORM VERSION----------- 
Red 0.6.4 for Windows built 24-Feb-2022/10:36:26-07:00  commit #bcb5720
--------------------------------------------
```

**Comment by qtxie** [comment]
This issue was introduced in this commit eb804cf81ecdd0c7a7809e713ce78f7c09cbf668

**Comment by greggirwin** [comment]
Because `type` is being set to the guessed datatype, when it's the face style. My guess at a glance. Why it triggers that code I don't know, having not worked on it before.

**Comment by hiiamboris** [comment]
You almost nailed it. Issue is, `type` is a newly introduced local which now shadows the `face/type` which needs qualified prefix.

**Comment by greggirwin** [comment]
Ah yes, `function` in use. I sometimes miss details when viewing bits on github. Thanks @hiiamboris. :+1:

**Comment by qtxie** [comment]
@greggirwin @hiiamboris Thanks a lot. 👍
