### ISSUE TITLE
Setting non-existing word in a context is silently accepted

### ISSUE THREAD

**Issue by rebolek** [red/red#5101]
Setting non-existing word in a context is silently accepted, however, an error should be thrown. See the example:

```
>> c: context [a: 1]
== make object! [
    a: 1
]
>> c/b: 1
>> c
== make object! [
    a: 1
]
```

Rebol properly throws an error:

```
>> c: context [a: 1]
>> c/b: 5
** Script Error: Invalid path value: b
** Near: c/b: 5
```

According to [@toomasv](https://gitter.im/red/bugs?at=62271ccdf43b6d783fef8fb8) this bug was introduced around June/July last year.

**Comment by hiiamboris** [comment]
https://github.com/red/red/issues/4988 likely too
