### ISSUE TITLE
Extra block copy in make map!

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5108]
**Describe the bug**

Looks like map is copying it's own spec on `make`:
```
>> recycle/off
>> prof/each/times [copy #(x: 1 y: 2) make map! [x: 1 y: 2] copy [x: 1 y: 2]] 10000
<10000> 20%      .00076ms         272 B [copy #(x: 1 y: 2)]
<10000> 40%      .00152ms         364 B [make map! [x: 1 y: 2]]
<10000> 40%      .00151ms          92 B [copy [x: 1 y: 2]]
>> 364 - 92
== 272
```

**To reproduce**

`s: stats loop n: 10000 [make map! [x: 1 y: 2]] stats - s / n`

**Expected behavior**

272 bytes from `make` as from `copy`

**Platform version**
```
Red 0.6.4 for Windows built 11-Mar-2022/2:40:53+03:00  commit #27f71f9
```

**Comment by qtxie** [comment]
If insert a `recycle` before `stats - s / n`, I got this:
```
>> s: stats loop n: 10000 [make map! [x: 1 y: 2]] recycle stats - s / n
root: 3768/6544, runs: 0, mem: 3284144 => 1808236, mark: 2.0ms, sweep: 1.0ms
root: 3768/6544, runs: 1, mem: 3984004 => 1808376, mark: 1.0ms, sweep: 2.0ms
== -1.084
```

**Comment by hiiamboris** [comment]
What would be the point? Measuring memory that's not freed by recycle?

**Comment by qtxie** [comment]
Sorry, I misunderstood the issue. So it's about the implementation detail. You want that `make` takes the same amount of memory as `copy`?

**Comment by hiiamboris** [comment]
Yeah. Extra block is just unnecessary GC pressure in this case.
