### ISSUE TITLE
[GTK] no `wheel` event at all?

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5109]
**Describe the bug**
```
view [text-list data repeat x 30 [append [] form x] focus on-wheel [probe event/picked]]
```
shows a text-list, allows to scroll it (I'm using touchpad), but `on-wheel` never fires

Same for `base`, `area`, likely other faces

**To reproduce**

Try wheel-scrolling the above face

**Expected behavior**

`on-wheel` event generated

**Platform version**
```
Red 0.6.4 for Linux built 15-Mar-2022/17:14:51+03:00  commit #af98e79
```

**Comment by qtxie** [comment]
I get this event for `base` and `area`, but not for `text-list`.

**Comment by hiiamboris** [comment]
What code are you using to get it for `base` and `area`?

**Comment by qtxie** [comment]
> What code are you using to get it for `base` and `area`?

```
view [area "jfdklkkjf" on-wheel [probe event/picked]]
view [base"jfdklkkjf" on-wheel [probe event/picked]]
```

**Comment by hiiamboris** [comment]
Confirmed, in latest build it works. After the fix? In an older build no wheel events for any face.
