### ISSUE TITLE
[View] `event/picked` randomly overflows

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5110]
**Describe the bug**
![](https://i.gyazo.com/dcfb7264afde50bd14aa3cb9b809aa51.gif)

On the vertical is `event/picked` value. Outliers are:
```
253.6
252.925
255.375
-251.9583333333333
251.3083333333333
251.8333333333333
```
that is they seem to equal real event/picked + 256 if it's negative and event/picked - 256 if it's positive

**To reproduce**

run this script
```
Red []
x: 0
view [
	base purple cyan 300x300 focus draw [
		pen cyan text 100x30 "Scroll me like crazy" 
		translate 0x150 scale 0.5 0.5
		shape []
	]
	on-wheel [
		if 10 < absolute event/picked [print event/picked]
		repend last face/draw ['line x * 1x0 as-pair x event/picked]
		x: x + 1 % 600
	]
]
```
like it says, scroll up or down insistently (I used touchpad 2-finger scroll on W10)

**Expected behavior**

No overflow

**Platform version**
```
Red 0.6.4 for Windows built 11-Mar-2022/2:40:53+03:00  commit #27f71f9
```

**Comment by dockimbel** [comment]
![image](https://user-images.githubusercontent.com/411393/190442190-a26ce162-2245-4943-9a2e-d50cc8cc07b8.png)

Can't reproduce. I had to take my mouse with one hand, keeping it firm on the table, then using a finger on the wheel to repeatadly scroll it strongly in order to get those tiny spikes. If I scroll it normally, I get pretty much a straight line.

**Comment by hiiamboris** [comment]
Anyway, I'm sure we can patch this on our side.

**Comment by hiiamboris** [comment]
I'll study this more, since it's easy to reproduce here.

**Comment by hiiamboris** [comment]
You're right. The high word of `wparam` I'm getting:
```
idx: 1339
idx: 1131
idx: 924
idx: -29747
idx: 1106
idx: 1098
idx: 1026
idx: 1082
idx: 1075
idx: -30469
idx: 1459
idx: 1067
idx: 892
```

**Comment by hiiamboris** [comment]
I confirm `ASUS Precision Touchpad` is the culprit:
![](https://i.gyazo.com/9c18fefe10ce99cac635d964c58e90c8.png)

No issues on generic MS driver.
