### ISSUE TITLE
`round/to` should be able to handle two pairs/tuples

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5151]
**Describe the bug**
```
>> round/to 22x33 10x20
*** Script Error: round/to does not allow pair! for its scale argument
*** Where: round
*** Near : 10x20
*** Stack:  

```

**Expected behavior**

```
>> round/to 22x33 10x20
== 20x40
```

Tuple could be supported too, maybe a bit less useful.

**Platform version**
```
Red 0.6.4 for Windows built 1-Jun-2022/7:18:47+03:00  commit #c619918
```

**Comment by greggirwin** [comment]
Tuple seems much less useful, I agree.

**Comment by hiiamboris** [comment]
We're walking in circles: https://github.com/red/REP/issues/10 https://github.com/red/red/issues/1263
