### ISSUE TITLE
`percent!` type is not allowed

### ISSUE THREAD

**Issue by ALANVF** [red/red#5156]
**Describe the bug**
[Block comparison](https://github.com/red/red/blob/master/runtime/datatypes/block.reds#L614) doesn't implement `percent!` logic. This behavior could probably be applied to `time!` and `char!` values as well in the future, as well as all string-based types.

**To reproduce**
```
>> [0.01] = [1%]
== false
```

**Expected behavior**
```
>> [0.01] = [1%]
== true
```

**Comment by hiiamboris** [comment]
dupe of https://github.com/red/red/issues/4456
