### ISSUE TITLE
[CONSOLE / HELP] Access Violation when calling system/words/what

### ISSUE THREAD

**Issue by gltewalt** [red/red#5159]
**Describe the bug**

```
>> system/words/what

*** Runtime Error 1: access violation
*** at: 080943BBh
```

**To reproduce**

Type above into the console.

**Expected behavior**

The output of `what`

`what` entered by itself works as expected, `system/words/what` does not.

**Platform version**
Red 0.6.4 for Linux built 4-Jul-2022/2:48:56-06:00  commit #ccc7e08

**Comment by dockimbel** [comment]
The fix ensures that the global context reference is not used when passing the parent's context on compiled function declared inside an object.
