### ISSUE TITLE
Unicode Specials considered invalid

### ISSUE THREAD

**Issue by gurzgri** [red/red#5172]
**Describe the bug**
The [Unicode Specials](https://en.wikipedia.org/wiki/Specials_(Unicode_block)) are considered invalid Unicode.

**To reproduce**
```Red
>> foreach char [#{fff9} #{fffa} #{fffb} #{fffc} #{fffd}] [probe copy/part form try [to string! char] 52]
{*** Access Error: invalid UTF-8 encoding: #^{FFF90000}
{*** Access Error: invalid UTF-8 encoding: #^{FFFA0000}
{*** Access Error: invalid UTF-8 encoding: #^{FFFB0000}
{*** Access Error: invalid UTF-8 encoding: #^{FFFC0000}
{*** Access Error: invalid UTF-8 encoding: #^{FFFD0000}
```

**Expected behavior**
They should be valid in a unicode string. 

**Platform version**
Red 0.6.4 for Windows built 6-Aug-2022/16:04:37

**Comment by dockimbel** [comment]
> They should be valid in a unicode string.

You didn't use "unicode strings" but `binary!` series.
```
>> binary? #{fff9}
== true
>> char? #{fff9}
== false
```

**Comment by gurzgri** [comment]
Sorry, my bad, noticed that by myself too after looking into https://github.com/red/red/blob/master/runtime/unicode.reds
