### ISSUE TITLE
[View, Regression] `size-text` doesn't take width into account anymore

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5173]
**Describe the bug**
```
>> r: rtd-layout ["abcdefghijkl"]
>> r/size: 50x50
>> size-text r
== 64x16    ;) single line wider than 50 px!
```

**Expected behavior**

Multi-line formatting (e.g. `50x32`). Was working in `Red 0.6.4 for Windows built 27-Jun-2022/11:51:28+03:00  commit #ed73e33`

**Platform version**
```
Red 0.6.4 for Windows built 11-Aug-2022/12:30:09 a20de412227b7f411f5082422c34ae2966ff47f7
```

**Comment by dockimbel** [comment]
I think I'll really remove that "priority.high" label, as it's abused too much.

**Comment by dockimbel** [comment]
That code works as expected after the recent fix making the text not auto-wrap by default. If you want to force it to fit inside the face size limits, you need to set the `para/wrap?` property to `true`.

```
>> r: rtd-layout ["abcdefghijkl"]
>> r/para: make para! [wrap?: yes]
>> r/size: 50x50
>> size-text r
== 50x32
```

**Comment by qtxie** [comment]
Well, if wrapping is expected in most of the cases. We should make it default.

**Comment by dockimbel** [comment]
@qtxie That's fine with me as the default as long as the user can control it using `para`.

**Comment by dockimbel** [comment]
> Great, yet another object to spawn.

That depends on the use-case.

**Comment by hiiamboris** [comment]
Actually, I'm fine with this, just created a shared para object.

Although IMO it's a design issue that there are two separate levers that have to be pulled in order to turn wrapping on: `size/x` and `para/wrap?`. One (`size/x`) should be enough (in "reducing complexity" mindset). Not saying we should dive into View issues & designs right now, but as a food for thought, for after 1.0.

**Comment by qtxie** [comment]
OK. I'll revert to auto-wrap by default as it was the default mode since a long time and there are several apps rely on it.

> One (size/x) should be enough

What if I don't want it to wrap even with a small `size/x`. `size` is for setting the bounding box, not for controlling the wrapping. `size` do affects it as well as `font-size`, `font style`.

**Comment by hiiamboris** [comment]
> What if I don't want it to wrap

Set size to `none`
