### ISSUE TITLE
Curious results of lexer

### ISSUE THREAD

**Issue by meijeru** [red/red#5185]
```
>> type? '+
== word!
>> type? '+1
== integer!
>> '+1
== 2511
```
Not only is `'+1` lexed as an integer literal where one would expect a (lit-)word at most, but its value is intriguing to say the least.

Further experimenting:
```
>> to-word "'+1"
*** Script Error: contains invalid characters
*** Where: to
*** Near : "'+1"
*** Stack: to-word  

>> to-integer '+1
== 2511

>> to-integer "'+1"
*** Script Error: cannot MAKE/TO integer! from: "'+1"
*** Where: to
*** Near : "'+1"
*** Stack: to-integer  

```

**Comment by greggirwin** [comment]
Reproduced. Nice catch! Happens for all digits, and with a minus sign as well as plus.

**Comment by greggirwin** [comment]
```
>> '+0
== 2510
>> '+00
== 25100
>> '+000
== 251000
>> '+0001
== 2510001
>> '+1
== 2511
>> '+12
== 25112
>> '+123
== 251123

>> '-9
== 2539
>> '-98
== 25398
>> '-987
== 253987
```

**Comment by greggirwin** [comment]
So for positive you get 251 followed by the scanned digits. For negative it's 253. That result is converted to an integer.

```
>> '-9876543
*** Syntax Error: (line 1) invalid float at -9876543
*** Where: set
*** Near : :delimiter-lex
*** Stack: load 
>> '-987654
== 253987654

>> '+9876543
*** Syntax Error: (line 1) invalid float at +9876543
*** Where: set
*** Near : :delimiter-lex
*** Stack: load 
>> '+987654
== 251987654
```

**Comment by meijeru** [comment]
Looks to me like a combination of missing/erroneous entries in the lexical scanning state machine, and a fluke in calculating the value of an integer (but that might go away once the combination of characters is forbidden or interpreted otherwise).

**Comment by greggirwin** [comment]
Yes, any alpha char sets it back to word mode. Others are more interesting:
```
>> '+9_
*** Syntax Error: (line 1) invalid integer at '+9_
*** Where: set
*** Near : :delimiter-lex
*** Stack: load 
>> '+9-
*** Syntax Error: (line 1) invalid date at '+9-
*** Where: set
*** Near : :delimiter-lex
*** Stack: load 
>> '+9@
== '+9@
>> '+9$
*** Syntax Error: (line 1) invalid integer at '+9$
*** Where: set
*** Near : :delimiter-lex
*** Stack: load 
>> '+9:
*** Syntax Error: (line 1) invalid time at '+9:
*** Where: set
*** Near : :delimiter-lex
*** Stack: load 
>> '+9%
*** Syntax Error: (line 1) invalid float at +9%%   ; Note the doubled sigil
*** Where: set
*** Near : :delimiter-lex
*** Stack: load 
```

**Comment by dockimbel** [comment]
This issue is broader:
```
>> '+1
== 2511
>> '-1
== 2531
>> :+1
== 3511
>> :-1
== 3531
>> =1
== 131
>> =+1
```

For literals starting with quote and colon, those are just wrong entries in the lexer table, so an easy fix. OTOH, equal character is rather problematic, as it has special meaning in conjuction with `<`.

**Comment by hiiamboris** [comment]
`=` should just start a word/set-word/path/set-path, why is it problematic?

**Comment by dockimbel** [comment]
Because we are allowing those words: https://github.com/red/red/blob/master/tests/source/units/lexer-test.red#L1578

And you're the one who requested such support: https://github.com/red/red/issues/4562#issuecomment-841802031

**Comment by hiiamboris** [comment]
IMO it shouldn't be any different from e.g. `a<a` which I also expect to be a word, but it opens a tag ;)
But those are still words, `=` shouldn't start a number in any circumstances.

**Comment by dockimbel** [comment]
`a<a` is not a word, because there's an "unsticking" rule for words preceding immediatly a `<`, so it's `a` and opening tag `<a`. OTOH, `=`  is allowed to stick to `<`, so it needs its own row in the lexer table now in order to satisfy all the constraints.

**Comment by hiiamboris** [comment]
By the way, do we need this tag unsticking in practice? Because I have a feeling it's a huge lexing troublemaker, and a very rarely used datatype. Also email is near useless datatype with huge lexical collisions.

**Comment by dockimbel** [comment]
We can reexamine those choices when working on the Red language specs.

**Comment by hiiamboris** [comment]
Noted. But it looks like a contrived example, as it's not generally loadable anyway, e.g. `{<b><i>Hello, world</i></b>}`.

**Comment by dockimbel** [comment]
```
>> name: "Bob"
== "Bob"
>> rejoin [<b><i>name</i></b>]
== <b<i>Bob</i></b>>
```
