### ISSUE TITLE
to-date to-integer now isn't the curent time zone

### ISSUE THREAD

**Issue by isqwy** [red/red#5195]
```
>> now
== 3-Sep-2022/21:32:47+08:00
>> to-integer now
== 1662211977
>> to-date 1662211977
== 3-Sep-2022/13:32:57
>>
```
why turn back is not use the same time zone?

**Comment by hiiamboris** [comment]
and how do you suggest integer will hold a time zone?

**Comment by dockimbel** [comment]
`to-integer` on dates converts to Unix Epoch Time, which is a lossy conversion wrt to timezones. See documentation: https://github.com/red/docs/blob/master/en/datatypes/date.adoc#epoch-time

"Epoch time are expressed in UTC. If the argument date is not in UTC, it will be converted internally before converting to epoch time."
