### ISSUE TITLE
Curious bitwise operations with typesets

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5198]
**Describe the bug**
```
>> number! or 0
== make typeset! [block! char! integer! float! set-word! lit-word! get-word! refinemen...
>> number! xor 0
== make typeset! [block! char! set-word! lit-word! get-word! refinement! native! bitse...
>> number! and 0
== make typeset! [integer! float!]
>> number! and 1
== make typeset! [integer! float!]
>> number! and 2
== make typeset! [integer! float! percent!]
>> number! or 1.#nan
== make typeset! [block! char! integer! float! set-word! lit-word! get-word! refinemen...
>> number! or [abracadabr]
== make typeset! [integer! float! typeset! percent! map! binary! series! email! money!...
>> number! or func []["hello"]
== make typeset! [datatype! none! block! file! url! integer! float! lit-word! refineme...
```
No idea what these are even doing...

**Expected behavior**

An error.

**Platform version**
```
Red 0.6.4 for Windows built 3-Sep-2022/17:53:01+03:00  commit #cb83eca
```

**Comment by greggirwin** [comment]
This leads to a good design question for the new work and specs. How do we catch things that fall through cracks. This should be something we can analyze statically for many cases, without going deeply down the formal path as some other langs do.

**Comment by greggirwin** [comment]
Also a balance of effort. What problems are more likely to occur, and what is really out there. I haven't sketched out designs for a Red analyzer (linter) but maybe there's a way to leverage that alongside the goal @dockimbel mentioned for using specs to verify compliance in the actual code against it.

**Comment by dockimbel** [comment]
That is the kind of erroneous case that shall be caught by unit tests generated from the spec knowledge base.
