### ISSUE TITLE
Wrong text length calculation

### ISSUE THREAD

**Issue by luce80** [red/red#5199]
**Describe the bug**
For some values of font size the calculated text length is wrong and the text is clipped. I am on Win11

**To reproduce**
```
>> view [text "targets react to slider , slider reacts to field" bold font [size: 10]]
```
**Expected behavior**
No text clipping

**Screenshots**
![image](https://user-images.githubusercontent.com/17967405/188314466-0f286fec-508d-45aa-89c8-cb5554fcf2a0.png)

**Platform version**
```
>> about
Red 0.6.4 for Windows built 4-Sep-2022/12:59:01+02:00  commit #d85b2ef
```

**Comment by hiiamboris** [comment]
:point_up: [September 4, 2022 3:46 PM](https://gitter.im/red/bugs?at=63149e297ccf6b6d45bb8ad5)

**Comment by luce80** [comment]
NIce ! But...is it possible to have the text length calculated **exactly** ?
```
>> about
Red 0.6.4 for Windows built 9-Sep-2022/17:02:57+02:00  commit #2a77792
>> view [text red yellow "targets react to slider , slider reacts to field" bold font [size: 23]]
```
![image](https://user-images.githubusercontent.com/17967405/189415404-7baaa26e-2cbf-44f3-911f-3634a7630201.png)

**Comment by hiiamboris** [comment]
on W10 works fine: ![](https://i.gyazo.com/d0be9399c20e7b4a9b217288a682828a.png)

**Comment by greggirwin** [comment]
Confirmed @hiiamboris' result on Win10.
![image](https://user-images.githubusercontent.com/460079/189423678-793f30ed-b1c6-41e5-aa93-f0d6dec8e4a6.png)

**Comment by qtxie** [comment]
@luce80 Confirmed on Win11.
