### ISSUE TITLE
ALL [] returns NONE or block!

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#520]
```
Red []

probe all []
```

none

red>> all []
== []

REBOL:

> > all []
> > == true

**Comment by rebolek** [comment]
In 0.6.1:

Interpreter
---

```
red>> all []
== none
```

Compiler
---

Source:
```
Red []

probe all []
```

Output:
```
E:\Code\red (master)
λ test
none
```

@dockimbel  So, should it behave as Rebol (returning `true`), or is `none` the right output?
