### ISSUE TITLE
No catch for throw: silent

### ISSUE THREAD

**Issue by luce80** [red/red#5201]
**Describe the bug**
A strange error appears when `system/view/silent?: yes` is used and VID block contains a `paren!`

**To reproduce**
```
>> system/view/silent?: yes
== true
>> view [base (error)]
*** Throw Error: no catch for throw: silent
*** Where: either
*** Near : no
*** Stack:
```
**Expected behavior**
A different error should appear because compose is not used or no error if that is an error that /silent? should avoid.

**Platform version**
```
>> about
Red 0.6.4 for Windows built 4-Sep-2022/12:59:01+02:00  commit #d85b2ef
```

**Comment by dockimbel** [comment]
It's intended, you need to provide a `catch` for it, see: https://github.com/red/red/blob/master/modules/view/VID.red#L73

Though, the documentation does not match the feature, so a change is needed anyway.

**Comment by dockimbel** [comment]
A default `catch` is now built-in VID for silencing those exceptions.
