### ISSUE TITLE
FIND/SAME on blocks never matches

### ISSUE THREAD

**Issue by dockimbel** [red/red#5212]
**Describe the bug**
`find/same` on block arguments never finds the 2nd argument block in the 1st one.

**To reproduce**
```
blk: [1]
append/only list: make block! 1 blk
find/same list blk
```
results in:
```
none
```

**Expected behavior**
Should return `[[1]]`.

**Platform version**
All.

**Comment by hiiamboris** [comment]
`find/same/only`

**Comment by dockimbel** [comment]
So intuitive that I forgot about that rule! 🙈

**Comment by hiiamboris** [comment]
Regularly being caught by it myself :D

**Comment by greggirwin** [comment]
`/same` could imply `/only`. We have a few other cases where one refinement implies another. By definition `/same | same?` means "single value", right?

**Comment by hiiamboris** [comment]
no more special cases please, we already have enough :)
