### ISSUE TITLE
Hash performance is completely inadequate

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5213]
**Describe the bug**

Simple modification benchmark:
```
Red []

pos: list: make block! n: 1e6
clock/times [append list random 99999] n
pos2: skip tail pos -1000
clock/times [pos: change pos 'new] n
clock/times [remove list] 1000
clock/times [insert list 'new] 1000
clock/times [remove pos2] 1000
clock/times [insert pos2 'new] 1000

print ""
pos: list: make hash!  n: 1e5
clock/times [append list random 99999] n
pos2: skip tail pos -1000
clock/times [pos: change pos 'new] 100
clock/times [remove list] 1
clock/times [insert list 'new] 100
clock/times [remove pos2] 1000
clock/times [insert pos2 'new] 100
```
Result:
```
0.50 μs [append list random 99999]
0.39 μs [pos: change pos 'new]
1.28 ms [remove list]
2.12 ms [insert list 'new]
1.02 μs [remove pos2]
0.77 μs [insert pos2 'new]

0.71 μs [append list random 99999]
12.7 ms [pos: change pos 'new]       ;) 32500 times slower than block!!
1110 ms [remove list]                ;) 867 times slower than block! - that's one second per removal!!!
12.4 ms [insert list 'new]
144 μs  [remove pos2]               ;) 140 times slower than block!
12.8 ms [insert pos2 'new]          ;) 16600 times slower than block!!
```
Note that block is 1M in size while hash is only 100k, so insert/remove times for hash appear much less than they are. Benchmarking block with 100k items is fruitless, while benchmarking hash with 1M requires too much patience :D

**Expected behavior**

One order of magnitude slowdown should be acceptable I assume, *for the same 1M length*.
I mostly care about append and change, rest is for completeness.

**Platform version**

```
-----------RED & PLATFORM VERSION----------- 
RED: [ branch: "master" tag: #v0.6.4 ahead: 4457 date: 11-Sep-2022/8:20:11 commit: #85fa7e7830ce1083bc56bee5e2b3db1d9b8d9489 ]
PLATFORM: [ name: "Windows 10" OS: 'Windows arch: 'x86-64 version: 10.0.0 build: 19044 ]
--------------------------------------------
```

**Comment by hiiamboris** [comment]
For comparison, times in `red-25may22-f656458f7.exe`, before the hash crash fixes:
```
0.42 μs [append list random 99999]
0.34 μs [pos: change pos 'new]
1.21 ms [remove list]
1.98 ms [insert list 'new]
0.99 μs [remove pos2]
2.00 μs [insert pos2 'new]

0.71 μs [append list random 99999]
0.63 μs [pos: change pos 'new]
1.24 ms [remove list]
1.35 ms [insert list 'new]
239 μs  [remove pos2]
124 μs  [insert pos2 'new]
```
Seems almost on par (0-1μs times are below resolution for 1000 iterations, these don't count).

Iteration count was adjusted as follows:
```
Red []

#include %/d/devel/red/common/clock.red

pos: list: make block! n: 1e6
clock/times [append list random 99999] n
pos2: skip tail pos -1000
clock/times [pos: change pos 'new] n
clock/times [remove list] 1000
clock/times [insert list 'new] 1000
clock/times [remove pos2] 1000
clock/times [insert pos2 'new] 1000

print ""
pos: list: make hash!  n: 1e5
clock/times [append list random 99999] n
pos2: skip tail pos -1000
clock/times [pos: change pos 'new] n
clock/times [remove list] 1000
clock/times [insert list 'new] 1000
clock/times [remove pos2] 1000
clock/times [insert pos2 'new] 1000
```

**Comment by hiiamboris** [comment]
Using more advanced (but slower and less precise) profiler on block and hash of *equal 1M length*:
```
<1000000>18%      .00091ms           0 B [append list random 99999]
<1000000>18%      .0009 ms           0 B [pos: change pos 'new]
<1000>  24%     1.23   ms           0 B [remove list]
<1000>  40%     2      ms           0 B [insert list 'new]
<1000>   0%      .00099ms           0 B [remove pos2]
<1000>   0%      .0029 ms           0 B [insert pos2 'new]

<1000000> 2%      .00148ms          17 B [append list random 99999]
<5>      3%   374      ms  25'020'346 B [pos: change pos 'new]
<1>     89%  61'211    ms   1'048'948 B [remove list]      ;) that's 1 minute for single removal !!!
<5>      3%   376      ms  33'020'346 B [insert list 'new]    ;) allocated size is per single insertion !!!
<1000>   1%      .36   ms       5'600 B [remove pos2]
<5>      3%   377      ms  25'004'176 B [insert pos2 'new]
```
Source:
```
Red []

;#include %/d/devel/red/common/profiling.red 
do https://codeberg.org/hiiamboris/red-common/raw/branch/master/profiling.red
recycle/off

pos: list: make block! n: 1e6
prof/each/times/quiet [append list random 99999] n
pos2: skip tail pos -1000
prof/each/times/quiet [pos: change pos 'new] n
prof/each/times/quiet [remove list] 1000
prof/each/times/quiet [insert list 'new] 1000
prof/each/times/quiet [remove pos2] 1000
prof/each/times/quiet [insert pos2 'new] 1000
prof/show

print ""
prof/reset
pos: list: make hash!  n: 1e6
prof/each/times/quiet [append list random 99999] n
pos2: skip tail pos -1000
prof/each/times/quiet [pos: change pos 'new] 5
prof/each/times/quiet [remove list] 1
prof/each/times/quiet [insert list 'new] 5
prof/each/times/quiet [remove pos2] 1000
prof/each/times/quiet [insert pos2 'new] 5
prof/show
```

**Comment by greggirwin** [comment]
Isn't that the nature of hashes and bucket sizes? All tradeoffs. Even Judy Arrays have their limits.

**Comment by qtxie** [comment]
@hiiamboris  The hard part of modifying the hash is that we need to update the `index` of the moved items. It used some complicated code to update them (only the moved items) before the hash crash fixes. But it's buggy. After the fixes, it updates all the items in the hashtable. That's why it's much slower in your benchmark.

For example, we have a hash.

```
[1 2 3 4 5 6 7 8]
```

when we removed 6 or insert before 7, only 7 and 8 need to be updated as their `index` changed. It's complicated to handle it correctly in current implementation.

@greggirwin Yes. And also tradeoff with the complexity of the algorithm. Judy Arrays are very sophisticated.

**Comment by hiiamboris** [comment]
But can you at least fix `change`? Without it, I don't see much use in hash table :)
It becomes faster to convert it to block, modify, and then convert back to hash than to change a single item :)

Can't use a map since my keys are objects (using /same lookup).

**Comment by qtxie** [comment]
> But can you at least fix change?

I can optimize cases where no items index changed.

**Comment by dockimbel** [comment]
> I can optimize cases where no items index changed.

Yes, please do.

**Comment by dockimbel** [comment]
After commit https://github.com/red/red/commit/7144ae76c5c9ff6958b35fd1cddbad66ec44f1e8
```
>> clock/times [pos: change pos 'new] 100
0.0 μs	[pos: change pos 'new]
```

**Comment by hiiamboris** [comment]
> For the other measures, those are expected

I disagree with the "expected" part, it's an implementation's fault. But append & change are enough for me for the time being. Let's just make sure we redesign this for the 1.0.

**Comment by dockimbel** [comment]
@qtxie ^--- There's a serious flaw there!

**Comment by qtxie** [comment]
Yes. The current implementation is quite naive and... slow.  I want to see if it really causes an issue in real projects. Most of them are small projects as the current Red is not ready for big serious projects.

@hiiamboris Do you have the test cases to make it crashing before the crashes fixes? I'll see if I can optimize more cases. IIRC, there are too many edge cases to handle, and all the series! types use a single `insert` function. That makes the code complicated and hard to change. That's why I switch to a naive implementation.

**Comment by hiiamboris** [comment]
> Do you have the test cases to make it crashing before the crashes fixes?

Only those I reported in issues... Crashes in real code were quite erratic.

**Comment by dockimbel** [comment]
@qtxie
```
59291 ms    [remove list]
485 ms      [make hash! remove to block! list]
```
For a hash of 1M elements, removing one item takes almost 60 seconds. Converting that hash to a block, removing the item, converting the whole block to hash, takes only ~0.5 seconds, so more than 100 times faster. 

That means that beyond a threshold of `hash!` series size, you should just rebuild the whole hashtable on any insertion/removal.

**Comment by qtxie** [comment]
@dockimbel Yes. `remove`, I overlooked it. It still uses the old buggy code. I'll fix it.

**Comment by dockimbel** [comment]
Now:
```
372 ms	[remove list]
538 ms	[make hash! remove to block! list]
```
👍
