### ISSUE TITLE
Big series in reactors are never freed

### ISSUE THREAD

**Issue by dockimbel** [red/red#5220]
**Describe the bug**
Big series referenced in reactors are never freed, even after cutting off all references to the reactor.

**To reproduce**
```
r: make reactor! [a: append/dup [] 'x 10'000'000] 
probe recycle
modify r/a 'owned none
r: none
probe recycle
```
outputs:
```
270471416
270471416
```

**Expected behavior**
Proper recycling of unreferenced reactors.

**Platform version**
All.

**Comment by dockimbel** [comment]
@qtxie 

I suspected that the [extra slots we are filling](https://github.com/red/red/blob/master/runtime/ownership.reds#L130) for ownership tracking were causing that, but even when I tried to set them to `none` in `ownership/unbind`, the reactor is still alive, so it does not seem to be that.

I've inserted a native stack trace on marking big series in the collector and the output looks like this:
```
***   stack: stack-trace
***   stack: red/collector/keep 031FCB14h
***   stack: red/collector/mark-block 05331658h
***   stack: red/collector/mark-values 05331658h 05337BA8h
***   stack: red/collector/mark-block-node 031E3880h
***   stack: red/collector/mark-context 031E3884h
***   stack: red/collector/mark-values 049FE18Ch 04A0E45Ch
***   stack: red/collector/mark-block 00520544h
***   stack: red/collector/do-mark-sweep
***   stack: red/natives/recycle* false -1 -1
```
which suggests that the reactor is referenced from the root block?!?

So I looked into the hashtable code and saw that [your are using a shadow buffer](https://github.com/red/red/blob/master/runtime/hashtable.reds#L1584) for the whole hashtable it seems which is allocated from root block. I guess that this `refresh-buffer` is not properly cleaned up and keeps a reference to all values that went into the hashtable.

**Comment by dockimbel** [comment]
@qtxie It seems `refresh-buffer` in hashtable is holding a copy of the ownership table and keeps all reactors alive even when they are not referenced anymore. The call to `modify r/a 'owned none` should have removed the big series from the ownership hashtable, but the collector is still marking the reactor as alive (it's reachable from the root block directly, so seems related to `refresh-buffer`...).

**Comment by dockimbel** [comment]
Actually, it's not even related to reactors:
```
r: make object! [a: append/dup [] 'x 10'000'000] 
probe recycle
r/a: none
recycle
r: none
probe recycle
```
gives
```
270470320
270470320
```

**Comment by qtxie** [comment]
> Actually, it's not even related to reactors:
> 
> ```
> r: make object! [a: append/dup [] 'x 10'000'000] 
> probe recycle
> r/a: none
> recycle
> r: none
> probe recycle
> ```
> 
> gives
> 
> ```
> 270470320
> 270470320
> ```

I got this with `red-02oct22-881df719b.exe`.

```
270245808
1810076
```

**Comment by dockimbel** [comment]
Try compiling it.

**Comment by dockimbel** [comment]
Forget the object version compiled with `do`, the unreleased series is related to the literal block `[]` that gets referenced by the Redbin decoded payload. So it's just a side-effect of compiling it.

**Comment by qtxie** [comment]
> Try wrapping it in `do [...]` and compiling it. I can't reproduce it from the console.
> 
> Can you reproduce the reactor issue?

Yes. I can. The object `r` is referenced somewhere. The `refresh-buffer` is cleared immediately after use, it should not hold any values.

```
r: make reactor! [a: append/dup [] 'x 10'000'000] 
probe recycle
modify r/a 'owned none
r/a: none
probe recycle
```
Outputs:
```
 270249944
 1839680
 ```
 
So the series `a` was removed from both reactors and the hashtable.

**Comment by dockimbel** [comment]
How do you run that code? From the same code in the GUI console, I get:
```
271213756
271214364
```

**Comment by dockimbel** [comment]
From the prebuilt CLI or GUI consoles downloaded from the red website, I get same results as you...

**Comment by qtxie** [comment]
I used the prebuilt CLI console downloaded from the red website.

**Comment by qtxie** [comment]
```
r: make reactor! [a: append/dup [] 'x 10'000'000] 
probe recycle
modify r/a 'owned none
r/a: none
probe recycle
```
Outputs:

```
270249944
1839680
```

I don't know why it works. I don't see code that remove the series `a` from the hashtable.

**Comment by dockimbel** [comment]
I can't reproduce with locally compiled CLI or GUI console. Also, by replacing `append/dup []` by `append/dup make block! 1`, the memory gets released as it should, showing that the retention of reference to this literal block is a side-effect of the compilation or the loading process. E.g.:

```
>> print read %5220.red
Red [] r: make reactor! [a: append/dup [] 'x 10'000'000] 
probe recycle
modify r/a 'owned none
r/a: none
probe recycle
>> do %5220.red
271219416
271219460
== 271219460
>> recycle
== 2784556
```
While the file is run the loaded source code is held the stack, preventing the literal block to be freed. After the file execution, calling `recycle` is successfully releasing the used memory, as the literal block is not referenced anymore from anywhere.

**Comment by dockimbel** [comment]
@qtxie There's still something strange going on as the following version does not release the memory:

```
>> r: reactor [a: append/dup [] 'x 10'000'000] 
== make object! [
    a: [x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x ...
>> modify r/a 'owned none
== [x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x ...
>> r: none
== none
>> recycle
== 271217868
```
It should work even without `r/a: none`...

**Comment by dockimbel** [comment]
The issue was caused by the `on-change*` function context node still pointing to the old 2-cell intermediary block when cloning the function during `object/copy` process, resulting in bindings inside `object/rebind` passing the old context node reference to the binding process, which results in `self` word in `reactor!/on-change*` getting bound to the new object, therefore holding a reference to the big series even after `r` has been GCed. 🤕

**Comment by dockimbel** [comment]
Additional note: when running the test code from a file, the memory might seem to be leaking even after a new GC pass. This is caused by the internal `object/path-parent` and  `object/field-parent` global references. Overwriting them is achieved by evaluating an object path from an object with at least one event handler defined:

```
>> do %5220red
== 270256432
>> recycle
== 270255432
>> a: object [b: 1 on-change*: func [w o n][]]
>> a/b
>> recycle
== 1819348
```

Trying to remove those internal global states in the past proved to be challenging. I will give it another try.

**Comment by dockimbel** [comment]
> Trying to remove those internal global states in the past proved to be challenging. I will give it another try.

Actually it was easier than expected: https://github.com/red/red/commit/cbe19354196e97a830b34899ef8ae525833c7ced
