### ISSUE TITLE
-1x- should NOT be a valid pair!

### ISSUE THREAD

**Issue by luce80** [red/red#5227]
**Describe the bug**
 `-1x-` is parsed as a valid `pair!`

**To reproduce**
```
>> -1x-
== -1x0
```

**Expected behavior**
An `error!` should appear.

**Comment by meijeru** [comment]
Any <integer>x-  is lexed as <integer>x0

**Comment by qtxie** [comment]
> Any `<integer>x-` is lexed as `<integer>x0`

Same for `<integer>x+`, so it looks like an issue when handling sign chars.
