### ISSUE TITLE
checkbox copied the parent's color into itself

### ISSUE THREAD

**Issue by bubnenkoff** [red/red#5283]
```
view [
   db-settings-panel: panel [] return 

   send-data-to-noSQL-check-panel: panel [ 
        send-data-to-noSQL-check: check "Activate" 
            react [
                either (face/data = true) [
                        db-settings-panel/color: gray
                        send-data-to-noSQL-check-panel/color: none
                    ] [
                            db-settings-panel/color: snow 
                            send-data-to-noSQL-check-panel/color: green
                    ]
            ]                    
          
    ]
]
```

![изображение](https://user-images.githubusercontent.com/6514326/219628005-641389ef-a95d-4fed-b669-502a52dd6e76.png)

The green border should not be displayed.
```
>> about
Red 0.6.4 for Windows built 26-Nov-2022/17:40:58+03:00  commit #94beb4d
```

**Comment by dockimbel** [comment]
A more readable version of the above code:
```
view [
   A: panel [] return 
   B: panel [ 
        check "Activate"  react [
            either face/data [
                A/color: gray
                B/color: none
            ] [
                A/color: snow 
                B/color: green
            ]
        ]
    ]
]
```

**Comment by dockimbel** [comment]
VID rewriting rules are in play there, more specifically the [`color-backgrounds`](https://github.com/red/red/blob/master/modules/view/backends/windows/rules.red#L16) rule. Those rewritting rules are active by default and defined specifically for each GUI platform (e.g. [rules for Windows](https://github.com/red/red/blob/master/modules/view/backends/windows/rules.red)).

If they interfere in any way with user code, they can be easily disabled:
* fully: `system/view/VID/GUI-rules/active?: no`
* specifically: `remove find system/view/VID/GUI-rules/OS/Windows 'color-backgrounds`
