### ISSUE TITLE
[View] Calendar doesn't focus itself on clicks

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5307]
**Describe the bug**

`view [field calendar]` after clicking focus stays in the field:
![](https://i.gyazo.com/ce40aac8a2c95cf62bdf5b18af40450b.gif)

`view [field calendar focus]` handles key events when focused manually:
![](https://i.gyazo.com/e2c2936f8e2d3b0782a353bbdff47d91.gif)

Bug is Windows-specific

**Expected behavior**

`calendar` gets focus on click

**Platform version**
```
-----------RED & PLATFORM VERSION----------- 
RED: [ branch: "master" tag: #v0.6.4 ahead: 4667 date: 9-Apr-2023/3:24:34 commit: #d36108eeffeafbf14839b5a9cadc9a0acd87f34a ]
PLATFORM: [ name: "Windows 10" OS: 'Windows arch: 'x86-64 version: 10.0.0 build: 19044 ]
--------------------------------------------
```

**Comment by qtxie** [comment]
> Calendar doesn't focus itself on clicks

This is the default behavior on Windows. Need to be handled manually.

**Comment by hiiamboris** [comment]
> the default behavior on Windows

@qtxie is this documented on MSDN somewhere?

**Comment by qtxie** [comment]
@hiiamboris I checked some GUI frameworks, they subclass the control and handle the CLICK manually. I don't find any docs about it. I guess MS don't care. Nowadays you can rarely find an APP which use this native calendar control.

**Comment by hiiamboris** [comment]
I still think if it accepts keyboard focus it should focus itself on clicks, just for consistency across widgets and platforms. Though it's of low importance indeed.

**Comment by qtxie** [comment]
@hiiamboris Sorry. I mean the GUI frameworks handle it manually, not the users. This issue is fixed in Red View.
