### ISSUE TITLE
Wrong place for this as usual. Also you haven't demonstrated the rationale for the new keyword, since set-word already works.

### ISSUE THREAD

**Issue by GiuseppeChillemi** [red/red#5338]
>> Wrong place for this as usual. Also you haven't demonstrated the rationale for the new keyword, since set-word already works.

I have tried to search the correct place but I have not found it. Could you point me where it is written the link?

**Comment by GiuseppeChillemi** [comment]
Please close this issue, as I remember I have replied and not opened a new one.

**Comment by hiiamboris** [comment]
https://github.com/red/REP
