### ISSUE TITLE
Design fault of LOADing DATEs

### ISSUE THREAD

**Issue by endo64** [red/red#5345]
**Describe the bug**
`LOAD`ing date values has a design fault and makes it untrustable.

> year and day fields are interchangeable, but only for low year values.

[Link](https://github.com/red/docs/blob/master/en/datatypes/date.adoc#22-runtime-creation)

Conversations on [Gitter](https://matrix.to/#/!mjbZGzLqlsqlDLaQVP:gitter.im/$OpVjizYTvUwbLDcyEcYnQfC5jhDBG_RzzFVfhb3jjr0?via=gitter.im&via=matrix.org&via=tchncs.de)

**To reproduce**

```red
>> 11-nov-13
== 11-Nov-2013
>> 12-nov-13
== 12-Nov-2013
>> 13-nov-13
== 13-Nov-2013
>> 14-nov-13
== 13-Nov-2014
>> 15-nov-13
== 13-Nov-2015
```

**Expected behavior**
Consistent use of argument positions.

**Platform version**
Red 0.6.4 for Windows built 20-Feb-2023/10:53:57-04:00  commit #bd5bc29

**Comment by dockimbel** [comment]
It's a bug, Expected results are:

```
>> 14-nov-13
== 14-Nov-2013
>> 15-nov-13
== 15-Nov-2013
```

**Comment by dockimbel** [comment]
The related docs were fixed also accordingly.

**Comment by hiiamboris** [comment]
What about 
> year and day fields are interchangeable, but only for low year values.

Did you mean "for *high* year values" instead?

**Comment by dockimbel** [comment]
Forgot it, it's fixed now, thanks.
