### ISSUE TITLE
red-view binaries do not work on MacOS 13.4 Ventura

### ISSUE THREAD

**Issue by rozek** [red/red#5359]
**Describe the bug**

well, the title already states it: both the precompiled binary for [CLI Red](https://static.red-lang.org/dl/auto/mac/red-31jul23-40096dd12) and [GUI Red](https://static.red-lang.org/dl/auto/mac/red-view-31jul23-40096dd12.zip) do not work on my Macbook Air M2 running MacOS 13.4 Ventura

**Comment by greggirwin** [comment]
Not a bug. Red is still 32-bit only.

**Comment by rozek** [comment]
well, this means that I will not be able to run RED on a modern Mac at all?

Because of the message `bad CPU type in executable` I tried to install Rosetta 2 (softwareupdate --install-rosettav`) but RED still refused to start...

**Comment by hiiamboris** [comment]
Dude, there's this "search" thing in Github issues :)
Which reveals https://github.com/red/red/issues/5087 https://github.com/red/red/issues/4889 https://github.com/red/red/issues/4359

**Comment by rozek** [comment]
damn...I did not remove the "is:open" filter from the search field - and ignored the "# closed" hint.

Sorry!
