### ISSUE TITLE
`max` native does not honor NaN comparison rules

### ISSUE THREAD

**Issue by dockimbel** [red/red#5362]
```
>> min 1.0 1.#nan
== 1.#NaN
>> max 1.0 1.#nan
== 1.0
```
Should be `1.#NaN` in both cases, see: https://en.wikipedia.org/wiki/NaN#Comparison_with_NaN

Issue is caused by [this line](https://github.com/red/red/blob/master/runtime/natives.reds#L3298), such higher-level flag overrides the NaN comparison result.

**Comment by hiiamboris** [comment]
Doesn't work on points yet.
```
>> about
Red 0.6.4 for Windows built 11-Aug-2023/5:27:21+03:00  commit #baa93a6
>> min (1,1) (1.#nan,1.#nan)
== (1, 1)
>> max (1,1) (1.#nan,1.#nan)
== (1, 1)
```

**Comment by qtxie** [comment]
What should return for those cases and why?
```
min (1,1.#nan) (1.#nan,1.#nan)
min (1,1.#nan) (1.#nan,1)
```

**Comment by hiiamboris** [comment]
(1.#nan, 1.#nan), for consistency with 1D math.

**Comment by qtxie** [comment]
That's odd to get a point! which different than the two being compared. It's worse for point3D!.
```
min (1, 1.#nan, 1) (1.#nan, 1, 1)
```

**Comment by hiiamboris** [comment]
```
>> min (1, 1.#nan, 1) (1.#nan, 1, 1)
== (1.#nan, 1.#nan, 1)
```

**Comment by hiiamboris** [comment]
We either propagate NaN everywhere (as we have chosen), or ignore it everywhere. There shouldn't be different shades of grey for every function.

**Comment by hiiamboris** [comment]
> which different than the two being compared

It was always the case with min/max:
```
>> min (1,4) (2,3)
== (1, 3)
```

**Comment by qtxie** [comment]
> > which different than the two being compared
> 
> It was always the case with min/max:
> 
> ```
> >> min (1,4) (2,3)
> == (1, 3)
> ```

OK. Didn't notice that.

**Comment by dockimbel** [comment]
@qtxie Can this ticket be closed now?
