### ISSUE TITLE
Transcode on file! scans different than previous Red version

### ISSUE THREAD

**Issue by mikeyaunish** [red/red#5365]
**Describe the bug**
Transcode on file! produces a different sized token than previous Red version

**To reproduce**
1. Run the same transcode on different versions of Red.
```
>> about
Red 0.6.4 for Windows built 2-Aug-2023/17:10:02-06:00  commit #2c0a400
>> transcode/trace "%hello.txt" func [event input type line token] [?? token true]
token: 1x11
token: 1x12
token: %hello.txt
== [%hello.txt]
```

```
>> about
Red 0.6.4 for Windows built 7-Jun-2023/13:38:46-06:00  commit #01ab176
>> transcode/trace "%hello.txt" func [event input type line token] [?? token true]
token: 1x11
token: 1x11
token: %hello.txt
== [%hello.txt]
```
2. Notice the token size is not the same.

**Expected behavior**
Token size as shown above for current version of Red should return 'token: 1x11' 

**Platform version**
RED: [ branch: "master" tag: #v0.6.4 ahead: 4893 date: 2-Aug-2023/23:10:02 commit: #2c0a40018c3b226226adc41eb7994d3989bc43a4 ]
PLATFORM: [ name: "Windows 10" OS: 'Windows arch: 'x86-64 version: 10.0.0 build: 19045 ]

**Comment by hiiamboris** [comment]
Note `12` is past tail

**Comment by dockimbel** [comment]
Probably related to #5351.
