### ISSUE TITLE
[Regression] Initial reactions get silently ignored sometimes

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5399]
**Describe the bug**

Consider this code:
`r: reactor [x: 1 s: {abc}] react [print ["reacted" i: r/x r/s/:i]]`

In `red-view-25nov22-e6ae842b4.exe`:
```
>> r: reactor [x: 1 s: {abc}] react [print ["reacted" i: r/x r/s/:i]]
reacted 1 a
== [print ["reacted" i: r/x r/s/:i]]
>> r/x: 2
reacted 2 b
== 2
```
In `red-view-26nov22-3b59a3ffc.exe` only subsequent changes are detected:
```
>> r: reactor [x: 1 s: {abc}] react [print ["reacted" i: r/x r/s/:i]]
== none
>> r/x: 2
reacted 2 b
== 2
```

**Expected behavior**

Initial reaction should fire as well.

**Platform version**
```
Red 0.6.4 for Windows built 7-Oct-2023/15:51:08+03:00  commit #0c72515
```

**Comment by dockimbel** [comment]
From top of my head, that's not a bug, it was an intended change, to avoid firing reactions on initial internal values setting during the creation of the reactor object, as that could cause unwanted side-effects.

**Comment by greggirwin** [comment]
In this example, the reactor object has been created, so this seems like a bug. We have `react/later` if you don't want it to trigger.

**Comment by dockimbel** [comment]
Indeed, it was a silly regression caused by a refactoring of `react` implementation.
