### ISSUE TITLE
VID `focus` option does not work inside a panel.

### ISSUE THREAD

**Issue by dockimbel** [red/red#5428]
Focusing using VID `focus` option does not work if the face is inside a `panel` or `group-box`.

Example:
```
view [panel [field focus]]
```
No focus in field when displayed.

It is a regression caused by the [fix](https://github.com/hiiamboris/red/commit/d2f50a46d28180d7e550a19bbadc253fe6857fb7) to #4321.

**Comment by dockimbel** [comment]
@hiiamboris Why did you change the focus handling code in [this commit](https://github.com/hiiamboris/red/commit/d2f50a46d28180d7e550a19bbadc253fe6857fb7)?

**Comment by hiiamboris** [comment]
You have one focus per `layout` call, it can't be global.

**Comment by dockimbel** [comment]
I've changed the implementation to a cleaner and hopefully, more robust version.
