### ISSUE TITLE
On Windows, Red added to the path, can't be run from another folder on cmd

### ISSUE THREAD

**Issue by SoleSoul** [red/red#543]
## Summary

Red can't be run from a different path on Windows.
## How to reproduce
- Put red.exe in a folder that is in the path
- On the command line, navigate to another folder (not the one where red.exe is)
- type 'red'
## Expected behavior

The Red interpreter should run.
## Observed behavior

c:>red
PROGRAM ERROR: Invalid encapsulated data.

**Comment by AJMansfield** [comment]
I had this same issue when I was trying to get sublime text to use red as a build system on Ubuntu 15.04.
My solution was similar; I created a shell script like this:
```bash
#!/bin/bash
red $@
```
and called that instead.

**Comment by cdokolas** [comment]
For the Windows batch file, I'd add a `@` in front, like this:
```
@"%~dp0red-exe.exe" %*
```
The way I've actually used it is by dropping the executable to my `C:\Utils\` folder (it's in the `PATH` variable) and also creating a `red.bat` file there with `@"%~dp0red-063.exe" %*` in it (I kept the original filename to keep track of the version I'm using).
