### ISSUE TITLE
Some lexer tracer's deadlock scenarios

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5444]
**Describe the bug**

Quoting docs:
> If an error event is ignored, the input does not advance automatically, it’s up to the callback function to set the input series to the right position for resuming the processing. Failure to do so can result in infinite loops.

So only `error` event may need manual advancement if ignored. Other events are expected to continue regardless of the value returned by the tracing function.

However lexer often deadlocks when tracer returns `false`. I don't have a full picture of these cases, but accidentally found a few:

**To reproduce**

Run any of these snippets:
```
transcode/trace "a/b:" func [e i t l k] [
	[open close]
	print [e tab k tab mold i]
	e = 'close
]
```
```
transcode/trace "a/b: " func [e i t l k] [
	[open close]
	print [e tab k tab mold i]
	no
]
```
Lexer will deadlock internally, never reaching the trace function again. Results respectively are:
```
open    1x1     "a/b:"
close   3x4     ":"
```
```
open    1x1     "a/b: "
close   3x4     ": "
```

**Expected behavior**

Should continue lexing, dropping values, as documentation states `false : drop` for these events:

<img width=600 src=https://link.storjshare.io/raw/jxfnjjold7d4xtoupll4mp7ychkq/img/HtFfF8h.png />

**Platform version**
```
Red 0.6.4 for Windows built 22-Nov-2023/17:24:25+03:00  commit #34f26df
```

**Comment by hiiamboris** [comment]
Also I don't know if it's a bug or by design but I expected lexer to report `1x3` and `1x4` pairs on `CLOSE` events here:
```
>> transcode-trace "a/b"
PRESCAN  path!        1x2          1    "a/b"
OPEN     path!        1x1          1    "a/b"
SCAN     word!        1x2          1    "/b"
LOAD     word!        a            1    "/b"
PRESCAN  word!        3x4          1    ""
SCAN     word!        3x4          1    ""
LOAD     word!        b            1    ""
CLOSE    path!        3x4          1    ""
== [a/b]
>> transcode-trace "a/b:"
PRESCAN  path!        1x2          1    "a/b:"
OPEN     path!        1x1          1    "a/b:"
SCAN     word!        1x2          1    "/b:"
LOAD     word!        a            1    "/b:"
PRESCAN  word!        3x4          1    ":"
SCAN     word!        3x4          1    ":"
LOAD     word!        b            1    ":"
CLOSE    set-path!    3x4          1    ":"
== [a/b:]
```
Otherwise user has to make own stack of opens and closes.

**Comment by dockimbel** [comment]
> Expected behavior:  Should continue lexing, dropping values, as documentation states false : drop for these events:

The documentation also adds in the "Notes" section below that table:
> If an open event is dropped, the corresponding close event should also be dropped.

**Comment by hiiamboris** [comment]
Didn't notice :)
What should happen if I don't follow this guideline?
I expect lexer should generate an error event about unclosed bracket (or what should it be in the path case?)

**Comment by dockimbel** [comment]
Undefined behavior for now. I'm looking into it to see if it can be improved.

**Comment by hiiamboris** [comment]
To drop an `open` event I think should mean that we don't enter a new series and continue loading into the same series.

**Comment by dockimbel** [comment]
That's the case already. See this [example](https://github.com/red/code/blob/master/Scripts/lexer/flatten.red).

**Comment by hiiamboris** [comment]
So to actually drop a list we need to open it as `true` and close as `false`, right? Because if it's opened as `false` then it will be separate values already appended. And open as `false` + close as `true` makes no sense for lists? Does it make sense for strings?

Something to be documented there, as it's unclear.

**Comment by dockimbel** [comment]
The fix avoids the deadlock by raising an error event if the returned values for `open` and `close` events do not match.

**Comment by hiiamboris** [comment]
Now it does:
```
transcode/trace "a/b: " func [e i t l k] [
	[open close]
	print [e tab k tab mold i]
	no
]
```
```
open    1x1     "a/b: "
close   3x5     " "
*** Syntax Error: (line 1) invalid path at a/b:
*** Where: transcode
*** Near : transcode/trace "a/b: " func [e i t l k]
*** Stack:
```
Why invalid?
