### ISSUE TITLE
cannot set on-change* field to none! datatype

### ISSUE THREAD

**Issue by GiuseppeChillemi** [red/red#5466]
**Describe the bug**

SECOND ERROR

As before, I was trying to duplicate a function context. I used a different MAKE-SKELETON and also a different line in the main function. This caused another kind of error duplication on a context of a word not inside the function used as a mistake

```
** Script Error: cannot set on-change* field to none! datatype
*** Where: make
*** Near : f-self: make object! make-skeleton words-of 
*** Stack: make-extra 
```

**To reproduce**

Run this code:

```
make-skeleton: func [
	"Creates an empty object prototype providing its words"
	words  [block!]  "the words or set-words of the object"
	/local 
	s
	out-data 
	word 
	] [

	s: system/words
	out-data: s/copy []
	if not s/empty? words [
		forall words [
			word: s/first words
			either not any [word? word set-word? word] [
				make error! rejoin ["word: > " word " < is not of word type"]
			] [
				append out-data to-set-word word
			]
		]
		append out-data none
		
	]
	out-data
]


make-extra: func [
       "Creates the /extra field in faces"
	data 
	col
	gui-cfg
	data-cfg
	/libs
	validation-libraries
	/id
	field-id
	f-self
] [
	f-self: make object! make-skeleton words-of context? 'x ;<<<----------
	set f-self reduce words-of context? 'x
;...remaining code omitted
] 

make-extra a: 1 b: 2 c: 3 d: 4
```

**Platform version**
```
RED: [ branch: "master" tag: #v0.6.4 ahead: 5087 date: 14-Jan-2024/8:37:32 commit: #7e50e5d36ac35668c5e8d43f15af804318af6570 ]
PLATFORM: [ name: "Windows 11" OS: 'Windows arch: 'x86-64 version: 10.0.0 build: 22621 ]
```

**Comment by hiiamboris** [comment]
Same [comment](https://github.com/red/red/issues/5465#issuecomment-1892751122) here

**Comment by GiuseppeChillemi** [comment]
Here is the short version.

```
make-extra: func [

	field-id
	f-self
] [
	f-self: copy context? 'x
	set f-self reduce words-of context? 'x
] 

make-extra 1 2
```

**Comment by dockimbel** [comment]
First, you cannot start a ticket with "SECOND ERROR  As before, [...]". That makes no sense. A ticket must be **_self-contained_** and **_self-explanatory_**. A ticket is not a chapter in a book. If it relates to another one, that can be added in the description, but **_cannot replace_** a proper description.

Second, there is no issue in the "short version". You are just trying to set a word to an unset value without using `set/any`...

```
>> w: words-of system/words
== [datatype! unset! none! logic! block! paren! string! file! url! char! integer! float! symbol! ...
>> set/any first find w 'on-change* ()
>>
```

Third the error and its location in the first example do not match with the second example! Attempting to set an event handler in an object at creation time, to a non-function value is currently not allowed:

```
>> o: context [on-change*: none]
*** Script Error: cannot set on-change* field to none! datatype
*** Where: make
```

**Comment by GiuseppeChillemi** [comment]
Thank you for the answer. The 'on-change*' error was for me suspicius and it is still so. It seems that it belongs to `COPY` code of the context inner fields that do not check for unset value. In fact, you can genate the error with just `COPY`

```
copy-problem: func [
	/local
	ctx
] [
	ctx: copy context? 'x
] 

copy-problem
```

**Comment by dockimbel** [comment]
1. You do not need to wrap such code in a function to show the error:
```
>> copy context? 'x
*** Script Error: cannot set on-change* field to unset! datatype
*** Where: copy
*** Near : copy context? 'x
*** Stack: 
```

2. This is the expected behavior. `copy` on an object will copy the context, then fill it with the values from the prototype object. When it reaches the `on-change*` field, it will try to set it to `unset` and get rejected because of the above mentioned rule.

**Comment by GiuseppeChillemi** [comment]
Thank you, waiting for it to change as the only way to safely copy a whole context is:
``` 
set/any copied-ctx: copy words-of context? 'x values-of context? 'x
```
As it seems quite slow setting each word one by one.
