### ISSUE TITLE
[Regression] More aftershocks from #5253

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5513]
**Describe the bug**

Coming from https://github.com/red/red/commit/5195586f4fbba248092a11893476d76717e4491e#commitcomment-143298002 , a quick breakage scenario:
```
view collect [
	repeat y 8 [
		repeat x 8 [
			keep [
				base white 60x60 rate 67 on-time [
					t: 6 * pick now/precise 'second
					face/draw: compose [
						line 30x30 (30 * ((1,1) + as-point2D negate sine t cosine t))
					]
				]
			]
		]
		keep 'return
	]
]
```

**Expected behavior**

Should be realtime, but it's 1 frame per second per base :)

**Screenshots**

In red-view-07mar24-5a39a7a32:

<img width=400 src=https://github.com/red/red/assets/25307049/4d8e8f3b-d882-4bb4-8ed5-385cb5098e10 />

In red-view-19jun24-5195586f4:

<img width=400 src=https://github.com/red/red/assets/25307049/dbdfb165-71b1-4436-8df7-f6d3e823fd0a />

**Platform version**
```
-----------RED & PLATFORM VERSION----------- 
RED: [ branch: "master" tag: #v0.6.5 ahead: 167 date: 19-Jun-2024/9:28:23 commit: #5195586f4fbba248092a11893476d76717e4491e ]
PLATFORM: [ name: "Windows 10" OS: 'Windows arch: 'x86-64 version: 10.0.0 build: 19045 ]
--------------------------------------------
```

**Comment by hiiamboris** [comment]
I also wonder if the fix for #5512 actually avoids the OS freeze or reduces the chance of it by the factor proportional to the fps reduction.

**Comment by dockimbel** [comment]
On `font-gc` branch, it's realtime! 

![5513](https://github.com/red/red/assets/411393/bc9cb73b-cf6b-4ddb-be13-70cf2ca2903d)

**Comment by hiiamboris** [comment]
> On `font-gc` branch, it's realtime!

Does that branch include the fix for #5253 ?

**Comment by dockimbel** [comment]
Nope.

**Comment by qtxie** [comment]
Hmm, I just realize that if all the base faces are non-transparent, it won't cause freeze.

**Comment by qtxie** [comment]
Pushed a new fix. Though we still have this slowness if mix normal base faces and semi-transparent base faces together. It's better than freeze the OS.
