### ISSUE TITLE
case, case/all and their returning values

### ISSUE THREAD

**Issue by gor77** [red/red#5517]
So, just a few examples I created while trying to learn _case_ and _case/all_. Comments are right below each case.

case [
    false true
    false true
]
;-- here, the result is _none_. 
;-- It makes sense if results of *condition* evaluation are being discarded (by discarded I mean evaluated to _none_) 

case/all [
    true true
    none true
]
;-- here, the result is _none_...

case/all [
    true true
    no true
    ]
;-- ...but here, it is _false_. 

case/all [    
    false true
    false true
]
;-- again, the result is _none_, I was expecting _false_. 
;-- Here, it acts like results of evaluation are being discarded (evaluated to _none_).

case/all [
    true true
    false false
]
;--The result is false - here it acts like the last condition wins (it's obviously **not** discarded)

So the idea is: if I know the rules, simply by looking at case block (or case/all), 
I should unambiguously know what the end result is going to be: will it return _false_, or _none_. 

But is it possible to know that now?

**Comment by hiiamboris** [comment]
So the bug here is that `case/all` returns `false` instead of `none` if last condition evaluates to `false`.

**Comment by hiiamboris** [comment]
Sister bug: https://github.com/red/red/issues/4899
Loop return values are of some relevance: https://github.com/red/red/issues/1706#issuecomment-660306764 https://github.com/red/red/issues/3158#issuecomment-539618980 as well as `any/all` return values https://github.com/red/REP/issues/85

**Comment by gor77** [comment]
So, as a general rule: is it safe to say that the correct behavior (when the bug is fixed) of _case_ and _case/all_  is such that the results of evaluation of **conditions**  is **always** discarded?

In other words, result of evaluation of any **condition** should never "slip through" and become the end result of 
case (or case/all), it is just being used for making decision whether to execute corresponding block or not.

I know this might seem naive, but Red is so much different that I'm really not sure about anything anymore.

**Comment by dockimbel** [comment]
After the fix, if no condition is met (`case`) or ending condition is `false` (`case/all`), the returned value will be `none`. In all other cases, the last evaluated value is returned.
