### ISSUE TITLE
Why does the output of the pwd function not have a line break effect in the gui console?

### ISSUE THREAD

**Issue by ScriptGo** [red/red#5526]
![Screenshot_2024-07-13_25991](https://github.com/user-attachments/assets/21112563-349a-4554-a967-be2fccfbd455)

**Comment by dockimbel** [comment]
Good catch, looks like a regression.

**Comment by dockimbel** [comment]
@qtxie There's something odd with the CLI console output, it does not honor `prin` and adds an extra LF. Once that fixed, we can replace `prin` by `print` in `pwd`.
