### ISSUE TITLE
[Compiler] `return` escapes `try/all`

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5535]
**Describe the bug**

https://github.com/red/red/commit/09d5aa3e2bdf9a43f5a3d2d1ec54a1a970059ac3#commitcomment-145380888
When compiled, `return` escapes the `try/all` block. The bug is abused in the current `attempt` implementation.

**To reproduce**

1. Compile and run this script without `-e`:
```
Red []

f: does [try/all [return 1] 2]
probe f
do [
	f: does [try/all [return 1] 2]
	probe f
]
```
2. Output is:
```
1
2
```

**Expected behavior**

```
1
1
```

**Platform version**
`Red 0.6.5 for Windows built 2-Jul-2024/1:21:21+08:00  commit #bbecb7e`

**Comment by dockimbel** [comment]
@hiiamboris The expected behavior should be
```
2
2
```
right?

**Comment by hiiamboris** [comment]
Oh right, my mistake 😅
