### ISSUE TITLE
DO-FILE hides evaluation stack from errors

### ISSUE THREAD

**Issue by hiiamboris** [red/red#5553]
**Describe the bug**

Example script output:
```
*** User Error: error message
*** Where: do
*** Near : do make error! e
*** Stack: do-file
```
I can only tell that the error generating function was called at someplace, but not where, not even in what file.

**To reproduce**

1. Save these scripts:
- `1.red`:
   ```
   Red [] do %2.red
   ```
- `2.red`:
   ```
   Red []
   e: func [e] [do make error! e]
   f: does [g]
   g: does [e "error message"]
   f
   ```
2. Run `1.red`
3. Observe the vague error report shown above

**Expected behavior**

Since `where` and `near` become non-informative when an error generating expression is used, stack trace is the only clue left. `do-file` shouldn't hide it.

**Platform version**
`Red 0.6.5 for Windows built 23-Oct-2024/2:43:13+07:00  commit #17c374f`

**Comment by hiiamboris** [comment]
Non-informative, because it doesn't point at the place where the actual error has happened. Only to an expression in an error-raising function (wrapper), where `do make error!` is by design.

**Comment by dockimbel** [comment]
Compiled `try` was not honoring the `/keep` refinement, that was fixed in the commit.

About input files tracking, it might be possible to extend `do-file` to track them and make them available to the error object when created somehow... I will look into it.

**Comment by dockimbel** [comment]
Now you'll get:
```
*** User Error: error message
*** Where: do
*** Near : do make error! e
*** Stack: do-file do-file f g e
*** Files: %1.red %2.red
```
The source files reporting is a bit raw, but at least the info is there and should be useful in big codebases. Only scripts run by `do` are tracked.
