### ISSUE TITLE
Using ? keep does not find any documentation information for the keep function

### ISSUE THREAD

**Issue by ScriptGo** [red/red#5570]
```red
>> ? keep
No matching values were found in the global context.
```

Platform version

`Red 0.6.5 for Linux built 29-Nov-2024/4:56:25+08:00  commit #a691592`

**Comment by gurzgri** [comment]
`keep` is only defined in `collect` contexts.

```Red
>> collect [help keep]
```

**Comment by ScriptGo** [comment]
> `keep` is only defined in `collect` contexts.
> 
> ```red
> >> collect [help keep]
> ```

It can't be used alone?

**Comment by hiiamboris** [comment]
@ScriptGo please ask questions in [red/help](https://matrix.to/#/%21wUTlqkqOhNGtfQzIsO%3Amatrix.org?via=gitter.im&via=matrix.org&via=nitro.chat) or [red/bugs](https://matrix.to/#/%23red_bugs%3Agitter.im?via=gitter.im&via=matrix.org&via=nitro.chat) before posting new issues on GitHub
