### ISSUE TITLE
insert/part & append/part to index broken

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#580]
red>> b: next a: [1 2 3]
== [2 3]
red>> append/part c: [] a b
== [1 2]
red>> c
== [1 2]
red>> b: next a: "123"
== "23"
red>> append/part c: "" a b
== "12"
red>> c
== "12"

In other cases the deviation is more than one position.

**Comment by iArnold** [comment]
I cannot find any use of the series (let alone pair!) in R3 documentation. Testing some more on try,rebol.nl
a: [1 2 3 4 5 6 7 8 9 0 11 12 13 14 15 16]
b: next next a
append/part c: [] a b
Has a result in R3
a: [1 2 3 4 5 6 7 8 9 0 11 12 13 14 15 16]
b: [12 3 6]
append/part c: [] a b
Also fails for R3. 
So 
a. I wonder what it should do
b. Wonder who will use it (and what for) 
c. there will be a workaround for such a use case.
d. It is R3 functionality, not even R2, and on top of all
e. it is afaiac undocumented.

?
