### ISSUE TITLE
(KEEP) COPY empty inconsistent

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#603]
red>> parse " " [collect [keep copy x " "]]
== [" "]
red>> parse "" [collect [keep copy x ""]]
== []
red>> x
== " "
red>> parse "" [collect [keep copy x 0 skip]]
== []
red>> x
== ""

I would expect COPY to always yield a string!, including an empty string on matching an empty string.

**Comment by dockimbel** [comment]
KEEP will now accept empty series from COPY.
