### ISSUE TITLE
object! iteration missing

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#617]
red>> foreach [x y] context [a: 'b] [?? x ?? y]

**\* Runtime Error 1: access violation
**\* at: 0809C4B1h

R3:

> > foreach [x y] context [a: 'b] [?? x ?? y]
> > x: a
> > y: b
> > == b

**Comment by dockimbel** [comment]
I think it is worth considering the addition of `/into` refinement to all `*-of` accessors, as they are producing a new block (except `body-of` on functions). In such case, iterating over objects directly will not be needed anymore.

**Comment by dockimbel** [comment]
Closing this ticket, as object semantics will be reexamined in the language spec work and iterability will be considered.
