### ISSUE TITLE
Refinement may start with digit, its use is problematic

### ISSUE THREAD

**Issue by meijeru** [red/red#650]
Simplest example:

f:  func [/1][]
f/1

This gives a compiler internal error in comp-call

**Comment by rebolek** [comment]
Still problem in 0.6.1:

Interpreter
---

```
red>> f: func [/1][]
== func [/1][]
red>> f/1
*** Script Error: f has no refinement called 1
*** Where: f
red>> ? f

USAGE:
    f  /1
ARGUMENTS:

REFINEMENTS:
     /1
```

Compiler
---

Compiles without errors, when run, throws this message:

```
*** Script Error: path none is not valid for unset! type
*** Where: probe
*** Stack: set func probe
```

**Comment by endo64** [comment]
`Script Error: f has no refinement called 1` on interpreter, but I see no error on compiled executable.

**Comment by hiiamboris** [comment]
`1.red`:
```
Red []
f: func [/1]
probe f/1   
```

```
> red "1.red"
*** Script Error: f has no value
*** Where: probe
*** Stack: probe
```

```
> red -c "1.red" & 1.exe
...
*** Runtime Error 1: access violation
*** at: 1003C218h
```
W7

**Comment by endo64** [comment]
@hiiamboris Where is your function's body?
Could you test with this one on W7?

```
Red []
f: func [/1][print "ok"]
f/1
```

**Comment by hiiamboris** [comment]
@endo64 right, didn't see that at night ☺ This ticket only requires compiler to report a malformed refinement just as interpreter does.

**Comment by 9214** [comment]
Were there any design ideas on how numeric refinements can be leveraged from a language design perspective?

**Comment by hiiamboris** [comment]
There's a use case in CLI library - to support `-9`-like arguments without workarounds. Not very important. It's actually possible to get the value of that refinement with `get /1`, but no way to provide it to the function.

Regardless of possible design space this may open, I'd more like refinements and any-words to be safely convertible to one another.

**Comment by greggirwin** [comment]
It falls into the That's Funny area, where we use numbers in paths, but say that refinements are words, and words can't start with numbers. So, to look at them superficially, it seems like it should almost all just work, like you could use `key: /2` and use that in a path as a `get-word!` segment. Humans wanting things to be easy is why we have dynamic languages and type coercion/polymorphism. But when things break down, it can become a train wreck rather than a single car accident.

As with the `issue!` word-v-string design, my gut says that even though we can dream up use cases, this is one that we should disallow. I'm willing to be convinced by a strong argument though.

**Comment by 9214** [comment]
To be clear, I asked for cases where such refinements are used (or can be used) in function calls; [De Bruijn indices](https://en.wikipedia.org/wiki/De_Bruijn_index) and inverses/obverses come to mind.

```red
increment/-2 3 → 1 ; inverse 2 times 
increment/0  0 → 0 ; identity
increment/3  4 → 7 ; apply 3 times
```

I personally used numeric refinements at least once as keys in a sort-of-a-dialect. And it's like with most of the datatypes, you have to fit them in your program's design and pick whose with the best intentionality. That also means that some of the Red datatypes are underleveraged, IMO `refinement!` is one of them.

**Comment by hiiamboris** [comment]
To use something like this you would have to define **all** the possible numbers as refinements to your function + be able to evaluate get-words into refinements before a function call. Right?

**Comment by Oldes** [comment]
It's still there:
```
>> /1
== /1
>> about
Red 0.6.4 for Windows built 18-Nov-2020/3:13:59+01:00 commit #8ee5a9f
```

**Comment by 9214** [comment]
@Oldes the ticket is concerned with numeric refinements in function's spec only.
