### ISSUE TITLE
large and not so large number math return unexpected results

### ISSUE THREAD

**Issue by shishini** [red/red#710]
red>> 27847278432473892748932789483290483789743824832478237843927849327492 \* 4932948478392784372894783927403290437147389024920147892940729142
== 1328642520
red>> 74789 \* 849032
== -926255192

The above results are obviously wrong,
it would be best of course if red can handle bignumbers
but if not, at least raise an error

**Comment by rebolek** [comment]
Current 0.6.1 behaviour:
```
red>> 27847278432473892748932789483290483789743824832478237843927849327492 * 4932948478392784372894783927403290437147389024920147892940729142

== 1.373691897708523e131
red>> 74789 * 849032
*** Math Error: math or number overflow
*** Where: *
```

Not consistent, IMO. It should works or error out for both cases.

**Comment by hiiamboris** [comment]
I disagree.
27847278432473892748932789483290483789743824832478237843927849327492 and such literals are loaded as a float64. Multiplying them is another float64.
74789 and 849032 literals are loaded as integers, and multiplying them is expected to be an integer. So an overflow is expected.

Fighting a silent integer to float promotion will be difficult. While manual promotion when one really requires it is as simple as `74789 * to-float 849032`.
