### ISSUE TITLE
String corruption with control characters

### ISSUE THREAD

**Issue by kealist** [red/red#715]
I saw some string corruption today with odd control characters.

```
red>> append "blah" "blah^2"
== "blah2"
```

**Comment by rebolek** [comment]
Currently the results are inconsistent between interpreter and compiler:

0.6.1 console behaviour: 
```
red>> append "blah" "blah^2"
== "blahblah2"
```

0.6.1 compiled behaviour:
```
; append "blah" "blah^2"
; "blahblah^^2"
```

**Comment by bitbegin** [comment]
https://github.com/red/red/pull/3633 will be good fix for this?

**Comment by bitbegin** [comment]
if it's ok, i will add some tests

**Comment by hiiamboris** [comment]
@bitbegin I think it may make more sense to fix https://github.com/red/red/blob/master/lexer.r (compiler behavior). For consistency with R2 and R3 (they skip single caret chars when they don't make a proper escape sequence).

**Comment by greggirwin** [comment]
@bitbegin tests aren't passing for your PR, so that would need to be addressed first.

From the historical messages, if it's only the compiler that now has the issue, we should compare %lexer.r and %lexer.red for how each handles this.

**Comment by meijeru** [comment]
In the specs document it reads: "[...] `^` will be ignored in front of any single character with which it does not form (the beginning of) an `<escaped-character>` or `<hexadecimal-codepoint>`. Thus e.g. `^3` yields the same as `3`." This behaviour would be consistent  with R2/3, and the lexers could be adapted accordingly.
