### ISSUE TITLE
In words case is significant for non-ascii characters

### ISSUE THREAD

**Issue by IngoHohmann** [red/red#719]
Case is significant for non-ascii characters:

    red>> ä: 1
    == 1
    red>> Ä
    *** Error: word has no value!

But it is not significant for ascii characters:

    red>> a: 1
    == 1
    red>> A
    == 1

I know, this is a deep issue, and maybe opening this now is premature

**Comment by dockimbel** [comment]
We have a partial support for deeper Unicode features. Such code now runs fine:
```
red>> ä: 1
== 1
red>> Ä
== 1
```
