### ISSUE TITLE
lit-word variables decay to word when evaluated

### ISSUE THREAD

**Issue by hostilefork** [red/red#734]
```
>> x: quote 'foo 
>> probe append [] x
[foo]
```

A hassle when trying to build code blocks with lit-words in them programmatically.  Seems it would make more sense to return `['foo]`.  Note that lit-path variables do not decay to path in this way.

Rebol has this behavior for currently unknown reasons.  The [issue has been proposed for modification](http://curecode.org/rebol3/ticket.rsp?id=1434) there, and a pull request implementing it is pending.

**Comment by 9214** [comment]
Should be reopened because compiler still decays `lit-word!`s to `word!`s.
```red
probe quote 'foo
```
On a1d1495 results in:
```red
foo
```
