### ISSUE TITLE
Too large "integer!" literals are interpreted as "float!"

### ISSUE THREAD

**Issue by rmn64k** [red/red#751]
Too large `integer!` literals should cause an error but are instead converted to `float!`.
This example program prints `4.587245897644e+35`.

```
Red/System []
foo: 458724589764398757698437598437598347 
print [foo lf]
```

**Comment by hiiamboris** [comment]
This one has regressed: the output now is `4.58725e+035`

**Comment by dockimbel** [comment]
New fix pushed.

**Comment by hiiamboris** [comment]
@dockimbel you can uncomment https://github.com/red/red/blob/fc202572458b6e9e19b4fe11ee9f1c79d54fcb43/system/tests/source/compiler/regression-test-rsc.r#L1178-L1185
