### ISSUE TITLE
How to quote a path

### ISSUE THREAD

**Issue by meijeru** [red/red#817]
I tested the new `random` on a path value, which should be OK since a path is a series.

`random a/b/c` fails (of course) since `a/b/c` has no value
`random 'a/b/c` works, but when the elements are shuffled, they can come out like `b/'a/c`
`random quote a/b/c` does not contains lit-words, as intended

Conclusion: a lit-path value is differently treated from a quoted path. In REBOL 2, both are treated equally by `random`, but the result is a block value in both cases!

I would expect Red to treat a quoted path and a lit-path equally as far as possible.  However, currently:

`same? 'a quote a` yields `true`, whereas
`same? 'a/b/c quote a/b/c` yields `false`

Admittedly, this also holds for REBOL 2...

**Comment by rebolek** [comment]
@dockimbel Is `random` expected to work on `path!`?
I get
```
red>> random 'a/b/c
*** Script Error: random does not allow path! for its value argument
*** Where: random
```
In Rebol, this works.

**Comment by meijeru** [comment]
It makes no sense, since the individual path items are not arbitrary: the first one is a HEAD, the subsequent ones are interpreted in the context of the previous ones. Swapping them around robs them of their significance.

**Comment by rebolek** [comment]
I agree it makes no sense, I was pointing out it’s possible in Rebol. I have no problem with this being not allowed in Red.
