### ISSUE TITLE
"workaround issues on 64-bit editions" needed in call.r

### ISSUE THREAD

**Issue by srpelissier** [red/red#842]
Hi. I changed lines 8 and 9 in `call.r` to the following then _kernel32.dll_ could be found. This is about Windows 7 64 bit and running red from the rebol/view console.

8:  `path: to-rebol-file get-env "SystemRoot"`
9:  `kernel32: load/library path/System32/kernel32.dll`

This did not seem worth a pull request. (Kindly) correct me if I am wrong.

Regards,

> sylvain

**Comment by dockimbel** [comment]
I am closing this ticket, as it does not describe an issue we can reproduce nowadays. If that issue can still be reproduced, please provide here all the detailed information to reproduce it, and we'll re-open this ticket.

**Comment by Oldes** [comment]
Actually it is still almost impossible to run `run-all.r` script on Windows, which would not stop responding. At least in regular Windows (not in VM). Just tested it now without success on Win10 with `REBOL/View 2.7.8.3.1 1-Jan-2011`. I guess we cannot do much with it as it will be Rebol's issue. Maybe port the test scripts to Red asap.

**Comment by dockimbel** [comment]
I don't trust 2.7.7 and 2.7.8 on Windows, I always use 2.7.6 and have no issue running the tests.

**Comment by Oldes** [comment]
@dockimbel I don't have 2.7.6 anymore... do you know a link where it's available?
