### ISSUE TITLE
NaN comparision doesn't follow IEEE754 spec.

### ISSUE THREAD

**Issue by qtxie** [red/red#847]
Using the code below to do the test.

```
Red []

foo-test: routine [][
    inf: 1e308 + 1e308
    nan: 0.0 * inf
    print-line inf
    print-line nan
    print-line ["inf > nan: " inf > nan]
    print-line ["inf < nan: " inf < nan]
    print-line ["inf <> nan: " inf <> nan]
    print-line ["inf = nan: " inf = nan]
]

foo-test
```

Results on Windows

```
1.#INF
-1.#IND
inf > nan: false
inf < nan: true                 ;@@ should be false
inf <> nan: false               ;@@ should be true
inf = nan: true                 ;@@ should be false
```

Results on ARM
On ARM (QEMU VM), we find that it doesn't generate INF and NaN, don't know why.

```
1.060479830104e-314             ;@@ should be INF ?
1.0607388627933e-314            ;@@ should be NaN ?
inf > nan: true
inf < nan: false
inf <> nan: true
inf = nan: false
```

```
```

**Comment by qtxie** [comment]
@dockimbel We already supported plan 2 now.

**Comment by hiiamboris** [comment]
look, more bugs came up (not `#inf`, normal numbers):
```
>> 1.0 < 1.#nan
== true
>> 1.#nan > 1.0
== false
>> 1.0 > 1.#nan
== false
>> 1.#nan < 1.0
== true
```
(all should yield `false`)

**Comment by qtxie** [comment]
> look, more bugs came up (not `#inf`, normal numbers):
> 
> ```
> >> 1.0 < 1.#nan
> == true
> >> 1.#nan > 1.0
> == false
> >> 1.0 > 1.#nan
> == false
> >> 1.#nan < 1.0
> == true
> ```
> 
> (all should yield `false`)
> 
> ```
> -----------RED & PLATFORM VERSION----------- 
> RED: [ branch: "master" tag: #v0.6.3 ahead: 703 date: 10-May-2018/3:19:55 commit: #7c5f402062ac67fbd6078592ca477bbe91a56f92 ]
> PLATFORM: [ name: "Windows 7 Service Pack 1" OS: 'Windows arch: 'x86-64 version: 6.1.1 build: 7601 ]
> --------------------------------------------
> ```

No more bugs. This issue has never been fixed.

**Comment by dockimbel** [comment]
```
>> 1.#nan >= 1.#nan
== true
>> 1.#nan <= 1.#nan
== true
>> 1.#nan <= 1
== true
>> 1.#nan >= 1
== true
>> 1 <= 1.#nan
== true
>> 1 >= 1.#nan
== true
```

**To reproduce**
```
1.#nan >= 1.#nan
1.#nan <= 1.#nan
1.#nan <= 1
1.#nan >= 1
1 <= 1.#nan
1 >= 1.#nan
```

**Expected behavior**

All false

**Platform version**
```
Red 0.6.4 for Windows built 11-Sep-2023/10:40:41+03:00  commit #def4b65
```
