### ISSUE TITLE
header case sensitive to compiler

### ISSUE THREAD

**Issue by WiseGenius** [red/red#884]
To the interpreter, the `Red` header is not case sensitive, but to the compiler `Red` and `Red/System` both are. So for each of the following headers, the compiler throws `*** Syntax Error: Invalid Red program`:

red []
RED []
ReD []
red/system []
RED/SYSTEM []
Red/system []
red/System []

**Comment by rebolek** [comment]
@dockimbel This bug should be reopened. The title says **"header case sensitive to compiler"** and that’s still true.

Example:
```
Red/system []
print "1"
```

Output:
```
*** Syntax Error: Invalid Red program
*** line: 1
*** at: {/system []
```
