### ISSUE TITLE
PRINT does not ignore UNSET values.

### ISSUE THREAD

**Issue by hostilefork** [red/red#901]
Red, like Rebol, will silently squelch unsets in COMPOSE (for example):

```
red> compose [10 (print "Hello") 20]
Hello
== [10 20]
```

In Rebol, this applies to PRINT as well.  In Red, the word "unset" appears:

```
red> print [10 (print "Hello") 20]
Hello
10 unset 20
```

I believe the preferable output in that case would be Rebol's output:

```
Hello
10 20
```

(I know this seems nitpicky but I am trying to build a new philosophy of PRINT, and you have asked for _complete_ proposals, so it's easiest to start with the "hopefully this is an agreement" parts in building that.)

**Comment by hiiamboris** [comment]
I think this has been fixed in Red 0.6.2. `form ()` now produces `""`, consistent with R3.
