### ISSUE TITLE
GET of compiled object method doesn't run

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#924]
```
c: context [
    f: does [print 'c/f]
]
; g: :c/f
g: get in c 'f
?? g
g
```

g: func [][print 'c/f]

When using the get-path! or when using `do [g]` you also get:

c/f

**Comment by hiiamboris** [comment]
Probably a closely related issue, although I think important to support:
```
b: context [ f: does ["B/F"] ]
g: func [x][ probe x/f ]

probe b/f
g b
```
Basically, I just pass an object as argument and wanna call it's method. In the interpreter it prints:
```
"B/F"
"B/F"
```
In the -c compiled mode:
```
"B/F"
func []["B/F"]
```
(Red 0.6.3 stable and 2018-3-26-44229, win7 x64)

**Comment by dockimbel** [comment]
@hiiamboris It's the same class of issues. The current compiler cannot recognize function calls expect for the most obvious cases. There is no way to achieve that without actually running the code and deciding _at runtime_ which value is a function call. As the compiler prefetches all arguments for function calls and builds stack frames statically, if it cannot statically recognize a function call at compile-time, then no call will be generated. I've devised a method that mixes static analysis and dynamic decision making for function calls under the term of "dynamic stack", but it proved to be overly complex to implement. This topic is left to be solved at a later stage of Red, where the role of the static compiler might be redefined.
