### ISSUE TITLE
Can't compile named context where /local follows /extern

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#930]
Red []

	c: context [
		f: function [
			/extern x
			/local y
		][
			x: 1
			set 'y 2
		]
	]

-=== Red Compiler 0.4.3 ===- 

*** Compilation Error: duplicate word definition in function: f 
*** near: [f: function [/extern x /local y] [x: 1 set 'y 2]]

The interpreter fails to make Y local:

== make object! [
    f: func [][x: 1 set 'y 2]
]

**Comment by dockimbel** [comment]
Compiled version works fine now.

**Comment by dockimbel** [comment]
Both compiled and interpreted version work fine now.
