### ISSUE TITLE
Vid app needs opening twice.

### ISSUE THREAD

**Issue by WiseGenius** [red/red#936]
Running %tests/android/vid.red on Android 2.3.4 on a Sony Ericsson Xperia Mini Pro (SK17i).

If I exit the vid app with the back button, I always have to tap on the app twice for it to open again. The first time always does nothing.

%eval.red doesn't have this issue.

**Comment by dockimbel** [comment]
I am closing those Android-related tickets, as the Android support has been deeply changed since then, and the old Android API binding code replaced.
