### ISSUE TITLE
Vid app terminates when tilted.

### ISSUE THREAD

**Issue by WiseGenius** [red/red#937]
Running %tests/android/vid.red on Android 2.3.4 on a Sony Ericsson Xperia Mini Pro (SK17i).

Changing between portrait or landscape mode (by tilting the screen or snapping the keyboard in or out) while the vid app is open terminates it. However, if I terminate the app this way, I only have to tap it once to open it again (unlike in #936).

%eval.red doesn't have this issue.

**Comment by dockimbel** [comment]
I am closing those Android-related tickets, as the Android support has been deeply changed since then, and the old Android API binding code replaced.
