### ISSUE TITLE
path! doesn't select string! from block!.

### ISSUE THREAD

**Issue by WiseGenius** [red/red#938]
path! doesn't select string! from block!.

	red>> b: [x y "x" "y"]
	== [x y "x" "y"]
	red>> b/('x)
	== y
	red>> b/("x")
	*** Error: invalid value in path!

**Comment by WiseGenius** [comment]
As expected, Red 0.5.1 now gives:

	red>> b: [x y "x" "y"]
	== [x y "x" "y"]
	red>> b/('x)
	== y
	red>> b/x
	== y
	red>> b/("x")
	== "y"

The compiler seems to be working too.
Should this issue now be closed?

**Comment by dockimbel** [comment]
Yes, forgot to close it, thanks for the reminder.
