### ISSUE TITLE
Compiler error on IF local object! path

### ISSUE THREAD

**Issue by Kaj-de-Vos** [red/red#968]
```
Red []

f: func [
    o [object!]
][
    if find o/a none []
]
```

**\* Compilation Error: expected a block for IF-BODY instead of word! value 
**\* near: [none []]

**Comment by dockimbel** [comment]
Good news, I have found a good candidate solution for this whole class of problems, affecting functions treated as keywords by the compiler. The compiler is currently doing some premature optimization by aggressively mapping those keywords to their closest Red/System counterparts, generating higher constraints at Red level. It is possible to detect cases where undetermined paths are involved and generate less optimized code (but still much faster than interpreted), relaxing the constraints on user code. :-)

Not sure in which release it will be implemented, but this is high priority, so it needs to be fixed asap.

**Comment by dockimbel** [comment]
The Red compiler can now compile such expressions but will assume a non-active `o/a` path, so if that evaluates to a function, it will not be called.  `do` can be used to enforce a call in such case if needed.

**Comment by meijeru** [comment]
Is this worth a warning in the documentation?

**Comment by greggirwin** [comment]
It's absolutely something we should note.
